### ISSUE TITLE
URL hash for item: javascript animation no working...

### ISSUE THREAD

**Issue by bebjakub** [metafizzy/isotope#1000]
Hi, Im testing URL hash for a isotope item http://codepen.io/kubooo/pen/WQgryJ
Its working, but I lost javascript animation feature...
Can you help me?
Thanks!

**Comment by desandro** [comment]
Try this http://codepen.io/desandro/pen/3cafad31c3dfb7031733cf2fdf148ddc/

**Comment by bebjakub** [comment]
Thanx :)

**Comment by bebjakub** [comment]
I checked it. Animation is working, also on click is selected just this item, great feature!
But when I go back in browser history, grid is with no change... :(

**Comment by bebjakub** [comment]
I think, that I fixed it http://codepen.io/bebjakub/pen/WQgryJ
