### ISSUE TITLE
How to avoid gaps using Isotope with Masonry layout sortby random

### ISSUE THREAD

**Issue by mattiaband** [metafizzy/isotope#1002]
I am using Isotope with Masonry layout and I noticed that sometimes leaves blank gaps between a box and the other (also if there is space to fit the other box).
But sometimes, if I refresh the page, it is all ok and it fills all the gaps. (for this reason I don't think it is a problem of css).
I use fluid dimensions for the items and I have the sortBy: random mode.
I think that my problem it is with this "random mode", infact if I delete 'sortBy: random' everything works fine.
so I would like to ask if, it is possible to keep the random mode, and fill the space available from top-left to the bottom-right?
in order to don't leave blank gaps.
I made a codepen to show you this strange behavior, http://codepen.io/mp1985/pen/epQJQL, if you refresh the page you can notice this issue.
any idea?
many thanks for all your brilliant work

**Comment by desandro** [comment]
If you're concerned about gaps, I recommend using the [Packery layout mode](http://isotope.metafizzy.co/layout-modes/packery.html). It's like Masonry, but it's designed to fill gaps.
