### ISSUE TITLE
Combination filtering checkbox's and dropdowns, inclusive to exclusive

### ISSUE THREAD

**Issue by EtienneRen** [metafizzy/isotope#1003]
Hi, This work is very amazing : http://codepen.io/desandro/pen/GFbAs

All works fine, but since 3 days I search how to do the same filter but with the checkbox "exclusive" too.
I see this on a previous issue : 

"Inclusive filters are like using OR. Color is inclusive. Selecting red and blue should filter red OR blue, .red, .blue.
Exclusive filters are like using AND. Size and price are exclusive. Selecting small and price should filter small AND price10, .small.price10."

So me I would like something like this : red AND blue AND small .red.blue.small
with color in checkbox and size in dropdown.
I see "Isotope combination filters with checkboxes" too :  http://codepen.io/desandro/pen/wjHEo 
So i can imagine, maybe it's possible to take this code and add a dropdown more ? I try but I am too bad in javascript...

Any help would be hugely appreciated !

Thanks ! 
Etienne

**Comment by desandro** [comment]
Hi there! Sorry to hear you are having trouble with Isotope. Could you try forking the [combination filter demo](http://codepen.io/desandro/pen/GFbAs) to provide a **reduced test case** of what you're trying to achieve? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by oscarsmeulders** [comment]
hi Desando, i like your isotope and also this codepen demo! I was working on it myself but this saves a lot of frustrations. A small question, is possible that we already start with a filtering, like .red is already checked and filtered at the onload? if you want need a codepen just let me know, thanks in advance!
oscar

**Comment by desandro** [comment]
Yes, you can initialize Isotope with a filter

``` js
var $grid = $('.grid').isotope({
  filter: '.red',
  masonry: {
    columnWidth: '.grid-sizer'
  }
});
```
