### ISSUE TITLE
Filter animations moving out of container

### ISSUE THREAD

**Issue by dubvfan87** [metafizzy/isotope#1004]
I'm having an issue where when the layout is filtering, the elements move out the container and do some "rubber banding" See here: http://justsold.wpstagecoach.com/boliger-til-salg/?niels=bente

It's especially noticeable on Internet Explorer where the elements fly up to the top of the page when filtering. I've been trying to mess with plugin options and the container css but no luck so far. Any idea what is happening here to cause this?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
