### ISSUE TITLE
Space available for 3 columns but it breaks

### ISSUE THREAD

**Issue by thehung2224** [metafizzy/isotope#1006]
In the example I have 3 columns with each 33.33% width. Container is 1170px (Bootstrap) but masonry only displays 2 columns and breaks the third one down.

Demo: http://codepen.io/thehung1724/pen/ojVzYo

**Comment by simonlongson** [comment]
Your example you have item as 33.33% but attaching item-half to the same element.

**Comment by thehung2224** [comment]
Hi @simonlongson 

Could you tell me clearly what's exactly problems?

**Comment by desandro** [comment]
You have two sizes of items, 33.33%, and 50%, so `columnWidth` should be set to fit both sizes. A 50% item in 33.33% columnWidth will take up 2 columns. Instead, you can add a sizing element, `.grid-sizer` and set its width to 16.67%.

``` css
.grid-sizer {
  width: 16.667%;
}
```

This way 33% items take up 2 columns, and 50% items take up 3 columns.

See demo http://codepen.io/desandro/pen/9bfa4c3ccd757156e34babab8c238197/

**Comment by thehung2224** [comment]
@desandro Thank you. But I took a look some websites, they don't use `.grid-sizer` and use they can use multiple width for item. They'll override each other.

**Comment by simonlongson** [comment]
They do but why risk it? Your's is reading the width: 50% in the demo you passed over. As .item-half appears after .item in your css, that's why it's over writing it but I'd serious suggest not to do that that way at all.

**Comment by thehung2224** [comment]
@simonlongson Thank you so much. Could you tell me where `.grid-sizer: 16.667%` as @desandro told from?

**Comment by simonlongson** [comment]
I think he'd mis-understood the question

**Comment by thehung2224** [comment]
Yes, but it solved my issue. @simonlongson Do you have any ideas for my problem?

**Comment by thehung2224** [comment]
@desandro Hi. Please help me, I want to add gutter except last child. How could I do this?

**Comment by simonlongson** [comment]
how much guttering would you be adding?

**Comment by simonlongson** [comment]
If you are wanting to do it with % you'd have to use % margin as well. To do it to all but the last you're best adding .item { margin-left: 2% } .item:first-child { margin-left: 0 } but what ever % you give you're margin-left you'll have to remove from your .grid-sizer width

**Comment by thehung2224** [comment]
Thanks @simonlongson so much. I know this way but you have to do manually. In my case, for the first row, I have 2 columns (I put the class `.item--half`). For the second row, I put the class `.item--one`. So if I have to add `:first-child` for each row.

**Comment by desandro** [comment]
@thehung2224 See masonry `gutter`: http://isotope.metafizzy.co/layout-modes/masonry.html#gutter. Try forking this example http://codepen.io/desandro/pen/aEmkl . Using the `margin-left` and `:first-child` technique will not work because Masonry removes horizontal ordering.

All of these options are documented, each with their own demo, editable on CodePen. I understand you're having issues, but I'd prefer not to use GitHub Issues as a support forum. GitHub Issues are best suited for submitting bugs and feature requests.

**Comment by thehung2224** [comment]
Ok @desandro I have last question, could you tell me how to calculate exactly `.gutter` width, it led me crazy. In your example, why `.grid-item` width is 22% instead of 20% (20 * 5 = 100%).

Thanks you.

**Comment by desandro** [comment]
The design has 4 columns, with 3 gutters inbetween. The space of the gutter is 4%

```
(100% - (3 gutters * 4%)) / 4 columns = 22% columnWidth
```
