### ISSUE TITLE
Layout break when resize on bootstrap grid

### ISSUE THREAD

**Issue by aboutjquery** [metafizzy/isotope#1007]
Hello,

Here is the pen1
http://codepen.io/anon/pen/GpLJqa

And here is the pen2
http://codepen.io/anon/pen/NGmqdx

Pen1 have not use image, i am using google chrome browser, when browser resize from 768px to 767px (from bootstrap col-sm to col-xs).

Sometime the layout will break like this image.

https://lh3.googleusercontent.com/ZP4iyxov31NP5LzB6SLRcAyK-ATTYeo1SRDu88FwVl_w-12B0-sGGDHWl-ke6XnqlC8sfLqfGlPM8np77jx154LbbUKiSP735sDRbjsoDhq0ByAKj3tx2P1TmgA8L5KxeeELNHHIbLPGcZh4Rn9ofo5oCsLls3xBkV1BdEGgGvMkWTw7Mwx4qy96CjYx_QoXRqDP_b7syPMnaM4PGJXoLoqBUBtKcfujd9VfSW3DYn29_p92l35YkvB8zhuDNcIJMj8cCaPeSQz8ka4pA7_8IxEWsDT3vWeV_M7m6ChooZtoseoztVX9qtvUhahRtMW8QpiBY_aE1jYgXsSTm5nEhEkQaqnkFUlHuYLqmyMgoZ_Qqwi68-jw0bbUk43YX5xPehXHZsHJ71Y0WHXlIcU8wt0FbxYyOenl64AxEHT6Dbo-ag1VBZ6n4wNzXQEXYZV_uy8m_xkLoKjNkgvuC1Lzt2krfVjBCR7vjQEJZWVnWD-l9BgToIUZ9Ow5y4STyPjkyfa1LkomkQDpYCOF75ywAktX9vIeNTChvkAJJv9oZA=w289-h320-no

Pen2 have use image, when browser resize from 768px to 767px.

Sometime (almost all time) the layout will break like this image.

https://lh3.googleusercontent.com/ULg7RUuVAHpKKhCcO_mjKCBDcpJbmPfT428IyXJOTrAp4MXjIbK0JifgkLP3dg_dZozBk123BuTop-wfGizQG_fEzFkIPwpowq6hmZujSXSdxqjp9J1c4Ap9gHSxIByHIt2SwauUc_r8JgPs1qX_vvf8qt1G19ODjQHNp9jiZJ-M6SHxS47lE_Kffw-21DyLXl3dHqe3Q59JIkOHwyhIZvdCVKeqgU6CCoTSzcs_LdAc3E51CGvdIf8_v7qsfniKF01pW4NjqL5HFRYfz-Er8FuO6OSUxVFfw24ToaE-8wMquFFCs_nF14VpF7co-254w79SLRGHaPNW99qNVHfbUBfdu5rDMcX-u1j9HUIBQairyUEz8n94-XgodvQdALZO-0DzLd5alD0I-zIPNTUc4TxoRZhQhmQ6sdLVq4ibF9ArVz3S0ju33BadOhmpMIshkTwDMSxHJOUDheTnBu95A1k1scxzit_rtgr1PBNUzmcvcUrPy-ysXNIpnZzY9bg0uSEO8TH92tFMc-JxHH9tNiD9HbMfnaayDP4TLob_OQ=w289-h320-no

Why the layout will break like above? Thank you so much :)

**Comment by desandro** [comment]
Thanks for the demos. I'm not sure I'm seeing the bug. I changed the image URLs so they are not broken.


I added [imagesLoaded](http://isotope.metafizzy.co/layout.html#imagesloaded) so there is no overlap [See demo](http://codepen.io/desandro/pen/c3a79b6b250f42c94d64d4db1e0c3aae/)

**Comment by aboutjquery** [comment]
Hello,

Thank you sooo much :)

I try to test again on the demo, but it still break the layout when try to resize between 767px and 768px, here is the image when break.

https://lh3.googleusercontent.com/INt4UXQUp8VFQEKHhBwi4Tl-OpmH9IdCLxmmczcq8K1H08Emxr1VW7ZVVfnN5cKqlQWEbVDgpGXcESFZKoZyoj6OXO0-oYug0eoaGf2md1WnJsbOGZ4NRwVv7679M90PxR3BvQzXLPDt6k1jVW-6B7bpaa6QNu_ubqDgAzmN7DIGkcb9_m8d7qYwhGVSGOBdFqIeMdLj1tU22Fs2QZwAr1H0bzwv8___eQbadg6HCDsRT_ACak_BTIur4zWAQPW4sLQsvpCsBDhM8hrm_XG2Dx5mbUh63gfYZIM9jVnxCogfG77A1In33ggCF6iRX1_wCSjVOiskL-RaQfivy2txVjbsVnA5A6SGgwusSHCZ5iRFJbrgWRu8dp2DBupkVg9Fxn9VkvxOqICNFRqJHGZlorRK_ndVJklPpEC_hdtxAoMLJNWAL3LSWpa0Y5TAC4nE8EN1UJ4iw1DdjlJWozAtdFv6oSCZih5ddmk84ea15UOrzTqilqKAXDnDBNMgaTo3e6LJPNLXjsm4pm-PxYXFv3-bSfUkP_uD-s9lJxOX_w=w174-h216-no

https://lh3.googleusercontent.com/elJrPjZJz2icJgMC8rr4PsA3d3sbO9Dix0MWB4XoSc2SCTYVozt_oVlmTwqO15GZHvWKY0ptQifFpp2t8H2RvpTjpuM8b-ASfkExFVDrhZmGiUH0nfxHgRrRQC6ePF2zS04VoBUJeHD6CvjUp2L-zgyVfOpDJZpgYqTW99nFc8mRWuaDRiza0NK2zzXOqIRRn4veMPI8-DvzCldyJn-bJGr5MAZNN2E2NVI3Szt0ANlsLdgviReqVtuLSwAJWFWYbxoTlIm7UxoZH8NhqnppYqGaJm45CEr2lPp_ke1Ax8b-Ive0qzY5nGm4DQXHINVhqUSnrams-FH45-wQDHVnwm20qx8d0xxJ3hfyETkh8LBgHtnrEGM_1-Sh2XYVqq8BlYSka2uMVW1BqpzLF7ntRsgZQBGhn_CK5BYkGBbMhkBSxFE3ffELuIYQ3NL5VLVpAKIzrLTkArLkq0yOua0f_J0fgYUmKPPEfIeXH931N64z9mDcqo_xRNk0eUDCyJbINZ0MJIBtbZBR38CMEeQvdnc4j6f3f6rKOOhXpriabw=w763-h906-no

I use google chrome and firefox browser, the layout work fine, but when i press f12 and keep to try resize the browser between 767px and 768px, it will break the layout.

Image 1 is use google chrome open demo at new tab, also break at firefox with same break layout.

Image 2 is use google chrome to test.

I dont know why it will break when resize between 767px and 768px (i resize move only 1px to test).

Thank you so much :)

**Comment by desandro** [comment]
Sorry, I am not able to reproduce this bug.
