### ISSUE TITLE
Wiredep issue - "Cannot read property 'Item' of undefined" 

### ISSUE THREAD

**Issue by laxmisalunkhe** [metafizzy/isotope#1008]
Getting error while installed isotope v2.2.2.

**Comment by desandro** [comment]
Are you using wiredep? Add this to your config

``` js
"overrides": {
    "isotope": {
      "main": [
        "js/item.js",
        "js/layout-mode.js",
        "js/isotope.js",
        "js/layout-modes/vertical.js",
        "js/layout-modes/fit-rows.js",
        "js/layout-modes/masonry.js"
      ],
    },
    "outlayer": {
      "main": [
        "item.js",
        "outlayer.js"
      ]
    }
  }
```

**Comment by laxmisalunkhe** [comment]
I have installed Isotope via Bower. Yes I am using wiredep but not sure about where to add this configuration? @desandro Can you provide more detail about config.

**Comment by laxmisalunkhe** [comment]
@desandro I have added the configuration provided by you in Bower configuration file but still it's shows same error.

**Comment by desandro** [comment]
Sorry about that, I had a trailing comma. I've edited the config code above. Try it again.

**Comment by desandro** [comment]
Closing as a duplicate of #879

**Comment by laxmisalunkhe** [comment]
@desandro I checked #879 but still my issue is not resolved after adding above code.
