### ISSUE TITLE
How to check is isotope has been initialised?

### ISSUE THREAD

**Issue by downFast** [metafizzy/isotope#1011]
I am adding new items on an ajax call, and I check each time I click to load new items if isotope has been initialised, the isotope layout happens laying all the new items as it should but the following never happens

if($("#list").data('isotope')) {
   alert("hello");
}

Is there anyway otherway to check if isotope has already been initialised?

**Comment by downFast** [comment]
This is how i resolved it

var myVar = false;

jQuery.fn.almComplete = function(alm){ <-- my ajax callback

    if(myVar) { <-- my var is set to true, means isotope is initialised
      do something
    } else {
     myVar = true; <-- set my var tot rue as isotope is not initialised yet
     start isotope
    }

});

**Comment by desandro** [comment]
Both methods would work. Thanks for sharing your code.

**Comment by downFast** [comment]
Hey
this didn't work for me actually :(

if($("#list").data('isotope')) {
alert("hello");
}

**Comment by desandro** [comment]
Sorry about the trouble. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by downFast** [comment]
i wish but i am loading the boxes via ajax :(
