### ISSUE TITLE
is there fast way to relayout after change dom show hide or add remove dom

### ISSUE THREAD

**Issue by JohnnieFucker** [metafizzy/isotope#1012]
is there fast way to relayout after change dom show hide or add remove dom。
just like 
$('#a').remove();
$('#b').hide();
$('#gridContainer').append(xxxx);
then
refresh the layout in a fast way

**Comment by desandro** [comment]
Sounds like you're asking about [`layout` method](http://isotope.metafizzy.co/methods.html#layout) ?

**Comment by JohnnieFucker** [comment]
but strangely it's not work for me :(

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by JohnnieFucker** [comment]
test case is here   
http://codepen.io/anon/pen/pgJGeW

click the test1 button ，you will see the new card 7， 8 will overlap the old cards

**Comment by desandro** [comment]
When adding and removing items from Isotope instance, you should use the [adding and removing methods](http://isotope.metafizzy.co/methods.html#adding-and-removing-items). See demo http://codepen.io/desandro/pen/bd41fc3334db2cd77833b14aa1940c06/

``` js
  // remove first card
  $container.isotope( 'remove', $container.find('.card').eq(0) );
  // prepend card
  var $prependCard = $('<div class="card" />', {
    id: 'card' + ++cardCount
  }).text( cardCount );
  $container.prepend( $prependCard );
  $container.isotope( 'prepended', $prependCard );
  // append card
  var $appendCard = $('<div class="card" />', {
    id: 'card' + ++cardCount
  }).text( cardCount );
  $container.append( $appendCard );
  $container.isotope( 'appended', $appendCard );
```

If you want to insert an item, I you can either use the [`insert` method](http://isotope.metafizzy.co/methods.html#insert), or try using [`reloadItems`](http://isotope.metafizzy.co/methods.html#reloaditems)

**Comment by JohnnieFucker** [comment]
how insert method specify the location of dom just like insertAfter，I try change layout method to reloadItems，it doesn't works。

http://codepen.io/anon/pen/pgJGeW
