### ISSUE TITLE
Multiple usage of .isotope('layout')

### ISSUE THREAD

**Issue by creher** [metafizzy/isotope#1013]
Say you have two .isotope('layout') calls in your function and you need to bind two different event listener to each of them. How would you achieve this? Using .isotope('once', 'layoutComplete', function() { ... will – as one might expect – fire randomly. What am I missing?

**Comment by desandro** [comment]
Thanks for submitting this issue. I'm having trouble understanding what you are trying to achieve. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by creher** [comment]
```
$('.grid').on('click', '.grid-item', function(e) {
    $(this).css({
 
    });
  $grid.isotope('layout').isotope('once', 'layoutComplete', function() {

          });

        });
```

**Comment by creher** [comment]
Sry for that. I was thinking about a case like this:

```
$grid.on('click', '.grid-item', function(e) {
    $(this).css({
        'width': '100%'
    });
    $grid.isotope('layout')
    $grid.isotope('on/once', 'layoutComplete', function() {
        // eg scroll to item
    });
    $.ajax({
        url: 'someurl',
        dataType: 'html'
    }).done(function (data) {
        $grid.append(data);
        $grid.isotope('layout')
        $grid.isotope('on/once', 'layoutComplete', function() {
            // eg hide some items
        });
    });
});
```
