### ISSUE TITLE
Logic in rearranging to fill gaps

### ISSUE THREAD

**Issue by playmono** [metafizzy/isotope#1014]
Hi,

Depend on screen resolution, isotope is arranging divs in a way or in another. Where can i see the logic in positiong? I mean which function more or less do this? (Initial positioning, not resizing).

More explanation: Its not about the first positioning, its about rearranging items to fill gaps.

Thanks.

**Comment by desandro** [comment]
If you are using the default layout mode, then it is using [Masonry layout's algorithm](http://isotope.metafizzy.co/layout-modes/masonry.html). Read more under [layout modes](http://isotope.metafizzy.co/layout-modes.html)

**Comment by playmono** [comment]
Thanks, thats perfectly what I needed :)
