### ISSUE TITLE
Searching with more than one term

### ISSUE THREAD

**Issue by eliluong** [metafizzy/isotope#1015]
Hello. The current Isotope search example given can search for anything in the object, but it can only do one word at a time. For example, if I search for "20", then 6 items show up, but if I search for "20 ium" it will not work. I'm trying to do this without using an additional filter.

Is this an easy fix, or will it require fixing the search method? Thanks.

**Comment by desandro** [comment]
Thank you for this request. Here's one way to do it: http://codepen.io/desandro/pen/Goqpzj

I've added more logic, so that if the value contains a space, like `20 ium`, the value will be split up and searched for: `20`, `ium` and `20 ium`.

**Comment by eliluong** [comment]
Thank you, sir. I'll drop it in my code to see if it works. I have one other issue I'm going to open a new thread because it's unrelated to this one.
