### ISSUE TITLE
Searching with filters (including filterFns) and search terms

### ISSUE THREAD

**Issue by eliluong** [metafizzy/isotope#1016]
I found some code written by you here (http://codepen.io/desandro/pen/mCdbD) where you show how to filter with button-filters and search terms. It works in my code.

I also wanted to use filter functions, which need to include this piece of code:
    $('.filters-button-group').on( 'click', 'button', function() {
        var filterValue = $(this).attr('data-filter');
        // use filter function if value matches
        filterValue = filterFns[ filterValue ] || filterValue;
        $grid.isotope({ filter: filterValue });
        });

But I noticed once I added this code in, the filters all work, but the search stops working unless I reload the page. Is this a known issue? Thanks.

**Comment by desandro** [comment]
See https://github.com/metafizzy/isotope/issues/709#issuecomment-43968341
