### ISSUE TITLE
Assign multiple colours to search and sort buttons 

### ISSUE THREAD

**Issue by ganemede** [metafizzy/isotope#1017]
When using isotope, the bank of search buttons, in the examples I have seen, are all the same colour. I would like to code each search button with the same colour as the 'element-item' shown in the display grid.
Can anyone give me a pointer as to how this might be achieved ?

**Comment by desandro** [comment]
You can style the buttons with CSS http://codepen.io/desandro/pen/370640d30ba9adb89c1075f6b60c43e9/

**Comment by ganemede** [comment]
Thanks for this... It worked perfectly...
