### ISSUE TITLE
Isotope cannot call methods on isotope prior to initialization; attempted to call 'insert' another one

### ISSUE THREAD

**Issue by helenemartin** [metafizzy/isotope#1018]
Hello  Alessandro
I have been struggling with Infinite scrolling for ages.

I am using Isotope infinite scrolling with filtering (using 'insert method') on Rails very confusing.
I have pushed it on Heroku but pagination doesn't work.
I have console error "cannot call methods on isotope prior to initialization; attempted to call 'insert'"
pins.js.coffee:
$ ->
  $(document).ready ->  
    $('.pagination').hide() 
    $('#pins').imagesLoaded().always ->
      $('#pins').isotope(
        itemSelector: '.box'
        isFitWidth: true)

    $(".button").on("click", ->
      if $(this).attr('data-filter') == ""
        $("#pins").isotope(filter:'*');
      else
        $('#pins').isotope(filter:"[data-filter*=\""+$(this).attr('data-filter')+"\"]")
    )

    if $('#pins').size() > 0
      $(window).on 'scroll', ->
        more_pins_url = $('.pagination .next a').attr('href')
        if more_pins_url != undefined && $(window).scrollTop() > $(document).height() - $(window).height() - 60
          $('.pagination').text("Fetching more pins...")
          $('.pagination').show()
          console.log(more_pins_url)
          $.getScript(more_pins_url)
        return
      return

Index.js.erb
var newItems = $('<%= j render(@pins) %>');
console.log(1, newItems);
// Append newItems to the pins container and tell isotope that there is new items to style
$('#pins').isotope('insert', newItems);

// Check if there is another page worth of pins, 
// If there is, change the pagination to the new will_paginate result
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= will_paginate(@pins) %>');

// Otherwise, hide the pagination
<% else %>
  $('.pagination').remove();
<% end %>

That would be great if you could have a look please
Thank you in advance
With kind regards
Merry Xmas!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by helenemartin** [comment]
Hello It is not very clear how to set a test case on the guidelinesI can't do Rails on CodePenMany thanksBest wishesH

Date: Wed, 23 Dec 2015 11:36:41 -0800
