### ISSUE TITLE
Stagger transition

### ISSUE THREAD

**Issue by anteksiler** [metafizzy/isotope#1019]
Hi everyone, 

Has anyone tried to add a material design animation such as http://zavoloklom.github.io/material-design-hierarchical-display/#demo

**Comment by desandro** [comment]
Thanks for this feature request. Others have requested this as well. See desandro/masonry#540

**Comment by desandro** [comment]
Isotope v3 has been released with new `stagger` option. See http://isotope.metafizzy.co/options.html#stagger

**Comment by anteksiler** [comment]
Hi @desandro,
Thanks for adding this on v3. I was wondering if it's now possible to stagger items on initial load.
