### ISSUE TITLE
Filter by groups of items

### ISSUE THREAD

**Issue by Toledoh** [metafizzy/isotope#1020]
Hello.

I'm wanting to display items in groups, I'm done this with multiple $containers.
Demo: http://sf.viuu6.com/toledoh/productList.php

If "Collection>Origin" is selected, it only shows those items in that collection which is correct, however I don't want to display the other collection headings.

Can you suggest a better way of grouping / filtering?

**Comment by Toledoh** [comment]
Any ideas on this - would it be possible?

**Comment by desandro** [comment]
You can check when an instance has no items after a filter. use `.filteredItems`. See http://isotope.metafizzy.co/faq.html#how-can-i-access-filtered-items-in-current-order

**Comment by Toledoh** [comment]
Brilliant - thank you!
