### ISSUE TITLE
Disabling the Isotope click event handler

### ISSUE THREAD

**Issue by JayWIlsonJr** [metafizzy/isotope#1021]
I have FlexSlider inside of a element that Isotope expands, however when the FlexSlider is open I need the user to be able to navigate through the image slider images etc. However due to the default behavior whenever the user clicks the FlexSlider the element shrinks back down. The element shouldn't shrink until the user clicks the 'X' in the upper corner to close the pane. 

My reduced test case can be found here:  http://codepen.io/JayWIlsonJr/pen/bErzrd

How do I accomplish this? 
I am new to this, so thank you in advance for your time and assistance. 

Kindly, 

Jay Wilson Jr.

**Comment by desandro** [comment]
Hi Jay! Sorry to hear you're having trouble. The code to change is `$items.click`. Currently it toggles  `selected` class. We can rewrite it so it only turns on `selected`.

``` js
  $items.click(function(){
    var $this = $(this);
    // don't proceed if already selected
    var $previousSelected = $('.selected');
    if ( $this.hasClass('selected') ) {
      return;
    }
    // remove other selected
    $('.selected').removeClass('selected');
    // update sortData for new items size
    $container
      .isotope('updateSortData')
      .isotope();
  });
```

See demo http://codepen.io/desandro/pen/cf847d651137ff594800b66491cc3805/

**Comment by JayWIlsonJr** [comment]
Hi! 

Thank you for your help, I am not sure if this is the best solution but it works: 

```js
$items.on('click',function(e) {
    var $this = $(this);
    if($this.find('.hidden-default:visible').length !== 0) {
      e.stopImmediatePropagation();
      e.stopPropagation();
      return false;
    }
    // don't proceed if already selected
    var $previousSelected = $('.selected');
    if (!$this.hasClass('selected')) {
      $this.addClass('selected');
    }
```
