### ISSUE TITLE
problem with resize

### ISSUE THREAD

**Issue by michellomp** [metafizzy/isotope#1022]
Hi

I had two problems the first one is that when i reduce the size of the windows under 767px the layout break up
here is a link of a test : http://www.teathemes.com/test-isotope/
Most of the time the isotope items behave well but under certain, specific window dimensions, don't fall into 3 columns, but stay as one thin column.
Do you have any idea of what's going on ?
It may come from bootstrap ?
and the second one is that in large screen when i click on riso the layout slightly move to the right

**Comment by desandro** [comment]
Looks to be related with how you are using flex box for sizing `.wrapper`, unrelated to Isotope.
