### ISSUE TITLE
2 and then 3 columns are not working

### ISSUE THREAD

**Issue by Pixelous** [metafizzy/isotope#1024]
Hi David,

Can you take a look here http://demo.themeuniverse.net/pear/demo-17/ why last 3 columns do not work properly?

Please see attached screenshot to make sure what I mean.

![image](https://cloud.githubusercontent.com/assets/1421184/12398156/7580b062-be1a-11e5-819e-f0afb38a7eea.png)

I use the latest version of Isotope: Isotope PACKAGED v2.2.2.

Do I need to provide any other info related to the issue?

Kind regards

**Comment by desandro** [comment]
``` css
#block-portfolio .col2 .grid-sizer {
  width: 48.7%;
}
```

columnWidth is set to this value. Looks like you want to set it to 6 columns so it can accommodate items that span 3 or 2 columns, `14.583%`

**Comment by Pixelous** [comment]
Thanks! That helps!
