### ISSUE TITLE
Error when using Isotope v2.2.2 with Rails 4.2 / AMD / rails-assets-almond (0.3.1)

### ISSUE THREAD

**Issue by brucek** [metafizzy/isotope#1025]
Not exactly sure where the problem lies, but using the instructions at:

http://nandovieira.com/using-es6-with-asset-pipeline-on-ruby-on-rails

I get the following error when trying to

    //= require isotope.pkgd.min

in my application.js file:

    Uncaught Error: See almond README: incorrect module build, no module name

This is kind of an outlier case, but it seems to be resolved by simply adding a name to the Isotope define() AMD call (line 3650):

```
  if (typeof define == 'function' && define.amd) {
    // AMD
    define('isotope', [
        'outlayer/outlayer',
        'get-size/get-size',
```

I suspect it is a problem with something happening in Babel but once I got it working I just moved on.  Hopefully this will help others and maybe worth adding to the source.  Thanks for the great library!

**Comment by desandro** [comment]
Thanks for reporting this issue. It's odd, because requiring `isotope.pkgd.js` works okay with RequireJS. Modules do not have to be named.

Sounds like a quirk with the Rails Assets pipeline. I'll keep this issue open for other's visibility.
