### ISSUE TITLE
Hiding titles when list is empty

### ISSUE THREAD

**Issue by MisturChris** [metafizzy/isotope#1026]
Hello,

I'm trying to hide/reveal items in my isotope instance and I'm having some issues. Now my jquery knowledge isn't the best, so for all I know this issue could be completely on my end, but the error i'm getting is coming from isotope so I figure I'd see what you guys think.

I have a codepen of what I'm working on here: http://codepen.io/anon/pen/YwadOK?editors=1010

What I want to happen is this: When clicking on a filter, if the list following the h2 isn't visible, hide that h2. (ie: when clicking the "Cats" filter, since nothing displays for 2016, hide the 2016 h2).

Now my issue is that when I try to hide/reveal items, like on line 33:
`$grid.isotope('hide', hideMeIDs);`

I get the error:
**isotope.pkgd.min.js:11 Uncaught TypeError: j.once is not a function**
_Edit:_
When I switch from using the minified isotope package to the non-minified package I get:
**isotope.pkgd.js:2495 Uncaught TypeError: item.once is not a function**

Along with that, my arrays seem to mess up when I try this as well. When line 33 is commented out, viewing the console while using the filters (for example, selecting Birds) shows:
```
2016 should be hidden
2015 should be hidden
Array: showMeIDs =
Array: hideMeIDs = #2016,#2015
```
However when line 33 is not commented out and clicking the Birds filter twice (it doesn't matter that I select Birds twice specifically, selecting any filter afterwards will show that the arrays don't reset but just keep adding) I get:
```
2016 should be hidden
2015 should be hidden
Array: showMeIDs =
Array: hideMeIDs = #2016,#2015,#2016,#2015
```

I'm hoping someone can lend a hand with this. Maybe my code's wrong, I'm hoping that's it. Sorry if this is the wrong place to put this but I'm unsure what to do next and any help would be appreciated.

Thanks.

**Comment by MisturChris** [comment]
I was able to get the hide method working here: http://codepen.io/anon/pen/RryaZo?editors=1010

Is there a way to have isotope rearrange after the h2's are hidden so there are no blank gaps in the grid?

**Comment by desandro** [comment]
Thanks for reporting this issue. I spot trouble in that your demo is mixing items with titles. It's going to be hard to manage when to show one but not the other. I would recommend breaking out each year into its own Isotope instance, so items can stay items, and titles can be treated separately. See [demo on CodePen](http://codepen.io/desandro/pen/4e0bbf3c391b74ebc708dd0caf8b4c0d)

I'm using [filteredItems](http://isotope.metafizzy.co/faq.html#how-can-i-access-filtered-items-in-current-order) to detect if an instance has any children or not, then hiding or showing the title.

``` js
var $years = $('.year');

// init isotope
$years.each( function( i, year ) {
  var $year = $( year );
  $year.find('.news-list').isotope();
});

$('.filter-list').on( 'click', 'a', function( event ) {
  event.preventDefault();
  var filterValue = $( event.currentTarget ).attr('data-filter');
  console.log( filterValue )
  $years.each( function( i, year ) {
    var $year = $( year );
    var $newsList = $year.find('.news-list').isotope({
      filter: filterValue
    });
    var iso = $newsList.data('isotope');
    if ( iso.filteredItems.length ) {
      $year.find('h2').show();
    } else {
      $year.find('h2').hide();
    }
  });
  
});

```

**Comment by MisturChris** [comment]
Works absolutley pefectly. Thank you so much for your help :+1:
