### ISSUE TITLE
2 passes required to avoid overlap with appended

### ISSUE THREAD

**Issue by afrozl** [metafizzy/isotope#1028]
I am unable to get a grid of variable height elements to layout withot overlap unless I do 2 passes.

This does not work:

<pre>$('#widgets').isotope()
append( item )
.isotope( 'appended', item )
.isotope('layout');</pre>

while this does:

<pre> $('#widgets').isotope()
.append( item )
.isotope( 'appended', item )
.isotope('layout');
 setTimeout(function() {
      $('#widgets').isotope('layout');
  }, 100);</pre>

Hopefully its something stupid that I'm doing and is easily fixed?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues). Try forking the [appended demo](http://isotope.metafizzy.co/methods.html#appended)

**Comment by afrozl** [comment]
Thanks, I was able to get a hint from the image loading example. it turns out that even though I had a fixed height set for the image container, the css for the image itself specified  'auto'. It's working fine now after setting the image height to a fixed number.
