### ISSUE TITLE
cellsByRow breaks with multiple filters and combination checkboxes

### ISSUE THREAD

**Issue by scornickccv** [metafizzy/isotope#1030]
Thank you for Isotope!

I have <div class="item ..............    with many items and have used your combo checkbox example to adapt to filter on 3 sets of categories.  

Is there a limit to how many tags i can put after the item in the class=? Isotope breaks after about 15 for my when i have 30 pictures in the container.

"Uncaught TypeError: Cannot read property 'innerWidth' of undefined" from console and points here:

" this.cols = Math.floor( this.isotope.tag.innerWidth / this.columnWidth );"

thank you!

stephen

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by scornickccv** [comment]
I will give it a shot but is hooked into a flask application.


regards,

stephen

**Comment by scornickccv** [comment]
here is the broken isotope.  on my end when i have too many tags in the items div class definition it dies.  I am also curious about having too many tags in the data-group and if that is a constraint. 
http://codepen.io/anon/pen/OMoXKZ

thanks

stephen

**Comment by desandro** [comment]
Thanks for that.  [Here's a working demo](http://codepen.io/desandro/pen/baef739c90c16ca45d16f38ceab100a3)

1. I removed about half the content, changing a 9000 LOC demo to 4000
2. Upgraded Isotope to v2. Removed old Isotope v1 CSS
3. There was a second `#container` element being used as a checked. So I renamed `#container` to `#grid`. I believe this may be the problem with your example breaking.

**Comment by scornickccv** [comment]
thank you so much.  after lots of testing i found a wall at 602 checkboxes.  see below. the first was updated to your fixed demo with more checkboxes added to get to 602 and the second to 603.  603 breaks.



http://codepen.io/anon/pen/OMoXKZ

$( ":checkbox" ).length =602 works

http://codepen.io/anon/pen/PZyWpG

$( ":checkbox" ).length =603 broken

**Comment by desandro** [comment]
That sounds like a browser bug more than an Isotope bug.

Looking at the bigger picture, Isotope works best with about 100 items. You might be able to get away with more. If your app is trying to filter through 1000 items, Isotope is not the right solution. If your UI has more options than it does items, that's not a good user experience. I recommend trying different UI, maybe tag-based with auto-complete.
