### ISSUE TITLE
this[(("_" + this.options.layoutMode) + "Reset")] is not a function

### ISSUE THREAD

**Issue by BlizzzArt** [metafizzy/isotope#1032]
Tell me, please, in which cases maybe this error:
`jquery.isotope.js?ver=1.5.25:15 Uncaught TypeError: this[(("_" + this.options.layoutMode) + "Reset")] is not a function`
Only totally restore theme(WordPress) and Base of Data resolved this trouble but this way very unsuitable
I need restore only part of code, because I remarked this error very later

**Comment by desandro** [comment]
It's likely caused by an invalid `layoutMode` option. See [Isotope v1 layout modes](http://isotope.metafizzy.co/v1/docs/layout-modes.html)

**Comment by BlizzzArt** [comment]
Thank you! parametr layoutMode was empty because of trouble with Cherry Framework
