### ISSUE TITLE
Difference in masonry grid and bin-packing layouts?

### ISSUE THREAD

**Issue by corysimmons** [metafizzy/isotope#1033]
> Masonry does cascading grid “masonry” layouts. Packery does bin-packing layouts, which allow it to be used for draggable interactions.

Are these generally the same except bin-packing can be dragged?

Is bin-packing just purely better than masonry? They appear to be very similar.

**Comment by desandro** [comment]
The Masonry and Packery layout algorithms are generally the same, but there are some differences

Packery use a bin-packing algorithm, so it can fill gaps. See demo on CodePen: http://codepen.io/desandro/pen/KVrpxM

![screen shot 2016-02-08 at 7 33 15 am](https://cloud.githubusercontent.com/assets/85566/12885722/3d232a70-ce36-11e5-9317-daff2955310d.png)

[Packery layouts are draggable](http://packery.metafizzy.co/draggable.html). With Packery layouts, items can be [fit to a spot](http://packery.metafizzy.co/methods.html#fit) and other items are laid out around it. Both these features are only available in the [stand-alone Packery library](http://packery.metafizzy.co/), not in the `packery` layout mode for Isotope.

Masonry requires `columnWidth` to be set. Packery does not.

> Is bin-packing just purely better than masonry?

It's a trade-off. While Packery has more features than Masonry, it is also bigger in filesize.

**Comment by corysimmons** [comment]
Well packery looks amazing and now I'm really interested in this bin packing algorithm. Good work. :+1:
