### ISSUE TITLE
Apply filter function to all filters

### ISSUE THREAD

**Issue by bebjakub** [metafizzy/isotope#1034]
Hi :)
Is possible apply filter function 'greaterThan50' to all filters?
I would like to show just items greater than 50 for all filters in container.
http://codepen.io/desandro/pen/owAyG/

thanks

**Comment by desandro** [comment]
I'm not sure I understand your question. The demo allows you the user to select **>50** filter and a selector filter.

**Comment by bebjakub** [comment]
Simple, I need show on init just >50 and keep it, but still I want use other buttons filters except >50 button.

**Comment by desandro** [comment]
Here's one way to do it http://codepen.io/desandro/pen/1f0c676d32473ccf8b6d053c07aa9ba6/

**Comment by bebjakub** [comment]
thanks! its perfect! :+1:
