### ISSUE TITLE
Custom Layout _getItemLayoutPosition

### ISSUE THREAD

**Issue by lolo34140** [metafizzy/isotope#1035]
Hello,

I have created a custom layout by extending isotope and it's working fine. However I have some difficulties to make it works when new items are appended to isotope.

With my custom layout, I need to get all filteredItems in order to apply the right new possitions to all items.
When I try to retrieve filteredItem in _getItemLayoutPosition, the filteredItems are set in the array but I can't acces to theme. For example:

`myLayout.prototype._getItemLayoutPosition = function( item ) {
           console.log(this.TG_Layout) /*** filteredItem with new appended item are set ***/
            console.log(this.TG_Layout.filteredItems) /*** filteredItem doesn't contains new item ***/
}`

It's really strange, the filteredItem is correctly set but I can't catch the right array! I can't understand why I can't get these filteredItems (I also try in myLayout.prototype._getContainerSize but it's the same)....
If it's not possible to get this array, is it possible to trigger a relayout everytime a new item is appended in the _getItemLayoutPosition ? 

I have searched during hours a solution but I can't find it....

Loïc

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by lolo34140** [comment]
Hello,

I have made a reduced test case. However I didn't set anything in the extended layoutMode, it just an example. I just want to get filtered items after appended method like in this reduced test case: http://codepen.io/anon/pen/xZQeXb

Loïc

**Comment by desandro** [comment]
Let's take a look at the source. Here's how [`appended` method currently looks in v2.2.2](https://github.com/metafizzy/isotope/blob/v2.2.2/js/isotope.js#L492)

``` js
Isotope.prototype.appended = function( elems ) {
  var items = this.addItems( elems );
  if ( !items.length ) {
    return;
  }
  // filter, layout, reveal new items
  var filteredItems = this._filterRevealAdded( items );
  // add to filteredItems
  this.filteredItems = this.filteredItems.concat( filteredItems );
};

Isotope.prototype._filterRevealAdded = function( items ) {
  var filtered = this._filter( items );
  this.hide( filtered.needHide );
  // reveal all new items
  this.reveal( filtered.matches );
  // layout new items, no transition
  this.layoutItems( filtered.matches, true );
  return filtered.matches;
};
```

So you can see that `filteredItems` doesn't get set until after the newly appended items are laid out. If you rather have `filteredItems` set before layout, within `appended`, you can rewrite `appended`.

``` js
Isotope.prototype.appended = function( elems ) {
  var items = this.addItems( elems );
  if ( !items.length ) {
    return;
  }
  // filter, layout, reveal new items
  var filtered = this._filter( items );
  this.hide( filtered.needHide );
  // reveal all new items
  this.reveal( filtered.matches );
  // add to filteredItems
  this.filteredItems = this.filteredItems.concat( filtered.matches );
  // layout new items, no transition
  this.layoutItems( filtered.matches, true );
};
```

It's a hack solution, but it should work.

**Comment by lolo34140** [comment]
Thank you for your answer.

But I don't understand why when I look at the isotope data array the filteredItems are there before layout an item. But I can't retrieve them in the array even if items are present in console.log (like in my reduced test case).

Is there a way to filter item directly in the new layoutMode instead of modifying/creating a new isotope prototype?

I can still make it works with this little trick: `var filtered_Items = this.isotope.items.filter(function(item){return item.isHidden !== true});` but I'm not sure if it's a good practice. It seems to work fine but I'm not sure about this.

Thank you for your help!

**Comment by lolo34140** [comment]
Hello,

I have changed the appended method for my custom layout. it's working really great now! 
Thank a lot.

Loïc
