### ISSUE TITLE
broken in WordPress & srcset

### ISSUE THREAD

**Issue by leanda** [metafizzy/isotope#1037]
Hi

I have a really strange problem with isotope, infinite scroll and imagedLoaded on iOS 9 (iPhone). This works fantastically in every other browser except for mobile safari. Where after maybe the second or third set of posts loads it's almost as if imagesLoaded stops working and a few posts start to overlap again. 

I've thrown everything at it this weekend and still can't figure out what's going on.

Thanks

    `$(window).load(function () {

	var $container = $('.container'); //The ID for the list with all the blog posts

	$container.imagesLoaded(function(){
	$container.isotope({ //Isotope options, 'item' matches the class in the PHP
		itemSelector : '.item',
		layoutMode : 'masonry',
		stamp: '.stamp',
		masonry: {
			gutter: '.gutter-sizer'
		}
	});
    });

	$container.infinitescroll({
		"nextSelector":".nav-links .nav-previous a",
		"navSelector":".paging-navigation",
		"itemSelector":".item:not(.stamp, .main-filter-navigation, .intro-about, .intro-written, .intro-brought, .intro-interpreted)",
		"bufferPx": "500",
		loading: {
			finishedMsg: 'No more items to load.',
			img: 'http://i.imgur.com/qkKy8.gif'
		}
	},

	function ( newElements ) {
       var $newElems = jQuery( newElements ).css({ opacity: 0 }); // hide to begin with

      $('.container').imagesLoaded( function() {
      $newElems.fadeIn().delay(40); // fade in when ready
      $container.isotope( 'insert', $newElems );
      });
     }
     );
    });`

**Comment by leanda** [comment]
I think I've tracked this down to be an issue with imagesLoaded and the new srcset responsive images introduced in WordPress 4.4

If I disable responsive image support using a filter in the functions.php file which removes the srcset attribute from the images then everything loads fine on mobile safari.

Is there a better way to fix this?

Thanks

**Comment by desandro** [comment]
Thanks for reporting the issue. Sorry, but I don't think there's a better fix. imagesLoaded does not support `srcset`. See desandro/imagesloaded#175

**Comment by leanda** [comment]
Thanks for confirming, any chance it will in the future?

**Comment by desandro** [comment]
Of course! Hoping for a valiant Pull Request to make it happen.

**Comment by leanda** [comment]
Thanks, awesome! Will watch this space.
