### ISSUE TITLE
load more button on filtered items

### ISSUE THREAD

**Issue by bebjakub** [metafizzy/isotope#1038]
Hi :)
Im working on load more button for filtered items http://codepen.io/bebjakub/pen/RraqBr
For filtering im using this your feature: http://codepen.io/desandro/pen/1f0c676d32473ccf8b6d053c07aa9ba6/

I would like to on init load have showed 6 items but a I got just 4 becouse filters, 
How I can fix it? I spend few hours on it without succes...

thanks

**Comment by desandro** [comment]
At this point, I would recommend simplifying your demo. There are too many concepts being used at once and the result is a lot of excess code that is hard to debug. Sorry but I won't be able to provide a solution to this request.

**Comment by bebjakub** [comment]
This is my Load more button for Isotope: http://codepen.io/bebjakub/pen/jWoYEO
Enjoy :)

**Comment by joeychukc** [comment]
I would like to write a page with combination filter and load more button.
I copied your code and found out that when I clicked the filter button, it doesn't show 4 filtered items. Instead, it shows the items which were shown under 'all' category(4 initialized items)  that belong to the filtered category.

But I would like to show 4 filtered item.

How can I fix it?

**Comment by bebjakub** [comment]
Can you post a url to your codepen?

**Comment by joeychukc** [comment]
https://codepen.io/jekaterina/pen/RowMzK

Sorry that I am new to Jquery, also I want to show the number of events hiding, but I just don't know why the values of counter and noOfClick never update.

**Comment by bebjakub** [comment]
For combination filter groups I used this source https://codepen.io/desandro/pen/JEojz For count hidden items you can use hiddenElems.length

**Comment by joeychukc** [comment]
I used this source too, but this combination filter method does not work find with your load more button. I just do no how to fix the problem.

**Comment by projectssome** [comment]
I also had this problem and your solution worked great, @bebjakub!! But wonder how could I change the `load more` animation only. I mean, keeping the filtering animation as it is now and showing the items fading down when clicking `load more`, for example. I changed `initShow` in order to replicate the `load more` animation showing from the side, as you can see in this [CodePen](https://codepen.io/projectssome/pen/pqVgXR).

**Comment by jagadeesh01** [comment]
can anyone help me to sortout this solution in pure javascript ...???
