### ISSUE TITLE
Hide/reveal methods not working

### ISSUE THREAD

**Issue by adipurdila** [metafizzy/isotope#1039]
Hi,

I'm having some problems with the hide/reveal methods. Here's a bit of code that doesn't work for me:

    var $notes = $( ".notes" );

    $notes.isotope( {
        itemSelector: '.note',
    } );

    var targetItem = $( "#note-test" );

    $( "#toggle-items" ).click( function( e ) {
        e.preventDefault();

        $notes.isotope( "hide", targetItem );
    } );

I've tried triggering a layout after that but it doesn't do anything. What am I doing wrong?

**Comment by blowsie** [comment]
Hide and reveal work with isotope items, not elements.

**Comment by blowsie** [comment]
There is a undocumented method you can use 'hideItemElements`

 `$notes.isotope( "hideItemElements", targetItem );`

**Comment by adipurdila** [comment]
Thank you @blowsie . Could you show me an example on how to use the hide/reveal methods? It's a bit confusing to me.

**Comment by blowsie** [comment]
@adipurdila  The example is in my comment :+1:

**Comment by adipurdila** [comment]
Thank you!
