### ISSUE TITLE
Using packery layout mode stops events firing

### ISSUE THREAD

**Issue by evoactivity** [metafizzy/isotope#1041]
```
var $container = $('#grid');

$container.isotope({
    itemSelector: '.item',
    layoutMode: 'packery',
    packery:{
        gutter: 14,
        columnWidth: 307
    },
    getSortData: {
        name: 'h3'
    }
});

$container.on('arrangeComplete layoutComplete', function(e, items){
    console.log('-------- layout ----------');
    console.log(e, items);
});
```
This does not work as expected, changing the layout mode to masonry and the event fires. If this behavior is intentional then it should be noted in the docs.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
