### ISSUE TITLE
 isotope modulo columns display order

### ISSUE THREAD

**Issue by sajpasa** [metafizzy/isotope#1042]
Hi I have been trying to implement isotope modulo columns, as i need it to display in the order that it comes in. My blocks need to have similar width, but the height will vary. 
However I keep getting a error while I use isotope modulo columns. Is there any other plugins I could use to achieve this?
Thanks

**Comment by desandro** [comment]
[isotope-modulo-columns](https://github.com/michieldewit/isotope-modulo-columns) is not maintained by me, so I can't speak for its compatibility with the rest Isotope. Looks like it hasn't been updated in years.

**Comment by sajpasa** [comment]
Got it work now! Just need to implement infinite scrolling now!
Thanks anyway
