### ISSUE TITLE
Filtering with min and max value

### ISSUE THREAD

**Issue by julienstuder** [metafizzy/isotope#1043]
Hi !
i've been searching for hours examples that would match my needs but i don't find any.

i have games with a min value of possible players and a max value of possible players.
and other filters.
i want to filter them, best would be with a range input
i found examples of range input, but for one value, like price.
my items have like 2 values.
is it possible ? do you have an example ?

thank you very much !!

**Comment by sajpasa** [comment]
http://isotope.metafizzy.co/sorting.html
Scroll to the down there should be a section called "Multiple sortBy" .
Maybe thats what you are looking?

**Comment by julienstuder** [comment]
Hi Thanks for your answer !
no my "problem" is that i want to filter like in this example:
http://jsfiddle.net/5aPg7/

but my items have multiple value, not only one like a price.

my items are games. they can be player by a minimum and a maximum of players, for example 1 to 3, 2 to 6, etc....

so maybe i have to add a class for each number of player (if a game can be played by players from 2 to 6, i have to add classes 2,3,4,5,6 to this item.

what do you think ?

**Comment by desandro** [comment]
Take a look: http://codepen.io/desandro/pen/qbzyqd/

I'm using a [filtering function](http://isotope.metafizzy.co/filtering.html#filter-functions), then updating `min` and `max` values when the range is changed.

``` js

// initial values
var min = 5;
var max = 20;


// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.grid-item',
  // filter with function
  filter: function( i, itemElem ) {
    var $number = $( itemElem ).find('.number');
    var number = parseInt( $number.text(), 10 );
    return number >= min && number <= max;
  }
});

var $range = $('.min-max-range').slider({
  range: true,
  min: 0,
  max: 40,
  values: [ min, max ],
  slide: function( event, ui ) {
    min = ui.values[0];
    max = ui.values[1];
    updateOutput();
    $grid.isotope();
  }
});

var $rangeOutput = $('.min-max-range-output');

function updateOutput() {
  $rangeOutput.text( min + ' - ' + max );
}

updateOutput();
```

**Comment by julienstuder** [comment]
cool desandro ! thank you !
that will help me !

you can see the thing here : http://j2c.nopixel.ch/jeux/

when we began the project, we thought that using tags like "1-2" "2" "2-3" "4-10" would be ok, but after tagging some games, we found that there to many combinations and not possible to see in one time all games that would be ok for 5 players, for examples.

so as i said before, maybe i have to add a class for each number of player (if a game can be played by players from 2 to 6, i have to add classes 2,3,4,5,6 to this item.

then i thought of having a min value and a max value for each game. but that needs some other coding, no ?

thanks again for your code example !

**Comment by desandro** [comment]
You can use the same concept of filtering function. See demo http://codepen.io/desandro/pen/5a101df3b15eac1c8f93376e4539d4c5/

This demo has a range of players in HTML `<p class="players">2-4</p>`. That HTML is then parsed and evaluated in the filter function.

``` js
// initial values
var players = 4;

// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.grid-item',
  // filter with function
  filter: function( i, itemElem ) {
    var playersText = $( itemElem ).find('.players').text();
    var playersRange = playersText.split('-');
    var min = playersRange[0];
    var max = playersRange[1];
    return players >= min && players <= max;
  }
});

var $range = $('.range').slider({
  min: 1,
  max: 10,
  value: players,
  slide: function( event, ui ) {
    players = ui.value;
    updateOutput();
    $grid.isotope();
  }
});

var $rangeOutput = $('.range-output');

function updateOutput() {
  $rangeOutput.text( players );
}

updateOutput();
```

**Comment by julienstuder** [comment]
that is totally perfect !!!!! 
thank you very much !!

just have to add other filters now, but this is ok !

**Comment by julienstuder** [comment]
well it's a bit more complicated for me than i thought...
do you think i can use your code from http://codepen.io/desandro/pen/73238e7835570ac86352d0a4e4c7a091
to combine filters ?

**Comment by desandro** [comment]
See http://codepen.io/desandro/pen/owAyG/ for combination filter and functions

At this point I recommend considering how much functionality you want to mix together. The more options and UI you offer, the more complex the code becomes.

**Comment by julienstuder** [comment]
thanks !
i have the slider and 3 button groups

**Comment by julienstuder** [comment]
Hi desandro !

i tried many things but ended up with the slider range working or the other button filter working :)
i got imageloaded working.
i'm really a newbie at javascript...
can you help me again ? thanks very much!


<script>

// initial values
var players = 4;


var $container = $('#container');
filters = {};
$container.imagesLoaded( function(){
  $container.isotope({
    itemSelector: '.item',
  // filter with function
  filter: function( i, itemElem ) {
    var playersText = $( itemElem ).find('.players').text();
    var playersRange = playersText.split('-');
    var min = playersRange[0];
    var max = playersRange[1];
    return players >= min && players <= max;
  }
  });
});

// filter buttons
    $('.filter a').click(function(){
      var $this = $(this);
      // don't proceed if already selected
      if ( $this.hasClass('selected') ) {
        return;
      }
      
      var $optionSet = $this.parents('.option-set');
      $optionSet.find('.selected').removeClass('selected');
      $this.addClass('selected');
      
      var group = $optionSet.attr('data-filter-group');
      filters[ group ] = $this.attr('data-filter-value');
      var isoFilters = [];
      for ( var prop in filters ) {
        isoFilters.push( filters[ prop ] )
      }
      var selector = isoFilters.join('');
      $container.isotope({ filter: selector });

      return false;
    });


var $range = $('.range').slider({
  min: 1,
  max: 10,
  value: players,
  slide: function( event, ui ) {
    players = ui.value;
    updateOutput();
    $container.isotope();
  }
});

var $rangeOutput = $('.range-output');

function updateOutput() {
  $rangeOutput.text( players );
}

updateOutput();


</script>

**Comment by desandro** [comment]
Sorry, but I won't be able to provide personal support on this one. I've provided several demos and [Isotope docs](http://isotope.metafizzy.co) are full of more examples and code.
