### ISSUE TITLE
5 columns isotope portfolio in boostrap3

### ISSUE THREAD

**Issue by TomasZmuda** [metafizzy/isotope#1044]
I have problem with isotope portfolio filtering. The default is 4 columns in col-sm-3 (25%), if I'd like to change it to col-sm-2 (16.6%), the image size is ok, but isotope filtering doesn't work.

You could try it in web page: http://komornik.zmuda.cz/#portfolio

Isotope is original, version 2.2.2.

    <div id="links">
      <div class="portfolio-items">
        <div class="col-sm-2 col-xs-12 portfolio-item penzion">
          <a href="images/fotogalerie/diana/352.jpg" title="Penzion a restaurace Diana" data-gallery>
            <img src="images/fotogalerie/diana/352.jpg" alt="Penzion a restaurace Diana"> </a>
        </div>
        <div class="col-sm-3 col-xs-12 portfolio-item kemp">
          <a href="images/our-team/member3.jpg" title="Kemp" data-gallery>
            <img src="images/our-team/member3.jpg" alt="Kemp"> </a>
        </div>
      </div>
     </div>

Could you help me? Thank you!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
