### ISSUE TITLE
Using isotope - Infinite scrolling with ajax call

### ISSUE THREAD

**Issue by sajpasa** [metafizzy/isotope#1045]
Hi, I am using isotope and have a infinite scrolling function implemented which uses ajax call to load the next pages. When ever the second page is loaded the items of second page appear behind the current items (overlaps, and the JS is not being applied to the items in new page), however when i scroll to the bottom of the page it runs the JS code and everything seems fine. 

Isotope
```
 $(document).ready( function() {
  var container = $('.grid')
  container.imagesLoaded( function() {
    container.isotope({
      // layoutMode: 'packery',
      itemSelector: '.grid-item',
      layoutMode: 'moduloColumns',
      moduloColumns: {
        columnWidth: 1,
        gutter: 1
      }
    });
  });

});

```
Thanks

**Comment by desandro** [comment]
Can you post your infinite scroll code? Or better yet, provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues)

**Comment by sajpasa** [comment]
Hi here is my infinite scroll code.
```
var didScroll = false; //Checking if user is scrolling then = true
 var page = 1;
 var totalHeight;  //total height of the whole page
 var visibleHeight; //visible height of the page

 $(window).scroll(function(){
   didScroll = true;  //if user is scrolling then set didscroll to true
 });

 setInterval(function(){
   if (didScroll) {
     didScroll = false;
     totalHeight = document.body.offsetHeight; //setting height of total page
     visibleHeight = document.documentElement.clientHeight; //setting height of the page- current view

     if (window.pageXOffset !== undefined) {  // All browsers, except IE9 and earlier
       currentScrollEnd = (window.pageYOffset !== undefined) ? window.pageYOffset : (document.documentElement || document.body.parentNode || document.body).scrollTop;
     } else {   // IE9 and earlier
       currentScrollEnd = (document.documentElement.scrollTop !== undefined) ? document.documentElement.scrollTop : (document.documentElement || document.body.parentNode || document.body).scrollTop;
     }

     // currentScrollEnd = (window.pageYOffset !== undefined) ? window.pageYOffset : (document.documentElement || document.body.parentNode || document.body).scrollTop;
     if(page < <?php echo $this->Paginator->counter('{:pages}');?>) {
       // console.log(totalHeight);
       // console.log(currentScrollEnd);
       console.log(visibleHeight);
       if (totalHeight - 400 <= currentScrollEnd + visibleHeight) { //comparing screen height to decide if new page should load or not
         page++;
         getItem(page); //calling fucntion getItem
       }
     }
   }
 },250);

function getItem(page){
   var url = getNextPageUrl(page); //calling function getnextpage

   $('.loader_area').show();  //show loading message when page is loading
   $.ajax({
     url: url,
     type: "GET",
     cache: false,
     success : function(html){
       appendProjects(html); //calling function appendProjects
     }
   });
 }

 function getNextPageUrl(page){
   var pathname = window.location.pathname;
   var params = parseQueryString();
   var nextPage;
   var newParams;
   params.page = page;
   newParams = $.param(params);
   nextPage = pathname + '?' + newParams;
   // console.log(nextPage);
   return nextPage;
 }

 function parseQueryString(){
   var queryString = window.location.search.substr(1); 
   var queryStringArray = queryString.split ("&");
   var params = {};
   for ( var i = 0; i < queryStringArray.length; i++) {
     var tmparr = queryStringArray[i].split("=");
     params[tmparr[0]] = tmparr[1];
   }
   return params;
 }

 function appendProjects(html){
   $('.searchResultsWrapper').append(html);
   $('.loader_area').hide();

 }

 $(document).ready(function(){
   if (totalHeight - 300 <= visibleHeight && page < <?php echo $this->Paginator->counter('{:pages}');?>){
     page++;
     getItem(page);
   }
 });
```

**Comment by sajpasa** [comment]
Hi do you require any further info?

**Comment by desandro** [comment]
try replacing your `appendProjects` code with:

``` js
// init Isotope first
var $container = $('.grid').imagesLoaded( function() {
  $container.isotope({
    itemSelector: '.grid-item',
    layoutMode: 'moduloColumns',
    moduloColumns: {
      columnWidth: 1,
      gutter: 1
    }
  });
});

function appendProjects( html ){
 // make jQuery object
 var $html = $(html);
 // append new items after images loaded
 $html.imagesLoaded( function() {
   $container.append( $html );
   $container.isotope( 'appended', $html );
   $('.loader_area').hide();
 });
}
```

1. I recommend setting `columnWidth` to multiple of the item width. Setting it to 1 means that the layout algorithm will have to make thousands of calculations for each item
2. New content should be appended to the same element that Isotope is being initialized on.

**Comment by sajpasa** [comment]
Hi,
Firstly thanks for your help. 
I have done the changes you suggested. 
Before i was having problem with the first set of results retrieved from the ajax call. By making the changes you suggested that has been fixed. First set to of results retrieved is perfect (does not overlap). However, now i am getting this error
`cannot call methods on isotope prior to initialization; attempted to call 'appended'`
on other set of results retrieved from ajax. 
So the first set of results retrieved are fine and any thing after than is messing up. This is opposite of what i had before. Before i was able having problem with the first set of results and others were fine.
Thank you again for your help.

**Comment by sajpasa** [comment]
Hi
Firstly thank you for your help.
I have done the changes you have suggested. And now I am not longer having issue with the first set of results retrieved from the ajax call. The first set of results work perfectly. However, all the set of results after the first set gives me this error.
`cannot call methods on isotope prior to initialization; attempted to call 'appended'`
Before I was having problem with the fist set of of results retrieved from ajax, which is now fixed but I am now get this error for any set of results after the first one.
Thank you again for the help.

**Comment by sajpasa** [comment]
Sorry my bad, i still had some old code on my ajax layout. Worked fine after i removed them.
Thank you! I have been stuck on this for few days now! Your a saviour!!
