### ISSUE TITLE
unclear how to disable ALL styling & animations

### ISSUE THREAD

**Issue by kn00tcn** [metafizzy/isotope#1046]
i only need the filter, it doesnt seem like there are options to disable the rest of the features... do i have to modify the plugin to remove functions at the moment?

edit: i am also integrating with a pagination function... but i think i almost got it working, as long as the css file !important will always override the inline styles that isotope generates

edit2:
`isResizeBound: false,`
`isInitLayout: false,`
`transitionDuration: 0`

`#container {`
`	position: static !important;`
`	height: auto !important;`
`	min-height: auto !important;`
`}`

`.item {`
`	position: static !important;`
`	top: auto !important;`
`	left: auto !important;`
`}`

**Comment by desandro** [comment]
Take a look at https://github.com/metafizzy/isotope/issues/675#issuecomment-40675160 is this what you're looking for?

**Comment by kn00tcn** [comment]
the container still appears to be getting a min-height & items get transitions, i'm looking for a completely minimal toggle of display:none on items with not a single further calculation or dynamic change

why create a 'none' layout when there's isInitLayout: false?

i just hope my !important works in all browsers

**Comment by desandro** [comment]
If you don't want any Isotope functionality accept for filtering, then you are likely better off writing your own code to do it.

``` js
var $items = $('.grid-items');

function filter( selector ) {
  $items.filter( selector ).show();
  $items.not( selector ).hide();
}
```

**Comment by kn00tcn** [comment]
do you mean to not use isotope or to make my own helper function for isotope?

so the reason i'm using isotope is i need a combination filter, i'm currently based on your example from some time ago http://codepen.io/desandro/pen/btFfG since i wouldnt be able to figure out the logic by myself at this stage (or within deadline)

right now i've taken your example, added a 'no results found' feature & integrated it with https://luis-almeida.github.io/jPages/ along with the css overrides & isotope options i mentioned earlier...

it's a bit of a frankenstein but it seems to work, maybe that's good enough for now

this sounds more like a feature request by now, styles & animations are what i want to be cleanly inactive, this time i am using filtering while another person may be using sorting, it's like i envision modular features (although i suppose if someone just wanted the layout engine, they could just use masonry or packery instead of isotope)

it's a really cool package anyway, thanks for your quick replies here & in some of the other threads i've seen

(fun fact: this is actually the third sorting engine i used in mere days while trying to deliver what the client wants, i'm so relieved that it appears to work)

**Comment by desandro** [comment]
Combination filter stuff is for creating complex selectors. You can use combination filters with the basic no-Isotope code. See demo: http://codepen.io/desandro/pen/c72ec4477f913f82d32f18e4a738a697

**Comment by kn00tcn** [comment]
wow... i sure look like i dont know what i'm doing

thank you so much! after a bit of fiddling, i got it integrated with my if statement inside the filter function

```
	if ( !$items.filter(selector).length ) {
		$('#filter-message').addClass('active animated fadeIn').html('<h2>No results found...</h2></div>');
		destroyPagination();
	}else {
		$('#filter-message').removeClass('active animated fadeIn').html('');
		destroyPagination();
    	setPagination();
	}
```
