### ISSUE TITLE
appended and insert not working with string content

### ISSUE THREAD

**Issue by ricnunes** [metafizzy/isotope#1047]
Hello,

First, I'm sorry if this is a duplicate. I did found a couple of issues here regarding this, but most of them did not had an example.

For some reason, both methods aren't working. I've added a callback to both while testing and they are never executed.. 

I found a way around the issue, but it sucks.

Any idea what I can do?

[http://d.crabcreative.com/vapeaware_dev/test-loadmore.html](url)

test cases: 

append - [http://codepen.io/ricnunes/pen/PNYmmr](url)

insert - [http://codepen.io/ricnunes/pen/dMbWRq](url)

**Comment by ricnunes** [comment]
Made it work.
Instead of adding new content from a new random element from jscript, I'm copying a random element that already exists and cloning it.

My guess is that isotope is thinking I'm adding a string, and that is what makes it fail.

**Comment by desandro** [comment]
Yes, that's the issue

``` js
// doesn't work
// content gets appended, but not added as Isotope item
var content = '<div class="grid-item"></div>'
$grid.append( content ).isotope( 'appended', content )

// works
// make into jQuery object
var $content = $('<div class="grid-item"></div>')
$grid.append( $content ).isotope( 'appended', $content )

**Comment by Splendorr** [comment]
Holy smokes! This just alleviated a day of frustration. I was generating a template with Handlebars, and neither "appended" nor "insert" would produce any results or errors. Just nothing happened! Finally, wrapping the template call in a $() jQuery wrapper, as shown, got it working.

And I can see now that the "insert" example *does* wrap the string in $(), but it's a fairly complex example, and could perhaps use a comment to the effect that passing strings won't work?

In any case, thank you for this solution!

**Comment by djary** [comment]
just say , save my life !

**Comment by desandro** [comment]
Added to docs under appended http://local/isotope-docs/build/methods.html#appended

**Comment by chriso0710** [comment]
Thanks for adding this to the docs! Essential detail when working with client side templates.

Nevertheless it just cost me an hour to fix my error with a handlebars template and a jquery 1.9 bug with newlines at the beginning of the string returned by handlebars

http://stackoverflow.com/questions/14347611/jquery-client-side-template-syntax-error-unrecognized-expression
