### ISSUE TITLE
How to set Sort by Date

### ISSUE THREAD

**Issue by SerNeo** [metafizzy/isotope#105]
Hi I was wondering if isotope can Sort by Date?

**Comment by sjoerdvalk1991** [comment]
Thnx @iamkeir I used your code for a date-based isotope!

**Comment by iamkeir** [comment]
:) :) :+1:

**Comment by JuliaMerquior** [comment]
@iamkeir 

Hi, could tell me what am I doing wrong? Thnx!


<!doctype html>
<html class="export">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width">
  <meta name="description" content="filter &amp; sort magical layouts">

  <title>Isotope</title>

    
    <link rel="stylesheet" href="css/isotope-docs.css" media="screen">

  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@metafizzyco">
  <meta name="twitter:url" content="http://isotope.metafizzy.co/index.html">
  <meta name="twitter:title" content="Isotope">
  <meta name="twitter:description" content="filter &amp; sort magical layouts">

  
  <script>
  var $grid = $('.grid').isotope({
getSortData : {
 name : function ( $elem ) {
  return $elem.find('time').attr('data-time');
 }
},
sortBy : 'name',
sortAscending : false
});
  </script>
  
  
</head>
<body class="page--index" data-page="index">
<div class="hero">
<div class="primary-content">
<div class="big-demo" data-js-module="hero-demo">

  <div class="ui-group">
    <h3 class="ui-group__title">Filter</h3>
    <div class="filters button-group js-radio-button-group">
      <button class="button is-checked" data-filter="*">show all</button>
      <button class="button" data-filter=".metal">metal</button>
      <button class="button" data-filter=".transition">transition</button>
    </div>
  </div>
  <div class="ui-group">
    <h3 class="ui-group__title">Sort</h3>
    <div class="sort-by button-group js-radio-button-group">
      <button class="button is-checked" data-sort-by="original-order">original order</button>
      <button class="button" data-sort-by="name">name</button>

    </div>
  </div>

  <div class="grid">
      <div class="element-item transition metal " data-category="transition">
        <data class="name" data-time="2016-12-02">02/12/2016</data>
      </div>
      
      <div class="element-item metalloid " data-category="metalloid">
         <data class="name" data-time="2015-05-02">02/05/2015</data>
      </div>
      
      <div class="element-item post-transition metal " data-category="post-transition">
         <data class="name" data-time="2015-05-01">01/05/2015</data>

      </div>
      
      <div class="element-item post-transition metal " data-category="post-transition">
         <data class="name" data-time="2012-02-03">03/02/2012</data>
      </div>
      
      <div class="element-item transition metal " data-category="transition">
         <data class="name" data-time="2016-12-01">01/12/2016</data>
      </div>
      


  </div>

   

</div>

  </div> 

</div> 






<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/jquery.min.js"><\/script>')</script>

  <script src="js/isotope-docs.min.js"></script>


</body>
</html>
