### ISSUE TITLE
isotope with a filter activated onload with a php var

### ISSUE THREAD

**Issue by jpbond13** [metafizzy/isotope#1051]
Hello,
i'm looking for a way to activate a filter by default with a php var.
Basically, i have an isotope, with filters via radio button. By default, my page is loaded without any filter activated. And on my page, i can click one of my radio button to filtering. But, i would like to be able to access on this page with a filter actived, as a variable in my URL : www.mywebsite.com//list-items.php?id_region=south (.south is my filter).

For this, i'm using this code :

`<script type="text/javascript">
		jQuery(document).ready(function () {
		'use strict';	
			var $container = jQuery('.isotope-container').imagesLoaded
			( function()
				{
				  $container.isotope(
				  {
					//filter: '.south'
					filter: '.<?php echo $id_region; ?>'
				  });
				}
			);
		});
	</script>`

This code is placed before the call of my script.js, witch is containing : 

	var $checkboxes = $('#isotope-filters input');
	/* activate jquery isotope */
	var $container = jQuery('#posts').isotope
	(
		{
		  itemSelector : '.item',
		  isFitWidth: true
		}
	);

	$checkboxes.change
	(
		function()
		{
			// initialise
			var filterValue = [];
			// value from checkboxs or radio button
			$checkboxes.filter(':checked').each
			(
				function()
				{
					filterValue.push( this.value );
				}
			);
			
			filterValue = filterValue.join('');
			$container.isotope({ filter: filterValue });
		}
	);

But it doesn't work. Filter is not activated.

Any help please ?

best regards

**Comment by desandro** [comment]
Sorry, but I'm not able to view your site. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by jpbond13** [comment]
Thanks for your answer.
I made 2 examples : 
Here is the first one with a filter activated by default in the isotope.js (.sud) in the imageloaded function :
http://chine-exclusive.com/isotope.php
All results are loaded, and, at the end of the images loading, the filter is applied. Only 2 results stay visibles.
The filter is working when it's in the isotope.js (but it's not dynamic)

here is the second example : 
same base, but i sent a php var into the URL, and the php var is applied in the js function inside the php file (and not in the isotope2.js).
http://chine-exclusive.com/isotope2.php?id_region=sud
All results are loaded, but the dynamic filter is not applied. But, when i check the HTML code, the php var is well converted inside the js function

I don't understand why the js function doesn't work when it's inside the HTML file, but works fine when it's in the js file. I think it's because some functions orders, but i'm not sure...
i tried to insert the js imageloaded function before (this example) or after the called isotope2.js but it's worse when it's after...nothing is displayed.

Thanks for your help and your time
(sorry for my english)

**Comment by desandro** [comment]
Looks like you're missing some brackets at the end

``` js
jQuery(document).ready(function () {
  'use strict';

/* Isotope Portfolio */
  var $container = jQuery('.isotope-container').imagesLoaded
  ( function()
    {
      $container.isotope(
      {
      filter: '.sud'
      });
    }
  );
});
```

**Comment by jpbond13** [comment]
sorry for my mistake.
i've corrected it but now nothing is displayed at all :
http://chine-exclusive.com/isotope2.php?id_region=sud

**Comment by desandro** [comment]
You are initializing Isotope twice on two different elements. In the page HTML

``` js
jQuery(document).ready(function () {
  'use strict';

/* Isotope Portfolio */
  var $container = jQuery('.isotope-container').imagesLoaded
  ( function()
	{
	  $container.isotope(
	  {
		filter: '.sud'
	  });
	}
  );
});
```

And i n isotope2.js:

``` js
jQuery(document).ready(function () {
    'use strict';

/* checkboxes et radio */
	var $checkboxes = $('#isotope-filters input');

	/* activate jquery isotope */
	var $container = jQuery('#posts').isotope
	(
		{
		  itemSelector : '.item',
		  isFitWidth: true
		}
	);

	$checkboxes.change
	(
		function()
		{
			// initialisation
			var filterValue = [];
			$checkboxes.filter(':checked').each
			(
				function()
				{
					filterValue.push( this.value );
				}
			);
			
			filterValue = filterValue.join('');
			$container.isotope({ filter: filterValue });
		}
	);
	
/* fin checkboxes et radio */	
							
});
````

The best way forward to remove the HTML/PHP JS code and change isotope2.js to:

``` js
jQuery(document).ready(function () {
    'use strict';

/* checkboxes et radio */
	var $checkboxes = $('#isotope-filters input');


	function getIdRegionParam() {
		var params = {};
		location.search.slice(1).split('&').forEach( function( param ) {
			var parts = param.split('=');
			var key = parts[0];
			var value = parts[1];
			params[ key ] = value;
		});
		return params.id_region;
	}

	var idRegionParam = getIdRegionParam();
	if ( idRegionParam ) {
		// select matching checkbox
		$checkboxes.filter('[value="' + idRegionParam + '"]');
	}

	/* activate jquery isotope */
	var $container = jQuery('#posts').isotope
	(
		{
			filter: idRegionParam,
			itemSelector : '.item',
			isFitWidth: true
		}
	);

	$checkboxes.change
	(
		function()
		{
			// initialisation
			var filterValue = [];
			$checkboxes.filter(':checked').each
			(
				function()
				{
					filterValue.push( this.value );
				}
			);
			
			filterValue = filterValue.join('');
			$container.isotope({ filter: filterValue });
		}
	);
	
/* fin checkboxes et radio */	
							
});
```

Then you can use URL's like http://chine-exclusive.com/isotope2.php?id_region=.sud  Note it's `.sud` not `sud`
