### ISSUE TITLE
Layout spacing issues (randomly)

### ISSUE THREAD

**Issue by SpabRice** [metafizzy/isotope#1054]
Hello,

when using isotope a always have slightly "spacing" issues between the different tiles.

Example:
If I give the items a right/bottom margin (2px for example), the margin is randomly different. (see screenshot)
This might vary using/changing different screen sizes, but it's never the same for all tiles which isn't really clean.

Even when I have no margin at all, I sometimes see very slight spacing between some items.  (It's less than 1 pixel but it's visible)

<img width="1130" alt="tiles-margin" src="https://cloud.githubusercontent.com/assets/1308858/13525742/653bf4a2-e203-11e5-9945-839d5d64e6c7.png">

**Comment by desandro** [comment]
Thanks for reporting this issue. See canonical issue https://github.com/metafizzy/isotope/issues/916#issuecomment-108899516

Closing here.
