### ISSUE TITLE
Downloads von Download-Artikel werden nicht angezeigt

### ISSUE THREAD

**Issue by eisermann-verlag** [metafizzy/isotope#1055]
Hello,

in our online-shop based on isotope the customers do not see the downloads of an download-article. I reset the templates an there are no change on the site.

What can I do?

i.A. Eike Schlüter

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
