### ISSUE TITLE
Apparent dependency issue

### ISSUE THREAD

**Issue by p2made** [metafizzy/isotope#1057]
Attempting to install isotope >=2 using Composer gives the following report...

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bower-asset/isotope v2.0.0 requires bower-asset/get-size >=1,<2 -> no matching package found.
    - bower-asset/isotope v2.0.1 requires bower-asset/get-size >=1,<2 -> no matching package found.
    - bower-asset/isotope v2.1.0 requires bower-asset/get-size >=1.1.8,<1.3 -> no matching package found.
    - bower-asset/isotope v2.1.1 requires bower-asset/get-size >=1.2.2,<1.3 -> no matching package found.
    - bower-asset/isotope v2.2.0 requires bower-asset/get-size ~1.2.2 -> no matching package found.
    - bower-asset/isotope v2.2.1 requires bower-asset/get-size ~1.2.2 -> no matching package found.
    - bower-asset/isotope v2.2.2 requires bower-asset/get-size ~1.2.2 -> no matching package found.
    - Installation request for bower-asset/isotope >=2 -> satisfiable by bower-asset/isotope[v2.2.2, v2.2.1, v2.2.0, v2.1.1, v2.1.0, v2.0.1, v2.0.0].

I have get-size 2.0.2 installed.

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm sorry to say that Isotope does not currently support Composer.

**Comment by p2made** [comment]
Sorry, I should have made clear. I was installing as a bower asset, & so from bower.io. My get-size is also installed as a bower asset.

**Comment by desandro** [comment]
Installing Isotope v2.2.2 with `bower install isotope` should install Isotope and its compatible dependencies. Here's what I got:

```
isotope#2.2.2
fizzy-ui-utils#1.0.1 (latest is 2.0.1)
doc-ready#1.0.4
matches-selector#1.0.3
get-size#1.2.2 (latest is 2.0.2)
get-style-property#1.0.4
masonry#3.3.2 (latest is 4.0.0)
outlayer#1.4.2 (latest is 2.0.1)
eventie#1.0.6
eventEmitter#4.3.0
```

Several libraries, like `get-size`, have had major updates but installing Isotope v2 should install compatible versions.

**Comment by desandro** [comment]
Isotope v3 has been released, so this issue may already be outdated. Closing now. Please open a new issue if you run into dependency version conflicts.
