### ISSUE TITLE
IE Issues

### ISSUE THREAD

**Issue by MattR11** [metafizzy/isotope#1058]
Hi,

I have an issue with Isotope.js that I have downloaded the code from http://isotope.metafizzy.co

The webpage I am working on is www.evolutionpowertools.com/exploretherange/
No issues on any other browser that I have tested except all versions of Internet Explorer.

The 3 ranges you can click on are 'Industrial, Construction or DIY'. When I click on any of these 3 options on Chrome (for example) the next set of options opens up using a javascript. In IE the next set options does not open up. I have ruled this JS out as being a possible cause of the problem. It is definitely the isotope.js. It seems as though IE does not recognise the ' <button class="button" data-filter=".steel"> '

Any help on this would be great!
Is there issues with IE and the isotope.js?

Thanks
Matt

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
