### ISSUE TITLE
Filtering with a drop-down menu

### ISSUE THREAD

**Issue by ghost** [metafizzy/isotope#106]
Just thought I would share with everyone on how to use filtering Isotope with a drop-down menu. 

Pretty similar to sorting with check boxes as seen here: http://jsfiddle.net/desandro/bb2PW/

So here is how you do it with a drop-down menu: http://jsfiddle.net/trewknowledge/jJZEN/

Cheers!

**Comment by JohnLauber** [comment]
This fiddle worked great. You do have an extra ';' in it, but it didn't affect anything.

**Comment by srikanthlavudia** [comment]
@vangelis183 here is the simplified js fiddle that I've come-up with multiple select dropdowns, well I have just tried with couple dropdowns

https://jsfiddle.net/srikanthLavudia/oj6z4fu8/14/
