### ISSUE TITLE
How can I implement both sorting and combination filtering at the same time?

### ISSUE THREAD

**Issue by archifox89** [metafizzy/isotope#1061]
Im having difficulty trying to integrate sorting with combination filtering. This is exactly what I want to acheive (minus the hash histroy): http://isotope.metafizzy.co/v1/tests/combo-sort-history.html#sortBy=original-order&comboFilters%5Bcolor%5D=&comboFilters%5Bsize%5D= 

However there is no link to codepen like other examples on the main site, in addition to it being an example from the older version of isotope. Is there any documentation (or codepen example) on how I can achieve this with the new version of isotope?

**Comment by desandro** [comment]
Here you go: http://codepen.io/desandro/pen/bpBYGB

**Comment by archifox89** [comment]
Thanks! :)
