### ISSUE TITLE
Jump to element after resorting the layout

### ISSUE THREAD

**Issue by JonasLoerken** [metafizzy/isotope#1062]
I'm using a cute little script to jump to an element by clicking on it.
```
$('.image-only').click(function () {
      $(this).parent().toggleClass('scale-image');
      $(".grid-item").not($(this).parent()).removeClass('scale-image');
      $grid.isotope('layout');
      $('html, body').animate({
          scrollTop: $(this).offset().top - 100
      }, 400);
});
```
The script works quite fine with one single issue. I'm using Isotope for ordering/sorting the images. If the user click on an item, the image scales up ($(this).parent().toggleClass('scale-image');) and the grid is resorting ($grid.isotope('layout');). The jQuery moves the viewport to the old position of the element, so it's not correct.

[Have a look here](http://relaunch.headonline.de/projekte/is-leuchten-planungs-und-beratungsordner/)! (click on one of the images below)

Is there a way to correct it?

**Comment by desandro** [comment]
Try this code:

``` js
$('.image-only').click(function () {
  var $this = $(this);
  var $parent = $this.parent().toggleClass('scale-image');
  $(".grid-item").not( $parent ).removeClass('scale-image');
  $grid.isotope('layout');
  var item = $grid.isotope( 'getItem', this );
  $('html, body').animate({
    scrollTop: $grid.offset().top + item.position.y - 100
  }, 400);
});
```

It uses the position of the Isotope Item set after `.isotope('layout')`

**Comment by JonasLoerken** [comment]
Thanks for your quick response, desandro!

Unfortunately the snippet isn't working. The site always jumps to the top! I've updated the link so you can check it out :)

**Comment by desandro** [comment]
I've updated the snippet, try again!

**Comment by JonasLoerken** [comment]
Works so smooth! Thanks a lot! :-)
