### ISSUE TITLE
Item disappear after reordering from random to original-order

### ISSUE THREAD

**Issue by olivierpons** [metafizzy/isotope#1063]
I wanted to have a fun thing: shuffle all items once, then re-order them so the user sees always the same order, but with a nice "shuffling effect" before.
If copy/paste this "simple" sample, you'll see a bug: one of the item disappear all the time (with 8 items that are the same size, and that take 2 lines x 4 items on each. When you manually resize, the item that disappeared goes back to the right place!
```
$(document).ready(function() {
    var g = $('.grid');
    g.isotope({
        itemSelector: '.grid-item',
        layoutMode: 'fitRows',
        transitionDuration: '1s'
    });
    g.isotope('once', 'arrangeComplete', function() {
        g.isotope({ sortBy : 'original-order' });
    });
    g.isotope({ sortBy : 'random' });
    /*
    var j = $('.grid-item').length*10;
    $('.grid-item').each(function() {
        console.log(j);
        $(this).css('z-index', j--);
    });
    */
});

```

Here's my CSS in case you need it:

```
.grid-item {
    position: relative;
    float: left;
    width: 400px;
    height: auto;
    margin: 10px 5px 0;
    padding: 0;
    background: 0;
    color: #262524;
    transition: background 0.4s, box-shadow 0.4s;
}
.grid-item a, .grid-item a:hover {
    color: black;
}
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by olivierpons** [comment]
There we go:

http://codepen.io/anon/pen/jqmVmJ

I've just added the following code, which is almot copy/paste from the code above.

```
    var g = $container;
    g.isotope('once', 'arrangeComplete', function() {
      g.isotope('once', 'arrangeComplete', function() {
        g.isotope({ sortBy : 'original-order' });
      });
      g.isotope({ sortBy : 'original-order' });
    });
    g.isotope({ sortBy : 'random' });
```

**Comment by desandro** [comment]
The missing item is being positioned behind another item. So there's likely a layout conflict happening. This is hard to resolve as you're trigging another layout immediately while the previous one just finished. One way to resolve this is to add 1 frame delay via `setTimeout` so the previous layout can complete before triggering the next one. [See demo on CodePen](http://codepen.io/desandro/pen/716e0dd3ad96490474154bf53ec36427/)

``` js
    var g = $container;
    g.isotope('once', 'arrangeComplete', function() {
      setTimeout( function() {
        g.isotope({ sortBy : 'original-order' });  
      })
    });
    g.isotope({ sortBy : 'random' });
```

**Comment by olivierpons** [comment]
Thank you very much, it works like a charm!
