### ISSUE TITLE
Isotope('layout') not working when slidingout items with velocity.js

### ISSUE THREAD

**Issue by regenrek** [metafizzy/isotope#1064]
Hi, i got some problems with isotope when i slideout items.
It looks like like that sliding out (or whatever effect) does remove
the layout information on items.

When I try to relayout items nothing happens. I'm using pagejs for content switching (https://github.com/visionmedia/page.js)

The animation effect works pretty well without the page.exit function.
But I want some cool slideout effect on leaving the page.

```
page('/work', function(ctx, next) {

        var animOpts = {
          duration: 1000,
          stagger: 100, // delay anim for each element
          drag: true,
          backwards: false
        };

        worksgrid.isotope({
            //layoutMode: 'packery', // tried it with masonry and packery
            itemSelector: '.work-item',
            transitionDuration: '0s',
            gutter: 0,
            masonry: {
              columnWidth: '.grid-sizer'
            }
        });

        // on image load
        worksgrid.imagesLoaded(function() {
          console.log('images loaded');
          // animate with a cool effect
          items.velocity('transition.slideUpIn', animOpts);
          worksgrid.isotope('layout');
          console.log('relayout');
        });

});
```

`<div class="work-item" style="position: absolute; left: 426px; opacity: 1; top: 0px; display: block; transform: translateY(0px);"></div>`

```
    // hide images if we leave the work page
    page.exit('/work', function (ctx, next) {

      var animOpts = {
        duration: 200,
        stagger: 50, // delay anim for each element
        drag: true,
        backwards: true,
        complete: function() {
            console.log('anim_complete');
            next();
          }
      };
      
      console.log('exit work page');
      items.velocity('transition.slideDownOut', animOpts);
    });
```

When I leave the page everything is hidden and the position information is still
there. But then when I call the "show work" function again the html markup looks
like this.

`<div class="work-item" style="position: absolute; left: 0px; opacity: 1; top: 0px; display: block; transform: translateY(0px);"></div>`

I took some useful code from here https://github.com/metafizzy/isotope/issues/727

Regards,
Kevin

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by regenrek** [comment]
Yeah sure... 

but it works in the test case. That kinda sucks :)

http://codepen.io/kkern/pen/dMWYgr

*) If u click on "work" - the slideUp effects shows up. 
*) Then if you click on home or work again the slidedown Effect occurs. 
*) Last if you click on work again, the layout seems good.

Here is a screenshot of my work:

works
![image](https://cloud.githubusercontent.com/assets/5182020/13967194/38b47b44-f076-11e5-8ce6-b1810920b000.png)

not working after visiting / loading work again
![image](https://cloud.githubusercontent.com/assets/5182020/13967157/fe38ccb8-f075-11e5-8c0e-abb27ff59a89.png)

**Comment by regenrek** [comment]
I created some workaround. This seems to work.
I added a variable loaded to the work function. 

https://codepen.io/kkern/pen/VabyXv

It's strange because it should work without this variable, but its fine for me now

**Comment by desandro** [comment]
I tried taking a look at this, but it's hard to debug with three libraries working together: velocity, page.js, imagesLoaded, and Isotope. Sorry, but I won't be able to provide support for this request as is. If you can isolate where the issue is I can take another look.

**Comment by regenrek** [comment]
Hi nevermind, I solved the case with this kind of workaround. 
Its fine for me now. 

I close this issue now !
Thank you.
