### ISSUE TITLE
Align grid with percent and pixel sizes

### ISSUE THREAD

**Issue by MorenoDiDomenico** [metafizzy/isotope#1065]
Hello,

I can't figure out how to achieve a perfect layout with Isotope.

This is my demo: http://codepen.io/MorenoDiDomenico/pen/MymYRx
The red image isn't aligned with the side images.

How can I fix this?

Thanks.

**Comment by desandro** [comment]
The trouble is that you're mixing percent sized items with pixel sized padding. Notice that this issue is fixed if you removed padding: http://codepen.io/desandro/pen/3632db0696d36b262ee26423c00cbea0/

One way to resolve this is to set padding with percents, so its based on the width of the item. You'll have to do this for each differently sized item

``` scss
```

**Comment by MorenoDiDomenico** [comment]
Hi @desandro ,

thanks for your fast reply.

Unfortunately I can't change the source of the images, so I wrote this little JS to automatic add height to elements that has class 'grid-item--height-2'.

`  var $gutter = 20;
  
  function _calc(){
    $('.grid').each(function(i, e){
       var $grid = $(e);
      
      $grid.find('.grid-item').each(function(i,e){
         var $item = $(e);
         if($item.hasClass('grid-item--height-2')){
            var $columnWidth = $item.width();
            var $height = Math['ceil']((2 * Math.ceil($columnWidth / 2)) * 2) + $gutter;
           console.log($height);
           $item.find('.entry').css('height', $height);
         }
      });
    });
  }
  
  _calc();
  `

You can see it live here: https://codepen.io/MorenoDiDomenico/pen/ZWKGpz

What do you think about it?

**Comment by desandro** [comment]
I'd recommend CSS solutions before turning to JS. There might be another way to do this. Or maybe try removing padding - it's a different look, but easier to manage. Using JS with layout can be problematic. What happens when user resizes the window?

**Comment by MorenoDiDomenico** [comment]
I'm not sure that this is possible with only CSS, but this would be great.

I added a simple resize handler here: https://codepen.io/MorenoDiDomenico/pen/ZWKGpz (this can be written waaaaay better obv).
