### ISSUE TITLE
add the infinite scroll to the isotope display

### ISSUE THREAD

**Issue by jpbond13** [metafizzy/isotope#1067]
Hello and thanks for your Isotope script !
I'm using it to display a large quantity of images, and when i arrive on the page, it takes too long to load all of them. i saw your page with infinite scroll : http://isotope.metafizzy.co/v1/demos/infinite-scroll.html and i't exactly the way i would like to manage my page.
But i'm a little bit confused about using the appended method, and loading the next set of images (Ajax ?)...
Is there a detailled example on github perhaps or somewhere else to understand how to do it ?
best regards

**Comment by richgcook** [comment]
There's several issues already been opened and closed about the use of infinitescroll and isotope. That demo is from v1. Try searching the issues for infinitescroll (https://github.com/metafizzy/isotope/search?q=infinite&type=Issues&utf8=%E2%9C%93).

Let me know if you get stuck.

**Comment by jpbond13** [comment]
i read some examples with part of the code like this one : https://github.com/metafizzy/isotope/issues/1045
but any chance to find a global example with isotope v2 ? it could be helpful for beginners like me...

**Comment by richgcook** [comment]
I don't think there is any examples for v2 on the docs; but feel free to use something from a standard setup for me. The real issue is infinitescroll's docs. It's dated and so many different 'docs' kicking around. Took me a while to work it all out but hopefully this makes the process faster for you.

First part is simple isotope implementation. 
Second is infinitescroll (load as you scroll, not triggered load).

```
var $container = $('.news-container');
$container.imagesLoaded(function() {
    $newsContainer.isotope({
        itemSelector : '.each-article',
        layoutMode: 'masonry',
        transitionDuration: 0,
        masonry: {
            columnWidth: '.grid-sizer'
        }
    });
});

$('.news-container').infinitescroll({
    loading: {
        img: ''
    },
    navSelector: '.pagination-container',
    nextSelector: '.pagination-container span.next a',
    itemSelector: '.each-article'
}, function(newElements) {
    var $newElems = $(newElements).hide();
    $newElems.imagesLoaded(function() {
    $newElems.fadeIn();
    $('.news-container').isotope('appended', $newElems);
    });
});
```

**Comment by jpbond13** [comment]
Here is my initial code :


$j(window).load(function(){

	var $container = $j('#folio');
	// var $container = $('.news-container');

	if( $container.length )   {
	$container.isotope({
		itemSelector : '.folio-item'
	});

	$container.imagesLoaded(function() {
		$newsContainer.isotope({
			itemSelector : '.folio-item',
			layoutMode: 'masonry',
			transitionDuration: 0,
			masonry: {
				columnWidth: '.grid-sizer'
			}
		});
	});	
	

	var $optionSets = $j('#portfolio .folio-filter'),
		$optionLinks = $optionSets.find('a');
	$optionLinks.click(function(){
		var $this = $j(this);
		// don't proceed if already selected
		if ( $this.hasClass('selected') ) {
			return false;
		}
		var $optionSet = $this.parents('.folio-filter');
		$optionSet.find('.selected').removeClass('selected');
		$this.addClass('selected');
	// make option object dynamically, i.e. { filter: '.my-filter-class' }
	var options = {},
		key = $optionSet.attr('data-option-key'),
		value = $this.attr('data-option-value');
		
	// parse 'false' as false boolean
	value = value === 'false' ? false : value;
	options[ key ] = value;
		if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
		changeLayoutMode( $this, options );
	} else {
		// otherwise, apply new options
		$container.isotope( options );
	}    
	return false;
	});
	}
	
});

$j(window).bind('resize', function(e){ 
	  window.RT = setTimeout(function()  {$j('#folio').isotope('reLayout'); }, 800); 
	  });

**Comment by jpbond13** [comment]
and the adaptation from your example : 

$j(window).load(function(){

	var $container = $j('#folio');
	// var $container = $('.news-container');

	if( $container.length )   {
	$container.isotope({
		itemSelector : '.folio-item'
	});

	$container.imagesLoaded(function() {
		$newsContainer.isotope({
			itemSelector : '.folio-item',
			layoutMode: 'masonry',
			transitionDuration: 0,
			masonry: {
				columnWidth: '.grid-sizer'
			}
		});
	});	
	

	var $optionSets = $j('#portfolio .folio-filter'),
		$optionLinks = $optionSets.find('a');
	$optionLinks.click(function(){
		var $this = $j(this);
		// don't proceed if already selected
		if ( $this.hasClass('selected') ) {
			return false;
		}
		var $optionSet = $this.parents('.folio-filter');
		$optionSet.find('.selected').removeClass('selected');
		$this.addClass('selected');
	// make option object dynamically, i.e. { filter: '.my-filter-class' }
	var options = {},
		key = $optionSet.attr('data-option-key'),
		value = $this.attr('data-option-value');
		
	// parse 'false' as false boolean
	value = value === 'false' ? false : value;
	options[ key ] = value;
		if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
		changeLayoutMode( $this, options );
	} else {
		// otherwise, apply new options
		$container.isotope( options );
	}    
	return false;
	});
	}
	
	$('#folio').infinitescroll({
		loading: {
			img: ''
		},
		navSelector: '.pagination-container',
		nextSelector: '.pagination-container span.next a',
		itemSelector: '.folio-item'
	}, function(newElements) {
		var $newElems = $(newElements).hide();
		$newElems.imagesLoaded(function() {
		$newElems.fadeIn();
		$('#folio').isotope('appended', $newElems);
		});
	});	
	
});

$j(window).bind('resize', function(e){ 
	  window.RT = setTimeout(function()  {$j('#folio').isotope('reLayout'); }, 800); 
	  });

**Comment by jpbond13** [comment]
but i'm quite sure it's not enough...
and i don't understand how to adapt navselector and nextselector to my case

have a look to my complete example : http://40parallele.com/produits.php?id=4

Really thanks for your help and time !

**Comment by jpbond13** [comment]
i have no answer to my last question, and i've no issue. But i try to find an other way to think about this problem : What is your solution if you have a lot of items to display ? Pagination ? Infinite scroll ? an other solution ? I can't display only the first 20 items and stop, because filters will be not complete in this case, will it ?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. This sounds like an implementation issue. I'd recommend starting by putting together a [**reduced test case**](http://css-tricks.com/reduced-test-cases) to identify the issue. Then request support in the [Isotope support forum on CodersClan](https://www.codersclan.net/?repo_id=1).

**Comment by jpbond13** [comment]
i'm gonna try to work with lazyload too...thanks for your help
