### ISSUE TITLE
FitRows unexpected behavior ?

### ISSUE THREAD

**Issue by iandoe** [metafizzy/isotope#1069]
I am using `isotope-layout v2.2.2` and i am using the bootstrap grid and a 2px gutter, i want to use isotope to filter items out of the grid, but the layout itself (without having even filtered anything) appears to be borked. (or i am missing something)

Code and sample reduced test case (actual and expected behaviors) here : http://codepen.io/Wilhearts/full/MyEZbj/

![image](https://cloud.githubusercontent.com/assets/297547/14232057/4962e482-f9c5-11e5-84ba-c20b8926b942.png)

Thanks for your help.

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like you've initialized Isotope twice. Once in HTML `js-isotope` and once in JS. When you remove the HTML initialization, it works just fine. See demo http://codepen.io/desandro/pen/7bfe1616b324e2c95a1c29cee1b7c8e3

**Comment by iandoe** [comment]
Thanks for getting back to me, i am not sure i understand as in the pen you sent me, "expected" grid is not using isotope at all since it does not have a `js-isotope` class ?

**Comment by desandro** [comment]
Sorry about that. Take another look: http://codepen.io/desandro/pen/7bfe1616b324e2c95a1c29cee1b7c8e3

I've removed `gutter: 2`, as its not necessary. The visible gutter may be 1 or 2px, due to pixel rounding errors.
