### ISSUE TITLE
Filter callback doesn't work in 2.2.2 version

### ISSUE THREAD

**Issue by SpabRice** [metafizzy/isotope#1072]
Hello,

the callback when filtering seems not to work in version 2.2.2.
jQuery('#isotope-grid').isotope({ filter: selector }, function() { alert("Hello World"); });

It works fine though with on older version:
http://isotope.metafizzy.co/v1/jquery.isotope.min.js

Am I missing something?

**Comment by desandro** [comment]
Callbacks were removed in Isotope v2. Use [arrangeComplete event](http://isotope.metafizzy.co/events.html#arrangecomplete) instead

**Comment by SpabRice** [comment]
Thanks,  this works.
