### ISSUE TITLE
Isotope + LazyLoad

### ISSUE THREAD

**Issue by jpbond13** [metafizzy/isotope#1073]
Hello
i tried for some days to find a way to use isotope filtering with a big items to filter on the same page.
I tried infinite scroll, pagination but didn't find a way to work with it.
I would like to try lazyload. The goal is to reduce the time of loading images and be able to filter items without waiting for the page to load completely.

I tried to apply this method : 
[http://stackoverflow.com/questions/11337291/combining-jquery-isotope-and-lazy-load](url)
or
read this : 
[http://www.appelsiini.net/projects/lazyload](url)
or that : 
[http://jsfiddle.net/arthurc/ZnEhn/](url)
But i don't understand how to adapt to my example. If i use the data-original attribute for the image address, the Isotope doesn't work. 
i read : "You must set image dimensions either as width and height attributes or in CSS. Otherwise plugin might not work properly" but my website has to be responsive and images have no dimension set.

Here is an example where isotope works with a lot of items : 
[http://40parallele.com/produits.php?id=1](url)

Here is the same page with Lazyload script added to the code, without success : 
[40parallele.com/produits-test.php?id=1](url)
because Isotope filtering doesn't work anymore and lazyload doesn't work at all.

here is the structure for each image block : 
`<div class="folio-item col-md-4 isotope-item 4">
								<div class="p-item-inner">
									<img src="./userfiles/image/produits/1801059.jpg" class="img-responsive lazy" alt="img"> 
									<div class="overlay-wrap">
										<div class="overlay">
											<div class="overlay-inner">
												<a href="./userfiles/image/produits/1801059.jpg" class="fancybox" data-fancybox-group="gallery" title=""><i class="fa fa-plus"></i></a>
												<div class="space30"></div>
											</div>
										</div>
									</div>
								</div>
							</div>`

here is the js code for isotope and lazyload : 

$j(window).load(function()
{
	// lazyload
	var $win = $(window),
		$container = $j('#folio'),
		$imgs = $("img.lazy");

	// calcul la taille des images
	$imgs.each(function(index) {
        var item_height = $(this).attr("height");
        $(this).parent().parent().css("height",item_height);
    });

	
	if( $container.length )
	{
		$container.isotope(
		{
			itemSelector : '.folio-item'
		});
	
		var $optionSets = $j('#portfolio .folio-filter'),
			$optionLinks = $optionSets.find('a');
			
		$optionLinks.click(function()
		{
			var $this = $j(this);
			// don't proceed if already selected
			if ( $this.hasClass('selected') ) 
			{
				return false;
			}
			var $optionSet = $this.parents('.folio-filter');
			
			$optionSet.find('.selected').removeClass('selected');
			$this.addClass('selected');
			
			// make option object dynamically, i.e. { filter: '.my-filter-class' }
			var options = {},
			key = $optionSet.attr('data-option-key'),
			value = $this.attr('data-option-value');
		
			// parse 'false' as false boolean
			value = value === 'false' ? false : value;
			options[ key ] = value;
			
			if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) 
			{
				changeLayoutMode( $this, options );
			} else {
				// otherwise, apply new options
				$container.isotope( options );
			}    
			return false;
		});
	}
	
	$container.isotope({
		onLayout: function() {
			$win.trigger("scroll");
		}
	});
	
	$imgs.lazyload({
		failure_limit: Math.max($imgs.length - 1, 0)
	});
	
});
	
$j(window).bind('resize', function(e)
{
	window.RT = setTimeout(function() {$j('#folio').isotope('reLayout'); }, 800);
});

really thanks in advance for your help...i'm lost...

best regards

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
