### ISSUE TITLE
Item alignment is off on some filters

### ISSUE THREAD

**Issue by JacobLett** [metafizzy/isotope#1074]
Great plugin but I noticed some views have the items in the wrong position and show negative space in an odd location. Is there a setting to make sure all items are flush left to the top?

Here is an example: http://puu.sh/oehJ6/1da150b40f.jpg

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by JacobLett** [comment]
I resolved the issue by adjusting the css on the grid div to not have a float applied.
