### ISSUE TITLE
Jumping / Scrolling to container on pageLoad / refreshing

### ISSUE THREAD

**Issue by SpabRice** [metafizzy/isotope#1075]
I tried to find anything related on the docs, but couldn't see anything.

When Scrolling to the bottom of a page and then refreshing the page, it will jump/scroll to the isotope container.  I think this, it is intended by the script, but is there an option to deactivate this?

**Comment by desandro** [comment]
What's happening is that Isotope has to resize the container after items have been laid out. There is a split second when the container has 0 height. So the content is collapsed as the scroll position moves to the top of the container. Unfortunately, there is no good solution for this issue.
