### ISSUE TITLE
Gutter size contains different height

### ISSUE THREAD

**Issue by iamjonasmarlo** [metafizzy/isotope#1076]
Hey over there :)

I've got a little "problem" with the gutter sitze.
![grid_isotope_gutter_problem](https://cloud.githubusercontent.com/assets/8004195/14462240/62745ffc-00c6-11e6-8dce-bfe3f8d264fa.jpg)

In my case I got five grid-elements on my site. The first (1) and the last (5) one is half as large as the three elements in the middle (2 / 3 / 4). Element 1 and 5 are smaller anyway.

The problem: The elements in the middle are 100% + 100% + Gutter Size (1,5%) width. So grid-item 2, 3 and 4 are 201,5% width. Grid-item 1 and 5 are 100% width.

Is there any way to prevent it? For example by dividing the complete gutter-size.

Thank you :)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by JonasLoerken** [comment]
It's not really an issue. It's just a logic process which i would like to prevent :)

You can check it out: [Here](http://relaunch.headonline.de/projekte/renusol-nonverbale-montageanleitung/)

**Comment by desandro** [comment]
Sorry, but I am having trouble understanding what you are trying to fix. From your example, it appears the gutters are all equal

![screen shot 2016-04-13 at 9 12 19 pm](https://cloud.githubusercontent.com/assets/85566/14514198/91a92798-01bc-11e6-8f23-c39112ec858f.png)
