### ISSUE TITLE
Reset inline styles on resize

### ISSUE THREAD

**Issue by exodusanto** [metafizzy/isotope#1077]
Hi!

I use gsap + isotope, in resize event i noticed that some properties ( for example: transform and opacity) are reset with top/left property...

There is an option to prevent this issue ? 

Thanks!

**Comment by desandro** [comment]
No, there is no option to prevent Isotope from reseting styles. I recommend using separate elements for separate effects. For example `.grid-item` can be used for Isotope filtering, but `.grid-item-content` can be used for GSAP effects.

``` html
<div class="grid-item">
  <div class="grid-item-content">...</div>
</div>
```

**Comment by exodusanto** [comment]
I will try with your method @desandro,

Thank you!
