### ISSUE TITLE
Transition initial layout from top left

### ISSUE THREAD

**Issue by HisHandiwork** [metafizzy/isotope#1078]
Ok, I've Googled and searched everywhere to find out how to get my isotope items to fly in on page load like this example:

http://themes.tvda.eu/demos/rudermann/dark/portfolio.html

I now it has to do with translte3D transitions, but I have no idea how to use it.  I see it in isotope.pkgd.min.js.

Here's my isotope:

http://s213792.gridserver.com/event_type/banquets/

I'm probably missing something super obvious.

**Comment by desandro** [comment]
You can recreate that effect by hiding elements, initializing Isotope, then showing items, then layout again.  See demo http://codepen.io/desandro/pen/25d2a3d01d65235b8c49c14a85b082c5

**Comment by HisHandiwork** [comment]
Awesome, thanks so much!

**Comment by HisHandiwork** [comment]
Any idea why I'm getting this result?

http://s213792.gridserver.com/event_type/promotions/

It moves them to the right for a split second and then reverses direction.

**Comment by desandro** [comment]
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
