### ISSUE TITLE
Getting Filtered Items Without Affecting Content

### ISSUE THREAD

**Issue by adriandegar** [metafizzy/isotope#1079]
Hi David,

Brilliant work, thank you for Isotope. I'm trying to implement a Load More functionality with show/hide and I'm stuck affecting the layout twice.

Currently I'm obtaining the Isotope filtered items array by first filtering by whatever the user clicks. 
Then I loop through the array, show the first ten items, hide the rest, and then I call 'layout' to tidy everything up.

Is there a way I can obtain the hypothetical filtered items array without actually triggering the filtration?

**Comment by desandro** [comment]
You can use `getFilteredItemElements` to get an array of filtered elements, in current sorted order.

If you're using jQuery, Isotope uses `.is()` to filter for items. Similarly, you can use `.filter()` to filter for an retrieve that set.

``` js
$grid.find('.grid-item').filter( filterValue )
```

**Comment by adriandegar** [comment]
Thanks David, that works! Is there any way to update the 'filteredItems' array with the set you retrieve from .filter()?

**Comment by desandro** [comment]
`filteredItems` represents the items that Isotope has filtered. It gets updated every time you trigger [`.isotope()`](http://isotope.metafizzy.co/methods.html#arrange-isotope)
