### ISSUE TITLE
Filtering count

### ISSUE THREAD

**Issue by leamcg** [metafizzy/isotope#1084]
Hi!
As a follow-up of this issue: https://github.com/metafizzy/isotope/issues/175 ,
I was wondering if there was a way to have the amount of items with each filters:
ie:
blue(30)
red(12)
green(16)
oval(12)
circles(40)
square(23)

but for multiple filtering. So for example, if you've selected 'blue', I'd like that the amount of circles isn't 40 anymore, but the actual amount of rounds visible (so basically the blue circles).

also, I tried using this: `$filtered.filter('.blue').length` but it says that '.blue' is not a function 

thanks for your amazing work with isotope!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by leamcg** [comment]
Here: http://codepen.io/leamcg/pen/RaePOV
I forked the one on the isotope page example and basically, next to each filter, I'd like to see the amount of items there is, and if you click on the color red, the amount of items on the other filters will change in accordance to the shapes left.

**Comment by desandro** [comment]
Thanks for that! Here's one way to do it: http://codepen.io/desandro/pen/pyxwem/

I'm getting an array of the filtered item elements with [`getFilteredItemElements`](http://isotope.metafizzy.co/methods.html#getfiltereditemelements) (this method was just documented today with the release of Isotope v3 😁 ). Then, I loop through each button, and get the length of isotope-filtered items, filtered again with the button's filter.

``` js
function updateFilterCounts()  {
  // get filtered item elements
  var itemElems = $grid.isotope('getFilteredItemElements');
  var $itemElems = $( itemElems );
  $filterButtons.each( function( i, button ) {
    var $button = $( button );
    var filterValue = $button.attr('data-filter');
    if ( !filterValue ) {
      // do not update 'any' buttons
      return;
    }
    var count = $itemElems.filter( filterValue ).length;
    $button.find('.filter-count').text( '(' + count +')' );
  });
}
```

**Comment by leamcg** [comment]
thank you so much for your help!  🙌 🔥
