### ISSUE TITLE
Sorting numbers (km)

### ISSUE THREAD

**Issue by holhel11** [metafizzy/isotope#1085]
Hi, im trying to sort numbers that's shown in km with decimals. It's not working and looks like this after sorting: 
![skjermbilde 2016-04-28 kl 11 14 27](https://cloud.githubusercontent.com/assets/1552433/14881036/92f711f6-0d32-11e6-8a4d-984801d9cd40.png)

I need the lowest km number to appear first. My code looks like this:

$dealer_container.isotope({ sortBy: writeIt, sortAscending : false });  

Anyone have a fix on this?

Edit:

I removed the decimals and have numbers like 198, 8, 36 etc and it's still not working. Is this a bug?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by holhel11** [comment]
@desandro can I send you some more code on mail?

**Comment by desandro** [comment]
A codePen or jsfiddle showing the issue is best.

> A reduced test case clearly demonstrates the bug or issue.
> It contains the bare minimum HTML, CSS, and JavaScript required to demonstrate the bug.
> A link to your production site is not a reduced test case.
> Providing a reduced test case is the best way to get your issue addressed. Without a reduced test case, your issue may be closed.
