### ISSUE TITLE
Set vertical alignment of "cellsByRow" layout to 'top' instead of middle

### ISSUE THREAD

**Issue by kdoonboli** [metafizzy/isotope#1087]
By default "cellsByRow" layout displays the items in rows as if vertical alignment is set to middle. Is there a way to have the vertical alignment of "cellsByRow" layout to TOP?  

See image below. I want items to be aligned by that red line:
http://i.imgur.com/LFHZDum.jpg

Thanks a lot,

**Comment by dmsims** [comment]
Use:

`layoutMode:     'fitRows',`

**Comment by desandro** [comment]
Yup, you might want to try the [fitRows layout mode](http://isotope.metafizzy.co/layout-modes/fitrows.html)

**Comment by kdoonboli** [comment]
The reason I was interested in "cellsByRow" was because it supports items with different heights, "fitRow" can't handle that and it would create holes in a row as items get pushed down to the next row if they can't fit properly in the current row.
To fix this issue I decided to give all my items a fixed height in their outer wrapper.
thanks

**Comment by dmsims** [comment]
Just as an addendum:

To fix the holes (when using fitRows) you can use nth child css
