### ISSUE TITLE
V.3 broken with requirejs

### ISSUE THREAD

**Issue by hirasso** [metafizzy/isotope#1088]
Hi there! I know, no one is using requirejs anymore, but I sill do ;)
```javascript
requirejs( [
  'path/to/isotope.pkgd.js',
], function( Isotope ) {
  var iso = new Isotope( '.grid', {...});
});
```
...does not work with v.3 anymore.

**Comment by desandro** [comment]
Thanks for reporting this issue. Yup, this is a real bug. I unfortunately did not catch it until after the 3.0.0 release. Fix will be coming in the next release!

**Comment by hirasso** [comment]
yay! Finding bugs actually makes me proud :) Thanks for the fast response, as always.

**Comment by desandro** [comment]
v3.0.1 has been released with a fix for this issue. Thanks again! 🐻 🌈
