### ISSUE TITLE
visibleStyle

### ISSUE THREAD

**Issue by senojeel** [metafizzy/isotope#1089]
I am trying to use an accordion with isotope. The problem is that the items are absolute positioned. So when I expand an accordion, it works exactly as you would expect absolute items to work. I need them to be relative so it will push down the items below. I tried using visibleStyle to change the position to relative, but it doesn't seem to be working. Or I may be misunderstanding what that does. When I change hiddenStyle, I can see it change. 

Any ideas on if this is possible?

Here is my page...
http://woodlands.fishhookcms.com/kiosk/t_events.php

The filter is working for the dropdown Audience. 

Thanks!

**Comment by desandro** [comment]
>  I need them to be relative so it will push down the items below.

Sorry, Isotope does not support relative item positioning. [`visibleStyle` is useful if you want to disable transform on reveal/hide](http://isotope.metafizzy.co/options.html#hiddenstyle-visiblestyle).
