### ISSUE TITLE
Overlap after filter with fitWidth

### ISSUE THREAD

**Issue by MrHunter** [metafizzy/isotope#1090]
I seem to be running into an issue of my elements overlapping after they've been filtered then filtered back to all, I created a reduced test case for it to be seen here: http://codepen.io/MrHunter/pen/xVQvGg

I noticed though if you click the all filter a second time it will re-align the elements properly, does this have something to do with the element sizing?

**Comment by desandro** [comment]
Thank you for reporting this issue! This was a tricky one. Although the item's width is set to `570px` in CSS, when it gets revealed, it's measured by browser as `330px`. What I believe is happening is that the Isotope container is being resized with [`fitWidth`](http://isotope.metafizzy.co/layout-modes/masonry.html#fitwidth) down to `330px`. Items that are larger than the container are then measured to be no bigger than the container.

One solution is to remove `isFitWidth: true`. See demo http://codepen.io/desandro/pen/9d541fe0bfc7f9105c507940e82ce4d0/

This is a peculiar browser bug and rare edge case.

**Comment by MrHunter** [comment]
Hmm very strange, but thanks for the solution of removing the `isFitWidth: true` it work perfect.
