### ISSUE TITLE
Infinite Scroll And Appending New Items

### ISSUE THREAD

**Issue by narutoniue** [metafizzy/isotope#1091]
I currently append new items to my container using infinite scroll.  It is grabbing the new items fine.  However, the new appended items lack positioning, and so they overlap the items that are there on the initial page load.  This uses ruby as the backend codebase.

I cannot link directly to the site since it is internal code, but it looks something like follows:

**The JS:**
`// init Isotope
    var $container = $('.container');
    $container.isotope({
        layoutMode: 'fitRows',
        itemSelector: '.item',
        filter: '*',
        getSortData: {
            name: '.name',
            city: '.city',
            zip: function (itemElem) {
                var zip = $(itemElem).find('.zip').text();
                return parseFloat(zip.replace(/-/g, ''));
            }
        }
    });
    $container.infinitescroll({
        navSelector  : '#page-nav',    // selector for the paged navigation
        nextSelector : '#page-nav a',  // selector for the NEXT link
        itemSelector : '.item',     // selector for all items you'll retrieve
        bufferPx     : 50,
        loading: {
          finishedMsg: 'No more pages to load.',
          img: 'imgnotfound.gif'
        }
      },
      // call Isotope as a callback
      function( newElements ) {
        $container.isotope( 'appended', $( newElements ));
      }
    );`

**The significant HTML:**
`<div class="row"><ul class="container infinite-scrolling"><% @item_array.each do |i| %><li class="item"><div class="name"><%= i.name %></div><div class="city"><%= i.city %></div><div class="zip"><%= i.zip %></div></li><% end %></ul></div><div class="row"><div id="page-nav"><a href="<%= items_path(page: @next_page) %>">Next</a></div></div>`

**Example of what the output looks like before I scroll down:**
`<ul class="container infinite-scrolling" style="position: relative; height: 200px;">
<li class="item" style="position: absolute; left: 0px; top: 0px;"><div class="name">A</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li class="item" style="position: absolute; left: 200px; top: 0px;"><div class="name">A</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li class="item" style="position: absolute; left: 400px; top: 0px;"><div class="name">A</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li class="item" style="position: absolute; left: 600px; top: 0px;"><div class="name">A</div><div class="city">City</div><div class="zip">24356-1234</div></li>
</ul>`

**Example of what the output looks like after I scroll down:**
`<ul class="container infinite-scrolling" style="position: relative; height: 200px;">
<li id ="a" class="item" style="position: absolute; left: 0px; top: 0px;"><div class="name">A</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li id ="b" class="item" style="position: absolute; left: 200px; top: 0px;"><div class="name">B</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li id ="c" class="item" style="position: absolute; left: 400px; top: 0px;"><div class="name">C</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li id ="d" class="item" style="position: absolute; left: 600px; top: 0px;"><div class="name">D</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li id ="e" class="item"><div class="name">E</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li id ="f" class="item"><div class="name">F</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li id ="g" class="item"><div class="name">G</div><div class="city">City</div><div class="zip">24356-1234</div></li>
<li id ="h" class="item"><div class="name">H</div><div class="city">City</div><div class="zip">24356-1234</div></li>
</ul>`

I added a console.log in the infinite scroll callback, but nothing fires.

Thanks for your help!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by narutoniue** [comment]
I figured this out.  Basically, I needed to reinitialize isotope.
