### ISSUE TITLE
getStyleSize exception

### ISSUE THREAD

**Issue by ugonj** [metafizzy/isotope#1092]
I was bitten by a small bug in isotope trying to call getStyleSize on a null value. Hard to construct a reduced test case, but it happened as I was trying to use isotope with reveal.js, so probably something to do with hidden elements. Very simple patch attached.

[getStyleSizeException.zip](https://github.com/metafizzy/isotope/files/254919/getStyleSizeException.zip)

**Comment by desandro** [comment]
Hello, thank you for reporting this issue. I appreciate you providing a download, but I need a pubicly viewable reduced test case so properly take a look at what's going on.  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by ugonj** [comment]
Thanks for your quick reply. Here's a link to a reduced test case:
http://codepen.io/ugonj/pen/MyLRvM?editors=1111

The bug doesn't appear in chromium or firefox. It seems that it occurs in webkit- based browsers (I tested with a few smallish ones, eg, qupzilla.)

**Comment by desandro** [comment]
I wasn't able to reproduce the bug in Chrome 51 or Safari 9.1.

Isotope v3 does not support Android < 4.0. Could this be the issue?

**Comment by ugonj** [comment]
I haven't tried Android at all. Here's a screenshot with midori on windows. It's unclear to me why it works with chrome and safari but not other webkit browsers. 
![midori screenshot](https://cloud.githubusercontent.com/assets/6858574/15135457/9d2872e2-16b9-11e6-9224-e58e368ce9b2.png)

**Comment by desandro** [comment]
I haven't heard of the midori web browser. Sounds like this is isolated to webkit browsers outside of Chrome and Safari. In which case, I'm okay leaving this bug unresolved.

**Comment by ugonj** [comment]
Sure, it's up to you. Thanks for taking the time to look into this.
