### ISSUE TITLE
Calling same sortBy twice does not trigger sort 

### ISSUE THREAD

**Issue by aunruh** [metafizzy/isotope#1093]
Test case:
http://codepen.io/arminunruh/pen/RadPKe

Hey!
I'm using "getSortData" and "sortBy". "sortBy" is set to "index" and in the "getSortData" object, "index" is a function:

`getSortData: {
			    	index: function(itemElem){
              return jQuery(itemElem).attr(sortbystring)
			    	}
			    },
			    sortBy : 'index'`

In the index: function I'm getting an attr based on the variable sortbystring. 

When I click the button, I'm calling .isotope using "sortBy": "index" again but I'm changing the sortbystring variable before.
Here's the problem. When I call sortBy again on button click, the getSortData.index() function is not called I guess, cause it doesn't sort based on the new sortbystring variable value.

I see that the standard way to sort is more like adding multiple getSortData key value pairs and then calling sortBy with the key like here http://codepen.io/desandro/pen/lzCqe

I hope this makes sense!
cu

**Comment by desandro** [comment]
Thank you for submitting the issue. Isotope collects is sort data only on initialization, or when new items are added. If you change sort data, you'll need to trigger [`updateSortData`](http://isotope.metafizzy.co/sorting.html#updatesortdata). Then you can re-sort the items with updated data. See demo http://codepen.io/desandro/pen/2a9b9245f2a3762c4d0c6dc97461a0c6/

**Comment by aunruh** [comment]
Thanks!
Am 10.05.2016 17:04 schrieb "David DeSandro" <notifications@github.com>:
