### ISSUE TITLE
center items within container

### ISSUE THREAD

**Issue by ynamite** [metafizzy/isotope#1094]
Hi

since this isn't so much a bug or problem report and more along the lines of a simple question or maybe even feature request, I hope you'll forgive me for not adding an actual test case.

If there's a better place to ask this, please let me know.

My question is this, is it or would it be at all possible to have isotoped items centered within their container? For instance, if we have 6 items in total and we display 4 items per row, would it possible to have items 5 and 6 centered within their container?

I'm not talking about centering the container itself (I know how to do that), I would like to center the items. I suspect it isn't possible, but I would love some sort of clarification.

If you wonder why I would want this: I have a responsive website where almost all content is centered (I know I know, clients wishes), except isotoped items and they kinda stick out when they're left aligned :)

Thanks for info.

Best Regards
yves

**Comment by desandro** [comment]
Thank you for this feature request. Yes this is possible to do, but not currently out-of-the-box with Isotope. You could write your own layout mode to handle the centering logic, or re-write a current layout mode.

**Comment by ynamite** [comment]
Thanks a bunch for the quick answer. If I have the time I'll have go at it and see what I can come up with.

**Comment by desandro** [comment]
Yes, `_getItemLayoutPosition` is largely responsible for positioning items. Best place to look is at a layout mode file, [fit-rows.js](https://github.com/metafizzy/isotope/blob/v3.0.0/js/layout-modes/fit-rows.js) is a good place to start
