### ISSUE TITLE
Huge gap between changing div containers on windows resize!

### ISSUE THREAD

**Issue by zilindeng** [metafizzy/isotope#1095]
Hi, i'm currently using Isotope to create my portfolio website.
Trying to mimic something like: http://malikafavre.com/ (featured on the Isotope website)
Desktop 4 Columns, Tablet 4 Columns, Mobile 1 Column.
I have this instance where one of my div's is twice the height of the others. (Box 2)
When viewing on mobile however, this div becomes a hinderance due to the lengthy scroll so I set some media queries where upon resizing the window to any dimension below 1000px will change the height back to match the other divs.

However, when resizing the window a huge gap between Box 2 and Box 3 will appear as the div changes, and will only disappear once I refresh the page or continue resizing.
Is there a way to fix this?
Also, there are times where Isotope will bug out and won't return to the initial layout after resizing/changing orientation.

Recreated in Codepen: http://codepen.io/zilindeng/pen/bpJVaB

Any help would be great, I'm simply a designer, but I'm really interested in code, so excuse me if I come off as a newbie!

Thanks,
Z.

**Comment by desandro** [comment]
Thanks for reporting this issue. The trouble is that the transitioning item widths is throwing off the calculations for layout. If you disable CSS transitions, it looks like the issue is resolved. See demo http://codepen.io/desandro/pen/3fc37afd0c7e4312d210d4f9d0c663de/

**Comment by zilindeng** [comment]
Thanks a lot for the rather quick reply! Disabling the CSS transition does fix this problem, but in this scenario how would I go about animating the hover states for my containers if there is this conflict?

**Comment by zilindeng** [comment]
Never mind the comment above, I just added the CSS transitions to the wrapper instead and it works perfectly. Thanks again!
