### ISSUE TITLE
search in subset of filtered items 

### ISSUE THREAD

**Issue by benediktscherer** [metafizzy/isotope#1096]
Heyho folks,

as u see in my codepen: https://codepen.io/bscherer/pen/MyxMZX
i would like to start a search in a subset of filtered items.
Unfortunately, isotope looking over the hole list of items …

i  already set an additional "is-filtered" class (dark flag). i think its because of using two instances for one #container?

many thanks for your advices

**Comment by desandro** [comment]
See this demo http://codepen.io/desandro/pen/mCdbD, linked in [Extra examples](http://isotope.metafizzy.co/extras.html#extra-examples)
