### ISSUE TITLE
cellsByRow: responsive (take tallest item per row)

### ISSUE THREAD

**Issue by richgcook** [metafizzy/isotope#1097]
cellsByRow is great but only when you know the heights and widths (albeit widths a lot easier to work out) per element. I have a responsive grid (via bootstrap) which fits the images per column but obvious due to the nature of different sized images the heights per element vary.

What I'd like to know is whether it is possible to get the tallest item per row and set that as the height of each row?

I have produced a reduced test case: http://codepen.io/anon/pen/yOrVwa

**Comment by desandro** [comment]
Thank you for this feature request. **Add a +1 reaction** if you'd like to see this feature added to Isotope.

To your question — no, Isotope does not support fitting cellsByRow rows to the tallest item. fitRows may be a better layout mode, as its rows are fit like this. The trouble is that Isotope does not have hooks for this kind of two-step calculations — where it goes through once to measure item sizes, then again to actually do layout.

**Comment by richgcook** [comment]
Thanks @desandro for the reply and option to have it as a feature. Just seems like the most obvious route to make cellsByRow as rarely is the first item the tallest OR fixed height elements these days. Let's hope we get some +1s.

**Comment by richgcook** [comment]
I'd also chip in again @desandro and say that actually if a client supports it then flexbox is probably a pretty great alternative for such options.

**Comment by davydden** [comment]
@desandro 

I hope you can re-consider implementing this feature. I just exchanged tens of messages in support forum of [uncode](https://undsgn.com/uncode/) wordpress theme to finally nail the issue with isotope on my wordpress site down to the case when there are only two images:

```
xyz.jpg 250 × 54 + fgh.jpg 349 × 304
```
In this case the layout will be broken as `isotope` seems to assume that the first element is the highest among the set. 

The workaround is, of course, to always put the highest element first. But this should probably be documented somewhere in bold letters as *known issues/limitations*.

ps. I don't think people would generally bother to look for the source code and report an issue upstream or wote up the feature request on GitHub. I would probably not decide on the importance of the feature/bugfix based on thumbs up.

pps. Fit rows won't achieve the same design (vertically centered elements) as CellsByRow.

**Comment by desandro** [comment]
Sorry, I will not be adding this feature to Isotope. I don't feel it received enough interest.
