### ISSUE TITLE
How to avoid conflicts with other versions

### ISSUE THREAD

**Issue by mnajafzadeh** [metafizzy/isotope#1098]
Hi,

I plan to merge Isotope into my wordpress project and for sure I will get the commercial license.
Just want to know, how can I avoid conflict of Isotope with other versions of itself. I mean for example, if two different wordpress plugins are using two different versions of Isotope and they are both installed on the website?

Thank you.

**Comment by desandro** [comment]
Thanks for reporting this issue. I highly advise resolving of using two different versions of Isotope. Nearly all your v2 Isotope code will work just fine with v3. See [upgrading from v2](http://isotope.metafizzy.co/extras.html#upgrading-from-v2) But Isotope does not have any logic to see if another version is already in use.

**Comment by mnajafzadeh** [comment]
Many WordPress themes are still using v1.5, one of them is installed on my website. I hope jQuery can prefer a standard solution for this collision problem to extension developers. Something like jQuery noConflict.
Thank you again for your response.
