### ISSUE TITLE
Changing stamps

### ISSUE THREAD

**Issue by sgurlt** [metafizzy/isotope#1100]
Hey,

I am currently trying to create something like shown here: http://etchapps.com/
What I am looking for is how they are doing the thing with the stamps. They have them all shuffled somewhere on the frontpage and according on which menu item you currently are, the matching stamp is shown in the top left corner.
I currently fighting with the issue that i can not change the stamp activly, so what I did for now as a workaround is that I added:

`$iso.isotope('destroy');`

on every hash change. 
This is working for now, but it is breaking the animation.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by sgurlt** [comment]
Sorry, took me a while to do it. Here is the test case:

https://jsfiddle.net/sgurlt/buwndhns/3/

Settings the corner stamp on filter does not work.

**Comment by desandro** [comment]
Thank you for the test case.

Looks like part of the issue is that you were setting the option `stamp`, but you should be triggering the [method `stamp`](http://isotope.metafizzy.co/methods.html#stamp).

``` js
// set stamp option, set as object
$grid.isotope({ stamp: elem })
// stamp method, two arguments
$grid.isotope( 'stamp', elem )
```

You might also want to unstamp the previous stamp. See demo https://jsfiddle.net/buwndhns/8/

But, I don't think you want to be using stamps. Rather, you want certain items to come first. If that's the case, you can use sorting. See demo https://jsfiddle.net/buwndhns/9/

**Comment by sgurlt** [comment]
The sorting thing is nice, thanks a lot!
I am just having a new issue with it: https://jsfiddle.net/sgurlt/buwndhns/11/

When then element that should be on the first position is bigger then the others, the layout seems to be broke.

**Comment by desandro** [comment]
[Set columnWidth](http://isotope.metafizzy.co/faq.html#the-first-item-breaks-the-grid). See demo https://jsfiddle.net/buwndhns/14/

**Comment by sgurlt** [comment]
Found this out 2 minutes ago and just wanted to write it here :)
Thanks a lot for your help !! Now i just need to achieve that i have a stamp on the frontpage homepage and the sorting the filter pages, but I think that can not be that hard.

**Comment by sgurlt** [comment]
One last question, is it possible to have items which do not have a sort relevant value to be sorted random?

**Comment by desandro** [comment]
Yes. You could change the `getSortData: stampFirst` function to have another conditional.

``` js
stampFirst: function( itemElem ) {
  var $item = $( itemElem );
  if ( $item.is('.stamp') ) {
    return 0;
  } else if ( $item.is('.random') ) {
    return Math.random() * 20
  }
  return $item.index();
}
```

**Comment by sgurlt** [comment]
I just played around with that sorting functions and to be honest, it is awesome ! You did a very great job here, thanks a lot !
