### ISSUE TITLE
Fixed positioning after x entries

### ISSUE THREAD

**Issue by jppanteon** [metafizzy/isotope#1101]
I have a layout in which i have an advertisement banner.
I want to show that banner every time after 8 items even if i change Sorting A-Z or Most Popular.

Please see the screenshot

![isotope](https://cloud.githubusercontent.com/assets/18391879/15318804/719739a6-1c45-11e6-9a7a-8874956f6f93.jpg)

Here i want ADVERTISEMENT banner at same place even if i change sorting A-Z or most popular.

THank You

**Comment by desandro** [comment]
Have you looked at using [stamp](http://isotope.metafizzy.co/options.html#stamp)?
