### ISSUE TITLE
Sort & Animation

### ISSUE THREAD

**Issue by Bluxart** [metafizzy/isotope#1102]
Hi, I make a test case.

If I apply the sort to isotope container and apply an simple animation on init for reveal items, the animation work but based on DOM index element and not based sort isotope index.

How I do to make the animation based on sorting index? It is possible?

I used in this case the shuffle method.

Test Case: http://codepen.io/Bluxart/pen/MydQvg

Thanks for your time.

**Comment by desandro** [comment]
Use [getFilteredItemElements](http://isotope.metafizzy.co/methods.html#getfiltereditemelements)

``` js
var $items = $( $grid.isotope('getFilteredItemElements') );
```

See forked demo http://codepen.io/desandro/pen/aba74bd6e108a1ca79f53e14bc672aae/
