### ISSUE TITLE
Data Counter for Drop Down List ?

### ISSUE THREAD

**Issue by Alex36** [metafizzy/isotope#1106]
Hello  guys, i saw @desandro share a data counter for isotope, but i want to adapt it for my drop down list filter but i dont know how to do, more precisely what i need to put instead of "button" for my case ?

``` js
function updateFilterCounts()  {
  // get filtered item elements
  var itemElems = $grid.isotope('getFilteredItemElements');
  var $itemElems = $( itemElems );
  $filterButtons.each( function( i, button ) {
    var $button = $( button );
    var filterValue = $button.attr('data-filter');
    if ( !filterValue ) {
      // do not update 'any' buttons
      return;
    }
    var count = $itemElems.filter( filterValue ).length;
    $button.find('.filter-count').text( '(' + count +')' );
  });
}
```

My codepen : 

http://codepen.io/anon/pen/gMYMBB

Thanks for helping guys !

**Comment by desandro** [comment]
Here's one way to do it. See demo http://codepen.io/desandro/pen/35a42935ef94a22659d618790ea9451a/

``` js
var $filterOptions = $('.option-set option');

function updateFilterCounts()  {
  // get filtered item elements
  var itemElems = $container.isotope('getFilteredItemElements');
  var $itemElems = $( itemElems );
  $filterOptions.each( function( i, option ) {
    var $option = $( option );
    var filterValue = $option.attr('data-filter-value');
    if ( !filterValue ) {
      // do not update 'any' buttons
      return;
    }
    var count = $itemElems.filter( filterValue ).length;
    var text = $option.text();
    text = text.replace( /\(\d+\)$/, '(' + count + ')' )
    $option.text( text );
  });
}
```

**Comment by Alex36** [comment]
Oh nice, thanks you ! But i dont know if its my Isotope function that is a bit bug or something but, when i click for exemple in "Societe : S2MI" and after i look "Societe : ENTI" the number is 0 but if i click on ENTI, the number is now 1.

If think there is a problem somewhere :(

**Comment by desandro** [comment]
Currently this code is acting as if both selects can be used in combination to filter. It shows the count of how many _are currently visible._ When you click a filter with 0, then you are setting a different filter.

**Comment by Alex36** [comment]
Ah my brain do a mistake so.
All i want since the start is a system who can prevent the user if they are result with the combinaison.

Like a display like you do, with the number or disable the link when they are no result. But with a drop list filter i found nothing to help me

I'm sorry i misspoke i think :(
