### ISSUE TITLE
Sort by Range of percentages

### ISSUE THREAD

**Issue by narutoniue** [metafizzy/isotope#1109]
http://codepen.io/narutoniue/pen/aZbdPG

As you can see, I am trying to sort by %, but the numbers are all over.  Some are ranges (10-15%), some begin with decimal points, some are greater than or less than....

I tried to remove > or < and % and parseFloat, but isotope didn't seem to like it.  Any ideas of how to deal with this dataset?

**Comment by desandro** [comment]
Looks like you'll have to use a [function to properly extract the number value](http://isotope.metafizzy.co/sorting.html#getsortdata-functions) from that text.

``` js
    number: function( itemElem ) {
      var number = $( itemElem ).find('.number').text();
      return parseFloat( number.replace( /[<>%]/gi, '' ), 10 );
    }
```

See demo http://codepen.io/desandro/pen/1e05d7b67862dbdfa460e95e177bf753/

This removes `<`, `>` and `%`. I'll leave it to  you to figure out how you want resolve ranges.
