### ISSUE TITLE
What would it take to apply isotope to svg?

### ISSUE THREAD

**Issue by geraldo** [metafizzy/isotope#1110]
I'd like to apply isotope to svg elements as I use thousands of elements, which are represented as `<rect class="node" width="2" height="2"/>`
I use '.node' as item selector but noting happes. Any hint if this could be possible or if the library can't be applied to svg elements?

**Comment by desandro** [comment]
> thousands of elements

I do not recommend Isotope for this use case. Isotope works best with about 100 elements at most. Isotope was not designed to support SVG, so I cannot recommend Isotope for that use case as well. You may be better off looking at [D3](https://d3js.org/)
