### ISSUE TITLE
append method appends elements and sets them to display none and no top or left rules

### ISSUE THREAD

**Issue by vk011** [metafizzy/isotope#1111]
I am using isotope 3.

I dont't seem to be able to append new items to isotope no matter what I try. I wanna do it after an ajax request.

The closest I've come to is the following in my success callback:

$('.storiesiso').append( response ).isotope( 'reloadItems' ).isotope({ sortBy: 'original-order' }).isotope('layout');

Using that, the items ARE actually added but they are set to display:none and have no right or top css stying applied to them.

Actually If I take out `sortBy` and leave it as `$('.storiesiso').append( response ).isotope( 'reloadItems' ).isotope('layout')` the items are visible but still top and left is not calculated so they're at the top of the div and the height of the container div is not updated.

Is this a bug or am I doing something wrong? Please advise.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by vk011** [comment]
I am sorry I forgot to come back here. 

Actually it was not an isotope issue, it had something to do with filtering and I think that isotope actually did its job by setting the appended divs to `display: none` and not calculating top and left. 

Bottom line is, I don't think there is a bug in isotope but in the way I handled it. I've done it another way now  on my site and it works.

Sorry for the false alarm !
