### ISSUE TITLE
Container padding breaks masonry layout

### ISSUE THREAD

**Issue by cojocaru3** [metafizzy/isotope#1112]
I have a three columns masonry layout which works just fine until i add paddings to container, after that, layout breaks into two columns, looks like each third column is not getting enough space to fit
see the fiddle https://jsfiddle.net/cojocaru3/8kns9Lv0/ 
( try to remove/add has-paddings class to .isotope-container )
Setting a fixed width to column is not a solution, because actually it's unkown how many columns there will be.
Any ideas how to fix ?

**Comment by desandro** [comment]
Looks like this issue is caused by how padding, percent sizes work different with static vs. absolute positioning. We can resolve it by adding another container element (sorry, only way) for the padding, separate from the isotope container. See demo http://codepen.io/desandro/pen/ff46305e07702e88d6c122a5e3478c30

``` html
<div class="container">
  <div class="row">
    <div class="isotope-padding">
      <div class="isotope-container">
        <!-- items... -->
      </div>
    </div>
  </div>
</div>
```

**Comment by cojocaru3** [comment]
Thanks a lot, it helped !

**Comment by stephdotnet** [comment]
I think that should be in the FAQ since i had this problem with percent grid and padding inside each element. It's a common layout when you deal with grid & responsive design.

Anyway the plugin is amazing. Good Job!

**Comment by BryanBarrera** [comment]
This helped me! Thanks @desandro

**Comment by frizzant** [comment]
in my case i just removed the padding.
