### ISSUE TITLE
URL Hash change '#' into '?'

### ISSUE THREAD

**Issue by NickHeurter** [metafizzy/isotope#1113]
Hi @desandro, first of all thanks for the awesome plugin. I'm busy building a filter for my website and I'm wondering if I could change the '#' into a '?' character when using the URL hash function?

I'm using multiple values in my URL structure and they all start with a question character. So it would be nice if I could use the question character for the URL hash function of Isotope as well.

**Simple explanation:** Currently the Isotope URL Hash structure looks like this: `http://website.com/#filter=.test` and I would like to change this into: `http://website.com/?filter=.test`. Is this possible? Thanks already for your help!

Best Regards,
Nick

**Comment by desandro** [comment]
The same principle of hash history, but you might want to look into [HTML pushState and history manipulation](https://developer.mozilla.org/en-US/docs/Web/API/History_API). Then use [jQuery's param](http://api.jquery.com/jquery.param/) and [deparam](https://github.com/AceMetrix/jquery-deparam) to handle more complex objects.

**Comment by NickHeurter** [comment]
Thanks a lot for your quick answer!
