### ISSUE TITLE
having multiple grids and filters in a page

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/isotope#1116]
hi,
first of all thanks for such a great plugin.

I'm having an issue when I add multiple grids in a page and I want to have filters for each of them.
here's a demo http://codepen.io/Mohsen-Khakbiz/pen/gMrQpq

you will see if you click on first filter sets, the second grid will also affected. and this is the issue.

filters and grid can't have the same parent. they have to work in a situation I provided in the demo. because filters may be in another element.

**Comment by desandro** [comment]
Currently, you are setting up the filters to be associated with two Isotope instances (the two `.grid` in `$('.grid')`. Instead, you want to separate the filter click behavior to be associated with the correct single `.grid`. The best way to do this is to wrap each set in another element, for example `.grid-container`, and use `.each` to set up each filter.

``` js
// for each container
$('.grid-container').each( function( i, gridContainer ) {
  var $gridContainer = $( gridContainer );
  // init isotope for container
  var $grid = $gridContainer.find('.grid').imagesLoaded( function() {
    $grid.isotope({
      itemSelector: '.grid-item',
      layoutMode: 'packery'
    })
  });
  // initi filters for container
  $gridContainer.find('.masonry-filters').on( 'click', 'li', function() {
    var filterValue = $( this ).attr('data-filter');
    $grid.isotope({ filter: filterValue });
  });
});
```

See demo http://codepen.io/desandro/pen/e73e9ca10897063fd9e75f7f47db1a13/

**Comment by Mohsen-Khakbiz** [comment]
thanks for your respond.

but can't we make it work without wrapping filters and the grid with an element?

**Comment by desandro** [comment]
Yes, you can use jQuery `next()`. See demo http://codepen.io/desandro/pen/e24ee19a0727784a4f3b7d9b9be0d977

**Comment by Mohsen-Khakbiz** [comment]
yes, this can be as well. but we don't have the same markup everytime. this is the situation I mean

http://codepen.io/Mohsen-Khakbiz/pen/MeeyOM

**Comment by desandro** [comment]
I'll leave the implementation up to you.

**Comment by Mohsen-Khakbiz** [comment]
thank you for helping.
just came up with using data-attributes. btw I'm not good in js. but here is the solution I came up with, maybe it'll help someone else

http://codepen.io/Mohsen-Khakbiz/pen/MeeyOM

**Comment by mariakhn** [comment]
@Mohsen-Khakbiz Thank you so much for providing last Pen. I am using your solution in 2020. It really saved my life. Thanks ton
