### ISSUE TITLE
Not Issue : But need enhancement

### ISSUE THREAD

**Issue by KarthikDev81** [metafizzy/isotope#1117]
Hi Thanks for this filter. But in my scenario, i want image filter like stack of images there. When we type keyword, the image get filtered... For example, Photos page in any Sports site, we can search filter, the images get filtered.. Any idea???

**Comment by desandro** [comment]
[See quicksearch filter demo](http://codepen.io/desandro/pen/wfaGu)

**Comment by KarthikDev81** [comment]
Thanks for the reply... But I need filter for images not for content / text
