### ISSUE TITLE
Combine inclusive and exclusive filters with a function

### ISSUE THREAD

**Issue by NickHeurter** [metafizzy/isotope#1118]
Hi @desandro, I'm trying to combine the following two example you've created before:

1. [Combination filters with a function](http://codepen.io/desandro/pen/owAyG/)
2. [Checkboxes and dropdowns, inclusive and exclusive filters](http://codepen.io/desandro/pen/GFbAs)

I would like to use a function I wrote to filter my data as an inclusive filter, the filter is equal to your ['greaterThan50' example filter](http://codepen.io/desandro/pen/owAyG/). But I also have some checkboxes, like in [your second example](http://codepen.io/desandro/pen/GFbAs), which I want to use as exclusive filters. Is it possible to combine these to so that I can use my own function filter in combination with the inclusive and exclusive filters? 

Thanks already for your help!

**Comment by desandro** [comment]
Thanks for reporting this issue. Mind putting together a test case I can work with given those two examples? JS not necessary. I'm curious what kind of HTML and UI you are working with.

**Comment by NickHeurter** [comment]
Off course! I've created a test cast on a beta website. Is it an idea that I give you the login to access the beta website? Should I sent it to you by private message?

**Comment by desandro** [comment]
CodePen works best. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by NickHeurter** [comment]
Sorry, I didn't knew about the Submitting Issues guidelines. I've insert my HTML, UI and my script in [My Codepen](http://codepen.io/anon/pen/BzzrGa). The idea is that the range slider checks the distance value in each vacancy. And if the distance value of the vacancy is smaller then the range value then it needs to be displayed. But as you can see in my Codepen the function is sticked to the class filter. I'm wondering how you would solve this. Thanks for your help @desandro!

**Comment by shmshrbali** [comment]
Hi @desandro , First of all thanks for a great plugin! I bought it two years ago, and have used it in a lot of my projects.

Regarding this issue posted by @NickHeurter , I've run into a similar issue (i think) in a recent project.

So while experimenting - bear with me here

Say i have two categories of filters A[a1, a2, a3] and B[b1,b2,b3]

So i want a combination of A iso.arrange({ filter: ".a1,.a2,.a3"})(which is how it works in your plugin)

But then i want an exclusion of the combination A and B

something like say iso.arrange({ filter: "(.a1,.a2,.a3)(.b1,.b2,.b3)"}) (which doesnt work)

ps :- Apologies if posted in the wrong thread. Would love to see this solved though.

**Comment by desandro** [comment]
@NickHeurter See http://codepen.io/desandro/pen/056c9e538c36478c9307ac4b5c7c2ae6/

**Comment by shmshrbali** [comment]
@desandro should i open a separate issue? 

Here's a link to the [http://codepen.io/shmshrbali/pen/vKXKEp](codepen)

My issue if you see there is, if i select say two brands, it shows all products of that brand. but if i, say, select a category it then shows all products with that category too **added to the above result**.

What i require is for it to show a subset of products where all products of those brands have the **selected category/categories**. So on and so forth for material as well.

Let me know if this is clear, or if you need me to open a separate issue.

@NickHeurter  I hope the solution worked out for you.

**Comment by desandro** [comment]
@shmshrbali  You can change `filters = filters.join('');` so that the filters are exclusive. See demo http://codepen.io/desandro/pen/e348d07df31186fe11ae0b4b6f51d1b6/

Please open a new issue if you continue to have trouble.

**Comment by shmshrbali** [comment]
@desandro opening a new issue

**Comment by NickHeurter** [comment]
Thanks a lot @desandro, works like a charm!
