### ISSUE TITLE
Commercial use question

### ISSUE THREAD

**Issue by robbisy** [metafizzy/isotope#1119]
Hi David 
I just want to know if i buy a Commercial license for isotope v3.0.1 i could use all the version until v 4 but could i also use v2.x.x ?

**Comment by desandro** [comment]
The license is assigned to the major version, currently 3. See [license terms](http://isotope.metafizzy.co/license.html#commercial-license-grant):

> You are entitled to receive all updates to the major version of the Software licensed by you, as well as any later version of the Software that Metafizzy, in writing, explicitly authorizes you to use. (For illustration purposes only, if you purchased a license for version 3.0, this licenses authorizes you to use version 3.9, but not 4.0.)

Metafizzy does offer discounted upgrade pricing. As v3 was recently released this year, Isotope v4 is far in the future. The license does not cover previous major versions. Commercial licenses are no longer available for v2. You may use [Isotope v2](http://isotope.metafizzy.co/v2/license.html) under the open source GPLv3 license.
