### ISSUE TITLE
Combining Inclusive filters with exclusive for complex filters

### ISSUE THREAD

**Issue by shmshrbali** [metafizzy/isotope#1120]
**Test case:** http://codepen.io/shmshrbali/pen/vKXKEp
 @desandro : http://codepen.io/desandro/pen/e348d07df31186fe11ae0b4b6f51d1b6/

So i've been through your codepen, and thats exactly the issue. what i want from the functionality is that, for example - If i select Reebok in Brand, and select Cloth in material, It shows products with both tags. But if i want to select say reebok in brand, and select both Cloth and leather in material, I want it to show all Reebok Products with either cloth or leather.

So the categories are Inclusive within, but exclusive of each other, if that makes sense?

**Comment by desandro** [comment]
Okay. To better understand your request, Can you confirm what would happen when user selects REEBOK & ADIDAS and SHOES & SHIRTS and CLOTH & LEATHER?  I imagine you want something like

+ [reebok shoes cloth] OR
+ [reebok shoes leather] OR
+ [reebok shirt cloth] OR
+ [reebok shirt leather] OR
+ [adidas shoes cloth] OR
+ [adidas shoes leather] OR
+ [adidas shirt cloth] OR
+ [adidas shirt leather]

**Comment by shmshrbali** [comment]
@desandro Yes, It would show all the combinations possible but NOT any product of LISBON, PANTS or  SYNTHETIC

**Comment by desandro** [comment]
See demo http://codepen.io/desandro/pen/MebyMR

These combination filters work by associating groups of filters: brands, productTypes, sizes, colors. Those groups are then combined so that filters within groups are included together **OR** and filters outside of groups are included **AND** — inclusive and exclusive.

``` js
// store filter per group
var filters = {};

var $container = $('#container');

$container.isotope();
// do stuff when checkbox change
$('#options').on( 'change', function( event ) {
  var checkbox = event.target;
  var $checkbox = $( checkbox );
  var group = $checkbox.parents('.option-set').attr('data-group');
  // create array for filter group, if not there yet
  var filterGroup = filters[ group ];
  if ( !filterGroup ) {
    filterGroup = filters[ group ] = [];
  }
  // add/remove filter
  if ( checkbox.checked ) {
    // add filter
    filterGroup.push( checkbox.value );
  } else {
    // remove filter
    var index = filterGroup.indexOf( checkbox.value );
    filterGroup.splice( index, 1 );
  }
  
  var comboFilter = getComboFilter();
  $container.isotope({ filter: comboFilter });
});

function getComboFilter() {
  var combo = [];
  for ( var prop in filters ) {
    var group = filters[ prop ];
    if ( !group.length ) {
      // no filters in group, carry on
      continue;
    }
    // add first group
    if ( !combo.length ) {
      combo = group.slice(0);
      continue;
    }
    // add additional groups
    var nextCombo = [];
    // split group into combo: [ A, B ] & [ 1, 2 ] => [ A1, A2, B1, B2 ]
    for ( var i=0; i < combo.length; i++ ) {
      for ( var j=0; j < group.length; j++ ) {
        var item = combo[i] + group[j];
        nextCombo.push( item );
      }
    }
    combo = nextCombo;
  }
  var comboFilter = combo.join(', ');
  return comboFilter;
}
```

**Comment by shmshrbali** [comment]
@desandro This is exactly what i was looking for. The example was pre-available on the demo page?
Apologies for not researching properly. 

Thank you!

**Comment by desandro** [comment]
I thought it was, but nope. But it's at least linked to now.
