### ISSUE TITLE
1px bug...

### ISSUE THREAD

**Issue by trajektorijus** [metafizzy/isotope#1123]
Hi, so **It** is back. No need to fork. I can see 1px on the masonry fluid sizing example. 
Screenshots:
https://snag.gy/G27z5T.jpg
https://snag.gy/mFj8uv.jpg

You can see them even more clearly in this example (just resize the window if everything looks good):
http://codepen.io/pollenlondon/full/PzWdJL/ (not following Reduced Test Cases)

**Test case:** http://codepen.io/desandro/pen/mIkhq

**Comment by trajektorijus** [comment]
Not sure if it helps, but just noticed that on [this](http://codepen.io/desandro/pen/mIkhq) example 1px bug appears only vertically. But on [my ](http://codepen.io/pollenlondon/full/PzWdJL/)example is the opposite. The bug appears only horizontally.

**Comment by desandro** [comment]
See https://github.com/metafizzy/isotope/issues/916#issuecomment-108899516
