### ISSUE TITLE
layoutChange event

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/isotope#1124]
hi,

is there any callback like .on('layoutChange') ?
please check this demo http://codepen.io/Mohsen-Khakbiz/pen/BzpXRb

I need to add **.layout-completed** classname on 'layoutComplete' event, and remove that classname when the layout starts changing, e.g. when we resize the window

btw, I don't know why that loading screen isn't hiding on page load!

**Comment by desandro** [comment]
You can hack a solution:

``` js
var layout = Isotope.prototype.layout;
Isotope.prototype.layout = function() {
  layout.apply( this, arguments );
  this.dispatchEvent('layout');
};
```

This will emit a `layout` event, before items are actually laid out.

**Comment by Mohsen-Khakbiz** [comment]
thank you so much, helped a lot

**Comment by Szymon-dziewonski** [comment]
This one isnt work even in codepen example.. This plugin just have not any callback complete at all - i mean working one. Looks around web for hours and nothing is working all everywhere are complains about that.. Such a pitty, so nice plugin, but many people will drop it - its major flaw..
