### ISSUE TITLE
V.3.0.1  issue with requirejs

### ISSUE THREAD

**Issue by jaman7** [metafizzy/isotope#1125]
Hi
im try with requirejs 
**this code for me not working**

```
requirejs( [ 'require', 'jquery', 'path/to/isotope.pkgd.js' ],
  function( require, $, Isotope ) {
    // require jquery-bridget, it's included in isotope.pkgd.js
    require( [ 'jquery-bridget/jquery-bridget' ],
    function( jQueryBridget ) {
      // make Isotope a jQuery plugin
      jQueryBridget( 'isotope', Isotope, $ );
      // now you can use $().isotope()
      $('.grid').isotope({...});
    }
  );
});
```

output console : jQueryBridget  not a function

I tried another method and found a way, my code looks like this:

**main config recurejs main.js:**

```
require.config({
    baseUrl: 'js/',
    paths: {
        'jquery': ['https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min',
            'vendor/jquery.min'
        ],
       'isotope.pkgd': 'vendor/isotope.pkgd'
    }
});
require(['jquery', 'isotope.pkgd'], function ($, Isotope) {
    // require jquery-bridget, it's included in isotope.pkgd.js
    require(['jquery-bridget/jquery-bridget'], function() {
        // make Isotope a jQuery plugin
        $.bridget('isotope', Isotope, $);
        // now you can use $().isotope()
        $('.grid').isotope({...});
    });
});
```

Now is working very well

**Comment by jingjiewei** [comment]
Hi @jaman7 ,
I used the same code, but got an error of Uncaught TypeError: Cannot read property 'masonry' of undefined(…) isotope.pkgd.js:3351 

require(['isotopepkgd'], function (Isotope) {
			 //require jquery-bridget, it's included in isotope.pkgd.js
			require(['jquery-bridget/jquery-bridget'], function() {
				// make Isotope a jQuery plugin
				$.bridget('isotope', Isotope, $);
				// now you can use $().isotope()
				$('.js-isotope').isotope({
					layoutMode: 'masonry'
				});
			});
		});

so, i tried to change the code to, 
		require(['isotopepkgd'], function (Isotope) {
			var iso = new Isotope('.js-isotope');
		});
and it works, but when  resize the window, you got the same error "Cannot read property 'masonry' of undefined"

**Comment by maruful** [comment]
Isotope is not working on jQuery-2.2.4  ,, What should i do ?? help me someone plzz

**Comment by jaman7** [comment]
work great, main setup example;

```
require.config({
    baseUrl: 'js/',
    paths: {
        'jquery': ['https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min',
            'vendor/jquery.min'
        ],
        'isotope.pkgd': 'vendor/isotope.pkgd'
    },
    shim: {
        'jquery.easing': {
            deps: ['jquery'],
            exports: ['easing']
        },
        'isotope.pkgd': {
            deps: ['jquery'],
            exports: ['Isotope']
        }
    }
});
define(['jquery', 'isotope.pkgd'], function ($, Isotope) {
    'use strict';
    // require jquery-bridget, it's included in isotope.pkgd.js
    require(['jquery-bridget/jquery-bridget'], function () {
        // make Isotope a jQuery plugin
        $.bridget('isotope', Isotope, $);
            // now you can use $().isotope()
            var $grid = $('.grid').isotope({
            itemSelector: '.filtr-item',
            layoutMode: 'fitRows'
        });
        $('.menu-filter').on('click', 'li', function () {
            var filterValue = $(this).attr('data-filter');
            // use filterFn if matches value
            filterValue = filterValue;
            $grid.isotope({
                filter: filterValue
            });
        });
        // change is-checked class on buttons
        $('.menu-filter').each(function (i, buttonGroup) {
            var $buttonGroup = $(buttonGroup);
            $buttonGroup.on('click', 'li', function () {
                $buttonGroup.find('.active').removeClass('active');
                $(this).addClass('active');
            });
        });
    });
});
```

**Comment by maruful** [comment]
thanks a lot buddy !!  
#jaman7

**Comment by desandro** [comment]
I'm closing this issue. Please open a new issue if you run into trouble with Isotope and RequireJS.

**Comment by 29sunil** [comment]
Hello, 
I am using isotopeMB but i am getting following error:
TypeError: $container.isotopeMB is not a function

I have confugured it with require js.
Below is require js configuration

var config = {
    map: {
        '*': {
            compareItems:           'Magento_Catalog/js/compare',
            compareList:            'Magento_Catalog/js/list',
            relatedProducts:        'Magento_Catalog/js/related-products',
            upsellProducts:         'Magento_Catalog/js/upsell-products',
            productListToolbarForm: 'Magento_Catalog/js/product/list/toolbar',
            catalogGallery:         'Magento_Catalog/js/gallery',
            priceBox:               'Magento_Catalog/js/price-box',
            priceOptionDate:        'Magento_Catalog/js/price-option-date',
            priceOptionFile:        'Magento_Catalog/js/price-option-file',
            priceOptions:           'Magento_Catalog/js/price-options',
            priceUtils:             'Magento_Catalog/js/price-utils',
            catalogAddToCart:       'Magento_Catalog/js/catalog-add-to-cart', 
        }
    },
    paths: {
        isotope:                'Magento_Catalog/js/jquery.isotope.min', 
        imagesLoaded:                'Magento_Catalog/js/jquery.imagesLoaded.min', 
        transit:                'Magento_Catalog/js/jquery.transit.min', 
        easing:                'Magento_Catalog/js/jquery.easing', 
        waypoints:                'Magento_Catalog/js/waypoints.min', 
        modernizr:                'Magento_Catalog/js/modernizr.custom.min', 
        mediaBoxesdropdown:                'Magento_Catalog/js/jquery.mediaBoxes.dropdown', 
        mediaBoxes:                'Magento_Catalog/js/jquery.mediaBoxes', 
        autoGrid:                'Magento_Catalog/js/jquery.autoGrid', 
        bridget:                'Magento_Catalog/js/bridget' 
    },
    shim: {
        'isotope': {
            deps: ['jquery'],
            exports: ['IsotopeMB']
        },
        'mediaBoxes': {
            deps: ['jquery','isotope']
        }
    }
};
