### ISSUE TITLE
Adding multiple items dynamically breaks isotope

### ISSUE THREAD

**Issue by chrisid** [metafizzy/isotope#1126]
I've been trying to figure out what's going on, non-dynamic items work well, trying to have dynamic breaks the grid when initializing isotope

Test case ready:
http://codepen.io/christianpugliese/pen/vKmBNv

**Comment by desandro** [comment]
Looks like the issue was that you were passing an array of jQuery objects.

``` js
var items = [ $('<div />'), $('<div />'), $('<div />'), ...  ]
```

While this works with with `.append()`, it does not with `.isotope( 'appended' )`. One way to fix this is to append a jQuery object instead.

``` js
var $items = $('<div /><div /><div />...')
```

See demo http://codepen.io/desandro/pen/c931983b379dff6488c7e303a6fd17e3/
