### ISSUE TITLE
Using Flexbox in IE10. Is there a layout for "just use what is already there" ?

### ISSUE THREAD

**Issue by MartinMuzatko** [metafizzy/isotope#1128]
Reduced Test Case:

My problem is, that I want to use flexbox to arrange how items are layed out.

Furthermore, I'd love to have isotope not interfere with the layout I already have, I just want to be able to filter items with animation.

So is there a layout for "just use what is already there" ?
I also saw, that most of the layouts, [showcased](http://isotope.metafizzy.co/layout-modes.html) here do not work.

```
isotope.js:3349 Uncaught Error: No layout mode: horiz
isotope.js:3349 Uncaught Error: No layout mode: cellsByRow
isotope.js:3349 Uncaught Error: No layout mode: packery
isotope.js:3349 Uncaught Error: No layout mode: masonryHorizontal
isotope.js:3349 Uncaught Error: No layout mode: fitColumns
isotope.js:3349 Uncaught Error: No layout mode: cellsByColumn
```

**Comment by MartinMuzatko** [comment]
Update: When I force `position: static !important;` on target item element, it works for IE10

**Comment by desandro** [comment]
> My problem is, that I want to use flexbox to arrange how items are layed out.

If you want to use flexbox for layout, then you should not use Isotope. But there is a hack for Isotope that only does filtering. See https://github.com/metafizzy/isotope/issues/675#issuecomment-40675160

**Comment by MartinMuzatko** [comment]
Thank you a lot. Yes I saw that isotope isn't that good with flexbox. Elements get displaced easily.
Thank you for the hint.
