### ISSUE TITLE
Maintain left-to-right order with masonry layout

### ISSUE THREAD

**Issue by markmaurerrr** [metafizzy/isotope#1130]
Basically, this describes everything:

<img width="600" alt="bildschirmfoto 2016-07-05 um 16 08 16" src="https://cloud.githubusercontent.com/assets/7374283/16587457/facd5ede-42ca-11e6-8e97-cee581661308.png">

What i am trying to do, is force the elemens to be placed in the DOM Order from left to right, even if it takes more space in the end. Am i overlooking something? Is this possible with the isotope script?

Thanks a lot in advance!

**Comment by thestype** [comment]
+1

**Comment by desandro** [comment]
> Am i overlooking something? Is this possible with the isotope script?

This is how the Masonry layout algorithm is intended to work. It prioritizes vertical spacing over horizontal spacing.

If you would like to see this feature added to Isotope, please add a +1 reaction to desandro/masonry#873

**Comment by desandro** [comment]
Isotope v3.0.4 has added [`horizontalOrder` with the masonry layout mode](http://isotope.metafizzy.co/layout-modes/masonry.html#horizontalorder). You can now maintain left-to-right with Masonry layouts in Isotope.

Thanks all for your feedback over the years (!). Glad to have this feature finally delivered. Please open a new issue if you run into trouble. 🌈🐻

**Comment by polack45** [comment]
Hi,
I 'm the same problem with date : [http://www.verdun.fr/agenda]
I would like a sort by date..
Do you have an issue please ?
Thanks of lot
See you
bye
stéphanie

**Comment by vikasui** [comment]
Hi guys i am having same issue can you help me.
Thanks in advance
