### ISSUE TITLE
Packery cannot be activated 

### ISSUE THREAD

**Issue by MaluNoPeleke** [metafizzy/isotope#1133]
I have setup social-feed together with isotope which works quite well but it doesn't apply my packery settings:
You can see an example including source code on https://peleke.diphda.uberspace.de/bower_components/social-feed/wilkenm.html
How can I use packery combined responsive width of the columns? Thanks in advance

**Comment by desandro** [comment]
Can you confirm that the `callback` and `GridInit` function are triggering?

**Comment by MaluNoPeleke** [comment]
I cannot test it at the moment but I think it should: https://github.com/pavelk2/social-feed/issues/94
I will verify soon with my setup.

**Comment by MaluNoPeleke** [comment]
I got it working now, thanks!
