### ISSUE TITLE
IE11 problem

### ISSUE THREAD

**Issue by adam1920** [metafizzy/isotope#1134]
Sometimes in container all items position set to "top:0;left:0"
This is my site: [www.joy.land/](http://www.joy.land/)
This part of code:
grid_container.append( template(withData) ).**isotope({
                                        /* options */
                                        itemSelector: '.game_item',
                                        masonry: {
                                                columnWidth: '.game_item',
                                                isFitWidth: true,
                                                gutter: 10
                                        },
                                        filter: ''
                                });**

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
