### ISSUE TITLE
arrangeComplete and layoutComplete events fire too early

### ISSUE THREAD

**Issue by rawb1t** [metafizzy/isotope#1135]
I found out that an issue from past is still existing.

Both events, (arrangeComplete and layoutComplete) fires about 1 second too early. I need to use

```
window.setTimeout(function() {
...
});
```

to get correct results. I am using transitions. Without transition everything works well.

I don't want to use this setTimeout()-Method do fix my program...

Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by rawb1t** [comment]
```
this.pinboard = this.$pinboard.isotope(
{
	stamp: '.stamp',
	itemSelector: '.pin',
	layoutMode: 'masonry',
	masonry:
	{
		isFitWidth: true,
		gutter: 20
	},
	isInitLayout: false,
	transitionDuration: 400,
	getSortData:
	{
		top: '[data-top] parseInt',
		views: '[data-views] parseInt',
		ts: '[data-ts] parseInt',
		distance: '[data-distance] parseFloat',
		price: '[data-price] parseFloat'
	}
});
this.pinboard.on('arrangeComplete', function()
{
	console.log($(document).height());
	$w.setTimeout(function() {
		console.log($(document).height());
	}, 1);
});

this.pinboard.on('layoutComplete', function()
{
	console.log($(document).height());
	$w.setTimeout(function() {
		console.log($(document).height());
	}, 1);
});
```
This is my code. I am using jQuery and after the arrangeComplete or layoutComplete events, i need the REAL document height. When I use $(document).height() without the setTimestamp() method and with transitions, i get a wrong result. When I disable transitions, I dont need the setTimeout() method anymore, I get a correct result.

It seems there is an issue with the transition duration.

**Comment by rawb1t** [comment]
This issue is fixed?

**Comment by nsocrates** [comment]
Maybe this could help http://metafizzy.co/blog/isotope-animating-item-sizes/
