### ISSUE TITLE
Sort Order doesn't work properly

### ISSUE THREAD

**Issue by scepticore** [metafizzy/isotope#1136]
I don't know if this is an issue. But for a customer project, I'd like to use the isotope plugin with Masonry Layout.

To keep my issue short: 
If I use layoutMode: 'fitRows', the grid shows in the correct order, just as I want it to. But there are a lot white spaces. I understand why, but that's not exactly what I want.
http://codepen.io/scepticore/pen/EyLpqP

When I use layoutMode: 'masonry' the order of the items - and so the layout - is not correct anymore, as you can see in the example below:
http://codepen.io/scepticore/pen/RRyBOL

Maybe you want to know, why the order of the items is **important** to me: It will show all upcoming events of a concert venue / club.

**Comment by desandro** [comment]
Sounds like you are looking for Masonry to keep left-to-right order. If so, add your 👍  to desandro/masonry#873

**Comment by scepticore** [comment]
Hi @desandro 
Yes Exactly, and I found this issue right afterwards so I gave it a :+1: . Problem is, that I would need this feature very soon :/
