### ISSUE TITLE
Ensure tab order is correct besides positioning

### ISSUE THREAD

**Issue by Phyks** [metafizzy/isotope#1137]
Hi,

When using isotope (fitRows algorithm, but not sure it is relevant) with filtering and sorting, the items are reorganized in the grid layout.

But when pressing `TAB` key, the tab-ing order is not the same as the visual order, which is quite confusing, especially from an accessibility point of view.

I am not really sure about the correct way to solve it, but I guess it can be handled by the use of `tabindex` or anything related.

Typical tab-ing order on the following screen is:
* Bob Dylan
* Breaking Benjamin
* Inconnu (Orphelin)
(as expected as of now)
* Megaherz
(Mika was expected)
* Mickey 3D
* Mika
* Nightwish
* Nirvana
* …

![2016-07-25-234940](https://cloud.githubusercontent.com/assets/3856586/17118807/b5d8e520-52c2-11e6-852b-6247f35fb7f1.png)

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. We already have an issue opened for this one. See #1108

**Comment by Phyks** [comment]
Oops, sorry I did not find it in my search before opening it… Will follow #1108 then! Thanks
