### ISSUE TITLE
Responsive flow, sorted and same space between items

### ISSUE THREAD

**Issue by mrondra** [metafizzy/isotope#1138]
Hello, I would like a help from you. I have a grid with pictures of different sizes and I'd like to know if it's possible to have a layout like is shown on codepen. 

**Codepen:** http://codepen.io/razorlight/pen/BzVBjB

I want it to be responsive, pixel sorted and same space between every item. I spent a lot of time trying to figure it out and this is the result. I'm not satisfied with it and I'd like to know if there's a way to make it better, which I believe there is. 

Can you help me? 
Thanks

**Comment by desandro** [comment]
You can simplify your JS to be

``` js
$('.lookbook__first').isotope({
    itemSelector: '.lookbook__grid',
    layoutMode: 'packery',
    packery: {
      columnWidth: '.lookbook__sizer',
      gutter: 21
    }
});
```

You'll also need [imagesLoaded](http://isotope.metafizzy.co/layout.html#imagesloaded)

See demo http://codepen.io/desandro/pen/763516bc81d75016a82f691cbb107116/

**Comment by mrondra** [comment]
Thanks for reply, but I can't see any change. The corners still don't match. Maybe it's a bit worse

**Comment by desandro** [comment]
> The corners still don't match

If you want to perfectly line up every item, you'll have to size your items so that they fit perfectly in the grid. The gutter will have to be a percent size. Let's use `5%`. If we have a grid of six columns ...

```
( 100% - 5 * 5% ) / 6 = 12.5%
```

Column width would be 12.5%.

```
5% gutter
12.5% column

1 column = 12.5% * 1 + 5% * 0 = 12.5%
2 column = 12.5% * 2 + 5% * 1 = 30%
3 column = 12.5% * 3 + 5% * 2 = 47.5%
4 column = 12.5% * 4 + 5% * 3 = 65%
5 column = 12.5% * 5 + 5% * 4 = 82.5%
6 column (full width) = 100%
```

Image sizes need to adhere to those ratios. A 2x3 item would have a ratio of 30:47.5.

See demo http://codepen.io/desandro/pen/6d7e82d4277fc053772bf9c7c05fa413

**Comment by mrondra** [comment]
Oh thanks it looks good now. One more question, is it possible to have constant gutter size, let's say 20px and still have corners matched?

**Comment by desandro** [comment]
No, because both the height and the width of the items need be proportional to the grid.

**Comment by mrondra** [comment]
Yeah I thought so. Ok thanks for help
