### ISSUE TITLE
Get position of hidden items by 'filter'.

### ISSUE THREAD

**Issue by rafavth** [metafizzy/isotope#1139]
As you can see in this jsfiddle the first time you filter,animation is different because hidden items are looking for its position.Is there a way to avoid this?

https://jsfiddle.net/a8255xz4/1/

Thank you.

**Comment by desandro** [comment]
The other items need to have a position first set. You can do this by filtering for them first, then filtering for other groups, then setting transition duration. See demo https://jsfiddle.net/ynv7waLs/

**Comment by rafavth** [comment]
Thank you desandro.
