### ISSUE TITLE
Transitions for items still visible after filtering

### ISSUE THREAD

**Issue by richardbuff** [metafizzy/isotope#1140]
If you look at the example at the top of the page here,  http://isotope.metafizzy.co/filtering.html, and you click the 'number > 50' filter, the first 5 items remain visible.  This works fine with small grid items and larger screensizes.  

But with larger grid items (where there may only be 1 or 2 items in each column), on smaller devices, the 6th item (the first one that has any movement/transition) would be offscreen.  So the user would have no visual feedback that anything happened when they clicked the filter. 

Is there a recommended way to make the visible grid items fade/flicker/etc.. so that there is some visual feedback that they were in fact filtered?

**Comment by desandro** [comment]
You could show a count of currently visible items. See demo http://codepen.io/desandro/pen/pbkbBO

**Comment by richardbuff** [comment]
Ah, excellent, thanks @desandro I was so hung up on showing feedback on the grid items themselves that I hadn't even considered that approach.  That would be a nice example to add the plugin's doc's  or FAQs if it's not already in there somewhere (just a suggestion).  Keep up the great work, this is one of my favorite jQuery plugins to work with

**Comment by desandro** [comment]
Just added to [Extra examples](http://isotope.metafizzy.co/extras.html#extra-examples)
