### ISSUE TITLE
Masonry Search

### ISSUE THREAD

**Issue by manattweb** [metafizzy/isotope#1141]
I'm very sorry about this, but my issue doesn't exist on desktop browsers at all - it works great when using something like the developer console in responsive mode; however, it doesn't work on iOS mobile browsers (Safari, Chrome tested).

The issue is that when using search to filter the grid elements, the resulting elements are displaying down the page outside of the container that holds them instead of moving up to the top.

LINK: http://dev.localfirstar.com/directory

Any help would be greatly appreciated as this project is due to go live next week.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
