### ISSUE TITLE
Center items inside container

### ISSUE THREAD

**Issue by gielcobben** [metafizzy/isotope#1142]
Hey,

Is it possible to generate a layout from the center of the container instead of the left side? 
I quickly made an image that isn't totally accurate but I think you get the idea. It's a sort of 'timeline' / 'spineAlign' layout but with more items next to each other.

![centered](https://cloud.githubusercontent.com/assets/2663212/17246998/2836a682-5590-11e6-8740-0a20dad476ad.jpg)

I hope someone can help me out.

Thanks,
Giel.

**Comment by desandro** [comment]
Yes, it's possible by creating your own custom layout mode. Take a look at some [fit-rows.js source code](https://github.com/metafizzy/isotope/blob/v3.0.1/js/layout-modes/fit-rows.js) for a simplified example. Here's the [old spineAlign code](https://github.com/metafizzy/isotope/blob/gh-pages/_posts/custom-layout-modes/2011-10-18-spine-align.html#L57-L90) used in Isotope v1. Isotope's layout mode API changed from v1 to v2, but you may be able to see how it worked.
