### ISSUE TITLE
grid breaks if first item is full width

### ISSUE THREAD

**Issue by basvandertogt** [metafizzy/isotope#1144]
Hi,

My grid breaks when the first grid-item is a full width (100%) item.
All items after the first are left aligned then while these items are 50%.
It would be fantastic if someone can point me what i'm doing wrong.
Demo: http://blok.hyperconnected.nl/dames/

Regards,
Bas

**Comment by desandro** [comment]
Set `columnWidth`. See http://isotope.metafizzy.co/faq.html#the-first-item-breaks-the-grid
