### ISSUE TITLE
Isotope and Unite Gallery

### ISSUE THREAD

**Issue by Svoeobraznaya** [metafizzy/isotope#1145]
Hello. Isotope plugin doesn't work with unite gallery. Why? How can I fix this problem?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
