### ISSUE TITLE
Question: Is there a correct way to hide some elements after filtering manually by javascript?

### ISSUE THREAD

**Issue by jousch** [metafizzy/isotope#1146]
If you check out my codepen you see, that I want to filter by class (austria, germany). And after that I actually try to hide superfluous violet dividing lines by using the event layoutComplete.

My problem is, that if I add in js line 65 `$grid.isotope('layout');` my browser window freezes.

Do anybody of you maybe have a tip or solution on how to resolve it without freezes? Is there a correct way?

_Josef_

**Test case:** http://codepen.io/jousch/pen/mEQjRz/

**Comment by phongtran0** [comment]
If I was coding it, I would do something like this instead since the real trigger is your button filters.

Add an 'all' or 'alle' class to the first button and use the button click to show or hide the dividers.
,,,
$('.button-group').each( function( i, buttonGroup ) {
  var $buttonGroup = $( buttonGroup );
  $buttonGroup.on( 'click', 'button', function() {
    $buttonGroup.find('.is-checked').removeClass('is-checked').removeAttr('disabled');
    $( this ).addClass('is-checked').attr('disabled','disabled');
    
    if ($(this).hasClass('all')) {
        $('.grid-item--divider').show();
      } else {
        $('.grid-item--divider').hide();
      }
    $grid.isotope('layout');
    
  });
});
,,,

Remove the layoutComplete function entirely as when you put the isotope('layout') on line 65, you're creating an infinite loop with layout and layoutComplete which is causing the browser freeze.

**Comment by phongtran0** [comment]
After looking at the code more, I merged the two button functions and got the following:

```
$('.filters-button-group').on( 'click', 'button', function() {
  var filterValue = $( this ).attr('data-filter');
  // use filterFn if matches value
  filterValue = filterFns[ filterValue ] || filterValue;
  
  $('.button-group').find('.is-checked').removeClass('is-checked').removeAttr('disabled');
    $( this ).addClass('is-checked').attr('disabled','disabled');
    
    if ($(this).hasClass('all')) {
        $('.grid-item--divider').show();
      } else {
        $('.grid-item--divider').hide();
      }
  
  $grid.isotope({ filter: filterValue });
});
```

**Comment by desandro** [comment]
One way to do this is by checking for duplicate dividers within a [filter function](http://isotope.metafizzy.co/filtering.html#functions)

``` js
var filterValue = '*';
// keep track of previous filtered element
var prevFilterDivider = false;

var $grid = $('.grid').isotope({
  filter: function() {
    if ( filterValue == '*' ) {
      return true;  
    }
    var $this = $( this );
    var isDivider = $this.is('.grid-item--divider');
    var isFiltered;
    if ( isDivider ) {
      // visible if previous filtered item was not divider
      isFiltered = !prevFilterDivider;
      prevFilterDivider = isFiltered || prevFilterDivider;
      return isFiltered;
    }
    isFiltered = $this.is( filterValue );
    prevFilterDivider = isFiltered ? false : prevFilterDivider;
    return isFiltered;
  }
});
```

See demo http://codepen.io/desandro/pen/a61fd2b6c99605d2efeb29b9ff908494

**Comment by phongtran0** [comment]
Oops, missed the point of what he was trying to do.

**Comment by jousch** [comment]
Wow, thanks for your quick replies! @desandro after reading your code I tried to add an additional code to hide also a divider at the first position. Do you've an idea how to extend your snippet?

**Comment by desandro** [comment]
If you reset `prevFilterDivider = true;` instead of `false`, it should hide the first divider it encounters

**Comment by jousch** [comment]
Thx!! Thank you for your tipps!
