### ISSUE TITLE
AMD/requireJS problem

### ISSUE THREAD

**Issue by tigusigalpa** [metafizzy/isotope#1147]
Hi!
im trying to make it works on Moodle website. Moodle now uses AMD/requireJS. So my code is
`(function( factory ) {
    if ( typeof require === "function" ) {
        require([
            'jquery'
            ,'theme_pioneer/isotope'
            ,'theme_pioneer/jquery-bridget'
        ], factory );
    } else {
        factory( jQuery );
    }
}(function( jQuery, Isotope, jQueryBridget ) {
    jQuery.noConflict( true );

```
jQueryBridget( 'isotope', Isotope, jQuery );
jQuery( document ).on( 'click', '.isotopefilterlink', function() {
    var filterValue = jQuery( this ).data( 'filter' );
    jQuery( '.isotoped' ).isotope( {
        filter:        filterValue
        ,itemSelector: '.isotope-item'
    } );

    return false;
} );
```

} ) );`
But it not works and writes in console

**Uncaught TypeError: Cannot read property 'option' of undefined**

line 86 at **jquery-bridge**

`!PluginClass.prototype.option`

**Comment by davecarlile** [comment]
There appears to be an issue with the AMD section at the top of the library. I used the following code to make isotope a plugin, but it was throwing an error:

```
require( [ 'jquery-bridget/jquery-bridget' ],
function( jQueryBridget ) {
    // make Isotope a jQuery plugin
    jQueryBridget( 'isotope', Isotope, $ );
    // now you can use $().isotope()
});
```
I modified line 24 of isotope.pkgd to return the result of the factory statement and it started working:

```
  if ( typeof define == 'function' && define.amd ) {
    // AMD
    define( 'jquery-bridget/jquery-bridget',[ 'jquery' ], function( jQuery ) {
      return factory( window, jQuery );
    });
  }
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by jingjiewei** [comment]
Hi @davecarlile ,after modifieds line 24, i got another issue "isotope.pkgd.js:3351 Uncaught TypeError: Cannot read property 'masonry' of undefined", have any idea?

**Comment by desandro** [comment]
@jingjiewei Can you please open a new issue with a [**reduced test case**](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues)
