### ISSUE TITLE
Filtering to one column in specific case

### ISSUE THREAD

**Issue by keccakec** [metafizzy/isotope#1149]
**Test case:** http://codepen.io/keccakec/pen/wWOEAV

I want to create a multi-filterable gallery like this, but it seems to randomly put everything in one column upon filtering. I didn't want to submit this as an issue, but I can't figure out why this is happening. It could just be something obvious I'm missing. I think it may have to do with filtering from a combination of data filters that have no results to one that has multiple. Clicking front end -> canvas, then switching from canvas to sass will reproduce this.

**Comment by desandro** [comment]
I'm not able to reproduce this issue. Were you able to fix it?

Also, I recommend using [element sizing](http://isotope.metafizzy.co/options.html#element-sizing) over setting `columnWidth` in JS. It's more flexible and keeps your logic in your CSS>

**Comment by phongtran0** [comment]
I took a stab at it as I like practicing my coding to get better.  I made the following changes and I think it works the way I would expect it to.

```
isotope = function() {
      grid.isotope({
        resizable: false,
        itemSelector: '.tile',
        masonry: {
          columnWidth: colWidth(),
          gutterWidth: 15
        }
      })
```

I removed the filterString parameter from the initialization of the isotope function as filters can always be applied later.

```
function globalSet() {
  console.log(globalFilter);
  grid.isotope({filter: globalFilter});
}

$(window).resize(function() {
    clearTimeout(this.id);
    this.id = setTimeout(function() { grid.isotope('destroy');
                                     isotope();
    }, 500);
});

isotope();
```

I then initialized the isotope function which creates the isotope instance with the function globalSet applying the filter only.  If the window is resized, the isotope grid is destroyed and reinitialized which should check the ColWidth() function again.

Hope that helps.

**Comment by phongtran0** [comment]
Ok, I think I got it this time.  

```
function globalSet() {
  console.log(globalFilter);
  grid.isotope({filter: globalFilter});
}

$(window).resize(function() {
    clearTimeout(this.id);
    this.id = setTimeout(function() { grid.isotope('destroy');
                                     isotope(globalFilter);
                   
    }, 500);
});

isotope(globalFilter);
```

I kept the filterString parameter in the isotope creation but kept globalSet function applying the filter only.  When the window is resized, the isotope grid is destroyed and recreated with the existing filter settings.   Now I think it works the way I would expect.

Hope that helps.

**Comment by keccakec** [comment]
Thanks so much for the help and the recommendation from you both. It seems to be working as expected now, so I'll close this.
