### ISSUE TITLE
Infinite scroll: Images overlap on first load and flashes on first append

### ISSUE THREAD

**Issue by RBIII** [metafizzy/isotope#1152]
Hi, I'm working on a site using Ruby on Rails that uses Isotope with the Kaminari gem for infinite scrolling. It generally works well, except on the initial load of the page where images often start off overlapping before adjusting, and on the first append, the page will flash when the new elements are added.

After that first load everything works great, but since it's the first load it will be seen by every user, every time so I'd really like to figure out why this is happening. Any advice is appriciated!

page: http://immense-wildwood-9339.herokuapp.com/discover/index

index.html.erb
```html
<div class="masonry-container">
      <div class="row">
        <div id="discover_emails" class="masonry isotopeContainer">
          <%= render @discover_emails %>
        </div>
        <%= paginate @discover_emails %>
      </div>
    </div>
```

discover.js
```javascript
$(window).load(function () {
  var $container = $('#discover_emails');

  $container.imagesLoaded(function () {
    $container.isotope({
      itemSelector: '#discover_emails div.discover_email',
      animate: true
    });

    $container.infinitescroll({
      navSelector: 'nav.pagination', // selector for the paged navigation
      nextSelector: 'nav.pagination a[rel=next]', // selector for the NEXT link (to page 2)
      itemSelector: '#discover_emails div.discover_email', // selector for all items you'll retrieve
      bufferPx: Math.round($(window).height() * 1.5),
      loading: {
        finishedMsg: 'No more products to load.',
        img: 'data:image/gif;base64,R0lGODlhAQABAHAAACH5BAUAAAAALAAAAAABAAEAAAICRAEAOw==',
        msgText: ""
      }
    },
    // call Isotope as a callback
    function (newElements) {
      var $newElems = $(newElements);
      $newElems.imagesLoaded(function () {
        $container.isotope('appended', $newElems);
      });
    });
  });
});
```

**Comment by TimothyRackham** [comment]
Has the issue been addressed, I am experiencing the same issue
url (http://gochattervideos.com/blog/archive.php)

**Comment by RBIII** [comment]
Never addressed. I fixed the flashing issue by changing the isotope callback from
javascript```
    function (newElements) {
      var $newElems = $(newElements);
      $newElems.imagesLoaded(function () {
        $container.isotope('appended', $newElems);
      });
    });
```

to this
javascript```
  function (newElements) {
      var $newElems = $(newElements).hide();
      $newElems.imagesLoaded(function () {
        $newElems.fadeIn();
        $container.isotope('appended', $newElems);
      });
    });
```

However I was never able to fix the overlapping issue entirely
