### ISSUE TITLE
Bug in filtering, Safari browser.

### ISSUE THREAD

**Issue by DeoThemes** [metafizzy/isotope#1154]
Hey,
I'm having an issue on filtering in Safari browser, latest version. Please check the attachment video.
Any solution how to fix this?

Thanks.

[pb-filter-folio.zip](https://github.com/metafizzy/isotope/files/449807/pb-filter-folio.zip)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by DeoThemes** [comment]
Hi again.

Appologize, it was the problem of the old version of the plugin. Client updated it and everythin is working fine already.

Thanks.
