### ISSUE TITLE
Combination Filters - 2 dropdowns (select options) + Reset button + Search (input)

### ISSUE THREAD

**Issue by hybrid8287** [metafizzy/isotope#1155]
Hey all,

I just recently found this great plugin but have a question.  How can I add the "Search" functionality to what I currently have?  At the moment, I have it working with 2 dropdowns (select options), and a Reset button, but I am in need of the "Search" functionality as well.

I've seen just about all examples out there and there hasn't been one made yet (or at least that I've seen) regarding these 3 different types of filtering.  Any help would be greatly appreciated.

Here is a fiddle of what I got so far: https://jsfiddle.net/Lbya59bb/

On the js part of this fiddle, please scroll down to the very bottom - I commented where things need to be edited...And apologies for the layout...

**Comment by desandro** [comment]
> 3 different types of filtering

Isotope can handle this, but I cannot recommend it. The code is complex for you to maintain, and the user experience is complex for your users.
