### ISSUE TITLE
Limit to opened category only

### ISSUE THREAD

**Issue by stefanjap** [metafizzy/isotope#1156]
Hi,

My English is bad but I will try my best. 

There is a product that is under several categories (in this case 3 categories). That product shows up on all the categories it's assigned to which is correct. But why does the category name show 3 of the same? 

Category example:
Plants
-Low tech
--In Vitro
-Medium tech
--In Vitro
-Hi tech
--In Vitro

A product that is in all 3 categories under in vitro. And when I check the Hi tech category, the Isotope shows: In vitro, In vitro, In vitro

Why is that?
And how can I prevent/fix it in a simple way? 
Maybe limit the isotope to the specific category only?

Best regards,
Stefan Johansson

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
