### ISSUE TITLE
Rebuild distribution packages

### ISSUE THREAD

**Issue by timneutkens** [metafizzy/isotope#1157]
The distribution packages depend on `jquery-bridget` which had an AMD loader bug fixed by @desandro in the [following commit](https://github.com/desandro/jquery-bridget/commit/bd09b859b4eac30a8c768983a5d85f307b2d2f89#diff-8e6400e9e79ac3fc6514dfa896a9542aR15) could you rebuild the dist folder / cdn to reflect this change? Thanks! 👍

**Comment by desandro** [comment]
Thanks for reminding me. This fix will be in the next release of Isotope.

**Comment by timneutkens** [comment]
Great 👍  Do you have an ETA on the new release? 🚀

**Comment by timneutkens** [comment]
Closing this, looking forward to the next release 👍

**Comment by timneutkens** [comment]
Hasn't been resolved yet ❤️

**Comment by desandro** [comment]
Done!

**Comment by timneutkens** [comment]
Thanks ❤️
