### ISSUE TITLE
Is there a way to load the items directly on their position even before the page loads so you won't see an unstyled grid?

### ISSUE THREAD

**Issue by ableslayer** [metafizzy/isotope#1158]
I'm using Isotope layout for a page that loads a lot of items like a  gallery. But the grid uses same width and height images (300x300) so I was hoping that when it loads, even if it's loading a lot of items in one page, it won't look unstyled. 

As of now, when the page is still loading, the items in the grid are touching each other, it doesn't have a gap. After the page loads, the items arranges itself properly. 

How can I make the grid looked finish even if the other part of the page is still loading?

Here's a test case: http://codepen.io/ableslayer/pen/dporbb

The only problem with this test case is that the time that the boxes touches each other is very fast. But in mine, since I have more items, it takes more than 5secs and therefore you will have a good look at the unstyled grid. And not to mention that it looked weird that the page looks like it moves for a while after relay outing.

**Comment by desandro** [comment]
See demo http://codepen.io/desandro/pen/6a9dcd98b132f5b078ab3fcb972f7825

I hide the grid with `is-hidden` class. After`imagesLoaded` I remove this class, which fades in the grid. Isotope is then triggered. Since all images have loaded, everything is in place.

**Comment by ableslayer** [comment]
Thanks @desandro, never thought about adding another class to the grid and use it in the imagesloaded script. This works perfectly!
