### ISSUE TITLE
Isotope filter loading all categories on page load, not selected category

### ISSUE THREAD

**Issue by vegman** [metafizzy/isotope#1159]
My isotope filter is loading all categories on page load, not the selected category.  I did the best I could with my test case.  Hopefully you'll be able to figure out how to get the page to load with the selected category only.  Appreciate the help!

**Test case:** https://codepen.io/PaulyC777/pen/pEJEPR

**Comment by desandro** [comment]
1. Remove the `.isotope` CSS styles. These are no longer needed as of Isotope v2
2. I recommend upgrading to the [latest Isotope v3](http://isotope.metafizzy.co). Looks like your HTML has `js/jquery.isotope.min.js` which is the file used in Isotope v1
3. [Don't use window.load](http://metafizzy.co/blog/window-load-last-resort/)
4. Remove `$(window).on("resize", ...`. Isotope already does this for you.
5. Now then...

You can set an initial filter when you initialize Isotope. Currently your code is:

``` js
    $container.isotope({ 
        filter: '*',
        layoutMode: 'fitRows'
    });
```

You can change `filter:` to the selector you want to be the initial filter.

**Comment by vegman** [comment]
Hi David,



Thanks so much. I did what you suggested and don't worry, the
jquery.isotope.min.js now contains v3


The selected category loads now on page load, but for some reason the page
is still connecting with the youtube and facebook videos during the page
load, thus slowing the selected page of jpegs.



I don't know why it's doing that. While the page is connecting with youtube
and facebook, despite the page load of just jpegs, you can't scroll until
the page finishes connecting with the media sites...strange!



I have a possible solution but am unable to figure out how to execute
it.  Maybe
you could help?



Currently, the jpegs appear as thumbnails. Clicking on them opens a
semi-transparent window and makes them larger.



I couldn't figure out how to do that with the videos, so I just coded the
videos to load as full size thumbnails...clicking the youtube/facebook
arrow plays them as the thumbnail video.



I can instead create a small thumbnail jpeg of the video for page load, but
is there a way to load the videos in the semi-transparent window like the
full-size jpegs do? If possible, please list the code as well as placement,
as I'm not that savvy with js.  The html reference to <div
class="video-container5 iframe"> on the isotope-filter3 (videos) is there
only to help make the page responsive via my css.



I've attached my html and js pages. Here's my site as well:
http://www.boulderdrumstudio.com/gallery.htm



Thanks so much!

**Comment by desandro** [comment]
Sorry, but I won't be able to help with video loading.
