### ISSUE TITLE
question / feature request: disallow multiple occurences of a specific element in a row

### ISSUE THREAD

**Issue by minitauros** [metafizzy/isotope#1160]
I've ran into this a couple of times now: a customer would like to fill up the grid with some (for example) random empty blocks, for decoration. The problem is that these blocks are the same size as the regular blocks. This sometimes results in having a row full of empty blocks, which looks kinda weird. It would be great if I could specify something like "allow a maximum of 1 element with class x per row". Is this possible? If not, I would like to make this a feature request :).

**Comment by desandro** [comment]
Thanks for this feature request. Sorry, but Isotope will not natively support this feature. If you have a **reduced test case** demo, that could be helpful for other users who are interested in this feature.  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
