### ISSUE TITLE
automatically shuffle after a period

### ISSUE THREAD

**Issue by robbisy** [metafizzy/isotope#1161]
Hi I've seen the shuffle button which order items in a random order.
And I want to know if it's possible to do that automatically after a period without having to click on the button 
Thanks

**Comment by desandro** [comment]
``` js
// shuffle after 30 seconds
setTimeout( function() {
  $grid.isotope('shuffle');
}, 30 * 1000 );
```

See also [Isotope Card Match Game](http://codepen.io/gabriellewee/pen/xOBLgX) which has a shuffle every-so-often behavior.
