### ISSUE TITLE
layout not rendering when dynamically loading data from angular service while normally it rendering fine.

### ISSUE THREAD

**Issue by Gnanakannan** [metafizzy/isotope#1162]
layout not rendering when dynamically loading data from angular service while normally it rendering fine.

Even though I call the isotope('layout') once again after data load, it is NOT rendering the next row tile the least height white space.

It render the next row tile as like table new row.

Regards
Kannan

**Comment by hanwong** [comment]
Me too.
Layout is not rendered when using ng-repeat contents.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
