### ISSUE TITLE
Filtering wordpress issue

### ISSUE THREAD

**Issue by chriswhiting** [metafizzy/isotope#1164]
Hello

I have created a isotope grid layout which is filterable via data filters and classes. It all is working perfectly on my codepen and static HTML website. 

http://codepen.io/anon/pen/yaZXVQ

When i try to insert this into my clients Wordpress website the filtering no longer works. As far as i can tell from web tools the .js file is being brought it. Has anyone else had a similar problem?

http://www.phelanbarker.com/wordpress/

Thanks in advance for any help.

Chris

**Comment by downFast** [comment]
console says:

Uncaught TypeError: $ is not a function

Try to insert your js code inside a $ function

```
(function($) {
  ... your code...
})(jQuery);
```

See if that helps

**Comment by chriswhiting** [comment]
Thanks for the quick reponse @downFast 

I have changed the js code but still getting the same issue. I notice now you've said that the same file has another error now. I originally started this a few months ago then put it down for a while and just coming back to it. Strange that the filtering works in other environments.

**Comment by downFast** [comment]
when i go to your site i still see the js errors, those errors are most likely because of jQuery conflict. That's why you need to insert that code i provided. Could you put it and let me know so that I can check it again?

**Comment by chriswhiting** [comment]
@downFast I have changed the code.

The file producing those errors used to read..

```
// external js: isotope.pkgd.js, packery-mode.pkgd.js

$( function() {
  
  $('.grid').isotope({
    layoutMode: 'packery',
    filter: '*',
    itemSelector: '.grid-item',
    packery: {
      gutter: 0
    }
  });
  
});

$(window).load(function(){
    var $grid = $('.grid');
    $grid.isotope({
        filter: '*',
        animationOptions: {
            duration: 950,
            easing: 'linear',
            queue: false
        }
    });
 
    $('.gridFilter a').click(function(){
        $('.gridFilter .current').removeClass('current');
        $(this).addClass('current');
 
        var selector = $(this).attr('data-filter');
        $grid.isotope({
            filter: selector,
            animationOptions: {
                duration: 750,
                easing: 'linear',
                queue: false
            }
         });
         return false;
    }); 
});

```

And now it reads...
```

// external js: isotope.pkgd.js, packery-mode.pkgd.js

(function($) {

  $('.grid').isotope({
    layoutMode: 'packery',
    filter: '*',
    itemSelector: '.grid-item',
    packery: {
      gutter: 0
    }
  });

});

$(window).load(function(){
    var $grid = $('.grid');
    $grid.isotope({
        filter: '*',
        animationOptions: {
            duration: 950,
            easing: 'linear',
            queue: false
        }
    });

    $('.gridFilter a').click(function(){
        $('.gridFilter .current').removeClass('current');
        $(this).addClass('current');

        var selector = $(this).attr('data-filter');
        $grid.isotope({
            filter: selector,
            animationOptions: {
                duration: 750,
                easing: 'linear',
                queue: false
            }
         });
         return false;
    });
});
```

**Comment by downFast** [comment]
you are missing the closing

`})(jQuery);`

You can see in your site console the same error twice:

`Uncaught TypeError: $ is not a function`

**Comment by chriswhiting** [comment]
Sorry mate, i mis-understood your first post. Ive changed it again now, seems to be working. Thanks a lot, does that look correct to you now @downFast ?

**Comment by downFast** [comment]
it works but on your link i still see the error:

Basically you need this:

it works but on your link i still see the error:

Basically you need this, see the function and the closing jquery? Also you are calling layoutmode "packery" but you didn't include the packery layout mode file, see the docs that says to include the [packery layout mode](http://isotope.metafizzy.co/layout-modes/packery.html)

```
(function($) {
  
  $('.grid').isotope({
    layoutMode: 'packery',
    filter: '*',
    itemSelector: '.grid-item',
    packery: {
      gutter: 0
    }
  });
  
});

$(window).load(function(){
    var $grid = $('.grid');
    $grid.isotope({
        filter: '*',
        animationOptions: {
            duration: 950,
            easing: 'linear',
            queue: false
        }
    });
 
    $('.gridFilter a').click(function(){
        $('.gridFilter .current').removeClass('current');
        $(this).addClass('current');
 
        var selector = $(this).attr('data-filter');
        $grid.isotope({
            filter: selector,
            animationOptions: {
                duration: 750,
                easing: 'linear',
                queue: false
            }
         });
         return false;
    }); 
})(jQuery);
```

**Comment by desandro** [comment]
@downFast Thanks so much for handling this issue!
