### ISSUE TITLE
Isotope 3 spaces / gaps on first load

### ISSUE THREAD

**Issue by anteksiler** [metafizzy/isotope#1165]
Hi everyone,

I can't figure out why there are spaces between columns on first load: http://werkstatt.fuelthemes.net They disappear after resize.

I don't see it on dom explorer either.

Test case: http://werkstatt.fuelthemes.net/

**Comment by desandro** [comment]
I believe it's due to the scrollbar appearing. You can resolve this by forcing a scrollbar in CSS

``` css
html { overflow-y: scroll; }
```

**Comment by anteksiler** [comment]
@desandro OMG, I really did not expect it to be that easy :)
