### ISSUE TITLE
ISOTOPE - Commercial Organization license

### ISSUE THREAD

**Issue by ankitvasani** [metafizzy/isotope#1166]
Hello,

our company (Investis) has recently procured commercial organization license. is there any notation we have to add in the source file to denote it is licensed version?

after acquiring license, we only got PDF and invoice but didn't get any specific key/notation to be used in the code base.

your help would be highly appreciated. 

Thanks,
Ankit Vasani

**Comment by desandro** [comment]
Thank you for your purchase. You are now free to use Isotope in your commercial projects. I have record of your purchase, so there is no additional registration to go through. Thanks for checking!
