### ISSUE TITLE
Initialize isotope with a certain amount of items

### ISSUE THREAD

**Issue by ochoarobert1** [metafizzy/isotope#1167]
I want to initialize isotope on my portfolio page with only 8 elements, can i initialize this someway?

**Test case:** http://codepen.io/ochoarobert1/pen/kkbwap

**Comment by desandro** [comment]
Yes! You can use a [filter function](http://isotope.metafizzy.co/filtering.html#filter-functions)

``` js
  filter: function(){
    return $(this).index() < 8;
  }
```

**Comment by ochoarobert1** [comment]
Incredible man! you are a Genius, thanks! :)
