### ISSUE TITLE
Padding on grid items

### ISSUE THREAD

**Issue by chriswhiting** [metafizzy/isotope#1168]
I have been working on the following packery layout (see codepen). 

http://codepen.io/anon/pen/EgKdpL (Padding to all)

I am trying to create a white border around the outside of all my grid items. I have tried a couple of different ways to do this, applying a border to the grid items and applying padding to the grid items. Each time i am left with uneven borders. (see the first blue box)

When i tried applying the padding individually it became clear that some sides of grid items were not receiving the border/padding. (see below) it appears to be the bottom that is not receiving.

http://codepen.io/anon/pen/QKNkzd (individual padding)

I notice that you can use gutter, but that only applies to sides. Is there anything else?

Appreciate any help, seems as though the sort of thing that i am missing something small on.

**Comment by desandro** [comment]
Thanks for reporting this issue and your demos. Looks like the images in the second demo are not working, could you take a look?

**Comment by chriswhiting** [comment]
Hi @desandro i have fixed the image links now - it seems as though i only get padding problem on my one third box.
