### ISSUE TITLE
Isotope Tiles Out Of Order

### ISSUE THREAD

**Issue by Johnnh** [metafizzy/isotope#1169]
Hi there, I incorrectly posted an issue to 'masonry' the other day that is in fact related to isotope.

The website url is below:

http://www.butterscotchdesign.com/work/

The 8th image 'Deborah Goodchild - Sketched tall house and tree' unexpectedly swaps it's order with the Garden Gent image and breaks the expected layout as you resize the window.

I can reproduce this consistently across all browsers and am wondering what I am doing wrong?

I am using isotope-horizontal-masonry.js in addition to the core code.

Any ideas would be greatly appreciated.

Thanks for your time and help with this.

**Comment by desandro** [comment]
Thanks for reporting this issue. This is well known issue with pixel rounding differences between JS and CSS. See possible solution in desandro/masonry#811. Closing here, keep discussion there.
