### ISSUE TITLE
Is it possible to reset values in one group of checkboxes when a checkbox from another group is checked?

### ISSUE THREAD

**Issue by barrygirsh** [metafizzy/isotope#1171]
**Test case:** http://codepen.io/desandro/pen/mEinp
See: https://peakpropertygroup.com/ajax/
jQuery(function ($) {
	$('input[type="radio"]').on('click change', function(e) {
		console.log(e.type);
	});
	// store filter per group
	var filters = {};
	
	var $container = $('#isotope-list').isotope({
	  itemSelector : '.item', 
  		layoutMode : 'vertical'
	});
	
	var iso = $container.data('isotope');
	var $filterCount = $('.filter-count');
	//var $filterDisplay = $('.sidebar');
	
	function updateFilterCount() {
	  $filterCount.text( iso.filteredItems.length + ' items' );
	}
	updateFilterCount();
	
	$container.isotope();
	// do stuff when checkbox change
	$('#options').on( 'click', 'input', function( event ) {
	  var checkbox = event.target;
	  var $checkbox = $( checkbox );
	  var group = $checkbox.parents('.option-set').attr('data-group');
	  // create array for filter group, if not there yet
	  var filterGroup = filters[ group ];
	  if ( !filterGroup ) {
		filterGroup = filters[ group ] = [];
	  }
	  // add/remove filter
	  if ( checkbox.checked ) {
		// add filter
		filterGroup.push( checkbox.value );
	  } else {
		// remove filter
		var index = filterGroup.indexOf( checkbox.value );
		filterGroup.splice( index, 1 );
	  }
	  
	  var comboFilter = getComboFilter();
	  $container.isotope({ filter: comboFilter });
	  //$filterDisplay.text( comboFilter );
	  updateFilterCount();
	});
	
	function getComboFilter() {
	  var combo = [];
	  for ( var prop in filters ) {
		var group = filters[ prop ];
		if ( !group.length ) {
		  // no filters in group, carry on
		  continue;
		}
		// add first group
		if ( !combo.length ) {
		  combo = group.slice(0);
		  continue;
		}
		// add additional groups
		var nextCombo = [];
		// split group into combo: [ A, B ] & [ 1, 2 ] => [ A1, A2, B1, B2 ]
		for ( var i=0; i < combo.length; i++ ) {
		  for ( var j=0; j < group.length; j++ ) {
			var item = combo[i] + group[j];
			nextCombo.push( item );
		  }
		}
		combo = nextCombo;
	  }
	  var comboFilter = combo.join(', ');
	  return comboFilter;
	}
});

**Comment by desandro** [comment]
Sorry, but I will not be able to personally provide a solution here. Yes this is possible, but it requires writing custom code.

**Comment by barrygirsh** [comment]
Are you available to do this as a consultant? If so, what is your hourly rate and when would you be available to get this done. Thank you
