### ISSUE TITLE
Conflict with Dojo

### ISSUE THREAD

**Issue by Eiad** [metafizzy/isotope#1172]
Hi, i work on IMB WCS, and it use Dojo toolkit but i can't seem to integrate isotope even though i use jQuery and other libraries (flexslider..etc) fine.

![screen shot 2016-09-25 at 13 13 11](https://cloud.githubusercontent.com/assets/4707734/18814130/d53e8ba6-8321-11e6-802a-1dabfdc0983b.png)

![screen shot 2016-09-25 at 14 57 46](https://cloud.githubusercontent.com/assets/4707734/18814867/725fde0e-8330-11e6-8a7a-fde6e904c2c2.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
