### ISSUE TITLE
Random stacking of all items in same place 

### ISSUE THREAD

**Issue by neilgee** [metafizzy/isotope#1173]
Hi,
I'm getting a random error when all items are being stacked left hand side of the page in the same place - it only happens some of the time and otherwise all items align in a grid properly, using v3.0.1

When it does occur all isotope items inherit the same css
```
element.style {
    position: absolute;
    left: 0px;
    top: 0px;
}
```

```
jQuery(document).ready(function($){

        /*main function*/
        $('.portfolio-content').isotope({
                // options
                itemSelector: '.portfolio-item',
        });



        /*filter*/
        $('.filter a').click(function() {
                var selector = $(this).attr('data-filter');
                $('.portfolio-content').isotope({
                filter: selector
                });
                $(this).parents('ul').find('a').removeClass('active');
                $(this).addClass('active');
        });
});
```
I don't get any console errors when it does occur

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by neilgee** [comment]
Not too sure why this was happening - I've a feeling I was using some older code - rebuilt and all ok now.
