### ISSUE TITLE
Unicode sorting, custom alphabet

### ISSUE THREAD

**Issue by lebac** [metafizzy/isotope#1174]
Hello, I want to thank you for a beautiful work you have done with Isotope. 

Also I would like to ask if it is possible in any way to sort by some custom function or means?
When using higher unicode characters in names and when sorting by them, sorting occurs by A-Z and then other characters.

Example would be in Serbian (sr-RS - latin encoding) character Č comes right after ABC, however in sorting the names of elements Č appears after Z (at the end). 

I have researched a bit about collation and custom sorting functions and was wondering if it is possible to do the sort by some custom order or function?

Thank you once again.

**Comment by desandro** [comment]
Yes, with [`getSortData` functions](http://isotope.metafizzy.co/sorting.html#getsortdata-functions), you can read each item and then assign a value to be used to sort it. In your case, this would mean parsing the string and assigning perhaps an integer value.
