### ISSUE TITLE
Filter .selector1 AND .selector2

### ISSUE THREAD

**Issue by mikewgd** [metafizzy/isotope#1176]
Hello,
First of all great plugin! Incredibly handy 👍 Anyways on to my issue. I am developing a site for an animal rescue and I would to include a filter that will help users narrow down the list of our animals according to the items selected. Rather than provide the entire site. I created a pen that demonstrates the issue I am having: http://codepen.io/mikewgd/pen/ozqOOX

Using the pen as an example. Lets say I click on "Male". I only see cards with Male. Great! However If I click on "Baby" nothing happens. I would expect that only cards that contain "Male" and "Baby" would appear. Another example would be clicking on "Male" and then "Adult", this now brings "Female" cards back into the mix.

Is there something I am missing here? If anyone could help me out. I would really appreciate it!
Thank you!

**Comment by desandro** [comment]
Thanks for the demo. If you want filters to be exclusive — `.male` and `.baby` — then the selector would look like `.male.baby`. Use `.join('')` so there is no comma. See demo http://codepen.io/desandro/pen/a9e132c1a4e65447a570f0f2a1e8b27c/

**Comment by mikewgd** [comment]
Oh, of course! I used your demo and this demo http://codepen.io/desandro/pen/MebyMR to achieve my desired filtering and worked like a charm! Thank you! :)
