### ISSUE TITLE
Filtering 2 sets - need total amount of results after filtering

### ISSUE THREAD

**Issue by eheiser** [metafizzy/isotope#1177]
We're using Isotope to filter on sets  - the actual page is here: http://atacama.be/reisaanbod
It's all working fine, the only snag that we're running into is that we need the total amount of results (of the 2 sets) after a filter is applied. We run the following code, where #nr-item is just a span where the number is inserted in. 

`$grid.on('arrangeComplete', function(event, filteredItems) {
                $('#nr-item').text(filteredItems.length);
            });`

Probleem is this arrangeComplete event fires twice, once for each set of items. I know this isn't really a bug but any suggestion you might have to solve this would be very much appreciated.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by eheiser** [comment]
I'll put up a pen and get back to you - thanks in advance for taking a look.

**Comment by eheiser** [comment]
Hi desandro - I have a codepen set up at http://codepen.io/eheiser/pen/KgOojL
Like I explained the filtering is working fine, it's just the number of results that we're having trouble with , check the code below the //set the nr of results for mobile use*/ comment
Any suggestions?

**Comment by desandro** [comment]
See http://codepen.io/desandro/pen/cf0274b2eb9f9a6bf6a98e34b8196836

The issue was that you're filtering two instances of Isotope. You had the right idea to use `.each()`. In my solution, I use it to keep track of counts for each instance. Then on arrangeComplete, those counts are then added for a total count.

``` js
var counts = [];

$grid.each( function( i, grid ) {
  var $iGrid = $( grid );
  $iGrid.on( 'arrangeComplete', function( event, filteredItems ) {
    // update grid count for specific grid
    counts[i] = filteredItems.length;
    updateNrItem();
  });
});

function updateNrItem() {
  var count = 0;
  counts.forEach( function( num ) {
    count += num;
  });
  $nrItem.text( count );
}
```

**Comment by eheiser** [comment]
Awesome - learned something new from this as well. I bought an isotope license as payment since I didn't see any donate button anywhere. Thanks man!

**Comment by desandro** [comment]
Thank you for supporting Isotope!
