### ISSUE TITLE
Spacing Issue with different width iems

### ISSUE THREAD

**Issue by mayank597** [metafizzy/isotope#1178]
i have issue with different size of element with bootstrap.
my html code looking like below code : 

    <div class="wall-container">
          <div class="grid-sizer col-md-3"></div>
          <div class="col-md-3 item" data-created="" data-pinned="" data-order=""></div>
          <div class="col-md-6 item" data-created="" data-pinned="" data-order=""></div>
          <div class="col-md-3 item" data-created="" data-pinned="" data-order=""></div>
          <div class="col-md-6 item" data-created="" data-pinned="" data-order=""></div>
          <div class="col-md-3 item" data-created="" data-pinned="" data-order=""></div>
          <div class="col-md-3 item" data-created="" data-pinned="" data-order=""></div>
          <div class="col-md-6 item" data-created="" data-pinned="" data-order=""></div>
    </div>
    $('.wall-container').isotope({
              itemSelector: ".item",
              percentPosition: true,
              layoutMode: 'packery',
              packery: {
			    // use outer width of grid-sizer for columnWidth
			    columnWidth: '.grid-sizer'
			  },
              sortBy: ['pinned', 'created', 'order'],
              sortAscending: false,
              getSortData: {
                pinned: function(elem){
                  return parseInt($(elem).attr('data-pinned'), 10);
                },
                created: function(elem){
                  return parseInt($(elem).attr('data-created'), 10);
                },
                order: '[data-order]'
              }
            });    
![1](https://cloud.githubusercontent.com/assets/22789551/19306014/42e0a294-9091-11e6-9998-08c359037ae0.png)
![2](https://cloud.githubusercontent.com/assets/22789551/19306015/42e36506-9091-11e6-80ab-85fd630b5b46.png)

it is not exactly my code but looking like my code

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by desandro** [comment]
Gaps may appear in Masonry layouts. Consider using the [Packery layout mode](http://isotope.metafizzy.co/layout-modes/packery.html), which can fill gap with items that can fit into them.
