### ISSUE TITLE
Chrome (desktop) doesn't sort in the same order as Firefox, IE or Safari

### ISSUE THREAD

**Issue by nicanaca0** [metafizzy/isotope#1179]
In this example you should see that in Chrome the grid cell 5 is in the incorrect position compared to the way Firefox and other browsers render it. The first row of cells are the same but for some reason Chrome doesn't handle the second row of cells in the same way.
- I've also included a HTML comment in the codepen example to show the basic difference.
- Chrome for IOS seems to not have this problem.
- I've tried adding a custom sort order and even tried reversing it and it made no difference, there were still differences between the browsers.

https://codepen.io/anon/pen/zKaLpB

**Comment by thesublimeobject** [comment]
@nicanaca0 The issue it the heights that you have set on the cells. If you notice, in Chrome, the height of item #1 is 565px, but the height of item #3 is 564px. On the other hand, in Firefox, item #1 has a height of 565px, and the height of item #3 is 566px.

Now, Isotope's masonry automatically fills in items from top to bottom in a vertical order, _no matter_ if there is 1500px left over in the horizontal row, or 1px. In this case, you have literally a 1px offset compared to the first two row in Chrome, so item #5 is first filling in that gap to complete the row, and then #6/7 start filling the next row.

This has sort of been an issue of contention, and there are a few issues on it. I don't know them offhand right now, but I might look for them in a bit. BUT, either way, for you, this is more of a cross-browser height-setting issue, which if you can figure out, should solve your problem. So, just do some research into how/why those browsers are coming up with different heights, and **bam**, problem solved! :)
