### ISSUE TITLE
Isotope filter doesnt works on child added later to the main item selecto

### ISSUE THREAD

**Issue by prashantsingh0205** [metafizzy/isotope#1180]
I am using isotope on a div with different filters and it works very well for me like this. But when I later add a child div to this div having id communitymembers, the isotope filter doesnt work for that child.

         $container = $('#communitymembers').isotope({
              itemSelector: '.item-select',
              filter: function() {
                    var $this = $(this);
                    var searchResult = commMemberKeywordSearchFilter ? $this.find('.memberName').text().match( commMemberKeywordSearchFilter ) : true;
                    var expertiseResult = $this.is(commMemberExpertiseFilter);
                    var distanceResult = commMemberDistanceFilter ? $this.find('.communityLocation').attr("data-com-loc") < parseInt(commMemberDistanceFilter) : true;
                    return searchResult && distanceResult && (expertiseResult || commMemberExpertiseFilter=='');
                }
            });
               $('.filtercheck').change( function() {
                var inclusives = [];

                $('.filtercheck').each( function( i, elem ) {   
                    if ( elem.checked ) {
                        inclusives.push(elem.value);                                                   
                    }                     
                });
                commMemberExpertiseFilter = inclusives.join(', ');
                $container.isotope();              
            }); 
            $('#distance-filter-community-member-list').on("change", function() {
                commMemberDistanceFilter = this.value;
                $container.isotope();            
            });

            $("#communityMemberListSearch").keyup(debounce(function(){                         
                commMemberKeywordSearchFilter = new RegExp( $("#communityMemberListSearch").val(), 'gi' );
                $container.isotope();
            } , 200));
Event though after appending I have called the isotope but it doesnt work.

$("#communitymembers").append(memberslist); 
$container.isotope();
Please help !!!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by prashantsingh0205** [comment]
Hi,

Thank you so much for replying. But I have got the solution to my problem
will soon post the solution. And further you can close the issue.

Thanks,

Prashant Singh

On Oct 18, 2016 7:15 PM, "David DeSandro" <notifications@github.com> wrote:

I'm sorry to see you're having trouble with Isotope. Could you provide
a *reduced
test case*? See Submitting Issues in the contributing guidelines
<https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metafizzy/isotope/issues/1180#issuecomment-254512123>,
or mute the thread
