### ISSUE TITLE
Sticky items

### ISSUE THREAD

**Issue by hatzipanis** [metafizzy/isotope#1181]
I'm not quite sure if this is possible but please refer to the test case. I'd like to ensure that some items are always stuck in their original order/position (in the test case position 1, 5 and 8) even after being sorted.

I've been working through different ideas for the last two hours or so but I'm not sure if this is something for `stamp` or whether there is an alternative. My challenge with `stamp` is that I'd still like the item to remain part of the grid so it assumes the correct positions and height/widths as ordinary items. Essentially I want sorted items to flow around these stuck items.

If I'm not quite explaining myself well enough I'll add sorting code.

**Test case:** http://codepen.io/hatzipanis/pen/yaQPkR

**Comment by desandro** [comment]
Sorry, but I don't think there's any easy way to do this.

You can modify `getSortData` to check for custom order

``` js
getSortData: {
  name: function( itemElem ) {
    var $item = $( itemElem );
    // return index of element if sticky
    if ( $item.is('.sticky') ) {
      return $item.index();
    }
    // else return name text
    return $item.find('.name').text();
  }
}
```

However, this will only work if the getSortData function is returning numbers that fit within the number of items — not for a different range or strings or other values.
