### ISSUE TITLE
Filtering LI-items inside .grid-item-content

### ISSUE THREAD

**Issue by buyavets** [metafizzy/isotope#1182]
Hello, dear Desandro.
I've got an issue.

I'm trying to get sort of 1 element of list instead of element of grid-item.

Shortly speaking, my query looks like this (in case of this CodePen http://codepen.io/buyavets/pen/GjzvPv):

We have .grid, .element-item and .grid-item-content-ffs.
In .grid-item-content-ffs we have h3 which represents Class Name, then UL and LI with last names of students.

I need to filter that silly Jerry Fischer.

The final result:

When i push the button to filter Jerry Fischer, i need to show 
.element-item and .grid-item-content-ffs and LI elements that have class "Jerry Fischer".

I know that's hard to understand, but please, i need help with sorting.

I didn't find any cases that could help me with my issue.

Best regards,
Ivan.

**Comment by desandro** [comment]
Use a [filter function](http://isotope.metafizzy.co/filtering.html#filter-functions) to check if the element has `.jerry-fischer`

``` html
<!-- remove dot -->
data-filter="jerry-fischer"
```

``` js
var filterFns = {
  // show if element contains .jerry-fischer
  'jerry-fischer': function() {
    return $(this).find('.jerry-fischer').length;
  }
};
```

See demo http://codepen.io/desandro/pen/7b56bd4dc5ccbab3254315e603e1d4fe/

**Comment by buyavets** [comment]
Thank you very much.
But what about to hide another students in class to show only Jerry Fischer in class instead?
