### ISSUE TITLE
Place non-filtered items to bottom rather than hiding

### ISSUE THREAD

**Issue by richgcook** [metafizzy/isotope#1183]
I'm curious... is it possible that when you filter, using isotope, it doesn't hide the non-filtered items but rather places them at the bottom? What do you think?

**Comment by desandro** [comment]
You could achieve this with sorting with a function and updating it with `updateSortData`. See demo http://codepen.io/desandro/pen/jMooLz/

**Comment by richgcook** [comment]
@desandro Thanks for the input and help! This definitely makes sense!
