### ISSUE TITLE
Isotope with Foundation for Sites 6 accordion

### ISSUE THREAD

**Issue by rafaelhc** [metafizzy/isotope#1185]
I am using isotope with a Foundation for Sites 6 accordion. The main issue is the height of the isotope container not responding to the toggle of an accordion item, therefore making the height of the page wrong.

I have seen previous answers, and tried to implement the following code:

`$('.isotope-container').on( 'click', '.accordion-title', function() {
  // trigger layout after item size changes
    $('.isotope-container').isotope('layout');
});`

This does change the height of the isotope container, but wrongly and randomly. Any ideas?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
