### ISSUE TITLE
Flickr's Justified Layout

### ISSUE THREAD

**Issue by maimairel** [metafizzy/isotope#1187]
Any chance to add Flickr's Justified Layout as an layout mode?

They have open sourced the algorithm and looks like it's not too hard to create a layout mode with it:
https://flickr.github.io/justified-layout/

Thank you!

**Comment by desandro** [comment]
Thanks for this feature request. I'll have to say no. The justified layout requires resizing of items, which Isotope stays away from.

**Comment by Tazintosh** [comment]
This is sad :(
