### ISSUE TITLE
Possible bug with Packery mode in Safari

### ISSUE THREAD

**Issue by dgobnto** [metafizzy/isotope#1188]
Hi,

I have been trying to fix the following issue in Safari but couldn't figure out what could be wrong. I'm using Packery mode and you can see a live version here: [http://www.empreitel.cv/ef-website/portefolio/](http://www.empreitel.cv/ef-website/portefolio/). What happens is, when clicking an item to toggle its dimensions, some neighbor items don't layout correctly and the newly dimensioned item overlaps them.

**Test case:** [http://codepen.io/koiastudio/pen/dOyXLX](http://codepen.io/koiastudio/pen/dOyXLX)

This only happens in Safari. Other browsers like Firefox or Chrome seem to be working fine.

Really appreciated if you could have a look.

Thanks in advance,
Diogo.

**Comment by desandro** [comment]
Thanks for reporting this issue. I tried the CodePen demo in Safari, but I wasn't able to reproduce the issue. I can see the bug occurring on your site however. If you can reproduce the issue in the CodePen, I can take a look.

**Comment by dioogbento** [comment]
I can still reproduce the issue in the CodePen, exactly as it is now… I'm on OS X Yosemite (10.10.5) and Safari 9.1.2. Try changing the grid's max-width to something like 1199 or 1201. For me, I can only reproduce the issue at 1200px (which is odd anyway)…

In the meanwhile, I've sort of quick fixed it in my website by changing the global max-width (haven't uploaded it yet). I suppose the issue has something to do with Safari's subpixel calculations. Although in the CodePen there shouldn't be any subpixel calculation, as there shouldn't be any rounding with a 1200px max-width, so I'm still confused!

Could you still take a look anyway? I would like to clearly understand what's going on and try to give it a stable fix.

Thank you for your attention,
Diogo.

**Comment by desandro** [comment]
I'm now able to reproduce the issue.

**Comment by dioogbento** [comment]
Thank you @desandro for taking a look at this. It also seems to me that it is a Safari bug.
