### ISSUE TITLE
buggy overflow: auto

### ISSUE THREAD

**Issue by leocadiomichael** [metafizzy/isotope#1190]
Hello!
Thank you a lot for this awesome plugin!

I have an issue on setting my grid's overflow..
I have many products and want to set a height for the products grid so I don't end up with a giant div.

**I try to set overflow to auto to have vertical scroll bars.**
Without Isotope that works normally (but of course I don't have filtering there)..
**However when using the plugin, seems like Isotope is conflicting with the overflow** (I must say filtering works perfectly without that styling on the grid).

Initially the scrollbars does not even show up, like Isotope had completely ignored the style.
When you change categories (filters) you can see the styling, but it's flickering and not usable at all.

This is the website: http://fundyrio.webflow.io/#Produtos
(Isotope code is near _</body>_)

Thanks in advance! 👍

EDIT:
When I set the grid's overflow to scroll, the bars show up, but the height is still ignored.

**Comment by leocadiomichael** [comment]
I forked your example on filtering and replicated my situation: http://codepen.io/LuckyScooby/pen/ObJrZw

I set layout mode to masonry, a small height (25px) just for testing and duplicated the elements just to populate it a bit more.
The same thing happens when overflow is set :(
Obs.: That flickering mentioned before is not happening here, I believe it's due to some CSS effects I've used on each product div, but it works without the overflow thing.

**Comment by desandro** [comment]
Thanks for reporting this issue. Can I ask why you are using `overflow: auto`?  If that's the issue, maybe we can find a solution that doesn't require `overflow: auto`.

**Comment by leocadiomichael** [comment]
Sure!
The products section has many items. When the website loads all items are shown resulting in a "forever" height.
Also, when we click the categories filters, that height is readjusted (of course).

I think it would be nice to have a fixed height for the products section while scrolling only the items grid in it instead of the page itself, so users can easily access the categories filters on the left and easily scroll up or down to other sections on the page. 
I'm trying to achieve that using `overflow: auto` or `overflow: scroll`. =]

**Comment by leocadiomichael** [comment]
@desandro I made it! 😃 
Instead of applying height and overflow to the grid div itself, I wrapped it in another div and applied to this wrapper.
```
<div class="wrapper" style="height: 222px; overflow: auto;">
    <div class="grid">
        <div class="item1">..</div>
        <div class="item2">..</div>
        ..
    </div>
</div>
```
👍

**Comment by desandro** [comment]
Nice work! Thanks for following up.
