### ISSUE TITLE
Stamping creating a hole in the layout

### ISSUE THREAD

**Issue by ierpe** [metafizzy/isotope#1191]
Hi, here is my short test case : http://codepen.io/ierpe/pen/jVWORV
In my test case when you click the shuffle, "holes" appear in the layout.

Basically what I'm trying to create here is to "fix" an element in the middle of the grid, that won't be moved by the shuffle. I found the stamp method might be what I'm looking for, and in fact it works, except that it create a hole in my grid above my element (and not below) : 

![screenshot](https://cloud.githubusercontent.com/assets/790992/20176356/b5f3f782-a747-11e6-86e6-df89447f794f.png)

In this screenshot the orange button is my shuffle button. You can see that after applying the stamp on it, all the items above it are moved "out" of its column. 

Is this a normal behavior? Is there another method? Or do you think something is wrong with my css? Everything's working fine before I apply the stamp on my middle element.
Any help greatly appreciated!

**Comment by desandro** [comment]
> Is this a normal behavior?

Yes, with Masonry stamps, items move below the stamps.

> Is there another method?

Yes, with [Packery stamps](http://packery.metafizzy.co/options.html#stamp), items move all around the stamps, above and below. Try the [packery layout mode](http://isotope.metafizzy.co/layout-modes/packery.html).

**Comment by ierpe** [comment]
Thanks, works great! 
Maybe you could write something on your site on the Stamp method documentation ;-)
