### ISSUE TITLE
Inclusive and Exclusive filters - view all

### ISSUE THREAD

**Issue by Cobbalobb** [metafizzy/isotope#1192]
Hi,

I'm basically using: http://codepen.io/desandro/pen/MebyMR

I want to be able to add a 'Show all' button to each checkbox group. I've tried making this button clear the filtergroup array, but that didn't work. I also tried clearing the array and then adding '*', but no luck with that either. How can I achieve this?

Thanks for any help,
James

**Comment by desandro** [comment]
What would the show all button do? If you select show all on brands, does that mean you want to show '.brand1, .brand2, .brand3, .brand4' ?

**Comment by Cobbalobb** [comment]
Yeah, exactly that. Basic it would reset the brand filter so all brands
show, like when the page loads initially.

On 12 Nov 2016 3:18 p.m., "David DeSandro" <notifications@github.com> wrote:

What would the show all button do? If you select show all on brands, does
that mean you want to show '.brand1, .brand2, .brand3, .brand4' ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metafizzy/isotope/issues/1192#issuecomment-260127820>,
or mute the thread

**Comment by desandro** [comment]
See demo http://codepen.io/desandro/pen/21c4295472938164326fe600e7d706cb/

The label behavior is buggy, but otherwise it works.

**Comment by Cobbalobb** [comment]
Hi, 

Thanks for that. It's almost what I want, but I guess what i'm looking for is more a 'Clear Selection' button. Where it unticks all options, and therefore goes back to showing everything.

Basically I'm trying to get something like the following to work:
`$grid.isotope({ filter: '*' })`

I tried doing:
`filterGroup = ["*"];`
But it didn't work.

Any way to get that to work?

**Comment by desandro** [comment]
I'll have to leave the rest to you. Sorry, but I won't be able to personally develop the solution for you.
