### ISSUE TITLE
Common js, wrong require path

### ISSUE THREAD

**Issue by bampnet** [metafizzy/isotope#1194]
Hi,
there's a wrong path on line 21 of js/layout-modes/masonry.js.

`require('masonry-layout') `
must be 
`require('masonry')`

Mattia

**Comment by desandro** [comment]
Thanks for raising this issue. If you are using Common JS, then there is a strong likelihood that you are using Browserify, and have installed Isotope and Masonry with npm. That's why it requires `masonry-layout` and not `masonry`.
