### ISSUE TITLE
How to check element has already initialized

### ISSUE THREAD

**Issue by mayank597** [metafizzy/isotope#1196]
i find a solution to check isotope initialized or not. below is my code

         if ($(".div-class").hasClass('isotope')) {
            // some other code
         }

but it is not working. i have find about it that isotope is not adding class at the time of initailization.
so how check isotope initialized

**Comment by desandro** [comment]
You can check with jQuery with $().data('isotope')

``` js
// get Isotope instance 
var iso = $('.grid').data('isotope')
if ( iso ) {
  // isotope initialized
}
```

**Comment by mayank597** [comment]
Tahnkyou

**Comment by mayank597** [comment]
Thank you. it is working for me.

**Comment by ishfaqmch** [comment]
Worked for me as well. Thanks.

**Comment by wpexplorer** [comment]
Anyone know how to do this with Vanilla js?

**Comment by thesublimeobject** [comment]
@wpexplorer — You can get the data for the active instance in the same way as described above without using jQuery by [using the method in the documentation here](https://isotope.metafizzy.co/methods.html#isotope-data).

**Comment by wpexplorer** [comment]
@thesublimeobject - thanks! Totally missed that, looked at the docs like 1000x.
