### ISSUE TITLE
How can i show all items after filtering? 

### ISSUE THREAD

**Issue by tazcabe** [metafizzy/isotope#1197]
**Test case:** http://codepen.io/desandro/pen/mEinp

Hello I am using isotope v3.0.1 and i need show all items after apply filtering, right now after to apply filtering Isotope adds a css property to elements that do not match my filter: "display: none", however i will like show all elements maybe only add opacity to elements that do not  match with my filter. 

Can you help me?

**Comment by desandro** [comment]
If you do not want to hide elements, but change their opacity, you don't need to use Isotope. You can do this with your own jQuery code. 

``` js
var $items = $('.grid-item');
$items.filter( selector ).css({ opacity: 1 });
$items.not( selector ).css({ opacity: 0 });
```
