### ISSUE TITLE
hideItemElements / revealItemElements - issue

### ISSUE THREAD

**Issue by flythird** [metafizzy/isotope#1199]
hello ! 

isotope is a very good tool and i use it since the first versions.

i use hideItemElements and revealItemElements so that to spend the less of time to display my items.
sorry for my english, i'm french....

i apply different filter sessions and my cache collection is finally...full of my items.
so i have just to hide or show the filtered items and that's why i use these two functionalities.

my problem : **i have holes in display** the layout method does'nt re-arrange ( just after a filter scenario )
**if i resize the browser window**, the visible items go up **but the item container lose the mansory layout**

what kind of  method can i use dynamically to force the layout to re-arrange my items and to see the mansory layout play ?

Is there somebody with the same issue ? did you solve it ?

thank you for your attention, have a nice day, 
alien,  from south of france

**Comment by englishextra** [comment]
Perhaps, it's about  .layout() that is called with progress event of imagesloaded.

(See the test repo/demo here)[https://github.com/englishextra/masonry-packery-isotope-demo]

There I gather experience with masonry/packery/isotope libs

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by citizentim** [comment]
I'm having the same issue with Isotope.  hideItemElements() succeeds in removing filtered elements from the view, but the items remain in-place, with large holes in the layout.  A call to layout() appears to have no effect.

I will work on creating a reduced test case tomorrow.
