### ISSUE TITLE
Isotop overlaps when resizing browser from full width to small( around 420px) width

### ISSUE THREAD

**Issue by vishy93** [metafizzy/isotope#1201]
Hi Guys,

I have a strange issue: I am using isotope in my bootstrap based theme. Now, it works fantastic for all other sizes. But, when I go from either md view or even lg down to xs view via browser resize the isotope items are overlapping. Only in this situtation it happens. Going from and between any other sizes works well. On normal page load works well across all sizes. 

Now, I am aware unloaded images can throw off Isotope layouts and cause item elements to overlap. But, on browser resize the images will already be loaded. Nonetheless, I tried:

`$container.imagesLoaded().progress( function() {
  $container.isotope('layout');`

Resulting in the error:

Uncaught TypeError: $container.imagesLoaded is not a function

**Comment by desandro** [comment]
You may need to install imagesLoaded on your site. It is not included in Isotope.

**Comment by vishy93** [comment]
Sorry about the delayed response. Was away for festive holidays. Nonetheless, would imagesLoaded be a free additional plugin ?

**Comment by vishy93** [comment]
Sorry about the late reply. I loaded imagesLoaded and followed the code example on your site for overlapping images fix. But, it did not do the trick. 

This is my current code for isotope isolation:
` var $container = $('.grid-items');
        $container.isotope({
            filter: '*',
			percentPosition: true,
            animationOptions: {
                duration: 350,
                easing: 'linear',
                queue: false
            }
        });
        
        $('.cat a').click(function() {
            $('.cat .active').removeClass('active');
            $(this).addClass('active');
            var selector = $(this).attr('data-filter');
			$("#TechFilter").val(selector);
            $container.isotope({
                filter: selector,
                animationOptions: {
                    duration: 350,
                    easing: 'linear',
                    queue: false
                }
            });
            return false;
        });`

Weirdly, the overlapping only occurs when I resize from either md view or even lg down to xs view. In bootstrap terms. When I refresh or resize again there is no overlapping.

**Comment by desandro** [comment]
Sorry, but I will not be able to provide support for this issue.
