### ISSUE TITLE
is there _masonryResizeChanged equivalent for isotope?

### ISSUE THREAD

**Issue by danyj** [metafizzy/isotope#1203]
I am trying to resize items before the layout same as this 
http://stackoverflow.com/questions/16350111/isotope-resize-elements-before-relayout

I have tried this 

			Isotope.prototype.getSize = function() {
				
				console.log('now');
				
			  	this.size = getSize( this.element );
			};

but seems to me it ruins after the resize or ?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by danyj** [comment]
not sure what test case can do here I am just asking what isotope method is best to use to set items width in px on load and resize ,  now I am using this 



			var self = this;
			self.ThzMasnorySizeItems();
			Isotope.prototype.onresize   = function() {
				self.ThzMasnorySizeItems($(this.element));
				this.resize();
			};

            self.grid.isotope({
                itemSelector: '.thz-grid-item',
                layoutMode: 'packery',
                transitionDuration: '0.4s',
                masonry: {
                    columnWidth: '.thz-items-sizer',
					gutterWidth: 0,
                },
                packery: {
                    gutter: 0
                },

                hiddenStyle: {
                    opacity: 0
                },
                visibleStyle: {
                    opacity: 1
                }
            });



I am asking for the best method to use to change items width before all transitions and positions fire.

**Comment by danyj** [comment]
cant use columnWidth only since there are multiple layouts like metro and grid, 
and have found out that 1px bug is due to rounding as you advised , fixed it on several browsers than IE did not want to play along, 

only way to get all browsers to work properly and fix the 1px bug is 

disable percentposition , 

find container width , divide by number of columns and set items width in px not percentage , 

all this works now but I need the perfect timing to fire the setsizes method, 

this is why I did not setup any testcase

**Comment by desandro** [comment]
I'm trying to figure out why you need to use this technique in the first place. I may be able to offer a better solution than the one you proposed.

**Comment by danyj** [comment]
ok , thnx , fw min will post what I have

**Comment by danyj** [comment]
OK bud here is the  demo   of the layout I have and the method I made , 
https://jsfiddle.net/Themezly/xsmxoas0/1/

note that I have to follow this layout so in my case all the css fixing of 1px issues does not apply since we are using a pseudo for backgrounds and the grid is as you see it there. 


if you disable the isotope in the demo you will see that grid is perfectly sized with the gap , 


in the demo if you remove packery , you will see the bug again , 
if you use only your version of isotope without my extra size method again there is the bug 

please note that I just copied pasted the methods from our plugin , did not clean up anything 



the current thing I have works for me but the issue is that I have to call the item sizing method on load, resize , new items append and it kinda does not sit well with me

**Comment by danyj** [comment]
what I would love to do is execute resize before isotope calculates the item next position

**Comment by danyj** [comment]
@desandro any suggestions ?

**Comment by desandro** [comment]
All the item sizing should be done in CSS with media queries. You don't need any of it in JavaScript. See demo http://codepen.io/desandro/pen/a30d13a9f0d270c300fdb0b6bd8501c8
