### ISSUE TITLE
_bindArrangeComplete isn't yet considering item transitions

### ISSUE THREAD

**Issue by JackDandy** [metafizzy/isotope#1205]
Hi,

Can't edit the library in the pen, so, using ... https://unpkg.com/isotope-layout@3.0.1/dist/isotope.pkgd.js

at L#1167 before, `emitEvent( 'transitionEnd'` i insert  
`console.log('fire transitionEnd');`

and at L#3119 before, `dispatchEvent( 'arrangeComplete'` i insert   
`console.log('fire arrangeComplete');`

Using masonry, I observe **`fire arrangeComplete`** _**before**_ **`fire transitionEnd`** in any console. 
It looks as though `_bindArrangeComplete()` isn't yet considering the completion of items[] transitions?

The effect shows when trying to chain two sorts using the event completion to determine when to fire the second. Transition 1 doesn't end before the transition 2 begins, therefore the render will leave one or two items non visible because they are positionally overlapped by others in the modified CSS.

I am failing like so...
```
$('#isotope').one('arrangecomplete', function(){
	$('#isotope').isotope({sortBy: sortCriteria});  // transition 2, 18 divs in #isotope
	// would like to do more work here when transition 2 is complete
})
$('#isotope').isotope({sortBy: 'random'});  // transition 1, 18 divs in #isotope
```
[edit] TL;DR A simple test of the above is to try and chain two 'random' renders

for now I'll `.isotope('layout')` to correct the placements, but any ideas ?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by JackDandy** [comment]
nevermind, i did a workaround and it works fine with that.
