### ISSUE TITLE
Problems image first boot

### ISSUE THREAD

**Issue by Fezas** [metafizzy/isotope#1207]
Greetings!
I've got a problem: the image when the page first loads imposed and move out.
jquery.isotope.js builds a page of those pictures which had to boot in 1 second? Accordingly, then they are in the cache, and everything is built properly?
I apologize for the English.
Help.
Isotope v1.5.25

**Comment by desandro** [comment]
See http://isotope.metafizzy.co/faq.html#how-do-i-fix-overlapping-item-elements
