### ISSUE TITLE
Isotope load more button 

### ISSUE THREAD

**Issue by laura2489** [metafizzy/isotope#1208]
Hello. can you please help me with this isotope issue? http://stackoverflow.com/questions/41507244/isotope-pagination-with-load-more

I managed to create a load more button with isotope, but the layout doesn't work properly . Thank you

**Comment by thesublimeobject** [comment]
Hey @laura2489, I am going to try to remember to respond to this tomorrow. I have an extremely well-tested set of functions for exactly this that I wrote for our web shop. I'll share try my best to share it tomorrow.
