### ISSUE TITLE
Random Layout working with Filters

### ISSUE THREAD

**Issue by rae0724** [metafizzy/isotope#1209]
Hi, I am wondering whether filter will work in the layout as link below.
http://codepen.io/rae0724/pen/oBYLyq

What if when I click the filter, the layout will auto rearrange to become exactly like this, but will not run away...
I studied in the docs, but seems there is no way to filter on this kind of layout?

**Comment by desandro** [comment]
Sorry, Isotope does not support this kind of staggered layout.
