### ISSUE TITLE
Filtering by multiple values in single data attribute

### ISSUE THREAD

**Issue by shainanigans** [metafizzy/isotope#1210]
Hey there,

I'm working on a project where we are filtering stores by category. Some stores appear in multiple categories, so the data-attribute contains multiple values. I would prefer to use a data attribute rather than a class for filtering, as it's cleaner and more semantic (especially since we identify our categories with unique 16-character strings). I'm also using a data-attribute for another filter, so it makes sense to me to keep my filtering method consistent.

Here's my test case (there are multiple filters working in conjunction on my project so I've set up my test case as if there are multiple filters): http://codepen.io/shainanigans-1472169587/pen/PWWQJW

You'll see that all the categories go into the same data-attribute: "data-category." If a user filters by the categories in the same order that they appear in the attribute, the filtering works. However, if a user filters in a different order, the filtering does not work because data-attributes do not work like classes.

For example: Clicking on "men's fashion" and then "women's fashion" should show Zara, Gap, and Myer. Instead, it only shows Gap and Myer because the order of the attribute values for Zara doesn't match what jQuery is comparing it to. There is no way that I know of to find individual values inside a single data-attribute.

So is there a way to use data-attributes like this, or am I stuck using classes?

**Comment by desandro** [comment]
The issue is that class selectors do not have order `.red.small` is the same as `.small.red`. When you are using an attribute, you are selecting based on more of a string match. `attr="red small"` is different from `attr="small red"`.  They are different values.

My solution is iterate through the filters and check that the element has each. See demo http://codepen.io/desandro/pen/a807b00bb785cea30160aaa7c8e458ac/

``` js
  filter: function() {
    var length = categoryFilters.length;
    if ( !length ) {
      return true;
    }
    var $this = $(this);
    // check if all category filter match
    for ( var i=0; i<length; i++ ) {
      var catFilter = categoryFilters[i];
      if ( !$this.is('[data-category*=' + catFilter + ']') ) {
        return false;
      }
    }
    // otherwise match
    return true;
  }
```

Alternatively, you could check if at least one matches

``` js
  filter: function() {
    var length = categoryFilters.length;
    if ( !length ) {
      return true;
    }
    var $this = $(this);
    // check if one category filter matches
    for ( var i=0; i<length; i++ ) {
      var catFilter = categoryFilters[i];
      if ( $this.is('[data-category*=' + catFilter + ']') ) {
        return true;
      }
    }
    // otherwise no match
    return false;
  }
```

**Comment by shainanigans** [comment]
Thanks, @desandro. This did the trick.

**Comment by shainanigans** [comment]
Hi @desandro, I thought I had this going but turns out it's not quite there.

I've added the other filtering that I'm using and now the categories are returning only the last item clicked. I've put this into a new pen [here](http://codepen.io/shainanigans-1472169587/pen/RKEjzz).

**Comment by desandro** [comment]
Sorry, but I won't be able to personally work on a solution here.

**Comment by shainanigans** [comment]
Leaving [this solution](http://codepen.io/shainanigans-1472169587/pen/vgMKee) here for anyone who may need it.

**Comment by betodasilva** [comment]
Hey guys, 
first of all, thanks @desandro for this solution!!

In my case, I have multiple properties set inside getSortData, wich one use this function to filter by category. 

However, I though it would be enough just to use sortBy: 'filter', when need to call this function, but it doesn't work. 

Could you help me with this one? 

Here's the [codepen](https://codepen.io/betodasilva/pen/LzZGEM) example.
