### ISSUE TITLE
Append elements while grid is hidden makes them jump

### ISSUE THREAD

**Issue by scal-m** [metafizzy/isotope#1211]
**Use case**
New item is added to a grid located in an inactive tab (hidden). 
```.isotope('layout')``` works as expected when tab content is displayed.
When elements are resized/relayed out, they get properly placed at first but then jump before retrieving their fine spot again.
*Behaviour simulated in test case.*

**Notes**
I understand that by design, laying elements in a hidden grid isn't supposed to work. 
Surprisingly enough, ```.isotope('layout')``` perfectly deals with reseting the grid once it's displayed again. 

**Current workaround**
Destroying Isotope before adding a new element. Re-init it afterward. Would it be a better way to deal with such a use case?

**Test case:** http://codepen.io/pascal-mercier/pen/ggRBrE

**Comment by desandro** [comment]
Thanks for detailing this problem. As you mention, changing things in a hidden grid is not what Isotope was designed for. I'll leave this issue open in case others are running into it
