### ISSUE TITLE
Incorrect calculation cell with float percent width

### ISSUE THREAD

**Issue by BulatSa** [metafizzy/isotope#1214]
Hello, cell with width: 25% ok, but width: 33.33333% have some troubles with first column: 
http://codepen.io/BulatSa/pen/OWQJoe

width of cell is 318.78px, but left is 318px

**Comment by BulatSa** [comment]
I think the problem is solved, if the correct function
```
proto.setPosition = function( x, y ) {
  this.position.x = x;
  this.position.y = parseInt( y, 10 );
};
```
After this, columns look good, but i don't know, maybe it's not bulletproof solution

**Comment by thesublimeobject** [comment]
Try using `percentPosition: true`: http://isotope.metafizzy.co/options.html#percentposition
