### ISSUE TITLE
Isotope, once items changed - got a visual shake 

### ISSUE THREAD

**Issue by 01Kuzma** [metafizzy/isotope#1216]
As I have made a mistake in [previous ](https://github.com/metafizzy/isotope/issues/1215)issue description - it was closed. So, it's refined:
I've a weird issue with displayed items:
once I change the filter selections or resize window the items got a shake. They disappear for a moment and appear with a motion.
I tried experimenting with different options, but it was useless for me...
Don't know is it a bug or some kind of CSS issue. Asking for help
Here is a link to a temporary technical demo: removed
I use Twitter Bootstrap 3 
The library is v3.0.2

Config:
```
$(document).ready(function() {    
var container = $('.isotope'),
		  sortIsotope = function(){
			container.isotope({
                animationOptions: {
                   animationEngine: 'best-available',
                   duration: 750,
                   easing: 'linear',
                   queue: false
                },                
                layoutMode: 'fitRows',
				itemSelector: '.item',		
				masonry: {
				  columnWidth: '.col-md-3'
				},				
				transitionDuration: '2s',
				getSortData: {                    
				  name: '.name',
				  symbol: '.symbol',
				  number: '.number parseInt',
				  category: '[data-category]',
				  weight: function( itemElem ) {
					var weight = $( itemElem ).find('.weight').text();
					return parseFloat( weight.replace( /[\(\)]/g, '') );
				  }
				}
			  });
			};

	  // change is-checked class on buttons
	  $('.button-group').each( function( i, buttonGroup ) {
		var $buttonGroup = $( buttonGroup );
		$buttonGroup.on( 'click', 'button', function() {
		  $buttonGroup.find('.is-checked').removeClass('is-checked');
		  $( this ).addClass('is-checked');
		});
	  });
	  
	  var filterFns = {
		// show if number is greater than 50
		numberGreaterThan50: function() {
		  var number = $(this).find('.number').text();
		  return parseInt( number, 10 ) > 50;
		},
		// show if name ends with -ium
		ium: function() {
		  var name = $(this).find('.name').text();
		  return name.match( /ium$/ );
		}
	  };
	  // bind filter button click
	  $('#filters').on( 'click', 'button', function() {
		var filterValue = $( this ).attr('data-filter');
		// use filterFn if matches value
		filterValue = filterFns[ filterValue ] || filterValue;
		container.isotope({ filter: filterValue });
	  });
	  // change is-checked class on buttons
	  $('.button-group').each( function( i, buttonGroup ) {
		var $buttonGroup = $( buttonGroup );
		$buttonGroup.on( 'click', 'button', function() {
		  $buttonGroup.find('.is-checked').removeClass('is-checked');
		  $( this ).addClass('is-checked');
		});
	  });		  		  
		$('#works .container-fluid').imagesLoaded( function() {
		sortIsotope();
		$(window).on('debouncedresize', sortIsotope);
	});		
});
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? I appreciate you providing a live link, but your live production site is too complex to look into. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by 01Kuzma** [comment]
Hi!
Thank you for reply!
I hope this will be OK?
http://codepen.io/anon/pen/WRyyKp

**Comment by thesublimeobject** [comment]
@01Kuzma This is the easiest bug, and I still make it sometimes, forgetting it's implications. Never, ever put `transition: all` on an Isotope instance. It will mess with it's internal transition/animation state and cause it to shake or re-render, etc. If you have a specific transition you need to set on some other CSS prop on the item, set it specifically; i.e., `transition: border ...`. In the pen if you just remove the transition property on the item you'll completely fix the issue. 

Hope this makes sense! : )

**Comment by 01Kuzma** [comment]
@thesublimeobject, thank you for you answer! Long time ago I've copied this example from official docs(as I remember clear). But there aren't `transitions: all` properties. This CSS code was copied:
`.isotope,
.isotope .item {
  -webkit-transition-duration: 0.8s;
     -moz-transition-duration: 0.8s;
      -ms-transition-duration: 0.8s;
       -o-transition-duration: 0.8s;
          transition-duration: 0.8s;        
}

.isotope {
  -webkit-transition-property: height, width;
     -moz-transition-property: height, width;
      -ms-transition-property: height, width;
       -o-transition-property: height, width;
          transition-property: height, width;
}

.isotope .item {
  -webkit-transition-property: -webkit-transform, opacity;
     -moz-transition-property:    -moz-transform, opacity;
      -ms-transition-property:     -ms-transform, opacity;
       -o-transition-property:      -o-transform, opacity;
          transition-property:         transform, opacity;
}


/**** disabling Isotope CSS3 transitions ****/

.isotope.no-transition,
.isotope.no-transition .isotope-item,
.isotope .isotope-item.no-transition {
  -webkit-transition-duration: 0s;
     -moz-transition-duration: 0s;
      -ms-transition-duration: 0s;
       -o-transition-duration: 0s;
          transition-duration: 0s;
}`


Or I'm wrong?

**Comment by thesublimeobject** [comment]
@01Kuzma Eh, if you say you copied it from somewhere, I'm sure you did. Not sure what the difference is...perhaps an older version of the docs? Also, you're correct, I didn't look that hard at your code once I saw what the issue was. Even though you aren't applying the transition to all, you are applying it to both opacity and transform, which are both properties that isotope uses. If you want to change the duration or type, make that change in the options: http://isotope.metafizzy.co/options.html#transitions

**Comment by 01Kuzma** [comment]
hm... maybe @desandro will shed a light on those transitions from an old example

**Comment by desandro** [comment]
Looks like you were using [Isotope v1 CSS](http://isotope.metafizzy.co/v1/docs/introduction.html). This CSS should be removed with using Isotope v2+

**Comment by 01Kuzma** [comment]
@desandro I've completely removed CSS on production and it seems that everything is working now. So v3 doesn't use at all any external CSS?

**Comment by desandro** [comment]
That is correct. v3 only requires the Isotope .js file. Closing this as fixed!

[FYI, there's this about transitions in the FAQ](http://isotope.metafizzy.co/faq.html#items-jump-after-transitioning-position)

**Comment by 01Kuzma** [comment]
Good! Thank you!
