### ISSUE TITLE
layout issue after flickity init

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/isotope#1218]
hey there.

recently had an issue with the masonry layout when using flickity in the page. the issue is when flickity is initialized the layout won't be updated. here's the codepen demo. you maybe need to refresh a couple of times to see the issue

http://codepen.io/Mohsen-Khakbiz/pen/WRayrm

also made a video if you couldn't see the issue http://take.ms/fmi7t

maybe one one solution is to fire flickity before calling isotope. but unfortunately this won't work in my case.

any help will be really appreciated
Regards

**Comment by thesublimeobject** [comment]
@Mohsen-Khakbiz Adding a call to layout after flickity initializes seems to be the easiest fix for this; worked for me on multiple refreshes:

```
flickityContainer.imagesLoaded(function() {
        var flkty = flickityContainer.flickity();
        flkty.on('settle.flickity', function() {
		flkty.closest('.row').isotope('layout')
	})
		
        // RE-LAYOUT ISOTOPE HERE
	isotopeContainer.isotope('layout')
})
```

That said, an issue you might run into is that you are attaching imagedloaded() to both of the libraries, which means one instance could be done before the other depending on certain variables (images, mainly). Re-triggering isotope here won't do anything worse than potentially re-snapping tiles into position that were already there anyway, but I thought it's something that I would at least mention. There are ways you could avoid this, but I'm not sure it's worth delving into here.

**Comment by Mohsen-Khakbiz** [comment]
@thesublimeobject thanks for the help.
your suggestions actually solved some of my other issues as well
