### ISSUE TITLE
Request for progress label of sorting/filtering

### ISSUE THREAD

**Issue by carletto0282** [metafizzy/isotope#1219]
HI there,

I'm setting up a sort for a big number of items (+500).

Actually the process is taking about 15secs so I'm hiding the container while the sort is taking place and once done - through arrangeComplete - showing the container back.

I'd like to ask if is there a way to show the progress of sorting something like.
Thanks

Carlo

**Comment by desandro** [comment]
Hi! Thanks for submitting this issue. Isotope works best with <100 items. More than that, browser performance will worsen. Isotope may not be the best solution for such a big collection. Sorry, but I won't be able to resolve this one.
