### ISSUE TITLE
Status of #873

### ISSUE THREAD

**Issue by jimmyadaro** [metafizzy/isotope#1220]
Sorry if this is not the right place, but I didn't know where else ask about this, because in Desandro's website (contact section) says:

> Please use GitHub issues for support for Masonry, Isotope, Flickity, or my other projects.

I want to know the development status of [#873](https://github.com/desandro/masonry/issues/873) and how it will be included in Isotope - Sure I'm not the only one.

Thanks.

**Comment by desandro** [comment]
> I have been working on this feature. I have no current ETA. I'll follow up once a release is ready.

Same status. This feature will be included in Isotope when its released in Masonry.
