### ISSUE TITLE
Just show the first item on load, not all

### ISSUE THREAD

**Issue by FerkoHH** [metafizzy/isotope#1222]
Heya,

I've read the web up and down nothing helped. 
Actually my Isotope Filter is showing all Items when the page is loaded. 
I want just to show the first Item from my list instead of all. 

Dont know what I'm doing wrong, already tried many things.
See Codepen Link: 
http://codepen.io/anon/pen/OWGjBJ

Thank you very much

**Comment by desandro** [comment]
Easiest solution is to add a class to the first item like `.first`, then filter for this class when initializing isotope

``` js
$grid.isotope({
  filter: '.first'
})
```

See demo http://codepen.io/desandro/pen/c583ce785b55f29566c6b926b3c0d950/
