### ISSUE TITLE
Columns shifting position, 1px height mismatch

### ISSUE THREAD

**Issue by jimmyadaro** [metafizzy/isotope#1223]
Hi there. I have some items of the same size with only one which is bigger. Isotope works as expected, but when the screen is resized some columns are shifting position.

[**MCVE**](http://stackoverflow.com/help/mcve): http://codepen.io/anon/pen/mRgGVG

**How to replicate the error:** just resize the window, and you will see some columns under the biggest item are shifting position.

This issue isn't happening if you remove the "big" class to the first item.

Is there any way to solve this?

**Comment by desandro** [comment]
Thanks for submitting this issue. This is a known issue. It caused by JS measuring the height of the 2-row-tall item to be different than the height of 2 1-row-tall items. One solution could be desandro/masonry#873

**Comment by jimmyadaro** [comment]
@desandro Thank you sir for your response.
I guess there's no temporal hack for this cause?

**Comment by desandro** [comment]
Sorry, I don't have a good fix.

**Comment by desandro** [comment]
[Isotope v3.0.4 now has support for horizontalOrder](https://isotope.metafizzy.co/layout-modes/masonry.html#horizontalorder)
