### ISSUE TITLE
[Question] large data set with virtualization ?

### ISSUE THREAD

**Issue by MarcMagnin** [metafizzy/isotope#1224]
Hi,

I was wondering if that could be possible to integrate Isotope with some virtualization such as:
https://bvaughn.github.io/react-virtualized/#/components/Collection

The idea would be to present a lot of items (let say 500K+ images to represent) and been able to virtualize them (nothing is rendered outside of the view, DOM is empty) and add the nice and smooth filtering animations of your library.
In this previous component you can easily scroll on a million items list. The big drawback is that is misses the wonderful animations that you provide on appear/disappear of items on filter.
The advantages of such component is that you can scroll if you like across a giant collection without any other manual server side request (except for getting the inner data of the items such as downloading the image on demand) but you are still able to search/filter with a very smooth UX and provides nice animations (as everything is virtually there, in place).

I had a reply form the react-virtualized component dev: "You might be able to implement this by providing our own (stateful) cellRangeRenderer (https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#cellrangerenderer). Grid would manage windowing for you but you'll have to manage the transitions. 
If you do do something like that- I'd love to see it. Perhaps we could make a reusable component out of it." : http://stackoverflow.com/questions/42296231/how-to-show-a-large-data-set-with-animated-filtering

If you have any ideas, that would be absolutely awesome as such component as never be done before.
Many thanks!

**Comment by desandro** [comment]
Hi! Thanks for your interest in Isotope. To be honest, I do not have any familiarity with React. I'm sorry to say that Isotope is not well suited for this use case. Isotope was designed to handle 100 items, for the DOM. Combining Isotope with frameworks like React can be done, but I can speak to its quality. I feel like they must compete with one another, as both manipulate the DOM, and Isotope wasn't designed to be integrated directly into a framework like React.

From my experience, Isotope isn't the right solution. It has filtering, sorting, and transition behavior. But you're likely better off developing a custom solution than jerry-rigging Isotope to fit in.

**Comment by MarcMagnin** [comment]
Thanks for that clear answer.
Thumbs up for your library!
