### ISSUE TITLE
Safari isotope performance problem

### ISSUE THREAD

**Issue by Helge85** [metafizzy/isotope#1225]
Hi first of all, thanks for your amazing plugin!
I'm facing an issue which has been quite unknown to me.

In my example http://studio-a-h.de/kirby-test/projects/morning-has-not-dawned-yet you see an imageslider.

**If you click on "Index"** an overlay with the image index is about to be displayed. In chrome and Firefox everything is fine, but Safari shows the overlay with a delay of appr. 500ms and it seems that there is an extra delay, even when the div is already visible.

Are there any known bugs with Safari and isotope? In my research i hardly found something, beside the repaint bug.

Would be great if someone has an idea.
I already checked everything else. It is not a CSS problem.

With just 4 images, the overlay displays perfectly.

Best regards

**Comment by thesublimeobject** [comment]
@Helge85 Interesting. Mind posting some code I can take a look at? I'm not personally aware of anything that would cause this to happen off the top of my head, but I might be able to help!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
