### ISSUE TITLE
Filtering - Initial filter URL doesn't sort properly, but clicking between categories does

### ISSUE THREAD

**Issue by khoallaby** [metafizzy/isotope#1226]
When visiting a specific category (in my case, multi-family) via the URL, isotope doesn't properly sort them. But when i click on another category, and back to the problematic one, isotope reorders it just fine.

When i run $grid.isotope('layout') manually, it'll reorder it back the "wrong" way. 

I believe isotope actually is doing it's job correctly though. If you look at the 'data-order' attributes, the numbers are numerically ordered correctly, when the layout is "wrong". But i would like it to "fill the gaps" like it does when i switch between categories.

test case @
http://s.codepen.io/khoallaby/debug/aJbKbO/yYryLDBjmKPM#filter=.multi-family

pen @ 
http://codepen.io/khoallaby/pen/aJbKbO

**Comment by desandro** [comment]
Thanks for reporting this issue. Would you mind removing the images from the demo? They're returning 401 unauthorized. Not sure if that's the problem or not.

**Comment by khoallaby** [comment]
Hey David, thanks a lot for quick reply. Sorry about that, forgot these were behind an http auth site.. i replaced them with placeholder images for now.

**Comment by khoallaby** [comment]
Got it figured out. I think maybe it was calculating .col-md-4 incorrectly for the columnWidth. I ended up manually calculating it from the grid container's width.

masonry: { columnWidth: '.col-md-4' }

Needs to be 

masonry: { columnWidth: $grid.width() / 3 }
