### ISSUE TITLE
Using lazy load with isotope

### ISSUE THREAD

**Issue by vishy93** [metafizzy/isotope#1227]
I am using the code below to lazy load my images:

```js
window.onload = function() {
    for (var c = document.getElementsByTagName("img"), d = 0; d < c.length; d++) {
        c[d].getAttribute("data-src") && (c[d].setAttribute("src", c[d].getAttribute("data-src")), c[d].removeAttribute("data-src"))
    };
    if (d == 10) {
        $(".appren-items").isotope('layout')
    }
};
```

Now, load.gif is a very small size image, causing overlap for the isotope images, when my bigger images get swapped in. As seen in the code I have tried to call the layout method when the loop has reiterated 10 ten times, to cover all the isotope images  being loaded. But, still they overlap and if I normal refresh it works fine or if I resize window it will relayout fine. Only when I hard refresh the overlap occurs. How can I incorporate my lazyload code to cover isotope images ?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by vishy93** [comment]
Sorry of course, [http://codepen.io/vishpatel93/pen/JWYKwr/](url)

**Comment by vishy93** [comment]
I have got it to work by moving the initialisation code into my downloadJsatonload here:

`function downloadJSAtOnload() {
    var element = document.createElement("script");
    element.src = "<?php get_theme_url();?>/js/contact_me.js";
    document.body.appendChild(element);
    $(window).load(function() {
        $("body").removeClass("preload");
        var e = $(".appren-items");
        e.isotope({
            filter: "*",
            layoutMode: 'fitRows',
            percentPosition: !0,
            animationOptions: {
                duration: 150,
                easing: "linear",
                queue: !1
            }
        }), $(".cat2 a").click(function() {
            $(".cat2 .active").removeClass("active"), $(this).addClass("active");
            var n = $(this).attr("data-filter");
            return $("#apprenFilter").val(n), e.isotope({
                filter: n,
                animationOptions: {
                    duration: 150,
                    easing: "linear",
                    queue: !1
                }
            }), !1
        }), $("#apprenFilter").on("change", function() {
            var n = this.value;
            $(".cat2 .active").removeClass("active"), $(".cat2 .type li a[data-filter='" + this.value + "']").addClass("active"), e.isotope({
                filter: n,
                animationOptions: {
                    duration: 350,
                    easing: "linear",
                    queue: !1
                }
            })
        })
    });
`}`
if (window.addEventListener)
    window.addEventListener("load", downloadJSAtOnload, false);
else if (window.attachEvent)
    window.attachEvent("onload", downloadJSAtOnload);
else window.onload = downloadJSAtOnload;` 

I also came across a page on your site desandro stating that windows load is bad/slow for loading isotope, but if I do not use this and do it when dom is ready the images not being loaded would throw the isotope top offset, causing overlap. 

Could you look at my code here and tell me if it is a suitable solution?

**Comment by vishy93** [comment]
This now throws my bxSlider weirdly stops that functioning :s

**Comment by thedonquixotic** [comment]
I am also curious about this
