### ISSUE TITLE
Bower Install Bug - Uncaught TypeError: Cannot read property 'Item' of undefined

### ISSUE THREAD

**Issue by thathurtabit** [metafizzy/isotope#1228]
Hi, 

I'm struggling with getting Isotope to work correctly after installing with Bower.

I've read through over similar problems here but have been unable to find a solution.
I'll document my steps below in the hope it explains the problem:

1. Ran `bower install isotope --save` which installs Isotope and dependencies in my `bower_components` older and updates `bower.json` to include:

```javascript
"dependencies": {
        "isotope": "^3.0.2"
}
```

2. Run `gulp && gulp watch` to compile my JS and see the results in browser

3. Get the `console` error: 
```javascript
Uncaught TypeError: Cannot read property 'Item' of undefined
    at outlayer.js:39
    at outlayer.js:39
```

4. Looking at [this](https://github.com/metafizzy/isotope/issues/879#issuecomment-161400781) I update my `bower.json` to read:

```javascript
{
  "name": "sage",
  "homepage": "https://roots.io/sage/",
  "authors": [
    "Ben Word <ben@benword.com>"
  ],
  "license": "MIT",
  "private": true,
  "dependencies": {
    "bootstrap": "git://github.com/twbs/bootstrap.git#v4.0.0-alpha.6",
    "isotope": "^3.0.2"
  },
  "overrides": {
    "isotope": {
      "main": [
        "js/item.js",
        "js/layout-mode.js",
        "js/isotope.js",
        "js/layout-modes/vertical.js",
        "js/layout-modes/fit-rows.js",
        "js/layout-modes/masonry.js"
      ]
    },
    "outlayer": {
      "main": [
        "item.js",
        "outlayer.js"
      ]
    }
  }
}
```

5. Run `gulp && gulp watch` to compile my JS and see the results in browser

6. Get the below error which seems to suggest Isotope isn't working at all now.

```javascript
Uncaught TypeError: t(...).isotope is not a function
    at Object.init (main.js:3)
    at Object.fire
```

***Any ideas?***

**Comment by desandro** [comment]
Looks like you're trying to use isotope as a jQuery plugin. You'll need to install [jQuery bridget](https://github.com/desandro/jquery-bridget)

**Comment by thathurtabit** [comment]
Thanks for the heads up @desandro. 

So although I have jQuery included in my build, I'll need to use [jQuery Bridget](https://github.com/desandro/jquery-bridget) to call `isotope` using the jQuery calls? Might be worth adding that info to the main [isotope](https://github.com/metafizzy/isotope) page if that's the case (save having to explain things to laymans like myself).

To get mine working, I've used the overrides in my `bower.json` setup below:

```javascript
{
  "name": "sage",
  "homepage": "https://roots.io/sage/",
  "authors": [
    "Ben Word <ben@benword.com>"
  ],
  "license": "MIT",
  "private": true,
  "dependencies": {
    "isotope": "^3.0.2"
  },
  "overrides": {
    "isotope": {
      "main": [
        "js/item.js",
        "js/layout-mode.js",
        "js/isotope.js",
        "js/layout-modes/vertical.js",
        "js/layout-modes/fit-rows.js",
        "js/layout-modes/masonry.js"
      ]
    },
    "outlayer": {
      "main": [
        "item.js",
        "outlayer.js"
      ]
    }
  }
}
```

And vanilla JS calls in my `main.js`

```javascript
var grid = document.querySelector('.quote-list');
        var iso = new Isotope( grid, {
          // options...
          itemSelector: '.quote',
          masonry: {
            columnWidth: 300
        }
});
```

**Comment by desandro** [comment]
Thanks for reporting back. [jQuery Bridget is mentioned multiple times in the Module loaders section](http://isotope.metafizzy.co/extras.html#module-loaders)
