### ISSUE TITLE
FitRows combined with Masonry

### ISSUE THREAD

**Issue by jnicol** [metafizzy/isotope#1231]
I am hoping to produce a layout that includes features of both the FitRows and Masonry layout modes.

I have attached a mockup showing what I want to achieve. I see this as being a Masonry layout with rows. Another way to look at it is a FitRows layout where items are re-ordered to fit the available horizontal space.

Unlike a regular Masonry layout, the top of each element would be set to the tallest height of the previous row's elements.

I don't think Isotope's current layout modes make it possible to achieve what I want? I am thinking that it might be possible to hack together the Masonry and FitRows logic to achieve what I want, but possibly I am being naive!

![screen shot 2017-03-02 at 12 50 13 pm](https://cloud.githubusercontent.com/assets/1201646/23489923/4e470be2-ff49-11e6-8b06-ece97d5d0d7f.png)

**Comment by desandro** [comment]
Hello! Thank you for this feature request and for the helpful image.

If you're looking to fill gaps, then [Packery layout mode](http://isotope.metafizzy.co/layout-modes/packery.html) is the way to go.

Both fitRows and masonry were not designed to manage gaps. But Packery was explicitly designed for this purpose.

**Comment by Markyz-coder** [comment]
Jnicol: hello, did you find the solution? I need exactly same functionality. Thank you very much!
