### ISSUE TITLE
Tile on page load rather than click?

### ISSUE THREAD

**Issue by therourke** [metafizzy/isotope#1232]
I am using a [wordpress theme](https://thepixeltribe.com/template/draft-portfolio/) that has isotope baked in. It is used on the front page to tile 'featured' wordpress images. 

[As you can see](http://machinemachine.net), when you first load my site the tiles do not sit in place. To get isotope to tile them you have to click any of the headers (such as 'portfolio'). The theme designer has each of these headers call up isotope using href="javascript:void(0)"

Is there a way to have the tiling happen upon page load without clicking anything? My coding knowledge is very sketchy.

Your help much appreciated.

**Comment by desandro** [comment]
Looks like Isotope is not initialized until after all images have loaded. You likely would want Isotope initialized first, then re-laided out as images load. See http://isotope.metafizzy.co/layout.html#imagesloaded
