### ISSUE TITLE
window.getSize() return undefined

### ISSUE THREAD

**Issue by WebWikom** [metafizzy/isotope#1233]
Hi,

I have an image grid on my website which work with Rokbooster ( On click, open a overlay with the image you clicked in a greater size)
I need to add isotope to filter the images however it seems that isotope is breaking Rokbooster.

I've been trying things with and without isotope enabled and it seems that window.getSize() return undefined when isotope is enabled and Rokbooster is using the window.getSize() values to create the overlay.

Is this intended ?

**Comment by desandro** [comment]
If your theme has MooTools, there may be a conflict. See desandro/get-size#1. Can you confirm if that's the issue?

**Comment by WebWikom** [comment]
Well it seems that it was the issue. However the Rokbooster plugin need Mootools to work, so i used @nicbell advice and now everything works fine ! Thanks for your quick response  !

**Comment by desandro** [comment]
Thanks for following up 👍
