### ISSUE TITLE
isotope and item with display flex

### ISSUE THREAD

**Issue by fabienlm** [metafizzy/isotope#1234]
i've problem with positionning element
look this list of item without isotope plugin : http://codepen.io/fabiolm/pen/jBVJWM
You see that the items are the same height even though the text size is different.

But with isotope plugin, isotope apply absolute position on each item and height of each is different. look this : https://codepen.io/fabiolm/pen/EWNmoX

Is there any solution to keep same height on items with isotope plugin ?

**Comment by desandro** [comment]
Sorry, but I don't think there is a good solution here. Isotope and `display: flex` (flex-box) are not designed to work together. Isotope was designed to work with floated elements. `display: flex` is designed to have elements static, and not have their layout manipulated.
