### ISSUE TITLE
sortBy with a non-array parameter

### ISSUE THREAD

**Issue by joallard** [metafizzy/isotope#1235]
Sorry for removing the issue template, but I feel this is fairly straightforward.

I'm having issues sorting elements. In stepping through, I noticed this line in `_sort`:

```
    var sortBys = [].concat.apply( sortByOpt, this.sortHistory );
```

If `sortByOpt` is a string, the string is split by letter into an array, and concat with the history. ie. if `sortByOpt = 'name'`, then `sortBys = [['n','a','m','e'], 'foo', 'bar']`

**Comment by desandro** [comment]
Wow, thank you for catching this bug. It's gone unnoticed for years 😱. This bug should be fixed in v3.0.3, freshly released. I did have trouble creating a test case for it. Please let me know if this hasn't been fixed.

**Comment by joallard** [comment]
Thanks for the quick fix! The issue I've reported has been rightly fixed, ie. the first `sortBy` is the right value. However that has no effect on why my own sort in the DOM doesn't work haha. I'm debugging at the moment.

**Comment by joallard** [comment]
Found it. Turns out I was calling isotope in my js as a function before doing the isotope setup putting the sort data in place. I found this bug by chance while debugging. ^_^
