### ISSUE TITLE
isotope filtering option not working when user come on link form other page

### ISSUE THREAD

**Issue by vishalsingh119** [metafizzy/isotope#1238]
Isotope filtering plugin not working properly when we redirect link from another page to filtering page.For example in website two filtering menu is there(mobile and design).So from other page when i give link for filtering menu then page redirect properly but that menu not display filtered option.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by vishalsingh119** [comment]
right now i don't have any,i will crate in code pen and i will share the link with you

**Comment by vishalsingh119** [comment]
i create a basic and simple test just for understanding...
http://codepen.io/vishalsingh119/pen/OpQYma

as you see in this part i add anchor tag inside all filter for redirect link to graph.its redirecting but graph not filter the data

**Comment by vishalsingh119** [comment]
same time i am facing issue with alignment also.refer these two image-https://ibb.co/jNx1rF and https://ibb.co/mzAMrF  

See these also

**Comment by desandro** [comment]
Sorry, but I don't think this demo demonstrates the issue you're having.

As for alignment, are you using [imagesLoaded](http://isotope.metafizzy.co/layout.html#imagesloaded)?

**Comment by vishalsingh119** [comment]
Exactly i don't know but i am thinking js code(that call isotope plugin) having some issue, because when i try to call isotope plugin using js code that you provide at your page, that time plugin not working.

**Comment by vishalsingh119** [comment]
At same time in console also when we click on one filter option then 8 error in right side showing,when we click on another one then multiple of 8 means 16.refer image....https://ibb.co/hWMXiv

**Comment by desandro** [comment]
Without a **reduced test case** I cannot provide support for your issue.

**Comment by vishalsingh119** [comment]
ok...soon i provide you full test for this issue
