### ISSUE TITLE
Appending images in a specific order using imagesLoaded

### ISSUE THREAD

**Issue by alexhollender** [metafizzy/isotope#1241]
I don't think this qualifies as a bug, I'm just wondering if it's possible and cannot figure it out.
I want to append images to my isotope grid in a specific order. Currently the test case below appends 10 images at a time. The images are numbered and if you look at the DOM they are in the desired order, however they appear in the grid in a seemingly random order.

_*Sometimes, by chance, they do append in the expected order (1, 2, 3, 4, 5, 6, 7, etc.), so make sure to try a few times to see what I mean_

**Test case:** http://codepen.io/alexhollender/pen/NpBZWB

**Comment by desandro** [comment]
If you want to maintain order of the new items, then you cannot use `appended` when each loads. One option is to use `appended` after the whole set is loaded.

``` js
  $items.imagesLoaded( function() {
    $grid.append( $items );
    $grid.isotope( 'appended', $items );
  });
```

See demo http://codepen.io/desandro/pen/ea76cc80964e9917d781ead940e9bd92

You can maintain the staggered effect by using [`stagger` option](http://isotope.metafizzy.co/options.html#stagger)

**Comment by alexhollender** [comment]
@desandro thank you so much for explaining that!
