### ISSUE TITLE
"show all" automatically comes into action

### ISSUE THREAD

**Issue by heyl-d** [metafizzy/isotope#1242]
Hello !

I am currently working on a Wordpress website and I am using a filterable gallery based on Isotope.
I want the gallery to hide all images before before you click on one of the filters. I managed to "delete" the "show all" filter but my issue is that all the images automatically appear as they load and only after that they all disappear, even when I select one of the filters to be first loaded. 

Is there any way this could be avoided ? It is quite annoying as there is a lot of images displayed.

Thanks a lot and sorry for my english !

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by heyl-d** [comment]
Yes, sure.

As I think the problem comes from the gallery plugin, here is its php code :

`<?php
function rfp_shortcode_func( $atts ) {
	ob_start();
    $opts = shortcode_atts( array(
        'id' => '',
    ), $atts );

	$postID = $opts['id'];

	if(!empty($postID) && 'rfp-scode' == get_post_type($postID))
	{
		$rfp_data = get_post_meta($postID);
		
		// fetch rfp post meta data
		$_rfp_selpost  = !empty($rfp_data['_rfp_selpost'][0]) ? $rfp_data['_rfp_selpost'][0] : '';
		$_rfp_seltax   = !empty($rfp_data['_rfp_seltax'][0]) ? $rfp_data['_rfp_seltax'][0] : '';
		$_rfp_taxterms = !empty($rfp_data['_rfp_taxterms'][0]) ? unserialize($rfp_data['_rfp_taxterms'][0]) : array();
		$_rfp_st_dcol  = !empty($rfp_data['_rfp_st_dcol'][0]) ? $rfp_data['_rfp_st_dcol'][0] : '';
		$_rfp_st_tcol  = !empty($rfp_data['_rfp_st_tcol'][0]) ? $rfp_data['_rfp_st_tcol'][0] : '';
		$_rfp_st_pcol  = !empty($rfp_data['_rfp_st_pcol'][0]) ? $rfp_data['_rfp_st_pcol'][0] : '';
		$_rfp_st_size  = !empty($rfp_data['_rfp_st_size'][0]) ? $rfp_data['_rfp_st_size'][0] : '';
		
		wp_reset_query();
		
		// custom query with arguments to fetch project posts
		$rfp_posts_args = array(
			'post_type'			  => $_rfp_selpost,
			'posts_per_page'	  => '-1',
			'post_status'		  => 'publish',
			'ignore_sticky_posts' => true,
			'tax_query'  => array(
				array(
					'taxonomy' => $_rfp_seltax,
					'field'    => 'id',
					'terms'    => unserialize($_rfp_taxterms),
				),
			),
		);
		$filter_posts = new WP_Query( $rfp_posts_args );
		$contentCall  = 'rfp-shortcode-'.$postID;
		?>
		<div id='<?php echo $contentCall; ?>' class='rfp-wrapper <?php echo $contentCall; ?>'>
		
			
			<div class="rfp-filter">
				<ul class="filter rfpfilters">
					<?php

					$filter_terms = unserialize($_rfp_taxterms);
					
					foreach( $filter_terms as $term_id ) 
					{
						$term      = get_term( $term_id, $_rfp_seltax );
						$term_slug = $term->slug;
						$term_name = $term->name; 
						?>
						<li><a href="JavaScript:void(0);" data-filter="<?php echo $term_slug; ?>"><?php echo $term_name; ?></a></li>
						<?php 
					} 
					?>
				</ul>
			</div>
			
			<div class="rfp-posts rfp-grids">
				<?php
				if ( $filter_posts->have_posts() ) :
				while ( $filter_posts->have_posts() ) : $filter_posts->the_post(); 
				
					$data_type  = '';
					$postID     = get_the_ID();
					$post_thumb = wp_get_attachment_image_src( get_post_thumbnail_id( $postID ), $_rfp_st_size ); 	
					
					$terms = get_the_terms( $postID, $_rfp_seltax ); 
					$cat_links = array();
					foreach ( $terms as $term ) {
						$cat_links[] = $term->slug;
					}
					foreach($cat_links as $itm){
						$data_type .= $itm.' ';
					}
				?>
					<div class="rfp-item item <?php echo $data_type; $data_type = null; ?> rfp-grid <?php echo $_rfp_st_dcol.' '.$_rfp_st_tcol.' '.$_rfp_st_pcol; ?>">
						<?php if(isset($post_thumb[0]) && $post_thumb[0] !=""){ ?><div class="rfp-imgwrap"><img alt="<?php the_title(); ?>" src="<?php echo $post_thumb[0]; ?>" class="rfp-img"></div><?php } ?>
						<a class="rfp-mask" href="<?php the_permalink(); ?>"></a>
						<div class="rfp-item-title"><?php the_title(); ?></div>
					</div>
				<?php
				endwhile;
				wp_reset_postdata();
				else: 	
				_e( 'Sorry, no post items found. Kindly add.','rfp' );
				endif;
				?>
			</div>
			<script>
			jQuery(window).load( function() 
			{
				var $container = jQuery('#<?php echo $contentCall ?> .rfp-posts');
				// initialize isotope
				$container.isotope({
					filter: '.example',
					animationOptions: {
						duration: 750,
						easing: 'linear',
						queue: false,
					}
				});
				
				// filter items when filter link is clicked
				jQuery('#<?php echo $contentCall ?> .rfpfilters a').click(function(){
					var selector = jQuery(this).attr('data-filter');
					if( selector !== '*' ) selector = selector.replace(selector, '.' + selector)
					$container.isotope({ 
						filter: selector ,
						animationOptions: {
							duration: 750,
							easing: 'linear',
							queue: false,	
						}
					});
					return false;
				});
				
				// set active filter items
				var $optionSets = jQuery('#<?php echo $contentCall ?> .filter'),
				$optionLinks    = $optionSets.find('a');
				
				$optionLinks.click(function(){
					var $this = jQuery(this);
					// don't proceed if already active
					if ( $this.hasClass('active') ) {
						return false;
					}
					var $optionSet = $this.parents('.filter');
					$optionSet.find('.active').removeClass('active');
					$this.addClass('active'); 
				});
			});	
			</script>
		</div>
		<?php
	}
	else{
		_e( 'Sorry, RFP shortcode does not exists.','rfp' );
	}
	return ob_get_clean();
}
add_shortcode( 'rfp', 'rfp_shortcode_func' );`


what I did was changing the `filter: '*',` to `filter: '.example',` that is not an existing class so that the "show all" filter disappeard but there comes the problem I mentioned.

**Comment by heyl-d** [comment]
and if you need it, you can see my website here : http://lapetitefabrique.apps-1and1.net

**Comment by desandro** [comment]
Thanks for that. The issue is that you're using [$(window).load, which will wait until everything on the page loads](http://metafizzy.co/blog/window-load-last-resort/). Instead, I recommend using [imagesLoaded](http://imagesloaded.desandro.com) to wait only for the grid items images to load.

Here's how I would do it. See demo http://codepen.io/desandro/pen/a228a90f644ba6dd48d6ff4b49723406/

Hide images initially with CSS. Then un-hide them once they are loaded.

``` css
.grid-item {
  float: left;
  opacity: 0; /* invisible by default */
}

.imgs-loaded .grid-item {
  opacity: 1; /* visible once loaded */
}
```

``` js
// init Isotope after all images have loaded
var $grid = $('.grid').imagesLoaded( function() {
  // add class once loaded
  $grid.addClass('imgs-loaded');
  // init Isotope
  $grid.isotope({
    itemSelector: '.grid-item',
    filter: 'none',
    percentPosition: true,
    masonry: {
      columnWidth: '.grid-sizer'
    }
  });

  $('.show-items-button').on( 'click', function() {
    $grid.isotope({ filter: '*' });
  })
});
```

**Comment by heyl-d** [comment]
Thanks for your quick answer !
Unfortunately I can't make it work, the opacity:0 is working but the images are still there (as you can see on the website). If I am right, the part that you are changing is 

> jQuery(window).load( function() 
> 			{
> 				var $container = jQuery('#<?php echo $contentCall ?> .rfp-posts');
> 				// initialize isotope
> 				$container.isotope({
> 					filter: 'none',
> 					animationOptions: {
> 						duration: 750,
> 						easing: 'linear',
> 						queue: false,
> 					}
> 				});

so I changed it like this 

> jQuery.imagesLoaded( function() 
> 			{
> 				var $container = jQuery('#<?php echo $contentCall ?> .rfp-posts');
> 				// initialize isotope
>                                 $container.addClass('imgs-loaded');
> 				$container.isotope({
>                                         itemSelector: '.rfp-item',
> 					filter: 'none',
> 					animationOptions: {
> 						duration: 750,
> 						easing: 'linear',
> 						queue: false,
> 					}
> 				});

and added the css but apparently that is not the right way to do it !
I am quite a beginner at this so it is probably a ridiculous mistake but I really want to make it work

**Comment by heyl-d** [comment]
So I believe the part that I needed to change was 
`jQuery(window).load( function() 
			{
				var $container = jQuery('#<?php echo $contentCall ?> .rfp-posts');
				// initialize isotope
				$container.isotope({
					filter: 'none',
					animationOptions: {
						duration: 750,
						easing: 'linear',
						queue: false,
					}
				});`

so I tried this
`var $container = $('.container').imagesLoaded( function() {
				var $container = jQuery('#<?php echo $contentCall ?> .rfp-posts');
				// initialize isotope
                                $container.addClass('imgs-loaded');
				$container.isotope({
					filter: 'none',
					animationOptions: {
						duration: 750,
						easing: 'linear',
						queue: false,
					}
				});`

and added the css and imagesLoaded but what I got was that my images are transparent but still there and do no appear when a filter is clicked...
i am kinda new at this so i probably made something wrong but i can't find what

**Comment by desandro** [comment]
I'll have to leave the rest to you. My recommendation is to look through the **reduced test case* I provided to understand what's going on and apply that technique to your site.
