### ISSUE TITLE
using with table elements add styles

### ISSUE THREAD

**Issue by Paul75** [metafizzy/isotope#1243]
Hello,

I'm using Isotope with filtering tr in tables.

When I do this in my tbody element it has style and in tr element azlso... Whe I can remove styles that it add ?

Thanks

**Comment by desandro** [comment]
I do not recommend using Isotope with `<table>` element. Tables have innate positioning and display styles. Plus there's that pesky `<tbody>` in there. You may be able to resolve some issues by overwriting styles with your own CSS.

Instead, I recommend you build up a table-like list with your own CSS. See demo http://codepen.io/desandro/pen/pbwGC?editors=1010
