### ISSUE TITLE
Isotope + Flickity issue

### ISSUE THREAD

**Issue by DeoThemes** [metafizzy/isotope#1244]
Hello,
I'm having trouble to make isotope work together with flickity.
After I resize the browser the calculation of isotope breaks layout. Only first time on page load the calculation is correct, The layout breaks only below flickity slider. I tried to add the call function in the (window).resize so it will recalculate every time browser resize but it doesn't help.

**Test case:** http://codepen.io/DeoThemes/pen/bqOXJz

Any help will be appreciated :)

**Comment by desandro** [comment]
Thanks for reporting this issue. Sounds like you're running into #916. I'm closing this one as a duplicate.
