### ISSUE TITLE
CSS transition duration doesnt work

### ISSUE THREAD

**Issue by Hayko1994** [metafizzy/isotope#1245]
Hi. I have tried several times to change transition duration in the CSS but I don't know why it doesn't work. Can you help me, please? I really can't find the mistake in the jQuery and CSS file. Here is the link.
Test case: [http://codepen.io/Hayko/pen/zZbYOE](url)
Thanks.

**Comment by desandro** [comment]
Looks like you're using older Isotope v1 CSS and options, but you have Isotope v3 JS.  Use [`transitionDuration` option](http://isotope.metafizzy.co/options.html#transitionduration)

See revised demo http://codepen.io/desandro/pen/3f7b1f5bf97f539689de4408b1936587/

**Comment by Hayko1994** [comment]
Thanks a lot. Works perfectly.
