### ISSUE TITLE
imagesLoaded is Not Working With Filters.

### ISSUE THREAD

**Issue by tayfunefendi** [metafizzy/isotope#1246]
When I try to use imagesLoaded, filters are not working. When i disable imagesLoaded, all images are overlapping. Any ideas?

Here is my codes without imagesLoaded:
`var $container=$(".portfolio-content");$container.isotope({itemSelector:".portfolio-items",layoutMode:"fitRows"});$("#filters").on("click","a",function(){var a=$(this).attr("data-filter");$container.isotope({filter:a})});$(".button-group").each(function(b,a){var c=$(a);c.on("click","a",function(){c.find(".is-checked").removeClass("is-checked");$(this).addClass("is-checked")})});`

When I change the codes with codes below, filters are down.
`var $container = $('.portfolio-content');
$container.imagesLoaded( function() {
$container.isotope({
itemSelector: '.portfolio-items',
 layoutMode: 'fitRows'
});
}); $("#filters").on("click","a",function(){var a=$(this).attr("data-filter");
	$container.isotope({filter:a})});
	$(".button-group").each(function(b,a){var c=$(a);
	c.on("click","a",function(){c.find(".is-checked").removeClass("is-checked");$(this).addClass("is-checked")})});`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by tayfunefendi** [comment]
Here is the test case but they are not working i don't know why. http://codepen.io/anon/pen/aJeMXB  Please check the links below working. Filter is working without imagesLoadedhttp://www.sitegoster.net/x/test/test1.html Filter is not working with imagesLoadedhttp://www.sitegoster.net/x/test/test2.html  I am really need your help. Please check my website and you can understand better.http://basiliscodesign.com/automotive.html Thanks. 10.04.2017, 21:25, "David DeSandro" <notifications@github.com>:I'm sorry to see you're having trouble with Isotope. Could you provide a reduced test case? See Submitting Issues in the contributing guidelines.

**Comment by dmto** [comment]
It's not working because you're not including the imagesLoaded library.

Just insert this at the bottom of your script instead.

`window.onload = function() {
    $container.isotope('layout');
};`

**Comment by tayfunefendi** [comment]
imageLoaded is not working with filters but this code is working perfect. Thank you.

**Comment by desandro** [comment]
Looks like we needed to fix: `itemSelector: '.portfolio-items'` and add imagesloaded.pkgd.js. See demo http://codepen.io/desandro/pen/b1520e9dc08cc2591ae5dae831417200
