### ISSUE TITLE
Url hash filter changes url field

### ISSUE THREAD

**Issue by dare023** [metafizzy/isotope#1247]
Hello, 
I wonder if anyone can help.

I have coded grid with isotope from WP custom posts and that part works ok.
The only problem I have is that I need to use URL hash filter, and every change changes URL field.
that is not the case on the demo, so I wonder if I am making a mistake somewhere?

Test link http://privaterooms.www023.in.rs/test/
Thank you in advance

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. I appreciate the live URL, but this looks like a full site, not a **reduced test case**. If you can provide a **reduced test case**, I can take a look. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by dare023** [comment]
Hi.
Not sure how to provide a test case as this is development Wordpress website where all info is created using the database and WP functions.
After (a lot ) trying and googling I came up with this that seems to work ok
```
jQuery(window).load(function() { 

    // cache container
    var $container = jQuery('.grid');

    // initialize isotope
    $container.isotope({
    // options...
    
    itemSelector: '.grid-item'
    });

    // filter items when filter link is clicked
    jQuery('.filter-button-group li ').on('click', function() {
    var selector = jQuery(this).data('filter');
    $container.isotope({
    filter: selector
    });

});
    });

```
Maybe it will help?
Thank you so much for the support and great work.

**Comment by desandro** [comment]
[I recommend you do not use window load](http://metafizzy.co/blog/window-load-last-resort/)

**Comment by dare023** [comment]
Great, thank you.
Now when I have it working I can see to avoid this.
Thank you so much for support.
