### ISSUE TITLE
<table> Chrome and IE issue

### ISSUE THREAD

**Issue by rahulchandrasekharan** [metafizzy/isotope#1250]
I am doing Sorting using isotope.
 It works perfectly on Firefox, but has issues on Chrome, Opera and IE. I am also using bootstrap css. and jQuery 1.11.1

Here is a demo of the issue that I am facing

http://codepen.io/linktoahref/full/JNKgJZ/

Thank You!

**Comment by desandro** [comment]
Looks like you're using `<table>`, which is causing the layout to break. `<table>` has innate layout that browsers handle. I recommend using `div` instead, with table-like CSS for the rows. See demo http://codepen.io/desandro/pen/pbwGC
