### ISSUE TITLE
Animation issue on IOS

### ISSUE THREAD

**Issue by senner007** [metafizzy/isotope#1252]
**Test case:** http://codepen.io/desandro/pen/mEinp
Dear developer

Is there a chance that the animations will be fixed on ios in the future. At some point it stoppped working properly. You can see an example of this if you go to the NY Times site in your list of demos. 
I'm using Ipad air 2 with latest IOS. 
Thanks

**Comment by desandro** [comment]
Thanks for reporting this issue. Performance can be improved by:

+ disabling transitions 
+ limiting the number of items
+ using smaller images within items

This goes for mobile and desktop devices.

If your site is still struggling with Isotope, it may not be right solution. Lists of items work just as well :)
