### ISSUE TITLE
wrong key of masonry fitWidth option in the docs

### ISSUE THREAD

**Issue by team-ok** [metafizzy/isotope#1253]
**Sorry, actually there's no issue with the docs concerning the fitWitdh option.** 
I was using an old version of isotope where the key had to be `isFitWidth`. The current version seems to be supporting both `isFitWidth` and 
`fitWidth`.

**Test case:** http://codepen.io/desandro/pen/BptxJ

<del>
Hi,
the key of the fitWidth option mentioned in the [docs](http://isotope.metafizzy.co/layout-modes/masonry.html#fitwidth) doesn't work. It should be `isFitWidth` as used in the linked CodePen example.
</del>

**Comment by desandro** [comment]
[Yup](http://masonry.desandro.com/options.html#fitwidth). Thanks for double checking
