### ISSUE TITLE
A WP theme + visual composer

### ISSUE THREAD

**Issue by karwanmino** [metafizzy/isotope#1254]
Hello david, 

i use a wp theme integrated visual composer - when i activate the VC plugin i see the isotope bakery issue it don't let the theme to find some functions - without VC its okay !

i updated the Isotope to latest version from both sides in VC and in the theme too 

both of them using isotope.min.js

i want use the theme with VC plugin but together they has isotope issue, so how to fix the issue ?

any help ? please ..

best regards

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by karwanmino** [comment]
I'm not familiar with codepen - or providing the test case but i'm ready to explain my problem with examples. maybe you feel it and understand the cause .. 

- i deleted the isotope require line in VC functions now in my theme it works finely but maybe VC needs the isotope too.

make sense ?

**Comment by desandro** [comment]
Sorry without a **reduced test case** there is no way I can debug your issue.

**Comment by karwanmino** [comment]
At last i fixed my issue by myself .

i can declare how i fixed it.

i replaced the v2 of isotope to both places in VC and in my theme JS files and it fixed .!

best love ..
