### ISSUE TITLE
How to use https://jsfiddle.net/qg6orjnr/28/ with multiple filter values.

### ISSUE THREAD

**Issue by mikeantkowiak** [metafizzy/isotope#1255]
Hi Guys,

I found this post about creating a case where pagination is used with filtering. 
https://github.com/metafizzy/isotope/issues/724

Sample is here.
https://jsfiddle.net/qg6orjnr/28/

So my question/issue is as follows:

Is there a way to include multiple data-filter values for the pagination example? Looking at the code, it looks for a single data-filter value as an attribute, instead of data-filter values, like isotope works out of the box, using multiple classes.

Is there a way to take IIIu6ko's example https://jsfiddle.net/qg6orjnr/28/ and integrate multiple values for data-filter on each item? Or use that exact example but stick with using the classes instead of the data-filter attribute?

The html is like this for the individual items

   <div class="isotope-item height-2" data-filter="red">
      <div class="box box-red">
        Box-1
      </div>
    </div>

As you can see it is not using the class name, but instead data-filter attribute. How can we take the code from https://jsfiddle.net/qg6orjnr/28/ and make it so that the items can have multiple filter values?

For example:
  <div class="isotope-item height-2" data-filter="red, blue">
      <div class="box box-red">
        Box-1
      </div>
    </div>
or
  <div class="isotope-item height-2 red blue">
      <div class="box box-red">
        Box-1
      </div>
    </div>

The code uses only a single value, and we need more then one.

Any help would be great!

Thank you for your time!

Mike

**Comment by desandro** [comment]
You can filter for multiple attributes. To select _red_ and _blue_, instead of a class selector `.red, .blue` or attribute filter would looks like `*[data-filter="red"], *[data-filter="blue"]`.

Looking at your example: it's getting fairly complex. 100+ lines of code. I do not recommend using pagination with Isotope because it requires this amount of complexity. Maybe Isotope isn't the right solution for your use case.

**Comment by mikeantkowiak** [comment]
@dessandro Thank you for the response. On the old isotope site there was an example using infinite scroll. We basically want a better user experience where it either, lazy loads or work in an infinite scroll. 

Do you know if there is a solution for dealing with many entries with filtering capabilities, that works into isotope like in v1? Many of the examples using isotope either, didn't work or were not properly coded.

Any insight would be helpful.

**Comment by desandro** [comment]
> Do you know if there is a solution for dealing with many entries with filtering capabilities, that works into isotope like in v1?

Sorry, I'm not sure what you're asking for
