### ISSUE TITLE
white space beneath items

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/isotope#1256]
hi,

recently got an issue with isotope.
please check here http://www.charicomm.org/en/selected-projects/

see the gap between each row. it'll be fixed after resizing window or filtering items.

here's the js code
```javascript
work_grid.imagesLoaded(function(){
   work_grid.isotope({
      itemSelector: '.mix',
      layoutMode: isotope_mode,
      filter: fselector
   });
});
```

tried with both masonry and packery  layouts. and had the same problem.
I appreciate any help.
thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by Mohsen-Khakbiz** [comment]
the issue was coming from a lazyload plugin. as I disabled the plugin the issue was gone.
closing this issue for now

thanks
