### ISSUE TITLE
Isotope Filter and Sort for more Items as 100

### ISSUE THREAD

**Issue by svanskivar** [metafizzy/isotope#1257]
**Hello David,**

How I know and tested, Isotope works very good with items under 100. But I have e.g. 400 Items or more. What can I do, that Isotope Filter and Sort so good to work how with 100 items. 

May you have some other Plugin like isotope, what may costs more, but does work with many items also very good? I think something like this need also others.

**best regards**

**Comment by desandro** [comment]
Thank you for this question!

My only recommendation for improving performance for 100+ items is to try disabling [`transitionDuration: 0`](https://isotope.metafizzy.co/options.html#transitionduration).

That's about it. Even then, Isotope has to make changes to 100+ items. There is no way around it.
