### ISSUE TITLE
IE9 recalculating positions after filtering

### ISSUE THREAD

**Issue by jwssnr** [metafizzy/isotope#1258]
Hi 

I’m stuck on this site: http://www.mutznerag.ch/unsere-referenzen/
(Short version: https://codepen.io/jwssnr/pen/dWevWW )
It works on all browsers except IE9 and below but I don’t care about IE8.
So I try to explain: After filtering the grid-items are just placed on their absolute positions where they were placed before filtering. How can I enforce IE9 to recalculate the positions or what did I wrong in my jQuery-script?

Cheers
Jürgen

**Comment by desandro** [comment]
[Isotope v3 does not support IE9](https://isotope.metafizzy.co/extras.html#browser-support). For IE9, try [Isotope v2](https://isotope.metafizzy.co/v2)

**Comment by jwssnr** [comment]
Thank you. Will V2 work for my layout?
