### ISSUE TITLE
sortComplete event support

### ISSUE THREAD

**Issue by nowres** [metafizzy/isotope#1259]
Hi,

When setting `sortBy` option on initialization, `arrangeComplete` event is not triggered I have to call `grid.isotope({ sortBy : 'name' });` after initialization as a workaround

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by nowres** [comment]
I checked again, the event gets fired if we bind it before isotope initialization:

https://codepen.io/anon/pen/jwbJOa

**Comment by desandro** [comment]
@nowres That's because the initial layout involves `arrange`, but there is no transition for that initial arrange.

**Comment by nowres** [comment]
@desandro That seems logic, Thanks
