### ISSUE TITLE
Isotope fitColumns and Name Order with first Capital Letters

### ISSUE THREAD

**Issue by svanskivar** [metafizzy/isotope#1261]
Hello,

I do isotope-Gallery for Names. All Names are already ordered in html alphabetically.
Example: https://codepen.io/anon/pen/dWKPoX?editors=0110 

I want to filter these names with Male and Female. Also User can live-search.  All these work now, but layout is not responsive and height of #grid also not dynamic. If I have after 1 Month new names in the list, then must I calculate Height of #grid manually. 

Also Big First Letters are very important. If User filters or search, then all names  are filling Height of #grid, but I want, that they fill width of #grid. 

I hope you have better solution and also Performance will better. 

best regards.

**Comment by desandro** [comment]
Thanks for reporting this issue and providing a test case.

I'm sorry but I don't understand what the exact issue you are trying to resolve. Could you clarify?

**Comment by svanskivar** [comment]
Thanks for response. 

This is not really issue, my question is more "How do I" and "Feature request". 

Can I do with isotope, `.element-grid` order so vertical, how with `layoutMode: "fitColumns"`, but #grid and elements must be responsive, how with `layoutMode: "masonry"` works.

`layoutMode: "fitColumns"`:  Now If you filter elements, height of grid is still same, but numbers of columns is lower. I need, that number of Columns is constant and #grid height changes automatically. But elements must be ordered vertically(`layoutMode: "fitColumns"`) and not horizontally(`layoutMode: "masonry"`).

**Comment by desandro** [comment]
> layoutMode: "fitColumns", but #grid and elements must be responsive

fitColumns can have items with percent heights, but not percent widths.

> I need, that number of Columns is constant and #grid height changes automatically. But elements must be ordered vertically(layoutMode: "fitColumns") and not horizontally(layoutMode: "masonry").

Have you looked at [fitRows](https://isotope.metafizzy.co/layout-modes/fitrows.html)? Otherwise, I don't think there is a layout mode for this behavior.

**Comment by svanskivar** [comment]
Thanks David, 

> Have you looked at fitRows? Otherwise, I don't think there is a layout mode for this behavior.

Yes I looked. Can I use every functionality of fitRows with only different, that the items are vertically ordered instead of horizontally?

**Comment by desandro** [comment]
>  Can I use every functionality of fitRows with only different, that the items are vertically ordered instead of horizontally?

Sorry, Isotope does not offer a layout mode for this behavior.
