### ISSUE TITLE
1px gaps sometimes occur

### ISSUE THREAD

**Issue by myartsev** [metafizzy/isotope#1263]
From the isotope docs: http://codepen.io/desandro/pen/NqNBxy
I just changed the background colour to green for better contrast, but it's obvious with the sample as it is.

![isotope_gap](https://cloud.githubusercontent.com/assets/4885345/26210803/68ae09dc-3bb6-11e7-9e72-abde33511718.png)

Is the tiny gap between the image an unavoidable side-effect of using the masonry layout? Masonry will have gaps, packery will fill them in, I understand that at a high level without being too familiar with the algorithms. 

The example below illustrates the difference well, both layouts look good and intentional.
Whereas in the example above the tiny gap looks more like a bug rather than an intended feature?
https://codepen.io/desandro/pen/KVrpxM

**Comment by desandro** [comment]
Hi, thanks for opening this issue. I've got a similar issue I'm resurrecting to address this. See #916
