### ISSUE TITLE
Unusual Spacing Behavior

### ISSUE THREAD

**Issue by DaveyJake** [metafizzy/isotope#1264]
@desandro Everything works as expected when using the filters, however, when [trying to view all items](https://www.usarugby.org/events-calendar/#filter=.event), the spacing acts very unusual.

I've never seen this kind of behavior before.  Wondering if you had any ideas?

**Comment by desandro** [comment]
My best guess is that some items are being counted twice by Isotope. This could happen when you initialize Isotope with items, then use the same items for [`appended`](https://isotope.metafizzy.co/methods.html#appended)

**Comment by DaveyJake** [comment]
I'm definitely not using `appended`. [Here's a Gist](https://gist.github.com/DaveyJake/0b944d764c01f5b00e28479cec0067a5) of our implementation.

**Comment by desandro** [comment]
I appreciate the live URL and gist of the code, but the best way for my to debug this issue is to look at a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by DaveyJake** [comment]
I had to make [this mini-version](https://codepen.io/DaveyJake/pen/JNVaNK) rather quickly.  Please forgive the ugliness.  Additionally, I inlined the external **`XML`** towards the very very bottom of the **`HTML`** panel to compensate for CORS.  The **`JS`** implementation has been very slightly modified as a result but the error has been recreated exactly as it is on our live site.  It's probably something so simple that I just can't see it!

**Comment by desandro** [comment]
Ah, thanks for taking a crack with the CodePen. It's a test case, but it's not reduced yet. There's a lot going on with it. Clearly, something is interfering with the normal Masonry layout. Disabling other stuff will help identify what it is.
