### ISSUE TITLE
Fixed width and height container

### ISSUE THREAD

**Issue by pauloffb** [metafizzy/isotope#1266]
I would like isotope to run on a fixed size layout similar to [this](https://codepen.io/pauloffb/pen/gWyZMX)

But if I shuffle enough times there will be some divs that end outside the main div. 
Is there a way I can keep randomizing the layout but with every inner divs being kept inside the outer div?
Thanks.

**Comment by desandro** [comment]
Thanks for this issue. Sorry, no. The Packery layout algorithm is not designed to work with two set dimensions (via width AND height), only one.
