### ISSUE TITLE
Isotope Remove

### ISSUE THREAD

**Issue by Brendan-McIntosh** [metafizzy/isotope#1267]
On the demo the items are closed by clicking the entire box. is there a way to close it with a close icon for example?

**Test case:** https://codepen.io/desandro/pen/fHkwt

**Comment by desandro** [comment]
Sure thing. You have to select item that in which the element was clicked. 

``` js
$grid.on( 'click', '.grid-item__close-button', function( event ) {
  // remove clicked element
  var $item = $( this ).parents('.grid-item');
  $grid.isotope( 'remove', $item )
  // layout remaining item elements
    .isotope('layout');
});
```

See demo https://codepen.io/desandro/pen/52cc6b4d3bcd90d23e9b88802d318168/

**Comment by Brendan-McIntosh** [comment]
Awesome, exactly what I'd hoped, your a legend!

Best regards

Brendan McIntosh

On 31 May 2017, at 18:12, David DeSandro <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure thing. You have to select item that in which the element was clicked.

$grid.on( 'click', '.grid-item__close-button', function( event ) {
  // remove clicked element
  var $item = $( this ).parents('.grid-item');
  $grid.isotope( 'remove', $item )
  // layout remaining item elements
    .isotope('layout');
});

See demo https://codepen.io/desandro/pen/52cc6b4d3bcd90d23e9b88802d318168/
