### ISSUE TITLE
Typescript support for angular 4

### ISSUE THREAD

**Issue by CD-UNCC** [metafizzy/isotope#1268]
Any support for using this with typescript in Angular 4? after getting @types/isotope-layout there are many errors trying to import Isotope into a file.
`/app/node_modules/@types/isotope-layout/index.d.ts' is not a module.
`
`Module not found: Error: Can't resolve 'masonry/masonry`

**Comment by desandro** [comment]
Officially, no Isotope does have Typescript support. But there may be a third party solution out there.

**Comment by PFight** [comment]
There some types

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/isotope-layout
https://www.npmjs.com/package/@types/isotope-layout

**Comment by desandro** [comment]
I'm closing this issue as it hasn't received that many reactions.
