### ISSUE TITLE
Is there a way to combine the URL hash with the combination in the new version?

### ISSUE THREAD

**Issue by bhines01** [metafizzy/isotope#1270]
**Test case:** http://codepen.io/desandro/pen/mEinp

**Comment by desandro** [comment]
Yes, this can be done. But in my experience, the code gets so complex that its not worth the effort. The trickiest part is setting up the selected buttons to change with the hash. I may be able to put together a demo combining [URL hash](http://s.codepen.io/desandro/debug/vErxXj#filter=%3Anot(.transition)) and [combination filters](http://codepen.io/desandro/pen/JEojz).

**Comment by bhines01** [comment]
The demo would be great! I appreciate your response!

**Comment by bhines01** [comment]
Also, I dont know if it is easier but if you could show how to do the hash with checkboxes as well?

**Comment by desandro** [comment]
Got it done!

+ See demo: https://s.codepen.io/desandro/debug/NgqxjW#filter=.green%2C.orange
+ See code: https://codepen.io/desandro/pen/NgqxjW

**Comment by bhines01** [comment]
Thanks! Can the checkboxes act like the combined filters? So when I check green and small, I only get all of the small green items. Right now it will display all of the green items and the small items for all of the other colors.

**Comment by desandro** [comment]
I'll leave that up to you. Take a look at the [other combination filter demo](https://isotope.metafizzy.co/filtering.html#combination-filters) for putting together exclusive filters.

**Comment by bhines01** [comment]
these examples dont seem to be working correctly, do you have an example of the combo filters with hash urls?

**Comment by desandro** [comment]
Sorry, I do not have demo that does exactly what you're asking for. I'll leave that up to you.

**Comment by bhines01** [comment]
ok thanks for all your help!

**Comment by good3n** [comment]
Any chance that two years later you have a demo for exclusive combination filters + URL hash?
