### ISSUE TITLE
Shuffle not firing

### ISSUE THREAD

**Issue by theagregory** [metafizzy/isotope#1271]
When calling the shuffle function, nothing happens. I'm initializing using jQuery, and not receiving any errors. The button is firing.

Initialization of isotope instance:

`$('.grid').isotope({
  itemSelector: '.grid-item',
  columnWidth: 100
});`

A console.log of ('.grid').isotope('shuffle'); reveals:

`(2) [div#container.grid, div#list_flavours.grid, prevObject: n.fn.init(1), context: document, selector: ".grid"]
0
:
div#container.grid
1
:
div#list_flavours.grid
context
:
document
length
:
2
prevObject
:
n.fn.init(1)
selector
:
".grid"`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
