### ISSUE TITLE
Using getFilteredItemElements to addClass during filtering.

### ISSUE THREAD

**Issue by macsupport** [metafizzy/isotope#1272]
I am using Isotope, [velocityjs](https://github.com/julianshapiro/velocity) and [lazysizes](https://github.com/aFarkas/lazysizes) to lazyload images and apply image effects. Actually works without using imagesLoaded. I understand that using `getFilteredItemElements` is the best way to do this but I am wondering if I am doing it correctly, since I can't find an example. 
 [My codepen](https://codepen.io/macsupport/pen/eWjLyX) ( all scripts are in the html panel due to timing issues)

Relevant code:

     var $container = $('#container');
   
      $container.isotope({
      itemSelector: '.item',
      masonry: {
      columnWidth: 200,
       gutter: 10,
       fitWidth: true
      },
      transitionDuration: '0'
       }); 
      
     var elems = $container.isotope('getFilteredItemElements');  
     $('.filters-button-group').on( 'click', 'button', function() {
      var filterValue = $( this ).attr('data-filter');   
       $(elems).removeClass('lazyloaded, lazyload').addClass('lazyload');
       $container.isotope({ filter: filterValue });
       });

Relevant CSS:

     .lazyload {opacity: 0;}
     .lazyloading {opacity: 1;}
     .lazyloaded {opacity: 1;}

**Comment by desandro** [comment]
You'll want to call `getFilteredItemElements` after the filter has been applied. Try this code:

``` js
$('.filters-button-group').on( 'click', 'button', function() {
  var filterValue = $( this ).attr('data-filter');
  $container.isotope({ filter: filterValue });
  var elems = $container.isotope('getFilteredItemElements');
  $(elems).removeClass('lazyloaded, lazyload').addClass('lazyload');
});
```
