### ISSUE TITLE
Multiple level filters

### ISSUE THREAD

**Issue by nadavmoreno** [metafizzy/isotope#1273]
Hi

I would like to make 2 levels category filters, like here: [http://uk.rimmellondon.com/products/all](url).
Do you have any code example ?

Thanks

**Comment by desandro** [comment]
Looks like they are using some variation of [combination filters](https://isotope.metafizzy.co/filtering.html#combination-filters)

**Comment by nadavmoreno** [comment]
thanks!

**Comment by nadavmoreno** [comment]
Do you have a combination filter vanilla  Codepen?

**Comment by desandro** [comment]
Sure thing, see [combination filters with vanilla JS demo on CodePen](https://codepen.io/desandro/pen/VWLJEb)

**Comment by nadavmoreno** [comment]
great!
