### ISSUE TITLE
Can't resolve 'masonry/masonry' in

### ISSUE THREAD

**Issue by gabrielresende06** [metafizzy/isotope#1274]
This error happens when I use your lib with gulp, it's because the lib try to require the masonry lib from masonry directory and the isotope install masonry lib in masonry-layout directory, how can I solve this?

ERROR in ./~/isotope-layout/js/layout-modes/masonry.js
Module not found: Error: Can't resolve 'masonry/masonry' in '/node_modules/isotope-layout/js/layout-modes'
 @ ./~/isotope-layout/js/layout-modes/masonry.js 12:4-16:15
 @ ./~/isotope-layout/js/isotope.js
 @ ./resources/assets/js/app.js

**Comment by desandro** [comment]
Thanks for submitting this issue. Can you specify which gulp package you are using?

**Comment by gabrielresende06** [comment]
I'm using the gulp package :

"dependencies": {
    "isotope-layout": "^3.0.4"
  }

**Comment by desandro** [comment]
Thanks, but I'm curious how you are loading the modules. Can you provide the relevant portion of your `gulpfile.js` where `isotope-layout` is being loaded?

**Comment by guozongwei** [comment]
I have the same problem,I use webpack :    "isotope-layout": "^3.0.4",
