### ISSUE TITLE
bug within items using opacity in style

### ISSUE THREAD

**Issue by o0alexela0o** [metafizzy/isotope#1275]
Hey, I think I have found a bug, 
If my items using opacity (fading each item after it loads) isotope having a problem after.
first item shows ok, them if i click to filter again, all item disappear. if i click again it shows and again all gone.
there also no opacity in browser inspection. but if i add it manually item shows.
i removed appearance of my items using opacity and it got back working normal.
anything i can do about it? 
i can wrap my items inside another div, but looks like a temporary fix. 

thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

You likely need to set both `visibleStyle` and `hiddenStyle`.  See demo https://codepen.io/desandro/pen/9b3004aab9d51cfe2d869bd38152e623/

``` js
var $grid = $('.grid').isotope({
  itemSelector: '.element-item',
  layoutMode: 'fitRows',
  visibleStyle: { opacity: 1 },
  hiddenStyle: { opacity: 0 },
});
```

**Comment by o0alexela0o** [comment]
Thanks for your answer.
What i did in your example is first gave opacity:0 to .element-item

and tried this : (added fadeTo to show elements, and after its done loading your code)
```

// external js: isotope.pkgd.js

$(document).ready(function(){
   $('.element-item').fadeTo(1500, 1, function(){
     
// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.element-item',
  layoutMode: 'fitRows',
  visibleStyle: { opacity: 1 },
  hiddenStyle: { opacity: 0 },
});
// filter functions
var filterFns = {
  // show if number is greater than 50
  numberGreaterThan50: function() {
    var number = $(this).find('.number').text();
    return parseInt( number, 10 ) > 50;
  },
  // show if name ends with -ium
  ium: function() {
    var name = $(this).find('.name').text();
    return name.match( /ium$/ );
  }
};
// bind filter button click
$('.filters-button-group').on( 'click', 'button', function() {
  var filterValue = $( this ).attr('data-filter');
  // use filterFn if matches value
  filterValue = filterFns[ filterValue ] || filterValue;
  $grid.isotope({ filter: filterValue });
});
// change is-checked class on buttons
$('.button-group').each( function( i, buttonGroup ) {
  var $buttonGroup = $( buttonGroup );
  $buttonGroup.on( 'click', 'button', function() {
    $buttonGroup.find('.is-checked').removeClass('is-checked');
    $( this ).addClass('is-checked');
  });
});

   })
})
```

please try to play with items, part of them gone after filter couple time.
this is my bug, thanks

**Comment by o0alexela0o** [comment]
Hey, i made an example:
https://codepen.io/anon/pen/vZXzrK
please check.
thanks

**Comment by desandro** [comment]
Looks like your default CSS is being used after Isotope changes the opacity

``` css
.element-item { opacity: 0; }
```

I recommend adding additional CSS so that items have full opacity after the fade in

``` css
.items-visible .element-item { opacity: 1; }
```

``` js
$('.element-item').fadeTo( 500, 1, function() {
  $grid.addClass('.items-visible');
});
```

See demo https://codepen.io/desandro/pen/e81c4b2d045ad1e1e5a0417121ba090f/
