### ISSUE TITLE
isFiltered flag needed

### ISSUE THREAD

**Issue by o0alexela0o** [metafizzy/isotope#1276]
Hey, could you please add isFiltered flag? so it would be easy to toggle filters.
thanks

**Comment by desandro** [comment]
Thanks for this issue. Could you provide a **reduced test case**? There may be a way to achieve what you're trying to do without adding this feature. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

Also, consider using [getFilteredItemElements](https://isotope.metafizzy.co/methods.html#getfiltereditemelements)
