### ISSUE TITLE
When page is loaded, already show selected filter

### ISSUE THREAD

**Issue by bielekas** [metafizzy/isotope#1277]
Hi. I want to show a pre-selected filter when page is loaded. What am I doing wrong?
`
   /**
    *
    * filter isotopes
    *
    */

    $( 'body' ).on( 'click touchstart', 'section.gallery .gallery-filters .filter', function( event ) {

        event.preventDefault();

        var isotope = $( this ).parent().parent();
        var isotopeID = isotope.data( 'isotope-id' );
        var filterValue = $( this ).data( 'filter' );

        martanianLuxuryApartmentsIsotopes[isotopeID].isotope({ filter: filterValue });

        isotope.find( '.gallery-filters' ).children( '.filter' ).removeClass( 'filter-active' );
        $( this ).addClass( 'filter-active' );
		
                //SHOW THE SELECTED FILTER
		isotope({
		itemSelector: '.filter',
		filter: '.gallery-filter-building'
		});

        isotope.find( '.gallery-single-image' ).removeClass( 'isotope-element-visible' );
        var filteredElements = martanianLuxuryApartmentsIsotopes[isotopeID].isotope( 'getFilteredItemElements' );
        for( var i = 0; i < filteredElements.length; i++ ) {

            var filteredElement = $( filteredElements[i] );
            filteredElement.addClass( 'isotope-element-visible' );

        };

    });
`

**Comment by desandro** [comment]
When you initialize Isotope, set an initial `filter` option

``` js
var $grid = $('.grid').isotope({
  itemSelector: '.grid-item',
  filter: '.filter-selector',
})
```

See demo https://codepen.io/desandro/pen/03963c5c79fd8696fa645ccf1335e96f/
