### ISSUE TITLE
Keeping the selection when coming back

### ISSUE THREAD

**Issue by antoniomatt** [metafizzy/isotope#1279]
Hello,

I'm using Isotope with cumulative filters, like this: 

```
var $grid = $('.grid').isotope({
    itemSelector: '.related',
    transitionDuration: '0.24s',
    hiddenStyle: {
      opacity: 0
    },
    visibleStyle: {
      opacity: 1
    }
  });

  var filters = [];

  // filter functions
  var $container = $('.grid');

  $('.filtratge').click(function(){
    $(this).toggleClass('is-checked');
    var isChecked = $(this).hasClass('is-checked');
    var filter = $(this).attr('data-filter');
    if ( isChecked ) {
      addFilter( filter );
    } else {
      removeFilter( filter );
    }
    $container.isotope({ filter: filters.join(',') });
  });
  function addFilter( filter ) {
  if ( filters.indexOf( filter ) == -1 ) {
    filters.push( filter );
  }
}

function removeFilter( filter ) {
  var index = filters.indexOf( filter);
  if ( index != -1 ) {
    filters.splice( index, 1 );
  }
}
```

There are 4 categories, and we can click more than one button and it will be added to the selection. It works just fine. The only problem is that Google Chrome doesn't store your selection when you visit one item and come back. Safari and Firefox do, they store the state of the page in the cache and when you press the "Back" button, you're back with your previous selection, but unfortunately Chrome doesn't. I've discovered that filtering via the URL hash could work, but even though I've seen examples of multiple filters and URL hash, that's not exactly what I'm trying to achieve here. 

Is there any way to do that? Or otherwise, to make Chrome "remember" the state of the filters. 

Thanks in advance!

**Comment by desandro** [comment]
Thanks for reporting this issue. What kind of UI are you using for  `.filtratge`?  Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
