### ISSUE TITLE
Disable filters that will not generate results

### ISSUE THREAD

**Issue by aurelienborst** [metafizzy/isotope#1280]
I'm working with Isotope 2 and I wandering how I make a smart filter.
The goal is to disable filter that will generate empty results. I think this function is pretty mandatory and I didn't see any solutions or discussions about this.
But who want to see empty results ?

I begin to make something but I'm stuck : https://codepen.io/share-a-dream/pen/dRXgyW

**Comment by desandro** [comment]
Thanks for reporting this issue. This issue has come up before, but not often. People use various UI and behaviors with Isotope so there is no one way to do this.

How are you stuck?
