### ISSUE TITLE
How do I add a reset filter button and no results found message to combined filter with search and hash url

### ISSUE THREAD

**Issue by bhines01** [metafizzy/isotope#1281]
**Test case:** http://codepen.io/desandro/pen/mEinp

Here is the code that I am trying to update. Any help is appreciated.

createItems();
var qsRegex;

var $quicksearch = $('.quicksearch').keyup( debounce( function() {
	qsRegex = new RegExp( $quicksearch.val(), 'gi' );
	$grid.isotope();
}));

// debounce so filtering doesn't happen every millisecond
function debounce( fn, threshold ) {
	var timeout;
	return function debounced() {
		if ( timeout ) {
			clearTimeout( timeout );
		}
		function delayed() {
			fn();
			timeout = null;
		}
		timeout = setTimeout( delayed, threshold || 100 );
	}
}

//init Isotope
var $grid = $('.grid').isotope({
	itemSelector: '.item',
	getSortData: {
		name: '.name'
	}
});

//store filter for each group
var filters = [];

//change is-checked class on buttons
$('.filters').on( 'click', 'button', function( event ) {
	
	var $target = $( event.currentTarget );
	$target.toggleClass('is-checked');
	var isChecked = $target.hasClass('is-checked');
	var buttonfilter = $target.attr('data-filter');
	
	if ( isChecked ) {
	 addFilter( buttonfilter );
	 
	} else {
	 removeFilter( buttonfilter );
	}
	
	//filter isotope
	$grid.isotope();
	location.hash = 'filter=' + encodeURIComponent( filters.join(',') );

	
});
function onHashchange() {
	var hashFilter = getHashFilter();

	// filter isotope
	$grid.isotope({
		filter: function() {
			var $this = $(this);
			var searchResult = qsRegex ? $this.text().match( qsRegex ) : true;			        
			var buttonResult = hashFilter ? $this.is( hashFilter ) : true;
			
			return searchResult && buttonResult;
		}
	}); 
}
	
$(window).on( 'hashchange', onHashchange );

//init Isotope with hash filter
onHashchange();

var hashFilter = getHashFilter();
if ( hashFilter ) {
	  var filters = hashFilter.split(',');
	  filters.forEach( function( filter ) {
	    var $checkbox = $(".button").filter('[data-filter="' + filter + '"]');
	    //console.log(filter)
	    $checkbox.addClass( 'is-checked' );
	  });
}

function getHashFilter() {
	var hash = location.hash;
		  // get filter=filterName
	var matches = location.hash.match( /filter=([^&]+)/i );
		  
	if ( !matches ) {
		return '';
	}
		
	return decodeURIComponent( matches[1] );
}

function addFilter( filter ) {
	if ( filters.indexOf( filter ) == -1 ) {
		filters.push( filter );
	}
}

function removeFilter( filter ) {
	var index = filters.indexOf( filter);
	if ( index != -1 ) {
		filters.splice( index, 1 );
	}
}

function createItems(){
	var jsonData = "/apps/villanova/components/content/programs/programs.json";
	var $content;
	$.getJSON(jsonData, function(data){
		
		$.each( data.Programs, function( key, val ) {
			
			var name = val.name;
			var description = val.description;
			var tags = val.tags;
			var tagsArray = tags.split(",");
			var tagsJoined = tagsArray.join(" ");
			console.log(key);
			
			$content = $("<div class=\'panel panel-default item " + tagsJoined + "\'><div class=\"name panel-heading\">" + name + "</div><div class=\"panel-body\">"+description+"</div></div>");
			$content.find(".panel-body").append("<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\".modal_"+key+"\">Large modal</button>");
			$(".modal-container").append("<div class=\"modal fade modal_"+key+"\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\"><div class=\"modal-dialog modal-lg\" role=\"document\"><div class=\"modal-content\">"+description+"</div></div></div>")
			$grid.isotope( 'insert', $content );
			$grid.isotope({ sortBy: "name" });
		});
	});
}

**Comment by bhines01** [comment]
the code: $grid.data('isotope').filteredItems.length seems to be quirky with the toggle state filters, any ideas?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by bhines01** [comment]
Here is the test case: https://codepen.io/bryguy25/pen/yXVeWR

**Comment by bhines01** [comment]
I'm having trouble adding a "No Results Found" message to the filter buttons and search. I'm also having trouble adding a reset filter button. No worries, this is a good product, I'm just not the best programmer :)

**Comment by bhines01** [comment]
I added:

$grid.on( 'arrangeComplete', function( event, filteredItems ) {
	  //console.log( filteredItems.length );
	  if(filteredItems.length == 0){
		  $(".no-results").show();
	  }else{
		  $(".no-results").hide();
	  }
});

This seems to be working for the no results message. Please let me know if there is a better way.

**Comment by bhines01** [comment]
The clear filters event seems to leave an empty string in the filters array and I dont know how to clear the array completely. 

$(".clear").click(function(){
	filters=[];
	$grid.isotope({
		filter: "*"
	});
})

**Comment by desandro** [comment]
Thanks for the test case.

Looking at this, my initial reaction is that there's so much going on: 

+ URL hash
+ quick search
+ combination filters

With each additional feature, the complexity between them increases exponentially. Do your users really need all these? Maybe Isotope isn't the right solution here.

That said, to your question, yes, the 'no results' behavior works just fine. 

As for clearing, I'm not exactly sure how you're using all these filters together. I'll leave that up to you.

Finally, I'm sorry but I can't offer personal support. My time on GitHub issues is limited and I don't have the availability to personally work on others implementations.

**Comment by bhines01** [comment]
I'm using the toggle button filter with hash url. The code that I have in my example is all code from your examples. The clearing works but there is a bug when you try to click on other filters after the clearing.

**Comment by bhines01** [comment]
I got the clear button and no results message to display: https://codepen.io/bryguy25/pen/yXVeWR

Please let me know if you notice any issues with this solution

**Comment by desandro** [comment]
Nice work!

**Comment by bhines01** [comment]
Thanks, you too!
