### ISSUE TITLE
isotope with php mysql

### ISSUE THREAD

**Issue by nevonevo** [metafizzy/isotope#1283]
hi there. thanks for the great plugin for filtering datas. But i searched on internet for using this plugin with php i couln't find results. Do you have any example for using isotope multifilter function with php mysql?

**Comment by desandro** [comment]
Isotope is built for the front-end: HTML, CSS, JavaScript. That means it works with data already rendered on a page by your backend. You'll have to create or provide an API to interface with your backend with PHP and MySQL
