### ISSUE TITLE
undefined is not an object (evaluating 'iso.appended')

### ISSUE THREAD

**Issue by illabo** [metafizzy/isotope#1284]
Hello David!

Sorry for bother you.

Your libraries are really great!
I've tried tinkering with your code snippets in CodePen and made up what I need for my prospected web page. Unfortunately when I run the code locally everything ends up with this error (see header).

Code fails in Safari and Chrome same way. It fails when served from template with a Golang app and it also fails when I merely open html file.

Here is CodePen [example](https://codepen.io/anon/pen/owZNXB) which works perfectly.

And here is the code I can't grasp why it is faily:

```
<!DOCTYPE html>
  <head>
    <link rel="stylesheet" type="text/css" href="http://localhost:9000/assets/css/gal.css">
    <script src="http://localhost:9000/assets/js/jquery-3.2.1.min.js"></script>
    <script src="http://localhost:9000/assets/js/isotope.pkgd.min.js"></script>
    <script src="http://localhost:9000/assets/js/imagesloaded.pkgd.min.js"></script>
    <script src="http://localhost:9000/assets/js/gal.js"></script>
 </head>
<body>

    <div class="grid"></div>
    
</body>
```

```
body {
  font-family: sans-serif;
}

.grid {
  max-width: 100%;
}

.grid-item {
  width: 300px;
}

.grid-item img {
  display: block;
  width: 100%;
}

.grid-item.gigante {
  width: 900px;
}
```

```
var $grid = $(".grid").isotope({
  itemSelector: ".grid-item",

  masonry: {
    columnWidth: 300
  }
});

$(function() {
  var $items = getItems();
  $grid.isotopeImagesReveal($items);
});

$.fn.isotopeImagesReveal = function($items) {
  var iso = $grid.data("isotope");
  var itemSelector = ".grid-item";
  // hide by default
  $items.hide();
  // append to container
  this.append( $items );
  $items.imagesLoaded().progress(function(imgLoad, image) {
    // get item
    // image is imagesLoaded class, not <img>, <img> is image.img
    var $item = $(image.img).parents(itemSelector);
    // un-hide item
    $item.show();
    // isotope does its thing
    iso.appended( $item );
  });

  return this;
};

function randomInt( min, max ) {
  return Math.floor( Math.random() * max + min );
}

function getItem() {
  var width = randomInt( 150, 400 );
  var height = randomInt( 150, 250 );
  var item = '<div class="grid-item">'+
    '<img src="https://lorempixel.com/' + 
      width + '/' + height + '/nature" /></div>';
  return item;
}

function getItems() {
  var items = '';
  for ( var i=0; i < 12; i++ ) {
    items += getItem();
  }
  // return jQuery object
  return $( items );
}

$grid.on("click", ".grid-item", function() {
  // change size of item by toggling gigante class
  $(this).toggleClass("gigante");
  $grid.isotope("layout");
});
```
Thank you in advance.

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry to hear you're having trouble. Without a reduced test case demonstrating the issue, there's no way for me to debug what's actually going.

From the error, the problem is that the `$item` used with `appended` is bad: either undefined or an empty object with no element.

Looking at the code from the CodePen, this may be caused by `getItems` which is returning the HTML of `$('#imgitm').html()`. I'd recommend trying this code:

``` js
function getItems() {
  // return jQuery object
  return $('#imgitm').find('.grid-item');
}
```

see demo https://codepen.io/desandro/pen/43d383f64b54a5d7397a553d0cc97929/

**Comment by illabo** [comment]
Thanks a lot for reply!

Unfortunately thats return the same error.

**Comment by desandro** [comment]
If you can put together a **reduced test case** demonstrating the issue, I can better debug it.

**Comment by illabo** [comment]
As far as I can see CodePen doesn't allow to run a script right from html pane. But it is ok on JSBin and some other services so I made up example there. If it's needed I'm ready to spin up a VPS instance with demonstration too.
[This example won't work](http://jsbin.com/bohipiqoru/edit?html,css,console,output)
I've found that if the script called after the last `<div>...</div>` does what it suppose to.
Presumably it is my mistake and 
```
$(function() {var $items = getItems();
$grid.isotopeImagesReveal($items);
});
``` 
fires up as soon as it is loaded prior the images, so it leads to undefined `$item` and all vars containing it.

**Comment by desandro** [comment]
Thanks for that. It looks like the issue was a race condition. Because your JS appears before the HTML, we need to wait until `document.ready` so the DOM is ready to be manipulated. This means moving all the code that deals with `$grid` into `$(function() {...})`.

See demo: http://jsbin.com/vutexohogu/edit?html,output

**Comment by illabo** [comment]
Thanks! Thats definitely is a solution!
Sorry for issue report, I've should double-check everything prior opening an issue.
