### ISSUE TITLE
Using a function as a filter, what is the first argument?

### ISSUE THREAD

**Issue by Pustur** [metafizzy/isotope#1286]
```
$grid.isotope({
    filter: function(arg1, element) {
        console.log(arg1, element);
        // arg1 is always 0
        // element is the element being evaluated
    }
})
```

What is the first argument? I thought it was the index of the element being evaluated but it's always 0.

Thanks in advance.

**Comment by desandro** [comment]
With jQuery, Isotope uses [jQuery `.is()`method](http://api.jquery.com/is/#is-function). See [isotope.js](https://github.com/metafizzy/isotope/blob/v3.0.4/js/isotope.js#L278).

``` js
jQuery( item.element ).is( filter )
```

Indeed that first argument is the index of the element in the jQuery object, but Isotope calls this line on individual elements so the index is always 0.

**Comment by Pustur** [comment]
Thanks for the explanation.

> Isotope calls this line on individual elements so the index is always 0.

Shouldn't this behaviour be changed? It's pretty useless to have an index always set to 0.

**Comment by desandro** [comment]
It's done this way so filtering can done with jQuery or vanilla JS. It's a tradeoff
