### ISSUE TITLE
Search field integration with inclusive and exclusive filters

### ISSUE THREAD

**Issue by moodXL** [metafizzy/isotope#1287]
Test case : https://codepen.io/anon/pen/LLzQZO

Hello,
I'm trying to integrate a search field (like the one from https://codepen.io/desandro/pen/Jfbpc) in your example of inclusive/exclusive filters (https://codepen.io/desandro/pen/iBkzF).

My issue is : the first search works well, but when I activate any filter, the search functionality is disabled. 
The issue obviously comes from the way i try to integrate the search box, but I'm not really a javascript developer...
Does anybody already did this ?

Thanks a lot ! :)
(And sorry for the mistakes, this is written by a frenchie...) 

PS : the work you did/do on this plugin is really impressive. It seems like we can do whatever we want kinda easily. Well done !

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. I do have an example that combines button filters with a search input filter: https://codepen.io/desandro/pen/mCdbD

I'll leave it to you to work this feature in with the others.

At this point, I have to advise that you may want to scale back how much UI you are using with Isotope. Yes, you can combine these features together, but I worry about how much complexity and code is required to do so. Your users may not need all these features together.
