### ISSUE TITLE
Layout with Jets.js search

### ISSUE THREAD

**Issue by Brendan-McIntosh** [metafizzy/isotope#1289]
Hello everyone,

I have a small issue, I need to re layout items after using jets js

`var jets = new Jets({
    searchTag: '#jetsSearch',
    contentTag: '#jetsContent'
  });`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by Brendan-McIntosh** [comment]
I'm using this to search https://jets.js.org/?utm_source=CSS-Weekly&utm_campaign=Issue-180&utm_medium=email

**Comment by desandro** [comment]
Looking at that documentation page, Looks like you can use `didSearch` callback function in your options

``` js
var jets = new Jets({
  searchTag: '#jetsSearch',
  contentTag: '#jetsContent'
  didSearch: function() {
    iso.layout()
  },
});
```

**Comment by Brendan-McIntosh** [comment]
Thanks,

Console say "unexpected Identifier"

didSearch: function() {
    iso.layout()

**Comment by desandro** [comment]
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues). Without a reduced test case I cannot debug your issue.

**Comment by Brendan-McIntosh** [comment]
https://codepen.io/BrendanMcintosh/pen/XgBygQ

**Comment by desandro** [comment]
See demo https://codepen.io/desandro/pen/6b343df21e6e3d451930ed5a9253ccd1/

``` js
var $grid = $('.grid').isotope({
  itemSelector: '.grid-item',
  masonry: {
    columnWidth: 100
  }
});

var jets = new Jets({
  searchTag: '#jetsSearch',
  contentTag: '#jetsContent',
  didSearch: function() {
    $grid.isotope('layout');
  },
});
```

**Comment by Brendan-McIntosh** [comment]
Nice one! thanks desandro
