### ISSUE TITLE
Issue in layout

### ISSUE THREAD

**Issue by xperiafan13-rom** [metafizzy/isotope#1290]
Issue in layout
I test without div class for filter elements and all works good but with the class....
https://drive.google.com/open?id=0B3-d1qBwE5oRYlhYZ0NMTVpLSlU

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
