### ISSUE TITLE
Problem on filtering when page load first time.

### ISSUE THREAD

**Issue by Ceyar** [metafizzy/isotope#1292]
Hello,

here is the [code pen](https://codepen.io/anon/pen/XgGmLz) test. 

1. I'm trying to apply to filter the "dietetique" class when page is loaded instead of displaying all my items. I've tried but my actual code didn't work.

2. When I filter by selecting an option in my select box, I want that a specific item come first like my sub-title "Responsable diététique"?

I hope you'll understand what I mean. 

Thank you in advance.

Daniel

**Comment by desandro** [comment]
Thanks for reporting this issue.

For item 1, you can resolve this by setting `filterValue` initially. See demo https://codepen.io/desandro/pen/be588779c7ac103d5dcbf49907a810b2

For item 2, you can re-sort items with a [sort function](https://isotope.metafizzy.co/sorting.html#getsortdata-functions). You'll need some way to signify that certain items should have precedence.
