### ISSUE TITLE
Connect buttons to categories without classes but with casses

### ISSUE THREAD

**Issue by LauraKerkhofs** [metafizzy/isotope#1293]
want to add some js to my code to let the buttons work with the Isotope.js filters. I think that the buttons could work with the js code that looks at the switch casses and so filter the tattoos.
Or if you have an other way, go for it!
Can anyone help me out with the how of it al?

https://we.tl/vzY0YddzX3

**Test case:** http://codepen.io/desandro/pen/mEinp

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. I appreciate that you're providing a download link for your project, but I'm sorry this will not be a sufficient reduced test case. Can you try forking one of the demos from the docs on CodePen instead?

**Comment by LauraKerkhofs** [comment]
It works now!
