### ISSUE TITLE
Isotope not Respecting Bootstrap cols on 4k Monitor

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [metafizzy/isotope#1294]
Hey, I have a weird issue that only affects my 4k monitor. Basically, the grid loads with 3 items across (col-md-4 * 3) but as soon as Isotope kicks in it switches to two columns leaving one column blank. Here's my code:

$('#grid').isotope({
      itemSelector: '.grid-item',
      percentPosition: true,
      layoutMode: 'masonry',
      masonry: {
        columnWidth: '#grid > article:first-of-type'
      }
    });

An example is at https://dev.thebestsites.com at the bottom. Any idea why this is happening on one computer and not another? I'm using the latest Chrome version.

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. I am unable to reproduce the bug on my side. It sounds like a pixel-rounding error. Have you looked at the Bootstrap documentation for Isotope? https://isotope.metafizzy.co/extras.html#bootstrap

**Comment by TimeTravelersHackedMe** [comment]
I'm also having issues with the initial load on mobile devices.. like there are overlapping tiles... Can you see anything wrong with my implementation

**Comment by desandro** [comment]
Sorry, but I won't be able to debug this issue with your production site. If you can produce a **reduced test case** demonstrating the overlapping problem I can take a look. ee [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by TimeTravelersHackedMe** [comment]
here we go: https://codepen.io/blzalewski/pen/xLxNZE

Here's a screenshot of them working properly in a VM on Chrome and not working on my 4k monitor: https://ibb.co/hR7kfQ

I'm totally stumped!

**Comment by Jyotsna-Singh** [comment]
@TimeTravelersHackedMe 
Did you try adding `columnWidth: '.grid-sizer'` to the .js file &

    <div class="grid row">
    <div class="grid-sizer col-md-4">
    </div>
    <div class="grid-item col-md-4">
 </div>

And adding .grid-sizer class to the first grid column item.

I'm using masonry.js and its kinda similar

**Comment by TimeTravelersHackedMe** [comment]
I tried using the .grid-sizer and that didn't work :/

**Comment by desandro** [comment]
Thanks for the test case. I tried resizing it as wide as I can on my screen and I'm not able to reproduce the two column problem. Sorry, but I won't be able to resolve this one.

**Comment by Jyotsna-Singh** [comment]
@desandro & @TimeTravelersHackedMe - I too tried resizing it on an extended desktop screen but was not able to reproduce the problem.
