### ISSUE TITLE
Double transition jump bug when Object.prototype has been extended

### ISSUE THREAD

**Issue by cyco** [metafizzy/isotope#1296]
Hi,

i'm relying on a piece of software that has added an enumerable method to `Object.protoype`. 
This causes the same behavior as *"Items jump after transitioning position"*  as mentioned in the FAQ. 

When the transition completes [this check](https://github.com/metafizzy/isotope/blob/737e8329b06aea35ad27d58fc3aca8281b1da07f/dist/isotope.pkgd.js#L1151) fails because `_transition.ingProperties` has a member for the method that was added to Object.prototype. I believe adding a check for `hasOwnProperty` to [this loop](https://github.com/metafizzy/isotope/blob/737e8329b06aea35ad27d58fc3aca8281b1da07f/dist/isotope.pkgd.js#L1061) should resolve the issue. *(I can only find the relevant pieces of code in the packaged version, sorry about that.)*

**Test case:** https://codepen.io/anon/pen/YxKoRX

Extending Object.protoype in that way is usually a bad idea, but there's nothing i can do about it. If you don't want to clutter your loops with `hasOwnProperty` calls, i'd appreciate it if you'd add a line to the FAQ mentioning `Object.prototype` extension as another possible case for *"Items jump after transitioning position"*.

Edit: I'm using Safari 10.1.2 (12603.3.8) on Mac OS 10.12.6

**Comment by desandro** [comment]
Thanks for reporting this issue. This is the first time I've encountered a bug dealing with extending `Object.prototype` in my 7 years of supporting JS plugins. As you mention

> Extending Object.protoype in that way is usually a bad idea

I'm surprised Isotope isn't more broken with this kind of foundational change. Isotope & its dependent packages use the `for in` iteration often. The `hasOwnProperty` check would need to be added in 7 other places.

I appreciate you bringing this issue to my attention. But ultimately, I do not feel this case deserves a fix or documentation
