### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 't.getAttribute(r)') on Windows Safari 5.1 only

### ISSUE THREAD

**Issue by Codesesh** [metafizzy/isotope#1297]
On Windows Safari 5.1 we are getting:

`TypeError: 'undefined' is not a function (evaluating 't.getAttribute(r)') - http://trendskitchens.mintdemo.co.nz/mysite/javascript/third-party/isotope.pkgd.min.js?m=1500873655`

Any ideas on how to fix this? Works fine on all other browsers.

![gallery-image](https://user-images.githubusercontent.com/12224994/28605194-444d9734-7224-11e7-9449-a0465faeb58e.png)

Live link of website: http://trendskitchens.mintdemo.co.nz/gallery/

**Comment by desandro** [comment]
Thanks for reporting this issue. Isotope v3 does not support Safari 5. [Safari for Windows has been discontinued since 2012](https://en.wikipedia.org/wiki/Safari_(web_browser)), five years ago.

**Comment by Codesesh** [comment]
Ah makes sense. Cheers!
