### ISSUE TITLE
Events not fired on "inclusive filters" case 

### ISSUE THREAD

**Issue by ludovicpages** [metafizzy/isotope#1298]
Hi there.
I'm having a hard time firering events on the "inclusive filters" démo.
Doing a $grid.isotope({ filter: filterValue }); works fine when filterValue is a single value, but nothing is fired when filterValue is a coma separated list.

Any help ? 

**Test case:** https://codepen.io/anon/pen/xLVQVb

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm having trouble understanding what you're trying to achieve. What do you mean by "firing events"? From your demo, I see `onArrange` being triggered with combination filters
