### ISSUE TITLE
How to fit element-item according to width of bootstrap 3.

### ISSUE THREAD

**Issue by inquisitive-stha** [metafizzy/isotope#1299]
I am using this https://codepen.io/desandro/pen/nFrte. But, it seems like its width is not according to bootstrap column width as it is generating some extra space at some screen width. How can I make it as 3 columns in medium sized screen and 2 column in the small sized screen without experiencing issue as shown in attached image.
![issue](https://user-images.githubusercontent.com/16288854/28855430-690d63aa-775c-11e7-8516-65a336ae3726.png)

**Comment by desandro** [comment]
See [Isotope + Bootstrap](https://isotope.metafizzy.co/extras.html#bootstrap)
