### ISSUE TITLE
namespace collision with Isotope eCommerce

### ISSUE THREAD

**Issue by paulhaem** [metafizzy/isotope#1300]
Hey, firstly thanks for your awesome work!
I've used Isotope in a project, where I am using Contao CMS + Isotope Ecommerce extension. It happened, that Metafizzy Isotope had a collision with the internal Isotope JS. All internal functions starting with `Isotope.*` were not found, after adding Metafizzy Isotope to my project. I am quite not sure if this is a Isotope Ecommerce issue or a Metafizzy Isotope issue, so sorry in advance. Shouldn't there be some kind of scope to avoid such namespace issues?

I avoided the collision by replacing all occurrences of 'Isotope' in the Metafizzy Isotope JS with 'IsotopeFix' but I am not happy with this kind of solution. :-/

**Comment by desandro** [comment]
Thanks for reporting this issue. This the first I've heard of [Isotope ecommerce](https://isotopeecommerce.org/en/). Unfortunately, I think your solution, renaming `Isotope` might be the only one

**Comment by desandro** [comment]
No one else has chimed in so I'm closing this issue. 🐳
