### ISSUE TITLE
how to add anchor tag on url and get the same filter effect

### ISSUE THREAD

**Issue by NayeemNipun** [metafizzy/isotope#1301]
Hello,

I am using the isotop for a WordPress theme. And the plugin is works well.

But I need to add the filter anchor tag on url when user clicks on anchor tag and get the same filter effect.

Example- When user enter http://mywebsite.com/page/#gynecologie and get the filter #gynecologie on page with filter effect.

This is kinda urgent.

Thanks.

**Comment by desandro** [comment]
See [URL hash documentation](https://isotope.metafizzy.co/filtering.html#url-hash)
