### ISSUE TITLE
Sorting not working with No Layout mode

### ISSUE THREAD

**Issue by sifur** [metafizzy/isotope#1302]
I need to use isotope in no layoutMode for sorting only. But sorting isn't working with no layoutMode.
**Test case:** https://codepen.io/anon/pen/LjjGoo

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. The "no layout mode" code is only designed to work for filtering. Sorting is handled by the layout mode itself. Without a layout mode, sorting will not work. Sorry, I will not be able to resolve this one.
