### ISSUE TITLE
Are these Themeforest themes in violation of Isotope's license?

### ISSUE THREAD

**Issue by abstratt** [metafizzy/isotope#1303]
Are hundreds of Themeforest themes in violation of Isotope's license?

Themes tagged isotope: https://themeforest.net/tags/isotope (435)
Themes tagged GPL: https://themeforest.net/tags/gpl (22)
Themes tagged isotope *and* GPL: https://themeforest.net/tags/gpl,isotope (NONE)

Or did all of those themes get a commercial license for Isotope?

I ask because I bought a theme that was not GPL, and included Isotope, which I suspect they are not entitled to.

**Comment by abstratt** [comment]
Also, if a template vendor tells a customer they have a commercial license for Isotope:

1. Am I, as a template customer, automatically granted a license that allows me to include Isotope when I distribute or deploy my applications based on that template?
2. Do n'yI need some sort of proof that I have been granted said license?

**Comment by desandro** [comment]
Hello! Thanks for posting these questions.

Isotope is licensed GPL. So you can either release a theme with Isotope as GPL, or purchase a commercial license and release a closed-source theme.

> did all of those themes get a commercial license for Isotope?

My hope is that those themes tagged with Isotope have been released by authors who have purchased a commercial license.

> Am I, as a template customer, automatically granted a license that allows me to include Isotope when I distribute or deploy my applications based on that template?

Yes. You may use themes with Isotope without purchasing a license for yourself. So long as you are not creating a new commercial product with themes.

> Don't I need some sort of proof that I have been granted said license?

There is no registration process with Metafizzy licenses. I prefer to keep license usage simple and straightforward. I rely on the good will of users and customers. I could establish some sort of registration process, but I feel it would not be worth the effort to track down & pester incorrect usage.

**Comment by abstratt** [comment]
> Yes. You may use themes with Isotope without purchasing a license for yourself. So long as you are not creating a new commercial product with themes.

I purchased a closed-source theme that allows me to include the template assets in a commercial product. Turns out one of the assets is Isotope. I asked the template seller about whether they had purchased a commecrial license that gave them the right to redistribute Isotope in their closed-source template, and they answered "yes", and from what you answered above, all I have to go by is their word, they have nothing to show for it.

> There is no registration process with Metafizzy licenses. I prefer to keep license usage simple and straightforward. I rely on the good will of users and customers. I could establish some sort of registration process, but I feel it would not be worth the effort to track down & pester incorrect usage.

I appreciate your preference for simplicity. However, as an indirect/downstream user, I have nothing to protect myself from unwillingly infringing Isotope's license, and that is unsettling. It is cool that you are laid back about enforcing your license now, but that could change in the future (say, if you changed your mind, or if someone else bought Isotope from you).

One solution may be a simple license file that people paying for Isotope get from you (maybe everybody gets it, but only applies to those that purchased the commercial license) and can pass on to their customers, were you lay out the rights for your customers, and their customers' customers, including redistribution.

I know this stuff is boring, but for people like me trying to do the right thing, and protect themselves from the possibility of a future litigation, acquiring a product that contains Isotope is currently risky business.

**Comment by abstratt** [comment]
I was reading Metafizzy commercial license now (sorry, should have done that sooner). 

Prohibited Uses
Your Application must have substantially different functionality than, and must not compete directly with, the Software.

You cannot create something very similar to Isotope, like a super-Isotope. Make something unique.

You may not distribute the Software or Modifications except as included within Your Application.

If You produce an Application for a customer, You are responsible for ensuring that your customer does not make use of the Software except with Applications licensed herein.

Do not re-package Isotope unless it’s part of your Application.

Likewise, your customer should be using Isotope as part of your Application.

> 4.4 Your Application must not enable End Users to produce separate applications that incorporate the Software or Modifications. For example, if Your Application is a development toolkit or library, an application builder, a website builder that can be used to incorporate the Software into a new Application, You must obtain a separate OEM license from Metafizzy.

Is this saying that template providers should in fact be using an OEM license, as templates are in fact libraries?

**Comment by desandro** [comment]
> Is this saying that template providers should in fact be using an OEM license, as templates are in fact libraries?

OEM License is for website-builder applications like Squarespace or Wix. If you are creating a product that produces websites, and those websites include Isotope. Then you should purchase an OEM License to cover your use case.

Template authors do allow end users to produce their own websites, but their product does not produce multiple kinds of websites like Squarespace does. I realize this is a thin distinction. It's hard to articulate in legalese.

> One solution may be a simple license file that people paying for Isotope get from you (maybe everybody gets it, but only applies to those that purchased the commercial license) and can pass on to their customers, where you lay out the rights for your customers, and their customers' customers, including redistribution.

Yeah, that could work. But then I would be adding another complication to using Metafizzy libraries. I'm already asking people to pay for something, in market where nearly all other solutions are free. Adding these kind of requirements may improve the license usage, but I am concerned they would hurt the sales.

That is perhaps the biggest challenge Metafizzy faces. I'm trying to build a business on a typically free product. Metafizzy libraries are already at a disadvantage. I'm open to other ideas, but I'm skeptical that the license/open-use balance can be improved.
