### ISSUE TITLE
First load gap issue

### ISSUE THREAD

**Issue by satrya** [metafizzy/isotope#1305]
Hi,
I am a bit frustrated with this issue. Here's the image when the first load

![1](https://user-images.githubusercontent.com/891643/29603080-f56101fc-880c-11e7-9bbb-9b2cab99051b.png)

After I clicked the filter, the gap disappears

![2](https://user-images.githubusercontent.com/891643/29603100-0be2e9ae-880d-11e7-8954-447821e33b7b.png)

The code

```
// Projects grid
var $grid    = $( '.project-item' ),
    $filters = $( '.project-filters' );

$grid.imagesLoaded( function () {
	$grid.isotope({
		layoutMode: 'fitRows',
		itemSelector: '.entry',
	});
});
$filters.on( 'click', 'a', function(e) {
	e.preventDefault();
	var filterValue = $( this ).attr( 'data-filter' );
	$grid.isotope({
		filter: filterValue
	});
});
// Dynamic class for filter
$filters.each( function( i, projectFilters ) {
	var $projectFilters = $( projectFilters );
	$projectFilters.on( 'click', 'a', function() {
		$projectFilters.find( '.filter-active' ).removeClass( 'filter-active' );
		$( this ).addClass( 'filter-active' );
	});
});
```

I really need help, thank you :)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
