### ISSUE TITLE
Module not found: Error: Can't resolve 'masonry/masonry' 

### ISSUE THREAD

**Issue by funcphp** [metafizzy/isotope#1306]
this is my usual package.json

    "isotope-layout": "^3.0.4",

I think it might be related to #1129 

I use it this way to solve the problem

package.json

    "isotope-layout": "git://github.com/metafizzy/isotope.git#master",

but I can not use isotope with verison in package.json

Error:

    ERROR in ./node_modules/isotope-layout/js/layout-modes/masonry.js
    Module not found: Error: Can't resolve 'masonry/masonry' in '....../node_modules/isotope-layout/js/layout-modes'
     @ ./node_modules/isotope-layout/js/layout-modes/masonry.js 12:4-16:15
     @ ./node_modules/isotope-layout/js/isotope.js
     @ ./app/init.js
     @ ./app/main.js
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./app/main.js

**Comment by desandro** [comment]
Thanks for reporting this issue. Yes, this sounds exactly like #1129. Closing here as a duplicate.
