### ISSUE TITLE
Isotope within Wordpress filtering/sorting

### ISSUE THREAD

**Issue by Mellis84** [metafizzy/isotope#1307]
Hi Guys,

I was just wondering what the best way to go would be to sort and filter my posts / videos in Wordpress with Isotope, I have set up a custom post type "Videos" with a custom Taxonomy "Video Categories", I would like to use the filtering when clicking on a category link / button but would like to have sorting buttons also, which would be eg. Chapter 1, Chapter 2 etc.

I'm just trying to think what the best way is to get the sorting set up? I was thinking of using Tags, or maybe Advanced Custom Fields using the radio fields to attach a video to a chapter, I'm not sure.

Any suggestions would be awesome thank you.

**Comment by desandro** [comment]
Hi! Thanks for reporting this issue. I don't too much expertise with WordPress, so I can't off the best advice here.

Isotope is designed to be flexible, so you can use it with radio inputs, or buttons, or a select list. I recommend trying out one of your approaches and see what works best for you. Please follow up to let others know for future reference.
