### ISSUE TITLE
Event arrangeBegin or onfilter

### ISSUE THREAD

**Issue by thomasdebruin** [metafizzy/isotope#1309]
I want to do some custom animation (css) during filtering (fade image opacity to 0 an reveal a coloured background) and reveal the image again when filtering is complete.
This works by:
- add a class when filter button is pressed
- remove the class on 'arrangeComplete'

But when you press the same button twice there is nothing to arrange,so the arrangeComplete event is never triggered. I can think of numerous crufty solutions, but looking for a more solid way.

What I need is something like a 'arrangeStart' or 'filterStart' event so I can make this rocksolid, any thought on this? Or am I missing something obvious?

**Comment by desandro** [comment]
Thanks for reporting this issue. This kind of behavior sounds like it can be achieved with your own JS, without the need for a special event. if you have a **reduced test case** I could take a look at how you're working.
