### ISSUE TITLE
fitRows is being ignored

### ISSUE THREAD

**Issue by ks3006** [metafizzy/isotope#1310]
Hi there,

I'm experiencing a weird issue. First: I'm using Wordpress with the Woffice theme. 
For the news/blog section i've selected masonary layout (three column). I requested a code to past in the "custom code" section of the theme in order to horizantally sort the news items. Some months back I received this code:

jQuery("body.page-template-blog  .masonry-layout, body.home .masonry-layout").isotope({
                        // options
                        itemSelector: '.box.blog-item',
                        layoutMode: 'fitRows'
                    });

With the last update it stopped working. When the page loads, it does get arranged as it was with this workaround. But, when the page is completely working it goes back to the original masonary layout. It looks like this custom code is being loaded and lateron being ignored? 

Does someone have a clue how I can fix this?

Many thanks!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by ks3006** [comment]
Hi Desandro,

Please find an front-end example here:
https://youtu.be/P5gScIpzIak 

It should be permanently displayed as on 0:03 but at 0:06 it's back to the original formatting.

**Comment by desandro** [comment]
I appreciate the video, but without a live URL for a **reduced test case** I cannot debug your issue.
