### ISSUE TITLE
Overlapping tiles on iOS (but not on OS X Safari in "responsive mode")

### ISSUE THREAD

**Issue by ericfynnmaier** [metafizzy/isotope#1315]
When I test my isotope grid in safaris "responsive mode" everything works like a charm- but if I try it on an iPhone I get overlapping tiles- and the grid overflows the viewport.

I already added the _Web Font Loader_ and _imagesloaded_ but the problem is still there.

~~It is difficult to simplify the code, but if necessary I will do my best.~~

You can find the simplified code here: https://codepen.io/ericgerhardy/pen/veYzrV/
Is there any known issue with iOS?

The height of the tiles is given in vh and the width in %. 

Thanks in advance for your support! 

I attached some screenshots of the "desktop-mobile" and the mobile grid.

![bildschirmfoto-2017-09-12-um-22 31 08](https://user-images.githubusercontent.com/13310987/30347065-22951218-980b-11e7-995c-1b4dd21041e7.jpg)
![whatsapp-image-2017-09-12-at-22 32 37](https://user-images.githubusercontent.com/13310987/30347066-22b94c64-980b-11e7-90ec-171b0d29bd72.jpg)

**Comment by desandro** [comment]
I recommend triggering `layout` after imagesLoaded, font load, and add window load:


``` js
// init Isotope
var $grid = $('#grid').isotope({
    itemSelector: '.grid-item',
    layoutMode: 'packery',
    percentPosition: true,
    packery: {
        columnWidth: '.grid-sizer'
    }
});

function isotopeLayout() {
  $grid.isotope('layout');
}

$grid.imagesLoaded( isotopeLayout );

WebFont.load({
    google: {
      families: ['Lato:400,700,900']
    },
    active: isotopeLayout,
});

$( window ).load( isotopeLayout );
```
