### ISSUE TITLE
Filtering by multiple categories in data-atribute [w/ getSortData]

### ISSUE THREAD

**Issue by betodasilva** [metafizzy/isotope#1316]
Hey guys, 
I've tried to use the solution by @desandro on #1210 but I have some diferences

In my case, I have multiple properties set inside getSortData, wich one use this function to filter by category. 

However, I though it would be enough just to use sortBy: 'filter' (available in [docs](https://isotope.metafizzy.co/sorting.html#sortby)), when need to call this function, but it doesn't work. 

Could you help me with this one? 

Here's the [codepen](https://codepen.io/betodasilva/pen/LzZGEM) example.

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm having trouble understanding what you're trying to do. Are you trying to filter for multiple categories? If not, how do you want them to be sorted?

My original demo: https://codepen.io/desandro/pen/a807b00bb785cea30160aaa7c8e458ac

**Comment by betodasilva** [comment]
Oh well, I was doing all wrong!! 

Let me explain what happened and will update my example to show the expected result.

**Filter != sortBy**  

So, I was putting the filter inside getSortData, wich would never work. 

Here's the updated codepen.

https://codepen.io/betodasilva/pen/yzavOE?editors=1101

**Comment by desandro** [comment]
Thanks for following up!
