### ISSUE TITLE
Filtering doesn't work with Bootstrap 4

### ISSUE THREAD

**Issue by AysunSachir** [metafizzy/isotope#1318]
Hello,

I'm quite a beginner in Jquery, so obviously I'm doing something wrong, but I can't figure it out.
Here's my stripped down version, no CSS added, just HTML & JS.
https://codepen.io/AysunShack/full/rGMGPX

Any idea why this doesn't work? Not sure what else I'm supposed to insert in my JS section.
I'm trying to get a simple 4x2 grid.

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue and for providing a reduced test case.  Looks like you needed to fix your button click JS

``` js
// change is-checked class on buttons
var $buttonGroup = $('.button-group');
$buttonGroup.on( 'click', 'button', function( event ) {
  $buttonGroup.find('.is-checked').removeClass('is-checked');
  var $button = $( event.currentTarget );
  $button.addClass('is-checked');
  var filterValue = $button.attr('data-filter');
  $grid.isotope({ filter: filterValue });
});
```

See demo https://codepen.io/desandro/pen/00cd14b7c85f173192b26d4a7c7b433d/

I recommend reading [Fizzy School for lessons in JavaScript for jQuery newbies](http://fizzy.school).

**Comment by AysunSachir** [comment]
Thank you for the response. In the meantime I just ended up copy pasting the entire codepen work.
It's a bit counterintuitive though. The installation instructions on the mainpage are not complete, so to say.

Anyway, after I managed getting it work, some of the images overlap when loading the gallery for the first time. Then, after a reload all looks good. Do you know what might be the problem? (I know, stripped down testcase, but it would not make sense in this case though).
Here's a live link:
[www.ascenddev.com/work](url)

And here's an image showing what I mean:
http://snpy.in/Nri3H3

I'm using multiple .js files, concatenated in gulp:
 

>  'src/js/jquery.js',
>   'src/js/owl.carousel.js',
>   'src/js/scrollreveal.js',
>   'src/js/isotope.pkgd.js',
>   'src/js/lightbox.js',
>   'src/js/custom.js',
>   'src/js/bootstrap.js'

I do not want a free fix for my troubles, I just want to know if this has anything to do with isotope.

Thank you!

**Comment by desandro** [comment]
Use [imagesLoaded](https://isotope.metafizzy.co/layout.html#imagesloaded)
