### ISSUE TITLE
Convert checkboxes to buttons *Help Request*

### ISSUE THREAD

**Issue by geobzmm** [metafizzy/isotope#1320]
I'm using the Metafizzy Isotope to filter some data, specifically using the Combination Filters: https://codepen.io/desandro/pen/MebyMR

I want to change some checkboxes to buttons and also include new additional ones but I'm struggling to do so.  I've managed to remove the dynamically generated container and replaced it with a defined div so I can once completed fill this div with data drawn from a mysql database.

I've forked and simplified the codepen: https://codepen.io/anon/pen/PJmeLy

I've added two buttons with a new filter criteria and would like to include these alongside the checkboxes as filters.

Could you point me in the right direction to achieving this please, once I've got this sussed I'll be able to add it to my app which should then be on the way to being finished and I'll be hopping over to get a commercial licence before going live.

Thank you.

**Comment by desandro** [comment]
Rather than adding a different UI for the Paid filters, I recommend sticking with the same UI and using a checkbox. See demo https://codepen.io/desandro/pen/d0c8e7a582549aef6f71e283ce2f413f/

**Comment by geobzmm** [comment]
Thanks, that would make sense. If I decided to replace all the checkboxes with buttons then could you give me a rough idea of how to adjust the script to handle that instead? I've been trying to replace the checkboxes with buttons today and I keep breaking the jquery script. (my lack of jquery experience more than anything else).

**Comment by desandro** [comment]
Here you go https://codepen.io/desandro/pen/5d9a44fb52d745cfa24487e6c998cb9d

I recommend looking through [Fizzy School — Lessons in JavaScript for anyone writing jQuery](http://fizzy.school/)

**Comment by geobzmm** [comment]
Thank you David, really appreciated. I'll take a look through the Fizzy School lessons as well. I'll drop you a line once my project is completed so you can take a look at it. :)
