### ISSUE TITLE
Any recommendations for carousel for isotope layout?  I Need to be able to filter and carousel results on each filter.

### ISSUE THREAD

**Issue by pierrerocket** [metafizzy/isotope#1324]
Hello.  I was wondering if anybody can recommend the best way to achieve this?  I have an isotope packery layout, with filtering. I need to be able to filter and put the filter results in a carousel where there are only 2 rows of items in height.  If I refilter the carousel needs to take recarouselize the filtered results.

Any help would be much appreciated!

**Comment by desandro** [comment]
[Flickity is the best carousel there is](https://flickity.metafizzy.co/) 😘

**Comment by pierrerocket** [comment]
@desandro  
So I am supposed to come up with a way to spread out the isotope layout over several of the carousel slides

So for filtering and the carousel Im assuming I would need to destroy flickity when filtering isotope (on button click),  Have my js wrap every X items in a wrapper div for the flickity slides, then reinitialize flickity?

Sorry if this question is stupid, I'm fairly novice at JS.

**Comment by desandro** [comment]
> So I am supposed to come up with a way to spread out the isotope layout over several of the carousel slides

If you're trying to use Isotope filtering in a carousel, my recommendation is to not try this. I recommend using either Isotope, or a carousel. but using them together will only cause trouble for both layout libraries to work on top of one another.
