### ISSUE TITLE
Issue with multiple filtering

### ISSUE THREAD

**Issue by goranhc** [metafizzy/isotope#1325]
Hi, can you check what I'm missing here.

Combining these 3 filter group works well, but if I check more than one option in filter group it doesn't work. [https://jsfiddle.net/goranhc/zrLjuaLp/](https://jsfiddle.net/zrLjuaLp/)

**Comment by desandro** [comment]
Have you looked at [combination filters](https://isotope.metafizzy.co/filtering.html#combination-filters)?  Or inclusive combination filters? See [Extras](https://isotope.metafizzy.co/extras.html)
