### ISSUE TITLE
CSS Problem

### ISSUE THREAD

**Issue by ibenettaleb** [metafizzy/isotope#1329]
After i remove some stylesheet links it works, this my all stylesheet links  :

<img width="609" alt="2017-10-24_16-32-43" src="https://user-images.githubusercontent.com/28574987/31952579-d7243aa4-b8d8-11e7-8b0b-c400bfb2f36e.png">

How do i solve this problem ? : 

<img width="826" alt="2017-10-24_16-21-20" src="https://user-images.githubusercontent.com/28574987/31952405-6b19e30e-b8d8-11e7-8c41-56810c5b22bb.png">

<img width="844" alt="2017-10-24_16-23-51" src="https://user-images.githubusercontent.com/28574987/31952415-70113024-b8d8-11e7-930a-b92e350fe42f.png">

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
