### ISSUE TITLE
URL hash – vanilla js

### ISSUE THREAD

**Issue by triograf** [metafizzy/isotope#1330]
Hi everybody,

is there any chance to get a demo for »url hash« with plain javascript? The demo on CodePen uses jQuery. Unfortunately there’s a lot of hatred for this awsome library nowadays in the js-world. I tried myself but failed. :-(

Thanks in advance.
Daniel

**Comment by triograf** [comment]
O.K. Got it working. The only issue i am facing is the active class on the button when entering the site with the hash attached to the url. Any hints? 

Thanks.
Daniel


<pre>
function getHashFilter() {
	var hash = location.hash;
	var matches = location.hash.match(/filter=([^&]+)/i);
	var hashFilter = matches && matches[1];
	return hashFilter && decodeURIComponent(hashFilter);
}

var grid = document.querySelector(".employees__list");

var iso = new Isotope(grid, {
	itemSelector: ".employees__list-item",
	layoutMode: "fitRows",
	percentPosition: true,
	transitionDuration: 750,
	stagger: 30
});

var filtersElem = document.querySelector(".employees__filter");
filtersElem.addEventListener("click", function(event) {

	if (!matchesSelector(event.target, "button")) {
		return;
	}
	var filterAttr = event.target.getAttribute("data-filter");

	location.hash = "filter=" + encodeURIComponent(filterAttr);
});

var isIsotopeInit = false;

function onHashchange() {
	var hashFilter = getHashFilter();
	if (!hashFilter && isIsotopeInit) {
		return;
	}

	isIsotopeInit = true;

	if (hashFilter) {

		var buttonGroups = document.querySelectorAll(".employees__filter");
		for (var i = 0, len = buttonGroups.length; i < len; i++) {
			var buttonGroup = buttonGroups[i];
			radioButtonGroup(buttonGroup);
		}

		function radioButtonGroup(buttonGroup) {
			buttonGroup.addEventListener("click", function(event) {

				if (!matchesSelector(event.target, "button")) {
					return;
				}

				buttonGroup.querySelector(".employees__filter-trigger---active").classList.remove("employees__filter-trigger---active");
				event.target.classList.add("employees__filter-trigger---active");
			});
		}

		iso.arrange({
			filter: hashFilter
		});
	}
}

window.addEventListener("hashchange", onHashchange);
onHashchange();
</pre>

**Comment by desandro** [comment]
I've created the demo. See Pen https://codepen.io/desandro/pen/ooEZyj and debug view https://s.codepen.io/desandro/debug/ooEZyj#filter=.nonmetal

``` js
var grid = document.querySelector('.grid');
var iso;

function onHashchange() {
  var hashFilter = getHashFilter();
  if ( !hashFilter && iso ) {
    return;
  }
  if ( !iso ) {
    // init Isotope for first time
    iso = new Isotope( grid, {
      itemSelector: '.element-item',
      layoutMode: 'fitRows',
      filter: hashFilter || '',
    });
  } else {
    // just filter with hash
    iso.arrange({
      filter: hashFilter
    });
  }
  
  // set selected class on button
  if ( hashFilter ) {
    var checkedButton  = filterButtonGroup.querySelector('.is-checked');
    if ( checkedButton ) {
      checkedButton.classList.remove('is-checked');
    }
    filterButtonGroup.querySelector('[data-filter="' + hashFilter + '"]').classList.add('is-checked');
  }
}

window.addEventListener( 'hashchange', onHashchange );
// trigger event handler to init Isotope
onHashchange();


// bind filter button click
var filterButtonGroup = document.querySelector('.filter-button-group');
filterButtonGroup.addEventListener( 'click', function() {
  var filterAttr = event.target.getAttribute('data-filter');
  if ( !filterAttr ) {
    return;
  }
  location.hash = 'filter=' + encodeURIComponent( filterAttr );
});

function getHashFilter() {
  // get filter=filterName
  var matches = location.hash.match( /filter=([^&]+)/i );
  var hashFilter = matches && matches[1];
  return hashFilter && decodeURIComponent( hashFilter );
}
```

**Comment by triograf** [comment]
Hi David, thanks for the snippet. I ended up combining my snippet with the one you posted. Because the one you posted is not working in current versions (Quantum) of FireFox:

<pre>

var grid = document.querySelector('.employees__list');

var iso = new Isotope(grid, {
	itemSelector: '.employees__list-item',
	layoutMode: 'fitRows',
	percentPosition: true,
	transitionDuration: 750,
	stagger: 30
});

var filtersElem = document.querySelector('.employees__filter');
filtersElem.addEventListener('click', function(event) {
	var filterAttr = event.target.getAttribute('data-filter');

	if (!filterAttr) {
		return;
	}

	location.hash = 'filter=' + encodeURIComponent(filterAttr);
});

var isIsotopeInit = false;

function onHashchange() {
	var hashFilter = getHashFilter();
	if (!hashFilter && isIsotopeInit) {
		return;
	}

	isIsotopeInit = true;

	if (hashFilter) {

		var checkedButton = filtersElem.querySelector('.employees__filter-trigger---active');
		if (checkedButton) {
			checkedButton.classList.remove('employees__filter-trigger---active');
		}
		filtersElem.querySelector('[data-filter="' + hashFilter + '"]').classList.add('employees__filter-trigger---active');

		iso.arrange({
			filter: hashFilter
		});
	}
}

window.addEventListener('hashchange', onHashchange);
onHashchange();

function getHashFilter() {
	var hash = location.hash;
	var matches = location.hash.match(/filter=([^&]+)/i);
	var hashFilter = matches && matches[1];
	return hashFilter && decodeURIComponent(hashFilter);
}
</pre>

The snippet above does it’s job and is tested with browserstack in different browsers and browser versions.

Thanks …

**Comment by desandro** [comment]
Looks like my code was missing the `event` argument. I've updated to fix it.
