### ISSUE TITLE
[Feature Request] flexbox support through `order`

### ISSUE THREAD

**Issue by konstin** [metafizzy/isotope#1333]
Flexbox allows items using the css `order` property as described by this [css tricks article](https://css-tricks.com/almanac/properties/o/order/).

I am aware about #1234, but I believe that this would an important feature given that it is relative easy to implement (adding a single css property to an item with no styling required) and that flexbox is growing in popularity. It's for example currently virtually impossible to use isotope with bootstrap 4, which is built fully upon flexbox.

**Comment by desandro** [comment]
Thanks for this suggestion, but I'm sorry flexbox is incompatible with Isotope. Isotope uses absolute positioning. Sorry, I'll have to pass on this one.
