### ISSUE TITLE
Isotope items start minimized

### ISSUE THREAD

**Issue by SaleenTheGod** [metafizzy/isotope#1334]
Hello, I am using isotope on an internal site, and whenever a user first goes on the default page there is a 50/50 chance that all the items start "minimized". 

![isotopeissue](https://user-images.githubusercontent.com/24516995/32611782-20067fc0-c52c-11e7-9ac5-a3656fdd38cb.png)

Selecting any of the filters fixes the issue, but I'm afraid my user base's first instinct wouldn't be to do that, and it kind of looks bad anyway.

Background information

* site is being hosted on a sharepoint 2013 server
* Appstack is Bootstrap, jQuery, Isotope, FlexSlider, and prettyPhoto

**Comment by bibliofille** [comment]
This is also happening on a site I'm working on as well.

**Comment by SaleenTheGod** [comment]
@bibliofille I narrowed it down to a Google Chrome thing. It doesn't happen in IE. I would test it in Firefox but my company doesn't allow it.

**Comment by bibliofille** [comment]
Interesting. Is there a workaround?

Any ideas on overriding the isotope default layout styles and using flexbox
instead?

**Comment by SaleenTheGod** [comment]
@bibliofille 

So I'm doing something kinda janky, and it isn't a surefire fix, but it at least makes Isotope load correctly more often than not. 

At the end of my html I call a css document that references the id of the isotope div doing this

`#services {
        display: none;
}`

then I have a js file right after that with this

`$('#services).show();`


Again this is pretty much a hack at this point, and it doesn't really completely fix it, it just makes it more consistent.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
