### ISSUE TITLE
AJAX appended items are overlapping 

### ISSUE THREAD

**Issue by kalyn12** [metafizzy/isotope#1335]
I am using Isotope with a CMS and pulling the same page within itself essentially to do in page pagination. 

`<script type="text/javascript">
		// 	let index = 6;
			
			
	 	$(document).ready(function() {
	 		$('.pagination-wrapper').delegate('.load-more', 'click', loadProducts);		
	 	});
			
	 	function loadProducts(e) {
	 		e.preventDefault();
	 		$('.load-more').replaceWith($('<p class="loading">Loading, please wait...</p>'));
				
	 		$.get($(this).attr('href'), { offset : index }, function(data) {    	
	 			var $grid = $('.portfolio-masonry');
					 
				$products = $(data).find('.portfolio-item').hide();
					
	 			 if (typeof imagesLoaded == 'function') {
					imagesLoaded($grid, function () {
	 					$('.loading').fadeOut('fast');
							
	 					setTimeout(function () {
	 						$grid.append($products).isotope('appended', $products);
							}, 
	 					500);
						$('.loading').fadeOut('fast');
					});
				};

				index = index + 6;
					
				$('.loading').replaceWith($(data).find('.load-more')).fadeIn('fast');	
			});
			}
		 </script>
`

The images are overlapping each other and it progressively gets worse with each call. I have tried relayout and still get the same issue.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by kalyn12** [comment]
I would love to create one for you, however, I'm utilizing a CMS to pull the data with the load more button. Do you have any other suggestions?

**Comment by desandro** [comment]
Sorry, without a reduced test case I cannot debug your issue.

**Comment by o0alexela0o** [comment]
having same problem.
