### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by bibliofille** [metafizzy/isotope#1336]
I've implemented Isotope in a WordPress site I'm building, and I used it to create a custom post type filter UI. 

Here's my URL: [http://staging.exhibitionsonthecusp.flywheelsites.com/stories/](url)

Flywheel requires a password to view staging site. Here are the credentials:
username: flywheel
password: thecusp

Sometimes on initial page load, the grid items get mushed to around 20px high, and the grid  becomes illegible. This is fixed by selecting some of the filter choices. 

I've used fit rows as the layout mode, however, I cannot get the gutter to work. 

What I really want is to be able to use flexbox on my Isotope container `div#isotope-list`, however, when I put that in CSS, it doesn't work at all. 

Here's how I've initialized the script: 
``//Load Isotope 

jQuery(function ($) {
 
var $container = $('#isotope-list'); //The ID for the list with all the blog posts
$container.isotope({ //Isotope options, 'item' matches the class in the PHP
  layoutMode: 'fitRows',
itemSelector : '.item',
fitRows: {
  gutter: 20
}
});
 
//Add the class selected to the item that is clicked, and remove from the others
var $optionSets = $('.filters-list'),
$optionLinks = $optionSets.find('a');
 
$optionLinks.click(function(){
var $this = $(this);
// don't proceed if already selected
if ( $this.hasClass('selected') ) {
  return false;
}
var $optionSet = $this.parents('.filters-list');
$optionSets.find('.selected').removeClass('selected');
$this.addClass('selected');
 
//When an item is clicked, sort the items.
var selector = $(this).attr('data-filter');
$container.isotope({ filter: selector });
 
return false;
});
 
});`
`

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Isotope. 

1. Looks like you're an old version of Isotope — v1. We're currently on v3.
2. Sounds like you're having an issue with unloaded images. See [imagesLoaded](https://isotope.metafizzy.co/layout.html#imagesloaded)
