### ISSUE TITLE
start isotope function on top of another script

### ISSUE THREAD

**Issue by to8gal** [metafizzy/isotope#1337]
Hello,

unfortunately I tried but cannot create the fork,

This cause I try to apply isotope to a div created and fill with instafeed, to do that I have to create a connection to a personal insta and this will not be authorized from Codepen.

so having the main div called instagram, and child inside of this being created by the instafeed.js ,
isotope seems to be able to append style to the parent but not the child

Try to delay that so to have all child and parent already in place with no avail.

I know like this is pretty confusing, hope I can receive help anyway

Thanks

Luca Cagnassi

**Comment by to8gal** [comment]
Hello,

this solved my problem 👍

**Comment by to8gal** [comment]
Hello,

this solved my problem, just secs after I posted this:

`setTimeout(function stack()`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by to8gal** [comment]
Hi David,

no as said I was not able to provide some cause this is regarding an interaction with another script for instagram feed and to make that work I should have some parameter wich is private as Auth and password ext and don’t really wanna share this info on codepen.

Whatever I think I solved it

Thanks

L
Luca Cagnassi
Media Designer at 5preview AB

(+46) 722111977

Luca Cagnassi is also: www.to8gal.com <http://www.to8gal.com/>

“Think Green – Please do not print this email or any printable file attached unless you really need to“
