### ISSUE TITLE
Step Fade of Results?

### ISSUE THREAD

**Issue by kaleidografik** [metafizzy/isotope#1338]
Hi. Is it possible with Isotope to disable the default transitions when filtering, and instead when a filter choice is made, step-fade out the items and the step fade in the new items? By step fade, I simply mean adding a delay of 0.1s to each item incrementally (0.1s,0.2s,0.3s)?

Thanks.

**Comment by desandro** [comment]
Have you looked at using [stagger](https://isotope.metafizzy.co/options.html#stagger)?

**Comment by kaleidografik** [comment]
Hi @desandro - Yes I have discovered Stagger and it is working quite well. I assume there is no way to disable the movement when filtering and simply have fading in and out of items?

**Comment by desandro** [comment]
If you only want opacity changes to filtered items then you should not use Isotope. You can accomplish this with your own custom jQuery.

**Comment by kaleidografik** [comment]
Not quite, I still require the re-ordering based on filter, however wondered if possible to remove the 'movement' when these changes are taking place. Instead, just fade out what is already there and fade back in the results (in the correct re-order). Thanks.
