### ISSUE TITLE
Compatibility with Flexbox

### ISSUE THREAD

**Issue by kaleidografik** [metafizzy/isotope#1339]
Hi, am I right in assuming that Isotope V3 isn't compatible with flexbox layouts? I'm trying to match the heights of all items. At the moment I'm having to use the matchHeight library to achieve this.

Thanks.

**Comment by desandro** [comment]
Sorry, Isotope does not support flexbox.

**Comment by kaleidografik** [comment]
Hi @desandro thanks for the reply. I suspected as much from looking through a bunch of other posts.

As a workaround, I'm using the MatchHeight JS library to achieve the effect, however I'm only able to get it working on initial layout. Is there a function I can use to force this function anytime Isotope is laid out/filtered?

Thanks

**Comment by julienbenisty** [comment]
@kaleidografik I know it's been a while. But for others who will stumble this post.
You can use isotope event [https://isotope.metafizzy.co/events.html](https://isotope.metafizzy.co/events.html) to trigger your MatchHeight again.
That way the MatchHeight recalculate the heights of each element.

**Comment by luis-lemos** [comment]
> @kaleidografik I know it's been a while. But for others who will stumble this post.
> You can use isotope event https://isotope.metafizzy.co/events.html to trigger your MatchHeight again.
> That way the MatchHeight recalculate the heights of each element.
