### ISSUE TITLE
Show/Hide stamp with animations ...

### ISSUE THREAD

**Issue by Skriptologe** [metafizzy/isotope#1340]
I have a isotope-grid with a so-called stamp. Everythings works fine.
But now I want to hide the stamp when user clicks a filter-value and show the stamp when no filter is activated. At the moment I have something like that:
` if(filterValue == '*') {
     stamp.show();
} else {
     stamp.hide();
 }` 
But I want animations for hiding/showing the stamp (the same the other grid-items have).
Have I to code the animations in CSS or jQuery or is there something I can use?
I tried something like:
`if(filterValue == '*') {  
     $grid.isotope('stamp', stamp);
} else {
     $grid.isotope('unstamp', stamp);
}`
but this didn´t work.

Are there some integrated functions I can call for hiding/showing a stamp with animations?
Thanx a lot for helping me ...

**Comment by desandro** [comment]
> But now I want to hide the stamp when user clicks a filter-value

If you want hide & reveal stamps, then you do not want a stamp. You'll have to treat the stamp as a regular item.

**Comment by Skriptologe** [comment]
Thank you for your answer!

Okay, my mistake. I should describe it in more detail. I forgot to mention, that i shuffle the items.
I have a portfolio with an introduction-text as a stamp (over two columns) within the isotope-grid. All the other items (images/thumbnails, one column) are shuffled. The introduction-text should be fixed in the top-left corner. So, I need the stamp or not? When the user select a category I want to hide the introduction-text (the stamp). The introduction-text (the stamp) should only be visible when user select category "all". Maybe there is a way to fix the introduction-text to the top-left corner/first position without using it as a stamp ... Can I exclude an item from shuffling?

I am pleased about every suggestion.

**Comment by desandro** [comment]
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by Skriptologe** [comment]
hier is my page:
[http://www.bbblue.de/testpage/index.html](url)

my problem:
i want to shuffle all items exclude the first item with text.
it works with hide()/show(), but i want to animate the first item likethe others.

**Comment by desandro** [comment]
Thanks for that. I recommend adding a new filter `default` to all the items you want to show initially. Then using that filter as the initial filter.  Then you can filter for items as you normally would, no stamps.

**Comment by Skriptologe** [comment]
Thanx. But the filter is not the problem. The shuffle is the problem. I want the text-box on the first fixed position (as it is). All other items are shuffled. So I need the stamp to exclude the text-box from shuffling. I don´t need a new filter. Filtering works perfect. I only want to animate the first item (text-box). Is there no way to animate a grid-item manually?

**Comment by desandro** [comment]
You'll have to create a sort function that shuffles the other items but preserves the title items in first place.  See https://isotope.metafizzy.co/sorting.html#getsortdata-functions

**Comment by Skriptologe** [comment]
Thats it! Thank you!

`var $grid = $('.grid').isotope({`
      `...`
      `getSortData: {`
            `myrandom: function ($elem) {`
                   `if($($elem).is('.fixed-item')) {`
                          `return -1;`
                   ` }`
                    `return Math.random();`
             `}`
      ` }`
` });`
`$grid.isotope({sortBy: 'myrandom'});`

This works perfectly!
