### ISSUE TITLE
microsoft edge css filtering issue

### ISSUE THREAD

**Issue by mkbatman** [metafizzy/isotope#1341]
Hi David, before I start whinging on, let me just say thank you for doing some great work. 

I have a testcase site I am developing and I am getting perfect behaviours on all browsers an devices, except the dreaded microsoft - edge in particular.

http://squibl.com/#gallery  is the URL, go to it in chrome and you will see the masonry grid gallery running perfectly with a default filter set to grayscale, colours on hover. now go to edge and you see the gallery is set up and works, but the grayscale is off - almost randomly - except try the pixel filter and you will see it works for a lower number of items. shift back to all again and it vanishes.

I made an experiment and as I moved from 33 to 34 elements the behaviour occurred consistently.

weird, isn't it?

**Comment by desandro** [comment]
Thanks for reporting this issue. Sounds a browser compositing/rendering issue that Isotope may be involved with. I see you are using larger sized images that get scaled down. You could try reducing the size of these, as this may be related to the problem.
