### ISSUE TITLE
Wrong item positioning (Integer values -> Float values)

### ISSUE THREAD

**Issue by HoloBack** [metafizzy/isotope#1343]
The current version of Masonry / Isotope parses the final values to Integer, which causes slight wrong positioning in some browsers. Changing the calculations from parseInt() to parseFloat() does the magic.

## Example

**parseInt()**
Item Height: 200.5px, Gutter: 1px, Position of next item: 201px, Real gutter: 0.5px

parseInt() cuts off the decimal place (Item Height) and adds the gutter, but the browser computed item height of course stays the same, so the final positioning values are wrong then.

## Solution

**parseFloat()**
Item Height: 200.5px, Gutter: 1px, Position of next item: 201.5px, Real Gutter: 1px as expected

parseFloat() uses the exact values for the calculation, which results in exactly positioned items. 
The presentation of the floating point pixels (subpixels) is then the part of the browser rendering engine.

I don't know, if this issue is already planned to be fixed in the next release, but I found it worth to mention.

**Comment by desandro** [comment]
Thanks for reporting this issue. I've actually experimented with float values and it sometimes resolves this issue, but has caused other issues. So it's a good solution, but not quite ready. I'm closing this issue. Please follow at #916
