### ISSUE TITLE
Isotope pagination

### ISSUE THREAD

**Issue by Munoz085** [metafizzy/isotope#1346]
Hello. I've been working using Isotope thanks to this demo, given by Desandro: [Link to codepen](https://codepen.io/desandro/pen/wfaGu)

However, I really need to implement pagination to this librarly, and found this: [JSFiddle](https://jsfiddle.net/acr8pk01/2/). Seems like someone did already. 

I'm trying to mix both, pagination, and filter with search bar but I haven't been able to do so, specially due to this imcompatibility:

Filter from pagination:
`function changeFilter(selector) {
        $container.isotope({
            filter: selector
        });
    }`

Filter from the basic example:
`// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.element-item',
  layoutMode: 'fitRows',
  filter: function() {
    var $this = $(this);
    var searchResult = qsRegex ? $this.text().match( qsRegex ) : true;
    var buttonResult = buttonFilter ? $this.is( buttonFilter ) : true;
    return searchResult && buttonResult;
  }
});`

How can I accomplish this? Some help would be great. Thank you.

**Comment by desandro** [comment]
> I'm trying to mix both, pagination, and filter with search bar

I do not recommending mixing this much functionality. It's overly complex for your users to interact with and overly complex for you to maintain code. Sorry, I won't be able to help here.
