### ISSUE TITLE
Appended items overlapping

### ISSUE THREAD

**Issue by o0alexela0o** [metafizzy/isotope#1347]
Having a problem with adding new items to container.

I'm getting a list of new items (AJAX), using a _.each() method to add all items to the container, but all new items are added on top of the first one.
Tried insertItem, Additems, appended same thing

photos is an object.
i use handlebars to render items with a template.

```
my config:
isoOptions = {
            itemSelector : '.image_item',
            layoutMode: 'masonry',
            masonry: {
                columnWidth: '.image_item',
                resizable: false,
                gutter: 40,
                stragger: 60,
                layoutMode: 'fitRows'
            },
            
        };

$('.images_inner_window').isotope(isoOptions);

_.each(photos, function(item){
                var $item = $(this.templates.photo( item ))
                $('.container').append( $item ).isotope( 'appended', $item )
            })


```

I think i'm missing something... please help.
thanks

**Comment by desandro** [comment]
Sounds like this may be an unloaded images problem. See [Layout - imagesLoaded](https://isotope.metafizzy.co/layout.html#imagesloaded)

You can resolve this by using imagesLoaded to layout items after they have loaded.

``` js
var $container = $('.container');

_.each(photos, function(item){
    var $item = $(this.templates.photo( item ))
    $item.imagesLoaded( function() {
      $container.append( $item ).isotope( 'appended', $item );
    });
});
```
