### ISSUE TITLE
How to not open on ALL

### ISSUE THREAD

**Issue by rpuddle** [metafizzy/isotope#1350]
I'm using Isotope for a Portfolio gallery. All I want to be able to do is to have my page open with one of the categories pre selected, not defaulting to show ALL. I can't seem to be able to. Can anyone help me with this?

**Comment by desandro** [comment]
Hello! See at an initial filter when initializing Isotope

``` js
var $grid = $('.grid').isotope({
  // set initial filter
  filter: '.featured',
});
```

**Comment by thetwopct** [comment]
Is it possible to use hashFilter and initial filter on the same page?

`  $grid.isotope({
 itemSelector: '.tryeRangeBox',
 filter: '.saloon',
 layoutMode: 'vertical',
 filter: filterFns[ hashFilter ] || hashFilter
  });`
