### ISSUE TITLE
Isotope Masonry with different widths

### ISSUE THREAD

**Issue by Stonino82** [metafizzy/isotope#1351]
Hi, I'm using Isotope in a new project, and it works very well. [Here](https://codepen.io/Stonino82/pen/VywBdY?editors=1100) is an example of what I have achieved.
Now I would like to make a small change, I would like to have differents widths for the columns, how can I do it using Bootstrap and Wordpress?
Here you have an example of what I would like to achieve: http://www.hannajun.com/

Thanks.

**Comment by desandro** [comment]
Take a look at the [Bootstrap examples](https://isotope.metafizzy.co/extras.html#bootstrap)
