### ISSUE TITLE
Isotope leaving a gap after adding imagesLoaded

### ISSUE THREAD

**Issue by AxelDolislager** [metafizzy/isotope#1353]
As I was building my website, I got into a problem with isotope(masonry) when I added imagesLoaded.js.

The thing works fine, but positions it +- 5000px to much on the top position.This happens in multiple browsers. I'm trying to get it back in place.

This is the website I'm developing on: http://noreplypictures.axeldhw261.261.axc.nl/

As you can see, I use this code to init my grid.

```
var $grid = $('.grid').imagesLoaded(function(){
      $grid.isotope({
                itemSelector: 'article',
                resizable: false,
                layoutMode: 'fitRows'
      });
});

var album = $("main").attr("album-data");
$.ajax({
url     : "/includes/handlers/newsfeed-handler.php",
type    : "POST",
data    : "album=" + album,
cache   : false,
success : function(data){
         var $data = $(data);
         $data.imagesLoaded().progress(function(){
                $grid.append($data);
                $grid.isotope('appended', $data);
                $grid.isotope( 'layout' );
                $('.loadingMsg').hide();
      });
}
});
```

Thank you for your help!

**Comment by desandro** [comment]
Thanks for reporting this issue. Looking at your code, `.imagesLoaded().progress()` will be triggered for each image that is loaded. So you are appending `$data` with each load. I recommend changing `progress` to `always`.

**Comment by AxelDolislager** [comment]
This fixed it! Thanks for the help!
