### ISSUE TITLE
Imageheights not fitting in rows

### ISSUE THREAD

**Issue by AxelDolislager** [metafizzy/isotope#1354]
I am trying to get all images the same height in the fitrow layout mode, I can't seem to figure it out. Maybe you guys can help?

As you can see on this website http://noreplypictures.axeldhw261.261.axc.nl/ I have a 3 column grid system. The images that take 2-width are not the same height as the 1-width elements.

here's my js code: 

```
var $grid = $('.grid').imagesLoaded(function(){
          $grid.isotope({
                    itemSelector: 'article',
                    resizable: false,
                    layoutMode: 'fitRows'
          });
});

var album = $("main").attr("album-data");
$.ajax({
    url     : "/includes/handlers/newsfeed-handler.php",
    type    : "POST",
    data    : "album=" + album,
    cache   : false,
    success : function(data){
             var $data = $(data);
             $data.imagesLoaded().always(function(){
                    $grid.append($data);
                    $grid.isotope('appended', $data);
                    $grid.isotope( 'layout' );
                    $('.loadingMsg').hide();
	                   addRemoveIcon();
          });
    }
});
```

and my css code for desktop view:
```
	main.grid{width: 96%;padding-top: 5px;margin-left: 2%;}
	main.grid .grid-item { width: calc(100%/3);padding: 18px 20px;}
	main.grid .grid-item--width2 { width: calc((100%/3) *2);padding: 18px 20px;}
	main.grid article{position: relative;}
	main.grid .grid-item img{width: 100%;height: 100%;}
```

Thank you for your help!

**Comment by desandro** [comment]
This looks to be an basic issue with your grid measurements. Let's first look at a grid with no gutters, that uses 2x3 portrait images:

![screen shot 2018-01-03 at 9 38 50 pm](https://user-images.githubusercontent.com/85566/34548188-a3c1ccc0-f0ce-11e7-883b-6fa0f38e26ca.png)

The landscape images need to be 4x3, not 3x2.

Now let's try adding gutters

![screen shot 2018-01-03 at 9 42 40 pm](https://user-images.githubusercontent.com/85566/34548262-0c0a2fb6-f0cf-11e7-8a32-f1f6e15a75a7.png)

This grid has 30 columns. Portrait images take up 8 horizontal columns. Landscape images take 18x12 squares Each square in this grid is 1/30 or 3.333%. Padding needs to be set in percents in order for everything to scale. CSS would look something like

``` css
.grid-item {
  width: calc((100%/3));
  padding: 18px 3.33%;
}

.grid-item--width2 {
  width: calc((100%/3) * 2);
}
```

See demo https://codepen.io/desandro/pen/26cb98edafed55813a7a34152edaabd0

**Comment by AxelDolislager** [comment]
So there's no way from not resizing before making it fit?

**Comment by desandro** [comment]
Draw a grid and you can figure it out for yourself.
