### ISSUE TITLE
Use hashfilter + filter for initial view?

### ISSUE THREAD

**Issue by thetwopct** [metafizzy/isotope#1355]
Awesome script. I'm struggling with implementing hashfilters combined with initial filter view. Is this possible? I'm guessing some sort of IF hashfilter ELSE type structure, but maybe not.

Current code (based on a codepen demo): 

``` js
function getHashFilter() {
  // get filter=filterName
  var matches = location.hash.match( /filter=([^&]+)/i );
  var hashFilter = matches && matches[1];
  return hashFilter && decodeURIComponent( hashFilter );
}

// init Isotope
var $grid = $('.grid');

// bind filter button click
var $filterButtonGroup = $('.filter-button-group');
$filterButtonGroup.on( 'click', 'button', function() {
  var filterAttr = $( this ).attr('data-filter');
  // set filter in hash
  location.hash = 'filter=' + encodeURIComponent( filterAttr );
});

var isIsotopeInit = false;

function onHashchange() {
  var hashFilter = getHashFilter();
  if ( !hashFilter && isIsotopeInit ) {
    return;
  }
  isIsotopeInit = true;
  // filter isotope
  $grid.isotope({
    itemSelector: '.tryeRangeBox',
 	  filter: '.saloon',
    layoutMode: 'vertical',
    // use filterFns
    filter: filterFns[ hashFilter ] || hashFilter
  });
  // set selected class on button
  if ( hashFilter ) {
    $filterButtonGroup.find('.is-checked').removeClass('is-checked');
    $filterButtonGroup.find('[data-filter="' + hashFilter + '"]').addClass('is-checked');
  }
}

$(window).on( 'hashchange', onHashchange );

// trigger event handler to init Isotope
onHashchange();

var $items = $grid.find('.tryeRangeBox');
$grid.addClass('is-showing-items')
  .isotope( 'revealItemElements', $items );
```

**Comment by desandro** [comment]
Thanks for reporting this issue.

> I'm struggling with implementing hashfilters combined with initial filter view

The way this code works is that everything goes through the URL hash. To set an initial filter, your page will need to have a URL hash to start with.

I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues). Try forking the [URL hash demo](https://codepen.io/desandro/pen/vErxXj)

**Comment by thetwopct** [comment]
I don't understand what you mean then.

**Comment by desandro** [comment]
'hashfilter' is just a term I use to indicate that filtering is done via URL hash. In the [URL hash demo](https://isotope.metafizzy.co/filtering.html#url-hash), it is the same thing as 'filter'.

Looking at your code, you have set the `filter` option twice:

``` js
    filter: '.saloon',
    filter: filterFns[ hashFilter ] || hashFilter
```

I believe the first `filter` will be overwritten by the second.

Can you describe what behavior you are trying to achieve?

Are you trying to always filter `.saloon` if no URL hash is set? If so that code would look something like:

``` js
var isIsotopeInit = false;

function onHashchange() {
  var hashFilter = getHashFilter();
  if ( !hashFilter && isIsotopeInit ) {
    return;
  }
  
  // if initializing and no hashFilter is set, filter .saloon
  if ( !isIsotopeInit && !hashFilter ) {
    hashFilter = '.saloon';
  }
  // filter isotope
  $grid.isotope({
    itemSelector: '.tryeRangeBox',
    filter: '.saloon',
    layoutMode: 'vertical',
    filter: hashFilter
  });

  isIsotopeInit = true;
  // set selected class on button
  if ( hashFilter ) {
    $filterButtonGroup.find('.is-checked').removeClass('is-checked');
    $filterButtonGroup.find('[data-filter="' + hashFilter + '"]').addClass('is-checked');
  }
}
```
