### ISSUE TITLE
Weird hashfilter bug

### ISSUE THREAD

**Issue by thetwopct** [metafizzy/isotope#1356]
I'm using hashfilter. On page, it works fine to filter divs on the page, always correct. However when using the URLs as a href on another page, linking to a filtered display, the filter will show incorrect items - it will show whatever is my last div at the top of the search, even if its got nothing to do with the hashfilter term.
I only have 1 data-category per div. I have a matching class name for each div. Each hash (is now) completely different words (they were 3 letters). 
My code is based on a codpen example, so nothing weird. 
Any ideas why this could be happening?

``` js 
// filter functions
var filterFns = {
};

function getHashFilter() {
  // get filter=filterName
  var matches = location.hash.match( /filter=([^&]+)/i );
  var hashFilter = matches && matches[1];
  return hashFilter && decodeURIComponent( hashFilter );
}

// init Isotope
var $grid = $('.grid');

// bind filter button click
var $filterButtonGroup = $('.filter-button-group');
$filterButtonGroup.on( 'click', 'button', function() {
  var filterAttr = $( this ).attr('data-filter');
  // set filter in hash
  location.hash = 'filter=' + encodeURIComponent( filterAttr );
});

var isIsotopeInit = false;

function onHashchange() {
  var hashFilter = getHashFilter();
  if ( !hashFilter && isIsotopeInit ) {
    return;
  }
  isIsotopeInit = true;
  // filter isotope
  $grid.isotope({
    itemSelector: '.tryeRangeBox',
    filter: filterFns[ hashFilter ] || hashFilter
  });
  // set selected class on button
  if ( hashFilter ) {
    $filterButtonGroup.find('.is-checked').removeClass('is-checked');
    $filterButtonGroup.find('[data-filter="' + hashFilter + '"]').addClass('is-checked');
  }
}

$(window).on( 'hashchange', onHashchange );

// trigger event handler to init Isotope
onHashchange();
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues). Try forking the [URL hash demo](https://codepen.io/desandro/pen/vErxXj)

**Comment by thetwopct** [comment]
I can't build a test case easily, prefer just to share the project with you. Is there a way I can share a link with you in private?

**Comment by desandro** [comment]
Email yo@metafizzy.co

A **reduced test case** is the best way to get your issue address. They help me, you, and later users all understand the issue.

**Comment by thetwopct** [comment]
I fixed this with imagesLoaded https://imagesloaded.desandro.com and adding below to the above code:

```
var $items = $grid.find('.tryeRangeBox');
$grid.addClass('is-showing-items')
.isotope( 'revealItemElements', $items );

$(document).ready(function(){
    $grid.isotope();
});

$grid.imagesLoaded( function() {
  $grid.isotope();
});
```
