### ISSUE TITLE
Layout with "half height"...

### ISSUE THREAD

**Issue by PhotoTendance** [metafizzy/isotope#1361]
Hello,

I try since a couple of days to change layouts to have this result : 
![capture d ecran 2018-01-19 a 10 26 56](https://user-images.githubusercontent.com/19971279/35144207-2519cdc2-fd04-11e7-85d6-53e8fed9f7d5.png)
Actually, I can't obtain it, the ordering is left-to-right in priority, go bottom after the end of the line.
![capture d ecran 2018-01-19 a 10 14 18](https://user-images.githubusercontent.com/19971279/35144297-72104b92-fd04-11e7-8add-ee809f845941.png)
Unfortunately, I find this layout not great for readability.
Do you have an option for this ?

Thank you for your great work @desandro .

**Comment by desandro** [comment]
You can set [`horizontal: true`](https://packery.metafizzy.co/options.html#horizontal), to the packing algorithm works left-to-right, not top to bottom, with a set height, instead of a set width.

**Comment by PhotoTendance** [comment]
Thank you for your answer.
In my example, on two lines, packery with option "horizontal" will be a good idea.
But, in fact, my project is on unknown blocks. Maybe on ten or more lines, with twenty or hundred blocks.
In this case, this case, "horizontal" option will be not great.
The readability with blocks of two heights and one height, will be easier if alignments of blocks is top to bottom to pair lines (it is an idea) and left to right.
For odd (3,5,7,9...) lines, begin a new alignment top to bottom and after left to right for blocks of one height...

I hope my english is understandable...
Thank you @desandro  !

**Comment by desandro** [comment]
Sorry, that's the best solution given this scenario.
