### ISSUE TITLE
isotope on initial loading adding a extra space below items

### ISSUE THREAD

**Issue by cristianmavila** [metafizzy/isotope#1362]
Do you have any idea how can i remove that extra space below items?
Please, look this example http://dev-jorgemunizbranding.pantheonsite.io/
To see that error load the page in 1024x600, that happened only once time.
If you resize the window then the grid is pretty good.

Thank you for your great work @desandro.

**Comment by cristianmavila** [comment]
Hey guys!

Just to help someone i resolved that bug with this solution below.

```
.item {
    position: relative;
    height: 0;
    display: block;
    width: 100%;
    /* padding-bottom is calculated and rendered in to HTML OR inserted on css class*/
}
```

```
.item img {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: block;
}
```

If you have a 640x360 image you can do the following math: 

`360 / 640 * 100% = 56.25`

if you prefer use on HTML markup look that.

```
<div class="item" style="padding-bottom: 56.25% /* calc(360 / 640 * 100%)*/;">
    <img
        data-sizes="auto"
        data-src="http://placehold.it/640x360"
        class="lazyload" />
</div>
```

I hope that will help someone.

**Comment by desandro** [comment]
Thanks for following up!
