### ISSUE TITLE
Is there a way to use Isotope with WordPress?

### ISSUE THREAD

**Issue by Stonino82** [metafizzy/isotope#1363]
It's not exactly a problem, and maybe it's not the most appropriate place to ask... but I've been searching for a long time and it seems impossible to find a solution.

Suppose we want to use Isotope to show the posts of a blog made in WordPress.
The problem of using the two together is that when you make a loop with WordPress you decide in advance the layout, so you will apply the same column width for each entry, and Isotope will play with the height of the posts and find the best way to place them.

But....what if I want the width of the columns to be different for each entry?
Does anyone know how to approach the problem?

**Comment by desandro** [comment]
Yes, you can use Isotope with WordPress.

I'm not a WordPress expert, but I have two ideas:

+ Use custom fields to indicate when you an item to be large size. Add a class to post elements with the enabled custom field
+ Use tags added to the post element. `.tag-post-featured` could be larger size.

**Comment by desandro** [comment]
Also, add a 👍  to #1269
