### ISSUE TITLE
Isotope in combination with Slick slider

### ISSUE THREAD

**Issue by oudj001** [metafizzy/isotope#1364]
Hi,

I would like to combine Isotope with the slick slider.
When I initiate slick on my $('.grid'), a lot of classes and additional dom elements will be added. Isotope can't calculate anymore from that moment.

I'm filtering with combinationfilters and a custom search query on the Isotope and would like to display the results in my slick slider. 

Anyone already did this before?
Thanks in advance,

Justin

**Comment by desandro** [comment]
> I would like to combine Isotope with the slick slider

Isotope was not designed to work in combination with other layout libraries like Slick. Sorry, I cannot support using these two together.
