### ISSUE TITLE
filtering with imagesloaded

### ISSUE THREAD

**Issue by fraserdev** [metafizzy/isotope#1365]
https://codepen.io/anon/pen/LQbROM

I have the above pen as a reduced test case. The JS included is actually in an external file called "base.js" - I used the first chunk of code (lines 3-17) to help with loading all of the grid-items so that they didn't overlap. My issue is, I can no longer filter with the code that was previously working for me (starting at line 19). Can you please assist in the best way to handle filtering using the method I've chosen for imagesLoaded and initializing isotope?

**Comment by desandro** [comment]
Thanks for reporting this issue. You can resolve this by changing `$grid` to `$container`.  Then move the other code into `jQuery( function() {} )`

See demo https://codepen.io/desandro/pen/KQWqPe

``` js

// use document.ready instead of window.load
// window.load waits for all resources to be loaded first,
// can be a long time
jQuery( function() {
    // now doc is ready, make selection
    // use another selector, not .isotope,
    // since that is dynamically added in Isotope v1
    var $container = jQuery('.grid');
    // use imagesLoaded, instead of window.load
    $container.imagesLoaded( function() {
        $container.isotope({
          layoutMode: 'fitRows'
        });
    })

    $('.filter-button-group').on( 'click', 'button', function() {
        var filterValue = $(this).attr('data-filter');
        $container.isotope({ filter: filterValue });
    });

    // change is-checked class on buttons
    $('.button-group').each( function( i, buttonGroup ) {
        var $buttonGroup = $( buttonGroup );
        $buttonGroup.on( 'click', 'button', function() {
            $buttonGroup.find('.is-checked').removeClass('is-checked');
            $( this ).addClass('is-checked');
        });
    });
});


```

[Learn more jQuery lesson at Fizzy School](http://fizzy.school)
