### ISSUE TITLE
Combination filters load specific categories with lists (section, option)?

### ISSUE THREAD

**Issue by Asperino** [metafizzy/isotope#1367]
I've found [this](https://codepen.io/desandro/pen/1d4c5753226bffc0cfce3e9df01ea9fa) and wonder if its possible to have it with lists like [this](https://codepen.io/desandro/pen/GFbAs)?

**Comment by desandro** [comment]
Yes, See https://codepen.io/desandro/pen/OQOqQK

I moved `getFilterValue()` into its own function, then use that function to set the initial filter from the selected & checked inputs.

**Comment by Asperino** [comment]
Thank you very much but your link seems broken :/
