### ISSUE TITLE
Callback issues

### ISSUE THREAD

**Issue by oldskool73** [metafizzy/isotope#137]
I guess this is related to #128, but doing a filter that doesn't change the layout also doesn't appear to fire the callback.

Also, if you apply multiple filters with callbacks that aren't called, the callbacks get queued up and are then all fired at once when you later do a filter that does cause a layout change.

**Comment by benderlidze** [comment]
@desandro any example/link of a listener? thanks

**Comment by desandro** [comment]
@benderlidze See [Isotope events](https://isotope.metafizzy.co/events.html)
