### ISSUE TITLE
Unable to get local demo of codepen example working

### ISSUE THREAD

**Issue by mccreeker** [metafizzy/isotope#1370]
**Test case:** https://codepen.io/desandro/pen/nFrte (no need to fork, I'm trying to get it running locally for easier testing and learning for a more complex pre-built feature I'm trying to fix)

I've copied down the code and included the js files from documentation and CodePen settings (for that pen), and it shows the boxes and colors and buttons, but clicking the buttons does nothing, and there's no JS errors in console (Chrome)... not seeing what I'm missing.

**Comment by desandro** [comment]
[Here is the HTML for the that demo](https://gist.github.com/desandro/3103c528d3c2b4cf95502e426f568455). Try downloading this and running it
