### ISSUE TITLE
Centering with fitRows?

### ISSUE THREAD

**Issue by mccreeker** [metafizzy/isotope#1371]
I'm unable to do a reduced test case because it contains proprietary information, is very large, I don't know what's wrong with it (it doesn't do what we want yet), and I don't have time to convert it anyways, sorry. Also I'm new to Isotope and unable to get a local version functioning in a way that displays like the online examples.

I'm just trying to get fitRows (or another layout) to automatically center square icons based on screen width (for responsive). I'm not sure if that's possible/easy to do with that layoutMode (changing could require a lot of recoding), but I've tried multiple ways which haven't worked yet, including these: 

https://github.com/metafizzy/isotope/issues/428#issuecomment-165998802
http://jsfiddle.net/desandro/P6JGY/24/

I'm not sure what to change on these to make them work... and I'm unable to comment on the first link's thread.

Here's the JS we're including:

jquery.js?ver=1.12.4
isotope.pkgd.min.js

var $campaignBoxes = $('.the-box-wrapper').isotope({
	// options
	itemSelector: '.the-box',
	layoutMode: 'fitRows',
	transitionDuration: 0,
	fitRows: {
		gutter: 20
	}
});

Would it be best (regardless of time) to just use a different layoutMode and do the centering properly?

**Comment by desandro** [comment]
Officially, the fitRows layout mode does not support centering. See #1143 for a possible solution.
