### ISSUE TITLE
 filters do not work after load 

### ISSUE THREAD

**Issue by BlueAbe** [metafizzy/isotope#1372]
Hello, I had a problem with correct loading of images. When I use the load or imagesLoaded function, everything is fine in the arrangement of the images, but the filters stop working. Am I doing something wrong?

![1](https://user-images.githubusercontent.com/36880369/36721704-f1cb0618-1bab-11e8-8848-56a99b1dda30.jpg)

Here is the problem 
http://domnawydmach.pl/galeria

thank you in advance for your help

**Comment by desandro** [comment]
Looks like you have other errors happening on your page.

![screen shot 2018-03-02 at 4 20 50 pm](https://user-images.githubusercontent.com/85566/36922406-b660ad1c-1e35-11e8-94f6-14e15e5b49c4.png)

I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by BlueAbe** [comment]
The test case is not needed any more. 

I've attached libraries for ImageLoader directly above the code using the imageLoader functions instead of in the <head> section. Now they work great. Maybe imageLoader conflicts with other scripts when its libraries are in the <head> section.
Thank you for your interest in the topic and devoted to your time.
I really like the isotope and I will follow its development.
Regards !
