### ISSUE TITLE
iPad sleep/wake breaks isotope

### ISSUE THREAD

**Issue by jefau2** [metafizzy/isotope#1374]
iPad mini 4 / iOS 10.3.3 / Safari

1. View isotope item in browser (https://isotope.metafizzy.co/):

<a href="https://imgbb.com/"><img src="https://image.ibb.co/fvPYcn/iso.png" alt="iso" border="0"></a>

2. Press sleep button on iPad and wait 10 seconds or so.

3. Press home button to wake iPad and view the result (the isotope items have broken out of their container):

<a href="https://imgbb.com/"><img src="https://image.ibb.co/ckQWDS/iso2.png" alt="iso2" border="0"></a>

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm having trouble reproducing it. I don't have access to an iPad. But on my iPhone, I'm unable to reproduce the issue.

**Comment by jefau2** [comment]
Correct this only occurs on the iPad for some reason.
