### ISSUE TITLE
Inclusive Combination Filters With Counts

### ISSUE THREAD

**Issue by coolCode101** [metafizzy/isotope#1375]
I would like to filter very similarly to this here:
https://codepen.io/desandro/pen/zrMXQv
With two important differences.

1) I want the filters to be inclusive within the group, but not outside the group. So what I mean is, if I click "Red", I want it to show me just red shapes. If I then click "Blue," I want it to show Red AND Blue since they are both within the "Color" filter group. However, if I now click "Small," I want it to show me only Small shapes that are Red or Blue, but not Yellow since the Yellow filter is not selected.

2) The harder part, which I'm really struggling with. I want each button to show me a count of how many there are, and I want it to update accordingly. So for example, initially, the buttons should look like this:

> Red (8)
> Blue (8)
> Yellow (8)
> 
> Small (6)
> Wide (6)

If I select RED, the new values should look like this (bold denotes a selected item):

> **Red (8)**
> Blue (8)
> Yellow (8)
> 
> Small (2)
> Wide (2)

Blue and Yellow should stay the same, because they are inclusive. If I select either of those, then I should get 8 new shapes of that color. Small and Wide should change to 2, because there are only two Red and Small shapes, and only two Red and Wide shapes.

If I now select SMALL:

> **Red (2)**
> Blue (2)
> Yellow (2)
> 
> *Small (2)*
> Wide (2)

Red changes to 2, because there are only two shapes that are both Small and Red. Blue and Yellow also change to 2, because clicking either of those would add two more small shapes (ie: (Red OR Yellow) AND Small). Wide remains at 2, because clicking Wide would add two Wide and Red objects to our results.

I hope that I've explained it correctly; it's pretty tricky. I've been racking my brain how to do both of these things together and I just can't find a way! Ideally, a solution would also be quick so that it can filter hundreds (or more) items at once...

**Comment by desandro** [comment]
Thanks for reporting this issue. You're asking for some complex behaviors. Here are some demos to get you started:

+ [Inclusive combination fillters](https://codepen.io/desandro/pen/MebyMR)
+ [Filter button counts](https://codepen.io/desandro/pen/pyxwem), from #1084 

The implementation is up to you

**Comment by akm-TL** [comment]
This is the exact filtering/count solution I'm looking for as well. Did you have any luck with it? 

Haven't been able to figure it out myself.
