### ISSUE TITLE
isotope sort by numeric data attribute

### ISSUE THREAD

**Issue by santer2208** [metafizzy/isotope#1376]
Hello! How do I sort by numeric attribute? Id is always unique
HTML structure:
https://jsfiddle.net/s729oeL7/14/
Thanks!

**Comment by desandro** [comment]
Your code would look something like:

``` js
var $grid = $('.grid').isotope({
  getSortData: {
    currency: '[data-currency] parseFloat'
  },
});
```

This will read the `data-currency` attribute, and convert it to a float number.

You can then use `$grid.isotope({ sortBy: 'currency' });`

Read more at https://isotope.metafizzy.co/sorting.html#getsortdata-strings

**Comment by santer2208** [comment]
Buttons do not have a name in the attributes. Instead of the name ID.
An example is needed where names are not used and the value ID is taken from the selected button from the sort.
Sorry my english is not good
https://prnt.sc/ir5f1d

**Comment by desandro** [comment]
Are you looking to filter by currency type? If so, you would have to use a [filter function](https://isotope.metafizzy.co/filtering.html#filter-functions)

See demo https://codepen.io/desandro/pen/0ef9d81946c1c742e39255b16f94c360?editors=1010

``` js
var $mainItemsWrap = $('.main-items-wrap').isotope({
  layoutMode: 'vertical',
});

$('.sort-by-button-group').on( 'click', 'button', function( event ) {
  var $target = $( event.currentTarget );
  var value = $target.attr('data-value');
  var filter;
  if ( value == 'index' ) {
    filter = '*';
  } else {
    filter = function() {
      var currency = $( this ).attr('data-currency');
      return currency == value;
    }
  }
  $mainItemsWrap.isotope({
    filter: filter
  });
});
```

**Comment by santer2208** [comment]
A good example but sorting is necessary. Do not hide others blocks

**Comment by desandro** [comment]
I've provided extensive documentation and demos on how to [sort using Isotope.](https://isotope.metafizzy.co/sorting.html) I recommend you try forking a demo and putting in your own values.
