### ISSUE TITLE
Isotope plugin issue with require js 

### ISSUE THREAD

**Issue by 29sunil** [metafizzy/isotope#1377]
Hello,
I am using isotopeMB but i am getting following error:
TypeError: $container.isotopeMB is not a function

I have confugured it with require js.
Below is require js configuration

var config = {
map: {
'*': {
compareItems: 'Magento_Catalog/js/compare',
compareList: 'Magento_Catalog/js/list',
relatedProducts: 'Magento_Catalog/js/related-products',
upsellProducts: 'Magento_Catalog/js/upsell-products',
productListToolbarForm: 'Magento_Catalog/js/product/list/toolbar',
catalogGallery: 'Magento_Catalog/js/gallery',
priceBox: 'Magento_Catalog/js/price-box',
priceOptionDate: 'Magento_Catalog/js/price-option-date',
priceOptionFile: 'Magento_Catalog/js/price-option-file',
priceOptions: 'Magento_Catalog/js/price-options',
priceUtils: 'Magento_Catalog/js/price-utils',
catalogAddToCart: 'Magento_Catalog/js/catalog-add-to-cart',
}
},
paths: {
isotope: 'Magento_Catalog/js/jquery.isotope.min',
imagesLoaded: 'Magento_Catalog/js/jquery.imagesLoaded.min',
transit: 'Magento_Catalog/js/jquery.transit.min',
easing: 'Magento_Catalog/js/jquery.easing',
waypoints: 'Magento_Catalog/js/waypoints.min',
modernizr: 'Magento_Catalog/js/modernizr.custom.min',
mediaBoxesdropdown: 'Magento_Catalog/js/jquery.mediaBoxes.dropdown',
mediaBoxes: 'Magento_Catalog/js/jquery.mediaBoxes',
autoGrid: 'Magento_Catalog/js/jquery.autoGrid',
bridget: 'Magento_Catalog/js/bridget'
},
shim: {
'isotope': {
deps: ['jquery'],
exports: ['IsotopeMB']
},
'mediaBoxes': {
deps: ['jquery','isotope']
}
}
};

**Comment by desandro** [comment]
This looks to be an issue with your RequireJS configuration. Not necessarily with Isotope. Sorry, I won't be able to provide support.
