### ISSUE TITLE
Multifilter with group "AND" logic and hash

### ISSUE THREAD

**Issue by in-session** [metafizzy/isotope#1379]
Hi,

first many thanks for your great work.

I have a little question, I find no way to implement the isotope with AND logic + chash.
It is like your example "Isotope combination filters with checkboxes": https://codepen.io/desandro/pen/btFfG 

But I need a way to show only whiche match all the selected criteria, as example:
https://codepen.io/in-session/pen/MVrejQ

If you select brand 1 + red + blue there are 33 items, but with the AND logic it should only be one.
And the chash is like: #brand=brand1&color=red,blue

Here is an example of MixItUp, but I would like to use infinity scroll and this is current not possible: https://demos.kunkalabs.com/mixitup/toggle-filtering-and-logic/

Is that even possible with isotopes? And have an codepen example for this filtering?

Greetings Chris

**Comment by Gaetan-dc** [comment]
You need to modify the "merge filter groups" loop line 85 so that it concatenates the different values of filter groups instead of creating a new value.
You can see that here : https://codepen.io/anon/pen/ZxvJLN

That being said, note that front-end filtering and infinite scrolling don't play well together.

**Comment by desandro** [comment]
This behavior is getting very complicated. At this point I recommend removing features, unless you feel comfortable putting these all together. The code gets unwieldy.

> Is that even possible with isotope

Infinite Scroll and Isotope filtering is not recommend. See #1358

**Comment by noblesilence** [comment]
I need the same feature, to filter with AND logic.
