### ISSUE TITLE
Weird question: is it possible to save and load a random sortBy ordering?

### ISSUE THREAD

**Issue by willfaulds** [metafizzy/isotope#1380]
So I am helping someone to produce a relatively simple HTML "app." All was good but we are running into memory limit issues as they are displaying video and after a number are played they refuse to load.

We're using isotope and have no direct issue with it but the only fix we can find to the memory limit issue is a page reload... However, on imagesLoaded we isotope objects with sortBy: 'random'.

This leads to our issue - if possible would like to save and reload the random ordering until a user has finished their session (we have a timeout that performs a true reload). I've googled, and search this git, but can't find a similar use-case.

Can anyone suggest a relatively easy to implement a method to save/load a sortBy? I'm imagining extracting to a localStorage object. On load using the localStorage object exists and wiping it on a true timeout.

**Comment by desandro** [comment]
Yes! you can do this by using a [function for `getSortData`](https://isotope.metafizzy.co/sorting.html#getsortdata-functions) and setting & getting order with `localStorage`. See demo https://codepen.io/desandro/pen/mxxpBr/

``` js
// isotope options
var isoOptions = {};
// get itemOrder from localStorage
var itemOrder = localStorage.getItem('itemOrder');
if ( itemOrder ) {
  console.log('using saved order', itemOrder )
  // convert string to array
  itemOrder = itemOrder.split(',');
  // set options to use itemOrder
  isoOptions.getSortData = {
    // order is based on index in itemOrder array
    stored: function( itemElem ) {
      var itemId = $( itemElem ).attr('data-item-id');
      return itemOrder.indexOf( itemId );
    }
  };
  isoOptions.sortBy = 'stored';
}

var $grid = $('.grid').isotope( isoOptions );

$('.randomize-button').on( 'click', function() {
  $grid.isotope('shuffle');
  var itemElements = $grid.isotope('getFilteredItemElements');
  var shuffleOrder = itemElements.map( function( itemElem ) {
    return $( itemElem ).attr('data-item-id');
  });
  // convert array to string
  shuffleOrder = shuffleOrder.join(',');
  // save to localStoage, convert array to string
  localStorage.setItem( 'itemOrder', shuffleOrder );
  console.log('saving order', shuffleOrder )
});
```
