### ISSUE TITLE
Isotope Collapsing Images

### ISSUE THREAD

**Issue by dockerV** [metafizzy/isotope#1381]
I don't understand what 's the problem with my code and my gallery collapsing. I tried even the window load function but not working properly. I should press refresh to make isotope works properly.  I have tried the imagesLoaded function but still the problem insists. I am not sure if I wrote the code wrong.  Any ideas?

		<div id="filters" class="filter">
			<button data-filter="*" class="btn btn-red">All</button>
			<button data-filter=".one" class="btn btn-teal">One</button>
			<button data-filter=".two" class="btn btn-teal">Two</button>
		</div>
		<div class="grid">
			<figure class="element-item one" data-category="one">
				<a href="#"><img class="responsive-img" src="img/image1.jpg"></a>
			</figure>
                        <figure class="element-item two" data-category="two">
				<a href="#"><img class="responsive-img" src="img/image2.jpg"></a>
			</figure>
		</div>

                My First Script
		// quick search regex
		var qsRegex;
		var buttonFilter;

		// init Isotope
		var $grid = $('.grid').isotope({
		  itemSelector: '.element-item',
		  layoutMode: 'fitRows',
		  filter: function() {
		    var $this = $(this);
		    var searchResult = qsRegex ? $this.text().match( qsRegex ) : true;
		    var buttonResult = buttonFilter ? $this.is( buttonFilter ) : true;
		    return searchResult && buttonResult;
		  }
		});

		$('#filters').on( 'click', 'button', function() {
		  buttonFilter = $( this ).attr('data-filter');
		  $grid.isotope();
		});

		// use value of search field to filter
		var $quicksearch = $('#quicksearch').keyup( debounce( function() {
		  qsRegex = new RegExp( $quicksearch.val(), 'gi' );
		  $grid.isotope();
		}) );

		// change is-checked class on buttons
		$('.button-group').each( function( i, buttonGroup ) {
		  var $buttonGroup = $( buttonGroup );
		  $buttonGroup.on( 'click', 'button', function() {
		    $buttonGroup.find('.is-checked').removeClass('is-checked');
		    $( this ).addClass('is-checked');
		  });
		});
		  

		// debounce so filtering doesn't happen every millisecond
		function debounce( fn, threshold ) {
		  var timeout;
		  return function debounced() {
		    if ( timeout ) {
		      clearTimeout( timeout );
		    }
		    function delayed() {
		      fn();
		      timeout = null;
		    }
		    setTimeout( delayed, threshold || 100 );
		  };
		}

I also changed the Init isotope with this (from a post of @desandro ... but nothing

		// init Isotope TEST
		jQuery( function() {
			var $grid = jQuery('.grid');
			$grid.imagesLoaded( function(){
			    $grid.isotope({
				    itemSelector: '.element-item',
				    layoutMode: 'fitRows',
				    filter: function() {
				      var $this = $(this);
				      var searchResult = qsRegex ? $this.text().match( qsRegex ) : true;
				      var buttonResult = buttonFilter ? $this.is( buttonFilter ) : true;
				      return searchResult && buttonResult;
				    }
			    });	
			})
		});

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by desandro** [comment]
Looks like your JS code is missing [imagesLoaded](https://isotope.metafizzy.co/layout.html#imagesloaded)

> Is there a way instead of buttons to use lists (instead of buttons), therefore to input the clicks on the navbar? 

Yes, you can use any UI you like. It doesn't have to be buttons. See https://isotope.metafizzy.co/filtering.html#other-ui
