### ISSUE TITLE
fitRows with Stamp or Packery with horizontalOrder

### ISSUE THREAD

**Issue by dgobnto** [metafizzy/isotope#1382]
I need a kind of layout like fitRows with stamp support or Packery with horizontalOrder support.
Possible?

My scenario is a number of items with the same height and a button on the top right corner of the container (items should layout around this button).

The closest I got was with Packery layout and stamp but the order of the items is not always maintained.

![screen shot 2018-03-29 at 12 41 57](https://user-images.githubusercontent.com/8176105/38092171-a71571a2-334e-11e8-875f-94c875ac5577.png)
The "raretive" item (under the button) is not the next element after "artive" in the DOM structure. As expected with Packery, it's the next that fits the gap. But I need to maintain the original order.

Any hints?

Thank you!

EDIT: I was able to reach a nice compromise with the Masonry layout and a little trick.
```
$('.terms').isotope({
   layoutMode: 'masonry',
   masonry: {
      columnWidth: 1,
      horizontalOrder: true
   },
   itemSelector: '.filter',
   stamp: '.terms-reveal'
});
```
Notice `columnWidth: 1`.

**Comment by desandro** [comment]
> I need a kind of layout like fitRows with stamp support or Packery with horizontalOrder support.

Sorry, there is not a layout mode that has all these features.
