### ISSUE TITLE
Sorting transition not working same on all groups

### ISSUE THREAD

**Issue by tarun-nanda** [metafizzy/isotope#1383]
**Test case:** https://codepen.io/desandro/pen/mEinp

Hi,

I use isotope in one my website but after use in the page it's transition effect not display similar on each of my groups. I also use your hiddenStyle and visibleStyle example but it's resolve. Can you please help me how can I resolve this problem in my website.

Website name is http://www.hoaghospitalfoundation.org
and problem is in http://www.hoaghospitalfoundation.org/aboutus/hoag-hospital-story.html page.

Please check and confirm what I do in this.

Thanks,
Tarun Nanda

**Comment by desandro** [comment]
Sorry, I won't be able to debug this production site.  Can you please provide a **reduced test case** demonstrating the issue?  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by tarun-nanda** [comment]
Hi Desandro,

Today I create one demonstration for you. Please check attach file. In this each category transition of **hidden style and visible style** is coming different. Please check.

In this I use your hiddenStyle and visibleStyle example but it's not resolve.

I hope you understand my problem and provide better solution for solve this problem.

Thanks,
Tarun Nanda
[isotope-demonstration.zip](https://github.com/metafizzy/isotope/files/1883613/isotope-demonstration.zip)
