### ISSUE TITLE
Sorting around point instead of closest to the top

### ISSUE THREAD

**Issue by vin-ni** [metafizzy/isotope#1386]
I'm trying to build the following composition for various sized elements. (Later I'll remove one element and add a new, different sized one) I'd like them to arrange like isotope, but around a certain point instead of "closest to the top". I couldn't find a layout mode that would be right for this. 

Here's an image of what I try to achieve:
![group 6 1](https://user-images.githubusercontent.com/9806572/38425814-33b377dc-39b5-11e8-874b-5f0ec83c428c.png)

**Test case:** 
I tried to do it with stamps, but it doesn't keep the order.
https://codepen.io/Vin-ni/pen/eMPoJm

Maybe someone has an idea on how to achieve this.

**Comment by desandro** [comment]
hi! Thanks for reporting this issue. The closest solution I have is hacked version of Packery. See https://github.com/metafizzy/packery/issues/62#issuecomment-33448503
