### ISSUE TITLE
Quick Search + Select + Filter On Load

### ISSUE THREAD

**Issue by thiendinh91** [metafizzy/isotope#1387]
Hi,

I'm stuck on having the select choose a selected item on load and getting the search to work at the same time as well.

I am using the below script to achieve the quick search at the moment. I tried using var initialfilter and attempting to tie it to the select dropdown which didn't work.

Am I better off using a on load and adding selected into the option?

Thanks!

`		
		// quick search regex
		var qsRegex;

		// init Isotope
		var $grid = $('.grid').isotope({
			itemSelector: '.element-item',
			layoutMode: 'fitRows',
			filter: function() {
				return qsRegex ? $(this).text().match( qsRegex ) : true;
			}
		});

		// filter functions
		var filterFns = {

			// show if number is greater than 50
			numberGreaterThan50: function() {
				var number = $(this).find('.number').text();
				return parseInt( number, 10 ) > 50;
			},

			// show if name ends with -ium
			ium: function() {
				var name = $(this).find('.name').text();
				return name.match( /ium$/ );
			}

		};

		// bind filter on select change
		$('.filters-select').on( 'change', function() {
		// get filter value from option value
		var filterValue = this.value;
		// use filterFn if matches value
		filterValue = filterFns[ filterValue ] || filterValue;
		$grid.isotope({ filter: filterValue });
		});

		// use value of search field to filter
		var $quicksearch = $('.quicksearch').keyup( debounce( function() {
		qsRegex = new RegExp( $quicksearch.val(), 'gi' );
		$grid.isotope();
		}, 200 ) );

		// debounce so filtering doesn't happen every millisecond
		function debounce( fn, threshold ) {
			var timeout;
			return function debounced() {
				if ( timeout ) {
				clearTimeout( timeout );
				}
				function delayed() {
				fn();
				timeout = null;
				}
				timeout = setTimeout( delayed, threshold || 100 );
			}
		}
`

**Comment by desandro** [comment]
This is a lot of code. For your sake and for your users, I recommend limited the number of behaviors you are trying to use together.

Yes, this can be done. But it grows in complexity.

**Comment by thiendinh91** [comment]
Thanks, I have cleaned out the unnecessary code already as we only needed the search and select dropdown.

I'm assuming I`ll need to write the code as out of the box you do not support having both filter and search available?

Thanks!!

**Comment by thiendinh91** [comment]
Thanks for the input, I have managed to create the filters required. Most likely not the cleanest JS but here for reference.

Any chance you would be able to assist with initial filter with the below code? Thanks!
```

// quick search regex
var qsRegex;
var filterValue;
var filterValue2;

// init Isotope
var $grid = $(".grid").isotope({
  itemSelector: ".element-item",
  layoutMode: "fitRows",
  filter: function() {
    var $this = $(this);
    var searchResult = qsRegex ? $this.text().match(qsRegex) : true;
    var selectResult = filterValue ? $this.is(filterValue) : true;
    var selectResult2 = filterValue2 ? $this.is(filterValue2) : true;
    return searchResult  && selectResult && selectResult2;
  }
});

// bind filter on select change
$("#filters-2").on("change", function() {
  // get filter value from option value
  filterValue = $(this).val();
  console.log(filterValue);
  $grid.isotope();
});

$("#filters-1").on("change", function() {
  // get filter value from option value
  filterValue2 = $(this).val();
  console.log(filterValue2);
  $grid.isotope();
});

// use value of search field to filter
var $quicksearch = $("#quicksearch").keyup(
  debounce(function() {
    qsRegex = new RegExp($quicksearch.val(), "gi");
    $grid.isotope();
  })
);

// debounce so filtering doesn't happen every millisecond
function debounce(fn, threshold) {
  var timeout;
  return function debounced() {
    if (timeout) {
      clearTimeout(timeout);
    }
    function delayed() {
      fn();
      timeout = null;
    }
    setTimeout(delayed, threshold || 100);
  };
}

```

**Comment by desandro** [comment]
To set initial filter, set `filter` in the Isotope init options. Here's how to get the value from a single `select`:

```
var $filtersSelect = $('.filters-select');

// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.element-item',
  layoutMode: 'fitRows',
  filter: $filtersSelect.val(),
});

// bind filter on select change
$filtersSelect.on( 'change', function() {
  // get filter value from option value
  $grid.isotope({ filter: this.value });
});
```

See demo https://codepen.io/desandro/pen/PRVBRP . View in debug mode to see initial filter
