### ISSUE TITLE
Is there a recommended way to sort based on media breakpoints?

### ISSUE THREAD

**Issue by rbhalla** [metafizzy/isotope#1388]
Right now I'm laying out an asymmetric set of elements. I currently have them properly resizing, with the column size changing as the width of my screen changes. For aesthetic reasons, I'd also like to tweak the order of the elements depending on the screen size.

I realise this is possible to do using javascript, but if possible I'd like to keep as much of this logic in css if possible. My initial reaction was to look to see if flex's order property was supported, but I haven't managed to get it working.

Is there a recommended approach? Or is the only solution to have javascript code reacting to screen size?

**Comment by desandro** [comment]
> look to see if flex's order property was supported

Isotope does not support flex-box. #1234.

> Is there a recommended approach?

Nope, this sort of behavior can be achieved with your own JS. If you have a **reduced test case** I could better advise on a solution.

**Comment by rbhalla** [comment]
Thanks for the quick reply. I don't think it's much more than what you're already thinking. A grid of items, with a screen resizing. I simply want to change element order for different screen widths. 

I'll take a look at how I can do this using js. Feel free to close this issue unless you'd like to keep the discussion open.

**Comment by desandro** [comment]
Take a look at [sort functions](https://isotope.metafizzy.co/sorting.html#getsortdata-functions) for more complex logic with Sorting
