### ISSUE TITLE
Issue using select filter & search together

### ISSUE THREAD

**Issue by nathan-pbd** [metafizzy/isotope#1390]
Hi,

I am having an issue creating using search and select filters at the same time, whilst having a default filter value. I am able to get both working simultaneously, but cannot get them both to work together.

This is my code for the select filters:
		    
	  var $container = $('.portfolioGrid'),
	
	  $container.isotope({
	    itemSelector : '.portfolioBox',
	    filter: '.featured-project'
	  });
	
	  // filter buttons
	  $('select').change(function(){
	    var $this = $(this);
	    
	    // store filter value in object
	    // i.e. filters.color = 'red'
	    var group = $this.attr('data-filter-group');
	    
	    filters[ group ] = $this.find(':selected').attr('data-filter-value');
	    // console.log( $this.find(':selected') )
	    // convert object into array
	    var isoFilters = [];
	    for ( var prop in filters ) {
	      isoFilters.push( filters[ prop ] )
	    }
	    console.log(filters);
	    var selector = isoFilters.join('');
	    $container.isotope({ filter: selector });
	    return false;
	  });

and this my code for the search

	var qsRegex;
	
	// init Isotope
	var $grid = $('.portfolioGrid').isotope({
	  itemSelector: '.portfolioBox',
	  layoutMode: 'fitRows',
	  filter: function() {
	    return qsRegex ? $(this).text().match( qsRegex ) : true;
	  }
	});
	
	// use value of search field to filter
	var $quicksearch = $('.quicksearch').keyup( debounce( function() {
	  qsRegex = new RegExp( $quicksearch.val(), 'gi' );
	  $grid.isotope();
	}, 200 ) );
	
	// debounce so filtering doesn't happen every millisecond
	function debounce( fn, threshold ) {
	  var timeout;
	  threshold = threshold || 100;
	  return function debounced() {
	    clearTimeout( timeout );
	    var args = arguments;
	    var _this = this;
	    function delayed() {
	      fn.apply( _this, args );
	    }
	    timeout = setTimeout( delayed, threshold );
	  };
	}

Would really appreciate any help with combining these.

Thanks!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

You could fork the [filters + buttons demo](https://codepen.io/desandro/pen/mCdbD)

**Comment by nathan-pbd** [comment]
Thanks for the reply.

Of course. Here you go - https://codepen.io/nelsonathan/pen/aYxjqV

As you can see, the multiple filters work together seamlessly, but the search doesnt work at all.

**Comment by desandro** [comment]
Thanks for that. Here's how to do it. See demo https://codepen.io/desandro/pen/qowMeB

``` js
var qsRegex; // quick search regex
var filters = {};
var selectFilter; // filter value from <select>s

var $grid = $('.portfolioGrid').isotope({
  itemSelector : '.portfolioBox',
  layoutMode: 'fitRows',
  filter: function() {
    // combine search & select filters
    var $this = $(this);
    var searchResult = qsRegex ? $this.text().match( qsRegex ) : true;
    var selectResult = selectFilter ? $this.is( selectFilter ) : true;
    return searchResult && selectResult;
  }
});

// filter buttons
$('select').change(function(){
  var $this = $(this);
  
  // store filter value in object
  // i.e. filters.color = 'red'
  var group = $this.attr('data-filter-group');
  
  filters[ group ] = $this.find(':selected').attr('data-filter-value');
  // console.log( $this.find(':selected') )
  // convert object into array
  var filterValues = getObjectValues( filters );
  selectFilter = filterValues.join('');
  // console.log( selectFilter );
  $grid.isotope();
  return false;
});

// use value of search field to filter
var $quicksearch = $('.quicksearch').keyup( debounce( function() {
  qsRegex = new RegExp( $quicksearch.val(), 'gi' );
  $grid.isotope();
}, 200 ) );

// -- utils --- //

// replacement for Object.values
function getObjectValues( obj ) {
  var values = [];
  for ( var key in obj ) {
    values.push( obj[ key ] );
  }
  return values;
}

// debounce so filtering doesn't happen every millisecond
function debounce( fn, threshold ) {
  var timeout;
  threshold = threshold || 100;
  return function debounced() {
    clearTimeout( timeout );
    var args = arguments;
    var _this = this;
    function delayed() {
      fn.apply( _this, args );
    }
    timeout = setTimeout( delayed, threshold );
  };
}
```

**Comment by nathan-pbd** [comment]
Thanks for that!

Only issue is that the default value has disappeared. How would I change it so that one of the select boxes is selected by default?

The reason for this is that there are almost 100 items and its causing the website to load really slowly, we I have created a 'featured' category that will display on load.

**Comment by nathan-pbd** [comment]
Any help would be greatly appreciated.

**Comment by desandro** [comment]
You can set `selectFilter` to whatever value you want to start with

``` js
var selectFilter: '.featured-project'
```

Or you can add additional JS to read the initial `select` elements and get their initial value.
