### ISSUE TITLE
Is it possible to have jagged rows autofilled by a placeholder?

### ISSUE THREAD

**Issue by Arepo** [metafizzy/isotope#1392]
Suppose we've got a page with 14 elements, currently sized such that 4 are on each row, which at a different viewport width might have 5 on each row. Ie:

(at current width)
EEEE
EEEE
EEEE
EEXX

(at larger width)
EEEEE
EEEEE
EEEEX

Is there an option, or would it be feasible to add one, such that any leftover space (ie the Xes) is always filled in with some placeholder element? I couldn't find one in the docs, but wasn't entirely sure what I was looking for.

Thanks,

Sasha

**Comment by desandro** [comment]
Is it possible? Yes!

However, there's no simple option for this kind of feature. It would require developing your solution by reading the properties of the layout mode in use. For example, if you're using [`fitRows`, it has `x, y, maxY`](https://github.com/metafizzy/isotope/blob/v3.0.6/js/layout-modes/fit-rows.js#L34-L36).

You can access the layout mode with `_mode()` method (only accessible via instance, not jQuery method).

``` js
var fitRows = iso._mode();
```

**Comment by pmpinto** [comment]
I think this is exactly what I wanted so I'll just leave something here for any future visitors.
Thanks for the tips @desandro 🙌 

<details>
<summary>Snippets below:</summary>

```js
// Create a function to draw these "filler" elements
const drawFillerElements = (gridMode) => {
  const { gutter, element, colYs, columnWidth } = gridMode
  const tallest = [...colYs].sort((a, b) => b - a)[0]

  colYs.forEach((col, index) => {
    const hasSpace = col + gutter < tallest
    const fillerSize = Math.abs(tallest - col - gutter)

    if (hasSpace && fillerSize >= gutter) {
      const fillerTopPosition = col
      const fillerLeftPosition = columnWidth * index
      const filler = document.createElement('li') // This might be different for you

      filler.classList.add('filler')
      filler.style = `
        height: ${fillerSize}px;
        top: ${fillerTopPosition}px;
        left: ${fillerLeftPosition}px;
      `

      element.appendChild(filler)

      window.setTimeout(() => { // We need to inject the element first and only then trigger the transition
        filler.classList.add('is-visible')
      }, 0)
    }
  })
}
```

```js
// Create a function to remove the fillers
const removeFillerElements = () => {
  const fillers = document.querySelectorAll('.filler')

  fillers.forEach((node) => {
    node.addEventListener('transitionend', () => {
      node.remove()
    }, { once: true })

    node.classList.remove('is-active')
  })
}
```

```js
// Draw the fillers on init
const buildIsotopeGrid = (selector, options = {}) => {
  const isotopeGrid = new Isotope(selector, options)

  drawFillerElements(isotopeGrid._mode())

  // Setup layoutComplete event so the filler elements are updated when the isotope grid changes
  isotopeGrid.on('layoutComplete', () => {
    removeFillerElements()
    drawFillerElements(isotopeGrid._mode())
  })

  return isotopeGrid
}
```

Heads up: I also have a set of filter buttons in which I'm also running the `removeFillerElements()` function so the filler elements are removed _before_ the isotope changes actually happen.

Regarding  styles:
Everything that you don't see in the JS, is happening in the CSS. That includes setting the width and margin of these `.filler` elements just like you did for your isotope items, and also setting up transitions on both `.filler` and `.is-active`.
</details>


Here's a demo video of something still in the making:
https://user-images.githubusercontent.com/4265830/111044724-2c3f8380-8442-11eb-998b-36ea138e0df2.mp4
