### ISSUE TITLE
How do I change style of non-matches, rather than hiding them

### ISSUE THREAD

**Issue by creativearc** [metafizzy/isotope#1393]
We have a use case of showing a familiar Isotope grid of square tiles. Sorting and filtering are doing what we need, except for one thing:

The client wants the tiles to _always_ appear. Instead of hiding them, we are going to dynamically apply a CSS style. (Imagine the non-matches dimming instead of hiding)

For example, if the tiles were varieties of Soda, and the filter choice was "Diet," we don't want Diet soda tiles to disappear. We just want to "dim" them with CSS.

Note: We *do* want to keep the standard re-ordering function so the tiles remain in the proper sort order.

**Comment by creativearc** [comment]
To clarify: we want all the sorting features of Isotope - we don't want to abandon any of it's features. We merely want to prevent non-matches from being hidden; we'll dim them instead.

**Comment by desandro** [comment]
Hello! You can filter items with your own jQuery.

``` js
var $items = $('.items');
var filter = '.featured';

$items.filter( filter ).removeClass('is-filtered-out');
$items.not( filter ).addClass('is-filtered-out');
```

You can then use CSS on `is-filtered-out`

``` css
.is-filtered-out {
  opacity: 0.5;
}
```

**Comment by creativearc** [comment]
I think the trick is: we'd want the 'active' results to sort and change position, while the 'dim' tiles would be sent to the back of the order.

I think your example will allow for the setting of a CSS style upon filter, but it doesn't seem to address sorting.

**Comment by desandro** [comment]
See demo https://codepen.io/desandro/pen/WJoOrM/

``` js
var filterSelector = '*';

// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.element-item',
  layoutMode: 'fitRows',
  sortBy: 'selector',
  getSortData: {
    selector: function( itemElem ) {
      return !$( itemElem ).is( filterSelector );
    },
  },
});

var $items = $grid.find('.element-item');

// bind button click
$('.filters-button-group').on( 'click', 'button', function() {
  filterSelector = $( this ).attr('data-filter');
  $grid.isotope('updateSortData').isotope();
  // change is-filtered-out class
  $items.filter( filterSelector ).removeClass('is-filtered-out');
  $items.not( filterSelector ).addClass('is-filtered-out');
});
```

**Comment by desandro** [comment]
The same technique can be used. jQuery's `is`, `filter` and `not` can all use a function as an argument. I leave it to you write the code.
