### ISSUE TITLE
Percentage gutters

### ISSUE THREAD

**Issue by firestar300** [metafizzy/isotope#1394]
Hello !

I tried to use percentages gutters and column width to get 3 cols grid but gutters are not applied to the masonry grid.

**Test case:** https://codepen.io/firestar300/pen/NYVXEj

**Comment by firestar300** [comment]
I tried with another codepen and it works https://codepen.io/firestar300/pen/BreVWw but I don't understand why it works in this case and not the first one.

**Comment by HandHugs** [comment]
It’s because you manually added in all the isotope classes. Remove “js-isotope” class from your grid and “js-isotope-item” from your grid items and it should work. I think you are also missing the “grid” class on your grid. 



Jessie Matanky
303-396-5452
mail@handhugs.com
