### ISSUE TITLE
arrangeComplete does not update after initial arrangeComplete

### ISSUE THREAD

**Issue by steveooo9** [metafizzy/isotope#1397]
Hello,

I am using Isotope for filtering stuff.
On init, arrangeComplete does get called, but not after filtering (`$grid.isotope({ filter: '.foobar' })`).
The thing is, that visually the filter applies and the filter buttons work, but after a filter, arrangeComplete doesn't get updated.

Sometimes (can't really reproduce when), after toggling the filters for some time, it suddenly starts to work and then continues to work.

@desandro Any idea? I am trying to fix this the last 5 hours -.-

**Comment by steveooo9** [comment]
```$(function() {
  var defaults = {
    layoutAttr: 'vertical',
    percentPosition: true,
    stagger: 25,
    transitionDuration: '.375s',
    hiddenStyle: {
      opacity: 0,
      transform: 'translate(0, -.25rem)',
    },
    visibleStyle: {
      opacity: 1,
      transform: 'translate(0, 0)',
    },
  };
  var filterAttr = 'data-c-filter';
  var filterByAttr = 'data-c-filter-by';
  var filterIdAttr = 'data-c-filter-id';
  var layoutAttr = 'data-c-filter-layout';
  var alwaysOneAttr = 'data-c-filter-always-one';
  var activeClass = 'active';
  var filterFunctions = {
    // Show if there is a '1' in class
    oneTest: function() {
      return $(this).filter('[class*="1"]').length ? true : false;
    },
  };
  var $filters = $('[' + filterAttr + ']');

  // Events
  var events = {
    'schaetze': {
      onArrangeComplete: function(event, filteredElements) {
        console.log('onArrangeComplete');
      },
      onLayoutComplete: function(event, laidOutElements) {},
      onRemoveComplete: function(event, removedElements) {},
    },
  };

  $filters.each(function() {
    var $filter = $(this);
    var $filterElements = $($filter.attr(filterAttr));
    var id = $filter.attr(filterIdAttr);

    if (!$filterElements.length) {
      return;
    }

    var $filterBys = $filter.find('[' + filterByAttr + ']');
    $filterBys.filter('.' + activeClass).slice(1).removeClass(activeClass);
    var $filterBy = $filterBys.filter('.' + activeClass).first();
    var filterByValue;

    if ($filter.is('[' + alwaysOneAttr + ']') && !$filterBy.hasClass(activeClass)) {
      $filterBy = $filterBys.first();
      $filterBy.addClass(activeClass);
    }

    filterByValue = $filterBy.attr(filterByAttr);
    filterByValue = filterFunctions[filterByValue] || filterByValue;

    $filterElements.on('arrangeComplete', _.debounce(function(event, filteredElements) {
      if (events[id]) {
        events[id].onArrangeComplete(event, filteredElements);
      }

      $(this).find('.focuspoint').focusPoint({
        throttleDuration: 125,
      });
    }, 250));

    if (events[id]) {
      $filterElements.on('layoutComplete', _.debounce(events[id].onLayoutComplete, 250));
      $filterElements.on('removeComplete', _.debounce(events[id].onRemoveComplete, 250));
    }

    $filterElements.isotope({
      filter: filterByValue,
      layoutMode: $filter.attr(layoutAttr) || defaults.layoutAttr,
      percentPosition: defaults.percentPosition,
      stagger: defaults.stagger,
      transitionDuration: defaults.transitionDuration,
      hiddenStyle: defaults.hiddenStyle,
      visibleStyle: defaults.visibleStyle,
    });

    $filter.on('click', '[' + filterByAttr + ']', function() {
      var $filterBy = $(this);
      var filterByValue;

      if (!$filter.is('[' + alwaysOneAttr + ']') && $filterBy.hasClass(activeClass)) {
        filterByValue = '*';
      } else {
        filterByValue = $filterBy.attr(filterByAttr);
        filterByValue = filterFunctions[filterByValue] || filterByValue;
        $filter.find('.' + activeClass).removeClass(activeClass);
      }

      $filterBy.toggleClass(activeClass);

      $filterElements.isotope({
        filter: filterByValue,
      });

      console.log('this does trigger everytime and isotope works fine except that it does not trigger arrangeComplete, so I do the following ugly hack below:');

      // TODO: Ugly hack, fix later
      $filterElements.trigger('arrangeComplete', [$filterElements.isotope('getFilteredItemElements')]);
    });
  });
});```

This is some major code of this script. The `console.log('this does trigger..')` part is important, because this does trigger like intended, but it doesn't trigger `arrangeComplete`. @desandro Any ideas?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by steveooo9** [comment]
@desandro Does this code look ok for you? (esp. the isotope and events parts?)

Well, I can't reproduce this in a test case... I added some logs to a test case and found another thing, maybe related, because I tested something else. Here is the testcase: https://codepen.io/anon/pen/vjYoNm?editors=1010

When you change the filter normally, everything works (only one arrangeComplete), but if fastly switch filters (probably because one filter is still animating (so 2 filter switches in < .375s), I then get multiple arrangecompletes.. (I'm on Chrome 65, Mac). Don't know if same issue.

But what's interesting:
I needed to get the arrangeComplete trigger, so I tested it by adding some infinite loop via setTimeout:
https://codepen.io/anon/pen/gzOVXz?editors=1010

What this does (not in this codepen, but on my code) is that the first 1-2 iterations of this loop, where `$grid.isotope()` was called twice, it started showing arrangeComplete. I tested it with a simple setTimeout of 1000 or 2000ms, but this didn't work. Somehow, after nth-times of .isotope() somehow arrangeComplete was called..

Maybe all this is related? If you have further questions, please ask. I am working on this bug for 7+ hours :)

**Comment by desandro** [comment]
Thanks for that.

Regarding the staggered multiple `arrangeComplete` being triggered. This is likely caused by how the browser handles transitionend event when another transition is triggered on an already-transitioning item. I'm not sure if its related to your original issue.

I'm sorry, but without a reduced test case I cannot debug this issue. My recommendation is to try removing options for hiddenStyle & visibleStyle, and transitionDuration.

**Comment by steveooo9** [comment]
@desandro Ah, I made a new test case where I could reproduce the bug!!
https://codepen.io/anon/pen/MGYJoG

It should log `trigger` and `onArrangeComplete`.

After clicking on a filter, only `trigger` get's updated to know that the button runs to this important code. But also `onArrangeComplete` should trigger.

Hard to reproduce, but maybe you have success: If you hysterically change trigger fast, after some time, `onArrangeComplete` starts to show up and then it seems that it's almost everytime there.

If you have any further questions, please ask. I need a real fix for this and hope this get's fixed very soon..

**Comment by desandro** [comment]
Looks like this CSS was tripping up Isotope:

``` css
.c-schaetze-no-items {
  display: none;
}
```

Isotope is expecting transitions to end on those items. My recommendation is to remove `display: none`, and filter out those items when Initializing Isotope

**Comment by steveooo9** [comment]
@desandro Well, This is a CTA block that shows after filtering when no items are there.

Because Isotope needs a flat structure for filtering, I had to do following structure:

```.heading
.item
.item
.no-item```

```.heading
.item
.item
.item
.no-item```

So on `arrangeComplete` I count the .`item` and show `.no-item` when it's needed.
How would I do this without `display: none;`?

**Comment by desandro** [comment]
Another solution is to remove that CTA from the Isotope grid so its not treated as an item.

**Comment by steveooo9** [comment]
> Isotope is expecting transitions to end on those items. My recommendation is to remove display: none, and filter out those items when Initializing Isotope

Wouldn't it be good to do a simple check before transitioning (or waiting for it) to check if it's `display: none` to avoid such things?
