### ISSUE TITLE
Items take long to load

### ISSUE THREAD

**Issue by bhines01** [metafizzy/isotope#1399]
We have a large gallery with about 170 items to filter. Our page takes long to load due to the amount of items that we have. The problem mainly exists in IE 11. We believe this to be a bug because the plugin should be able to handle 170 items. Any ideas? Below is a link to the page.

https://wwwdev.villanova.edu/content/university/programs.html

Thanks!

**Comment by bhines01** [comment]
Would lazy load solve this issue? If so, how do we implement that?

**Comment by santyas** [comment]
On chrome works fine, it takes 3-4 seconds to start. Try with `scrollThreshold`:
https://infinite-scroll.com/options.html#scrollthreshold

You could use jquery append every time you scrollDown, and get 10 or 20 items to the grid.

**Comment by bhines01** [comment]
Please provide instructions on how to implement infinite scroll. It says I need to define the path in the options and I dont know what that path is since Im not loading in a new page. Also, this does not work in IE 11, this is a bug that needs to be addressed asap. We purchased a license and the product should work in ALL browsers. Please advise.

**Comment by bhines01** [comment]
We also have sorting enabled, would infinite scroll even work with these options set?
