### ISSUE TITLE
Images partially loading or stacking in Safari on Mac

### ISSUE THREAD

**Issue by dkoobs** [metafizzy/isotope#1401]
Bear with me as this is my first attempt at this type of issue reporting... It is also my first time implementing Isotope on a site.  The isotope is mostly working great, but users have noticed some issues with images not loading fully when viewing in Safari or Chrome on a Mac. The problem is intermittent, but unacceptable for the client. 

I tried to do a reduced test case, but failed miserably.  The link to the page is https://www.perceptivelife.com/team/#filter=.investment  

Any guidance on this would be of great help to me.

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. Weirdly, I believe the issue is caused by `animation` on `.itemwrap`. When I disabled these styles, it looks to fix the issue.

``` css
.itemwrap, .invwrap {
/* animation-name: fd-zm; */
/* animation-duration: 1s; */
}
```

`animation` styles should not conflict with `transition` styles (which is what Isotope uses). This may be a browser bug.

**Comment by dkoobs** [comment]
I think this may have solved the issue... As I don't see the issue regularly in my environment, I am having some testing done, but should be good to go.  Thanks for your quick response!
