### ISSUE TITLE
How to fix some initial elements? but then continue filtering with shuffle (and hide first fixed items)

### ISSUE THREAD

**Issue by santyas** [metafizzy/isotope#1402]
Hello!

I would like to know if is possible to start a grid with a filter `.home` but with 6 or 7 items fixed that it never change the position, and then start to filter with a multiple checkbox menu WITH SHUFFLE. So when I select a new filter, clear the `.home` items and use the rest of filters with shuffle.

Thank you!

**Comment by desandro** [comment]
> start a grid with a filter .home

See initial filter in the initial options

``` js
$('.grid').isotope({
  filter: '.home'
});
```

> with 6 or 7 items fixed

[Use the `.stamp` option](https://isotope.metafizzy.co/options.html#stamp). If you do use stamp option, make sure the stamps are not selected as items with `itemSelector`.

**Comment by santyas** [comment]
@desandro Excellent! And `.stamp` elements can be ordered with masonry and filtered?
For example:

```
<div class="stamp home"></div>
<div class="grid-item cars"></div>
<div class="grid-item bikes"></div>
```

**Comment by desandro** [comment]
> And .stamp elements can be ordered with masonry and filtered?

No, `stamp` elements are designed to be fixed in place so other elements can be laid out around them.

I you want a set of items to not be filtered, you can do so by adding their selector your your filters

``` js
$grid.isotope({
  filter: '.cars, .home'
});
```

**Comment by santyas** [comment]
@desandro Yes, I got that. But my problem is Im using `shuffle`, so when I goback to home, these first items are re-ordered. We want keep the pos.

What if I hide manually `.stamp`items using css/jquery when filter is not `.home` ?

Thanks!

**Comment by desandro** [comment]
> these first items are re-ordered. We want keep the pos.

Sorry, Isotope cannot do both. If you want fix elements to a certain position, then use `stamp`.
