### ISSUE TITLE
Filters while items loading by json and append loop

### ISSUE THREAD

**Issue by santyas** [metafizzy/isotope#1403]
Hello again!

Big question, Is it possible to use filters while the content of 300 items with images is appending inside a for loop? What happens with next loading items/images while there is an active filter? Important fact, I use only one js/json file/object with 300 items.

Hope its not impossible.
Thank you!

**Comment by desandro** [comment]
If you want to add items, but apply filter & sorting, use [`insert` method](https://isotope.metafizzy.co/methods.html#insert)
