### ISSUE TITLE
Isotope does not load correctly

### ISSUE THREAD

**Issue by mi5studio** [metafizzy/isotope#1405]
Dear,
I asked a question las week because Isotope was overlapping the images and you send me the function imagesloaded() that worked very good. Thanks for that.

Now I'm having a similar issue when I go back to the index after seen a project. 

In this [link](http://www.mi5studio.com/mi5/proyecto.php?id=19) at the very bottom between the footer and the las image there is an icon in the center is a grey icon formed by 4 squares that sends to the index where te isotope is. Most of the time when I click there the Isotope does not load correctly.

This is the code:

`<script>
			// external js: isotope.pkgd.js, imagesloaded.pkgd.js
			$( window ).bind("load", function() {
			// init Isotope
			var $grid = $('.grid').isotope({
			  itemSelector: '.grid-item',
			  percentPosition: true,
			  masonry: {
			    columnWidth: '.grid-sizer'
			  }
			});
			// layout Isotope after each image loads
			$grid.imagesLoaded().progress( function() {
			  $grid.isotope('layout');
			});  

			// store filter for each group
			var filters = {};

			$('#filters').on( 'click', '.button', function() {
			  var $this = $(this);
			  // get group key
			  var $buttonGroup = $this.parents('.button-group');
			  var filterGroup = $buttonGroup.attr('data-filter-group');
			  // set filter for group
			  filters[ filterGroup ] = $this.attr('data-filter');
			  // combine filters
			  var filterValue = concatValues( filters );
			  // set filter for Isotope
			  $grid.isotope({ filter: filterValue });
			});

			// change is-checked class on buttons
			$('.button-group').each( function( i, buttonGroup ) {
			  var $buttonGroup = $( buttonGroup );
			  $buttonGroup.on( 'click', 'button', function() {
			    $buttonGroup.find('.is-checked').removeClass('is-checked');
			    $( this ).addClass('is-checked');
			  });
			});

			// flatten object by concatting values
			function concatValues( obj ) {
			  var value = '';
			  for ( var prop in obj ) {
			    value += obj[ prop ];
			  }
			  return value;
			}

			}); //fin load function  

			</script>`

 
In the header I call jQuery and before closing the body I have:
` <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
	<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>`

Hope anyone can help me please.

Best Regards

**Comment by desandro** [comment]
Looks like you your JS script with `.isotope()` occurs before loading `isotope.pkgd.js`. If you can re-arrange your code so it occurs after `isotope.pkgd.js`, like at the very bottom of the HTML, then it should work.

[Also, you do not need to use `$(window).load()`](https://metafizzy.co/blog/window-load-last-resort/). imagesLoaded handles the loading part for you. If your code is at the end of the page, you don't even need to use `$(document).ready()`

**Comment by mi5studio** [comment]
Dear Desandro, many thanks for your response. If I quit `$(window).load()` the isotope does not work, there are blank spaces between images. Also if y put `isotope.pkgd.js` before the script it doesn't work. Any other suggestion. Many thanks in advanced.

**Comment by desandro** [comment]
There error I'm seeing is still

```
TypeError: $(...).isotope is not a function
```

Which means that `isotope.pkgd.js` has not been loaded before you have tried to call `.isotope()`. If you load `isotope.pkgd.js` before calling `.isotope()`, then this problem will be resolved.

**Comment by mi5studio** [comment]
Dear,
thanks for your response. This is what I'm doing and it is not working, can you please let me know if I'm doing something wrong.

Many thanks in advanced

For example
here is my html

html
header
/header

body
`<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>`

`$( window ).bind("load", function() {
			// init Isotope
			var $grid = $('.grid').isotope({
			  itemSelector: '.grid-item',
			  percentPosition: true,
			  masonry: {
			    columnWidth: '.grid-sizer'
			  }
			});
..........`

`<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>`
/body

**Comment by desandro** [comment]
I'm looking at http://www.mi5studio.com/mi5/index.php#projects The same issue is still present.

Sorry I will not be able to personally debug this issue

**Comment by mi5studio** [comment]
Thanks for your replay, I solve it I put the scripts at the start after <body> and now works perfect. Many thanks again

**Comment by braddalton** [comment]
```
add_action('wp_enqueue_scripts', 'enqueue_custom_scripts');
function enqueue_custom_scripts() {
    wp_enqueue_script('jquery');
    wp_enqueue_script('isotope', 'https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js', array('jquery'), '3.0.6', true);
    wp_enqueue_script('imagesloaded', 'https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js', array('jquery'), '4.1.4', true);
    wp_enqueue_script('custom-isotope', get_stylesheet_directory_uri() . '/iso-settings.js', array('jquery', 'isotope', 'imagesloaded'), '1.0', false);
}

```
Images stop displaying in grid
```
jQuery(document).ready(function ($) {
    var $container = $('.isotope-container');

    $container.imagesLoaded(function () {
        $container.isotope({
            itemSelector: '.isotope-item',
            layoutMode: 'masonry', // Set layout mode to masonry for a grid
            masonry: {
                columnWidth: '.isotope-item', // Set the column width based on the isotope item
                gutter: 20 // Adjust the gutter between items
            }
        });
    });

    $('.isotope-filter a').on('click', function () {
        var filterValue = $(this).attr('data-filter');
        $container.isotope({ filter: filterValue });
        return false;
    });
});
```
