### ISSUE TITLE
my isotope.js elements are overlaping

### ISSUE THREAD

**Issue by DraftProducts** [metafizzy/isotope#1406]
Hello !
If I ask this question, it is because I used the plugin isotope.js and I had a problem, my elements overlap from time to time. You can see it at this url: [draftman.fr/portfolio](https://www.draftman.fr/portfolio) And here is the result [what i have](https://i.stack.imgur.com/0UsPX.png) and here[ what i want
](https://i.stack.imgur.com/FF7zE.png)
and to have the right result I just reloaded the page

Thanks for help you can give me !

**Comment by desandro** [comment]
Looks like this could be resolved with [imagesLoaded](https://isotope.metafizzy.co/layout.html#imagesloaded)
