### ISSUE TITLE
Is it possible to have a "X" button on click to toggle size?

### ISSUE THREAD

**Issue by chriswhiting** [metafizzy/isotope#1408]
I am using the following code in my JS to toggle the size of a grid element when clicked. When a element is clicked, this toggle changes the size of the element, and displays more content.

Currently, the whole element is clickable in order to return it to its previous state. Is it possible to add a close 'X' button that is linked to toggling the state instead of having the whole element clickable?

```
$grid.on( 'click', '.grid-item', function() {
  // change size of item by toggling gigante class
  $( this ).toggleClass('gigante').siblings().removeClass('gigante');
  $grid.isotope('layout');
});
```

https://codepen.io/whitinggg/pen/pLMdWB

**Comment by desandro** [comment]
Sure thing. Here's one way to do it: https://codepen.io/desandro/pen/d71f18c72d7322fc1ff3e2bb938126d3/

``` js
// state variable
var $expandedItem;

// expand when clicked
$grid.on( 'click', '.grid-item', function( event ) {
  var isExpanded = $expandedItem && event.currentTarget == $expandedItem[0];
  if ( isExpanded ) {
    // exit if already expanded
    return;
  }
  console.log('grid-item click')
  // un-expand previous
  if ( $expandedItem ) {
    $expandedItem.removeClass('gigante');
  }
  // set new & expand
  $expandedItem = $( event.currentTarget ).addClass('gigante');
  $grid.isotope('layout');
});

$grid.on( 'click', '.close-button button', function( event ) {
  $expandedItem.removeClass('gigante');
  // reset variable
  $expandedItem = null;
  $grid.isotope('layout');
  event.stopPropagation();
});
```

I'm using a couple lessons from Fizzy School: [State variables](http://fizzy.school/state-variables), and [Replace jQuery this](http://fizzy.school/replace-jquery-this)
