### ISSUE TITLE
Parcel error

### ISSUE THREAD

**Issue by archistico** [metafizzy/isotope#1410]
C:\progetti\siti_laravel\zemi\src\js\isotope.pkgd.js:2903:14: Cannot resolve dependency '../layout-mode' at 'C:\progetti\siti_laravel\zemi\src\layout-mode'
  2901 |     // CommonJS
  2902 |     module.exports = factory(
> 2903 |       require('../layout-mode')
       |               ^
  2904 |     );
  2905 |   } else {
  2906 |     // browser global

**Comment by archistico** [comment]
I copy files /js in my folder and change: '../layout-mode' to './layout-mode'

**Comment by desandro** [comment]
Thanks for reporting this issue. What module loader are you using (Webpack, RequireJS, Browserify)?

**Comment by archistico** [comment]
Parcel

**Comment by desandro** [comment]
If you're using a module loader like Parcel, you can require `isotope-layout` as an npm/Yarn package. Do not require `isotope.pkgd.js`.

```
npm install isotope-layout
```

``` js
// demo.js
var Isotope = require('isotope-layout');

new Isotope( '.grid', {
  itemSelector: '.grid-item',
  columnWidth: '.grid-sizer',
});
```

**Comment by archistico** [comment]
Thank you! Perfect
