### ISSUE TITLE
need help with cellsByRow layout

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/isotope#1412]
hey there.

recently I had to use cellsByRow layout. but I'm having a little trouble with it and I was hoping you can help me with that.
here's my test case https://codepen.io/Mohsen-Khakbiz/pen/KRLrgW
currently this is the layout I'm getting https://tppr.me/kO9Sp
but I need to decrease the space beneath items. to have a layout like this. https://tppr.me/yfIQX

I guess it's just some simple math, but I can't get it. and I think it can be done from here by having the item's position and height https://tppr.me/b4NEW

any help will be pretty much appreciated

**Comment by desandro** [comment]
Thanks for reporting this issue. The layout you're going for cannot be achieved with cellsByRow. The You may be able to do it with [masonry layout mode](https://isotope.metafizzy.co/layout-modes/masonry.html) plus [stamps](https://isotope.metafizzy.co/options.html#stamp) in the corners.

**Comment by Mohsen-Khakbiz** [comment]
oh yeah. didn't think of stamps. thanks!
