### ISSUE TITLE
Multiple Isotope / different initial filters

### ISSUE THREAD

**Issue by rpuddle** [metafizzy/isotope#1413]
Hi Guys, 

Is there a way to have multiple instances of Isotope running on a site, with each instance being on different pages and each having a different initial filter set? I'm trying to setup the page here - 

http://portusandwhitton.co.uk.gridhosted.co.uk/projects/education/

with filter set for 'education' but the homepage needs to be set to display 'show all' on load. 

Hope that makes sense. 

Rich

**Comment by desandro** [comment]
Looks like you were able to figure this out. You can see initial filter in the initialization options.

``` js
```
