### ISSUE TITLE
Sorting with isotope from external json rendered with handlebars

### ISSUE THREAD

**Issue by tiomak** [metafizzy/isotope#1417]
Can't seem to get Isotope sort to work :(

On the client side of a webpage I'm displaying data which comes from an external json with a template using handlebars.js.

I want the users to be able to sort, filter and search the data that is displayed. I've seen that with Isotope can this be achieve successfully. I did manage to get filtering to work.

However I'm stuck with sorting in targeting the class of the object with the getSortData option which value comes from the json. Where I want to reach the p.class = number: (so as to sort by price). 

I'm positive that this can be done. Any ideas or suggestions on what I'm doing wrong?

**Test case:** https://codepen.io/dive69/pen/wXmpVJ

**Comment by desandro** [comment]
Here you go: https://codepen.io/desandro/pen/31be7226af870e6f266dae9d02822294/

1. Initialize Isotope on the container, not the items
2. Use `data-sort` attribute on the links click

**Comment by tiomak** [comment]
Many thanks for solving this issue :)
