### ISSUE TITLE
How to show specific category on page loaded

### ISSUE THREAD

**Issue by zakkento** [metafizzy/isotope#1420]
Hi i want that my first category  shouldn’t be “All”, but another category.
Instead of “All”, I would like to see only “Wood” items when the page is first loaded.

My code is this:

    function projectMasonry(){
        if ( $('#projects').length ){
            $('#projects').imagesLoaded( function() {
              // images have loaded
                      // Activate isotope in container
                $("#projects").isotope({
                    itemSelector: ".project",
                    layoutMode: 'masonry',
                    masonry: {
                        columnWidth: '.grid-sizer'
                    }
                });

                // Add isotope click function
                $(".project_filter li").on('click',function(){
                    $(".project_filter li").removeClass("active");
                    $(this).addClass("active");

                    var selector = $(this).attr("data-filter");
                    $("#projects").isotope({
                        filter: selector
                    })
                })
            })
        }
    }

Thanks!

**Comment by desandro** [comment]
See an initial `filter` option

``` js
$("#projects").isotope({
    itemSelector: ".project",
    filter: '.wood-category',
    layoutMode: 'masonry',
    masonry: {
        columnWidth: '.grid-sizer'
    }
});
```
