### ISSUE TITLE
Load more posts on page scroll

### ISSUE THREAD

**Issue by chriswhiting** [metafizzy/isotope#1421]
I am using Isotope to display all my blog posts in a packery layout, the grid also has some filtering to sort the posts via their category. 

What i would like to achieve is, on the initial page load i would like only a certain amount of items to load (12, for example) then, when the user reaches the bottom of the page it loads another amount of posts to show. Is this possible? 

I read through the issue here (https://github.com/metafizzy/isotope/issues/1358) and i couldn't work out if it was something that was implemented or not yet?

I have tried myself to add in the infinite scroll but i didn't have any success. Could someone help me with this?

Test Case - https://codepen.io/whitinggg/pen/GBgEeg

**Comment by chriswhiting** [comment]
Is this the best way to do what i want to achieve or would a 'load more' button work better?

**Comment by desandro** [comment]
Your code looks good. Looks like the CodePen demo doesn't have proper pages. Do you have a live URL where your page URLs work?

**Comment by chriswhiting** [comment]
Yes i do here it is; http://optimum-ifa.co.uk/wp/news-events/

**Comment by desandro** [comment]
Looks like you need to change your `path` option to a selector string for the link to the next page

``` js
// init Infinite Scroll
$grid.infiniteScroll({
  path: '.pagination__next',
  loadOnScroll: false, // disable loading
  history: false,
});
```

the `path: 'page{{#}}',` was a hack for CodePen demos to load multiple pages.

**Comment by chriswhiting** [comment]
I have made this change to my live link now. I think my i am still missing a part, i am no longer seeing any errors in console for my js file. Now i see the following in console:

- Bad InfiniteScroll path option. Next link not found: .pagination__next - infinite-scroll.pkgd.js
- Disabling InfiniteScroll - infinite-scroll.pkgd.js

Is there something i am missing?

**Comment by desandro** [comment]
In your HTML you need a link that points to the next page for example:

``` html
<a class="pagination__next" href="/page/2">Next page</a>
```

This is what Infinite Scroll uses to determine the URL structure to load the next pages. Given the error message, you are missing that element.
