### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by rulatir** [metafizzy/isotope#1422]
I have an ancient project that uses isotope 2.0.0 and I want to modernize it **first** by moving dependencies under management by npm. Unfortunately the oldest version in the npm registry is 2.1.0. I want to know if 2.1.0 introduced any incompatible changes with respect to 2.0.0. Where is the changelog?

**Comment by desandro** [comment]
[See GitHub releases for changelog](https://github.com/metafizzy/isotope/releases?after=v2.2.0)
