### ISSUE TITLE
Image positioning

### ISSUE THREAD

**Issue by winterhevn** [metafizzy/isotope#1423]
Can someone take a look at the link below. I am using Isotope on Wordpress and I'm just trying to get the new posts to come up in order of date posted (desc). If you check the link there are random dates in the wrong order (ex. Feb 21, Jan 23, Feb 18, Feb 9...) Notice Jan 23 is in the wrong location. I have ruled out Wordpress query since I tried to list the posts without the plugin and they are listing correctly.

http://cloudstreamcreative.com/acenergy/news/

Now I noticed the positioning of each items in the code. Each row runs from 0%, 19%, 39%, 59% and 79% but on the 4th row, the 0% is missing and it goes straight to 19%. Is there any fix for this?

![untitled](https://user-images.githubusercontent.com/41331837/42817180-e575f6a8-89ff-11e8-92af-d479e0f48316.png)

**Comment by desandro** [comment]
Were you able to resolve this issue?

**Comment by winterhevn** [comment]
Hi @desandro no I haven't. I had to use another plugin but my client is still wanting the feature of big and small images. Do you have any idea on why this is happening?

**Comment by gregorme** [comment]
Did you already tried to provide a sorting value for isotope?
Try to add a `data-sort` Attribute to your `<div>-Tags` and extend your isotope settings.

```html
<div class="c-content-isotope-item" data-date="2018-26-07 19:33:00">...</div>
```
and
```javascript
$('.c-content-isotope-gallery').isotope({
            // isotope options
            getSortData: {
                date: function (elem) {
                    return $(elem).attr('data-date');
                }
            },
            sortBy: 'date',
            sortAscending: false
});

**Comment by desandro** [comment]
If you have a **reduced test case** I can better identify the issue.
