### ISSUE TITLE
Isotope Masonry Breaks

### ISSUE THREAD

**Issue by montu1996** [metafizzy/isotope#1424]
I don't know why isotope masonry breaks? 

![1](https://user-images.githubusercontent.com/21100078/42897800-c6bb2280-8ade-11e8-9fd3-141937c0e5b1.png)

but when i remove first two block it works fine. is it related to images ? :thinking:

**Comment by desandro** [comment]
[You may need to set `columnWidth`](https://isotope.metafizzy.co/faq.html#the-first-item-breaks-the-grid)
