### ISSUE TITLE
Filtering inside an accordion

### ISSUE THREAD

**Issue by ciudadanoB** [metafizzy/isotope#1425]
Hi! I'm trying to use Isotope with a dropdown filter, inside a jQuery-ui accordion. Here's the example: https://codepen.io/ciudadanob/pen/ejBobY

In the first load it works correctly, you can open/close the accordions, you can filter with the dropdown and it works. But after you've filtered in one, when you click on the other accordion to open it, it only shows the dropdown menu, but the height for the elements seems to be 0. If you select a year (in the example), then it works again. I'm not sure why it's happening, but any help would be fantastic.

Thanks for an amazing project!

**Comment by desandro** [comment]
Isotope works when elements are visible in order to properly hide/reveal them with transitions. One way to resolve this is to only use Isotope when the accordion is open, and not link both Isotope instances together.
