### ISSUE TITLE
Always animate all items when filtering?

### ISSUE THREAD

**Issue by xyralothep** [metafizzy/isotope#1426]
Hi,

I was wondering if it was possible to animate all elements when Isotope is filtered, just to give a visual confirmation that filtering has occurred?  For example I have a filter called 'Work', and all the elements visible on the page when you first visit it are tagged Work, so when you click on the filter it looks like nothing has changed as only elements below the fold have been filtered out.  I guess I'd just need them to shrink/fade out and then fade back in.

Cheers,
James

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. Sorry, no this behavior is not supported in Isotope.
