### ISSUE TITLE
Sorting by drop down

### ISSUE THREAD

**Issue by CallumRocks** [metafizzy/isotope#1429]
This is just a small 'How do I' for those wondering how to sort items based upon a value inside of a drop down (select). I could only find people having issues with it, so I fixed another's jsfiddle.

**Example of Sort by with a Drop Down** 
http://jsfiddle.net/jb6twq5c/78/

**Comment by desandro** [comment]
See [Filtering - other UI](https://isotope.metafizzy.co/filtering.html#other-ui) - [select example CodePen](https://codepen.io/desandro/pen/jubmr) or others in [Extra examples](https://isotope.metafizzy.co/extras.html#extra-examples)
