### ISSUE TITLE
Filter Results count 

### ISSUE THREAD

**Issue by nabbs** [metafizzy/isotope#1430]
Hi

i have the following code and would like to extend it by showing the filtered results count.

      var myTheme = window.myTheme || {},
        myTheme.Isotope = function() {
        var isotopeContainer = $('.isotopeContainer');
        if (!isotopeContainer.length || !$().isotope) return;
        $(window).on('load', function() {
            isotopeContainer.isotope({
                itemSelector: '.isotopeSelector'
            });
            $('.isotopeFilters').on('click', 'a', function(e) {
                $('.isotopeFilters').find('.active').removeClass('active');
                $(this).addClass('active');
                var filterValue = $(this).attr('data-filter');
                isotopeContainer.isotope({
                    filter: filterValue,
                });
                e.preventDefault();                
            });
        });
    };
    myTheme.Isotope();

where can i add the [getFilteredItemElements]( https://isotope.metafizzy.co/methods.html#getfiltereditemelements )

thanks for your help.

**Comment by gregorme** [comment]
Take a look at the Events documentation
https://isotope.metafizzy.co/events.html#arrangecomplete

**Comment by nabbs** [comment]
@gregorme thanks for the link. can you please tell me where i would put the code in my function? please?

thanks

**Comment by gregorme** [comment]
Try the following (not tested)
```javascript
$(window).on('load', function(){
    
    isotopeContainer.on( 'arrangeComplete', function(event, filteredItems){
        console.log('Isotope arrange completed on ' + filteredItems.length + ' items');
    });

    isotopeContainer.isotope({
        itemSelector: '.isotopeSelector'
    });

    // ... 
});
```

**Comment by nabbs** [comment]
@gregorme brilliant! that works perfectly. 

thanks very much!
