### ISSUE TITLE
One element form every category on load

### ISSUE THREAD

**Issue by ipnextOne** [metafizzy/isotope#1431]
Hi, 

is it possible to show only one element from every category on load and that randnom?
Thanks for every idea

Mathias

**Comment by gregorme** [comment]
I think you have write your own litte function for that.

- on document.ready loop all categories
- count the items of the category
- create a random number in range of amount of items
- select the item by ist index number and add a new CSS class (the same on all categories)
- filter isotope by the given class
- now you should see only one item of each category in a random mode on page load
