### ISSUE TITLE
Grid not calculating correct height when using filter.

### ISSUE THREAD

**Issue by silvanicus** [metafizzy/isotope#1432]
Hi!
I have a bug in a gallery build with isotope.
In case, If you load the page and then  filter with reef-28 it will miscalculate height of the whole grid. You can see at the end it breaks the layout. After you filter several times it works but always at the beginning is breaking

**Case:** https://www.thereefresorts.com/gallery

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like there's a lot of scripts and behaviors interacting on this page. Sorry, but I cannot debug a live site. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
