### ISSUE TITLE
Vanilla JS combination filters with a function

### ISSUE THREAD

**Issue by NoahWilcox** [metafizzy/isotope#1434]
Hey @desandro , would you happen to have a Vanilla JS version of the following pen? I had been looking into getting this to work but ran across your pen that already had the functionality I wanted. Problem is I would need it in Vanilla as opposed to jQuery. 

https://codepen.io/desandro/pen/owAyG

**Comment by desandro** [comment]
Here you go! https://codepen.io/desandro/pen/pOjMdx

Added to [extra examples](https://isotope.metafizzy.co/extras.html#extra-examples)
