### ISSUE TITLE
Appending new items with filters on causing items to show up then disappear

### ISSUE THREAD

**Issue by hendrasan** [metafizzy/isotope#1435]
**Test case:** https://codepen.io/hendrasusanto/pen/VGveRz

Every time you click load more, I append 2 new A items and 1 new B item. 

Try selecting filter A, then click load more. There should only be 2 A items appended, however, the B item shows up on top left then transitions to hiddenStyle.

Is there any way to only show the appended items with the current active filter?

**Comment by desandro** [comment]
Thanks for reporting this issue.

> Is there any way to only show the appended items with the current active filter?

Use [`insert` method](https://isotope.metafizzy.co/methods.html#insert)

> Appends elements into container element, adds elements as items, and arranges items with filtering and sorting.

**Comment by hendrasan** [comment]
Here's a pen of the same issue using `insert`

https://codepen.io/hendrasusanto/pen/rZOEyY

The "flicker" still happens.

If a filter is on, can you append/add elements without showing elements that doesn't have the active filter?

**Comment by desandro** [comment]
> If a filter is on, can you append/add elements without showing elements that doesn't have the active filter?

Sorry, no. Isotope still triggers the hide transition on newly added items that are filtered out. I feel this is a good behavior as it indicates new items have been added even though they need to be hidden.

**Comment by hendrasan** [comment]
I agree, though since it appears in the top left of the container before disappearing, it looks a bit weird.

**Comment by skiokko** [comment]
This issue happen also without any filter active. If I remove and Item and the Insert it again it appear and disappear immediately....
