### ISSUE TITLE
Avoid positioning animation but keep transitions at the start

### ISSUE THREAD

**Issue by Surt** [metafizzy/isotope#1436]
Hi guys,

I wanted to hide the positioning animation at the start and keep the hiddenStyle to visibleStyle transitioning, but I can't make it work.
I tried many things (filtering none at the start with all hidden, then filtering again showing the elements (too much time and processor), I tried to hide the grid then show and firing event, ...)

What I'm doing now is setting visibility:hidden for the grid items, and setting them visible after layoutComplete so I can avoid the positioning effect. I just want the transitioning for hiddenStyle to visibleStyle on load. But it doesn't work:, it shows all the items already positioned, without transition animation.

```
    $grid.isotope('on', 'layoutComplete', function (event, filteredItems) {
        $('.grid .grid-item').css('visibility', 'visible');
        $grid.isotope( 'revealItemElements', filteredItems );
    });
```
I tried with this too

```
    $grid.isotope('on', 'layoutComplete', function (event, filteredItems) {
        $grid.isotope( 'hideItemElements', filteredItems );
        $('.grid .grid-item').css('visibility', 'visible');
        $grid.isotope( 'revealItemElements', filteredItems );
    }); 
```

Any help?

**Comment by Surt** [comment]
Seems that the documentation or something on my code is wrong. My filteredItems where empty, so I changed the closure 
```
$grid.isotope('on', 'layoutComplete', function (filteredItems) {
     // console.log(filteredItems); // seems to work well.
}
```
My problem now is that the code is firing in each filtering, not just at the start. :(

I just want to hide the initial positioning.

**Comment by desandro** [comment]
> I wanted to hide the positioning animation at the start and keep the hiddenStyle to visibleStyle transitioning

> I just want the transitioning for hiddenStyle to visibleStyle on load

Sorry, I'm having trouble understanding what you're trying to achieve. But, overall, Isotope may not be well suited for this kind of specialized behavior. `hiddenStyle` and `visibleStyle` are designed to work together so the same kind of transition occurs on hide & reveal. Isotope may not be the correct solution if you need this behavior.

**Comment by Surt** [comment]
Hi @desandro 

actually, I'm using the filtering option, the main isotope functionality. When I said "I just want" I meant "I just ask for it".
  My problem is that when I first load the page, the "masonry" layout makes the items jump, I resolve it just hiding the grid until load.
For my second request, I want the same effect of "filtering" from "none" to any kind of results. You know, the animation defined in hiddenStyle, visibleStyle.  But I don't want the page to hide all suddenly at the start, then showing it again. 

So, in resume, I want to load the page (with the grid empty) and then watch the Isotope animation placing the items (with stagger).

**Comment by gregorme** [comment]
My suggestion: leave the grid empty and visisible onload. Place your items in an other, hidden wrapper or load them by Ajax. Finally add the items to the grid and use Isotope to show and order them.

**Comment by Surt** [comment]
@gregorme thanks, I will try it. It seems like a lot of work, I was just having the hope of doing it in an easier way, cleaner, more transparent. :)

**Comment by desandro** [comment]
You'll have to develop a custom solution here. I'll leave that to you
