### ISSUE TITLE
How to check for status?

### ISSUE THREAD

**Issue by carlosalvidrez** [metafizzy/isotope#1437]
Before I accidentally "reloadItems", I'd like to see if the div that contains my elements is already enabled with isotope. How would I check for status?

For example:
if( ! $('#x').isotope('isActive') )   $('#x').isotope('reloadItems');

Thanks

**Comment by gregorme** [comment]
Save the initialization of isotope to a local or global variable and check it when you need it.
```javascript
// Variable definitions
var container = null;

// ... some other code

// Isotope initialization
container = $('#x').isotope({... options ...});

// ... any other code

// Events
$('#reload').bind('click', function(){
    if(container){
        // isotope is ready
    }else{
        // no isotope
    }
});
```

**Comment by carlosalvidrez** [comment]
Got it. Many thanks!

**Comment by desandro** [comment]
The way to check if Isotope has been initialized with jQuery is with `.data('isotope')`

``` js
var iso = $('.container').data('isotope');

if ( iso ) {
  // isotope initialized
} else {
  // isotope not initialized
}
```

**Comment by carlosalvidrez** [comment]
Thanks Desandro, will give that a whirl.
