### ISSUE TITLE
Don't hide items when filtering, just rearrange?

### ISSUE THREAD

**Issue by elliottcoe** [metafizzy/isotope#1438]
I'm filtering a load of items with 3 different filters, instead of hiding the items that don't fit the filter, I just want to bring the ones that do to the top and push the others down, I've seen I could do something like this with sorting, but I think that might not working quite well with multiple selectors.

**Comment by gregorme** [comment]
You can define a sorting function instead of a sorting value. With this function you can create a complex logic that fits your requirements.

**Comment by desandro** [comment]
See #901 & demo https://codepen.io/desandro/pen/zGZywM
