### ISSUE TITLE
How to query current isotope object's setup properties

### ISSUE THREAD

**Issue by carlosalvidrez** [metafizzy/isotope#1439]
Quick question, how does one know what properties (filters for example), have been applied to an already instantiated isotope object/element? 

I'd like to, based on its current settings, apply or not further filters.

Thanks!

**Comment by desandro** [comment]
It's available in the instances `options` property

``` js
// with jQuery, get instance
var iso = $('.grid').data('isotope');
console.log( iso.options );
// => { filter, sortBy, masonry, ... }
```

**Comment by carlosalvidrez** [comment]
Thank you very much!
