### ISSUE TITLE
Layout breaking after using different columnWidths

### ISSUE THREAD

**Issue by sirbene** [metafizzy/isotope#1443]
Hi there!

I made a responsive grid with a column variation. Unfortunately Isotope/Masonry is breaking the layout.
Check out my pen: https://codepen.io/anon/pen/MPWGBV
The last row with the 2 column-items is not working. I've already added a grid-sizer but it's still not working.

How can I fix this? Thanks in advance! :)

**Comment by desandro** [comment]
Thanks for reporting this issue.

Looks like you need to set the [Masonry options](https://isotope.metafizzy.co/layout-modes/masonry.html) within a 'masonry' object.

``` js
container.isotope({
    layoutMode : 'masonry',
    masonry: {
      columnWidth: '.grid-sizer',
      itemSelector : '.grid-item',
    },
    percentPosition: true,
});
```

See demo https://codepen.io/desandro/pen/45dce5a18010f7cacc6c0155b6fa8ed5/

**Comment by sirbene** [comment]
It is working now, thanks a lot!

**Comment by sirbene** [comment]
![resize](https://user-images.githubusercontent.com/43672953/46907848-5e6af500-cf19-11e8-8a27-1adee2e40acf.jpg)
This happens on window resize, is there a way to fix this without refreshing the page?

**Comment by desandro** [comment]
Sorry I'm not able to reproduce that overlap.
