### ISSUE TITLE
method appended does't work 

### ISSUE THREAD

**Issue by balexus** [metafizzy/isotope#1444]
Hello developers. i have created a simple app. User can add divs to container. When i add first div, it create isotope container and place div there - all is correct. But when i add second and so on divs it seems that they are added as no isotope was applied to container> How i see it. Each div will have position: absolute and left,top or right,bottom in the style. First div has these properties all others are not. Can you help me resolve where i am wrong . Compact code is here
```html
<style> 
.top {
	display:block;
	width:150px;
	height:70px;
	border: 1px solid red;
};

#content {
	display:block;
}
.box 
{
	border: 1px solid blue;
	display: inline-block;
	width:250px;
	height:300px;
}


</style>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>

<script>
let count_show = 0;
let posts_loaded = false;
try {
	$(document).ready(function () {
	$(".top").on('click',appendPosts);
	function appendPosts()
	{
		posts_loaded = false;
		let posts_buffer;
		count_show++;
                posts_buffer = '<div class="box"></div>';
	    	if( count_show == 1 ) {
			$('#content').append( posts_buffer ).isotope({
					itemSelector: '.box',
					resizable: false,
   					columnWidth: 250,
				});
				posts_loaded = true;
		}
		else {
			$('#content').append( posts_buffer ).isotope('appended', $(posts_buffer));
			posts_loaded = true;	
		}
	}
});
}
catch(e)
{
	console.log("exceptiion");
	console.log(e);
}

</script>
</head>
<body>
<div class="top">Click to add element </div>
    <div id="content" style="height:2000px; background: rgba(189, 189, 189, 0.41);"></div><!-- /.conts -->
</body>
</html>




[mods.php.zip](https://github.com/metafizzy/isotope/files/2439525/mods.php.zip)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by balexus** [comment]
Sorry for silence. Reduced test case is here 

https://github.com/metafizzy/isotope/files/2439525/mods.php.zip
