### ISSUE TITLE
Migration issues with webpack

### ISSUE THREAD

**Issue by herrvigg** [metafizzy/isotope#1447]
hello,

i've been using isotope with old-fashioned js code using the libraries globally through CDN. Now i'm porting some code to webpack and the migration is not straightforward. The documentation does not explain well how the new interface with the `Isotope` class should be used.

Before, you could just use `$('.my-class').isotope()` and it would handle a lot of cases, initialization, update filter, update layout, everything.  Now with webpack the `isotope()` interface disappears and it seems the only way is to use `new Isotope('my-class')` .This forces to store the instance, it cannot be accessed from a simple CSS selector again. Certainly a stupid question as i'm quite new to webpack but why isn't that possible to have the same interface as before through jQuery prototypes? 

~Though you can also give a jQuery object as in `new Isotope($('.my-class'), options)` ...~
Update: you cannot pass a jQuery object as i first thought.

The interface `Isotope('.my-class', options)` does not handle the case when multiple items are returned by the selector :-(
Also it was very easy to use as it even handled the cases where the selector would return no element.

With the old interface after initialization i could simply recall `$('my-class').isotope({filter: ...})` to only update a specific part such as the filter. What should i use now, is that `arrange({filter: ...})` ?

Also i had some quite nasty filters using values of other variables. Just by calling `$('my-class').isotope()` the filters would be updated but now should it also be used with `arrange()` without any argument?  What is the difference with `layout()`?

thank you

**Comment by desandro** [comment]
Have you looked at the [Isotope & Webpack documentation](https://isotope.metafizzy.co/extras.html#webpack)

----

To use Isotope as a jQuery plugin with Browserify, you need to use jQuery Bridget

npm install jquery
npm install jquery-bridget

```
var $ = require('jquery');
var jQueryBridget = require('jquery-bridget');
var Isotope = require('isotope-layout');
// make Isotope a jQuery plugin
jQueryBridget( 'isotope', Isotope, $ );
// now you can use $().isotope()
$('.grid').isotope({
  // options...
});
```

**Comment by herrvigg** [comment]
thank you,
i don't use Browserify so i actually skipped that part, but it seems it solves the first problem so yes i can be useful. I'll try this just to check but i finally managed to make it work with the Istotope class with a few workarounds.

About the direct usage with the Isotope class, i'm wondering if passing the class selector as a string is the most flexible. If not using a jQuery object it may be better to pass a DOM object. Also the case when the selector returns multiple or no element should be handled.

**Comment by oshihirii** [comment]
@herrvigg i have a [similar issue here](https://github.com/metafizzy/isotope/issues/1450) and was also thrown with the mention of `Browserify` as I don't use it.  Would you mind sharing how you instantiate isotope (for example on page load) and then how you access isotope later in a click function (for example to apply a filter)?  Do you need to instantiate isotope again or can you just do `$('my-class').isotope({filter: ...})`?  Thank You.

**Comment by herrvigg** [comment]
If you use the Isotope class directly (without Bridget which should not only be for Browersify i guess) you have first to instantiate it as written in the examples
```
var iso = new Isotope('my-class', { 
		  itemSelector: '.item',
		  sortBy : 'name',
		  percentPosition: true,
		  layoutMode: 'masonry',
		  masonry: {
			  gutter: 15
		  },
                  filter: { ... }
	  });
```
instead of `$('.my-class').isotope` - note the dot dispappears (*). 

Then later use the methods as described here: https://isotope.metafizzy.co/methods.html
If you want to apply a filter use: `iso.arrange({ filter: ... });` 
If you just have to update the layout: `iso.layout();` 
In some cases, if your filter does not change but need to be re-evaluated, because it depends on external changes, you could simply refresh like this: `iso.arrange();`  which was the equivalent of recalling `$(my-class).isotope()` without argument. I'm not entirely sure it's the best but it works :P

(*) Imo it's not ideal to pass a string instead of a jquery selector / DOM object because you might already have these "under hand". The string forces isotope to recompute the selection and it does not handle multiple results, unlike the direct `$selection.isotope()` call.

In that case the workaround is:
```
    $('.multiple-selection').each( function() {
      new Isotope(this, options);
    });
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you tell me what version of Webpack you are using?

**Comment by RoelZ** [comment]
@desandro , as it seems you are an active moderator, I'm hoping you can elaborate on my following (similar) issue.

I'm using the latest `laravel-mix` to use webpack inside my app.
I tried a Vanilla and the jQuery approach, but both won't return any result on the methods from Isotope.

```javascript
import $ from 'jquery'
import jQueryBridget from 'jquery-bridget'
import isotope from 'isotope-layout'

(function () {
  
  'use strict';

  jQueryBridget('isotope', isotope, $);
  let grid = $('.grid').isotope({ itemSelector: '.grid-item', layoutMode: 'fitRows' });
  grid.isotope('insert', '<div class="grid-item">ITEM</div>');

  console.log(grid.isotope('getItemElements'));

})();
```
So I also tried the basis initialisation (Vanilla, without jQuery and jQuery Bridget), but in both cases the console returns an empty array.

My gut tells me I overlook something simple. But I cannot seem to find it, so I hope anyone can elaborate.

Thank you in advance!

**Comment by RoelZ** [comment]
Although I just wrote the comment above, I'm leaving it here since it cost me a lot of pain and effort, in the hope I can help anyone else with this mind...

Eventually I got it fixed, and if I understand correctly, even @herrvigg second issue.
The catch was `grid.append(content).isotope('appended', content);`
So the `isotope` constructor invokes itself through a `jQuery` selector.

```javascript
import $ from 'jquery'
import jQueryBridget from 'jquery-bridget'
import isotope from 'isotope-layout'

(function () {
  
  'use strict';

  jQueryBridget('isotope', isotope, $);
  let grid = $('.grid').isotope({ itemSelector: '.grid-item', layoutMode: 'fitRows' });
  grid.isotope('insert', '<div class="grid-item">ITEM<div>');
  grid.append(content).isotope('insert', content);

  console.log(grid.isotope('getItemElements'));

})();
```
Though, the funny thing is that `getItemElements` still returns **0 results**. 
But my guess is I'm still misinterpreting the docs.

**Comment by desandro** [comment]
@RoelZ When you use the [`insert` method](https://isotope.metafizzy.co/methods.html#insert), you need to provide an Element or an Array of Elements or a jQuery Object. This is mentioned above in the docs under [`appended`](https://isotope.metafizzy.co/methods.html#appended)

> With jQuery, appended, prepended, and insert will not work with an HTML string, like it does for jQuery's methods. Wrap your HTML string in a jQuery object so it works with Isotope.

``` js
var item = $('<div class="grid-item">ITEM<div>');
grid.isotope('insert', item);
```

**Comment by RoelZ** [comment]
> @RoelZ When you use the [`insert` method](https://isotope.metafizzy.co/methods.html#insert), you need to provide an Element or an Array of Elements or a jQuery Object. This is mentioned above in the docs under [`appended`](https://isotope.metafizzy.co/methods.html#appended)
> 
> > With jQuery, appended, prepended, and insert will not work with an HTML string, like it does for jQuery's methods. Wrap your HTML string in a jQuery object so it works with Isotope.
> 
> ```js
> var item = $('<div class="grid-item">ITEM<div>');
> grid.isotope('insert', item);
> ```

You're so right! And thanks for pointing this one out. It did the final trick for me. 👍 
I guess I was in confusing while trying to build everything without jQuery, but now I am 😉 

Thanks for being such a concerned moderator/developer!

**Comment by desandro** [comment]
I'm locking this thread as its jumped across several different issues. Please open a new issue if you run into trouble with Webpack.
