### ISSUE TITLE
data-attributes are changing after item sorting bug

### ISSUE THREAD

**Issue by antonk9** [metafizzy/isotope#1448]
Hi, 
thank you for isotope plugin.
I found strange behaviour when make a sorting: value of data-project attribute changes. Here are example: 
https://yuush.co.uk/portfolio/  after plugin initialization items have properly data-project attributes(the first element has data-project="dAndAProjectsDesign"), but when we click on "photography" tab the same item becomes hidden, and another element has data-project="dAndAProjectsDesign" in compare with "all" filter.
I have tried change data-project to another data-attribute - but it didn't help. 

Best Regards,
Anton

**Comment by desandro** [comment]
The filters do not use `data-project`. Instead, they use the classes.  So when you click Photography, the filter is set to `.photography` and shows all items with `photography` class.

Looks like you're using an old version of Isotope (v1). You could try [upgrading to the latest](https://isotope.metafizzy.co).

**Comment by antonk9** [comment]
After plugin update works good. Thanks for help.
