### ISSUE TITLE
jQuery and webpack installation

### ISSUE THREAD

**Issue by oshihirii** [metafizzy/isotope#1450]
I have read instructions here:

https://isotope.metafizzy.co/extras.html#webpack

And the following works for me:

```
npm install isotope-layout

// main.js
var Isotope = require('isotope-layout');

var iso = new Isotope( '.grid', {
itemSelector: '.card',
layoutMode: 'fitRows'
});
```

**Edit:**  Actually, console in Chrome developer tools shows:

> Bad element for isotope: .grid

How can I achieve the same using jQuery, I tried the following:

```
npm install isotope-layout

// main.js
var isotope = require('isotope-layout');

var $iso = $('.grid').isotope({
itemSelector: '.card',
layoutMode: 'fitRows'
});
```

But it gives this error:

> $(...).isotope is not a function

The instructions above only mention jQuery in the context of:

> To use Isotope as a jQuery plugin with Browserify...

They don't seem to address a jQuery/webpack scenario.

Thank You.

**Comment by oshihirii** [comment]
I've come across this question:

https://github.com/metafizzy/isotope/issues/1447

And tried the following:

**Installation**

    npm install isotope-layout --save
    npm install jquery-bridget --save

**Main.js**

    var jQueryBridget = require('jquery-bridget');
    var Isotope = require('isotope-layout');
    jQueryBridget( 'isotope', Isotope, $ );

**On content load**
```js
$('.grid').isotope({
  itemSelector: '.card',
  layoutMode: 'fitRows'
});
```

**In the 'on click' handler**  
```js
$(".grid").isotope({
    filter: function() {
        var my_filter = $(this).attr("data-my_filter");
        console.log(my_filter); // this is undefined
        if (my_filter === "foo") {
            console.log("yay");
            return true;
        } else {
            console.log("nay");
            return false;
        }
    }
});
```
And the `my_filter` variable (which should be have the value of the `data-my_filter` attribute of `.card`) is `undefined`.

**Comment by desandro** [comment]
Thanks for reporting this issue. Let's keep discussion at #1447
