### ISSUE TITLE
Isotope reloadItems and filter issue

### ISSUE THREAD

**Issue by NenadObradovic** [metafizzy/isotope#1451]
Hi guys,

Is there any known problem about reloadItems and filter?

I have the problem with items disappearing when use these methods, example I have load more pagination and filter functionalities on the list.
I appended items with load more and use code below to reInit layout after appending
```
itemsHolder.isotope('reloadItems').isotope({sortBy: 'original-order'});
				
setTimeout(function () {
	itemsHolder.isotope('layout');
}, 300);
```
and for filter I used simple code to get the value of clicked items and to filter list
`$itemsHolder.isotope({filter: filterClass});`

But if you first click to filter item and then to load more new items from that category, after that if you click on show all filter item or some other, only items from first category are show and others are hide, then you need to click several times to filtering in order to fix indexing . You can check this video for example https://www.screencast.com/t/uVhml5MQ . It's seem like reloading messed up indexing or something like that.

I forgot to told if items from some category are not visible by default in list then I trigger to load new items and to show/filtering items from that category, like in video example cat3

Best regards,
Nenad

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry I cannot view the video (Flash required).  Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by NenadObradovic** [comment]
Hi Desandro,

I found the problem, if you have any transition style on isotope item then you got this issue with items disappearing, I juts removed that transition and now load more and filter functionality work fine.

Thanks for your time.

Best regards,
Nenad
