### ISSUE TITLE
method appended does't work

### ISSUE THREAD

**Issue by balexus** [metafizzy/isotope#1452]
Hello developers. i have created a simple app. User can add divs to container. When i add first div, it create isotope container and place div there - all is correct. But when i add second and so on divs it seems that they are added as no isotope was applied to container> How i see it. Each div will have position: absolute and left,top or right,bottom in the style. First div has these properties all others are not. Can you help me resolve where i am wrong. **Reduced code is here**
https://github.com/metafizzy/isotope/files/2439525/mods.php.zip

**Comment by balexus** [comment]
Your answer is a bit incorrect. But i found a fix for my issue. Here is it
```javascript
var $item = $('<div class="item" />');
$container.append( $item ).isotope( 'appended', $item );
```
I added "$" before **item**
Now all works fine. Thanks

**Comment by desandro** [comment]
Ah! good catch. Thanks for following up :)
