### ISSUE TITLE
Is itemPositionDataEnabled option missing  in V2?

### ISSUE THREAD

**Issue by Maxenus** [metafizzy/isotope#1454]
I am looking through the documentation for V2 but I am unable to find anything on itemPositionDataEnabled that is actually available in V1. I would like to know the position of every item inside the grid as there are some items which will take up 2 slot instead of 1.

**Comment by desandro** [comment]
Thanks for reporting this issue. [`itemPositionDataEnabled` option was removed in v2](https://isotope.metafizzy.co/v2/appendix.html#upgrading-from-v1). To read item position, you can get the element's `left` and `top` style.
