### ISSUE TITLE
Isotope & Fancybox 3 - Default items display in one column (problem)

### ISSUE THREAD

**Issue by Radzio1615** [metafizzy/isotope#1455]
Hi! I use Fancybox 3 to open html content in lightbox. I want to add there Isotope. Everything works great but i have one problem. By default, items are displayed in one column instead of side by side. When I click any filter everything will be fixed. How to repair this?

Demo:
https://codepen.io/radzio-125/pen/oQYzpe

**Comment by desandro** [comment]
You'll have to add a [JS event for Fancybox](https://fancyapps.com/fancybox/3/docs/#events) to trigger [layout](https://isotope.metafizzy.co/methods.html#layout) on `afterShow`.

See demo https://codepen.io/desandro/pen/aQJaGb

``` js
$('.modal-button').on( 'click', function( event ) {
  event.preventDefault();
  $.fancybox.open( $modal, {
    touch: false,
    afterShow: function() {
      $grid.isotope('layout');
    }
  });
});
```
