### ISSUE TITLE
Isotope and Elementor 

### ISSUE THREAD

**Issue by dimaeromin97** [metafizzy/isotope#1456]
In [Elementor ](https://elementor.com/), DOM elements are created in an external window (iframe).
It turns out that DOM elements are not created from window.HTMLElement but are created from window.parent.HTMLElement (iframe).
Because of this, DOM elements do not pass this check: https://i.imgur.com/4kn3npZ.jpg
To avoid this, I have to do this: https://i.imgur.com/XArW7wr.jpg

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

Related to  metafizzy/flickity#861

**Comment by steve231293** [comment]
Hello @dimaeromin97 , It's not fixed for me, please help. Thanks

**Comment by thejaydip** [comment]
Any updates ?
**Isotope (Masonry) JS library not working in elementor preview mode.**

**Comment by ernilambar** [comment]
Any updates on this?

**Comment by thesublimeobject** [comment]
@ernilambar — are you have the same issue as above? it seems there are a few different threads here, but there is no reduced test case that was ever provided in this thread specifically? could you perhaps detail the issue you're having more specifically?

**Comment by ernilambar** [comment]
I have Elementor widget with post filters with category. In the front end it is working. But in the backend in edit mode in Elementor, filtering was not working. I dug down the issue little bit. After modification of isotope like mentioned in the PR, it is working as expected. https://github.com/metafizzy/flickity/pull/900/files
