### ISSUE TITLE
Itemselector issue

### ISSUE THREAD

**Issue by pixedelic** [metafizzy/isotope#1457]
Is there any way to better target the elements stored in the "itemSelector" option?
Let me explain: unfortunately in our case we have some `.grid-elements` containing nested `.grid-elements`. We don't want that Isotope considers the nested one, but the "itemSelector" option doesn't accept something like `> .grid-elements` (that would be the best solution).

Am I right and (in this case) any workaround?

Here is a simple test case: https://codepen.io/pixedelic/pen/zMMKrZ

Thank you :-)

**Comment by pixedelic** [comment]
Thank you, but unfortunately that's impossible, it is for a very popular WP theme and we can't change the grid of the classes. But I think, however, that it could be a quite usual scenario...

**Comment by desandro** [comment]
One solution is to use JS to add an extra class so you can specify the top-level item elements

``` js
// add grid-item--iso class
$grid.children('.grid-item').addClass('.grid-item--iso');

// init Isotope
$grid.isotope({
  itemSelector: '.grid-item--iso',
});
```
