### ISSUE TITLE
Search field and button filters with initial filter

### ISSUE THREAD

**Issue by neoman666** [metafizzy/isotope#1459]
How would the following example look if I want to load the page not all displayed but only a selection. Something like an initial filter.

https://codepen.io/desandro/pen/mCdbD

I know how a simple Initial Filter looks like. But how does the above example need to be changed?

**Comment by desandro** [comment]
You can set an initial filter to match a selected button

``` js
var $filters = $('#filters');
var $selectedFilter = $filters.find('button.is-checked');
if ( $selectedFilter.length ) {
  buttonFilter = $selectedFilter.attr('data-filter');
}
```

See demo https://codepen.io/desandro/pen/0fbe70f672225a5011436d95d60b8e81/
