### ISSUE TITLE
Is there a way to add a tagging function to the search bar?

### ISSUE THREAD

**Issue by supasmo** [metafizzy/isotope#1460]
Is there a way, once you have typed your search, to submit it and add it to the output area. I also would like to remove a tag from the output area with maybe a little "x" next to the tag? Is this possible?

I have been testing on this pen I've setup with no success. https://codepen.io/supasmo/pen/PXYjNe

Also here is an image of what I'm kind of asking: https://i.stack.imgur.com/1KY5n.png

**Comment by desandro** [comment]
Is it possible: yes! But as to how: I don't have a ready-made demo for this kind of functionality. I'd try taking a look at other plugins that support text inputs and tags. Or you can try building it yourself.

**Comment by supasmo** [comment]
I know it's not an Issue, just was looking for some input from this community. I will start looking around. I have been trying to go the path of altering the output of the text to add/append html with no luck.
