### ISSUE TITLE
Multiple selections with

### ISSUE THREAD

**Issue by samanthatorres** [metafizzy/isotope#1461]
I've been looking through the different demos and have not been able to find an example where the user can select multiple filters per group, and it requires the returned items to have ALL of those attributes, instead of just joining them.

In the CodePen text example, that's actually the HTML output I currently have working on my Wordpress site. Many of the items listed belong to multiple children of the same parent filter. For example, a product could be good for safety and for sun control. How would I put that together?

**Test case:** https://codepen.io/samanthatorres/pen/LMNpPm

**Comment by desandro** [comment]
Thanks for reporting this issue. Currently the code joins the filters together. For example `.safety.sun-control`, which return results that match `.safety` AND `.sun-control`. If you want return results for `.safety` OR `.sun-control`, you would join them with a comma: `.safety, .sun-control`. This change can be made in

``` js
// flatten object by concatting values
function concatValues( obj ) {
  var values = [];
  for ( var prop in obj ) {
    values.push( obj[ prop ] );
  }
  return values.join(', ');
}

see demo https://codepen.io/desandro/pen/685912ba5f4fd1cc424b58728620038d/
