### ISSUE TITLE
Mistake in calculating  Height in first page load 

### ISSUE THREAD

**Issue by masami6871** [metafizzy/isotope#1464]
Hi dear .  first I want to thank for your useful plugin. i love that .
i have a problem , and i really tired , i try a lot to fix that , but i I did not get the result. 

i am a wordpress developer and i build a template with a lot of feature, a part of that is portfolio:

this is my home page : [wordpress.masami.ir](http://wordpress.masami.ir/)

when i load this page for first time isotope can't calculating  Height of grid correctly.
but for next load the page that is correct.
![firstload](https://user-images.githubusercontent.com/29583593/50589009-eff35e80-0e99-11e9-976f-73375199268f.jpg)

i use of your code in [codepen ](https://codepen.io/desandro/pen/nFrte) page 

look at this : 
in this photo in first page load isotope calculating  height of the page (( 55.65px )) : 
![firstloadheaight](https://user-images.githubusercontent.com/29583593/50589032-026d9800-0e9a-11e9-97ae-e6149b33ebc7.jpg)

and in reload the page this problem solved automatically.  now isotope calculating  height of the page (( 825.4px )) : 
![reloadheaight](https://user-images.githubusercontent.com/29583593/50589084-5f694e00-0e9a-11e9-931e-7f5fb89ed678.jpg)

i did not see this problem in localhost !!! 
please help me .  i really tired and confused. 
thanks my friend.

**Comment by Ohhhh** [comment]
same here!

**Comment by masami6871** [comment]
> same here!

what do you mean ?

**Comment by Ohhhh** [comment]
> > same here!
> 
> what do you mean ?

Same issue

**Comment by Ohhhh** [comment]
i think i figured out... try to layout after each image loads

https://isotope.metafizzy.co/layout.html#imagesloaded

`// layout Isotope after each image loads
$grid.imagesLoaded().progress( function() {
  $grid.isotope('layout');
});`

**Comment by masami6871** [comment]
> i think i figured out... try to layout after each image loads
> 
> https://isotope.metafizzy.co/layout.html#imagesloaded
> 
> `// layout Isotope after each image loads $grid.imagesLoaded().progress( function() { $grid.isotope('layout'); });`

no, i try that.  but that was not the solution.i am so angry. :(

**Comment by team-zindex** [comment]
@Ohhhh & @desandro  Thank you. Work well.

**Comment by Huzaifa1321** [comment]
> @Ohhhh & @desandro Thank you. Work well.

Can you open code again please I'm stuck in this

**Comment by thesublimeobject** [comment]
@Huzaifa1321 — Are you asking to re-open this issue? What is troubling you with regards to the solution presented?
