### ISSUE TITLE
Refresh a photo Gallery after filtering with 2 search Fields (LightGallery + Isotope) 

### ISSUE THREAD

**Issue by PapyIP** [metafizzy/isotope#1465]
Hello, 
Can you please guide me on this. Using [Isotope](https://isotope.metafizzy.co/layout-modes/masonry.html) and [LightGallery](http://sachinchoolur.github.io/lightGallery/), I filter elements of a gallery using 2 search fields. Filtering is not a problem, but I can't refresh the gallery to display only the filtered images. 

Once the gallery is destroyed after filtering, I can't reset it with only the filtered elements.

I made an example on [Codepen](https://codepen.io/PapyIP/pen/ZVxrLo)

Thank's for your help !

**Comment by desandro** [comment]
Sorry, I cannot provide support with LightGallery. It does not provide a robust API for this kind of behavior.
