### ISSUE TITLE
Need to insert more grids with filter containers

### ISSUE THREAD

**Issue by simonebanfi** [metafizzy/isotope#1466]
Hello,
i have used this test case but in my page i need to insert 3 grids with different filter select.
How can i do?
Thank you
Simone

**Test case:** https://codepen.io/desandro/pen/jubmr

**Comment by desandro** [comment]
You can wrap each code instance in a function. I wrote up an article on this concept: [Un-repeat with functions](http://fizzy.school/un-repeat-with-functions)

See demo https://codepen.io/desandro/pen/236026e365b62ebb7f94e66b3eb03f5c

**Comment by desandro** [comment]
Isotope requires that elements be visible in order for items to be laid out correctly. You can either initialize the Isotope grids first, then hide them within tabs. Or, trigger [layout](https://isotope.metafizzy.co/methods.html#layout) after tabs have been shown. If you're using bootstrap, [it'd be on `shown.bs.tab`. ](https://getbootstrap.com/docs/4.2/components/navs/#events)
