### ISSUE TITLE
v3.0.6 use question

### ISSUE THREAD

**Issue by cbastin** [metafizzy/isotope#1468]
Can I use Isotope v3.0.6 in my website?

I am doing a web page and this one have a category site, I wanna use Isotope for that and upload the website to internet, but I don´t know if I have to buy a license. 

Thanks for beforehand

**Comment by desandro** [comment]
Yes, you may Isotope on your website. If you getting paid from this website, then I advise you purchase a [commercial license](https://isotope.metafizzy.co/license.html). Otherwise, if this is a personal project, you may use Isotope under the open-source license

**Comment by cbastin** [comment]
Thank you 
And also thank you for make Isotope 
God bless you!! hehe
