### ISSUE TITLE
Bug when filtering with dynamic content

### ISSUE THREAD

**Issue by vmvelev** [metafizzy/isotope#1469]
I have a dynamic content website (only one page) and using isotope for the first tab only. I will explain what do I get - my question is - how do I fix this?

**Steps to reproduce**
1. Type **hr** in the search field.
2. Open the "Room Location" tab.
3. Clear the **hr** from the search field.
4. Open the "Company Roster" tab.

There goes my pen - https://codepen.io/vmvelev/pen/rPMjRo
The problem is that the pictures are stacked. When you type something (even space) in the search, it arranges them as they should. Here is a gif:
![2019-01-29_13-25-43](https://user-images.githubusercontent.com/7597032/51905257-6ddb5480-23c9-11e9-9e17-8e9202276cb6.gif)

**Comment by desandro** [comment]
1. After you reveal content that has been hidden, you may need to trigger [layout](https://isotope.metafizzy.co/methods.html#layout). If you are using jQuery `.animate()`, layout needs to be triggered after the animation has completed,
2. Or this could be an [imagesLoaded issue](https://isotope.metafizzy.co/layout.html#imagesloaded)
3. [Cache your jQuery objects](http://fizzy.school/cache-jquery-objects)
