### ISSUE TITLE
Custom insert/append animation

### ISSUE THREAD

**Issue by projectssome** [metafizzy/isotope#1470]
I've been using [this solution](https://github.com/metafizzy/isotope/issues/1038#issuecomment-188201238) for a "load more" button, however I wanted the animation coming from the top, for example, not from the right side (as you can see in the gif below or in [this CodePen](https://codepen.io/projectssome/pen/pqVgXR)), but I can't figure out how to do it.

![giphy](https://user-images.githubusercontent.com/44626533/52223709-5a2e6300-288d-11e9-97f7-bc6d9636863b.gif)

I'm trying to achieve something [like this](http://demo.select-themes.com/stockholm6/three-column-grid-no-space/) when clicking the "load more" button.

Thanks in advance,
Luiz.

**Comment by desandro** [comment]
I think a better solution is build off the demos for [insert](https://isotope.metafizzy.co/methods.html#insert) or [appended](https://isotope.metafizzy.co/methods.html#appended). The demo you linked to is a bit complex

+ Insert demo: https://codepen.io/desandro/pen/byqcz
+ Appended demo: https://codepen.io/desandro/pen/ECKiw

**Comment by projectssome** [comment]
But will I be able to filter/search itens that are not showing also? I mean, act like the demo I linked. I didn't add search in the test case because I wanted to make it minimal, but I use it in my actual code.

**Comment by projectssome** [comment]
Hi, @desandro! I tried to work around with insert/appended, but it doesn't look like to be the right way. As you can see in [this test case](https://codepen.io/projectssome/pen/RvZXdE), if you, for example, try to filter for "item-6" it'll only show one item, of course, because only exists before inserting more. In my case, I have a fixed number of items but showing a maximum number of items before loading more, for example, say I have 16 "item-6" in total. It might show, at start, 4 "item-6" among other items, but when filtering, it'll show 8, because it's the maximum number of items to show and when clicking to load more, it'll load the 8 left.

**Comment by projectssome** [comment]
Hi, @desandro! I tried to work around with insert/appended, but it doesn't look like to be the right way. As you can see in [this test case](https://codepen.io/projectssome/pen/RvZXdE), if you, for example, try to filter for "item-6" it'll only show one item, of course, because only one exists before inserting more. In my case, I have a fixed number of items but showing a maximum number of items before loading more, for example, say I have 16 "item-6" in total. It might show 4 "item-6", among other items, at start, but when filtering it'll show 8, because it's the maximum number of items to show and when clicking to load more, it'll load the 8 left.

**Comment by projectssome** [comment]
I tried to make [this test case](https://codepen.io/projectssome/pen/gqxmyV) as minimal as possible in order to be easier to visualize the problem, but I went through everything and still can't figure out how to change this animation to something like the insert/appended animation. Sorry to bother you, I don't know where more to ask.
