### ISSUE TITLE
Select filters with combination & update filter counts

### ISSUE THREAD

**Issue by borninthefuture** [metafizzy/isotope#1471]
Hello,

Thanks in advance!

Looking to use dropdowns (select, option) instead of buttons as per this pen:
Isotope - combination filters, update filter counts (https://codepen.io/desandro/pen/pyxwem)

Is it possible to have the same functionality (count of elements updating) using dropdowns?

My test case just forks the above pen and changes the first set of buttons into drop downs.
**Test case:** https://codepen.io/jonnyjonny/pen/XOVEyy

**Comment by desandro** [comment]
Here's one way to do it: https://codepen.io/desandro/pen/60056b176b7120d3ff3e5885921df00a

``` js
function updateFilterCounts()  {
  // get filtered item elements
  var itemElems = $grid.isotope('getFilteredItemElements');
  var $itemElems = $( itemElems );
  $filterUI.each( function( i, elem ) {
    
    var $elem = $( elem );
    var filterValue = $elem.attr('data-filter');
    if ( !filterValue ) {
      // do not update 'any' buttons
      return;
    }
    
    var count = $itemElems.filter( filterValue ).length;
    var countText = '(' + count +')';
    if ( $elem.is('option') ) {
      countText = $elem.attr('data-name') + ' ' + countText;
      $elem.text( countText );
    } else {
      $elem.find('.filter-count').text( countText );
    }
  });
}
```

The trick is that `<option>` elements should only have text in them, no extra elements. So I added `data-name` to their HTML and used that in changing their text.

**Comment by borninthefuture** [comment]
Thank you very much @desandro  
That worked great!!!
