### ISSUE TITLE
ng-masonry-grid only loads 1 column of grid on second load

### ISSUE THREAD

**Issue by jbiddulph** [metafizzy/isotope#1473]
I am using ng-masonry-grid in my Angular App, I have a problem when I load my list the second time, the list only displays 1 columnrather than a masonry 4 column grid... please help?

**Comment by desandro** [comment]
1. Double check that you are setting [columnWidth](https://masonry.desandro.com/options.html#columnwidth)
2. Sorry, but I can't speak for [ng-masonry-grid](https://github.com/Shailu4u/ng-masonry-grid), you might have to open a separate issue there.
