### ISSUE TITLE
Isotope error

### ISSUE THREAD

**Issue by marcelodilisio** [metafizzy/isotope#1474]
I'm using isotope in the Wordpress Uncode theme. It happens that when I define that a couple of posts are shown with the Isotope module they are not shown. They are in the site code but they do not look online, it just shows a blank space.
When I inspect the code I see the following error:
Uncaught TypeError: Can not read property '1' of null
     at v (app.min.js: 1)
     at g (app.min.js: 1)
     at Object.t.isotopeLayout (app.min.js: 1)
     at Object.t.init (app.min.js: 2)
     at app.min.js: 2
     at app.min.js: 2

Any idea what is happening?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
