### ISSUE TITLE
update Filter data after element changing

### ISSUE THREAD

**Issue by marcelglaeser** [metafizzy/isotope#1475]
Hi and thanks for that library,

I need an update function for the filters. If you have filtered the elements, then edited the elements and used the same filter again, the old elements are still only displayed. Although now more or less elements would have to be displayed, depending on the change to the elements.

how can I realize something like that?

Many Thanks,
Marcel

**Comment by marcelglaeser** [comment]
No one can help?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

You may need to trigger [`arrange`](https://isotope.metafizzy.co/methods.html#arrange-isotope) after items have been edited. Or if you're completely changing out items like in a framework, then use [`reloadItems`](https://isotope.metafizzy.co/methods.html#reloaditems)

**Comment by marcelglaeser** [comment]
I have now made a test ([https://codepen.io/iBeekeeper/pen/QYYzZB](https://codepen.io/iBeekeeper/pen/QYYzZB)), there it works as desired. Found mistakes on my part and now it works. Thank you, a license will be purchased in the next few days ;-)
