### ISSUE TITLE
Filtering does not load all items on first click

### ISSUE THREAD

**Issue by vmvelev** [metafizzy/isotope#1477]
I am having an issue with filtering with isotope. Current setup has the following items:
**Note: I will provide only a few lines of code just to make this simplified, otherwise (as you can see in the example) there are more.**

**Buttons**
```
<div class="btn-group filters-button-group mb-2" role="group">
  <button type="button" class="btn btn-outline-success active" data-filter="*">All</button>
  <button type="button" class="btn btn-outline-success" data-filter=".it">IT</button>
  <button type="button" class="btn btn-outline-success" data-filter=".marketing">Marketing</button>
</div>
```

**Items**
```
<div class="isotope-item it"><img src="images/nikolay-petrov.jpg" class="img-fluid" data-toggle="popover" alt="..."></div>
<div class="isotope-item it" data-number="2"><img src="images/emil-kirilov.jpg" class="img-fluid" data-toggle="popover" alt="..."></div>
<div class="isotope-item it"><img src="images/stefan-petrov.jpg" class="img-fluid" data-toggle="popover" alt="..."></div>
<div class="isotope-item marketing"><img src="images/kety-oliveira.jpg" class="img-fluid" data-toggle="popover" alt="..."></div>
<div class="isotope-item marketing"><img src="images/vasil-tonev.jpg" class="img-fluid" data-toggle="popover" alt="..."></div>
<div class="isotope-item marketing"><img src="images/danny-maiorca.jpg" class="img-fluid" data-toggle="popover" alt="..."></div>
```

**JavaScript**
```
var qsRegex;

$(document).ready(function () {
    var $grid = $('.row').isotope({
        itemSelector: '.isotope-item',
        masonry: {
            columnWidth: 0,
            fitWidth: true
        },
        filter: function () {
            return qsRegex ? $(this).text().match(qsRegex) : true;
        }
    });

    var $quicksearch = $('.quicksearch').keyup(debounce(function () {
        qsRegex = new RegExp($quicksearch.val(), 'gi');
        $grid.isotope();
    }, 200));

    // debounce so filtering doesn't happen every millisecond
    function debounce(fn, threshold) {
        var timeout;
        return function debounced() {
            if (timeout) {
                clearTimeout(timeout);
            }

            function delayed() {
                fn();
                timeout = null;
            }
            timeout = setTimeout(delayed, threshold || 100);
        }
    };
    $('.filters-button-group').on('click', 'button', function () {
        var filterValue = $(this).attr('data-filter');
        $grid.isotope({
            filter: filterValue
        });
    });

    $grid.imagesLoaded().progress(function () {
        $grid.isotope('layout');
    });
});
```

The problem that I have is - whenever I click on some of the items, the first time it loads, only a few items are shown. If you click the same button for second time, all items will load - see the example.

![2019-02-21_10-24-19](https://user-images.githubusercontent.com/7597032/53154220-f0b78f80-35c2-11e9-9126-4f6309704238.gif)

Would you be able to assist with this?

**Comment by desandro** [comment]
Thanks for reporting this issue. 
I'm sorry to see you're having trouble with Isotope. Could you provide a live URL or  **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by vmvelev** [comment]
Hello @desandro 

Here is a live URL - http://vmvelev.pro/front-end/

Thanks!

**Comment by desandro** [comment]
1. Remove the initial  line `var $grid = $('.row').isotope();` So that Isotope is initialized only once
2. Try removing/commenting-out all the `.click()` code that triggers `.isotope('layout')`

I wrote up some lessons in JS if you're writing jQuery that I think could be useful. See [Fizzy School](http://fizzy.school)

**Comment by vmvelev** [comment]
Hi @desandro 

Thank you for the suggestions. These, however, did not help with the issues. Code is changed in the live URL that I provided earlier. Do you have any other suggestions?

**Comment by desandro** [comment]
Sorry, I will not be able to provide personal support for this issue.
