### ISSUE TITLE
Images get overlapped using isotope and imagesLoaded

### ISSUE THREAD

**Issue by aniltudu** [metafizzy/isotope#1478]
Please bear with me as I am new to JavaScript, JQuery, Isotope, and ImagesLoaded. I have reduced my test case as much as I can.

So, the problem is that my images loads perfectly fine initially but when i append isotope elements the images get overlapped. I thought that the problem was with images not getting loaded properly so I used ImagesLoaded but the problem remained.

Also whats the difference between append and insert.

Test case: https://codepen.io/aniltudu/pen/VgJKQg

**Comment by desandro** [comment]
Thanks for this demo! You should be able to use `.imagesLoaded()` on the newly created `$content` variable:

``` js
  $content.imagesLoaded(function() {
    $("#gallery").isotope("insert", $content);
  });
```

---

If you're new to JS & jQuery, I made resource for you: http://fizzy.school - Lessons in JavaScript for anyone writing jQuery

**Comment by aniltudu** [comment]
**Thanks for the solution** and I will definitely read the source you provided. But there is one more problem, I modified the insert example given in [this](https://isotope.metafizzy.co/methods.html#insert) webpage and instead of inserting a random number in div I am inserting images. initial loops display the image properly but on third loop, the images start overlapping each other.

Test case: https://codepen.io/aniltudu/pen/YgzOMa

>I was not able to host the image in a serialized manner. So, If you know any service that helps to do the same or provide serialized images already please provide me with the link. So, I can modify the test case.

**Comment by desandro** [comment]
You could use the same approach. triggering `imagesLoaded` on the newly created content rather than on the container.

``` js
$("#load_more").on("click", function() {
  var elems = [];
  for (var i = 1; i <= 4; i++) {
    var $elem = $(`<div class="col-md-4 gallery_item">
            <div class="gallery_img">
                <img src="./images/gallery/${count}.jpg" alt="">
            </div>
        </div>`);
    elems.push($elem[0]);
    count++;
  }
  
  var $elems = $( elems ).imagesLoaded( function() {
    $gallery.isotope("insert", $elems );
  });
});

```

**Comment by aniltudu** [comment]
Wow, **thanks** @desandro it's working now.
