### ISSUE TITLE
Filtering issue when injecting code into Squarespace site

### ISSUE THREAD

**Issue by NumiSkyPie** [metafizzy/isotope#1479]
Hello,

forgive me as I'm very new to this and trying to suss out this issue I'm having with injecting Isotope and packery into our squarespace page. ([See page here](https://skypie.co))

We use it to filter out sections of our site but some filters create pockets with blank spaces. This also completely breaks on mobile. It starts with the sorting working normally, but after a moment it reloads with images pushed far down the mobile site.

I tried to put together a codepen for this but it doesn't quite work without the squarespace references. See below anyway just in case. 

Codepen: https://codepen.io/skypiestudio/pen/MLNWvM

**Comment by desandro** [comment]
WOW this looks great. I wasn't able to see any gaps. Were you able to resolve this?

**Comment by NumiSkyPie** [comment]
Hi! Thanks.

Unfortunately it is still showing gaps on my end (using Chrome):

![screen shot 2019-02-25 at 10 31 59 am](https://user-images.githubusercontent.com/47904106/53348415-01307880-38e9-11e9-841b-857c899b9d05.png)

The mobile part is also the trickiest, when I use the inspection tool in chrome and toggle device it looks fine, but on an actual phone it loads twice, then breaks on the second load.

**Comment by desandro** [comment]
Aside from unloaded images, I'm not seeing the gaps. Sorry, but I won't be able to provide personal support here.
