### ISSUE TITLE
Why jerks when sorting?

### ISSUE THREAD

**Issue by e5ash** [metafizzy/isotope#1480]
Здравствуйте, использую Вашу библиотеку. При фильтрации последний элемент дергается, подскажите, почему и как это исправить? 

Hello, I use your library. When filtering, the last element twitches, tell me why and how to fix it?

URL: [http://olfrey.ru/portfolio/wp/fastdog/](http://olfrey.ru/portfolio/wp/fastdog/), block with tabs.

**Comment by desandro** [comment]
Looks like this could be a double transition bug: https://isotope.metafizzy.co/faq.html#items-jump-after-transitioning-position

**Comment by e5ash** [comment]
Profit.
