### ISSUE TITLE
Isotope - Load more button with Ajax Call not showing correct layout

### ISSUE THREAD

**Issue by afnanabbasi** [metafizzy/isotope#1481]
I am using ISOTOPE in WordPress to show posts on the front-end. Initially when the page loads, everything displays correctly. However when I click the LOAD MORE button with the Ajax Call, it does loads more posts but they appear at the TOP of the page (which I think is because Isotope is not working on these newly loaded posts using Ajax).

What my ISOTOPE JS file looks like:

``` js
(function ($, root, undefined) {

	$(document).on('ready', function() {

	   // external js: isotope.pkgd.js
	   
         $('.grid').isotope({
	     itemSelector: '.grid-item, .item-mobil',
         masonry: {
	       columnWidth: 100,
	       horizontalOrder: true,
	     }
	     });
	   
	});
})(jQuery, this);
```

What the Ajax load More button file looks like:

``` js
var ajaxurl = "<?php echo admin_url( 'admin-ajax.php' ); ?>";
var page = 2;
jQuery(function($) {
    $('body').on('click', '.loadmore', function() {
        var data = {
            'action': 'load_posts_by_ajax',
            'page': page,
            'security': '<?php echo wp_create_nonce("load_more_posts"); ?>'
        };
 
        $.post(ajaxurl, data, function(response) {
            $('.my-posts').append(response);
            page++;
        });
      
    });
});
```

I notice that when I remove/comment the JS code in the ISOTOPE JS file then the new posts on load more button click appear at the bottom correctly however I see a space under each one of the post blocks.

**Comment by desandro** [comment]
After appending the response to `.my-posts` you'll need to add the new items to the Isotope instance. Your code would look something like:

``` js
$.post(ajaxurl, data, function(response) {
  $('.my-posts').append(response); 
  var $items = $( response ).find('.grid-item, .item-mobil');
  $('.grid').isotope( 'appended', $items );
  page++;
});
```

See [appended](https://isotope.metafizzy.co/methods.html#appended)

**Comment by Jignesh-Savaliya4705** [comment]
@desandro What my understanding is here that we need to add what ever the response we got from the ajax call to apply the isotope on fresh result, but   when i put below code in my file it throws an error that isotope is not a function.

var result = $(data);
var $items = result.find('.item');
$('#main').isotope( 'appended', $items );
