### ISSUE TITLE
Only working after filter

### ISSUE THREAD

**Issue by bbradleyjoness** [metafizzy/isotope#1482]
Hello,

I've been working on playing around with Isotope and it's been super great. The 'Masonry" effect only works AFTER I run a filter. I'm not sure why. After some  searching all over and found some suggestion, such as **$(document).ready(function()**, on how to fix this but I can't seem to get them to work on mine. 

Any help would be great. Here is a codepen project I was playing around on. Thanks in advance.

https://codepen.io/bbradleyjoness/pen/WmwmOW

**Comment by desandro** [comment]
You likely need to set [masonry: { columnWidth }](https://isotope.metafizzy.co/layout-modes/masonry.html#columnwidth).

**Comment by bbradleyjoness** [comment]
@desandro thanks for reaching out. I tried a few with columnWidth but still only triggers the masonry layout AFTER I select any filter. I still have the codepen link up if you need that.

Again, Any help would be greatly appreciated it.

-thanks

**Comment by desandro** [comment]
**1** Isotope should be initialized or re-triggered after the items have been loaded on to the page. The most straightforward way to resolve this is to move the `.isotope()` code into the `.getJSON()` callback


**2** Your selector for the container element should be `.grid`, not `.grid .item`.

``` js
  $.getJSON('https://api.sheety.co/71c2d750-ef77-477a-804f-67aab8d43e5e', function(data) {
    var template = Handlebars.compile($('#item-template').html())
    $('.content').html(template(data))

    $(".grid").isotope({
      itemSelector: ".grid-item",
      percentPosition: true,
      masonry: {
        columnWidth: ".grid-sizer"
      }
    });
  });
```

See demo https://codepen.io/desandro/pen/b6ecb17931eb2e9619c3321e14032c39

**Comment by bbradleyjoness** [comment]
That was my issue. Thank you so much for your help. Keep up the good work!
