### ISSUE TITLE
Search filter based on a specific element within a grid item

### ISSUE THREAD

**Issue by nocturnalmonkey** [metafizzy/isotope#1483]
As I understand it, the search will look at all the content within a grid item to determine which to hide and which to show. My specific issue is my users will be searching for codes which may contain letters in combinations which could appear in random words. Ideally, I'd like to filter based on a child-element.

Example CodePen: https://codepen.io/anon/pen/VRyPvK

**Comment by desandro** [comment]
Thanks for this demo. Let's take a look at the filter function:

``` js
  filter: function() {
    return qsRegex ? $(this).text().match( qsRegex ) : true;
  }
```

We can edit the code so it's searching a child element:

``` js
  filter: function() {
    return qsRegex ? $(this).find('.target-element').text().match( qsRegex ) : true;
  }
```

Or refactor it a bit for readability

``` js
  filter: function() {
    if ( !qsRegex ) {
      return true;
    }
    return $(this).find('.target-element').text().match( qsRegex );
  }
```

**Comment by nocturnalmonkey** [comment]
Awesome! Thank you @desandro :)
