### ISSUE TITLE
Inline styling not being overwritten

### ISSUE THREAD

**Issue by benbagley** [metafizzy/isotope#1488]
@desandro  So I'm currently using hubspot for a blog and filtering using isotype, however, I'm having an issue where if I click onto another tab, then back onto `all` no articles are being shown because of the inline styling.

I am trying to overwrite this using the below code to no avail, so any ideas would be great.

```
<script>           
  $(function(){
    var mostPopular = $('.blog-filters button').filter("[data-filter='all']");
    var postsGrid = $('.posts-grid article');

    if (mostPopular.hasClass('active')) {
      $(postsGrid).filter("[data-category='all']").css('display', 'block');
    };
  });
</script>
```

**EDIT**

I've tried

```
<script>
  $(function(){
    var mostPopular = $('.blog-filters button').filter("[data-filter='all']");
    var $postsGrid = $('.posts-grid article');

    $postsGrid.filter(mostPopular).css({ opacity: 0, display: none }).removeAttr('style');
    $postsGrid.not(mostPopular).css({ opacity: 1, display: block }).removeAttr('style');
  });
</script>
```

Still no luck, the articles still set display none when going back to the `all` filter.

It changes the inline style to block but when I go back onto all after clicking another tab, it's set as display none.

**Test case:** https://preview.hs-sites.com/_hcms/preview/template/multi?blog_listing=true&content_group_id=null&domain=undefined&portalId=4856132&tc_deviceCategory=undefined&template_file_path=FlyingSaucer_November2018_Theme/Blog_new/index.html

**Comment by desandro** [comment]
Were you able to resolve this issue? I don't believe I'm able to see the problem.
