### ISSUE TITLE
TypeError: Cannot set property 'position' of undefined

### ISSUE THREAD

**Issue by munjal-vandana** [metafizzy/isotope#1489]
Error: TypeError: Cannot set property 'position' of undefined

I have installed isotope with webpack. On initialization, it throws this error. 

**Test case:** https://codepen.io/greyb_vandana/pen/KLyjxx

**Comment by desandro** [comment]
If you're using jQuery, you can initialize Isotope as jQuery plugin:

``` js
var $container = $('.nodes_container').isotope({
    // options
    itemSelector: '.nodes',
    layoutMode: 'vertical',
    isResizeBound: true,
    isOriginLeft: true,
    isOriginTop: false
});
```

See demo https://codepen.io/desandro/pen/c47c36659aca31f2986a0b065ff70871
