### ISSUE TITLE
Group items in the default layout

### ISSUE THREAD

**Issue by houseofdoctors** [metafizzy/isotope#1491]
Is it possible to group items similar to this: 

```
Group A
item-1 item-2 item-3 item-4 item-5 

Group B
item-1 item-2 item-3 item-4 
```

but have the same container so when I filter for something they are filtered in that group 

so I have a filter for item-1, I will get this: 

```
Group A
item-1

Group B
item-1
```

I tried to use it with HTML but the items have absolute position so they dont stack correctly.

**Comment by desandro** [comment]
Sorry, Isotope v3 does not support this kind of layout. Isotope v1 did have a layout like this, categoryRows. I have dropped support. See #676
