### ISSUE TITLE
Using multiple containers hide the containers with no elements

### ISSUE THREAD

**Issue by houseofdoctors** [metafizzy/isotope#1494]
I have multiple containers and I want to hide the container which doesnt return any result. 
test case: https://codepen.io/anon/pen/KLryyx?editors=1111

so if you select Photography, the first container return results and the second one doesnt return anything, how can I hide the second container `container-wrapper` ?

**Comment by desandro** [comment]
You can get the number of filtered item elements with [getFilteredItemElements](https://isotope.metafizzy.co/methods.html#getfiltereditemelements)

If it returns 0 you can add behavior to hide the containing element. But be sure to un-hide the container when triggering a new filter, as Isotope needs containers to be viewable to show & hide items.
