### ISSUE TITLE
Get total number of items in multiple contains

### ISSUE THREAD

**Issue by houseofdoctors** [metafizzy/isotope#1495]
I have multiple contains and I want to get the total count # for the elements in all containers. 
test case: https://codepen.io/anon/pen/KLryyx?editors=1111

for example, if you click on web design, total count should be 7 (5 from first container and 2 from second container) . 

Also how can I get the initial count?

**Comment by desandro** [comment]
Use [`getFilteredItemElements`](https://isotope.metafizzy.co/methods.html#getfiltereditemelements)

``` js
  $('.masonry-filters').on( 'click', 'li', function() {
    var filterValue = $( this ).attr('data-filter');
    itemsContainer.isotope({ filter: filterValue });
    var filteredItemCount = 0;
    itemsContainer.each( function( i, container ) {
      filteredItemCount += $( container ).isotope('getFilteredItemElements').length;
    });
    console.log( filteredItemCount );
  });
```

See demo https://codepen.io/desandro/pen/c2cac6b82390f31be41595cd3a49cae1?editors=0011
