### ISSUE TITLE
How do I layout my tiles ?

### ISSUE THREAD

**Issue by bochen2014** [metafizzy/isotope#1496]
![image](https://user-images.githubusercontent.com/8207081/58771929-258fa580-85fa-11e9-9152-5dffad627e1f.png)

I want tile#2 to stack on top of tile #3. is there a way to achieve that?

**Comment by desandro** [comment]
Have you looked at [masonryHorizontal](https://isotope.metafizzy.co/layout-modes/masonryhorizontal.html)?
