### ISSUE TITLE
Duplicate an item in another div with isotope?

### ISSUE THREAD

**Issue by manoncombe** [metafizzy/isotope#1499]
I would like to duplicate one of my articles in the right column ($rightcontainer) when I click on it. However, I don't see any isotope option that allows you to duplicate an item rather than simply move it. Is it possible to keep my item in my left column ($leftcontainer) while adding it to the right? I thank you for your help!

```
`$(window).load(function() {
  var $leftcontainer = $('.articleContainer'),
  $rightcontainer = $('.printContainer'),
  $body = $('body'),
  colW = 100,
  columns = null;

  $leftcontainer.isotope({
    itemSelector: '.article-box',
    percentPosition: true,
    masonry: {
      // use outer width of grid-sizer for columnWidth
      columnWidth: '.article-sizer',
    }
  })
  $rightcontainer.isotope({
    itemSelector: '.article-box',
    masonry: {
      columnWidth: $rightcontainer.find('.printContainer')[0]
    }
  })

  // On click, add article to the right section
  $('.main-section').on( 'click', '.insert-button', function() {
    var $item = $(this);
    $rightcontainer.isotope( 'insert', $item );
    $container.isotope('layout');
  });
});`

```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
