### ISSUE TITLE
help with filtering Isotope via text box 

### ISSUE THREAD

**Issue by bruceH-27** [metafizzy/isotope#1500]
I searched for example code to use a search box for filtering items and found an example at https://codepen.io/desandro/pen/wfaGu.  I was wondering how to modify the filter so that only Items that start with whatever is typed in the search box are shown.  

For example using the code at https://codepen.io/desandro/pen/wfaGu, and type 't' in the text field, rather then seeing the items "Tellurium, Bismuth, Potassium, Thallium, Antimony, Cobalt, Ytterbium, Nitrogen, Plutonium", just have the items "Tellurium, Thallium" shown.  

If there are no items that match the filter how do you reset the filter so that all the items are shown and the search filed is cleared?

Hope that makes sense.
Bruce

**Comment by desandro** [comment]
If you're searching only within a single element, use `.find()` to specify that element:

``` js
  filter: function() {
    return qsRegex ? $(this).find('.name').text().match( qsRegex ) : true;
  }
```

Then, change the RegExp expression to match values that start with the search text, so add `^` to the front:

``` js
  var val = $quicksearch.val();
  qsRegex = val && new RegExp( '^' + val, 'i' );
```

See demo https://codepen.io/desandro/pen/9fdb504fad16daf280d74fd17c785608?editors=1010
