### ISSUE TITLE
chrome will not sort while firefox does

### ISSUE THREAD

**Issue by bruceH-27** [metafizzy/isotope#1501]
Any ideas on why when using isotope with Chrome nothing gets sorted when the page loads or the sort button is clicked.  When I use Firefox and click the button it sorts without any problems.  I'm not getting any errors in the Chrome Developer's tools console.  I do have the latest version of Jquery from their website.

 I'm running a virtual host on a XAMPP server in Windows 10 Pro.  

I am using AJAX to fetch the data from the database and generate a bootstrap 4 card for each user,  consisting of an thumbnail image, username and the date they joined.

```
$sql = "SELECT * FROM `users` WHERE `dateJoined` IS NOT NULL ";
try {
     $stmt = $dBase->prepare( $sql );
     $stmt->execute();
} catch ( PDOException $e ) {
     die( "Failed to run query: " . $e->getMessage() );
}
$result = $stmt->fetchAll( PDO::FETCH_ASSOC );
  foreach ( $result as $record ) {
         $imgPath = "/img/" . $record[ 'thumbnail' ];
        $retVal .= '<div class="grid-item">';
          $retVal .= '<div class="card">';
          $retVal .= '<img class="img-fluid" src="' . $imgPath . '" />';
           $retVal .= '<div class="card-title h4 text-center name">' . $record[ 'name' ] . '</div>';
           $retVal .= '<div class="card-text dateJoined">' . $record[ 'dateJoined' ] .' </div>';
          $retVal .= '</div>';
        $retVal .= '</div>';
     }
}
echo $retVal;
```
The cards are all placed in a <div class="grid"></div>.  I use imagesLoaded to load all the images before initializing  the isotope as follows initially sorting by name (but Chrome doesn't even do that)
```
  var $gallery = $( '.grid' );

 $gallery.imagesLoaded( function () {
               $gallery.isotope( {
                    itemSelector: '.grid-item',
                    layoutMode: 'fitRows',
                    getSortData: {
                         name: '.name',
                         date: '.dateJoined',
	      },
               sortAscending: {
                         name: true
                         date: false,
                },
             sortBy: [ 'name' ]
               } );
          } );

```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by bruceH-27** [comment]
It seems if I add **async : false,** to my Ajax call, Chrome preforms the sorting.
