### ISSUE TITLE
combination filters with toggle buttons - vanilla js

### ISSUE THREAD

**Issue by brandlewco** [metafizzy/isotope#1503]
Looking for help with an inclusive combo filter with toggle, in vanilla js. As well as some clarification, is this with an OR operand, or AND? it appears OR. to make it and, do you just chain the classes?

**Isotope - combination filters with toggle buttons** https://codepen.io/desandro/pen/zrMXQv

**Comment by desandro** [comment]
Here's a vanilla JS demo: https://codepen.io/desandro/pen/OeBOvK

>  is this with an OR operand, or AND? it appears OR. to make it and, do you just chain the classes?

inclusive filter would be *OR* operand

**Comment by brandlewco** [comment]
ah, yes that works! trying to find a way to use this with hash change like [this example](https://codepen.io/desandro/pen/ooEZyj). I'm able to get it to do a single filter, but not multiple filters at a time with join. is there a demo for combination with hash in vanilla js? 
Thanks for all the help!
