### ISSUE TITLE
Site in two languages

### ISSUE THREAD

**Issue by mstudioIL** [metafizzy/isotope#1508]
I have site with two languages: Hebrew that is RTL and English,
I using WordPress and plugin for elementor, what is the best way to align item to the right on Hebrew?
Someone said I need to set "originleft" but how to make ?

**Comment by downFast** [comment]
https://isotope.metafizzy.co/options.html#originleft

**Comment by mstudioIL** [comment]
thanks, but it don't work, I don't have where to add it and make it work only for LTR or RTL

**Comment by downFast** [comment]
this is how you add it 

```
$('.grid').isotope({
  itemSelector: '.grid-item',
  originLeft: false,
  masonry: {
    columnWidth: 100
  }
});
```

**Comment by mstudioIL** [comment]
Thanks, I will try it

**Comment by mstudioIL** [comment]
Hey, sorry for the late answer.
I can't make it to work.
I comment the code on the files and it work for RTL site but not for LTR site
this is the RTL: https://www.noganagarut.com/new/projects/hotels/
this is the LTR: https://www.noganagarut.com/new/en/projects/hotels/
the last post on the LTR need to be on the left not on the right
It is WordPress site with oceanwp theme and Livemesh Addons for Elementor to display the posts.

**Comment by mstudioIL** [comment]
I found something, I add the code
`if (isRTL){
		$('.lae-grid-container').isotope({
			itemSelector: '.lae-grid-item',
			originLeft: false
		});
		
	}`
to JS file, but the first item is getting left:0 and not right:0
while all the others are getting right: some-value.
How to make the first get right:0?
