### ISSUE TITLE
Isotope doesn't work with Ember.js

### ISSUE THREAD

**Issue by hagope** [metafizzy/isotope#151]
I've tried using Isotope with Ember.js and the DOM output is blank...here's a snipped of code within my Ember.view.extend

didInsertElement: function() {
    $container = this.$()
    $container.imagesLoaded( function(){
      $container.isotope({
        masonry: {
          columnWidth: 240
        },
        itemSelector : '.item',
        animationEngine : 'css'
      });
    });
  }

**Comment by desandro** [comment]
Closing this thread as it's a bit old now. If you've run into trouble with Isotope and Ember, please open a new issue :gift:
