### ISSUE TITLE
Snake layout

### ISSUE THREAD

**Issue by dudo** [metafizzy/isotope#1514]
**Test case:** https://codepen.io/desandro/pen/mEinp

Hello! I'm recently in need of laying out objects in a snake or sorts. 

```
1  2  3  4

8  7  6  5

9  0  N  ...
```

After scouring the web for a bit, I decided to just do it myself with brute force. Upon further conversations, some friends pointed me to isotope! Amazing library! All of your stuff is amazing. I'd also say that you are uniquely qualified to help me with this problem. Is this something that isotope (or related library) can do? If not, is it something that is easy enough to add?

Thanks so much for your time!

**Comment by thesublimeobject** [comment]
@dudo i don't think this is possible to do natively in isotope, but you could easily achieve it by adding a `data-sort="${order}"` property to the items, and then using isotope to sort by that property.
