### ISSUE TITLE
Isotope Filtering by ID 

### ISSUE THREAD

**Issue by vulkanus** [metafizzy/isotope#1518]
Hi @desandro  David.

It´s possible to get filtering by ID (#) instead .class in isotope?
Something like this:

$("#filter-metal").click(function() {  $container.isotope({ filter: '#metal' });  }); 

Thank you.

**Comment by thesublimeobject** [comment]
@vulkanus —

off the top of my head, i don't think this is possible. i've never tried it though; using an ID would intrinsically only be for returning a single item, which you could do just as well with some combo of classes, or a custom filter function if you preferred.
