### ISSUE TITLE
How to make isotope js to set its height to grid item?

### ISSUE THREAD

**Issue by NasKadir123** [metafizzy/isotope#1526]
Hi!
As I can see in my developer tools, isotope is setting to "grid-items" its position automatically,
but what about height? I found out a lot of web sites that using isotope and have a smooth bottom. And found out that isotope also can set height to the "grid-items".

Example: https://diefinnhutte.qodeinteractive.com/masonry-portfolio/

My question is - is there an option for this?
Or maybe advice)

Thanks in advance.

**Comment by thesublimeobject** [comment]
@NasKadir123 there is not a native isotope option for setting the height, but you can achieve this by simply setting the heights of the item elements in CSS such that they are even as they are in the example.
