### ISSUE TITLE
Force animate on filtering? 

### ISSUE THREAD

**Issue by runnickrun** [metafizzy/isotope#1528]
Is it possible to force animate *all* items upon filtering, even ones that belong to both sets (currently they are not animated and stay in place if they are in first positions)?

**Comment by thesublimeobject** [comment]
@runnickrun — If you were to force an animation on the first item, what kind of animation would you imagine would occur since it's not moving anywhere: if it's not moving, animation would be difficult since some sort of change in size/location would be necessary for an animation to occur.
