### ISSUE TITLE
Hide Buttons filtering when are no class/image loaded

### ISSUE THREAD

**Issue by vulkanus** [metafizzy/isotope#1530]
Hi,

Can anyone helpme to hide or reveal the filter button when there is no images (yet) loaded, I´m using isotope + infinite-scroll?

**Comment by thesublimeobject** [comment]
@vulkanus in order to do this, you would need to add the 'arrangeComplete' listener to your isotope instance, and when it returns an array of length 0, use a classname or some other JS method to hide the filters. i can provide you with a more explicit example if you can give me some more context for your issue or a codepen.

**Comment by vulkanus** [comment]
hi @thesublimeobject,

Thank you for the reply.
> i can provide you with a more explicit example if you can give me some more context for your issue or a codepen.

In my situation, in my filter in WP, I have aWP query 'posts_per_page' => xxxx and if xxxx is less then 10.
The filter does not work because the images didn´t yet loaded, so, in my case I intent to hide in this situations.

Because if I use 10 post per page in mobile will be overload  it´s lots of imagens :)
Thank you

**Comment by thesublimeobject** [comment]
@vulkanus hey, this really seems to be verging on more of a WP question than it is an isotope question; nonetheless, i'll still try and provide you some direction, but i'm still going to need a lot more information about what you're working with exactly. a codepen would be ideal (per the issue guidelines), but if you could even just paste your code from WP/JS i can probably point you in the right direction. as it stands, i really just don't have enough information.

**Comment by vulkanus** [comment]
@thesublimeobject 

It´s not really a WP issue, or either Isotope.

it´s complicate to give you a codepen, sorry, but I will try it to show you what I meaning in the logs https://pastebin.com/kkY8DiGu

I have some button filters and on the fourth button (and in ASC order) when I press one time, the infinite scroll keeps return 0, because the imagens still not yet ready/append to the page,  (post-per-page is less then 10, I would like to put 1 or 2 post per page), to show some images.
I keep pressing until shows the imagens related to that filter.  Maybe its missing something in my infiniteScroll options I do not know.

$container.infiniteScroll({
transitionDuration: '0.2s',
prefill: true,
path: '.next',
append: '.cell',
outlayer: iso,
status: '.page-load-status',
hideNav: '.pagination',
debug: true,
 }

You can see in live mode / the  working website in this gallery https://www.rgoncalves.net/gallery
But in this page, you will see all the filters working well, because its calling more than 10 posts_per_page (that way will load all the imagens) but in optimization its not good, will overload.

Thank you

**Comment by thesublimeobject** [comment]
> It´s not really a WP issue, or either Isotope.

i'm sorry, if this is not an isotope issue, this really isn't the place to ask the question. as specified in the [contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md), you should really have a reduced test case for _bugs_; this is really a question that better fits stackoverflow/reddit/etc.

that said, as i mentioned before, i'm willing to try to give you a bit of direction to get you pointed in the right direction, but none of the links you posted work, and i'm not able to help you without a complete diagnosis of the issue. for example, in this case i would probably need to see a cross-section of the PHP from your WP page and the full code for infiniteScroll + isotope. without that context, i'm sorry, but there's really no way for me to help.

**Comment by vulkanus** [comment]
> but none of the links you posted work, and i'm not able to help you without a complete diagnosis of the issue.

 @thesublimeobject The links is now working, please check it below

https://www.rgoncalves.net/gallery
https://pastebin.com/kkY8DiGu

When I mention "It´s not really a WP issue, or either Isotope." I mean, in Isotope option or something else, is missing something. In the website (live mode), trough Chrome Devetools, you can se or debug my code.

If you cant, sorry, but it´s what is possible, Thank you anyway for your time.

Cumpz!
