### ISSUE TITLE
isotope on wordpress, and grid layout issue, Need help

### ISSUE THREAD

**Issue by yuyazz** [metafizzy/isotope#1532]
i'm facing two major issue trying to implement isotope on a wordpress custom theme.
i created a custom  archive page, with a custom loop. I managed to display filters and to make isotope filtering working on that page.
1- I have 9 post divided in 3 categories (filters). Depending on the "post_per_page' parameter, if i put 4 post_per_page, clicking on the first filter i'll get 3 posts of that category, but if i click on the second filter i'll get only 1 post of the second category, and 0 on the third parameter.. Because the post are limited to 4, i cannot make isotope work properly. It is not displaying 4 posts per category, but 4 posts in total...As i need to make this work with a load more button, i need to limit the posts display...so how can i achieve this ? is it even possible ?

2- on a second page (blog page) i'm also using an isotope filter to display posts. My grid, working like bootstrap, is the following : 1rst post 12 col, second and third post 6 col, and all others posts 4 col.
Using the filters, I would like the grid to remain the same, i.e. the first item is always 12 columns wide, regardless of its category.

I don't know if I'm making myself clear
here are three images to explain : my original layout is the following:
![test-isotope-layout](https://user-images.githubusercontent.com/7109121/75122552-e11fca80-569e-11ea-9e34-512f9c775b88.jpg)
and whatever filter i click on, i would like to keep this grid layout, for example 
![test-isotope-layout-2](https://user-images.githubusercontent.com/7109121/75122591-9f435400-569f-11ea-82bd-b363e56ec0d3.jpg)

but what i get is this...
![test-isotope-layout-3](https://user-images.githubusercontent.com/7109121/75122593-a2d6db00-569f-11ea-9ca5-bd1914be247e.jpg)

so is it possible to have a custom grid layout with isotope ?

**Comment by thesublimeobject** [comment]
1. yes, this is possible, but this is really more of a wordpress question than it is an isotope question.
2. yes, this is also possible. just set your column width in isotope to the smallest grid item, then style the bigger items to span 2x, 3x, or whatever width you would like them to span.
