### ISSUE TITLE
isotope imagesloaded with requirejs

### ISSUE THREAD

**Issue by dan-777** [metafizzy/isotope#1536]
I am new here and have basic knowledge of javascript. I'm learning. I am trying to find the correct way to include the 'imagesloaded' code using the require.js method. 

Here is what I have that does not work. can you help me out here? 

``` js
requirejs( [
 'https://files.cargocollective.com/c608006/isotope.pkgd.js', 'https://files.cargocollective.com/c608006/imagesloaded.pkgd.js'
], function( Isotope ) {
  //var grid = document.querySelector('.grid');
  var iso = new Isotope( '.grid', {
  		itemSelector: '.grid-item',
  		percentPosition: true,
    	transitionDuration: '0',
  		masonry: {
    		columnWidth: '.grid-sizer',
            gutter: '.gutter-sizer',
            horizontalOrder: true
  		}
  
  });
  
  imagesLoaded( grid ).on( 'progress', function() {
  // layout Isotope after each image loads
  		iso.layout();
	});
  
});
```

Thank you.

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry, I will not be able to provide personal support here.

**Comment by dan-777** [comment]
Thanks for your speedy reply. I think that I solved the issue if anyone else is having trouble with this. Please note that I am new to javascript so this may not be correct... However, it seems to be working:

I noticed that '.grid' in:
`var iso = new Isotope( '.grid', {`
that this should be the same as in the imagesLoaded() function.
I changed` imagesLoaded( grid )` to `imagesLoaded( '.grid' )`

this seems to be working but would love clarification from anyone willing to offer a helping hand.
