### ISSUE TITLE
How to change sort order without jQuery?

### ISSUE THREAD

**Issue by randolf** [metafizzy/isotope#1537]
The documentation shows how to change Isotope's sort order with jQuery, but I'm trying to avoid all these heavy-weight JavaScript libraries.  Is it possible to change the sort order without jQuery?

Documentation:  https://isotope.metafizzy.co/sorting.html

Thanks.

**Comment by thesublimeobject** [comment]
@randolf yes, all of the functionality is the same for sorting with vanilla JS instead of jquery. the [examples](https://isotope.metafizzy.co/sorting.html) all use jquery for simply selecting elements, but the general functionality is the same.

**Comment by desandro** [comment]
See vanilla JS sorting demo https://codepen.io/desandro/pen/Wwabpr
