### ISSUE TITLE
Wordpress Ajax Load More Infinite Scroll layout issues 

### ISSUE THREAD

**Issue by sclkfxcite** [metafizzy/isotope#1539]
**Test case:** https://codepen.io/desandro/pen/mEinp

Hi,

I'm currently using Isotope and Masonry on a website that is using the ALM plugin for infinite scroll.
Using preloaded items is not a problem, as shown here:
![Screenshot 2020-04-06 at 3 38 11 PM](https://user-images.githubusercontent.com/43979180/78534226-a8861b80-781c-11ea-9167-d1be0a0a9647.png)

 However it's when ALM adds new items to the grid where the layout breaks:

![Screenshot 2020-04-06 at 3 33 50 PM](https://user-images.githubusercontent.com/43979180/78533869-3a415900-781c-11ea-9984-542bf6a4ce9d.png)

I'm currently using the shortcode to load infinite scroll, and the closest I've gotten to the solution is an ALM callback function that runs when ALM is done loading new items:

`  window.almDone = function() {
                    $grid.isotope('layout');
                }`

What's another way I can solve this?

**Comment by thesublimeobject** [comment]
@sclkfxcite the solution that you've proposed would have been the type of solution that i would have suggested. when you say, "the closest i've gotten", do you mean the solution above still isn't working?

the test case that you linked doesn't have any of the relevant code that would be needed to debug this. ALM, as far as i know, doesn't naturally integrate/interface with isotope, so i would assume calling the layout function after inserting the items—depending on who you're inserting them—would be necessary; at least that's how i would probably do it. 

i'm happy to try to help more, if necessary, but i will need more information about your specific implementation.
