### ISSUE TITLE
SVG icon vanishes when Isotope is loaded

### ISSUE THREAD

**Issue by lucasfads** [metafizzy/isotope#1540]
I have an SVG icon on my page and it simply vanishes just by loading isotope js file.

Example: https://codepen.io/lucasfads/pen/yLYaRoZ

**Comment by thesublimeobject** [comment]
@lucasfads in codepen, you need to load your external libraries through settings => js. the reason that your icon is disappearing is that your script tag is unclosed. for example, in your codepen, you could replace the isotope url with any other url and your icon would still disappear. just close the script tag `<script src="https://proest.com/js/isotope.pkgd.min.js"></script>` and it will work again; but i would still advice to load isotope through the external library loader that codepen provides.

**Comment by lucasfads** [comment]
> @lucasfads in codepen, you need to load your external libraries through settings => js. the reason that your icon is disappearing is that your script tag is unclosed. for example, in your codepen, you could replace the isotope url with any other url and your icon would still disappear. just close the script tag `<script src="https://proest.com/js/isotope.pkgd.min.js"></script>` and it will work again; but i would still advice to load isotope through the external library loader that codepen provides.

Boy, I'm dumb haha
Thank you so much!

**Comment by thesublimeobject** [comment]
@lucasfads for sure! glad i could help; happens to all of us!
