### ISSUE TITLE
Complexe filtering

### ISSUE THREAD

**Issue by romain-granai** [metafizzy/isotope#1541]
Hi I'm trying to do some kind of complex filtering,
I have actually 2 lists each items of the list must be filtering by "OR" but between the 2 lists it needs to be a "AND" filtering.

I had a look at this post : https://github.com/metafizzy/isotope/issues/144

but couldn't manage to do it and I can't figure out how the "new" function filtering is working.

Here is my example : https://codepen.io/romaingranai/pen/mdemoJP?editors=0010

I think it's a very usual case of filtering, it would be interesting to have that in the documentation or maybe links to examples : I found that one https://codepen.io/desandro/pen/JEojz?editors=0010 but in this case you can select only one item of each list which is not really waht I want to do.

Thank you

**Comment by thesublimeobject** [comment]
@romain-granai did you figure this out? if not, i can pull some code from one of my codebases. i have written a sort like this a few times in the past.
