### ISSUE TITLE
Isotope combination filters with checkboxes - checkbox styling issues

### ISSUE THREAD

**Issue by MarjoJ** [metafizzy/isotope#1550]
(I'm new to isotope, github and JS in general, so I hope I'm doing this right! If this should go somewhere else or if I need to change my demo, please let me know.)

[Demo can be found here.](https://codepen.io/MarjoJ/details/QWyEpQX)

I've made the original's checkboxes look like buttons using labels, so I can style them. However, I'm having trouble with line-breaks. 

When a data-group is pushed to a second line (ie when the width is too small to fit all labels on one line), I want all checkboxes that are not class="all" to group together, so not under the one checkbox of that group that does have the attribute class="all". 

I've tried doing this by using a table (see data-group="size"), and while this results in the desired layout and doesn't break the filtering, it does break the styling of the labels. More precisely, the background no longer changes color properly when (un)checking the checkbox by clicking the label. For all other datagroups, styling behaves as desired. 

Anyone know how to fix this? Many thanks in advance!

**Comment by thesublimeobject** [comment]
@MarjoJ unfortunately, this is a general CSS issue, and not an issue that's specifically related to this library. for trouble with an issue like this, you might try somewhere else like stackoverflow, or perhaps reddit. nonetheless, from a quick glance, you could just wrap the non-"all" buttons in their own div, and then just write a media-query for those specific divs with the other buttons in them to display at full-width when the query breaks. there are certainly other ways to do it as well, but that's just the first thing off the top of my head. hope it helps!
