### ISSUE TITLE
"Bad element for isotope" when using Isotope with Webpack

### ISSUE THREAD

**Issue by petracoding** [metafizzy/isotope#1551]
I followed the guide for usage with webpack. I installed Isotope with _npm install isotope-layout_ and this is my Javascript code:

```
var Isotope = require("isotope-layout");
var isotope = new Isotope(".grid", {});
```

In my HTML I obviously have an element with the class _grid_. Just to be sure, I tested _document.querySelector(".grid")_ and it returns the correct element.

However, in the console I get the following error: _Bad element for isotope: .grid_

**Comment by daniellelecomte** [comment]
I am seeing this as well, even though my grid loads as expected.

**Comment by thesublimeobject** [comment]
@petracoding @daniellelecomte are you all still having trouble with this? if you could post a more comprehensive example, i'd be happy to help.
