### ISSUE TITLE
Removing 'display: none' while resizing.

### ISSUE THREAD

**Issue by budyaaa** [metafizzy/isotope#1552]
Hi ! Its site https://solomon.help/pomogaem/
All is working good but when i am choosing second tab and resize browser all isotope items removing theirs 'display: none' which cause to showing second item behind main.

**Comment by thesublimeobject** [comment]
@HotZee did you get this figured out? i'm not seeing the issue, so i assume you solved it?

**Comment by budyaaa** [comment]
@thesublimeobject yep )

**Comment by ricardofloress** [comment]
How did you solve that problem?

**Comment by ricardofloress** [comment]
@HotZee
