### ISSUE TITLE
Combination filters do not set display:none, instead uses hiddenStyle, creates lots of empty space

### ISSUE THREAD

**Issue by kksmvs** [metafizzy/isotope#1556]
I hope this is the right place to ask a question. Here is my pen, please excuse the horrible style formatting! But did enough to see the effect. 

I am using a Bootstrap card-deck with cards and a set of combination filters and sort. The filters/sort works perfectly, but noticed sometimes when doing a combination filter, while it does display/hide what it's supposed to, for cards that don't match any of the filters, it sets a "display:none" property to it. For those that do match ONE of the criteria, but not all, it is still not shown, but instead of "display:none", it applies "hiddenStyle" to it (which adds the following to the style of the card).
    opacity: 0;
    transform: scale(0.001);
    transition-property: opacity, transform;
    transition-duration: 0.4s;
    transition-delay: 0ms;

The problem with this is it creates a whole bunch of empty space on my page. How do I work around this? I tried overriding the hiddenStyle in the init of the grid, but it doesn't accept "display:none".

**Test case:** https://codepen.io/kksmvs/pen/oNbJLXR

In this example, select "Pale Ale", then "Year Round". You'll see that the correct item is displayed. But when you look in developer tools, you'll see that there's still elements there, just with opacity 0 - such as the one in the attached pic.

![image](https://user-images.githubusercontent.com/11961364/87929524-d4a17180-ca86-11ea-91df-4116c054478c.png)

**Comment by thesublimeobject** [comment]
@kksmvs this seems like standard functionality for isotope, as far as i can tell. what difference in functionality are you expecting? even if the items were completely hidden with `display: none`, as you noted above, the empty space on the page would still be the same, would it not? is there some other content you would expect to fill that white space? maybe i'm not completely understanding your issue.

**Comment by kksmvs** [comment]
@thesublimeobject thanks for your response! :)
No, if it had "display:none" insteady of hiddenstyle, it wouldn't have the extra space at the bottom - as evidenced when the items match one criteria.

**Comment by thesublimeobject** [comment]
@kksmvs what do you mean by "extra space at the bottom"? when i filter and there's only one match—using the example that you gave in the original issue—there's essentially no white-space below the items (perhaps 8-16px, but i would consider that negligible), so i would assume you mean something else? 

_edit_: sorry if i'm misunderstanding you—doing my best to help! :)
