### ISSUE TITLE
"transitionStart" event?

### ISSUE THREAD

**Issue by ianthedev** [metafizzy/isotope#1557]
Is there a "transitionStart" event, which would be triggered when all positioning transitions start?

**Comment by thesublimeobject** [comment]
@ianthedev there is not a transition start method as far as i know. it would probably be fairly easy to add one though, if you forked the repo. look at the source for methods like layoutItems/_layoutItems, as well as for the other events and their handlers like 'layoutComplete'. the logic should be fairly straightforward from there.

**Comment by ianthedev** [comment]
@thesublimeobject Thanks. But that's currently beyond my ability.

**Comment by thesublimeobject** [comment]
@desandro if i added a few new events/handlers would you consider merging them? just curious. i have actually also needed other events a few different times, and it might be useful to have them for at least some subset of the userbase.
