### ISSUE TITLE
Update filter counts with combination select filters

### ISSUE THREAD

**Issue by olliehilton** [metafizzy/isotope#1559]
Hello,

Thanks in advance!

I'm using select options instead of buttons as per this pen:
https://codepen.io/desandro/pen/pbkbBO

Is it possible to have the same functionality (count of shown items) using select instead of buttons?

Im using three select combination filter dropdowns and need the item count to update when select options are selected.

**Comment by thesublimeobject** [comment]
@olliehilton yes, as you see in this pen, https://codepen.io/thesublimeobject/pen/GRZbvqN, you can use the exact same type of functionality in the original example. no matter what type of filtering elements you're using, you can always call the data methods from isotope to return metadata about the instance after filtering.
