### ISSUE TITLE
Filter value not working on custom function

### ISSUE THREAD

**Issue by anta199** [metafizzy/isotope#1560]
I've used a custom function to play with opacity instead of hiding the items.
I want a custom filter item to appear selected as default instead of all items. I know you can do it with the 'filter' value but I can't manage to make it work.

Is there any way to do it?

```
jQuery(function ($) {

  $.fn.hideReveal = function(options) {
   options = $.extend({
     itemSelector: '.item',
     filter: '.slctd',
     hiddenStyle: {
       opacity: 0
     },
     visibleStyle: {
       opacity: 1
     },
   }, options);
   this.each(function() {
     var $items = $(this).children();
     var $visible = $items.filter(options.filter);
     var $hidden = $items.not(options.filter);
     // reveal visible
     $visible.animate(options.visibleStyle);
     $visible.css('pointer-events', 'auto');
     // hide hidden
     $hidden.animate(options.hiddenStyle);
     $hidden.css('pointer-events', 'none');
   });
 };

 $(function() {

   var $container = $('#isotope-list');

   // bind filter button click
   $('#filters').on('click', 'li a', function() {
     var filterValue = $(this).attr('data-filter');
     // use filterFn if matches value

     $container.hideReveal({
       filter: filterValue
     });
   });

 });

 $(function() {

$('#filters').on('click', 'a', function() {


$('#filters li').find('.selected').removeClass('selected');
$( this ).addClass('selected');

    var selector = $(this).data('filter');

    $spcl.isotope({
        filter: selector
    });
});

});

});

```

**Comment by thesublimeobject** [comment]
@anta199 are you just trying to change the filter animation, in general? i think that is what you're saying, but i'm not completely sure. if you could provide me with more of your code, in a codepen, for example, that would really help.

in general, your implementation seems strange, but without working with it, i can't be sure. for instance, in the final click listener block, you're initializing a new isotope instance every single time one of the links is clicked. is that what you're meaning to do? in addition, the variable `$spcl` doesn't seem to be defined anywhere. there are some other issues as well, but i can speak more concretely to them if you can provide an example with a bit more context.
