### ISSUE TITLE
Combining several awesome features into one script

### ISSUE THREAD

**Issue by teebling** [metafizzy/isotope#1566]
Loving isotope, especially some of the features shown off in the ['Extras'](https://isotope.metafizzy.co/extras.html) section of the documentation! :)

I'd like to ask for help here with combining some of the best features from here ^ into one super script. I can get some of them working together but not all of them (something always breaks). Below are the different features and their corresponding demos:

- Inclusive Filtering
- Combination Filtering
- Toggle buttons

https://codepen.io/desandro/pen/zrMXQv

- Quick search

https://codepen.io/desandro/pen/mCdbD

- URL hashing
- Functions 

https://codepen.io/desandro/pen/vErxXj (debug version to show URL hash https://s.codepen.io/desandro/debug/vErxXj)

- Outputting filters to text

https://codepen.io/desandro/pen/JGKyrY

----------

Does anyone know where to start with this? I've tried reading the documentation, forking of codepens, mixing and mashing and just can't get anywhere with it. Any help greatly appreciated :)

**Comment by thesublimeobject** [comment]
hey @teebling, unfortunately this isn't really the place to ask for help on implementing features from scratch. if you have put something together and there's a bug of some sort—something that's broken, directly related to the library—i'd be happy to help you.
