### ISSUE TITLE
Issue integrating functions into inclusive/exclusive filters

### ISSUE THREAD

**Issue by teebling** [metafizzy/isotope#1567]
So far I have had no problems filtering using the `data-filter=".cssclass"` method. 

[In this example codepen](https://codepen.io/teebling/pen/KKMWzvR), click on the 'Odin' button and it will filter the list to 'Odin'. Click the 'Odin' button again and it will remove the filter. The same is also true with the 'Frigg' filter. Great!

However, when I try and use a custom function (in this case, searching a div for matching text), I cannot seem to get isotope to recognise it. Look at the 'Thor' button - you will see that its not selecting a css class like the other buttons, instead it is referencing the function 'searchthor'.

In the jQuery, I have assigned the 'searchthor' function to the variable 'filterFns', [as per the documentation here](https://isotope.metafizzy.co/filtering.html#filter-functions), so that I can then call it easily when I ask isotope to do the filtering. The function just searches for 'or' in an element and if it matches the filter runs.

However, when I try to tell isotope to filter the css filters (`var filter= $target.attr('data-filter');`) AND ALSO any functions `filterFns`, it does not work. The documentation says that I should combine the variables into one like this:

    var filterValue = $target.attr('data-filter');
    filterValue = filterFns[ filterValue ] || filterValue

The `||` meaning 'or'... then ask isotope to filter it. But no matter what I try it doesn't work.

Does anyone know how I can get isotope to ALSO use my functions as well as the default css classes (which are already working)? I can get the 'functions' working as a standalone thing, I just can't get them integrated into my current script.

I think it's because in my script, the filters are stored in an array, and when I run .isotope() it adds and removes filters from that array. How would I get the functions to go into that array? I imagine it would involve modifying these two blocks of code (that actually .push and .slice the array):

```
function addFilter( filter ) {
  if ( filters.indexOf( filter ) == -1 ) {
    filters.push( filter );
  }
}

function removeFilter( filter ) {
  var index = filters.indexOf( filter );
  if ( index != -1 ) {
    filters.splice( index, 1 );
  }
}
```

Cheers!

**Comment by thesublimeobject** [comment]
@teebling i just responded to your other more general issue; i didn't see this one here, so you've already done what i was asking in the other thread anyway!

so, first of all, with regard to the filter function, i noticed that you have an object called `filterFns` with the `searchthor` property, but that object isn't attached to anything, which means it's never going to be invoked. this is why that search function doesn't work.

if you notice, there's an important part to the page you linked that you missed,

```
$('.filter-button-group').on( 'click', 'button', function() {
    var filterValue = $(this).attr('data-filter');
    filterValue = filterFns[ filterValue ] || filterValue; // HERE
    $grid.isotope({ filter: filterValue });
});
```

you might notice the last two lines are actually setting the value of `filterValue` to either the value of the `filterFns` for the current filter value if it exists, or defaulting back to the current filter value. since you didn't assign that variable to any of the properties or methods available by isotope, there is no way for it to know that it exists. 

i would imagine that this will likely solve your second and third issues as well.

**Comment by teebling** [comment]
Hey @thesublimeobject thanks for getting back to me on this :)

Okay yes so I understand that towards the end the `filterValue` variable is calling either `filterFns` or the original `filterValue`. And that I need to attach the filterFns object to _something_ in order for it to be invoked and therefore run with the rest of the script.

How would I go about doing that?

EDIT: I have integrated your suggestion but it still isn't working: https://codepen.io/teebling/pen/KKMWzvR?editors=1010

By the way I've had success with my other ticket and have been able to combine a lot of UI into one script, this is like one of the remaining things on my list to try :) After that I'll publish it as a codepen.

**Comment by thesublimeobject** [comment]
@teebling hey there—so i want to first point you to [this example from the "extras" section](https://codepen.io/desandro/pen/owAyG/); it should give you exactly what you're looking for as far as a better way to understand the issues here. while it's obviously not a direct match, all of the concepts you're working towards are there. if you still can't get it figure out, feel free to ping me with an updated pen.
