### ISSUE TITLE
How do I access filters through external URL and highlight only active filter class in the menu?

### ISSUE THREAD

**Issue by thedivtagguy** [metafizzy/isotope#1568]
**Test case:** https://codepen.io/thedivtagguy/full/eYzvgJO

Hi! I've attached a link to what I could pull together for a test case above. I've also discussed the issue in detail over on Stackoverflow and in the interest of keeping it in one place, here is a link to that: 

[https://stackoverflow.com/questions/64530859/how-do-i-access-filters-through-external-url-and-highlight-only-active-filter-cl](https://stackoverflow.com/questions/64530859/how-do-i-access-filters-through-external-url-and-highlight-only-active-filter-cl)

The summary of my issue is as follows: 

1. While the URL hash does get updated, you can't actually visit the link and see a sorted grid. A video of the problem is here: https://gofile.io/d/5aJ4oA

2. I've added links to the URL hashes in my main menu but for some reason, all of them are getting highlighted as active links and none of them actually work or filter the grid. 

You can try this out by going here: https://thedivtagguy.com/#filter=.coding

Notice how you'll have to click on the `Data and Coding` in the second filter menu to actually sort the grid. Nothing is being sorted when you visit from the link itself. 

What can I do to fix this?

**Comment by thesublimeobject** [comment]
@thedivtagguy hey, did you get this figured out? it looks like you got some activity and marked an answer correct, too. i looked at your site and it seems to be working correctly now, yeah?

**Comment by thedivtagguy** [comment]
Hey! Yeah this worked. Should I post the code that I used to make this
happen?

**Comment by thesublimeobject** [comment]
you don't have to; although, you can if you want! i just wanted to make sure you got it solved and get the issues closed out if you did. glad you got it sorted out.
