### ISSUE TITLE
Uncaught ReferenceError: $grid is not defined

### ISSUE THREAD

**Issue by Kroesss** [metafizzy/isotope#1570]
Hi all,

I am trying to get Isotope to work, and I have an issue where it keeps giving me an error "Uncaught ReferenceError: $grid is not defined" when I try to add a filter. I am using code from the docs to try and get it to work.

I made a jsfiddle with the bare minimum, and for references sake, I'll include the complete HTML-test of my test below. What am I doing wrong?

https://jsfiddle.net/dyu7vjwz/

```
<!DOCTYPE html>
<html>
    <head>
        <title>Isotope test</title>
		<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
		<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
		<style>
		span{cursor:pointer;border:#000 1px solid;margin:10px}
		.grid-item{border:#000 1px solid; margin:10px}
		</style>
    </head>
    <body>
	<div>
		<span id="cat_a_span">Cat a</span>
		<span id="cat_b_span">Cat b</span>
		<span id="cat_c_span">Cat c</span>
	</div>
	<div class="grid">
		<div class="grid-item cat_a">A1</div>
		<div class="grid-item cat_b">B2</div>
		<div class="grid-item cat_a">A3</div>
		<div class="grid-item cat_c">C4</div>
	</div>
	<script>
	$('.grid').isotope({
		itemSelector: '.grid-item',
		layoutMode: 'fitRows'
	});
	$('#cat_a_span').click(function(){
		$grid.isotope({filter:'.cat_a'});
	});
	$('#cat_b_span').click(function(){
		$grid.isotope({filter:'.cat_b'});
	});
	$('#cat_c_span').click(function(){
		$grid.isotope({filter:'.cat_c'});
	});
	</script>
    </body>
</html>
```

**Comment by thesublimeobject** [comment]
hey there, @Kroesss —

it looks like you just forgot to set your instance to a variable for later use.

```
let $grid = $('.grid').isotope({
	itemSelector: '.grid-item',
	layoutMode: 'fitRows'
});
```

**Comment by Kroesss** [comment]
Yes, that was it! Thank you.

I just followed the docs, maybe it would be usefull to let those incluse this as it is easily missed.

**Comment by thesublimeobject** [comment]
@Kroesss they docs do include it—i actually copied that code block from the docs.

**Comment by Kroesss** [comment]
@thesublimeobject Okay, then I must have missed it. Thanks anyway!

**Comment by thesublimeobject** [comment]
@Kroesss no worries!—

i did just re-check and i'm guessing that you copied one of the examples from the first page, which doesn't necessarily explicitly reference what i copied above, but if you looked deeper into some of the other docs, there are instances that show what i copied above (for examples, under "filters" about halfway down).

glad i could help! :)
