### ISSUE TITLE
Two identical isotope menus affecting each other‘s selected filter?

### ISSUE THREAD

**Issue by ballmannweber** [metafizzy/isotope#1576]
We use the Isotope script in both the content area of the website as well as in the mobile navigation. So in mobile, the filter menu exists twice without affecting the other – and we're looking for a way that clicking on one of the options in one menu is reflected in the other.

Thanks for help!

**Comment by thesublimeobject** [comment]
@ballmannweber — Please read the [contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md). 

> All bug reports and problem issues require a reduced test case. Create one by forking any one of the CodePen examples from the docs.

While this is not necessarily a bug with the library itself, I would be happy to try and point you in the right direction, but without a test case/reference to your code, it's going to be difficult. So if you could create a Codepen, or if you have a link to the site in which the issue already exists, that would be helpful.

Generally, without anything to reference, I would say that your best bet would be creating some sort of shared state that both menus can reference, where events from either menu are reflected as a state change in both places. You could also forgo the shared state, and just propagate any change to either menu to the other one, but I'm not sure if this will make sense as an abstract concept, which is why having something to use as an example would be helpful.

**Comment by ballmannweber** [comment]
I deleted the already pasted code out of my post because it looked so complex. 
sorry!

we basically have the problem, that we use isotope both inside the landingpage to filter the shown entries as well as on the mobile navigation where we would like to shown the visitors the same filters. but since the mobile menue a) don’t closes by clicking on a filter link and b) the other menu inside the landingpage doesn’t reflect those clicks I am looking for a solution.

I also thought the URL hash good be good solution but I couldn’t find a way to make the example code on code pen work with our site or to expand our code to work the url hash.

but if we could generate urls by clicking on the mobile filter menu it would solve the problem, because this would also reflect within the menu inside the landingpage’s content, right?

this is our current code: 

`var $container = $('#container');
		$('.filters a').click(function() {
			$('.filters a').removeClass("current");
			$(this).addClass("current");
			var selector = $(this).attr('data-filter');
			$container.isotope({
				filter: selector
			});
			return false;
		});
		$(function() {
			$container.isotope({
				itemSelector: '.element',
				percentPosition: true,
				masonry: {
					columnWidth: '.grid-sizer',
					gutter: '.gutter-sizer'
				}
			});
		});
		$container.imagesLoaded().progress(function() {
			$container.isotope('layout');
		});`

**Comment by thesublimeobject** [comment]
@ballmannweber —

I'm sorry, but I really need to see the entirety of your code in order to help you. Whether that's a reduced test case from a Codepen, a link to your site, or something else, it really needs to include all of the applicable JS and the HTML that you are using. I simply cannot help you if you cannot provide me with those.  

The code that you've included above does not even appear to match what you're describing. Where is the code for the menus, for example?

**Comment by ballmannweber** [comment]
please find following a simplified version of our landingpage’s code including the mobile menu: 

`<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" itemscope itemtype="http://schema.org/Article" lang="de">

<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
	<meta name="MobileOptimized" content="width" />
	<meta name="HandheldFriendly" content="true" />
	<meta name="robots" content="index, follow" />
	
	<title>test</title>
	<link rel="alternate" hreflang="x-default" href="/" />
	<link rel="alternate" hreflang="en-DE" href="/en//" />
</head>

<body class="start">

	<div class="mobile">
		<nav class="menu">
			<ul class="filters">
				<li>
					<a href="#filter" class="current" data-filter="*">All Projects</a>
				</li>
				<li>
					<a href="#filter" data-filter=".editorial-design">Editorial Design</a>
				</li>
				<li>
					<a href="#filter" data-filter=".hospitality">Hospitality</a>
				</li>
				<li>
					<a href="#filter" data-filter=".corporate-identity">Corporate Identity</a>
				</li>
				<li>
					<a href="#filter" data-filter=".editorial-design">Editorial Design</a>
				</li>
			</ul>
		</nav>
		<nav class="secondary">
			<ul>
				<li>
					<a href="/studio">Studio</a>
				</li>
			</ul>
		</nav>
	</div>
	<div class="desktop">
		<nav>
			<ul>
				<li class="logo">
					<a href="/" title="Zur Startseite">Logo</a>
				</li>
				<li class="studio">
					<a href="/studio" title="Über das Studio">Studio</a>
				</li>
			</ul>
		</nav>
	</div>
	<header>
		<p>
			Text
		</p>
	</header>
	<main>
		<article>
			
			<div id="options">
				
				<ul class="filters">
					<li>
						<a href="#filter" class="current" data-filter="*">All Projects</a>
					</li>
					<li>
						<a href="#filter" data-filter=".editorial-design">Editorial Design</a>
					</li>
					<li>
						<a href="#filter" data-filter=".hospitality">Hospitality</a>
					</li>
					<li>
						<a href="#filter" data-filter=".corporate-identity">Corporate Identity</a>
					</li>
					<li>
						<a href="#filter" data-filter=".editorial-design">Editorial Design</a>
					</li>
				</ul>
				
			</div>
			
			<div id="container">
				
				<div class="grid-sizer"></div>
				<div class="gutter-sizer"></div>
				
				<a href="/projects/project-a">
					<div class="element editorial-design" data-category="editorial-design">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project A</h2>
						</div>
					</div>
				</a>
				
				<a href="/projects/project-b">
					<div class="element editorial-design" data-category="editorial-design">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project B</h2>
						</div>
					</div>
				</a>
				
				<a href="/projects/project-c">
					<div class="element hospitality" data-category="hospitality">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project C</h2>
						</div>
					</div>
				</a>
				
				<a href="/projects/project-d">
					<div class="element hospitality" data-category="hospitality">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project D</h2>
						</div>
					</div>
				</a>
				
				<a href="/projects/project-e">
					<div class="element hospitality" data-category="hospitality">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project E</h2>
						</div>
					</div>
				</a>
				
				<a href="/projects/project-f">
					<div class="element corporate-identity" data-category="corporate-identity">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project F</h2>
						</div>
					</div>
				</a>
				
				<a href="/projects/project-g">
					<div class="element hospitality" data-category="hospitality">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project G</h2>
						</div>
					</div>
				</a>
				
				<a href="/projects/project-a">
					<div class="element editorial-design" data-category="editorial-design">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project H</h2>
						</div>
					</div>
				</a>
				
				<a href="/projects/project-i">
					<div class="element editorial-design" data-category="editorial-design">
						<div class="fxwrap">
							<picture>
								<img src="#" alt="">
							</picture>
							<h2 class="name">Project I</h2>
						</div>
					</div>
				</a>
				
			</div>
		</article>
	</main>

	<script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
	<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
	<script>
		var $container = $('#container');
		$('.filters a').click(function() {
			$('.filters a').removeClass("current");
			$(this).addClass("current");
			var selector = $(this).attr('data-filter');
			$container.isotope({
				filter: selector
			});
			return false;
		});
		$(function() {
			$container.isotope({
				itemSelector: '.element',
				percentPosition: true,
				masonry: {
					columnWidth: '.grid-sizer',
					gutter: '.gutter-sizer'
				}
			});
		});
		$container.imagesLoaded().progress(function() {
			$container.isotope('layout');
		});
		document.addEventListener("touchstart", function() {}, true);
		$('.hamburger').click(function() {
			$(this).toggleClass('act');
			if ($(this).hasClass('act')) {
				$('.mobile').addClass('act');
			} else {
				$('.mobile').removeClass('act');
			}
		});
		var forEach = function(t, o, r) {
			if ("[object Object]" === Object.prototype.toString.call(t))
				for (var c in t)
					Object.prototype.hasOwnProperty.call(t, c) && o.call(r, t[c], c, t);
			else
				for (var e = 0, l = t.length; l > e; e++)
					o.call(r, t[e], e, t)
		};
		var hamburgers = document.querySelectorAll(".hamburger");
		if (hamburgers.length > 0) {
			forEach(hamburgers, function(hamburger) {
				hamburger.addEventListener("click", function() {
					this.classList.toggle("is-active");
				}, false);
			});
		}
	</script>
</body>

</html>`

**Comment by ballmannweber** [comment]
doesn’t this help?

**Comment by thesublimeobject** [comment]
@ballmannweber,

It does give me more information, but please have some patience. This is not a general support forum.

After re-reading your post, I agree that a URL hash may be a good solution. There are two examples of this functionality [on the extras page of the website](https://isotope.metafizzy.co/extras.html). One for [regular menus](https://codepen.io/desandro/pen/vErxXj), and one for [checkboxes](https://codepen.io/desandro/pen/NgqxjW).

> I also thought the URL hash good be good solution but I couldn’t find a way to make the example code on code pen work with our site or to expand our code to work the url hash.

By this do you mean that you've already tried implementing the functionality from one of the two links above? If so, then you definitely need to make a CodePen showing what you have actually tried. Both of these examples contain the functionality that would be required as far as I understand your explanation of the issue.
