### ISSUE TITLE
Safari bug driving me mad - Only works correctly once you refresh or select a filter

### ISSUE THREAD

**Issue by webchap** [metafizzy/isotope#1580]
Hi there, script is great and seems to work fine on Chrome and Firefox. I am using it with a 'Load more' script but still keep getting it when you first load the page the elements overlap until you press refresh and it works fine. I have tried it with ImagesLoaded but still no luck. Looking for some help if possible. 

I am using it to show news articles with a photo, title and description in each div. I have it set out like this:

```
<div class="button-group-home filters-button-group">
<button class="button is-checked" data-filter="*">Show All</button>
<button class="button" data-filter=".option1">Option One</button>
<button class="button" data-filter=".option2">Option Two</button>
<button class="button" data-filter=".option3">Option Three</button>
</div>

<div class="grid" id="grid">
<div class="row">				
<div class="element-item option1">
<div class="row">
<div class="col-lg-4 col-md-12"><a href="link.htm"><img src="image.jpg" alt="Image" class="img-fluid"></a></div>
<div class="col-lg-8 col-md-12">
<h3>Headline</h3>
<p>Text goes here</p>
<div class="row">
<div class="col-md-6"><span class="articledate">February 2021</span></div>
<div class="col-md-6" align="right"> <a href="link.htm"><button type="button" class="btn btn-lg">Read More</button></a></div>
</div>
</div>
</div>
</div>
</div>
</div>
```

so around 10 of those and they filter fine. 

Before my closing body tag I then have 

```
<script src="../../assets/js/jquery-3.4.1.min.js"></script>
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
<script src="../../assets/js/isotope.js"></script>
```

with the contents of isotope.js being:

```
// init Isotope
var initial_items = 8;
var next_items = 5;
var $grid = $('#grid').isotope({
    itemSelector: '.element-item',
    layoutMode: 'masonry',
    stamp: '.element-item--static'
});


// bind filter button click
$('.button-group-home').on('click', 'button', function () {
    var filterValue = $(this).attr('data-filter');
    // use filterFn if matches value
    $grid.isotope({filter: filterValue});
    updateFilterCounts();
});
function updateFilterCounts() {
    // get filtered item elements
    var itemElems = $grid.isotope('getFilteredItemElements');
    var count_items = $(itemElems).length;
   
    if (count_items > initial_items) {
        $('#showMore').show();
    }
    else {
        $('#showMore').hide();
    }
    if ($('.element-item').hasClass('visible_item')) {
        $('.element-item').removeClass('visible_item');
    }
    var index = 0;

    $(itemElems).each(function () {
        if (index >= initial_items) {
            $(this).addClass('visible_item');
        }
        index++;
    });
    $grid.isotope('layout');
}
// change is-checked class on buttons
$('.button-group-home').each(function (i, buttonGroup) {
    var $buttonGroup = $(buttonGroup);
    $buttonGroup.on('click', 'button', function () {
        $buttonGroup.find('.is-checked').removeClass('is-checked');
        $(this).addClass('is-checked');
    });
});

function showNextItems(pagination) {
    var itemsMax = $('.visible_item').length;
    var itemsCount = 0;
    $('.visible_item').each(function () {
        if (itemsCount < pagination) {
            $(this).removeClass('visible_item');
            itemsCount++;
        }
    });
    if (itemsCount >= itemsMax) {
        $('#showMore').hide();
    }
    $grid.isotope('layout');
}
// function that hides items when page is loaded
function hideItems(pagination) {
    var itemsMax = $('.element-item').length;
    var itemsCount = 0;
    $('.element-item').each(function () {
        if (itemsCount >= pagination) {
            $(this).addClass('visible_item');
        }
        itemsCount++;
    });
    if (itemsCount < itemsMax || initial_items >= itemsMax) {
        $('#showMore').hide();
    }
    $grid.isotope('layout');
}
$('#showMore').on('click', function (e) {
    e.preventDefault();
    showNextItems(next_items);
});
hideItems(initial_items);
```

I have tried having imagesloded on there with this below the above too but not making a difference.

```
 <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.js"></script> 
 <script type="text/javascript">

$('.container').imagesLoaded()
  .always( function( instance ) {
    console.log('all images loaded');
  })
  .done( function( instance ) {
    console.log('all images successfully loaded');
  })
  .fail( function() {
    console.log('all images loaded, at least one is broken');
  })
  .progress( function( instance, image ) {
    var result = image.isLoaded ? 'loaded' : 'broken';
    console.log( 'image is ' + result + ' for ' + image.img.src );
  });
</script>
```

I'm sure I'm just missing something and it's fine one minute and not the next. Having googled it there seems to be an issue with Safari mainly. Any help most welcome

**Comment by thesublimeobject** [comment]
@webchap — Hey sorry I didn't know you created your own issue or I would have just responded in here. Can you please create a [reduced test case](https://github.com/metafizzy/isotope/blob/1dd4cd186a599dfd70846431506437fe774c285e/.github/contributing.md) via CodePen so that I can more easily help debugging your issue? This is definitely an issue I have run into many times in the past, but it can often depend on a lot of different variables, so unfortunately, without a working example that presents the bug, I'm not going to be of much help. But if you can create a working example, we should be able to very quickly fix your issue. :)

**Comment by webchap** [comment]
Hi there, first time I have set up a CodePen so forgive me if wrong. Can PM you a URL where test page is if easier as it is all looking as it should with bootstrap etc.? 

https://codepen.io/webchap2020/pen/RwogRzG

You will see it has the Load More at the end which is working and needs to afterwards.

**Comment by thesublimeobject** [comment]
@webchap — Thank you! Am I correct in assuming. that this isn't experiencing the same issues as your site? The pen seems to be working fine.

(Yes, by the way, you are welcome to PM the site as a reference as well, but I would still like to use the codepen as the main frame of reference in case anyone else stumbles upon this issue.)

Also, just so you know, you can click on the little settings icons at the top near "CSS" or "JS", for example, and add libraries via URLs there instead of pasting the entire library into the box. This will make the code much more readable and easier to debug.

**Comment by webchap** [comment]
Thanks for that, it's not overlapping on the pen but is on the site. I will try and amend the pen to get it to replicate the issue. I can't see any way to PM you the link to the site?

**Comment by thesublimeobject** [comment]
@webchap — oh yeah, i guess github doesn't have DMs lol my bad. were you able to get the pen to replicate the site?
