### ISSUE TITLE
ElectronJS App - Cannot find Module

### ISSUE THREAD

**Issue by CubE135** [metafizzy/isotope#1582]
Hi, im having some trouble including Isotope in a Electron App.

I downloaded the minified JS file and included it in my HTML.
When running my Electron App, i get the following Error in the Console:
![image](https://user-images.githubusercontent.com/8761463/111034483-2af86180-8416-11eb-932b-ebd72694047c.png)

I tried googling for a solution to this problem but i could not find anything.
I already tried adding the required module from the Error to my App, but that only brings up the next error where another module is not found.
I repeated this for all modules that could not be found, but i end up with an Error saying:
`Cannot find module './item'`
And i dont know how to fix that.

Am i missing something? This cant be the intended behaviour, right?

**Comment by thesublimeobject** [comment]
@CubE135 — can you share some code so I can see in what type of way you're trying to use it, etc.? For instance, the first error you posted, is that from just including it without calling the library at all, or is it from actually trying to call something, etc.?

Edit: I am closing this issue, but feel free to respond if you can provide more information.
