### ISSUE TITLE
Bug in Isotope with accordion

### ISSUE THREAD

**Issue by ricardofloress** [metafizzy/isotope#1585]
Hello,

My isotope filter is bugging on mobile devices. When I scroll down then scroll up my filtered elements start to disappear. It's only doing this on mobile. I´ve tried to do like Dave DeSandro has on code pen(Isotope with accordion) but it's still bugging.  I´ve also tried different aproaches but got me no where. Can any one help me? Please check the page on a mobile device not on chrome "mobile emulator".

Page: https://7431024.hs-sites.com/careers

### My code:

let currentscrollpos;

$(".atmc-accordion-02_trigger").on('click', function(){  
  let parent= $(this).parent();
  let divtoopen = parent.children().filter('.div-to_open');
  let thisdiv = parent.children().filter('.view-more');
  let greatgrandparent = parent.parent();
  let isOpen = greatgrandparent.hasClass('accord-open');
  // close other accordion
  $grid.find('.accord-open').removeClass('accord-open')
    .find('.list-jobs').first().find('.atmc-accordion-02_trigger').trigger( "click" );

  let sharing_wrapper = parent.children().filter('.sharing_wrapper');
  let icon_sharing = sharing_wrapper.children()[0];
  let icon_sharing_childs = sharing_wrapper.children()
  let icon_sharing_hidden = icon_sharing_childs[1]; 
  let sharing_svgs = icon_sharing_childs.children('a').children().children()
  //search for button of that div in the overall wrapper
  let first_row = greatgrandparent.children().filter('.row-fluid');
  let aplly_button = first_row.children().filter('.text-right').children().children().children()[0];
  let icon_wrapper = first_row.children().filter('.atmc-career-01_left').children().filter('.atmc-career-01_icon');
  let icon_old_html = '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 56.69 56.69" style="enable-background:new 0 0 56.69 56.69;" xml:space="preserve"><g><path d="M48.84,27.14h-2.34c-0.67,0-1.21,0.54-1.21,1.21c0,0.67,0.54,1.21,1.21,1.21h2.34c0.67,0,1.21-0.54,1.21-1.21C50.05,27.68,49.51,27.14,48.84,27.14z"></path><path d="M46.51,25.57c0.21,0,0.42-0.06,0.6-0.16l1.53-0.88c0.28-0.16,0.48-0.42,0.56-0.73c0.08-0.31,0.04-0.64-0.12-0.92c-0.33-0.58-1.07-0.77-1.65-0.44l-1.53,0.88c-0.28,0.16-0.48,0.42-0.56,0.73c-0.08,0.31-0.04,0.64,0.12,0.92C45.67,25.34,46.08,25.57,46.51,25.57z"></path><path d="M48.64,32.17l-1.53-0.88c-0.58-0.33-1.32-0.13-1.65,0.44c-0.33,0.58-0.14,1.32,0.44,1.65l1.53,0.88c0.18,0.11,0.39,0.16,0.6,0.16c0.43,0,0.83-0.23,1.05-0.6c0.16-0.28,0.21-0.61,0.12-0.92C49.12,32.59,48.92,32.33,48.64,32.17z"></path><path d="M38.97,11.14c-0.34,0-0.67,0.08-0.95,0.22L7.38,24.23c-0.45,0.19-0.74,0.63-0.74,1.11v6c0,0.49,0.29,0.92,0.74,1.11l6.42,2.7v4.98c0,1.52,1.23,2.75,2.75,2.75h7.58c1.34,0,2.45-0.96,2.7-2.25l11.15,4.68c0.31,0.16,0.64,0.24,0.98,0.24c1.69,0,2.89-1.79,3.77-5.62c0.71-3.11,1.1-7.22,1.1-11.58s-0.39-8.47-1.1-11.58C41.86,12.93,40.66,11.14,38.97,11.14zM24.47,39.64v0.5c0,0.18-0.15,0.33-0.33,0.33h-7.58c-0.18,0-0.33-0.15-0.33-0.33v-3.96L24.47,39.64z M12.35,27.12c-0.67,0-1.21,0.54-1.21,1.21v3.08l-2.08-0.87v-4.39l26.62-11.18c-0.17,0.54-0.33,1.14-0.48,1.8l-0.44,2.28c-0.44,2.74-0.67,5.95-0.67,9.3c0,4.36,0.39,8.47,1.1,11.58c0.15,0.66,0.31,1.26,0.48,1.8l-22.12-9.29v-4.1C13.56,27.67,13.02,27.12,12.35,27.12z M38.43,28.36c0,1.2-0.76,2.23-1.87,2.6c-0.03-0.86-0.05-1.74-0.05-2.61c0-0.88,0.02-1.75,0.05-2.59C37.66,26.12,38.43,27.16,38.43,28.36z M40.84,28.36c0-2.47-1.76-4.58-4.14-5.06c0.17-2.24,0.47-4.31,0.85-5.99c0.57-2.49,1.16-3.38,1.42-3.66c0.24,0.27,0.83,1.16,1.41,3.66c0.67,2.94,1.04,6.86,1.04,11.04c0,4.18-0.37,8.1-1.04,11.04c-0.58,2.52-1.17,3.4-1.41,3.66c-0.24-0.27-0.84-1.16-1.42-3.67c-0.38-1.67-0.68-3.73-0.85-5.97C39.08,32.94,40.84,30.82,40.84,28.36z"></path></g></svg>';
  let icon_new_html = '<svg xmlns="http://www.w3.org/2000/svg" width="58.808" height="33.659" viewBox="0 0 58.808 33.659"><g transform="translate(-6.64 -11.14)"><path   d="M38.265,11.14a2.1,2.1,0,0,0-.929.215L7.364,23.944A1.182,1.182,0,0,0,6.64,25.03V30.9a1.172,1.172,0,0,0,.724,1.086l6.28,2.641V39.5a2.688,2.688,0,0,0,2.69,2.69h7.415a2.7,2.7,0,0,0,2.641-2.2L37.3,44.564a2.072,2.072,0,0,0,.959.235c1.653,0,2.827-1.751,3.688-5.5a53.32,53.32,0,0,0,1.076-11.327,53.32,53.32,0,0,0-1.076-11.327C41.092,12.891,39.918,11.14,38.265,11.14ZM24.081,39.018v.489a.326.326,0,0,1-.323.323H16.344a.326.326,0,0,1-.323-.323V35.634ZM12.225,26.771a1.181,1.181,0,0,0-1.184,1.184v3.013l-2.035-.851V25.823L35.046,14.886q-.249.792-.47,1.761l-.43,2.23a58.69,58.69,0,0,0-.655,9.1A53.32,53.32,0,0,0,34.567,39.3q.22.968.47,1.761L13.4,31.975V27.965A1.175,1.175,0,0,0,12.225,26.771Zm25.511,1.213a2.667,2.667,0,0,1-1.829,2.543c-.029-.841-.049-1.7-.049-2.553s.02-1.712.049-2.533A2.671,2.671,0,0,1,37.736,27.984Zm2.357,0a5.062,5.062,0,0,0-4.05-4.95,41.52,41.52,0,0,1,.831-5.859c.558-2.436,1.135-3.306,1.389-3.58a8.644,8.644,0,0,1,1.379,3.58,51.007,51.007,0,0,1,1.017,10.8,51.006,51.006,0,0,1-1.017,10.8c-.567,2.465-1.144,3.326-1.379,3.58a8.581,8.581,0,0,1-1.389-3.59,41.005,41.005,0,0,1-.831-5.84A5.051,5.051,0,0,0,40.094,27.984Z"/><path   d="M47.243,22.106a1.212,1.212,0,0,1-1.164-.861,1.225,1.225,0,0,1,.8-1.526c.528-.166.626-.421.773-1.115.039-.166.068-.323.108-.45a3.57,3.57,0,0,1,1.761-2.093,3.638,3.638,0,0,1,2.837-.254.918.918,0,0,0,.587.049,1.032,1.032,0,0,0,.313-.606,3.457,3.457,0,0,1,3.179-2.719,1.242,1.242,0,0,1,1.233,1.213,1.211,1.211,0,0,1-1.213,1.233c-.166.01-.646.127-.841.88A3.192,3.192,0,0,1,54.11,18a3.08,3.08,0,0,1-2.514.137,1.239,1.239,0,0,0-.949.088,1.1,1.1,0,0,0-.558.636q-.029.117-.059.264a3.487,3.487,0,0,1-2.445,2.944A1.829,1.829,0,0,1,47.243,22.106Z" transform="translate(-0.859 -0.03)"/><path   d="M56.458,42.856A1.167,1.167,0,0,1,56.1,42.8a3.487,3.487,0,0,1-2.445-2.944c-.02-.1-.039-.186-.059-.254a1.132,1.132,0,0,0-.558-.636,1.239,1.239,0,0,0-.949-.088,3.08,3.08,0,0,1-2.514-.137A3.248,3.248,0,0,1,48.065,36.6c-.2-.753-.675-.871-.871-.88a1.246,1.246,0,0,1-1.154-1.272,1.209,1.209,0,0,1,1.2-1.174h.02a3.457,3.457,0,0,1,3.179,2.719,1.052,1.052,0,0,0,.313.606.918.918,0,0,0,.587-.049,3.638,3.638,0,0,1,2.837.254,3.57,3.57,0,0,1,1.761,2.093,3.824,3.824,0,0,1,.108.45c.147.695.245.949.773,1.115a1.225,1.225,0,0,1-.362,2.4Z" transform="translate(-0.86 -0.483)"/><path   d="M54.445,30.248a4.222,4.222,0,0,1-2.739-1.164,1.888,1.888,0,0,0-2.309-.362,1.233,1.233,0,0,1-1.682-.362,1.216,1.216,0,0,1,.323-1.673,4.364,4.364,0,0,1,5.253.538,1.942,1.942,0,0,0,1.233.567,1.7,1.7,0,0,0,.978-.724,4.648,4.648,0,0,1,3.15-1.8,4.48,4.48,0,0,1,3.345.9c.137.108.293.254.46.4.753.695,1.281,1.1,2.289.773a1.222,1.222,0,1,1,.743,2.328,4.458,4.458,0,0,1-4.705-1.321,2.5,2.5,0,0,0-.313-.274,2.03,2.03,0,0,0-1.526-.381,2.229,2.229,0,0,0-1.506.851,3.862,3.862,0,0,1-2.67,1.673A1.722,1.722,0,0,1,54.445,30.248Z" transform="translate(-0.892 -0.307)"/></g></svg>';
  let icon;

if(divtoopen.css('display') == 'none')
{ 
    layoutIsotope();
    currentscrollpos = $(window).scrollTop();  
    $("html, body").animate({ scrollTop: currentscrollpos }, 500);
    greatgrandparent.addClass('accord-open')
    let imageUrl = "https://f.hubspotusercontent20.net/hubfs/7431024/Website%20Resources/Career-Box.png";   
    $(this).toggleClass("atmc-accordion-02_trigger_active");
    $(this).next().slideToggle(); 
    parent.children(".div-to_open").after(this); 
    thisdiv.children().filter('.atmc-accordion-02_trigger_text').text(function () {
      divtoopen.closest(".atmc-career-01_box").css("background-image", "url(" + imageUrl + ")");
      return $(this).text().replace("MORE", "LESS");
    });
    greatgrandparent.css('color', '#ffffff');
    $(this).css('color', '#5599C3');
    icon_sharing.style.opacity = '0';
    icon_sharing_hidden.style.display = 'flex';  
    icon_sharing_hidden.style.color = '#ffffff'; 
    parent.css('padding-top','0');
    aplly_button.style.background = '#5599C3';
    icon_wrapper.html(icon_new_html);
    icon = icon_wrapper.children()[0];
    icon.style.fill = '#5599C3';
    sharing_svgs.addClass('white-fill');
    if ($(window).width() < 768) {
       parent.css('padding-bottom','6rem');
       icon_sharing_hidden.style.marginTop = '40px';
    }else{ 
       icon_sharing_hidden.style.transform  = `translateX(35px)`; 
       parent.css('padding-bottom','0.7rem');
    }
    icon_sharing_hidden.style.flexDirection = 'row';
  }else{
    layoutIsotope();
    $(this).toggleClass("atmc-accordion-02_trigger_active");
    $(this).prev().slideToggle();
    parent.children(".div-to_open").before(this); 
    thisdiv.children().filter('.atmc-accordion-02_trigger_text').text(function () {
      divtoopen.closest(".atmc-career-01_box").css("background-image", "none");
      return $(this).text().replace("LESS", "MORE");
    });
    $(this).css('color', '');
    greatgrandparent.css('color', '#000000');
    icon_sharing.style.opacity = null;
    icon_sharing_hidden.style.display = null; 
    icon_sharing_hidden.style.color = null;  
    icon_wrapper.html(icon_old_html);
    icon = icon_wrapper.children()[0];
    parent.css('padding-top','');
    aplly_button.style.background = null;
    icon.style.fill = null;
    sharing_svgs.removeClass('white-fill');
    parent.css('padding-bottom','');
    icon_sharing_hidden.style.marginTop = '';
    icon_sharing_hidden.style.flexDirection = '';
    icon_sharing_hidden.style.transform = ``; 
    console.log(currentscrollpos)
    $("html, body").animate({ scrollTop: currentscrollpos }, 500);

  }  
});

// // init Isotope
let $grid = $('.filtering').isotope({
  itemSelector: '.color-shape',
  isResizeBound: true,
  layoutMode: 'vertical',
	stagger: 30,
  filter: '.init'
});

// store filter for each group
let filters = {};

$('.filters').on( 'change', function( event ) {
  let $select = $( event.target );
  // get group key
  let filterGroup = $select.attr('value-group');
  // set filter for group
  filters[ filterGroup ] = event.target.value;
  // combine filters
  let filterValue = concatValues( filters );
  if(filterValue ==''){
    // set filter for Isotope
    $grid.isotope({ filter: '.init' });
  }else{
    // set filter for Isotope
    $grid.isotope({ filter: filterValue });
  }
});

// flatten object by concatting values
function concatValues( obj ) {
  let value = '';
  for ( let prop in obj ) {
    value += obj[ prop ];
  }
  return value;
}

//no results
$grid.on( 'arrangeComplete', function( event, filteredItems ) {
  let resultCount = filteredItems.length;
  if(resultCount == 0) {
    $(".custom-modal-main").addClass('model-open');
    $('#listagem-jobs').hide();
  } else {
    $(".custom-modal-main").removeClass('model-open');
  }
});

$(".close-button, .bg-overlay").click(function(){
  $(".custom-modal-main").removeClass('model-open');
});

function layoutIsotope() {
  $grid.isotope('layout');
}

**Comment by thesublimeobject** [comment]
@ricardofloress — From a quick look, my intuition is that this isn't actually a bug related to Isotope, but more than likely something off with the rest of your code. In addition, it actually also happens for me on desktop (not only mobile). 

I'm happy to help a bit more, but you're going to have to give me a bit more explanation for what you're trying to do here. There's a _LOT_ of code here, and none of it is even formatted—it would be easier if you could explain what you're trying to accomplish, format your code, and leave some notes/comments in different places so I can help track down the bug. 

Regardless, the reason I say it might not be related to Isotope is that that there's a lot of code here and it seems like you're re-laying out Isotope perhaps several times once that click function is triggered, and your scroll position that is getting logged seems off. 

Anyway, if you can provide some more context I can try and help a bit more.
