### ISSUE TITLE
Bootstrap Cols with Sass Precision 10

### ISSUE THREAD

**Issue by hirbod** [metafizzy/isotope#1586]
Hi,

when I use Webpack and sass-loader with the default of a decimal precision of 10, my cols have a width of 33.3333333333%. This works great in every browser but Firefox. Firefox shows 2 elements in a row while all other browsers show 3.

If I change (manually using devtools) to 33.33333%, it also works on Firefox. I recently ported from browserify and gulp to Webpack and this error introduced. While there is a sass-loader option for setting precision to 5, its not doing anything and still gets rendered with 10 decimals. Even if a change to 5 would be possible, it does introduce line-height issues on the other end, so sticking with a precision of 10 would be great but as said, it breaks on Firefox.

Is there a workaround or a patch?

**Comment by thesublimeobject** [comment]
@Hirbod — I'm not sure if there is a better or "more official" way to handle this, but I usually just solve this by simply writing my column widths as something like `width: calc((100% / 3) - 1px)`. Some of the browsers seem to handle those decimal columns with absolute sizing a bit differently, which is a bit annoying, but some variant of the above styling has always worked for me.
