### ISSUE TITLE
isotope.metafizzy.co website down

### ISSUE THREAD

**Issue by grhmstwrt** [metafizzy/isotope#1587]
Can you get the documentation website up again so i can view the docs, or add them into repo as current home of docs is completely down "ERR_CONNECTION_TIMED_OUT"

**Comment by thesublimeobject** [comment]
@grhmstwrt Is this working for you now?

**Comment by grhmstwrt** [comment]
I can view it now, though my router security is flagging it for some reason - but yeah, i can get into it now - thanks
