### ISSUE TITLE
A "sleep" method would be helpful

### ISSUE THREAD

**Issue by ianthedev** [metafizzy/isotope#1589]
If would be helpful if there is a "sleep" method which allows us to, for example, temporarily put to sleep an Isotope functionality which is in an invisible [tabpanel](https://www.w3.org/TR/wai-aria-1.1/#tabpanel) so that it won't recalculate its layout with window resizing.

**Comment by thesublimeobject** [comment]
@ianthedev — I assume this is related to the other issue, and therefore potentially solved as well, but for this more nuanced question, you could just use the `destroy()` method whenever one of your tabs is hidden, and then re-initialize the layout once hidden is removed.

**Comment by ianthedev** [comment]
@thesublimeobject Thanks for the advice. But the other issue isn't actually solved yet, and what we have is just a provisional workaround.
