### ISSUE TITLE
Isotope sorting with pagination.

### ISSUE THREAD

**Issue by Sumit89612** [metafizzy/isotope#1591]
I am pretty impressed with Isotope but I am stuck with sorting with pagination. I have managed to filter with pagination but can't able to sort with the same.

Anyone have any idea about it ?

**Comment by thesublimeobject** [comment]
Please provide a Codepen replicating the issue and what you have so far, [per the contributing guidelines](https://github.com/metafizzy/isotope/blob/1dd4cd186a599dfd70846431506437fe774c285e/.github/contributing.md). I would be happy to help you debug your issue once your provide an example.

**Comment by desandro** [comment]
I do not recommend you mix filtering with pagination, as they are conflicting behaviors — filtering removes items, paginating adds them. Unless you are an experienced developer, it's not a good combination.
