### ISSUE TITLE
Do I need a commercial license?

### ISSUE THREAD

**Issue by N3evin** [metafizzy/isotope#1596]
Hi. I am making a website that uses isotope as a library. I intend to sell my own API service which does not use isotope at all, the isotope is just using for the site. The user just hoping over to the site to buy API keys.

I only use it for the web design and the template UI is not being sold in any way. Would I still be needing a commercial license or can I just use GPL3.0?

**Comment by thesublimeobject** [comment]
@N3evin — If you're selling a service my assumption would be that a developer license would probably be the route to take, although @desandro can you confirm here?

**Comment by desandro** [comment]
Hello! Yes, I recommend you purchase an [Isotope Commercial Developer License](https://gum.co/isotope-dev). This is the appropriate license to use so you may include Isotope in a closed source or commercial project.
