### ISSUE TITLE
Can I use CSS Grid with Isotope?

### ISSUE THREAD

**Issue by webcrawlersites** [metafizzy/isotope#1599]
Hey there! I am struggling to get a clean and even image grid layout without using grid, but when I use grid, it doesn't work. Is there a way to use CSS Grid with Isotope?

Thanks!
Jason

**Comment by thesublimeobject** [comment]
@webcrawlersites — CSS Grid will _not_ work with Isotope as it uses absolute positioning for the elements. I suppose it's possible that you could get it to work; I haven't really tried it, but wouldn't recommend it, as I know from experience that using flexbox really messes with the layouts as well. 

If you can't get an even image grid then there's probably some other issue going on with your config/setup. If you can provide a reduced test case as outlined in the [contributing guidelines](https://github.com/metafizzy/isotope/blob/1dd4cd186a599dfd70846431506437fe774c285e/.github/contributing.md), I'd be happy to help you work out the bug.

**Comment by webcrawlersites** [comment]
@thesublimeobject Ah okay. I created a pen to show my issue. I am trying to create a responsive grid (without grid lol) and get the images to all fill their container and have spacing between each image. Here is the pen. Thank you for your help!

https://codepen.io/jaytb95/pen/vYxMGqP
