### ISSUE TITLE
Using imagesLoaded with insert method

### ISSUE THREAD

**Issue by fedesoria** [metafizzy/isotope#16]
I'm working with an ajax call for new elements with images inside, I'm calling 'remove' and then 'insert' with callback 'reLayout'. The problem is that 'reLayout' is called before the images are loaded so it doesn't respect their sizes.

Where would you add the imagesLoaded hook for this to properly work?

Thanks!

**Comment by huykon** [comment]
I did like that but it occur an error:
`Uncaught TypeError: img.imagesLoaded is not a function`
How can I fix it?
Best
