### ISSUE TITLE
Isotope layout isn't working

### ISSUE THREAD

**Issue by webcrawlersites** [metafizzy/isotope#1600]
Hey there! I am trying to create a responsive layout with each image the same size and space in between the images. How can I achieve that?

Here is my codepen:
https://codepen.io/jaytb95/pen/vYxMGqP

Thanks! 
Jason

**Comment by thesublimeobject** [comment]
@webcrawlersites — This is not really a Isotope-specific issue, but you should be able to easily fix this issue by using the `object-fit` property for your images with the value `cover` ([see here](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)). You may need to wrap your images inside of each item in a container with 100% width/height, though. The `cover` property basically works the same as `background-size`.

**Comment by webcrawlersites** [comment]
@thesublimeobject -- I just updated the pen with what you said to do, but it still isn't working. Any suggestions on how to fix it?

**Comment by thesublimeobject** [comment]
You're using `flex` and `columns` in your pen. It would probably be best to use neither, but definitely don't mix the two. Fixing that may fix your `object-fit`, but like I said, you may have to set a static height or put a wrapper around them. You could also potentially do something like just putting them as background images, etc.
