### ISSUE TITLE
Combo of filter and sort?

### ISSUE THREAD

**Issue by ThePixelPixie** [metafizzy/isotope#1606]
I love the combo filters. But I'm wondering if there's a way to combine the effects of the filters and the sorting, such that, if I have, say, the "Red" filter selected, I can then sort all the red items by alphabetic name. So I could get all items with attributes of Red, displayed in alphabetical order by their name? I'm afraid I don't know *quite* enough js to figure out how to make this combo work right.

Thanks in advance.

**Comment by thesublimeobject** [comment]
@ThePixelPixie — Yes, this is a default feature if you use sort functions in combination with the filter functions. For example, if your sort function alphabetizes the items, when filtered, they will be alphabetized as well.
