### ISSUE TITLE
Infinite scroll + isotope = overlapping

### ISSUE THREAD

**Issue by metalbug** [metafizzy/isotope#1607]
look, I tried a lot, but dont work   /(ㄒoㄒ)/~~
@desandro 

edit: okay i found you demo https://codepen.io/desandro/pen/WJrWex

**Comment by thesublimeobject** [comment]
@metalbug — I'm sorry, but I'm not sure what your issue is here? Could you please provide some more information, and then I might be able to better help you. Right now it just seems like you've posted a demo and before that just claimed that something isn't working. What exactly is overlapping?
