### ISSUE TITLE
count possible additional combined filters within the group

### ISSUE THREAD

**Issue by rrrrpppp** [metafizzy/isotope#1612]
Hi, I was wondering if it is possible to include a counter in a combined selection (like this: https://codepen.io/desandro/pen/zrMXQv) as well (like here: https://codepen.io/desandro/pen/60056b176b7120d3ff3e5885921df00a).

The counter would then not set the other selection fields within the group to 0 if a selection was made. The number would then remain the same because it adds more additional items.

What would be the best way to implement this?

**Comment by thesublimeobject** [comment]
@rrrrpppp — Sure, it's definitely possible, I think. I might need some more details, though. This section is a bit confusing:

> The counter would then not set the other selection fields within the group to 0 if a selection was made. The number would then remain the same because it adds more additional items.

 Do you just mean that when it's filtered the non-active filters wouldn't be `(0)`? 

> What would be the best way to implement this?

What have you tried so far? Is there something you've tried that didn't work as expected?
