### ISSUE TITLE
Grid layout push into 1 column

### ISSUE THREAD

**Issue by b3d0** [metafizzy/isotope#1616]
**Hey, I am stuck on problem with Isotope filter and oxyge builder. I tried lot of changes but still me page push 2 column grid layout push into 1 column. 
When i set grid-item {position: static!important;} push back to 2 column but animation of filtering looks really terible
any advice please?
https://kompliment.vojtyla.sk/test/**

**Comment by thesublimeobject** [comment]
@b3d0 — The link you posted has a password protection...do you have a reduced test case?

**Comment by ThomasWu2333** [comment]
I have the same issue
https://cteye.net/eco/V2_1_1/
Choose the "Oprawy" Menu Element  to see the problem
