### ISSUE TITLE
Highlight quicksearch result

### ISSUE THREAD

**Issue by esovetnik** [metafizzy/isotope#1617]
Hello! I can't make function for highlighting keywords in quick search results. Can someone help me?
Example [(https://i.stack.imgur.com/ipMje.png)]( https://i.stack.imgur.com/ipMje.png)
Code [(https://codepen.io/desandro/pen/wfaGu)](https://codepen.io/desandro/pen/wfaGu)

**Comment by thesublimeobject** [comment]
@esovetnik — What have you tried? I don't see any code related to what you're requesting in the link you posted. 

Honestly, this isn't really at all related to Isotope, so I'm going to close this, but if you respond with some more information, I can still try and help you out. Thanks!

**Comment by esovetnik** [comment]
How can I tried!?)) if I don't know what I must change in code which I add to my post. I just want to add highlight to text from search input! Thats is!
