### ISSUE TITLE
Filtering list of selectors from second filter dropdown

### ISSUE THREAD

**Issue by PiotrGorczyca** [metafizzy/isotope#1620]
Hi, is there a way to filter options in a second dropdown filter based on the selection of the first filter?

I also have problems in filtering results with those two different filters. They don't seem to respond to one another. 

Test case: https://codepen.io/piotrgorczyca/pen/jOGKwNx

**Comment by thesublimeobject** [comment]
@PiotrGorczyca —

Honestly, this isn't really an Isotope question so much as it's a general JS/CSS question, but I'll try to help you as much as I can. 

The answer is yes, but you're probably going to have to use custom dynamic menus of some sort. I typically don't use the native input menus for customization reasons, so I might be wrong on whether or not you can use them directly, but regardless, you're definitely going to have to write some custom JS for it.

What you would need to do is attach some listeners to the `change` event for those inputs (or some other event depending on what you're using), and then inside the listener, write some small bit of code that decides which content to display for each menu depending on what is currently being selected.

If you have more questions or want me to take a look at an example that you have tried, I'd be happy to help—just follow up in this thread!
