### ISSUE TITLE
How to toggle Size of item

### ISSUE THREAD

**Issue by fasteddys** [metafizzy/isotope#1630]
Hello how can we achieve `toggling the Size` of the items, like in isotope v2

**Comment by thesublimeobject** [comment]
@fasteddys — Could you please provide a more comprehensive example? I do vaguely remember what you're talking about, but it's been quite awhile, so I might need a bit more detail in order to help you. Thanks!

**Comment by fasteddys** [comment]
In version 2, they had a toggle class, and they could toggle all/multiple items, and multiple sizes `ALL items @ the same time`, followed by a new layout automatically.. this seems to be missing or harder now.. I was hoping for some guidance

In this version I struggle.. For e.g. I need help in _toggle between more than one size_? i.e. how do I `toggle more than 2`, say 3 or 4  items/with **various** sizes at then -> safely same time & auto layout/pack the items.  for e.g. `item 1 `could have `css small & gigante1`; while `Item 2` could have `css small & gigante22` 

### please let me know, how to toggle both/all items at the same times with various CSS, and retain the state as I use filters/sort.

```
var $grid = $('.grid').isotope({
  masonry: {
    columnWidth: 50
  }
});
// how to change all the items with various sizes, change size of item by toggling gigante class
$grid.on( 'click', '.grid-item', function() {
  // How do I handle/toggle more than one CSS class? & all at the same time?
  //  for e.g. item 1 could have css small & gigante1; while Item 2 could have css small & gigante2
  $(this).toggleClass('gigante1');
  $grid.isotope('layout');
});
```

**Comment by thesublimeobject** [comment]
@fasteddys — Thanks for the extra detail. I think the way you're doing it should work fine, in theory. 

So, in general, this is probably how I would go about doing what you're asking (I grabbed the CodePen for the[ first Vanilla JS example from the website](https://codepen.io/desandro/pen/pOjMdx)).

I added the following to the CSS to change the size:

```
.color-shape.big {
  width: 150px;
  height: 150px;
  transition: all 0.5s ease-in;
}
```

And I added this to the JS, to listen for events:

```
let items = Array.from(document.getElementsByClassName( 'color-shape' ))
items.forEach(item => {
  item.addEventListener('click', () => {
    item.classList.toggle( 'big' )
    iso.layout()
  })
})
```

Yes, this is a more basic example, but I wanted to start there. (Also, sorry I know this in vanilla JS, but I don't know jquery as well as I used to...if you can't parse this and re-apply in jquery, just follow up and I will try my best to help out). 

So, all I've done here is add the CSS class for `.big` and then add an event listener for each `.color-shape` (item), such that when they are clicked, the class is toggled and then a re-layout is triggered. 

So, from here, we can deal with multiple classes and/or items. I'm not 100% sure if you're asking about applying to multiple items at once, but clarify if my example does not help. Your example and my example both deal with only one item at a time, when clicked. If you wanted to toggle all items at once, it would be more like this:

```
let items = Array.from(document.getElementsByClassName( 'color-shape' ))
items.forEach(item => {
  item.addEventListener('click', () => {
    items.forEach(item => item.classList.toggle( 'big ))
    iso.layout()
  })
})
```

Here we are just looping over ALL items once any of the items are clicked, and then applying the class toggle to all of them. That said, if you are dealing with multiple classes it might be a bit different. Given that you're trying to apply classnames based on the classnames that already exist, you're just going to have to write some more granular code. Maybe something like this (but I'm guessing here without more information):

```
let items = Array.from(document.getElementsByClassName( 'color-shape' ))
items.forEach(item => {
  item.addEventListener('click', () => {
    items.forEach(item => {
        if (item.classList.contains( 'gigante2' )) {
            item.classList.toggle( 'big )
        } else {
            item.classList.toggle( 'small' )
        }
    })
    iso.layout()
  })
})
```

Something like this should work, but it really just depends on the logic of the process itself. Hope this helps!

**Comment by fasteddys** [comment]
Hello @thesublimeobject I am no jquery expert either, just going with the flow 😀 this is will work I think, let me try it out.

but I think you picked up on what I was trying...

"_..I'm not 100% sure if you're asking about applying to multiple items at once.._", which was **how to I assign & toggle multiple CSS variations of `gigante1`, 2, 3 etc to various items and toggle _all in "one click" at the same time?_** like the original version allowed me to.
