### ISSUE TITLE
Layout with multiple image sizes

### ISSUE THREAD

**Issue by rubymused** [metafizzy/isotope#1631]
I'm trying to use Isotope with a layout that contains multiple image sizes laid out in rows and aligned with left/right margins, as in the attached image. It's easy to lay this out with a grid. Each image has a size class (small, medium, large), which corresponds to a certain number of columns wide. But Isotope doesn't play well with grid layout.

I can translate from grid layout to percentages, but is it possible to use Isotope with multiple sizes, and if so how? I haven't come across any examples.

Thank you.

<img width="268" alt="Screen Shot 2022-08-29 at 4 27 15 PM" src="https://user-images.githubusercontent.com/18076136/187316046-cf55a5ac-7832-4cb8-8381-d7fcc8d1c5a9.png">

**Comment by thesublimeobject** [comment]
@rubymused — Yes, it is possible. Take a look at the [Masonry Layout.](https://isotope.metafizzy.co/layout-modes/masonry.html)
