### ISSUE TITLE
isotope v3 error: No layout mode: cellsByRow

### ISSUE THREAD

**Issue by rubymused** [metafizzy/isotope#1632]
Using version 3.06, and cellsByRow does not seem to exist. 

Here are my option settings:
let options = {
      itemSelector: ".teaser",
      layoutMode: "cellsByRow",
      cellsByRow: {
        columnWidth: 74,
        rowHeight: 74
      },
      
      getSortData: {...}
}

I've attached a screen shot of the error I'm seeing. 

Thank you.

<img width="784" alt="Screen Shot 2022-08-29 at 5 05 06 PM" src="https://user-images.githubusercontent.com/18076136/187319624-52f59151-19b0-4dcc-873f-73f4bd42c78d.png">

**Comment by thesublimeobject** [comment]
@rubymused —

From the [Layout Modes](https://isotope.metafizzy.co/layout-modes.html) page: 
> masonry, fitRows, and vertical are included in Isotope by default. All other layout modes need to installed separately.

If you did not install the module for that layout mode separately, that is likely the source of your error.

**Comment by rubymused** [comment]
Sorry if I'm being obtuse, but where would I find that module? Not seeing it on the website or here in github.

On Aug 30, 2022, at 10:21 AM, hunter b rose ***@***.***> wrote:


@rubymused <https://github.com/rubymused> —

From the Layout Modes <https://isotope.metafizzy.co/layout-modes.html> page:

masonry, fitRows, and vertical are included in Isotope by default. All other layout modes need to installed separately.

If you did not install the module for that layout mode separately, that is likely the source of your error.

**Comment by thesublimeobject** [comment]
@rubymused — https://www.npmjs.com/package/isotope-cells-by-row
