### ISSUE TITLE
Paginate Isotope Filter

### ISSUE THREAD

**Issue by xdebono** [metafizzy/isotope#1640]
Hi there,

is there a way to paginate an isotope filtered grid? I’m looking for a way to implement a truncated pagination.
Many thanks for any help

**Comment by thesublimeobject** [comment]
most straightforward option would probably be combining [Infinite Scroll ](https://infinite-scroll.com/) with Isotope, although there are other ways as well. if you have any further questions once you get working on the implementation, i would be happy to help, but please review the [contributing guidelines and provide a reduced test case](https://github.com/metafizzy/isotope/blob/1dd4cd186a599dfd70846431506437fe774c285e/.github/contributing.md) next time. thanks!
