### ISSUE TITLE
sorting by date doesn't work

### ISSUE THREAD

**Issue by ghost** [metafizzy/isotope#165]
I'm trying to sort the elements of a container by date, but it's not working. I'm confident this is a bug, rather than an issue with my implementation because when I replace the sort-by-date function with a sort-by-name function, it works fine. Of course, it's still possible that there's a bug in my sort-by-date function, but I've debugged it very thoroughly and it seems to be correct.

I've described the issue in full in a stackoverflow post, complete with a URL that demonstrates the issue. The stackoverflow post is here: http://stackoverflow.com/questions/9787215/sort-elements-in-isotope-container

The URL for a demonstration of the bug is: http://festivals.jelastic.com/festival/show/3. The Isotope code is in the SF.layoutImageContent function in common.js

**Comment by laurelle** [comment]
Hi,

I am trying to get sort by date to work, but can seem to figure it out. I have setup a jFiddle here:
[https://jsfiddle.net/ljk999/kumqua9x/33/](url)

I tried adding the logging console code, but it didn't work. Not sure where it should go to see what:
Date.parse($($elem).find('.l49-publish-date').attr('datatime')) is returning.

Any help would be appreciated.

Thank you
