### ISSUE TITLE
How to scroll to a specific element during layout-animation?

### ISSUE THREAD

**Issue by sbormann** [metafizzy/isotope#1652]
I would like to scroll to the position of a specific element. Is there a way to find out the goal-coordinates before the layout animation has completed? Many thanks and greetings!

**Comment by thesublimeobject** [comment]
@sbormann — You won't be able to get the coordinates for item locations until the calculations have completed. The layout can be triggered without an animation, but it will still need to be recalculated for the new layout (whatever that may be). So you would have to wait until after the layout has completed before you could get the position of the desired item you would like to scroll to.
