### ISSUE TITLE
Gutter works for columns not rows

### ISSUE THREAD

**Issue by sbondi** [metafizzy/isotope#1653]
I have used the "gutter" setting with Packery with no issues - a gutter is created across both columns and rows.  But when I try it with Isotope, it only seems to create a gutter across columns, but not across rows :-(. Anyone else experiencing this?

 iso = new Isotope(grid, {
                    itemSelector: '.grid-item',
                    layoutMode: 'fitRows',
                    percentPosition: true,
                    fitRows: {
                        gutter: 2,
                    },
                    resize: true,
                    getSortData: {
                        title: '[data-title]',
                        year: '[data-year] parseInt',
                        medium: '[data-medium]',
                        rating: '[data-rating] parseInt',
                        reviewdate: '[data-reviewdate]',
                        hasreview: '[data-hasreview]'
                    }
                });

**Comment by thesublimeobject** [comment]
@sbondi — This is the correct functionality. Packery and Isotope are different libraries serving different purposes. If you check the documentation on [FitRows](https://isotope.metafizzy.co/layout-modes/fitrows.html), you can see under the "Gutter" section it states the following: 

> Adds horizontal space between item elements.
