### ISSUE TITLE
filtering twice? 

### ISSUE THREAD

**Issue by giovannicoppola** [metafizzy/isotope#1655]
**Test case:** https://codepen.io/Giovanni-Coppola/pen/mdQOBMJ

Hi, beginner here, I am trying to become familiar with the library and I stripped it down to the bare minimum. My demo flickers or filters twice and I can't figure out why? What am I missing? Thanks

**Comment by thesublimeobject** [comment]
@giovannicoppola —

This is your issue:

```
.element-item {
    transition: transform 0.3s ease;
} 
```

The transitions are added via JS and can be customized via the Isotope [options](https://isotope.metafizzy.co/options.html#transitions). If you comment out the transition on the element item (shown above), the grid sort/arrange will stop double-animating/jumping for you. Hope this helps!

**Comment by giovannicoppola** [comment]
aha!! awesome @thesublimeobject, thank you so much!
