### ISSUE TITLE
Istotope: CSS transitions/animations

### ISSUE THREAD

**Issue by liamcrean** [metafizzy/isotope#1665]
Hello

In v2 of isotope it was possible to use custom CSS override to control animation properties of Isotope using these two properties:

```
animationEngine: 'css', 
transformsEnabled: false,
```

I've tinkered with it for a while but doesn't appear to work the same way... and there's no mention of these being present in Isotope V3. Is there an option in V3 to remove native animations and replace with CSS transitions in a similar was as v2? In this case I'd like to remove scale transforms and just animate opacity and Y position.

Thanks.

**Comment by thesublimeobject** [comment]
@liamcrean — i belive what you're looking for can be found in the documentation [here](https://isotope.metafizzy.co/options#transitions). let me know and i can help further if you need.
