### ISSUE TITLE
unpkg links no longer working

### ISSUE THREAD

**Issue by vitordml** [metafizzy/isotope#1668]
this link no longer works, cloudflare is returning a Error code 520 for this link, but not sure if its something you need to fix or not
[https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js](https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js)

**Comment by rupert-quaderer** [comment]
Same issue here.

**Comment by vitordml** [comment]
> Same issue here.

You can host the files yourself, either on a website, or a cdn, they are available for download on this repo

**Comment by thesublimeobject** [comment]
@vitordml — Link seems to be working fine for me.
