### ISSUE TITLE
Option Count

### ISSUE THREAD

**Issue by NewbieJquery** [metafizzy/isotope#175]
Hello David,
gerat work!!
I am new the Jquery and have no expirience.
Is it posibile to include an option counter?

As example on your demo.
Color
All (48)
red (12)
blue (12)
...
If red is selected
red (12)
blue (0)

also counter for the folowing boxes.

**Comment by rattrayalex** [comment]
For others googling this, the current version has it has `$('#container').data('isotope').filteredItems;` (not `$filteredAtoms`).

**Comment by Slind14** [comment]
is there an easy way to do it the other way around? (I would like to display next to the buttons the amount of items on the current view that match the filter. This means that hidden items should not be counted. This allows the user to see if further filters into this direction make sense or not. => are there still +20 left or only 2 if I filter for x)
