### ISSUE TITLE
Filter using html5 data attributes

### ISSUE THREAD

**Issue by dotdreaming** [metafizzy/isotope#182]
Hello, 
Is it possible to filter items using html5 data-attributes, on the items, rather than classes?

I want to use data attributes in the list items e.g. 
data-location="london" data-skills="json, javascript, asp" data-age="35" class="items"

**Comment by richgcook** [comment]
I'm interested in this, still. Filtering (not sorting) by data tags instead of classes?

**Comment by desandro** [comment]
@richgcook Use [Filtering functions](http://isotope.metafizzy.co/filtering.html#filter-functions)

``` js
$grid.isotope({
  filter: function() {
    var attr = $(this).attr('data-attribute');
    return attr == 'hello world';
  }
});
```

**Comment by Unit60** [comment]
@desandro i am failing to filter using value on select-option and data-* on itemSelector... a little help?

`var $grid = $('.isotope').isotope({
  itemSelector: '[data-type]'
});

$('#item-filter-select').change( function () {
  var el = this.value;
  $grid.isotope({ filter: el });  
  console.log(el)
});`

and html
`<select id="item-filter-select">
            <option value="*" >Show All</option>
            <option value="clothes" >Clothing</option>
            <option value="jewelry" >Jewelry</option>
            <option value="misc" >Miscellaneous</option>
          </select>


    <div class="isotope">

      <div class="isotope-item" data-price="23" data-type="misc">
        <img src="http://unit60.com/vendo/img/shop/1.jpg" />23
      </div>

       <div class="isotope-item" data-price="400" data-type="misc">
        <img src="http://unit60.com/vendo/img/shop/2.jpg" />400
      </div>

       <div class="isotope-item" data-price="12" data-type="jewelry">
        <img src="http://unit60.com/vendo/img/shop/3.jpg" />12
      </div>... etc`

this on codepen:
[http://codepen.io/unit60/pen/vXyAzj](url)

**Comment by desandro** [comment]
@Unit60 The demo looks good to me. Were you able to resolve this issue?

**Comment by Unit60** [comment]
@desandro sort of... 
probably not the most elegant but here we go:

 var $grid = $('.isotope').isotope({
 itemSelector: '[data-type]'
});

$('#item-filter-select').change( function () {
  var el = this.value;
  var fel;
  if(el!='*'){
   fel = "[data-type='" + el + "']"
 }else{
   fel = "*"
 }
 $grid.isotope({ filter: fel });  
});

**Comment by Unit60** [comment]
@desandro 
Yay... I got it :)

```javascript
var filters = {};
$('.item-filter-select').on( 'change',function() {
  var $this = $('option:selected');
  var $parent = $(this);
  var level = $(this).parent().find('select option:selected');
  // get group key
  var $buttonGroup = $parent.parents('.select-group');
  var filterGroup = $buttonGroup.attr('data-filter-group');
  // set filter for group
  filters[ filterGroup ] = level.data('value');
  // combine filters
  var filterValue = concatValues( filters );
  $grid.isotope({ filter: filterValue });  
});

// flatten object by concatting values
function concatValues( obj ) {
  var value = '';
  for ( var prop in obj ) {
    value += obj[ prop ];
  }
  return value;
}
```
I reverted to class method with filter combination...
Updated pen: http://codepen.io/unit60/pen/ORbdWE
