### ISSUE TITLE
Maximum number of items?

### ISSUE THREAD

**Issue by Ivor** [metafizzy/isotope#191]
Hi.

(Would have sent a message if I could still do that in github).

I am using isotope to layout (masonry) a large quantity of items. It seems slow/laggy so I am wondering if you have an idea how many items isotope should be able to handle. I have 3 panes of roughly 500 items per pane that I flip through using twitter-bootstrap's carousel.

Btw, thanks for the great plugin. If I get it all working I will definitely get a commercial licence.

Thanks!
Ivor

**Comment by svanskivar** [comment]
Can I do something to do isotope more faster? I have 300-400 text items to filter and Sort.
