### ISSUE TITLE
Adding custom class to filtered items

### ISSUE THREAD

**Issue by vangelis183** [metafizzy/isotope#231]
Hello all,
how do i pass a custom class to filtered items and only them? I mean every isotope-item except isotope-hidden  should get a custom class.

**Comment by bene1705** [comment]
hey folk, unfortunately it doesen't work with the new isotope version (3.0) :-(

**Comment by desandro** [comment]
@bene1705 Use [getFilteredItemElements](http://isotope.metafizzy.co/methods.html#getfiltereditemelements)
