### ISSUE TITLE
reloadItems doesn't work

### ISSUE THREAD

**Issue by KaptajnKold** [metafizzy/isotope#238]
… or at least it doesn't work as I would expect it to. In my project I initialize isotope for a container which at the time has one atom. Later on, this atom is removed from the container by some other library code (without using isotope's `remove` method). I would then expect to be able to refresh isotope's view of the world by calling `reloadItems`. Alas, this doesn't work.

The problem as far as I can figure it, is that while `reloadItems` refreshes isotope's internal `$allAtoms` variable, it doesn´t at the same time refresh isotope's internal `$filteredAtoms` which keeps a reference to the element that has been removed. This causes problem's later on `_getSegments` which tries to divide by the width of the atom which is 0, since it's not part of the DOM anymore. 

The workaround, which I've gotten to work, is to call `_init` after I've called `reloadItems`. To be able to do that, I had to remove the code that checks if a method starts with an underscore.

I have a couple of questions: 
- Why is there both an _init and a _create method? This seems to be either redundant or poor naming.
- It seems to me that _init and `reloadItems` should be just one method called `reloadItems`. Do you agree or am I missing something?

**Comment by kucharzgotuje** [comment]
Hi there guys, 

So I have way simpler problem and, sadly, .isotope('reloadItems').isotope() doesn't work as I would expect it to work. 
I'm assuming here that isotope 2.0 by default is now mobile ready, this issue appears only on mobile devices.
So I'm drawning isotope onDocumentReady with those options:
{
                itemSelector: '.element-item',
                stagger: 30,
                sortBy: 'random'
}
and after user has scrolled to isotope container reloadItems is triggered. 
Some items are still crossing one another like before but on much smaller case. 

How can I prevent this?
