### ISSUE TITLE
Resizable is not overideable on future re layouts

### ISSUE THREAD

**Issue by bvanderhoof** [metafizzy/isotope#24]
Resizable is only read once when the initial window resize event is binded.  I would like to send {resizable:false} to isotope at a later time to temporarily disable the resize event and then send {resizable:true} to isotope to re-enable the resize.

**Comment by Terrycy** [comment]
I realise this is a closed issue and may not even refer to the latest Isotope V2, however I had a case where I needed to disable the resize function. After Googling I found this page, however it didn't help.
The solution I found (whether it was intended or not) was to set isResizingContainer to false in my config for Isotope:

```javascript
isoConfig: {
            isResizingContainer: false
}
 init: function () {
            var options = this.isoConfig;
            this.iso = new Isotope(elem, options);
}
```
