### ISSUE TITLE
Isotope Filtering & Lazy Load

### ISSUE THREAD

**Issue by benjaminsehl** [metafizzy/isotope#244]
Hello,

Hoping someone here can help me. On a client's website, I've got a large list of projects – which may be filtered by their category – heeding to Desandro's advice, I have avoided infinite scrolling, and instead opted for lazy loading. However I have now ran into the problem of the **lazy load not being triggered after projects are filtered**. 

Has anyone gotten this to work, or attempted?

For reference, see: **http://c7a.bmd-labs.com/work**

Thanks! Really hoping someone can reply quickly.

**Comment by illycz** [comment]
Thanks for solution, I have one question:
There is my working example: http://test.3dsimo.com/tutorials/templates
Everything working fine, but when I use filter, also invisible images are loaded and I don't uderstand why. Maybe some layout or filter issue?
Try filtering on example page and look at network tab.

Thanks for any suggestion

Patrik
