### ISSUE TITLE
isotope container height will not grow with isotope-item

### ISSUE THREAD

**Issue by masterkrang** [metafizzy/isotope#275]
I have an isotope-item that will grow in height when somebody comments inside of it. When it grows, how do I tell the main isotope container to grow with it? Right now what is happening is, as the isotope-item grows, the isotope container maintains it's initial height that was set when calling $(".home_main").isotope();  So when I leave comments inside the isotope-item, the item grows, then is cut off by the main container. Thanks.

Also posted this question in stackoverflow: http://stackoverflow.com/questions/12648376/jquery-isotope-plugin-container-height-will-not-grow-with-isotope-item

**Comment by veeren** [comment]
sdfsdf sdf sd f
dsf
f sdfs
 df
 

fs 
dfs
 
dfsdfs
