### ISSUE TITLE
Locale sort

### ISSUE THREAD

**Issue by cdonnelly** [metafizzy/isotope#366]
Hi Guys,

We spotted an issue with the isotope when using this script for sorting elements with text from different locales. I've amended the script.

Let me know your thoughts,

 _sort : function() {

```
  var sortBy = this.options.sortBy,
      getSorter = this._getSorter,
      sortDir = this.options.sortAscending ? 1 : -1,
      sortFn = function( alpha, beta ) {
        var a = getSorter( alpha, sortBy ),
            b = getSorter( beta, sortBy );
        // fall back to original order if data matches
        if ( a === b && sortBy !== 'original-order') {
          a = getSorter( alpha, 'original-order' );
          b = getSorter( beta, 'original-order' );
        }

        //CD - added a locale comparer
        if (typeof a === 'string') {
            //localeCompare(compareString)

            var localeCompar = a.localeCompare(b);
            var sortValue = 0;

            if (localeCompar > 0) {
                sortValue = 1;
            } else if (localeCompar < 0) {
                sortValue = -1;
            } else {
                sortValue = 0;
            }

            return sortValue * sortDir;

        } else {

            return ( ( a > b ) ? 1 : ( a < b ) ? -1 : 0 ) * sortDir;
        }
      };

  this.$filteredAtoms.sort( sortFn );
},
```

**Comment by abubelinha** [comment]
@desandro So this functionality is now integrated in isotope?
I couldn't find any examples on how to use it.

i.e. the following sequence: a B c Ç e É è ñ n 
is being ordered like this:  B a c e n Ç É e è ñ

The original sequence is already ordered in the expected way.
But isotope sorting actually unsorts them:

Isotope puts unaccented characters before accented ones.
And within each group, uppercase characters are sorted before lowercase.

How can I avoid that?
Thanks

**Comment by desandro** [comment]
@abubelinha  I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by philippe-caer** [comment]
Hi @desandro the issue with the sorting is that Isotope considers that any uppercase letter should show up before lowercase letters (ie. "Z" shows up before "a"). You can test it on https://codepen.io/anon/pen/bovJxb by renaming some items with lowercase only.

**Comment by giuseppegarbin** [comment]
Hi @desandro - I'm stuck on this as well. The uppercase strings show up before the lowercase. Do you have any solution for this issue?

**Comment by desandro** [comment]
@philippe-caer @giuseppegarbin One solution is to standardize data by converting all text `.toLowerCase()`

``` js
var $grid = $('.grid').isotope({
  getSortData: {
    // make all lowercase, so uppercase does not come first
    name: function( itemElem ) {
      var name = $( itemElem ).find('.grid-item__name').text();
      return name.toLowerCase();
    },
  }
});
```

See demo https://codepen.io/desandro/pen/OQwEgK
