### ISSUE TITLE
Get item index after shuffle? 

### ISSUE THREAD

**Issue by Denoizzed** [metafizzy/isotope#368]
Thanks for the great plugin. 

I'm wondering if it's possible to get the items' indexes after shuffling. Since the markup is the same, is there an other way to detect now which item is the first / second / third / etc. now?

Thanks in advance!

**Comment by inkcreativ** [comment]
Hi Dessandro, just one question, i need to reorder visible items on the top of the window, because i need to print the result. So i need my page-break to be effective.

Any idea please?
