### ISSUE TITLE
Can isotope be used to re-create Flickr Justified view?

### ISSUE THREAD

**Issue by sebastienbarre** [metafizzy/isotope#380]
First, thanks for providing this tool to the community.
Was wondering if Isotope could be used to recreate Flickr's Justified view.
See: http://www.flickr.com/explore/ (and select "View -> Justified").
I've the feeling Masonry Horizontal is the closest layout, but in the Layout Mode demo page it doesn't seem this layout can be constrained to the window width (i.e. the layout is not recalculated in this mode when the window is resized).

See here for an effort at re-creating it in Javascript:
http://www.wackylabs.net/2012/03/flickr-justified-layout-in-jquery/
http://jsbin.com/upinek/15
Thanks

**Comment by jpadhye** [comment]
I'm interested too. This feature would be really useful
