### ISSUE TITLE
How to achieve a " Centered fitRows" Layout mode

### ISSUE THREAD

**Issue by inpixel** [metafizzy/isotope#428]
First of all, Amazing plugin!

We have been working for the last days without any success to achieve a "Centered fitRows layout mode" for this client's website: http://inpixel.net/dev/pvdv . Have been looking hard for a solution but nothing so far. Right now we are using the centered layout, and combining it with the fitRows would solve our last problem with this website. 
Does anyone have an idea how we can achieve and Centered fitRows layout mode? 

Any help is welcome!

**Comment by genielabs** [comment]
This is a solution for centering each row when using fitRows layout:
```
<script type="text/javascript">
// Put the following code after isotope js include
// Override and customize Isotope FitRows layout mode: CENTER each rows
var fitRows = Isotope.LayoutMode.modes.fitRows.prototype;
fitRows._resetLayout = function() {
  this.x = 0;
  this.y = 0;
  this.maxY = 0;
  this._getMeasurement( 'gutter', 'outerWidth' );

  this.centerX = [];
  this.currentRow = 0;
  this.initializing = true;
  for ( var i=0, len = this.items.length; i < len; i++ ) {
      var item = this.items[i];
      this._getItemLayoutPosition(item);
  }
  this.centerX[this.currentRow].offset = (this.isotope.size.innerWidth +this.gutter-this.x) / 2;
  this.initializing = false;
  this.currentRow = 0;

  this.x = 0;
  this.y = 0;
  this.maxY = 0;
  this._getMeasurement( 'gutter', 'outerWidth' );
};
fitRows._getItemLayoutPosition = function( item ) {
  item.getSize();
  var itemWidth = item.size.outerWidth + this.gutter;
  // if this element cannot fit in the current row
  var containerWidth = this.isotope.size.innerWidth + this.gutter;
  if ( this.x !== 0 && itemWidth + this.x > containerWidth ) {

    if (this.initializing)
        this.centerX[this.currentRow].offset = (containerWidth-this.x) / 2;
    this.currentRow++;

    this.x = 0;
    this.y = this.maxY;
  }

  if (this.initializing && this.x == 0) {
    this.centerX.push({ offset: 0});
  }
  //if (this.centerX[this.currentRow].offset < 0)
  //  this.centerX[this.currentRow].offset = 0;

  var position = {
    x: this.x+(this.initializing?0:this.centerX[this.currentRow].offset),
    y: this.y
  };

  this.maxY = Math.max( this.maxY, this.y + item.size.outerHeight );
  this.x += itemWidth;

  return position;
};
</script>
```
I was not able to extend isotope by using ```$.Isotope``` , indeed just using ```Isotope``` object is working, can this create problems with specific browsers (tried Firefox and Chrome)?
What is the correct way for getting the Isotope class?

**Comment by StephenPunwasi** [comment]
Awesome @genielabs. Works like a charm, much appreciated.

**Comment by zomboh** [comment]
@genielabs that just saved my sanity (and day). Thank you so much.

**Comment by dioogbento** [comment]
Could I have some guidance please on how to center rows for large down only?

I've tried watching for breakpoint changes with `$(window).on('changed.zf.mediaquery', function(event, newSize, oldSize) {` but couldn't get it to change back to normal flow once screen changes from large to xlarge…

Thank you!

**Comment by dioogbento** [comment]
I'm building a website with the Foundation framework.
Could someone please give me some guidance on how to get centered rows on large down screens only?

I've tried working with the Foundation.MediaQuery object while watching for breakpoint changes but couldn't get the layout to get back to normal flow once screen changes from large to xlarge…

Thanks in advance.

**Comment by desandro** [comment]
See #1143 for possible solution to centered fitRows for Isotope v3.

I'm locking down this older conversation here.
