### ISSUE TITLE
CSS-Transforms and viewport scrolling in Safari causes distorted elements

### ISSUE THREAD

**Issue by fk** [metafizzy/isotope#45]
First of all – I'm pretty sure this _is not an isotope bug, but a Safari issue._
I'm interested if anyone can reproduce this and if this is a known issue (I googled a lot, actually – but came up with nothing); I figured posting it here is better than not posting it at all.

Over the weekend I finally had some time to fiddle around with isotope and ran into some strange Safari-issue where once the isotope-items have been "relayouted", scrolling the viewport causes weird distortions of the elements.

To reproduce:
- open http://isotope.metafizzy.co/
- let the page load completely, then narrow down the browser window so that the isotope-items get rearranged (making the browser window wider does not cause the following behaviour)
- scroll and you'll see the distorsion happening – the faster you scroll, the more the items on the page will get "stretched"
- the elements visual position will also shift (even push them out of the viewport), but a mouseover will still trigger at the correct position of the element
- this seems to affect all elements in the document and is not limited to isotope-items
- triggering a relayout (resizing the browser window) will fix the positioning and dimensions of the items
- screenshot: http://tinypic.com/view.php?pic=339ue68&s=7

_Edit:_ just did another test and found out that
- when trying to reproduce above behavior on http://isotope.metafizzy.co/demos/elements-complete.html one does not need to resize the browser window
- as far as I can see, only scrolling up causes the distortion
- arrow-up or page-up also trigger described behavior
- i cannot reproduce the distortion of non-isotope items on the two posted pages, in my local project it affects an element with `position: fixed` applied
- another screenshot: http://tinypic.com/view.php?pic=29oh06p&s=7

This all happens for Safari 5.0.5 (5533.21.1), Mac OS X 10.5.8 – but not in Chrome or Firefox 4 (and of course not in IE).

Setting `transformsEnabled` to `false` (as described here: http://isotope.metafizzy.co/docs/options.html#transformsenabled) fixes the problem in my local project.

**Comment by manish143143** [comment]
i

**Comment by manish143143** [comment]
ghjhgj  jghj
