### ISSUE TITLE
Ios crash

### ISSUE THREAD

**Issue by skeletor00** [metafizzy/isotope#502]
Hello,

My website crashes everytime I open it on the IPAD within the isotope page.
Is there any workaround?

thank you

**Comment by fourroses666** [comment]
I noticed when having a large ammount of items on ipad I had an error message loading the page (215 items), when changing the width to 3 items per row instead of 2 the error was gone. Really weird.
So it looks like when the height of the wrapper is too high then issues pop up. Just saying.
