### ISSUE TITLE
Isotope combination filtering with checkboxes

### ISSUE THREAD

**Issue by blnu** [metafizzy/isotope#517]
Hello, I'm looking to create a combination filter using checkboxes. I have a single group check box filter working but need to add another group of checkboxes to the mix and am running into trouble.

I'd like to be able to select multiple choices from two groups. 

Group 1      Group 2
Round        Red
Square       Blue
Rectangle  Yellow

Hope that's clear. Any help is greatly appreciated!

**Comment by mayankthecoder** [comment]
@desandro Thanks for the post. But right now the data is coming from JS. How can i put the static data "http://codepen.io/desandro/pen/btFfG". Thanks in Advance.
