### ISSUE TITLE
Masonry on iPad is compressed, container height too short?

### ISSUE THREAD

**Issue by cfxd** [metafizzy/isotope#526]
The masonry grid gets collapsed. No console errors I can see on a desktop browser. Sometimes a reload will straighten it out but that's unreliable.

Check out my site: http://goo.gl/t7wsTG

My site on responsinator: http://goo.gl/zybjPJ

You can see the init call in main.js.

Thanks for any feedback!

![image](https://f.cloud.github.com/assets/1671933/963821/0b12b138-050a-11e3-8c42-a23c04453ec1.png)

**Comment by uhuru-be** [comment]
I have the same problem.   The problem occurs only on my iphone and ipad.  On my macbook all looks well (in Chrome and Safari).  I'm using the newest versions of masonry (v4.0.0) and imagesLoaded (v4.1.0)..  The imagesLoaded function gets triggered for each image in the masonry grid, but the images are overlapping each other.  After refreshing the browser, sometimes the image are shown well.
