### ISSUE TITLE
Centering the items within the container div

### ISSUE THREAD

**Issue by theskinny** [metafizzy/isotope#54]
Hi,

I was wondering if it is possible to center all the items within the container, instead of them being left aligned. 
If it is - i would buy a support license for your help. I'm afraid that maybe it is not.

Here is my fiddle: http://jsfiddle.net/yv7m3/

You made a fiddle to center the container, but not the item elements inside: http://jsfiddle.net/desandro/P6JGY/6/  

You also suggested a great site, but i'm not sure how to pick up what they have done: "ish.tv is also a great example of how to center masonry layouts."

Thanks for your time.

**Comment by mariodermez** [comment]
@desandro  even with your code it doesnt center. Centering means equal space from the sides per row of elements. That means that in suggested code if use two rows of boxes (equal height) with less in the second row then they will align to the left. They won't be centered. 

So how can someonw do a layout like the image below?
![fbxcu](https://cloud.githubusercontent.com/assets/11358039/17269065/087d6b02-5647-11e6-893e-35eaef88f3bf.jpg)
