### ISSUE TITLE
reLayout Problem with First Item in List

### ISSUE THREAD

**Issue by Mesidin** [metafizzy/isotope#57]
Development Site:
http://184.106.64.28/index.php

First, fair warning that the site above is not production ready, and things are changing on it at an almost hourly basis.

When you first bring up the site, you should see a dialogue asking you to select a location.  Select "Casper".  Below the promo wheel is our Isotope list.  Click on a movie titlecard to see the showtimes for that film.  We are still dealing with some formatting issues, but as far as Isotope items are concerned, it is 99% working correctly.  You can hover over the "All" option just above the movies to sort the list by theater and it works great.

The one issue is that when you expand the first item in the list, it just shows a two column layout, whereas all the other options wrap the block of movies around the expanded one.

It's not a huge issue, but we can't puzzle out why it isn't working correctly.

**Comment by mobeet** [comment]
I am having this problem, everything works when I use a number for columnWidth, but I'd like to use '.grid-sizer' for the column width so that I can make the column width responsive.  Any way to make the first item behave correctly while using the '.grid-sizer' element?
