### ISSUE TITLE
Elements overlapping after using .isotope on element and element children when filtering.

### ISSUE THREAD

**Issue by janannedh** [metafizzy/isotope#576]
See: http://websites.dehaanwerkbank.nl/dehaanmedia/portfolio.html

When you click in the filter on: "Websites" and go back to "Alles", the items are overlapping. The filter is filtering the elements and elements images. You will have to click TWICE to get the right result.

.js can be found here: http://websites.dehaanwerkbank.nl/dehaanmedia/js/bootstrap.js
this is the bug result: http://websites.dehaanwerkbank.nl/dehaanmedia/bug.png

**Comment by Ondele** [comment]
Add 
 <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>

Then

// init Isotope
var $grid = $('.grid').isotope({
  // options...
});
// layout Isotope after each image loads
$grid.imagesLoaded().progress( function() {
  $grid.isotope('layout');
});
