### ISSUE TITLE
Cannot center the container when use layoutMode: 'fitRows'

### ISSUE THREAD

**Issue by ianthedev** [metafizzy/isotope#579]
Because items have different height and I want them to align tidily, I used `layoutMode: 'fitRows'`.  But then the container can't be centered.

And somehow the gutter doesn't work, too. I want gutter being between items and items but not between container's edges and items.

Please see the example on jsfiddle: http://jsfiddle.net/IanY/4D6N9/8/

**Comment by n0tel** [comment]
+1
