### ISSUE TITLE
Add gutter option to fitRows layout mode

### ISSUE THREAD

**Issue by desandro** [metafizzy/isotope#580]
If you'd like to see this feature, please +1.

**Comment by andreaslindahl** [comment]
Has this been implemented? Still can't get this to work.

**Comment by junaidbhura** [comment]
The gutter size works perfectly except on the old webkit browsers like Safari and Chrome, where it stacks one below the other. But if I enter an explicit value, it works fine. It only has an issue with the gutter size being a percentage value.
![screen shot 2015-06-03 at 9 43 46 am](https://cloud.githubusercontent.com/assets/2512525/7952568/11d1d9c8-09d5-11e5-9bc9-9772d211420c.png)

**Comment by desandro** [comment]
fitRows gutter option is now documented http://isotope.metafizzy.co/layout-modes/fitrows.html#gutter

**Comment by LevKanter** [comment]
:+1:

**Comment by junaidbhura** [comment]
I've used the exact same syntax as in your documentation:

```
work_container.isotope({
	itemSelector: '.item',
	percentPosition: true,
	layoutMode: 'fitRows',
	fitRows: {
		gutter: '.gutter-sizer'
	}
});
```

But I face the problem as I mentioned in my previous comment. It works perfectly for all browsers, except for the old webkit browsers like old Safari and Chrome.

If I use:
```
fitRows: {
	gutter: 18
}
```

It is fine, but with a percentage based sizer value such as:
```
fitRows: {
	gutter: '.gutter-sizer'
}
```

It breaks the layout in those old browsers and stacks one below the other, as in my screenshot.
