### ISSUE TITLE
Add back masonryColumnShift layout mode in v2, v3

### ISSUE THREAD

**Issue by desandro** [metafizzy/isotope#582]
[masonryColumnShift layout mode](http://isotope.metafizzy.co/v1/custom-layout-modes/masonry-column-shift.html) is currently not in v2. Please **+1** if you would like to see it back.

Also - I'm curious if people need this layout mode with Isotope, or they just need it as a layout library (like Masonry or Packery), in which case they do not need filtering or sorting.

**Comment by jdmoliner** [comment]
That's just I wanted. Thanks!!

**Comment by jdmoliner** [comment]
That's just what I wanted. thanks

**Comment by jdmoliner** [comment]
+1

**Comment by blpraveen** [comment]
+1

**Comment by jacobmasters** [comment]
+1

**Comment by flinguin** [comment]
+1

**Comment by mksowmya** [comment]
+1

**Comment by salkii** [comment]
+1 yes we need this of course

**Comment by desandro** [comment]
[Packery v2 supports `shiftLayout`](http://packery.metafizzy.co/methods.html#shiftlayout) which achieves the same functionality that the masonryColumnShift layout mode was going for. Even better, it can shift down multiple columns.

Closing this issue here.
