### ISSUE TITLE
Masonry Layout Bug when First Elem Hidden

### ISSUE THREAD

**Issue by joshreisner** [metafizzy/isotope#585]
If your first element is hidden, say by filtering, and then you try to filter further, Isotope puts everything in a single column.

The issue is on line 3418, inside Masonry.prototype.measureColumns, where it says 

```
  var firstItem = this.items[0];
```

If this first item is hidden then it screws everything up. I fixed the issue in my code by making a function to return the first non-hidden element like so:

``` javascript
  Masonry.prototype.firstItem = function() {
    for (var i = 0; i < this.items.length; i++) {
        if (!this.items[i].isHidden) return this.items[i];
    }
  }
```

And then updated the call:

```
  var firstItem = this.firstItem();
```

And this fixed the issue for me fully. Let me know if you'd like me to make a fiddle or do a pull request or whatever.

Thanks SO MUCH for this amazing software. I'm a customer.

**Comment by RedskyThirty** [comment]
Hello,

I'm quite late but I just lost a few hours with the same issue.
I've updated the script but I'm sure you will fix this by a better way than me...

```
Masonry.prototype.measureColumns = function() {
		this.getContainerWidth();
		// if columnWidth is 0, default to outerWidth of first item
		if ( !this.columnWidth ) {
			var firstItem = this.items[0];

			// Start fix
			if(!$(firstItem.element).is(':visible'))
			{
				for (var i = 1; i < this.items.length; i++)
				{
					firstItem = this.items[i];
					if($(firstItem.element).is(':visible')) break;
				}
			}
			// End fix

			var firstItemElem = firstItem && firstItem.element;
			// columnWidth fall back to item of first element
			this.columnWidth = firstItemElem && getSize( firstItemElem ).outerWidth ||
				// if first elem has no width, default to size of container
			this.containerWidth;
		}

		...
```
