### ISSUE TITLE
Tip: Variable filter isotope entering from another page, with variable hash in url (without plugins)

### ISSUE THREAD

**Issue by o-l-e** [metafizzy/isotope#594]
Hi,

i came up with this hacky kind of way of (simple way) filtering isotope entering from another page. I tried searching for a solution all over the place, and nobody seemed to have a simple answer. 

Now i know the bbq/hashchange plugin does great things, but i was really only looking for a way to filter isotope arriving from another page with one simple filter.

So this is how i did it:

```
Url from a different page:
www.domain.com/isotope-page/#filter-id

// initiating the isotope page
$(window).load(function(){

    // Store # parameter and add "." before hash
    var hashID = "." + window.location.hash.substring(1);

    //  the current version of isotope, the hack works in v2 also
    var $container = $('#container');

    $container.imagesLoaded(function(){
        $container.isotope({
            itemSelector: ".item",
            filter: hashID, // the variable filter hack
        });             
    });

});
```

This does bring about a few other problems though, like what happens if the url has no hash id in it. 

But my suggestion is just to get the ball rolling, so feel free to suggest improvements or showing other solutions. Or if there is something really bad about this method.

Cheers

**Comment by macsamiro** [comment]
@o-l-e
hmmm...your code seems pretty straight forward. Like the idea very much.
Not sure though why it won't work on this site:

http://schoenert.im-ig.de/dev/

Please scroll down to "Unsere Produkte"...and then click on "Markenbrillen"...

The link looks like this:
http://schoenert.im-ig.de/dev/schoenert-optik-produkte-angebote.php#sportbrillen

And the js is:
	    var hashID = "." + window.location.hash.substring(1);

		// portfolio grid layout and filtering
		$container.isotope({
			itemSelector: 'li',
			filter: hashID,
			animationEngine: 'jquery',
			masonry: {
				columnWidth: 5
			}
		});
		console.log("hash.substring.testing")

Would you please take a minute and guide me to the right direction? :)

**Comment by o-l-e** [comment]
hmmm...@macsamiro it looks like you have a conflicting script going on,
It seems like the "unique id" is taken up by some lightbox plugin you have on your page,
I haven't looked at it closely, but try it without the lighbox plugin,

**Comment by Judderman** [comment]
This is exactly what I've been looking for since updating my version of isotope, how would you extend this to set the is-checked class on a button group button set:

i.e.

$('.button-group').each( function( i, buttonGroup ) {
  var $buttonGroup = $( buttonGroup );
  $buttonGroup.on( 'click', 'button', function() {
    $buttonGroup.find('.is-checked').removeClass('is-checked');
    $( this ).addClass('is-checked');
  });
});

**Comment by downFast** [comment]
For another case, I am checking the stirng in the URL like so, maybe it will help you about the URL having or not having the #

	var token = document.location.href.split('?s=')[1].match(/[a-z0-9]+/);
	var attribu = "." + token;
	jQuery('a[data-filter-value="' + attribu + '"]').parent().parent().parent().find(".dropdown-toggle").html(token).removeAttr("href").removeAttr("data-toggle").parent().addClass("disabled");

**Comment by downFast** [comment]
This i the full code I am using. I have set of filters like "agency" "client" "skills" "years" then I am checking if in the URL we have any and if so i am applying the style to the element I want.

    var hash = document.location.hash;

    // create an object to act like a dictionary to store each value indexed by its key
    var partDic = {};

    // remove the leading "#" and split into parts
    var parts = hash.substring(1).split('&');

    // If you just want the first value, whatever it is, use this.
    // But be aware it's a URL so can be set to anything in any order, so this makes little sense
    // var string = parts[0].split('=')[1];

    // build the dictionary from each part
    $.each(parts, function(i, v) {
      // do the "=" split now
      var arr = v.split("=");

      // decode to turn "%5B" back into "[" etc
      var key = decodeURIComponent(arr[0]);
      var value = decodeURIComponent(arr[1]);

      // store in our "dictionary" object
      partDic[key] = value;
    });

    var timeoutId = setInterval(function() {
      if(partDic['comboFilters[agency]'] && partDic['comboFilters[agency]'] != ""){
            var ag = partDic["comboFilters[agency]"].substring(1);
            $('.home .agency .dropdown-toggle').html(ag).append(' <span class="caret"></span>').addClass("current");
        }

       if(partDic['comboFilters[client]'] && partDic['comboFilters[client]'] != ""){
            var cl = partDic["comboFilters[client]"].substring(1);
            $('.home .client .dropdown-toggle').html(cl).append(' <span class="caret"></span>').addClass("current");
        }

        if(partDic['comboFilters[year]'] && partDic['comboFilters[year]'] != ""){
            var yr = partDic["comboFilters[year]"].substring(1).slice(1);
            $('.home .year .dropdown-toggle').html(yr).append(' <span class="caret"></span>').addClass("current");
        }

        if(partDic['comboFilters[skills]'] && partDic['comboFilters[skills]'] != ""){
            var yr = partDic["comboFilters[skills]"].substring(1).slice(1);
            $('.home .year .dropdown-toggle').html(yr).append(' <span class="caret"></span>').addClass("current");
        }

        clearInterval(timeoutId);
    }, 1000);

Since I also have a search page, the URL may change adding extra prefix so i am also doing this

if (window.location.href.indexOf('?s=') > -1) {
	var sel = document.location.href.split('?s=')[1].match(/[a-z0-9]+/);
	if ($('.navbar-inverse a[id^="filter-"][id*="' + sel + '"]').length){
		$('.navbar-inverse a[id^="filter-"][id*="' + sel + '"]').addClass('current').parent().parent().parent().find(".dropdown-toggle").html(sel).removeAttr("href").removeAttr("data-toggle").parent().addClass("disabled");
	}
}

if (window.location.href.indexOf('category=') > -1) {
	var sel = document.location.href.split('category=')[1].match(/[a-z0-9]+/);
	if ($('.navbar-inverse a[id^="filter-"][id*="' + sel + '"]').length){
		$('.navbar-inverse a[id^="filter-"][id*="' + sel + '"]').addClass('current').parent().parent().parent().find(".dropdown-toggle").html(sel).removeAttr("href").removeAttr("data-toggle").parent().addClass("disabled");
	}
}

I hope this helps anyone. It's a bit hacky but at least it works and my menu gets selected and the style I want in regards of the filtered element when coming from another page. In the hope there will be a more incorporate isotope solution, this will be it, for me.

**Comment by mayersdesign** [comment]
This worked for me, hacky but seems robust

```javascript

var hashID = "." + window.location.hash.substring(1);

 if(window.location.hash) { //If we have a hash filter by it, if not don't try
  $container.isotope({
   itemSelector: '.item',
   filter: hashID 
  });		 
 } else {
  $container.isotope({
   itemSelector: '.item'
  });
 }
````

**Comment by NayeemNipun** [comment]
Hello,

I am using the below solution from o-l-e. And this works fine. But the problem is the Filter tab is not adding active class (menu is not selecting) after redirection.

Need a solution for this.

Url from a different page:
www.domain.com/isotope-page/#filter-id

// initiating the isotope page

`$(window).load(function(){
    // Store # parameter and add "." before hash
    var hashID = "." + window.location.hash.substring(1);

    //  the current version of isotope, the hack works in v2 also
    var $container = $('#container');

    $container.imagesLoaded(function(){
        $container.isotope({
            itemSelector: ".item",
            filter: hashID, // the variable filter hack
        });             
    });
});`

**Comment by o-l-e** [comment]
@NayeemNipun i don't have time to explain properly, but try this snippet for your filter menu:

  // if url contains hash, filter
if (hash) {		
	// ISOTOPE + MENU UPDATE
	$(".active").removeClass("active"); // remove class from all first
	$(".active" + '[href=' + window.location.hash + ']').addClass("active");
}
