### ISSUE TITLE
updateSortData in Isotope 2?

### ISSUE THREAD

**Issue by daGUY** [metafizzy/isotope#602]
I'm trying to dynamically update the sorting data I'm using on my items after Isotope is initialized, then trigger a re-sort.

`updateSortData` looks like exactly what I need, but it's only documented in Isotope 1 and I don't see an equivalent in Isotope 2. I tried using it anyway and just got a generic `"undefined" is not a function` error, so it seems like it's been removed – but if so, there's no mention of this in the [list of changes from v1](http://isotope.metafizzy.co/beta/appendix.html#upgrading-from-v1).

Is there any way to do this in Isotope 2?

**Comment by andrewjmead** [comment]
The JavaScript equivalent of this would be:

```js
iso.updateSortData()
iso.arrange()
```
