### ISSUE TITLE
Improving compatibility with Angular

### ISSUE THREAD

**Issue by sohocoke** [metafizzy/isotope#605]
Hi,

Isotope is totally awesome.

I’m putting together an AngularJS app, and as a lot of my lists are rendered with ng-repeats which automatically create the DOM elements in the list, I thought it would be very nice to initialise Isotope with an option to work with dynamic list elements. This would avoid Isotope users from having to request ‘reloadItems’ to get Isotope to properly render the latest version fo the DOM.

I'd imagine there'd be an appropriate event that Isotope could watch. This would be trivial with jQuery, but obviously you’d not want to require that dependency. Can an efficient ‘watching’ mechanism of the DOM be written with a native function these days?

Would you consider observation of a dynamic portion of the DOM to be too much out of scope of Isotope’s remit? 

Else my best workaround at the moment seems to be to catch the appropriate event in my code, then link up to a call to ‘reloadItems’. I’m reluctant to do this, since it will require the markup to be isotope-aware, bring in directives etc. 

Looking forward to your thoughts.

**Comment by tristanguigue** [comment]
> Taking a step back, I can imagine a solution that implements Isotope-like animation and layout 
> behavior into the Angular framework.

I wrote an AngularJS library based on isotope (it is still in early stage): http://tristanguigue.github.io/angular-dynamic-layout/ 

It is far from being as complete as isotope and meant to be very lightweight, it uses `ngRepeat` with `ngFilter` to process the data before any representation is done. Animations are controlled from the CSS and launched with `ngAnimate`.

**Comment by desandro** [comment]
This issue has been quiet for over a year, so I'm closing it up now. If you do have issues or ideas with Isotope and Angular, please submit a new issue 🐻
