### ISSUE TITLE
Prevent show all when page loads using filters.

### ISSUE THREAD

**Issue by thughestamu** [metafizzy/isotope#61]
I have several groups of images that I am using filters on.  Everything works fine but my issue is that when the page loads it displays every image that I have because there is no filter applied when the page initially loads.  I am wondering if there is a way to code the filters so that when the page loads it is applying a filter rather than showing everything unfiltered.

Basically...is there a way to set a specific filter as the default filter rather than no filter being the default?

**Comment by tinhbeng** [comment]
Hi,
I have the code:
<ul data-option-key="filter" id="filter">
	<li class="next selected">
		<a title="<?php echo JText::_('JUX_PORTFOLIO_ALL')?>" data-option-value="*"    ref="#"><?php echo JText::_('JUX_PORTFOLIO_ALL')?></a>
	</li>
		<?php $count=count($catArr);
		$k=1;
		foreach ($catArr as $key=>$cat){?>
			<li class="next <?php if($count==$k)echo "last";$k++;?>">
				<a title="<?php echo $cat['name']?>" data-option-value="<?php echo $cat['filter']?>" href="#"><?php echo $cat['name']?></a>
			</li>
			<?php } ?>
		</ul>
How I can set the default "filter" on  on <li> within foreach

Thank
