### ISSUE TITLE
isotope.pkgd.min.js not available via github/bower

### ISSUE THREAD

**Issue by otravers** [metafizzy/isotope#635]
I tried adding isotope 2.0b8 to my project via Bower, and felt overwhelmed by the number of files that retrieved. Unless I missed something, isotope.pkgd.min.js seems available only as a separate manual download. Can it be added to the Git repository? With bower-installer it would then be very easy to add just that file to my production directory for third-party front-end libraries.

**Comment by cescoferraro** [comment]
@otravers I have included this to my .bowerrc and now bower only downloads the isotope folder that I need for production

```json
  "ignoredDependencies": [
    "eventie",
    "eventEmitter",
    "doc-ready",
    "get-size",
    "matches-selector",
    "outlayer",
    "get-style-property",
    "fizzy-ui-utils",
    "masonry"
  ]
```
