### ISSUE TITLE
Implementing Selectors without Jquery - Isotope V2

### ISSUE THREAD

**Issue by TheFlyingSquirrel** [metafizzy/isotope#657]
HI Desandro, the latest version of chrome is not compatible with Isotope V1 so I plan to adopted V2 and use plain javascript, however my knowledge of javascript is not complete enough to change the second code block, Could you assist? 

var iso = new Isotope('#container', {
  // options
  itemSelector: '.item',
  filter: '*',
  layoutMode: 'masonry'
});

$(window).load(function(){
    $('.isotope-filter a').click(function(){
        $('.isotope-filter .current').removeClass('current');
        $(this).addClass('current');

```
    var selector = $(this).attr('data-filter');
  $container = iso;
  $container.isotope({filter: selector});
});   
```

});

**Comment by Google-search-apiundesir** [comment]
> Hi there! Thanks for reaching out
> 
> > latest version of chrome is not compatible with Isotope V1
> 
> What version of Chrome? I'm looking at v34 and it looks just fine.
> 
> You can still use v2 with jQuery. I recommend looking at the examples on CodePen to help build your own. Here's the filtering example: http://codepen.io/desandro/pen/Ehgij





https://jquerys.space/questions/using-the-filter-function-in-jquery-allows-for-efficient-sorting-and
