### ISSUE TITLE
Safari vs. percentage-width-items (masonry)

### ISSUE THREAD

**Issue by netzrocker** [metafizzy/isotope#661]
Safari (7.0.2, OS X 10.9.2) has problems with the percentage-width-items masonry layout, possibly rounding errors. Test this pen http://codepen.io/desandro/pen/mIkhq and resize the window, the grid breaks in various stages. Works fine in FF an Chrome. Thanks for help!

![safari](https://cloud.githubusercontent.com/assets/2510090/2577866/14db6bd0-b985-11e3-99f2-807a7c558a02.png)

**Comment by desandro** [comment]
Masonry v3.2.3 added fixes for pixel positioning for Safari. This issue is now resolved.

There is a new issue with `percentPosition` in Safari though. See desandro/masonry#698

**Comment by richgcook** [comment]
Is rounding with different browsers still an issue?
