### ISSUE TITLE
Wrong positioning of elements when a scrollbar is present

### ISSUE THREAD

**Issue by xxvii** [metafizzy/isotope#664]
Hi,
I'm using Isotope 2.0.0 in this page: 
http://o-zone.it/wp/portfolio/

with this configuration:
        // init Isotope
	var $container = $('#projects_list').isotope({
		itemSelector: '.project',
		masonry: {
			gutter: 0,
			columnWidth: '.project'
		}
	});

In firefox 28 and chrome 33 (win 8.1 pro), when the number of elements is enough to cause the page to scroll, the position of the elements is a bit wrong.
You can see that there is a space of about 7px between the elements.
This space disappears if you resize the window or filter the elements.

It reappears if you show all the elements again, causing the page to scroll.

It seems that the plugin calculates the width of the container (which is set at 100%) as if there's no scroolbar, so wider than it really is.
The elements width is correct, but they are positioned as if they were in a wider container.

The bug does not occur in IE11.

Thank you very much.

**Comment by Jovian** [comment]
html { overflow-y: scroll; }
As I remember, this "fix" is reducing overall website performance, because browser is forced to do constant usless page repaints.
Correct me if I'm wrong.

**Comment by desandro** [comment]
@Jovian `html { overflow-y: scroll; }` has no effect on paint and should not affect browser rendering performance. This is set in CSS, not dynamically with JS, so there's no way it could causing multiple paints.

**Comment by Jovian** [comment]
Ah, remembered an issue, I've faced one day.
When I was testing a website on Android tablet, the strange problem got me spend 2 hours of seraching a solution. The problem: whenever I scroll the page, some elements were "simulating" parallax effect (jumping outside the flow). Solution was to remove this:
`body, html {
height: 100%;
overflow: auto;
}`
Via Chrome Dev tools I saw, that those CSS rules were forcing constant page repaints.

Such "parallax" effect You can see, for example, here: https://atmospherejs.com/
Browsing such websites on, for example, "not-so-good" tablet (with 2 x Cortex-A9 CPU) is very painfull and unpleasant. Although, yes, atmospherejs just uses too much absolutely and fixed positioned elements, causing webpage to use alot of system resources (CPU, GPU, memory).

Sorry for my bad English. :)

**Comment by richgcook** [comment]
@desandro Any news on this rounding error? Thank you.

**Comment by richgcook** [comment]
Interestingly enough, I'm using the bootstrap grid (@mdo) and their columns use several decimal points: .66666667% and .33333333% which obviously allows us to be super specific, but I think due to the accuracy, and the way Firefox rounds decimal points, it's causing problems. By removing these numbers and simply using .6% and .3% it seems to fix the issue, albeit with a slight (if even noticeable) gap on the right. What do you guys think? @desandro

**Comment by desandro** [comment]
I'm considering adding an option that used `Math.round` instead of `Math.ceil` so you can resolve rounding errors like this.

**Comment by richgcook** [comment]
@desandro That sounds good. If it helps and doesn't cause too much hassle. Thanks for replying.

**Comment by desandro** [comment]
Closing this issue as it's been quiet for a year. If you have related issue, please open a new issue. :strawberry:
