### ISSUE TITLE
checkbox problem

### ISSUE THREAD

**Issue by martajohnsson** [metafizzy/isotope#670]
Hi, I love your solution and would like to use your demo http://codepen.io/desandro/pen/btFfG but I have a problem. I'm trying to make some changes so the user can not see the checkbox but the color is chanching when clicked. My problem is that when I click on ALL other checked boxes are still active. You can see it here: http://visitoland.com/bo/bb/ I did some changes in the html code and my option-set checkboxes loks like that now:

Hela Öland

<div class="checkbutton">
    <label for="norra-oland">
        <input type="checkbox" value=".norra-oland" id="norra-oland" /><span>Norra Öland</span>
    </label>
</div>

<div class="checkbutton">
    <label for="sodra-oland">
        <input type="checkbox" value=".sodra-oland" id="sodra-oland" /><span>Södra Öland</span>
    </label>
</div>

<div class="checkbutton">
    <label for="mellersta-oland">
        <input type="checkbox" value=".mellersta-oland" id="mellersta-oland" /><span>Mellersta Öland</span>
    </label>
</div>

<div class="checkbutton">
    <label for="kalmar">
        <input type="checkbox" value=".kalmar" id="kalmar" /><span>Kalmar</span>
    </label>
</div>

I think that there is a problem to find checkboxes now, but I don't know what I should change in t he code. Very thankfull for any ideas.
Great code!

**Comment by iamrobert** [comment]
This seems to work:

`  function manageCheckbox($checkbox) {
            var checkbox = $checkbox[0];
            var group = $checkbox.parents('.option-set').attr('data-group');
            // create array for filter group, if not there yet            
            var filterGroup = filters[group];
            if (!filterGroup) {
                filterGroup = filters[group] = [];
            }
            var isAll = $checkbox.hasClass('all'); // reset filter group if the all box was checked            
            if (isAll) {
                delete filters[group];
                if (!checkbox.checked) {
                    checkbox.checked = 'checked';
                }
            } // index of            
            var index = $.inArray(checkbox.value, filterGroup);
            if (checkbox.checked) {
                var selector = isAll ? 'input:not(.all)' : 'input.all';
				$checkbox.parents('.option-set').find( selector ).removeAttr('checked');
                if (!isAll && index === -1) {
                    // add filter to group                    
                    filters[group].push(checkbox.value);
                }
            } else if (!isAll) {
                // remove filter from group                
                filters[group].splice(index, 1);
                // if unchecked the last box, check the all            
                var test = $checkbox.parents('.option-set').find('input:checkbox:checked').length;
                if ($checkbox.parents('.option-set').find('input:checkbox:checked').length === 0) {
      					$checkbox.parents('.option-set').find('input.all').prop('checked', true);
           
				}
            }
        }`
