### ISSUE TITLE
"sortBy: 'random'" multiple times?

### ISSUE THREAD

**Issue by daGUY** [metafizzy/isotope#672]
I want to create a button that shuffles/randomizes the order of all my Isotope items every time it's clicked. I thought this would be as simple as calling a function whenever the button is clicked:

```
function shuffle() {
    $container.isotope({
        sortBy: "random"
    });
};
```

However, this only works the first time the button is clicked, because it seems that the `random` order is created just when Isotope is initialized. So when I click the button a second time, the items are sorted by the "same" `random`, so nothing moves.

How do I regenerate the random order so that every time I click the button, the items are reshuffled into a new order?

**Comment by energy7** [comment]
This fixed my issue with sortBy not working for anything except random, too :)

**Comment by pstrawberriedev** [comment]
Seems like now you can use [Shuffle Method](http://isotope.metafizzy.co/methods.html#shuffle) instead
