### ISSUE TITLE
Using Isotope without Layoutmode

### ISSUE THREAD

**Issue by benjick** [metafizzy/isotope#675]
Hi

I want to use Isotope without Layoutmode. Is this possible?

Best regards,
Max

**Comment by smachi** [comment]
But what if there are multiple instances of isotope running on same page and I want one of them with no layout and the others with a specific layout?

**Comment by jacobraccuia** [comment]
This worked really well, but I can't toggle to and from this mode.  I wanted to toggle between none and vertical.  I haven't found a way to put the modifications in a conditional.

**Comment by brettmhoffman** [comment]
I understand that the "no layout" mode referenced here if a hack of the intended functionality of Isotope, but as per @smachi comment above, is there a way to make the referenced workaround work with multiple instances of Isotope on a single page? The current solution overrides everything.

**Comment by ses2013** [comment]
Any News on this. Would be very helpfull to have both Layout Modes on one Page.
Best

**Comment by BenjaminHoegh** [comment]
Anyone there know how to add back the smooth transitions?

**Comment by anasik** [comment]
> Anyone there know how to add back the smooth transitions?

Good question. It's a pity nobody answered. @desandro can you look into this? Your solution for no layoutmode kind of removes half the transitions.

**Comment by robwent** [comment]
Does anyone know how to use this with a hashfilter (jQuery version)?

The none layout works great, but it's ignoring the filter set on pageload.

**Comment by desandro** [comment]
> Anyone there know how to add back the smooth transitions?

Sorry, no. By removing layout mode you remove the layout behavior which controls transitions.

> Does anyone know how to use this with a hashfilter (jQuery version)?

Removing the layout mode will not affect use of [URL hash](https://isotope.metafizzy.co/filtering.html#url-hash)

**Comment by robwent** [comment]
@desandro that's weird. Not sure if I had the code in the wrong place but it stopped the filter working on page load.

I tried a few things, but this is what I have working now with the manual trigger.

https://gist.github.com/robwent/ef96e4f82f49a1442069aaf0d99ca0c1

At line 71, it checks for a hash on pageload to change the value of the select field, so I added a manual hash change event after changing the select which triggers the filters.

Might help someone else.

**Comment by abelgriffen** [comment]
> This is a fun exercise 🏃. I hacked a couple methods and I think I got it. See http://codepen.io/desandro/pen/AEslp
> 
> Here's the JS you'll need
> 
> ```js
> Isotope.Item.prototype._create = function() {
>   // assign id, used for original-order sorting
>   this.id = this.layout.itemGUID++;
>   // transition objects
>   this._transn = {
>     ingProperties: {},
>     clean: {},
>     onEnd: {}
>   };
>   this.sortData = {};
> };
> 
> Isotope.prototype.arrange = function( opts ) {
>   // set any options pass
>   this.option( opts );
>   this._getIsInstant();
>   // just filter
>   this.filteredItems = this._filter( this.items );
>   // flag for initalized
>   this._isLayoutInited = true;
> };
> ```
> 
> Note that the filtering transitions aren't smooth, as `display: none` is applied.

---

It works fine but the code create issue when applying sort functionality. Is there a way to fix that? Thanks

**Comment by dgobnto** [comment]
I haven't been able to get the "no layout" mode to work with Webpack. Could someone please help me?

This is my code:
```
var Isotope = require('isotope-layout');

Isotope.Item.prototype._create = function() {
  // assign id, used for original-order sorting
  this.id = this.layout.itemGUID++;
  // transition objects
  this._transn = {
    ingProperties: {},
    clean: {},
    onEnd: {}
  };
  this.sortData = {};
};

Isotope.Item.prototype.layoutPosition = function() {
  this.emitEvent( 'layout', [ this ] );
};

Isotope.prototype.arrange = function( opts ) {
  // set any options pass
  this.option( opts );
  this._getIsInstant();
  // just filter
  this.filteredItems = this._filter( this.items );
  // flag for initalized
  this._isLayoutInited = true;
};

// layout mode that does not position items
Isotope.LayoutMode.create('none');

var $grid = new Isotope( '.main-content', {
	itemSelector: '.presentation',
	layoutMode: 'none'
});
