### ISSUE TITLE
Filter layout thrashing and performance issues

### ISSUE THREAD

**Issue by nandastone** [metafizzy/isotope#677]
Hey,

My Isotope grid consists of around 200 small rectangles, of identical sizes.

When filtering, I've noticed the browser locks for 1-2 seconds before the filter is actually applied. Capturing this process in Chrome Developer Tools Timeline reveals the browser is being force to _recalculate styles_ and _layout_ for every tile in my Isotope grid.

Here is an example, showing a cut-down version with only 10 tiles:

![isotope-filtering](https://cloud.githubusercontent.com/assets/199204/2717267/d97066ea-c53c-11e3-91f9-d555fbb2118b.jpg)

Could this be caused by my implementation? It seems unlikely, as this occurs even without any CSS transition styles.

Known issues? Tips?

cheers,
Matt

**Comment by desandro** [comment]
I'm closing this issue as it's been quiet for years. Please open a new issue if you'd like to re-start this discussion.
