### ISSUE TITLE
Multiple selection for one filter

### ISSUE THREAD

**Issue by hjujah** [metafizzy/isotope#68]
Hey,
I was trying to enable multiple selection for one filter, but sadly without success.... So what I actually want is to enable selecting multiple options under the same filter... Currently I am working on some cell phones portal , and i would like to enable that option , so visitors could select for example HTC and Nokia, and not only one manufacturer...
Can you help me a little please?
Sorry for my bad english, but i hope its understandable....

Cheers!

**Comment by drupalik** [comment]
how about many for one filter (data-filter="red yellow green") isotope(filter : data-filter ^= green)

**Comment by desandro** [comment]
@drupalik For more complex filters than combine classes with other types, you can build it all together with a [filter function](https://isotope.metafizzy.co/filtering.html#filter-functions). See [Combination filter and function demo on CodePen](https://codepen.io/desandro/pen/owAyG/)

This original issues is 7.5 years old, so I'm locking this thread.
