### ISSUE TITLE
Replacing animations/transitions 

### ISSUE THREAD

**Issue by flavorco** [metafizzy/isotope#683]
Hello,

I'd like to disable the filtering animations. I don't want the items to change size or move about the screen.

Instead, when filtering, I would like for all of the objects to instantly disappear and then all of the new objects fade in.

How can this be done?

**Comment by markegli** [comment]
This code will provide the behavior @Dreamsickle and @jeacott desire:

    var positionFunc = Isotope.prototype._positionItem;
    Isotope.prototype._positionItem = function( item, x, y, isInstant ) {
      // ignore isInstant, pass in true;
      positionFunc(item, x, y, true);
    };

In action: <http://codepen.io/anon/pen/raWgwb>
