### ISSUE TITLE
Overlap Issue (using v2.0)

### ISSUE THREAD

**Issue by cyrildc** [metafizzy/isotope#684]
Hi,

I'm using isotope to create fullwidth grid with no gutter. Depending on the width of the window and the number of columns, items can overlap others.

For example:
http://codepen.io/cyrildc/pen/myHAi/

By resizing your window, if the container's width is set to an odd number, the grey item will overlap the red one by 1px.

Can we prevent this from happening?

Thanks

**Comment by danyj** [comment]
@desandro  bud , I tried all suggested solutions and even the one you posted here and for me it does not work, http://prntscr.com/9plyrr,  try resizing the browser and the gap comes and goes. To me it is always visible on 1370, 1170 container width which are standard site widths.
