### ISSUE TITLE
Having items fade in from bottom

### ISSUE THREAD

**Issue by rjchugh** [metafizzy/isotope#690]
How can I have new items added via lazy loading fade in from bottom, and not fly in from top left? I see this in the demo but what do I need to set to achieve that?

**Comment by Farrukhzaman** [comment]
I am getting same issue. you got any solution?

**Comment by thedonquixotic** [comment]
Has this been fixed?

**Comment by desandro** [comment]
Use [`hiddenStyle` & `visibleStyle`](https://isotope.metafizzy.co/options.html#hiddenstyle-visiblestyle). See demo https://codepen.io/desandro/pen/qjXKBp

``` js
var $grid = $('.grid').isotope({
  // options...
  // fade in from bottom
  visibleStyle: {
    opacity: 1,
    transform: 'translateY(0)',
  },
  hiddenStyle: {
    opacity: 0,
    transform: 'translateY(100px)',
  },
});
```

CodePen link added to [Extra examples](https://isotope.metafizzy.co/extras.html#extra-examples)
