### ISSUE TITLE
IE (9, 10, 11) grid doesn't stack the same as with Chrome/Safari/FF/Opera

### ISSUE THREAD

**Issue by thewatts** [metafizzy/isotope#704]
I'm building a grid that has to be very specific, and it has very specific sizes. Because of this, we are specifically ordering each tile of the grid so that it fills in accordingly (and doesn't leave gaps).

Isotope has been great for this, and has worked very very well.

However, when it comes to how Isotope interacts with Internet Explorer - the grid doesn't shape up the same way that it does the rest of the browsers.

Unfortunately, this proves to be a huge problem - as it prevents the grid from being predictable - and therefore breaks the visual element of the page.

I've created an example of what I mean.
Here is an example with padding in the `scss` for tile elements: http://codepen.io/thewatts/full/oBfvu

And here is an example *without* padding in the `scss` for tile elements: http://codepen.io/thewatts/full/Cvabl

And here is a gist of the scss being used in both examples:
https://gist.github.com/thewatts/3c6d71e6e67100cd2f36

If you look at the way the widths/heights are being calculated - I'm using the `calc()` method. 

*I thought at first it was because of how the different browsers can calculate the values.*
**However, this isn't the case - as I also tried an example where I hand coded the pixels to add up to the correct ratios - and still there are issues.**

### Here are screenshots of the grid working correctly on Chrome:
*With Padding*
![screen shot 2014-05-14 at 12 41 49 am](https://cloud.githubusercontent.com/assets/1141717/2967271/852a8b2a-db2a-11e3-960b-35452b0208c8.png)

*Without Padding*
![screen shot 2014-05-14 at 12 41 59 am](https://cloud.githubusercontent.com/assets/1141717/2967280/aa92cfc6-db2a-11e3-8df2-5afcef5fc900.png)

### Here are screenshots of the grid breaking in IE:
*With Padding*
![screen shot 2014-05-14 at 12 40 51 am](https://cloud.githubusercontent.com/assets/1141717/2967286/bffb016c-db2a-11e3-9ca8-90b8e5b96b96.png)

*Without Padding*
![screen shot 2014-05-14 at 12 41 07 am](https://cloud.githubusercontent.com/assets/1141717/2967288/c4af1a4a-db2a-11e3-937f-66c1fc9ca0ed.png)

Thanks for your help, and for a super legit library!

**Comment by desandro** [comment]
Closing this issue as it's been quiet for over an year :ghost:
