### ISSUE TITLE
Can Isotope combine two different types of filters - search and keywords

### ISSUE THREAD

**Issue by romoi** [metafizzy/isotope#709]
I'm trying to combine a search and a keyword filter
http://fiddle.jshell.net/8DJ8V/
I cant get the two to work together - if I start clicking on a keyword, the search filter will stop working.
Is this an implementation or configuration error on my part, or a limitation of Isotope?

**Comment by Saabbir** [comment]
Can Isotope combine filtering with a search field and select box?
