### ISSUE TITLE
How do I prevent animations in Isotope V2?

### ISSUE THREAD

**Issue by jeacott** [metafizzy/isotope#711]
I'm trying to migrate from isotope v1 but I cannot figure out how to effectively prevent the slide animations on insert/append/prepend window resize.

I've tried animationEngine: 'css', and animationEngine: 'none', and various css incantations but obviously not the right ones.
I also have transitionDuration: 0, but no joy (I realise this shouldn't do what I want, but I'm not getting anywhere).

I actually want items to fade in, I just don't want the slide animation on resize which is straightforward in v1. 

Any help greatly appreciated.
Cheers

**Comment by keupsonite** [comment]
Hello, the animationEngine option is not available for the documentation v2 instead of in the v1, cf. https://isotope.metafizzy.co/v1/docs/options.html#animationengine.
There is a way to use CSS instead of jQuery like the Isotope v1?
Thanks in advance

**Comment by downFast** [comment]
isotope v2 uses css not jquery for animation, you can easy check that while looking at the inspector when you're filtering. To prevent animation all together use transitionDuration: '0'

**Comment by keupsonite** [comment]
I made a mistake in my first question, sorry, I wanted to say I want to use jQuery instead of CSS.
With Isotope v1 when I configured with animationEngine: '$', the positionment is not managed with position: absolute/relative. Can I have the same functionnality with the v2?

**Comment by desandro** [comment]
@keupsonite Isotope v2 and v3 only uses CSS transitions for animation.

**Comment by keupsonite** [comment]
That's too bad to read. The animation managed by jQuery was useful to bypass the fixed height constraint caused by the relative and absolute positionment and allows to set the height to 100% (relative to the parent, in my case, the row class, for a unified responsive height based on the max content of the row child item). I hope my explanations is clear... otherwise don't hesitate to ask me.
