### ISSUE TITLE
How to make isotope render items vertically

### ISSUE THREAD

**Issue by theHazzard** [metafizzy/isotope#721]
I need to load items vertically 
ex:
1 5  9
2 6 10
3 7 11
4 8 12
I've tried masonryHorizontal layout, but the container width is omitted, and the items get out of his container, how can I mantain the items inside of his container and get a variable height? please help and sorry for my english :(

**Comment by desandro** [comment]
Closing this feature request as it's been quiet for nearly a year. :ghost:
