### ISSUE TITLE
Em height and IE8 (and stamp)

### ISSUE THREAD

**Issue by mh-nichts** [metafizzy/isotope#722]
First of all, thanks for this great plugin !

And now my very precise problem : 
On IE8, when I stamp an item, the normal item that should be below it gets an incorrect top position (it appears a bit under the stamp).

I managed to get a reduced test-case : 
http://codepen.io/mh-nichts/pen/vAIcd
(easier to watch on IE8) http://codepen.io/mh-nichts/full/vAIcd

The problem actually comes from the fact that the stamp height is defined in em, and it seems that isotope can't calculate it properly, and takes the height of the block that is inside it (although this height is in em, too).

To go further, I've observed that, if you fix the height of all items in em, isotope calculate it in pixels, so they all overlap each other (15em becomes 15px). 
In that case, it behaves another way than with the stamp, because it doesn't even take in account the height of the block inside, whether it's in em or not.

This happens only in IE8 (real or emulation), and probably below, but I haven't tested.

The simplest workaround is to always use heights in px, but this isn't a great solution when we work with responsive interfaces...

Thanks for looking into that, I hope we can get it fixed !

**Comment by desandro** [comment]
Sorry, but I won't be able to resolve this issue. No one else has chimed in AND I'll be dropping support for IE8 in 2016. #947
