### ISSUE TITLE
Callback after layoutComplete executed too early

### ISSUE THREAD

**Issue by Speekless** [metafizzy/isotope#732]
Hi,

I'm using the filter functionality, with a callback function to update item count for each filter. I'm triggering an updatecount() function on layoutComplete, as such:

    $("#container").isotope( 'on', 'layoutComplete', function( isoInstance, laidOutItems ) {
        updatecount();
    } );

While this works fine in most combinations, *sometimes* my updatecount() function returns an element count that is incorrect. I've isolated the issue to the selector incorrectly returning elements that are set to hidden. If I run the same selector by hand after the layout has finished updating, the returned value is correct (doesn't return hidden elements). So I can only assume the "callback" is being run before the layout has been completely updated?

**Comment by desandro** [comment]
Isotope v2.2.0 has been released with a new [event `arrangeComplete`](http://isotope.metafizzy.co/events.html#arrangecomplete). Try it out: http://codepen.io/desandro/pen/pvXxRN This issue is now resolved :rabbit:

**Comment by Youhan** [comment]
I am using arrangeComplete event, but it seems that it is triggering too early. I just set a timeout for 1 sec and it returns fine! 

Please test.

**Comment by stuk88** [comment]
arrange complete not fired at all.

```
   window.homeIsotope = $(page).find('.friends-list').isotope({
            itemSelector: '.friend',
            masonry: {
                isFitWidth: true
            },
            getSortData: {
                distance: function(itemElem) {
                    return $(itemElem).find(".distance").text().replace("m", "");
                }
            },
            sortBy: 'distance'
        });
            $(page).find('.friends-list').on( 'arrangeComplete', function( event, filteredItems ) {
              console.log("arrangeComplete")
            })

```

**Comment by Kwapi** [comment]
I've still got the same issue. Both `arrangeComplete` and `layoutComplete` execute before the grid has been formatted properly.

**Comment by desandro** [comment]
@Kwapi Please open a new issue with a **reduced test case**.   See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).
