### ISSUE TITLE
How do you run an animation on page load in v2?

### ISSUE THREAD

**Issue by contrariwise** [metafizzy/isotope#733]
I would like to animate on page load, like in [this example](http://mpezzi.github.io/bootstrap_isotope/). 

I tried adding CSS transitions but they only get triggered on resize, not on load. Triggering a relayout doesn't make an animation run either.

**Comment by AbrahamHalil** [comment]
Hi,

is it possible to use different Animations as loading the items. 

Like fadeInUp or flipInX?
