### ISSUE TITLE
Isotope using Drop Down Menu with Chrome on Android

### ISSUE THREAD

**Issue by deaon5** [metafizzy/isotope#747]
Isotope on Android (have tested on 4.2 & 4.4) using the Chrome browser with a drop down menu does not update the selected index on the drop down. Isotope will rearrange and run, however, the drop down doesn't update accordingly. Visit the following page on Chrome on Android http://jsfiddle.net/trewknowledge/jJZEN/ for an example.

**Comment by desandro** [comment]
No one has chimed in on this issue in over a year. Closing 🍍
