### ISSUE TITLE
getItemElements does not return item elements in current order

### ISSUE THREAD

**Issue by desandro** [metafizzy/isotope#768]
@marcel12bell from https://github.com/metafizzy/isotope/issues/756#issuecomment-49989468

> @desandro my test case is like http://codepen.io/desandro/pen/nFrte
I want to know if it is possible to get get position of the sorted element (to get the ids) from top left to bottom right.
The elements over isotope('getItemElements') is not the order in wich the elements are displayed...

---

This is a valid request. What you can do is add this code

``` js
  Isotope.prototype.getFilteredItemElements = function() {
    var elems = [];
    for ( var i=0, len = this.filteredItems.length; i < len; i++ ) {
      elems.push( this.filteredItems[i].element );
    }
    return elems;
  };
```

and then use it like any other method.

**Comment by Shuunen** [comment]
Works great ! thanks :)

**Comment by desandro** [comment]
[`getFilteredItemElements` has been added to Isotope API and to the docs](http://isotope.metafizzy.co/methods.html#getfiltereditemelements)
