### ISSUE TITLE
Combination filtering checkbox's and dropdowns

### ISSUE THREAD

**Issue by HarryFrancis** [metafizzy/isotope#771]
Hey there, I am trying to create an isotope gallery that can be filtered with 2 drop downs and multiple category checkboxes.

I currently have it all working apart from when I select a new filter it just overrides the old one rather than combining them.

Any help would be hugely appreciated, thanks!

I have made a codepen so you can see what I'm trying to achieve. (It's my first codepen sorry if it's messy!)

http://codepen.io/HarryFrancis/pen/iowHz

Thanks alot, 
Harry.

**Comment by rostik** [comment]
Is there a way to add to this functionality, so just like there are 2 different groups of select items, have 2 different groups of check boxes ?
