### ISSUE TITLE
bigGraph extension doesn't work with Isotope v2

### ISSUE THREAD

**Issue by emmar** [metafizzy/isotope#772]
I recently started using Isotope v2.0.0, and, since the upgrade, bigGraph.js hasn't worked.  In the console log, I get "Uncaught TypeError: Cannot read property 'prototype' of undefined" on the following line:
```
$.extend($.Isotope.prototype, 
```

  My guess is that it's related to the fact that v2 doesn't require jQuery.

**Comment by desandro** [comment]
Closing this feature request as it's been quiet for a year :ghost:
