### ISSUE TITLE
non-commercial licensing is unusable

### ISSUE THREAD

**Issue by JonasT** [metafizzy/isotope#800]
"For non-commercial, personal, or open source projects and applications, you may use Isotope under the terms of the GPL v3 License. You may use Isotope for free." You cannot release something under the GPL for non-commercial use only. That is an invalid additional restriction which the GPL forbids - the statement pretty much contradicts itself. (read the GPL carefully - it explicitely forbids additional restrictions such as this one)

You were probably meant to write: "Alternatively, you may use Isotope under the terms of the GPLv3 License." However, this necessarily includes commercial use as well.

**Comment by freshsun** [comment]
highchart.js use another option, which is:
1.cc non commercial license for personal and non-profit use
2.commercial license for other use
I think this might be a solution, but cc is not compatible with GPL and is not even an open source license.

**Comment by desandro** [comment]
After working with legal council, we have developed a solution. The product will be dual-licensed, under GPLv3 and a Commercial License. Flickity has been released with this licensing in place: http://flickity.metafizzy.co/license.html

### Open source license

The GPLv3 has many terms, but the most important is how it is sticky when you distribute your work publicly. From the [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic):

> If you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL.

Releasing your project that uses Flickity under the GPLv3, in turn, requires your project to be licensed under the GPLv3. If you are okay with this, feel free to use Flickity under the GPLv3, without purchasing a commercial license.

### Commercial license

The commercial license is designed to for you to use Flickity in commerical products and applications, without the provisions of the GPLv3. With the commerical license, your code is kept propietary, to yourself. If you want to use Flickity to develop commercial sites, themes, projects, and applications, the commercial license is the appropriate license.

---

This licensing will be applied to Isotope and Packery in the next several weeks, with minor version upgrades for both products.

**Comment by QWp6t** [comment]
@desandro You should also consider adding a CLA

http://en.wikipedia.org/wiki/Contributor_License_Agreement

If someone contributes code to the project expecting it to be GPL, and you turn around and throw a commercial license on it, you might have a problem. There's also a question of what exactly IS a "contributor"? Are you yourself a contributor? Does that mean that you abide by the same contributor license? Make sure you factor in a definition of a contributor as well as the licensing terms under which contributors are agreeing to release their contributions.

I don't think this is something you would be able to do on your own. I think you'd want to talk to your lawyer about it.

**Comment by kabatza** [comment]
I don't know what legal council was this but any commercial app or website can connect to gpl licenced program. what has to be released as gpl is a modified version of the actual program. This is how everybody can use mysql for example BUT mariadb Has to be GPL.

**Comment by QWp6t** [comment]
@kabatza he's talking about the commercial publications of projects. If, for example, you want to make a theme or something and sell it in a marketplace (themeforest or whatever), you would either have to license it under GPLv3 or you can pay for a commercial license of Isotope and release it under whatever license you want. While ostensibly you might assume that your product isn't a "modified version" of Isotope, that's actually very imprecise; the viruslike application of GPLv3 affects all *derived* works, not just works that "modify" Isotope. Your product, in this hypothetical, is a derived work, at least in the opinion of the FSF. I have no idea how well any of it has been tested in court, however.

**Comment by desandro** [comment]
Isotope v2.2.0 has shipped with revised licensing model. GPL by default. Purchasing a commercial license allows use outside of the GPL, under the Commercial License terms. Read details at: http://isotope.metafizzy.co/license.html

Thanks all for your input in this matter. I'm happy to resolve this.
