### ISSUE TITLE
Mobile Safari Filtering Issues

### ISSUE THREAD

**Issue by austb25** [metafizzy/isotope#812]
Hi There,

I know that the recommended number of items is 50, but my project requires much more. I haven't had any issues until testing on the iPad. Filtering takes a very long time (even when using only 75 items). I have disabled all animations and set transformsEnabled: false, and I have also changed click events to touchstart and nothing seems to help. Do you have any suggestions on how to optimize it for mobile safari? The initial load is also significantly longer than other browsers (even without any images).

Thank you!

**Comment by desandro** [comment]
Closing this issue as its been quiet for a while. :speak_no_evil:
