### ISSUE TITLE
cannot call methods on isotope prior to initialization; attempted to call 'appended' 

### ISSUE THREAD

**Issue by patrickbjohnson** [metafizzy/isotope#822]
Having some trouble setting up Isotope even though I've pretty much followed the docs to a T ([basically copy and pasted from here](http://isotope.metafizzy.co/methods.html#appended)). 

While the layout actually works, I still get an error in the console
`cannot call methods on isotope prior to initialization; attempted to call 'appended'`

Not sure what I'm doing wrong, if anything at all? As of now I'm trying to create a reduced test for another issue I'm having (separate issue). Basically I want to have 4 images loaded at page load (inline images in html). After the initial four load, it should then load the rest from an array in my JS file. The images within the array are iterated over and then built into img tags then appended into the isotope layout. 

[Live demo available here.](http://pbj.me/dev/isotope/)
### JS

```
    var $imgs = [
    '_blackbird-soap@2x.jpg',
    '_skullcandy-airraid@2x.jpg',
    '_publicsupply-notebooks@2x.jpg',
    '_charitywater-tshirt@2x.jpg',
    '_joya-candle@2x.jpg',
    '_miansai-bracelet@2x.jpg',
    '_salt-surfboard@2x.jpg',
    '_stance-socks@2x.jpg',
    '_stelton-knife@2x.jpg',
    '_stelton-vacuumjug@2x.jpg',
    '_westwardlearning-sunglasses@2x.jpg',
    'blackanchor-bracelet@2x.jpg',
    '_bellroy-wallet@2x.jpg'
    ];

    // builds array img tags. 
    for ( var i = 0; i < $imgs.length; i++ ) {
        $imgs[i] = makeImg($imgs[i]);
    }

    // container variable for isotope
    var $container = $('.img-gallery');
    // initilize isotope on layout
    $container.imagesLoaded(function(){
        $container.isotope({
            itemSelector: '.grid-item',
            stamp: '.gallery-block',
            layout: 'masonry',
            isFitWidth: true
        });
    });


      // append elements to container
      $container.append( $imgs )
        // add and lay out newly appended elements
        .isotope( 'appended', $imgs );
```

**Comment by vishalsingh119** [comment]
kindly see in Getting error in cosole #1239(similar case)
