### ISSUE TITLE
Does Isotope support margin-right grid systems?

### ISSUE THREAD

**Issue by corysimmons** [metafizzy/isotope#826]
Like this one? http://codepen.io/corysimmons/pen/Qwbjyr

Seems like it only supports Bootstrappy grid systems.

**Comment by corysimmons** [comment]
Sorry to bring this up again after so long...

Masonry usage is literally the only advantage to using a Bootstrappy grid (which produces a metric ton of extra markup).

I actually had to make a feature specifically to support Masonry (see: turn my idea of a good grid into a Bootstrap-like grid) in my last project: https://github.com/peterramsing/lost#masonry-support

I guess I don't fully understand why this doesn't work...

If you're doing the math by container size, and a JS-specified gutter size, then positioning things with position: absolute, why does it matter if I have a margin-right of 10,000px or 0?

Are you trying to figure out what the margins are? If so, why even have a `gutter` setting?

Again, I'm sorry. I'm working on a new project and I really don't want to offer screwy markup just so Masonry works...

**Comment by desandro** [comment]
> Like http://codepen.io/corysimmons/pen/rxqNbg Why is there no gutter between item 6 and 7? The only difference in 6 and the other units is 6 doesn't have a margin-right.

![Masonry margin-right gutter bug](https://cloud.githubusercontent.com/assets/85566/12846808/b8b59c2e-cbdc-11e5-8dad-e57f8d4d772b.png)


This demonstrates the problem with attempting to use Masonry with grid systems that use `nth-child { margin-right: 0 }`.  In a normal CSS-only layout items 3, 6, 9, & 12 would appear on the right side. However, in a Masonry layout, the horizontal order of items can be changed. Items 6, 9, & 12 do not appear on the right side, so their missing margin throws off the grid layout.

> http://codepen.io/corysimmons/pen/rxqaxB seems like gutter doesn't do anything at all.

This demo has a JS error. [Try this demo](http://codepen.io/desandro/pen/f1133fd3e8ea834e9b9ffa4b2d6c719e/)

> Doesn't even seem to be working in your masonry + gutters CodePen example http://codepen.io/desandro/pen/dHsCJ

This demo is working properly. You can see that some items are aligned to the grid. Wide items span two columns, but are still aligned with gutters.

---

I recommend taking a look at the [Isotope + Bootstrap example](http://isotope.metafizzy.co/appendix.html#bootstrap), which may be what you're looking for.

**Comment by corysimmons** [comment]
> Items 6, 9, & 12 do not appear on the right side, so their missing margin throws off the grid layout.

I understand that. I guess my question is, why does masonry care _at all_ about what margin's I have set on anything _if_ I have set `gutter`?

> This demo has a JS error.

Ha, my bad.

> This demo is working properly. You can see that some items are aligned to the grid. Wide items span two columns, but are still aligned with gutters.

Are we looking at the same demo? I don't see any gutters on this one and there aren't any JS errors.

![image](https://cloud.githubusercontent.com/assets/224636/12851466/ed4be838-cbf7-11e5-891f-f62d0d0ce625.png)

> I recommend taking a look at the Isotope + Bootstrap example, which may be what you're looking for.

No, the whole point of my Issue is I don't want to use Bootstrap's nasty markup.

Bootstrap markup (that generates fake gutters and forces padding on the sides) looks like this:

```html
<div class="container">
  <div class="row">
    <div class="col-md-6">1</div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-6">1a</div>
        <div class="col-md-6">
          <div class="row">
            <div class="col-md-6">2a</div>
            <div class="col-md-6">2b</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```
http://codepen.io/corysimmons/pen/qbJaBb?editors=1100

My grids' markup looks like:

```html
<div>1</div>
<div>
  <div>1a</div>
  <div>
    <div>1b</div>
    <div>2b</div>
  </div>    
</div>
```
http://codepen.io/corysimmons/pen/RreGNV?editors=1100

https://youtu.be/ueZ6tvqhk8U?t=18

But that's besides the point. My only question is, why do your masonry plugins care at all what margin is set IF gutter is set? I feel like gutter being set should completely take margins out of the equation 100%.

**Comment by desandro** [comment]
> My only question is, why do your masonry plugins care at all what margin is set IF gutter is set?

Because this is consistent behavior. Whether you use gutter or not, margin is calculated in measuring items size. It requires less code for me to maintain, less documentation to cover, and one less behavior difference for the user.

If you do want to use `nth-child` CSS AND use Isotope/Masonry's `gutter`, you can do so with adding some CSS and JS.  When JS is disabled, CSS will use `nth-child` margins. When JS & Masonry is enabled, add a class to remove those margins for Masonry. See [demo on CodePen](http://codepen.io/desandro/pen/1da5287e140d313b4047daa99a7585fd/)

**Comment by corysimmons** [comment]
https://i.imgur.com/C18lvp4.gifv

I have no idea why I never thought of that... So simple.. That's why you're the man.

I still think this is unexpected behavior and changing the math if `gutter` is set is the correct solution (that I'd be happy to PR throughout your plugins/docs if they're on gh-pages), but in lieu of that, this workaround is infinitely better than offering alternative markup.

**Comment by corysimmons** [comment]
@desandro I wasn't necessarily wrong about a lot of your demos being broken.

For instance if I go to http://isotope.metafizzy.co/layout-modes/packery.html and click on the first "Edit this demo on CodePen" link it doesn't work:

![image](https://cloud.githubusercontent.com/assets/224636/12965862/96c7a18a-d027-11e5-8b66-eff7aa8f4e83.png)

I changed http://isotope.metafizzy.co/isotope.pkgd.js to the cdnjs version and it works:

http://codepen.io/corysimmons/pen/JGwyLo?editors=0010

I discovered that it was the popular [HTTPS Everywhere Chrome Extension](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en). Basically it doesn't allow http and https resources on the same page. So when you're trying to pull in https jquery and http isotope, it freaks out.

I'd suggest either adding an SSL cert to metafizzy or just using CDNjs for your pens as a lot of devs use https everywhere. /$.02
