### ISSUE TITLE
Alphanumeric sorting

### ISSUE THREAD

**Issue by GreeKatrina** [metafizzy/isotope#830]
I noticed that Isotope does not sort alphanumeric strings correctly. I have changed the code for the getItemSorter function from this:
```javascript
// returns a function used for sorting
  function getItemSorter( sortBys, sortAsc ) {
    return function sorter( itemA, itemB ) {
      // cycle through all sortKeys
      for ( var i = 0, len = sortBys.length; i < len; i++ ) {
        var sortBy = sortBys[i];
        var a = itemA.sortData[ sortBy ];
        var b = itemB.sortData[ sortBy ];
        if ( a > b || a < b ) {
          // if sortAsc is an object, use the value given the sortBy key
          var isAscending = sortAsc[ sortBy ] !== undefined ? sortAsc[ sortBy ] : sortAsc;
          var direction = isAscending ? 1 : -1;
          return ( a > b ? 1 : -1 ) * direction;
        }
      }
      return 0;
    };
  }
```
And change the return line to this:
```javascript
return alphanum(a,b) * direction;
```
I found a alphanumeric sorting algorithm from this site: http://web.archive.org/web/20130826203933/http://my.opera.com/GreyWyvern/blog/show.dml/1671288 and applied the function like so:
```javascript
 //Custom function to sort alphanumerically
  function alphanum(a, b) {
    function chunkify(t) {
      var tz = [], x = 0, y = -1, n = 0, i, j;

      while (i = (j = t.charAt(x++)).charCodeAt(0)) {
        var m = (i == 46 || (i >=48 && i <= 57));
        if (m !== n) {
          tz[++y] = "";
          n = m;
        }
        tz[y] += j;
      }
      return tz;
    }

    var aa = chunkify(a);
    var bb = chunkify(b);

    for (x = 0; aa[x] && bb[x]; x++) {
      if (aa[x] !== bb[x]) {
        var c = Number(aa[x]), d = Number(bb[x]);
        if (c == aa[x] && d == bb[x]) {
          return c - d;
        } else return (aa[x] > bb[x]) ? 1 : -1;
      }
    }
    return aa.length - bb.length;
  }
```
Not sure if you were planning on adding something like this or not. I thought I would share since I ran into this issue trying to figure out how to sort numbers and strings. It doesn't seem to slow things down.

**Comment by debprotim** [comment]
Thanks Katrina, for such a lovely solution.

I just found one issue with this, whenever the input is numeric, alphanum function throws error. I faced this issue because i had 2 columns, 1 with alphanumeric values and other 2 having numeric values. 

I made a minor change to get around it, I just replaced the following code: 
```javascript
return alphanum(a,b) * direction;
```

with:

```javascript
return (typeof a == "string" && typeof b == "string") ? alphanum(a, b) * direction : (a > b ? 1 : -1) * direction;
```

Above statement helped me in sorting alphanumeric as well as numeric. (Haven't checked pure string, should work i guess)

**Comment by GreeKatrina** [comment]
Debprotim, nice catch. 

I was using this for names of things, so naturally didn't think about integer values. I would assume this would work by looking at it.

**Comment by desandro** [comment]
Looks like this issue has been quiet for a while, so I'm going to close it up. Thanks again for this code! :strawberry:

**Comment by animaux** [comment]
Would love to see this being merged. No one would like to have sorting like this?:

+ K1
+ K12
+ K2
* K21

`;)`

**Comment by epicalex** [comment]
Just encountered this same scenario and after a lot of head scratching found this issue.

What are the downsides to changing alphabetical sorting to be alphanumeric, either as an option or by default?

Seems like a common sense thing to do?
