### ISSUE TITLE
Layout works only sometimes

### ISSUE THREAD

**Issue by JJJuergens** [metafizzy/isotope#842]
Hello, 
I really like isotope but its behavior is a little strange in my project. When I load the page, the items are sometimes arranged correctly and sometimes they're just aligned vertically, one below the other (which is not wanted!). When I refresh the page several times, it rearranges it sometimes. The layout seems to work on a random basis... :-( What's wrong?

```
  <div id="divHistory" class="js-isotope"
 data-isotope-options='{ "columnWidth": 100, "itemSelector": ".lilhdiv", "layoutMode": "fitRows","getSortData": { "pos": ".pos"},"sortBy": "pos" }'>
 </div>
```

And the code where I add the divs:

```
            var elem=d3.select("body").select("div#divHistory").selectAll("querydiv").data(querydata);              
             var elemEnter = elem.enter();

            var divElem = elemEnter
            .append("div")
            .attr("class","lilhdiv")
            .attr("id",function(d,i){return "div"+(i+1);})
            .attr("width",80)
            .attr("height",80);

            divElem.append("p")
            .attr("class","pos")
            .html(function(d){return d.theposition;})
            .style("opacity",0);    
```

**Comment by JJJuergens** [comment]
Thanks a lot for your quick answers! I have another tiny questions that you can probably answer really quickly as well: When I resize the window, there is a nice transition when the elements are ordered in a new way. But when I sort them, this transition doesn't happen. Why? It's so nice and also useful since otherwise you barely notice something has happened.

**Comment by desandro** [comment]
Sounds like you're running into a bug. I could better diagnose the problem with a **reduced test case.** See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues). (sorry to repeat, but test cases help so much).

**Comment by JJJuergens** [comment]
I know, you're right. It's just so hard to produce it but I will try... 

I've got another problem (maybe you understand the error without the test case?)...The filtering doesn't work as expected, either. I thought I'm doing it exactly like you but it only works the first time. After that, nothing happens. 
I have several svg objects and depending on which ones I click, I specify a different type variable. 
When I load the page, I don't want any filtering, so type = null and the third case is executed. Everything is fine so far. When I click on the yellowstar, all objects with the class yellowstar are filtered. That's correct, too. But when I click on another filter option, like "all", the objects don't show up again.

I understand if it's not possible for you to find an answer without a reduced test case but maybe it is...
Maybe I should use the arrange() but I don't know how...

This is my isotope-function:

      function makeIsotope(type){
       //filter
    if (type == "greenstar" || type == "redstar" || type == "yellowstar"){
      var iso = new Isotope( '#managementDiv', {
    columnWidth: 40,
    itemSelector: '.resultrect',
    layoutMode: 'fitRows',
    filter: '.'+type
    });           
     }
     else if (type == "all"){
    console.log("bin in all");
     var iso = new Isotope( '#managementDiv', {
    columnWidth: 40,
    itemSelector: '.resultrect',
    layoutMode: 'fitRows',
    filter:'*'
    });      
    }
    else{
     // at the beginning, i don't want a filter 
     var iso = new Isotope( '#managementDiv', {
    columnWidth: 40,
    itemSelector: '.resultrect',
    layoutMode: 'fitRows'
     });        
     }    
    }

**Comment by JJJuergens** [comment]
Hey, I think I'm getting closer. I think I guessed right that iso.arrange() is the way to go. My code now looks like this (still doesn't work but somehow better):

    function makeIsotope(type){

    // at the beginning, i don't want a filter 
     var iso = new Isotope( '#managementDiv', {
    columnWidth: 40,
    itemSelector: '.resultrect',
    layoutMode: 'fitRows',
    filter:'*'
      });
    
    //filter
    if (type == "greenstar" || type == "redstar" || type == "yellowstar"){
     console.log("star-filter");
     iso.arrange({
        filter: '.'+type
       });  
    }
    else if (type == "all"){
    console.log("all-filter");
    iso.arrange({
        filter: '*'
       });   
     }
    }

**Comment by JJJuergens** [comment]
Ok, the filtering works now. Had to declare the iso variable outside the function. Now I only call the function when I filter, so only the if else statement is left. It filters a little slow but I guess that's normal with more than 200 elements right?

I will see if I can figure out the transition problem as well on my own... If not, you'll hear again from me. Is it in general possible to send you a reduced test case per e-mail? The prototype I'm building is for my PhD thesis and I would not want to share it with the public.
