### ISSUE TITLE
Issues with insert() and addItems()

### ISSUE THREAD

**Issue by mega-cache-money** [metafizzy/isotope#845]
First, my issue with `insert()`:
I can add a single item fine. Why can I not add an array like [this](http://jsfiddle.net/fp0qnur1/2/)?

Then, I can't seem to use `addItems()` to insert items. I understand it doesn't automatically layout my additions, but what am I doing wrong [here](http://jsfiddle.net/oozztvg2/)?

**Comment by desandro** [comment]
See my example: http://jsfiddle.net/fp0qnur1/3/

In your `insert()` example, you are inserting an Array with a jQuery object, which itself is an Array-like object. [`insert`](http://isotope.metafizzy.co/methods.html#insert) will accept an Element, jQuery Object, NodeList, or Array of Elements. It will not accept an Array of jQuery objects.

Instead, you can just use a jQuery object.

```js
var $grid = $('.grid').isotope({
    itemSelector: '.result',
    masonry: {
        columnWidth: 110
    }
});
var iso = $grid.data('isotope');
var elems = $('<div class="result">new</div><div class="result">new</div><div class="result">new</div>')
$grid.append( elems );
iso.insert(elems); 
```
