### ISSUE TITLE
Filtering with no layout.

### ISSUE THREAD

**Issue by chris37879** [metafizzy/isotope#846]
Hey, I'm using the filtering with no layout example from #675 and there is one small problem with it. The top and left values are still being added to the objects, this is causing layout to still apply to things I'm laying out with my own positioning. I'm using inline-block with a text align center to get a nice centered strip of items.

**Comment by desandro** [comment]
I've added this code, which removes setting `top` and `left` on items. http://codepen.io/desandro/pen/AEslp

``` js
Isotope.Item.prototype.layoutPosition = function() {
  this.emitEvent( 'layout', [ this ] );
};
```
