### ISSUE TITLE
set a result limit number for isotope

### ISSUE THREAD

**Issue by RamyarIran** [metafizzy/isotope#848]
Hi

My code is like this, I have 4 categories and 10 items on each one of them, so there is 40 items when I click on all but I just want to show 10 of them :) 

```javascript
var $container = $('.weeklyitems');
  
  	$container.isotope({
	    itemSelector: '.col-md-3',
	    layoutMode: 'fitRows',
	    // filter: ':nth-child(-n+2)',
	    getSortData: {
	      category: '[data-category]'
	    }
	  });

	  $('#filters .wfbutton').on( 'click', function() {
	    var filterValue = $( this ).attr('data-filter');
	    $('#filters').find('.is-checked').removeClass('is-checked');
	    $( this ).addClass('is-checked');
    	$container.isotope({ filter: filterValue});
	  });
```

Can you guide me please ? Thanks

**Comment by desandro** [comment]
A simple way to do this is use a [filter function](http://isotope.metafizzy.co/filtering.html#functions) that checks if the item element's index is less than 10. See example:   http://codepen.io/desandro/pen/MYpaZw

``` js
function() {
  return $(this).index() < 10;
}
```

**Comment by Sawascwoolf** [comment]
Accessing the .index() Attribute only works for the initial dataset. I would like to display only the first 10 items regarding custum sorting orders. Is there any chance to get the current sorting?

**Comment by desandro** [comment]
@Sawascwoolf See http://isotope.metafizzy.co/faq.html#how-can-i-access-filtered-items-in-current-order

**Comment by nhekkens** [comment]
Is there a solution for this issue yet? That faq link doesn't seem to have the relevant section anymore.

I need to: 

Dom has 20 grid items, Isotope only shows 3. If i filter, i filter the entire pool of 20 but only show 3.

**Comment by SamBenson** [comment]
@nhekkens I need the exact same thing - did you have any luck?

**Comment by nhekkens** [comment]
@SamBenson I ended up using CSS. Not ideal, but got the job done.

**Comment by maurocolella** [comment]
I think you can do something like:
```
$targetGrid.isotope({
    filter: function() {
        return $(this).is(filterValue) && $(this).index(filterValue) < limit;
    }
});
```

Although it's far from a general solution at all.

**Comment by xfechx** [comment]
Hi everyone, 

My grid is only showing 10 items. Not sure where this is being limited. 

I would like the grid to show all items. 

Can somebody help me ?

**Comment by lsheva** [comment]
> I think you can do something like:
> 
> ```js
> $targetGrid.isotope({
>     filter: function() {
>         return $(this).is(filterValue) && $(this).index(filterValue) < limit;
>     }
> });
> ```
> 
> Although it's far from a general solution at all.


Didn't work well if filterValue is "*" (show all elements)
Suggest:
```
$('.js-isotope').isotope({
  filter: function() { 
    var index = $(this).parent().children(filterValue).index(this);
      return (index > -1) && (index < limit)
    }
});
```

**Comment by link2badar** [comment]
hope so, in future anybody will require this solution

declare variable before imagesLoaded function 
var counter = 1;

Add this filter inside the function. it will load 20 images for all on pageloading but on click of any other categories. it will show their images too as expectation. This function only work on the page load. when click on all again. it will show all
filter: function() {
                        if(counter <= 20){
                            counter++;
                            return true;
                        }
                        else{
                            counter++;
                            return false;
                        }
            }
