### ISSUE TITLE
horizontalAlignment with Layout mode different than vertical 

### ISSUE THREAD

**Issue by alvaro0555** [metafizzy/isotope#849]
Hi!
I love the plugin, I have used it before for some project and now I am trying to achieve a certain layout.
I would like to have a layout mode such as Packery or fitRows (vertical layout were no columnWidth is required) and align the elements in the center of the container rather than the left.
Could someone please point me some direction?
Thanks

**Comment by desandro** [comment]
Hi there! Thanks for the kind words. To help me understand what you're asking for, could you possibly provide an image of what you're thinking?

The closest thing I can think of is the experimental center-out branch of Packery. See https://github.com/metafizzy/packery/issues/62#issuecomment-33448503

**Comment by alvaro0555** [comment]
That experiment looks pretty cool! I was refering to something simlar to http://www.thomasduval.com/ or http://www.madebyparent.com/
As you can see its kind of Packery or fitRows mode where elements tend to align to the center (in the x axis).
Thanks desandro :)

**Comment by desandro** [comment]
Ah, thanks. Currently, there's no layout mode for these kind of layouts. If you would like to see a layout mode to support this, please **+1** this issue.

Isotope isn't well suited for this centered kind of layout. You may want to take a look at MitItUp, which is better suited.

**Comment by alvaro0555** [comment]
Thanks for looking at it. MixItUp doesnt seem to have it neither. Ill try to find some way to force this, if not Ill give up. Thanks!

**Comment by desandro** [comment]
pst @patrickkunka

**Comment by patrickkunka** [comment]
Hi @alvaro0555 - You could get close to the Thomas Duval design with MixItUp by using a combination of `text-align: center` on your container and `display: inline-block; vertical-align: middle` on your target elements. You would still have to have distinct rows on the x-axis, which is a limitation of the native CSS layouts that MixItUp uses. Thanks @desandro.

**Comment by alvaro0555** [comment]
@patrickkunka Thank you very much, I could manage to get something thanks to your comment: http://codepen.io/anon/pen/NPppON (The last row doesnt get centered though). It is a close attempt.

**Comment by patrickkunka** [comment]
@alvaro0555 Great. By the way - you don't need the "gap" elements in the markup unless you are using `text-align: justify;` on the container. Removing them should help with centering the last row.
