### ISSUE TITLE
Stamp/unstamp on window resize

### ISSUE THREAD

**Issue by matyushen** [metafizzy/isotope#852]
Hello. 
I'm trying to figure out how I can stamp/unstamp isotope item when resizing the window. I was trying to use enquire.js, but without luck. Maybe there is a better way to do that?
I want to display stamped item in top right corner on big screens and push it to the bottom of the isotope on smaller screens. 
Thanks.

				var $container = $('.loop-container'),
				$sidebar = $container.find('.loop-sidebar');

				function triggerIsotope() {

					if ( !$container ) {
						return;
					}

					$container.imagesLoaded(function(){

						$container.isotope({
							itemSelector: '.loop-item',
							stamp: $sidebar,
							masonry: {
								columnWidth: '.loop-item-sizer',
								gutter: '.loop-gutter',
							},
						});

						enquire.register("screen and (min-width:768px)", {
							match : function() {
								$container.isotope( 'stamp', $sidebar );
								$container.isotope('layout');
							},
							unmatch : function() {
								$container.isotope( 'unstamp', $sidebar );
								$container.isotope('layout');
							}
						})

					});
				}

**Comment by desandro** [comment]
Sorry, Isotope does not support this feature out of the box.
