### ISSUE TITLE
JqueryMobile Compatablity Problem

### ISSUE THREAD

**Issue by plane007** [metafizzy/isotope#854]
Everything works fine with jquerymobile when using my data in Masonry with this call. 

	var $container = $('#container');
	$('#container').masonry( {
	  	stamp: ".stamp",
		columnWidth: 220,
		itemSelector: '.item'
	});
	$container.imagesLoaded( function() {
	  $container.masonry();
	});

However, when using Isotope in the same page (changing the above code to become the following call), the items are stacked in one column only. 

The container is 900+ px wide and the items are 200px width

	var $container = $('#container');
        $('#container').isotope({
	  itemSelector: '.item',
	  stamp: ".stamp",
	  masonry: { columnWidth: 220 }
	});

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by plane007** [comment]
I have reduced the page to the point where it calls a script to load the 
data.

I believe that the script that supplies the data it is immaterial, since 
I have provided a simple switch between masonry and isotope for you to 
see the difference.

I give you two links to the same script for you too to see the effect 
easily:
Masonry version
Isotope version

The switch is created by using php to receive the single parameter given 
and to reveal each related lines of code at the bottom of the page. You 
will see that they are identical, except for the words masonry and 
isotope and yet give obviously different results

Warm Regards,
Peter Lane
MyGRWorld.com > Think Global, Act Local

CEO - MyGR Technology Ltd
020 8656 0187
22 Longhurst Road
Croydon CR0 7AS UK

Company Number: 05983593
(England & Wales)
ICO: Z1623231



------ Original Message ------

**Comment by desandro** [comment]
Sorry, but I'm unable to see your attachment. Please see the conversation on the GitHub Issue tracker https://github.com/metafizzy/isotope/issues/854

**Comment by plane007** [comment]
Sorry, I see the messaging software removed the links 

Try: 
http://www.mapworldlive.com/assets/php/testboard.php?use=masonry

http://www.mapworldlive.com/assets/php/testboard.php?use=isotope

**Comment by desandro** [comment]
On http://mapworldlive.com/assets/php/testboard.php?use=isotope it looks like [`isotope.pkgd.min.js`](http://isotope.metafizzy.co/isotope.pkgd.min.js) is not installed on the page.
