### ISSUE TITLE
Update fitRows in Isotope on Click

### ISSUE THREAD

**Issue by brigi02** [metafizzy/isotope#856]
Hi!
I tried so much but I can't solve it. I am working on a grid layout with Isotope. After clicking the items the grid should update to the fitRows layout. It works perfectly with the exception of field number 2 and 3.

Here is the JSFiddle:
http://jsfiddle.net/brigi/kqh2m9y4/1/

Can anyone help me out with this? I am really grateful for any advice.

Thank you so much!!!

**Comment by desandro** [comment]
Whoa, you must have found an old demo. For this kind of functionality, I recommend using [Packery with its `fit` method](http://packery.metafizzy.co/methods.html#fit)

See http://jsfiddle.net/kqh2m9y4/4/

**Comment by brigi02** [comment]
Amazing!! Thank you so much! 
I just implemented it and it works perfect, just my filtering doesn't work anymore. Any thoughts? Is there no filtering in Packery?

**Comment by desandro** [comment]
Unfortunately, the `fit` method is only available to Packery. And filtering/sorting is only available with Isotope. You'll have to choose between which feature you'd prefer.

**Comment by brigi02** [comment]
Is there an alternative to the "fit" method in Isotope? Like the code I used at first?

**Comment by desandro** [comment]
Try this version: http://jsfiddle.net/kqh2m9y4/6/
