### ISSUE TITLE
"Roll back / toggle" filtering with Isotope

### ISSUE THREAD

**Issue by Dedalos** [metafizzy/isotope#857]
I would like to know if it's possible to use Isotope filtering using a button that could toggle the filter back to initial state, not just only applying the filter with the button but be able tu "unfilter" again that item gruop.

I didn't find in the docs a way to do it..., it could be interesting for me to built a kind of intuitive navigation filtering content

**Comment by desandro** [comment]
How about this? http://codepen.io/desandro/pen/vEJbNr

``` js
$filters = $('#filters').on( 'click', 'button', function() {
  var $this = $( this );
  var filterValue;
  if ( $this.is('.is-checked') ) {
    // uncheck
    filterValue = '*';
  } else {
    filterValue = $this.attr('data-filter');
    $filters.find('.is-checked').removeClass('is-checked');
  }
  $this.toggleClass('is-checked');

  // use filterFn if matches value
  filterValue = filterFns[ filterValue ] || filterValue;
  $container.isotope({ filter: filterValue });
});
```

**Comment by Dedalos** [comment]
Hey! It looks great your sample, that was I meant. I would like to share how it looks now my code with your script above, because I'm not sure how to make it fit there. Anyway I think it could be interesting to show my code because there is a solution there for the hashtag thing, that you can take advantage of.
'

<script type="text/javascript">
  var defaultFilter = '.mosaic-home';

  // Init isotope
  var $container = $('#isotope').isotope({
    itemSelector : '.frontiles',
    layoutMode   : 'masonry',
    filter       : defaultFilter,
    masonry      : {

                  columnWidth  : 82,

           gutter       :12
            } // end masonry parameters
  });
  // Add hidden class if item hidden

  // Listen and handle filter click
  $('#filters a, #isotope a').on('click', function(e){

    // Get filter selector
    var filter = this.getAttribute('data-filter');

    // If there is no filter, continue with browser's default behavior
    if(!filter) {
      return;
    };
    e.preventDefault();

    // If filter is all (*), make it empty string for better appearance
    if(filter === '*') {
      filter = '';
    };

    // Set the location hash
    window.location.hash = filter;
  });

  // Listen for hash change
  $(window).on('hashchange', function() {

    // Filter the wall on hash change
    filterWall();
  });

  // Wall filter function
  function filterWall(initial) {
    // Get current hash
    var filter = window.location.hash.replace('#', '');

    if(initial && !filter) {
      filter = defaultFilter;
    };

    // Filter the wall
    $('#isotope').isotope({ filter: filter });

    // Remove selected class from the filter triggers
    $('#filters a, #isotope a').removeClass('selected');

    if(filter) {
      // Add selected class to the filter triggers
      $('#filters a, #isotope a').filter('[data-filter="' + filter + '"]').addClass('selected');
    };
  };

  // Initial filter (on page load)
  filterWall(true);




</script>
'

**Comment by Dedalos** [comment]
I'm sorry I cannot edit the former comment, this the code:


<script type="text/javascript">
  var defaultFilter = '.mosaic-home';

  // Init isotope
  var $container = $('#isotope').isotope({
    itemSelector : '.frontiles',
    layoutMode   : 'masonry',
    filter       : defaultFilter,
    masonry      : {

                  columnWidth  : 82,

           gutter       :12
            } // end masonry parameters
  });
  // Add hidden class if item hidden

  // Listen and handle filter click
  $('#filters a, #isotope a').on('click', function(e){

    // Get filter selector
    var filter = this.getAttribute('data-filter');

    // If there is no filter, continue with browser's default behavior
    if(!filter) {
      return;
    };
    e.preventDefault();

    // If filter is all (*), make it empty string for better appearance
    if(filter === '*') {
      filter = '';
    };

    // Set the location hash
    window.location.hash = filter;
  });

  // Listen for hash change
  $(window).on('hashchange', function() {

    // Filter the wall on hash change
    filterWall();
  });

  // Wall filter function
  function filterWall(initial) {
    // Get current hash
    var filter = window.location.hash.replace('#', '');

    if(initial && !filter) {
      filter = defaultFilter;
    };

    // Filter the wall
    $('#isotope').isotope({ filter: filter });

    // Remove selected class from the filter triggers
    $('#filters a, #isotope a').removeClass('selected');

    if(filter) {
      // Add selected class to the filter triggers
      $('#filters a, #isotope a').filter('[data-filter="' + filter + '"]').addClass('selected');
    };
  };

  // Initial filter (on page load)
  filterWall(true);




</script>

**Comment by Dedalos** [comment]
var defaultFilter = '.mosaic-home';

  // Init isotope
  var $container = $('#isotope').isotope({
    itemSelector : '.frontiles',
    layoutMode   : 'masonry',
    filter       : defaultFilter,
    masonry      : {

                  columnWidth  : 82,

           gutter       :12
            } // end masonry parameters
  });
  // Add hidden class if item hidden

  // Listen and handle filter click
  $('#filters a, #isotope a').on('click', function(e){

    // Get filter selector
    var filter = this.getAttribute('data-filter');

    // If there is no filter, continue with browser's default behavior
    if(!filter) {
      return;
    };
    e.preventDefault();

    // If filter is all (*), make it empty string for better appearance
    if(filter === '*') {
      filter = '';
    };

    // Set the location hash
    window.location.hash = filter;
  });

  // Listen for hash change
  $(window).on('hashchange', function() {

    // Filter the wall on hash change
    filterWall();
  });

  // Wall filter function
  function filterWall(initial) {
    // Get current hash
    var filter = window.location.hash.replace('#', '');

    if(initial && !filter) {
      filter = defaultFilter;
    };

    // Filter the wall
    $('#isotope').isotope({ filter: filter });

    // Remove selected class from the filter triggers
    $('#filters a, #isotope a').removeClass('selected');

    if(filter) {
      // Add selected class to the filter triggers
      $('#filters a, #isotope a').filter('[data-filter="' + filter + '"]').addClass('selected');
    };
  };

  // Initial filter (on page load)
  filterWall(true);

**Comment by Dedalos** [comment]
Sorry Im having some problems to edit comments and to add the code in a proper way, but in the comment below you can check out the code I'm using now.

**Comment by desandro** [comment]
Trying putting 3 tick marks around your code block:

    ``` js
    console.log('hello world')
    ```

**Comment by Dedalos** [comment]
I'm really sorry there are some problesm editing and removing my comments here, so I paste here again my code as you advice me WITHOUT your script included because I'm not sure the proper way to implement, would be great if you can tell me, and as I told you this code has hastag implementation working (if you can try tom remove my previous comments to clean the thread)
'''
  var defaultFilter = '.mosaic-home';

  // Init isotope
  var $container = $('#isotope').isotope({
    itemSelector : '.frontiles',
    layoutMode   : 'masonry',
    filter       : defaultFilter,
    masonry      : {

                  columnWidth  : 82,

           gutter       :12
            } // end masonry parameters
  });
  // Add hidden class if item hidden

  // Listen and handle filter click
  $('#filters a, #isotope a').on('click', function(e){

    // Get filter selector
    var filter = this.getAttribute('data-filter');

    // If there is no filter, continue with browser's default behavior
    if(!filter) {
      return;
    };
    e.preventDefault();

    // If filter is all (*), make it empty string for better appearance
    if(filter === '*') {
      filter = '';
    };

    // Set the location hash
    window.location.hash = filter;
  });

  // Listen for hash change
  $(window).on('hashchange', function() {

    // Filter the wall on hash change
    filterWall();
  });

  // Wall filter function
  function filterWall(initial) {
    // Get current hash
    var filter = window.location.hash.replace('#', '');

    if(initial && !filter) {
      filter = defaultFilter;
    };

    // Filter the wall
    $('#isotope').isotope({ filter: filter });

    // Remove selected class from the filter triggers
    $('#filters a, #isotope a').removeClass('selected');

    if(filter) {
      // Add selected class to the filter triggers
      $('#filters a, #isotope a').filter('[data-filter="' + filter + '"]').addClass('selected');
    };
  };

  // Initial filter (on page load)
  filterWall(true);



'''

**Comment by Dedalos** [comment]
I'm really sorry, this is a mess, I've recieved a 404 Not found from GitHub when I try to remove my failed comments, edit also is not working. :-( . But there is the code

**Comment by desandro** [comment]
Sorry, but I won't be able to debug your code. I'll leave implementation in your hands.

**Comment by patrickabels** [comment]
Hey

is this toogle method possible with button groups?
I use this code in my project.
Thanks in advance.

```
$(function () {
      // init Isotope
      var $container = $('.isotope').isotope({
          itemSelector: '.item',
          layoutMode: 'masonry',
          masonry: {
            columnWidth: '.item',
            isFitWidth: true
          },
          getSortData: {
              name: '.info h2',
          },
      });
      // store filter for each group
      var filters = {};
      $('.filtering').on('click', '.button', function () {
          var $this = $(this);
          // get group key
          var $buttonGroup = $this.parents('.button-group');
          var filterGroup = $buttonGroup.attr('data-filter-group');
          // set filter for group
          filters[filterGroup] = $this.attr('data-filter');
          // combine filters
          var filterValue = '';
          for (var prop in filters) {
            filterValue += filters[prop];
          }
          // set filter for Isotope
          $container.isotope({
            filter: filterValue
          });
          $('body, html').animate({
              scrollTop: 0
          }, 500)
      });
      // bind sort button click
      $('.sorting').on('click', 'button', function () {
          var sortValue = $(this).attr('data-sort-value');
          $container.isotope({
              sortBy: sortValue
          });
          $('body, html').animate({
             scrollTop: 0
          }, 500)
      });
      // change is-checked class on buttons
      $('.button-group').each(function (i, buttonGroup) {
          var $buttonGroup = $(buttonGroup);
          $buttonGroup.on('click', 'button', function () {
            $buttonGroup.find('.is-checked').removeClass('is-checked');
            $(this).addClass('is-checked');
          });
      });
    });
```
