### ISSUE TITLE
 no such method 'shuffle' for isotope instance ?

### ISSUE THREAD

**Issue by downFast** [metafizzy/isotope#859]
When i try
$container.isotope('shuffle');

I keep having this error and no shuffle at all  "no such method 'shuffle' for isotope instance"

Any idea? (using v2, not need it on a click)

**Comment by desandro** [comment]
See [FAQ - Error: “cannot call methods on isotope prior to initialization; attempted to call '___'”](http://isotope.metafizzy.co/faq.html#call-methods-error)
