### ISSUE TITLE
'noop' is undefined in IE8

### ISSUE THREAD

**Issue by bjo3rnf** [metafizzy/isotope#860]
I am facing this error message in IE8 (which I unfortunately have to support) even when visiting isotope's website. After adding ``var noop = function() {};`` the error is gone (well, 'getComputedStyles' is not defined, but that's another story). I am using the current version installed via bower. Any hints? Thanks in advance.

Cheers
Björn

**Comment by bjo3rnf** [comment]
Meh, this is obviously a problem with grunt-contrib uglify. nvm.

**Comment by robinnorth** [comment]
I've actually experienced this issue too and it appears to be a legitimate problem. In the latest version of `isotope.pkgd.js` from bower, versions of IE without `console` support will throw this error because the closure for `getSize` is missing a definition for `noop`.

**Comment by desandro** [comment]
@robinnorth Thanks for catching this. getSize v1.2.2 fixed this bug, but it wasn't properly added into the Bower distribution due to a tag bug. Isotope v2.1.1 resolves this.

**Comment by bjo3rnf** [comment]
Thanks to both of you for updating the issue.

**Comment by robinnorth** [comment]
@desandro Thanks for resolving this so quickly :+1:
