### ISSUE TITLE
Not sorting numbers correctly

### ISSUE THREAD

**Issue by JJJuergens** [metafizzy/isotope#861]
Hi,
I have a problem with isotope because the sorting option only works sometimes. I have different objects that all have 4 numbers in paragraphs and I would like to sort according to these numbers. My jsfiddle shows that it is not working: http://jsfiddle.net/p3g9f1Lx/2/
Why??
Thanks for any help!

**Comment by JJJuergens** [comment]
Just a quick comment: The four numbers are in the same order as the sort options above.

**Comment by desandro** [comment]
Thank you for the example! It looks like you just need to sort the values as _Number_s rather than text, you can do this by adding ` parseInt` to your [`getSortData` shortcut strings](http://isotope.metafizzy.co/sorting.html#getsortdata)

See http://jsfiddle.net/p3g9f1Lx/3/

``` js
isofp = new Isotope( '#fpDiv', {
  columnWidth: 30,
  itemSelector: '.fpobject',
  layoutMode: 'fitRows',
  getSortData: {
    kw1: '.total_kw1 parseInt',
    kw2: '.total_kw2 parseInt',
    kw3: '.total_kw3 parseInt',
    kw4: '.total_kw4 parseInt'
  }
});
```

**Comment by JJJuergens** [comment]
Hi desandro, perfect! Thanks a lot for your (always) quick and professional help! Sometimes the solution can be so easy... Have a great day!
