### ISSUE TITLE
When sorting by a numeral in data attribute Isotope will only order correctly if single-digit numerals are preceded by zero

### ISSUE THREAD

**Issue by NoahJW** [metafizzy/isotope#864]
When sorting content by a numeral in a data attribute I cannot simply order them 1, 2, 3, ... 9, 10, 11 ...

If I leave numbers 1-9 as single digits not preceded by a zero. Isotope will sort the page as 1, 11, 2, 12, 3, 13 ...

Preceding single digits with a zero fixes this perfectly—however the need for this is mentioned nowhere in the documentation, which netted me six hours of searching through the source code and almost lead me to another platform.

–Noah

**Comment by NoahJW** [comment]
You can view a clear example of this bug here:

http://codepen.io/desandro/pen/lzCqe

The sort options "number" and "numberBusted" draw from the exact same number and thus should yield the exact same results. "Number" refers to a class, "numberBusted" to a data attribute. If you click the two sort buttons you'll see you get different results.

**Comment by desandro** [comment]
Thanks for taking a look here. You pasted a link to the original sorting demo. Is this what you intended?

Also - it sounds like this problem can be resolved by adding  `parseInt` to the `getSortData` shortcut string

``` js
number: '[data-number] parseInt'
```

See http://codepen.io/desandro/pen/KwQVrQ
