### ISSUE TITLE
"not isotope" fade effect not working for me

### ISSUE THREAD

**Issue by wordfool** [metafizzy/isotope#866]
I've been trying to implement the fade-not-hide effect and am having no luck. The filtered items fade as they should, but then do their normal disappearing act. I suspect it might be something to do with other aspects of the the isotope plugin I'm using (courtesy Mandi Wise... https://github.com/mandiwise/isotope-posts), but I wanted to make sure I'm not missing somethig obvious. The basic code I'm using to initialize isotope is:

		var initialFilter = window.location.hash && ( '.' + window.location.hash.substr(1) ) || '*';

		var $container = $('#iso-loop').imagesLoaded( function () {
			$container.fadeIn().isotope({
				itemSelector : '.iso-post',
				layoutMode : iso_vars.iso_layout,
				filter : initialFilter,
				hiddenStyle: {
				  opacity: 0.5
				},
				visibleStyle: {
				  opacity: 1
				}
			});
		});

I've tried it with various binding methods, including the one from your codepen example:

               $('#filters').on( 'click', 'a', function() {
		  var filterValue = $( this ).attr('data-filter');
		  $container.isotope({ filter: filterValue });
		});

Any clues/suggestions appreciated.

**Comment by desandro** [comment]
Items need to be hidden completely, otherwise they'd overlap one another when laid out. If you would prefer to only change the opacity of items, then I would recommend not using Isotope for this use case. You could probably achieve this with basic jQuery. See http://codepen.io/desandro/pen/ByYpaG

``` js
$('#filters').on( 'click', 'button', function() {
  var filterValue = $( this ).attr('data-filter');
  // use filterFn if matches value
  filterValue = filterFns[ filterValue ] || filterValue;
  $items.filter( filterValue ).css({
    opacity: 1
  });
  $items.not( filterValue ).css({
    opacity: 0.25
  })
});
```

**Comment by wordfool** [comment]
Thanks... I'll give it a go. For some reason I though that example did use Isotope. Doh!  I might also explore the option of sorting with Isotope then writing a new opacity style to the un-selected items.
