### ISSUE TITLE
getCenteredMasonryColumns not working in V2

### ISSUE THREAD

**Issue by ropoman** [metafizzy/isotope#868]
Hi,

Is there a getCenteredMasonryColumns equivalent which is working in version 2 ?
Upgrading to version 2 solved my crashes in Safari, but now my tiles are not centered anymore

Thanks,
Ropoman

**Comment by ropoman** [comment]
https://github.com/metafizzy/isotope/issues/766

**Comment by downFast** [comment]
See this answer http://stackoverflow.com/questions/28212194/isotope-2-link-to-specific-filter-from-another-page-like-has-history?noredirect=1#comment44828546_28212194

Inviato da iPhone
