### ISSUE TITLE
3 columns bug on Bootstrap 3 with container-fluid

### ISSUE THREAD

**Issue by Emyleen** [metafizzy/isotope#871]
Hello everybody!

I have a strange problem on my page when I use isotope v2 in a container-fluid. I test my code on 2 identical pages except for the container type. When I'm on a page with a normal container, it works, I have my 3 columns regardless of the screen resolution, but on the page with the container-fluid, sometimes I have only 2 columns while remaining width on the right.

This is my fiddle : http://www.bootply.com/5q3GWcRfcA

Thank you for your help!

**Comment by desandro** [comment]
Thanks for reporting this issue. Problems like this should be resolved in the latest version of Isotope. Can you verify that you're using Isotope v2.1.0?

Otherwise, this may be a rounding error bug.

**Comment by Emyleen** [comment]
Thank you for your answer ! I have checked and I have the v2.1.0 but the bug is always here :/ 
If you have a solution in the future, thank you to tell me! ^^

**Comment by duckzland** [comment]
faced similar issue on fitRows, seems have to do with browser calculating width with fraction and different decimal number, my solution is to add 1 pixel to the isotope container width calculation

**Comment by desandro** [comment]
Closing this issue as it's been quiet for a while.

[Take a look at responsive layouts with Isotope](http://isotope.metafizzy.co/layout.html#responsive-layouts).
