### ISSUE TITLE
Help, images & filtering results

### ISSUE THREAD

**Issue by isohelp** [metafizzy/isotope#872]
Hi all, I am trying to figure isotope out but I can't. More designer that coder lol.

Anyways, here's what I am trying to do (picture attached). I am looking to use isotope to show 2 rows of image buttons. When one of each set is clicked I want it to show a single result. Could have all of the results listed at the start similar to the isotope demo then filter to single result.

Ive had a look through github, some of what I am asking may have transferable value for others.

Thank you, help would be awesome and greatly appreciated.

![isohelp](https://cloud.githubusercontent.com/assets/11162405/6332223/ffbcac9c-bb7b-11e4-94c6-7b439f9f3f5e.jpg)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by isohelp** [comment]
Hi David, thank you for the speedy reply.
I closed down codepen because I wasn't getting anywhere.
Is it worth me having another go and posting the result?
(if this issue is a breach of guidlines I will take it down)

Cheers

**Comment by desandro** [comment]
A CodePen with what you're trying to achieve would be great.
