### ISSUE TITLE
One column bug

### ISSUE THREAD

**Issue by andrew-luhring** [metafizzy/isotope#874]
# Isotope one column bug

Link to example + code:
http://plnkr.co/edit/C2atD2?p=preview

Link to just the preview:
http://embed.plnkr.co/C2atD2/preview
***

<figure>
    <figcaption><h1>Actual (with bug)</h1></figcaption>
    <a href="http://imgur.com/53sbugF"><img src="http://i.imgur.com/53sbugF.png" title="source: imgur.com" /></a>
  </figuren>
  <figure>
    <figcaption><h1>Expected</h1></figcaption>
    <a href="http://imgur.com/Lyotsvt"><img src="http://i.imgur.com/Lyotsvt.png" title="source: imgur.com" /></a>
  </figure>

#### Steps to reproduce

+ Click the "update" button. This should make the first box 2 columns wide.
+ Click the "herp" filter.
+ Click the "herp" filter again.

Or

+ Click a box. The border of it should turn blueish and should be the width of roughly two normal columns. The window should also scroll to the selected box.
+ Click a filter that contains the selected box.
+ Click the filter again.
+ Shouldn't have an effect but it instead moves boxes to one per line.

### Result:

The boxes collapse to one box per line.
That's the bug. 
The expected behavior is for the one box to be expanded and the other ones should fit the way they normally would;
If the filter is clicked multiple times the bug will occur.

For example:

Clicking "update" should expand rectangle 1.
Clicking herp should filter out some of the rectangles, leaving 1, 3, 4 and 6
Clicking herp again will make 1, 3, 4 and 6 be on their own lines.

Clicking "all" will reset columns to normal behavior until you click herp twice again.

Issue:
http://embed.plnkr.co/C2atD2/preview

**Comment by desandro** [comment]
Looks like what's happening is that you are filtering away the element used for measuring. We recommend using a proxy element, like `.grid-sizer`, that is only used for sizing, and not for actual content.  See [Isotope - masonry element sizing CodePen](http://codepen.io/desandro/pen/mIkhq).

Here's your example using a proxy sizing element http://embed.plnkr.co/whSc4xwSEhfDbL3vYp8e/preview

**Comment by andrew-luhring** [comment]
Wow.
