### ISSUE TITLE
Isotope hides elements if parent is hidden

### ISSUE THREAD

**Issue by anteksiler** [metafizzy/isotope#875]
If I add a class to the parent container of the isotope to hide it like:
```
<div class="hide">
<div class="isotope">...</div>
</div>
```
The isotope items gets their opacity set to 0, causing the isotope to height 0.

Is there anyway to prevent this?

**Comment by anteksiler** [comment]
On resize, the container gets height set, but the elements are still opacity 0, so nothing is visible.

**Comment by desandro** [comment]
A good way to resolve this is to trigger `.isotope()` after the container element is un-hidden. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
