### ISSUE TITLE
jquery isotope + infinite scroll + layout mode 'fitColumns' with php/mysql pagination issue

### ISSUE THREAD

**Issue by kunalm** [metafizzy/isotope#876]
I am trying to implement: 
1. imagesloaded, 
2. isotope 
3. infinite scroll 
4. layout mode: fitcolumns, on the following page:

https://mellowyelo.com/products_infinite.php?type=showall

Facing 2 issues:

1. Without applying "fixed" min height value to the item conatiner (i.e. '#products-container') the items are being stacked horizontally. However each item has been given fixed width and height but the container height is not being auto-calculated somehow.

2. The next page is not loading. I have set the "navSelector" and "nextSelector" options but when I scroll down to the page, the next set of items are not being loaded.

You can do a view source and take a look at the code. Here it is for your quick reference.

	$(function(){

      var $container = $('#products-container');
    
	  $container.imagesLoaded(function(){
		$container.isotope({
			layoutMode: 'fitColumns',
			itemSelector: '.item-holder'
		});
	  });
	  
      $container.infinitescroll({
        navSelector  : '#page_nav',
        nextSelector : '#page_nav a',
        itemSelector : '.item-holder',
		path: function(index) {
			return 'ajax-products.php?<?php echo $parts['query'] ?>&page='+index.toString();
		},
        loading: {
			msgText: 'Loading next set of items',
            finishedMsg: 'No more items to load.',
            img: 'https://i.imgur.com/qkKy8.gif'
          }
        },
        function( newElements ) {
			/*$container.imagesLoaded(function(){
          		$container.isotope( 'appended', $( newElements ) ); 
			});*/
			
			var $newElems = $( newElements ).css({ opacity: 0 });
			$newElems.imagesLoaded(function(){
				$newElems.animate({ opacity: 1 });
				$container.isotope( 'appended', $( newElements ) ); 
			}); 
        }
      );
		
    });

Kindly help. Thanks in advance. Appreciate your comments.

**Comment by desandro** [comment]
Sorry to hear you're having trouble. It sounds like you are running into multiple  issues. I would recommend making **reduced test cases** for each separate problem. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).


The code you have pasted is for Isotope, but the code on your site is for Masonry.

**Comment by kunalm** [comment]
Hi David

Yes, I changed it to Masonry later on as I was having trouble with isotope
and infinite scroll. I will keep trying and post more comments.


--
Thanks & best regards,
Kunal Mukherjee

Cell/iMsg/Whatsapp: +91 9831072343
Skype: kunal_mukherjee
Gtalk/iMsg: mukherjiikunal@gmail.com
