### ISSUE TITLE
Grid ratio on images breaking alignment on padding/margin additions

### ISSUE THREAD

**Issue by richgcook** [metafizzy/isotope#877]
Hi folks,

I am trying to make my grid 'fit' with large, tall, small and wide images. They all have the same aspect ratio so when I have no margin or padding on my grid elements, everything fits perfectly (see first attachment) but then as soon as I add the padding (padding-left/right: 15px and margin-bottom: 15px) it breaks the alignment. (see second attachment).

I am using the bootstrap grid for these elements.

Any thoughts? @desandro 

Cheers,
R

![home bm3 architects](https://cloud.githubusercontent.com/assets/901289/6425542/d03e3352-bf25-11e4-95ec-c0d95d482d32.png)

![home bm3 architects 2](https://cloud.githubusercontent.com/assets/901289/6425541/d03b213a-bf25-11e4-8504-7e9c7be092a0.png)

```
if ($('.home-project-news-container').length > 0) {
	$(function() {
		var $container = $('.home-project-news-container');
		$container.imagesLoaded(function() {
			$container.isotope({
				itemSelector: '.each-home-project-news',
				masonry: {
					columnWidth: '.grid-sizer'
				}
			});
		});
	});
}
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by richgcook** [comment]
Hi @desandro thank you for the reply. I have set up two reduced cases... one without padding/margin and one with to reiterate the image screenshots above. Many thanks.

http://codepen.io/anon/pen/xbzaoW

http://codepen.io/anon/pen/jEKeEM

**Comment by desandro** [comment]
Thanks for that. Looks like the problem is how this example mixes percentage values (the width of the items) with pixel values (the padding between items). This is not necessarily a Masonry problem as much as it is a CSS problem.

You can achieve this kind of layout, but you have to use hard-coded height values, not proportional height values derived from images. See http://codepen.io/desandro/pen/RNJEeq

Also, I recommend you use `$(document).ready` over `$(window).load`. See http://stackoverflow.com/a/26929965/182183

**Comment by richgcook** [comment]
Thanks for the reply and help, @desandro, really appreciated.

I've been trying to work it all out and calculate why, with percentages then fixed padding it would break the ratio. I guess 15px and 66% and 15px and 33% are going to provide newer, different heights.

I'll would try percentage padding but this is slack. I guess fixed heights is the best option; a bit tricky with responsive grids though.

I'll keep you posted, and thanks again.
