### ISSUE TITLE
TypeError: isotope.options is undefined

### ISSUE THREAD

**Issue by jm21** [metafizzy/isotope#881]
Am trying to set up isotope on a page which was running masonry(which ran fine) I need the filter options for isotope. I've installed isotope with bower and am having issues when trying to run the script.
Below is my script:

 var container = document.querySelector('#allstories');      
 iso = new Isotope( container, {
        itemSelector: '.grid_story'
 } );

Any idea on what could be wrong?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by jm21** [comment]
Hi desandro. Thanks for getting back to me. Please check out the following link for more info
http://198.101.244.253/testcase/stories.html. We are using webpack to load the page

**Comment by desandro** [comment]
Sorry, but I'm not able to debug your production site. If you can provide a **reduced test case** I can take a better look.
