### ISSUE TITLE
expand element on click with isotope

### ISSUE THREAD

**Issue by stacybirdy** [metafizzy/isotope#882]
So I'm using Isotope to sort and filter some information. Obviously. Need to initially display only the title of each list item, then expand it to show details on click. Each of these actions is technically working (isotope is sorting/filtering properly, clicking the title div is causing the details div to display), but they don't play nice. The absolute positioning applied by isotope is preventing the other list items from adjusting appropriately when any of the details divs are revealed.

I've seen a few posts discussing re-adjusting the items on animation, but they all have a set height for the expanding element and in my case the heights will be based on content and not equal.

example codepen: http://codepen.io/stacybirdy/pen/emPwxj

So when one of the items is clicked, everything below it should move down to accommodate the the extra content instead of having it expand behind the other items. Will this be possible?

**Comment by zuhloobie** [comment]
Hey @stacybirdy. I had almost the exact same question back in Nov. See here: https://github.com/metafizzy/isotope/issues/818

**Comment by stacybirdy** [comment]
@zuhloobie welllllll don't i look silly for missing that thread. THANKS!

**Comment by zuhloobie** [comment]
It's okay :)
