### ISSUE TITLE
Isotope Container height not updating on "append" [Help]

### ISSUE THREAD

**Issue by amitbiswas06** [metafizzy/isotope#884]
Hello, I am using isotope "append" method for my WordPress portfolio site to load more content by ajax and within isotope container. So far everything is working nicely except one thing that is -

1. The isotope container height is not updating automatically after each append occurs. But if I refresh the page once, and click on "load more" button, then the isotope container height is updating.

So the issue is, first time when I load my page, and then if I press "load more" button, the content is appending but the isotope container height is not updating automatically.

Please help me to fix this issue. I have less experience in jQuery and ajax and learning now.

Using isotope 2.0
Here is my code below - 

<pre>
$(window).load(function(){
    var $container = $('.portfolioContainer');
    $container.isotope({
        filter: '*',
    });
	/* dynamically fetching the portfolio items */
var page = 1;
var loadMorePosts = jQuery('.view-more-btn').text();

function loadMore() {
	page++;
	$.ajax({
		method: "get",
		url: './page/' + page + '/',
		beforeSend: function() {
			jQuery('.view-more-btn').html("<i class='fa fa-spinner fa-spin'></i>");
		},
		complete: function() {
		},
		success: function (data) {
			var $data = jQuery(data).find('.portfolio');
			if($data.length > 0) {
				jQuery('.view-more-btn').html(loadMorePosts);
				// isotope items apend
				$container.isotope()
				.append( $data )
				.isotope( 'appended', $data )
				.isotope( 'layout' );
			}
			else {
				jQuery('.view-more-btn').html('No More Items');
			}
		},
		error: function() {
			jQuery('.view-more-btn').html('Nothing Left');
			 $(".view-more-btn").removeAttr('href');
			 
		}
	});
}
jQuery('.view-more-btn').click(function(e) {
	e.preventDefault();
	loadMore();
});
/* end dynamically fetching the portfolio items */
 
    $('.portfolioFilter a').click(function(){
        $('.portfolioFilter .current').removeClass('current');
        $(this).addClass('current');
 
        var selector = $(this).attr('data-filter');
        $container.isotope({
            filter: selector,
         });
         return false;
    }); 
});

</pre>

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues). Try forking [the appended CodePen](http://codepen.io/desandro/pen/ECKiw).

**Comment by amitbiswas06** [comment]
I tried to use codepen. But as I am using ajax (method get with url), its hard to fetch data on codepen due to CORS issue. Can you please look at my code above? I think you can help me by this. I can upload snapshot if needed. I have explained this issue in details for better understanding. Please help me!

**Comment by amitbiswas06** [comment]
Dear Desandro,

I manage to fix this issue with help of "imagesLoaded". Thanks to this issue where you have helped on similar issue - https://github.com/metafizzy/isotope/issues/76

Thanks for a great jQuery. Isotope is best! Cheers!
-Amit

**Comment by tkhuynh** [comment]
I have issue with isotopContainer height and it's with angular. For example, at initial load, I load 15 images using ng-repeat, and let say isotopContainer height is 1500px. Then click another button, those 15 images will be replace with 5 other images. All images has the same height and width, so at this moment isotopContainer height should be reduced to 500px but it's still at 1500px even thought there are only 5 images. Then if click another button, and those 5 images will be replaces with 5 other images. This time isotopContainer is changed to 500px which I want. I do not understand why isotopContainer height did not change at the second loading time.

@desandro any thoughts? Thanks

**Comment by RiadC123** [comment]
Hey @amitbiswas06 

Can you please share the code after implenting "imagesLoaded" that would be really helpful for me.

Thanks
