### ISSUE TITLE
Variable size on rearrange move vertical

### ISSUE THREAD

**Issue by blpraveen** [metafizzy/isotope#886]
I have configured `layoutmode` masonry and using the isotope to display blocks which collapse and expands.
on expand calling below function to rearrange the items

         $container.isotope('layout');

When the item is in the last column it moves down. if item is in any other columns the whole item moves to re-arrange
How do I make it to move down items which are below the item expanded or collapsed?

Thanks , Please let me know if it is possible

**Comment by desandro** [comment]
Sounds like you're asking for Masonry column shift. See #582 . Closing as a duplicate.
