### ISSUE TITLE
Bower Error Installing

### ISSUE THREAD

**Issue by christianmagill** [metafizzy/isotope#887]
C:\Projects\.....>bower install isotope --save

bower isotope#*                 cached git://github.com/metafizzy/isotope.git#2.1.1
bower isotope#*               validate 2.1.1 against git://github.com/metafizzy/isotope.git#*
bower get-size#>=1.2.2 <1.3     cached git://github.com/desandro/get-size.git#1.2.2
bower get-size#>=1.2.2 <1.3   validate 1.2.2 against git://github.com/desandro/get-size.git#>=1.2.2 <1.3
bower matches-selector#>=1 <2   cached git://github.com/desandro/matches-selector.git#1.0.3
bower matches-selector#>=1 <2 validate 1.0.3 against git://github.com/desandro/matches-selector.git#>=1 <2
bower outlayer#1.3.x            cached git://github.com/metafizzy/outlayer.git#1.3.0
bower outlayer#1.3.x          validate 1.3.0 against git://github.com/metafizzy/outlayer.git#1.3.x
bower masonry#3.2.x             cached git://github.com/desandro/masonry.git#3.2.2
bower masonry#3.2.x           validate 3.2.2 against git://github.com/desandro/masonry.git#3.2.x
bower get-style-property#1.x    cached git://github.com/desandro/get-style-property.git#1.0.4
bower get-style-property#1.x  validate 1.0.4 against git://github.com/desandro/get-style-property.git#1.x
bower doc-ready#1.0.x           cached git://github.com/desandro/doc-ready.git#1.0.4
bower doc-ready#1.0.x         validate 1.0.4 against git://github.com/desandro/doc-ready.git#1.0.x
bower eventie#~1.0.3            cached git://github.com/desandro/eventie.git#1.0.6
bower eventie#~1.0.3          validate 1.0.6 against git://github.com/desandro/eventie.git#~1.0.3
bower eventEmitter#>=4.2 <5     cached git://github.com/Wolfy87/EventEmitter.git#4.2.11
bower eventEmitter#>=4.2 <5   validate 4.2.11 against git://github.com/Wolfy87/EventEmitter.git#>=4.2 <5
bower eventie#^1            not-cached git://github.com/desandro/eventie.git#^1
bower eventie#^1               resolve git://github.com/desandro/eventie.git#^1
bower eventie#^1          ENORESTARGET Tag/branch ^1 does not exist

Additional error details:
Available tags: v0.0.1, v0.0.1^{}, v1.0.0, v1.0.0^{}, v1.0.1, v1.0.1^{}, v1.0.2, v1.0.2^{}, v1.0.3, v1.0.3^{}, v1.0.4, v1.0.4^{}, v1.0.5, v1.0.5^{}, v1.0.6, v1.0.6^{}
Available branches: master

**Comment by desandro** [comment]
Try `bower cache clean` and installing again.
