### ISSUE TITLE
Remove element without deleting from DOM

### ISSUE THREAD

**Issue by vercotux** [metafizzy/isotope#889]
What is the correct way to remove/unbind an element without removing it from DOM, preferably with an animation?
For example taking one element out and moving it somewhere else.

**Comment by desandro** [comment]
Thank you for your question. Could you provide a **reduced test case** so others could understand what you're trying to do? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by rohan-deshpande** [comment]
+1 for this because I'm using isotope with React js and it doesn't seem to like it when Isotope removes things from the DOM. Is there some way to simply trigger the remove transition (adding a CSS class maybe?) without the DOM removal?
