### ISSUE TITLE
Isotope does not format the list on the second call

### ISSUE THREAD

**Issue by jvence** [metafizzy/isotope#890]
I have a list that is dynamically refreshed. The first time isotope is initialized the list is displayed correctly. But when a new list is retrieved and isotope called, the list is never formatted. The culprit is the following code: 
   var instance = $.data( this, namespace );
        if ( instance ) {
          // apply options & init
          instance.option( options );
          instance._init();
        } else {
          // initialize new instance
          instance = new PluginClass( this, options );
          $.data( this, namespace, instance );
        }
where a new instance is never initialized. 

Perhaps we need to specify a variable to ignore old data in some cases.

**Comment by jvence** [comment]
Best solution was to disassociate the data using $('#container').removeData("isotope")

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by republicryan** [comment]
I'm also having the same issue. I create my lists via ajax, and isotope only runs on the first instance. I'll put up a codepen test case as soon as possible.
