### ISSUE TITLE
Sorting is not working properly with isotope

### ISSUE THREAD

**Issue by medateja** [metafizzy/isotope#891]
Basically, I have divs with different height. When I applied isotope with sorting enabled as "original-order", Its not showing properly. I need to have masonry(pinterest) layout with sort option.
Can you check it here : http://codepen.io/anon/pen/azXByO

**Comment by desandro** [comment]
Masonry layout is looking as expected. Masonry layouts are not ordered left-to-right, rather they work top-to-bottom. So you'll see that the 6 blocks is higher up than the 7 block. This is how Masonry layout works
