### ISSUE TITLE
Picturefill and Isotope

### ISSUE THREAD

**Issue by albi** [metafizzy/isotope#892]
Hi deSandro,

having an issue with picturefill.js (used in Wordpress as plugin called "WP Retina 2x") and Isotope (latest). Picturefill is running in the <head> and Isotope at the end (combined with other scripts). Even wrapping document ready around isotope won't layout al tiles properly. Some of them are displayed above others. Mostly at the end of the site. imagesloaded() is included and works as expected.

I think it has to do with the method picturefill replaces the images. Is there any callback to start the isotope layout after picturefill is done?

Example: http://silvioketterer.ch/projekte/

Kind regards
Alex

**Comment by desandro** [comment]
Thanks for reporting this issue. Looking over the [picturefill.js docs](http://scottjehl.github.io/picturefill/#api) it appears that picture fill does not provide any callbacks or event handling. 

Closing here. See convo at scottjehl/picturefill/#467
