### ISSUE TITLE
Packery - relayout issue (jerky animation)

### ISSUE THREAD

**Issue by OnkelTem** [metafizzy/isotope#893]
Hi!

First, let me thank you for the great tool. I almost made my gallery working, but there are couple of  issues to solve.

The test case is here: http://codepen.io/anon/pen/OPqgaq
It is a rewrite of your example: http://codepen.io/desandro/pen/jeLKl

I just replaced isotope with packery and added some custom stuff.

As you may see, each block should expand to show detailed information. This happens on click event and, its width doubles.

Issues:

1) The animation is jerky. The reason - is 52nd line, where I force reflow. I know it is bad, but without it (try to comment it), the order of items is wrong (see below **)
2) There is a redundant animation: say you started with clicking on CELL 1 and DETAILS 1 is appeared to the left. Now click CELL 2 and you will see how it moves to the left first, then when DETAILS 2 box starts appearing, CELL2 moves back to the right. I don't want CELL 2 to move at all.

**) If I remove 52nd line, I get into next usability issue: click CELL 1 to expand it. Now click CELL 2. Instead of stying on its place, it moves to the right and is placed to the right of CELL 3. This is not appropriate.

Please, if you have ideas, help! I need this asap :) Thanks in advance!

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like your example is running into a conflict with using `fit()`, which lays out one item, versus `layout()` which lays out all the items. Unfortunately, I don't think there's a perfect solution here. Either you can stick with using both. Or a simple solution is just to use `layout()`: http://codepen.io/desandro/pen/emXPba Yes, the expanded item might move around, but it works.

**Comment by OnkelTem** [comment]
Yes, it looks better now. But note the behavior of the 5th cell: when you click on it (when there is no selected cells in its row), it jumps to the next row :(
