### ISSUE TITLE
Licence Clarification 

### ISSUE THREAD

**Issue by syedazampasha** [metafizzy/isotope#896]
Hi, 
Need some clarification on Licence, Is one licence is applicable for both Isotope and Packery ?, 
as Isotope uses packery to work. 

can u plz confirm. 

Thanks!!

**Comment by desandro** [comment]
Hello! Yes, you only need one license to use Isotope with the [packery layout mode](http://isotope.metafizzy.co/layout-modes/packery.html).

**Comment by syedazampasha** [comment]
Hey I have buyed the Licence for Unlimited Applications. my question is do i need to include some where in the website ? 
can you please clarify.

Thanks!!

**Comment by desandro** [comment]
After you purchase an Isotope Commercial License, I have record of your purchase, so there is no additional registration to go through.

**Comment by syedazampasha** [comment]
Thanks for confirming. :) happy to use PACKERY /  ISOTOPE
