### ISSUE TITLE
Weird animation with a slideToggle stamp

### ISSUE THREAD

**Issue by dansa** [metafizzy/isotope#897]
I have a list of squares, each having a button which toggles a list of available files.

I have gotten everything to work but the animation is a bit weird, I am using the stamp function to realign the list, and a slidetoggle to display/hide the stamp.
I made a codepen to display the problem:
http://codepen.io/anon/pen/qEevdL

I couldn't find anything in the docs that would make the list and stamp animate simultaneously but perhaps I'm missing something?

**Comment by desandro** [comment]
Take a look at how to animate item size: http://packery.metafizzy.co/appendix.html#animating-item-size They use an extra element that sets the initial space. Then an inner element is animated. Both animations happen at the same time with this technique.

**Comment by dansa** [comment]
Thanks a lot for that, definitely pointed me in the right direction.
Had to resort to using velocity.js because css transitions were being weird 
For some reason the list would only transition up and instantly grow "down", might have had something to do with the workaround I used to set height to "auto" though.
Feel free to mark this as solved!
