### ISSUE TITLE
combining search field with 3 select dropdowns to filter

### ISSUE THREAD

**Issue by cfurer** [metafizzy/isotope#899]
I try to sort together with dropdowns and search field. i tried to modify using this example: http://codepen.io/desandro/pen/mCdbD/

My goal i want to change the 3 buttons into selects.

Something like this:

<p><input type="text" id="quicksearch" placeholder="Search" /></p>
    <div id="lexikon-filter" class="col span_9">
        <select data-filter-group="gestein">
            <option value="*" data-filter-value="" class="button is-checked">Alle Gesteine</option>
            <option data-filter-value=".metal" value=".metal">metal</option>
            <option data-filter-value=".transition" value=".transition">transition</option>
         </select>
         <select data-filter-group="farbe">
             <option value="*" data-filter-value="" class="selected">Alle Farben</option>
             <option data-filter-value=".red" value=".red">RED</option>
             <option data-filter-value=".blue" value=".blue">BLUE</option>
         </select>
</div>
But how does the javascript look like?

**Comment by downFast** [comment]
He provided an example http://codepen.io/desandro/pen/GFbAs

**Comment by cfurer** [comment]
I've seen, but how to combine with a search field. There I've some troubles. http://codepen.io/desandro/pen/mCdbD/ I tried to modify this example and change the button groups with the select, but i didn't get it. :( Can you help me what i have to do?

**Comment by downFast** [comment]
have a look here, it might help you http://jsfiddle.net/63cUD/3/

**Comment by desandro** [comment]
Sorry, but I won't be able to provide a solution here.

**Comment by karki-dennis** [comment]
https://codepen.io/karki-dennis/pen/XgEYew
