### ISSUE TITLE
On LayoutComplete

### ISSUE THREAD

**Issue by blpraveen** [metafizzy/isotope#900]
I am still using the old versions of the isotope as the page is relied on `Layout Mode ``masonryColumnShiftReset`. Now I have different issue . I am using the isotope inside a tab which will be hidden. when the tab becomes active all the items are collapsed and needs to be resized again.

I tried new version of Isotope and used `layoutcomplete` to trigger the window resize function.
Can you help how it could be achieved on older version of isotope.

	$('.page-tabbed #itemList').isotope( 'on', 'layoutComplete', function() { 
		$(window).resize();
	});

**Comment by desandro** [comment]
1. I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
2. Sounds like you are using an older version of Isotope, which does not support `layoutComplete` event
3. If you are using Isotope within a tab, then you need to trigger `layout` when that tab is revealed.

**Comment by blpraveen** [comment]
I want trigger the LayouComplete Event to resize the tab content height on filter
