### ISSUE TITLE
imagesLoaded and initialization

### ISSUE THREAD

**Issue by MattDiMu** [metafizzy/isotope#902]
To make sure, that the items never overlap, I'm using the imagesLoaded-Callback 
```js
// initialize Isotope
var $container = $('#container').isotope({
  // options
});
// layout Isotope again after all images have loaded
$container.imagesLoaded( function() {
  $container.isotope('layout');
});
```
Source: http://isotope.metafizzy.co/appendix.html

and I'm getting the following message in the console:

```
isotope.pkgd.js:64 cannot call methods on isotope prior to initialization; attempted to call 'layout'
```

I don't like console errors :P Is there (I haven't found any) some sort of callback for the initialization of isotope, so i can make sure, that the imagesLoaded callback isn't fired too early?

The existing layoutComplete event seems not to be fired on the initialization.

Regards

**Comment by desandro** [comment]
Thanks for reporting this issue. This is a weird bug. Could you provide a **reduced test case**? Try forking this CodePen: http://codepen.io/desandro/pen/WvNpwX See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by MattDiMu** [comment]
I found the issue, it was in my code. TBH I do NOT understand the difference, but it works now:


trigger layout using $(this)
```js
var mashups= $('.mashup').each(function(){
	var $iso = $(this).isotope();

	$iso.imagesLoaded(function(){
		$(this).isotope('layout');
	});
});

```


trigger layout using $iso

```js
var mashups= $('.mashup').each(function(){
	var $iso = $(this).isotope();

	$iso.imagesLoaded(function(){
		$iso.isotope('layout');
	});
});
```
