### ISSUE TITLE
Isotope doesn't work at all

### ISSUE THREAD

**Issue by aFreshMelon** [metafizzy/isotope#903]
I'm getting the following errors:

```
Uncaught TypeError: Cannot read property 'Item' of undefined ->
isotope.self-bf175132d17ff27383861570337406d15edf41c09d5603b8d8662f78aebef978.js?body=1:56

Uncaught TypeError: $(...).isotope is not a function  ->
streams2.self-a9a7fe134f822b10461211eabdf4a6ce0ba6cd2cae707711d5b38546414e0f7e.js?body=1:3
```

This is the script I use to initialize, it raises the second error:

```javascript
$( document ).ready( function() {

  var $container = $('.flex-grid').isotope({
    itemSelector: '.card',
    layoutMode: 'fitRows',
  });

  $container.isotope({ filter: '.online' });

});
```

The first error is raised by isotope.js itself, meaning the script must be somewhat broken or I have an error in my JavaScript order.

I use bower for dependency management. Here is my JavaScript loading order, all of this is at the very end of the body tag in my HTML.

```
<script src="/assets/jquery/dist/jquery.self-0664d02dcbfb008e715c754b00b9af29d6f1796828c03610aee4265bdfc6afff.js?body=1"></script>
<script src="/assets/jquery_ujs.self-8e98a7a072a6cee1372d19fff9ff3e6aa1e39a37d89d6f06861637d061113ee7.js?body=1"></script>
<script src="/assets/isotope/js/isotope.self-bf175132d17ff27383861570337406d15edf41c09d5603b8d8662f78aebef978.js?body=1"></script>
<script src="/assets/velocity/velocity.self-25391939afee1c8b82fecb9cf2c898b75da7d2c53371631fca570c79f379215a.js?body=1"></script>
<script src="/assets/helpers/search.self-31ad746dbd6d25fc9405c841e32d5b87661fd2142db735d0ca63ac0f814cff37.js?body=1"></script>
<script src="/assets/nav.self-7eeac04b70af26398f39a9cfdff44cb8a51f59af5efe82cf967ff157dd687a60.js?body=1"></script>
<script src="/assets/streams.self-6d328622adbaa12ea431cf32e077d3c79c2ddbe9e4fac4f1a871b3d5a253a1c4.js?body=1"></script>
<script src="/assets/streams2.self-a9a7fe134f822b10461211eabdf4a6ce0ba6cd2cae707711d5b38546414e0f7e.js?body=1"></script>
<script src="/assets/application.self-7c370d9536d7d0d6a0f7cd7f9826692acd93e4fb05ba46f7b630b879740343d3.js?body=1"></script>
```

What's wrong? (jQuery version is 2.1.3 as loaded from bower)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by aFreshMelon** [comment]
It was because the bower main file is not the packaged version for some reason. That should probably be fixed @desandro.

**Comment by ElpySites** [comment]
I have exactly the same problem. I've been trying to fix it for quite some time, but unsuccessfully. What exactly did you do?

**Comment by aFreshMelon** [comment]
I removed Isotope already because it doesn't work with Flexbox, but you have to change your include to ``isotope/dist/isotope.pkgd.js`` instead of just ``isotope``. At least in Rails that's how it worked.

**Comment by ElpySites** [comment]
Unfortunately for me, that didn't fix the problem of Item undefined.

**Comment by liujason** [comment]
Like @sebastianbarfurth, I have almost the exact problem. I use bower wiredep to manage dependencies, and included all the js from isotope. it didn't work unless I include the isotope.pkgd.js manually.

**Comment by laurend** [comment]
I have the same problem as described by @liujason. I've included the isotope.pkgd.js manually and it works. Is this something that can be fixed so that bower + wiredep works as it's supposed to?

**Comment by ElpySites** [comment]
I solved this without including isotope.pkgd.js manually, you just need to include js in the right order. Solution for me was to include isotope before everything else.

**Comment by desandro** [comment]
For wiredep related issues, please see #879. Locking discussion here
