### ISSUE TITLE
cellsByRow calculation error?

### ISSUE THREAD

**Issue by brianfor44** [metafizzy/isotope#904]
I am trying to use cellsByRow in a grid of thumbs with slightly different length titles. 
So far I have: 
```javascript
    var $container = $('.container-collection').imagesLoaded( function() {
        $container.isotope({
            layoutMode: 'cellsByRow',
            itemSelector: '.thumb',
            cellsByRow: {
                columnWidth: '.thumb',
                rowHeight: '.thumb'
            }
        });
    });
```
Somehow some of the thumbs are further down then they should. For example:
```html
<div class="col-md-3 col-sm-4 col-xs-6 thumb" style="position: absolute; left: 0px; top: 383px;">
<div class="col-md-3 col-sm-4 col-xs-6 thumb" style="position: absolute; left: 0px; top: 394px;">
<div class="col-md-3 col-sm-4 col-xs-6 thumb" style="position: absolute; left: 0px; top: 383px;">
<div class="col-md-3 col-sm-4 col-xs-6 thumb" style="position: absolute; left: 0px; top: 383px;">
```

How can I prevent this from happening? Otherwise all works great. If I resize the window, other thumbs will get the wrong numbers also. 

Thank you for any help with this.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
