### ISSUE TITLE
iphone crash issule

### ISSUE THREAD

**Issue by chiragparekh** [metafizzy/isotope#906]
Hi,

Here is my page link: http://kenindotechnology.com/product.html
I used isotope for portfolio.When I open this page in my iphone4 and iphone6 it crash my whole site.
Looking forward for your support.

Thanks.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
