### ISSUE TITLE
Can't make it work :/

### ISSUE THREAD

**Issue by Redani** [metafizzy/isotope#907]
Hi,
I'm currently using mixitUp and thinking to switch to isotop. I looked at the doc and it looks promising :) thank by the way for this amazing plugin ;)
I do have some fe question:
1- I'm using a layout that displays 1 element per row, i do not specify any height because it can vary, when I use isotop, it's all messed up, I was wondering if I can use isotop without have a specific height.
I tried layoutMode: 'vertical' but still not working well!

2- I can't make the filters work, when I changed the code, I've noticed that I have to use <button>, but i'm using the following code:  `<ul><li><a href="#" data-filter="">Filter</a><li></ul>`
is there a way to make it work that way?

3- I would like to be able to switch between "grid" and "list" view using isotop, can it be done with layoutMode?

Thank you for your inlights
Regards

**Comment by desandro** [comment]
1 & 2: I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

3: Yes, you can change the layoutMode options. Or if you're using a simple grid, you can change the items size and the layout mode should handle it after `.isotope('layout')`, with masonry or fitRows layout modes.

**Comment by Redani** [comment]
Thank you for your reply. I'll post a reduced test case soon :)

**Comment by Redani** [comment]
Hi Desandro, how are you?

Here is a simplified test code: http://codepen.io/anon/pen/waKbYp
I'm sure i might be missing something very stupid :D

Thanks a lot for your help ;)

**Comment by desandro** [comment]
Thanks for your example. Here's a working version I put together: http://codepen.io/desandro/pen/rVxBar I found two problems:

1 - You were missing code to [filter isotope](http://isotope.metafizzy.co/filtering.html#ui) on the `#filters` link click. I've added:

``` js
  $('#filters').on( 'click', 'a', function( event ) {
    var filterValue = $(this).attr('data-filter');
    $container.isotope({
      filter: filterValue
    });
  });
```

2 - the jQuery tools script was breaking jQuery. I'm not sure why. When I removed it, things look to be working fine.

Hope this helps!

**Comment by Redani** [comment]
Hi, and thanks for your reply.

1- ah OK!
I have forgotten to add class="filter" to the links in the code sample that i have updated, and I was wondering if there is a way to automatically bind filter to the links that have .filter class to prevent writing up additional code.

2- the example you gave me works well, but i'm looking to have only 1 <li> per row, how can this be achieved?

Thanks a lot

**Comment by desandro** [comment]
2 - use [vertical layout mode](http://isotope.metafizzy.co/layout-modes/vertical.html), or change the width of items to be full width

**Comment by Redani** [comment]
Oh cool, thanks :)

what about question 1, are you planing to add the possibility to automatically bind filter and sorting to an element with a specific class name? (hope you understand what i mean!)

3- what is actually the limit of rows to keep an optimal performance and speed? I'm asking you this question coz with mixItUp it gets very slow once we load over 150 rows...

Thanks

**Comment by desandro** [comment]
> are you planing to add the possibility to automatically bind filter and sorting to an element with a specific class name?

I've got an idea, but it will require some focused development

> what is actually the limit of rows to keep an optimal performance and speed

Isotope works best with less than 100 items. More than that and I can guarantee good performance.

**Comment by Redani** [comment]
OK, thanks for all and looking forward to isotope updates... :)
Have an amazing week end.

**Comment by Redani** [comment]
Hi Desandro,

I've started to integrate isotope then I realised that in addition to the filter code, i have to add also the code to change class name for the clicked filter :(
It would be great if you could also add this in the core code to prevent writing inline additional code...

Thanks
