### ISSUE TITLE
Surface Tablet issue

### ISSUE THREAD

**Issue by keithklingen** [metafizzy/isotope#909]
Isotope tiles display correctly when you view them in the browser on the "Tablet Side" of the Surface tablet. The browser window is maximized in such a way that it uses the totality of the screen. When you view the same page, same isotope tiles using the browser on the "Windows Side" of the Surface, it presents itself as shown in the attached picture below. This is true no matter what size the window is. Any clue on how to trigger isotope to reconfigure and display correctly in this setup?

![surface-tablet-error](https://cloud.githubusercontent.com/assets/1965668/7476143/579f529e-f311-11e4-9083-d795cb579f47.png)

**Comment by desandro** [comment]
Thanks for reporting this issue. Without an actual device to test on, I'm afraid I won't be able to properly investigate this. I'll keep this issue open in case others can shed some light.

**Comment by keithklingen** [comment]
@desandro thanks for the reply. I was able to get my hands on the device today as well. It's a Surface 2 tablet running IE 11.

Here is what i've been able to determine. When I am using IE 11 in the touch version - it's all cool and works great. When we switch to the desktop viewing of the tablet, and use IE 11, it loads like the image above. However, if we just refresh the page it displays correctly. So the issue is just on the initial load that the problem is persistent.

Here is a codepen - albeit, probably not super helpful: http://codepen.io/anon/pen/zGvMjo

I can't replicate the issue there as it is particular to a browser, but you can at least see our markup.

**Comment by desandro** [comment]
No one else has chimed in on this issue, so I'm closing it. Feel free to follow up if you have further feedback.
