### ISSUE TITLE
Firefox: Filtering animates twice

### ISSUE THREAD

**Issue by cavemon** [metafizzy/isotope#910]
I'm in Firefox 37.0.2.

When I click the filter buttons, it often animates, then animates a couple of items again, and from offscreen.  I thought this was an issue with my site I'm working, but found the issue on the demos as well (http://isotope.metafizzy.co/filtering.html).

To recreate, just click through all of the filter buttons a few times and you should see some of the items animate again.  Tested this in Google Chrome and no issue there...

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm not able to reproduce it in Firefox v38. If you have a reduced test case, I can take a look.
