### ISSUE TITLE
Error in bower install

### ISSUE THREAD

**Issue by JohnBueno** [metafizzy/isotope#911]
I just installed isotope via bower:

bower install isotope --save

Before I even try to implement I start getting the following error.

Uncaught TypeError: Cannot read property 'Item' of undefined
(outlayer.js line 42)

Tried trouble shooting it for a bit to no avail.

**Comment by desandro** [comment]
Sounds like you're missing some files in your build process. What are you using?

**Comment by Braus** [comment]
Any updates?
I am having the same issue.

Cheers

**Comment by spdaly** [comment]
+1

**Comment by spdaly** [comment]
I found the following issue on a dependent JS (https://github.com/metafizzy/outlayer/issues/33).  The problem is with the Bower setup and using wiredep.

I mod'd the bower.json file to use the pkgd JS version of Isotope. Not a permanent fix, but gets me through this issue.

**Comment by ethanclevenger91** [comment]
Try adding the following to your own bower overrides:

```
"isotope": {
      "main": "dist/isotope.pkgd.min.js",
      "dependencies": null
    }
```

**Comment by xelhark** [comment]
It might be related to https://github.com/metafizzy/isotope/issues/879 . I solved it using @EHLOVader 's solution

**Comment by desandro** [comment]
Closing this issue here as a duplicate of #879.

**Comment by NeXTs** [comment]
@ethanclevenger91 Thank you! This solved my problem with "bower-main-files" and dependent outlayer plugin

**Comment by nixoschu** [comment]
I needed to set dependencies to an empty array/object instead of null as @ethanclevenger91 pointed out

```
  "overrides": {
    "isotope": {
      "main": "dist/isotope.pkgd.min.js",
      "dependencies": {}
    }
  }
```

**Comment by eeiswerth** [comment]
+1 @nixoschu
