### ISSUE TITLE
isInitLayout doc example not working

### ISSUE THREAD

**Issue by dagobertrenouf** [metafizzy/isotope#913]
This example from the docs: http://isotope.metafizzy.co/options.html#isinitlayout doesn't work.
Using the same code, it doesn't allow to manually trigger isotope arrange / layout.

Codepen demonstrating the issue here, look at the console after initial load, without resizing the window:
http://codepen.io/dagobertrenouf/pen/xGZOXE

**Comment by desandro** [comment]
Thanks for reporting this. Fixed! :rotating_light:

**Comment by dagobertrenouf** [comment]
@desandro awesome, I actually lost some time over this, can't believe it was that simple ;)
