### ISSUE TITLE
Add watchCSS

### ISSUE THREAD

**Issue by virgo79** [metafizzy/isotope#917]
Hi David,
it would be very useful to have the watchCSS feature as in flickity package.
Especially if using complex layout (as packery) in small devices, it would be very useful.
When screen  became too small often it's better removing the isotope layout and apply a basic responsive css.
What do you think about this?
Thanks in advance.

**Comment by desandro** [comment]
Thanks for this feature request. It's interesting, but I don't feel it's right for Isotope as Isotope can do a lot. For example, if you have filtering UI, does the UI still work if Isotope is disabled? I fear this adds additional complexity.

**Comment by enrichit** [comment]
If I may submit my two-cents.

Really all I need is something which does as @virgo79 says. If I have 5 columns design handed to me by a very picky client then it simply doesn't work on mobile to have all 5 columns shown.

I'm honestly surprised (looking through issues) that this isn't bought up more.

I'll find a solution though, I'm sure someone has done it and I'll report back once I have.

**Comment by desandro** [comment]
@enrichit You can use [element sizing](http://isotope.metafizzy.co/layout.html#responsive-layouts) so Isotope layout is still active, but the number of columns can dynamically change for media queries.

**Comment by desandro** [comment]
Looks like this feature request hasn't gotten enough interest.

You can use media query behavior in JS to initialize Isotope or not.

``` js
// enable Isotope at 768px
if ( matchMedia('(min-width: 768px)').matches ) {
  $('.grid').isotope({
    //...
  });
}
```
