### ISSUE TITLE
Change options on resize

### ISSUE THREAD

**Issue by mikeebee** [metafizzy/isotope#918]
Hi!

I have a masonry layout which I'm using the ```isFitWidth``` option so that I can centre the item container. When I get to a certain screen size (768px wide) I want to change the options so that my items are 50% of the container instead, meaning (from what I can gather) that I need to remove the ```isFitWidth``` option and give a new percentage width. I can do this easy enough on load but I need to change this if the user resizes between these resolutions.

Everything I have tried has ended badly, so I'd love some help!

Here is my reduced test case without any resizing - http://codepen.io/anon/pen/waWePp (I'm using the Vanilla JS version)

Many thanks!

**Comment by jgrizou** [comment]
I think my problem is the same. I want to assign a width in px for my grid-items unless the grid_item width is bigger than the "screen width". In such case I would like it to become 100% of the "screen width".

Another way would be to assign width: 100% in row containing only one element.

Is there a way to do this currently? I tried a few things without success, but I am far from being an expert.

I am using a packery layout.

**Comment by desandro** [comment]
Thank you for submitting this feature request. 1 year later, looks like it didn't get a lot of others interest. Closing 🍍
