### ISSUE TITLE
2 columns with responsive items - expanding first item realigns other items into one column (masonry)

### ISSUE THREAD

**Issue by mpaulasaari** [metafizzy/isotope#919]
I noticed a weird issue with our design, which consists of two columns of items, each 50% width and when expanded they get 100% width. We're using Isotope in Masonry layout mode. Expanding any of the items works great and the other items realign as expected EXCEPT if you expand the first item. In that case the other items align into one column instead of two. Here's an example: http://codepen.io/anon/pen/dopNRy

**Comment by desandro** [comment]
See http://isotope.metafizzy.co/faq.html#the-first-item-breaks-the-grid
