### ISSUE TITLE
get new appended height Isotope

### ISSUE THREAD

**Issue by TaraRotten** [metafizzy/isotope#920]
Im running isotope with infinite scroll and imagesloaded, getting new items using isotope appended.

Before the new items are appended into the isotope container I need to get the new isotope container height to run through a height function, checkTopScroll(); this function just sets the parent container at top: xx; depending on the height of the isotope container. I have the function working but it doent run until the isotope container height has already been on the isotope container 

```javascript   
 $('.content-inner').infinitescroll({
    navSelector  : ".prev-next-posts",            
    nextSelector : ".prev-posts-link a",    
    itemSelector : ".content-inner .project",  
    loading: {
            msgText: "",
            finishedMsg: 'No More.',
            img: '/481.gif'
    }       
},  function( newElements ) {
        var $newElems = $( newElements ).css({ opacity: 0 });
        $newElems.imagesLoaded(function(){
          $newElems.animate({ opacity: 1 });
          $('.content-inner').isotope( 'appended', $newElems );  
          checkTopScroll();  
        });
      }
    );
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by TaraRotten** [comment]
Hi sorry here is a test case: http://codepen.io/anon/pen/GJNjwx 
So I have two isotope columns running, the right column needs to prepend once the left column has retrieved the left columns new isotope height, is this possible?

**Comment by desandro** [comment]
Instead of prepending, what about using [`isOriginTop: false`](http://isotope.metafizzy.co/options.html#isorigintop) on the "bottom-up" column. This way you can use the same infinite scroll callback to append to both Isotope instances?

**Comment by TaraRotten** [comment]
using one infinite scroll callback was a solution I thought of, however there are two streams so I have to declare that I want the new elements to load into  the corresponding container, left and right??

**Comment by desandro** [comment]
Sorry, but I won't be able to provide a solution here.
