### ISSUE TITLE
Erratic behavior in Meteor

### ISSUE THREAD

**Issue by tacoe** [metafizzy/isotope#924]
Coming in via atmosphere isotope:isotope package. 

A straight-forward 

```
Template.home.rendered = ->
  $('#isocontainer').isotope
    layoutMode: 'masonry'
    itemSelector: '.card'
    masonry:
      columnWidth: '.grid-sizer'
```

Works locally (almost always, anyway) but doesn't work on real life internet connections. 

I thought this has to do with images loading slowly, but even after loading all images, manually running `$('#isocontainer').isotope();` in the console doesn't work; it returns an array that mentions a 0px height and no masonry is applied.

I have the feeling this is a disconnect between how Meteor works and how Isotope works — Is this a bug or am I doing something wrong?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

See also #829

**Comment by tacoe** [comment]
Thanks. Just a note to say I'm looking at getting a reduced test case — it being in meteor and only reproducable on production hosted environments doesn't help.

**Comment by tacoe** [comment]
Didn't manage to get that reduced test case. For posterity, note that only adding the items to the isotope container after its initialisation made this work (that is, provided you trigger isotope only after imagesLoaded and even then, after a bit of timeout)
