### ISSUE TITLE
Rendering issues with headless browsers (Phantomjs, Casperjs)

### ISSUE THREAD

**Issue by jhendley25** [metafizzy/isotope#925]
I've been attempting to write some Casperjs tests, but it looks like isotope is not rendering in the headless environment. I couldn't seem to find any references to issues like this, but I thought I'd ask here anyway.

The attached screenshot shows the failing test. One of the tiles controlled by isotope has a click event bound to it that opens a modal, but the tile is not being rendered.

![screen shot 2015-06-01 at 11 47 12 am](https://cloud.githubusercontent.com/assets/5239363/7917035/6e0d8d44-0855-11e5-850e-d928cb2463e6.png)

The "subject" line in the screenshot shows the rendered html. The div.content-lower should be blown away and replaced by the isotope-controlled thumbnails but that's not happening. I know this is probably hard to answer without a test case, so I'll see if I can work one up. In the meantime, are there any known issues with isotope in a headless environment?

Thanks

**Comment by desandro** [comment]
Sorry, haven't heard any other experiences working with Isotope in a headless environment. Any insights here are appreciated.

**Comment by jhendley25** [comment]
It's not an issue with Isotope. After looking deeper into it, phantomjs does not support hash fragment navigation for some odd reason, so Isotope was never being initialized. Sorry for the non-issue. 

Isotope is awesome! Thanks for making such a badass piece of software.

**Comment by desandro** [comment]
Thanks for following up
