### ISSUE TITLE
iOS 7.1 breaking issue.

### ISSUE THREAD

**Issue by hoggworks** [metafizzy/isotope#926]
I noticed that there's an error that occurs in this function, only in iOS 7.1:

function getStyleSize( value ) {
  var num = parseFloat( value );
  // not a percent like '100%', and a number    
 var isValid = (value.indexOf('%') === -1 && !isNaN( num );
  return isValid && num;
}

In the project I'm using isotope in, I get an error that value is undefined, and the indexOf call fails. I added an error check make sure value exists, and it works.

**Comment by desandro** [comment]
Thanks for reporting this issue. iOS 7.1 is an older version. I'm surprised this issue wasn't reported earlier when it had bigger usage. I'm closing this one as an edge case.
