### ISSUE TITLE
Isotope filtering and Lightgallery update best practice

### ISSUE THREAD

**Issue by HybridSolutions** [metafizzy/isotope#927]
Hi,

Can you please guide me on this. I'm using checkboxes to filter Isotope Items. In the checkboxes I have the change event applied. Filtering Isotope is easy but I also need to update a gallery. 

```javascript
$checkboxes.change(function()
{
... 
// Refresh Lightgallery after Isotope grid filtering is complete
$currentGridItem.isotope( 'on', 'arrangeComplete', function( filteredItems ) {
     console.log( 'Isotope arrange completed with ' + filteredItems.length + ' items' );                    
     gallery.destroy();                    
     gallery = $currentGridItem.lightGallery({
          selector: $currentGridItem.find('.hotlink:visible'),
          exThumbImage: 'data-exthumbimage',
          lang: {
                  allPhotos: 'Todas as fotos'
                   },
          videoAutoplay: false
    });
});

// Apply filter to isotope grid
$currentGridItem.isotope({ filter: filterValue });
});
```

Do you see any issue using the arranjeComplete event inside the change event of each checkbox?
I really need to make sure the gallery is updated after Isotope filtering is complete and can't see another way of doing this besides this one.

Thank you!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by HybridSolutions** [comment]
I'm not having any troubles, it's more a doubt about the right approach with Isotope. It's working fine but I'm not sure about the arrangeComplete event being called the way I presented here whenever a checkbox is changed. Is the test case really necessary here?

**Comment by desandro** [comment]
Your solution looks pretty good. The lightGallery plugin does not offer an API to update its items, so the destroy/re-activate technique will have to do.
