### ISSUE TITLE
Combination Filter Reset

### ISSUE THREAD

**Issue by nightcoregirl** [metafizzy/isotope#928]
I am having difficulty understanding how to create a reset all button. I have seen plugins for it but that seems excessive. I'm using the example straight from the docs. How do I target all button-groups and reset the filter values to all?

http://codepen.io/desandro/pen/JEojz/

$(document).ready( function() {
  // init Isotope
  var $grid = $('.grid').isotope({
    itemSelector: '.color-shape'
  });

  // store filter for each group
  var filters = {};

  $('.filters').on( 'click', '.button', function() {
    var $this = $(this);
    // get group key
    var $buttonGroup = $this.parents('.button-group');
    var filterGroup = $buttonGroup.attr('data-filter-group');
    // set filter for group
    filters[ filterGroup ] = $this.attr('data-filter');
    // combine filters
    var filterValue = concatValues( filters );
    // set filter for Isotope
    $grid.isotope({ filter: filterValue });
  });

  // change is-checked class on buttons
  $('.button-group').each( function( i, buttonGroup ) {
    var $buttonGroup = $( buttonGroup );
    $buttonGroup.on( 'click', 'button', function() {
      $buttonGroup.find('.is-checked').removeClass('is-checked');
      $( this ).addClass('is-checked');
    });
  });
  
});

// flatten object by concatting values
function concatValues( obj ) {
  var value = '';
  for ( var prop in obj ) {
    value += obj[ prop ];
  }
  return value;
}

**Comment by desandro** [comment]
To reset combination filters with this demo, set `filters` to an empty object `filters = {}`. See full example: http://codepen.io/desandro/pen/pJPwpy

``` js
  var $anyButtons = $('.filters').find('button[data-filter=""]');
  var $buttons = $('.filters button');

  $('.button--reset').on( 'click', function() {
    // reset filters
    filters = {};
    $grid.isotope({ filter: '*' });
    // reset buttons
    $buttons.removeClass('is-checked');
    $anyButtons.addClass('is-checked');
  });
```

**Comment by pac0571** [comment]
What about resetting the location hash while doing this?

**Comment by eshbanbahadur** [comment]
thanks for this. its very helpful.
but codepen code is not working. If you fix it, then it will be more beneficial.

**Comment by desandro** [comment]
@eshbanbahadur Demo fixed https://codepen.io/desandro/pen/pJPwpy

**Comment by devconta** [comment]
@desandro I am using Isotope **without jQuery**: https://codepen.io/desandro/pen/pOjMdx

Is there a way to insert a filter reset button to remove all combination filters which works with plain **Vanilla JS**?
