### ISSUE TITLE
Using CSS transitions in isotope v2

### ISSUE THREAD

**Issue by danielcomriebell** [metafizzy/isotope#929]
Hi,

Is it possibile to use CSS3 transitions instead of the default jQuery animation in Isotope v2? 

Best,
Dan

**Comment by desandro** [comment]
Hi Dan! Isotope v2 only uses CSS transitions for its animation. jQuery animation has been removed in v2.

**Comment by danielcomriebell** [comment]
Thank you for the quick response. 
Where in the .css file can I change the transition effect? The only property I can change is the transition duration. 
Whenever I try something like the code below, the transition completely stops.

* {
  -webkit-transition: opacity 2s ease-in;
     -moz-transition: opacity 2s ease-in;
      -ms-transition: opacity 2s ease-in;
       -o-transition: opacity 2s ease-in;
          transition: opacity 2s ease-in;
}

**Comment by desandro** [comment]
Isotope v2 does not require that `.css` file. You can review changes at http://isotope.metafizzy.co/appendix.html#upgrading-from-v1

As for editing hide/reveal transitions, see [hiddenStyle & visibleStyle](http://isotope.metafizzy.co/options.html#hiddenstyle-visiblestyle) options
