### ISSUE TITLE
Content stack over each other when flip is used with isotope

### ISSUE THREAD

**Issue by debprotim** [metafizzy/isotope#930]
Hi,

I have a requirement of showing content in a row in slidable format. So when items are clicked one after the another, they open side by side. But if we close item which was first opened, it should go of and the others should slide and take its place. (A normal functionality of isotope)

But i want to flip these items as well. For that i am using jquery flip class.
http://nnattawat.github.io/flip/

But the moment i mix isotope and this flip functionality, all the items start stacking one over the another rather than coming side by side.

Can you please help me with this.

**Comment by desandro** [comment]
If you want to use a transform on Isotope item, I recommend using a separate element for the second transform

``` html
<div class="grid-item"> <!-- isotope transform -->
  <div class="grid-item-content"> <!-- second transform -->
  </div>
</div>
```
