### ISSUE TITLE
setPosition method should be float or int?

### ISSUE THREAD

**Issue by duckzland** [metafizzy/isotope#932]
I couldn't find the source for the setPosition method in the isotope method. but seems that by forcing to parseInt in some condition it can eat up the border set if the x or y position has fraction on it.

by changing the setPosition to use parseFloat actually fixes the problem. I've only test this on fitRows method, is there any special reason to disallow fraction for x or y position?

Item.prototype.setPosition = function( x, y ) {
  this.position.x = parseFloat( x, 10 );
  this.position.y = parseFloat( y, 10 );
};

thanks in advance.

**Comment by desandro** [comment]
Integer pixel values are used to ensure proper text rendering. Items set with fractional pixel values can have blurry text.

**Comment by duckzland** [comment]
Thanks for the info, do you have any idea on which browser this blurring can occurs? so I can test them.

Thanks

**Comment by desandro** [comment]
I remember Chrome, Firefox & Safari all had issues with blurry text and fractional pixel values, when using `transform: translate`.
