### ISSUE TITLE
Animation running twice when webkit effects added to item

### ISSUE THREAD

**Issue by yuvalshu** [metafizzy/isotope#933]
Hi,
great plugin - exactly what I was looking for in my project!

I wanted to add some hover animations to the grid items, but it appears for some reason this causes animation to run twice every time I sort the items. Reduced case is here: http://codepen.io/anon/pen/OVjLox

on a different note, would appreciate reference to examples where clicking an item pops up a centralized item and disables/dims the original layout if you have one handy. Thanks again.

**Comment by lolo34140** [comment]
Hello,

You must remove transitions on isotope items. Remove these two lines and it will work fine:

  -webkit-transition-duration: 0.3s;
  transition-duration: 0.3s;

lolo

**Comment by desandro** [comment]
@lolo34140 Has the right solution.
