### ISSUE TITLE
Isotope in IE 11MVC View

### ISSUE THREAD

**Issue by RobFra** [metafizzy/isotope#934]
Hello, 
I' trying to use the new isotope version on MVC project.
I've just made a simple View with the sample of Isotope - Filtering page, exactly the one here:
http://codepen.io/desandro/pen/Ehgij
It works on Chrome but it doesn't work in my view with IE 11. It gives Error: 'Element' is undefined in isotope.pkgd.min.js :+1: function(t){function e(t,e){return t[s](e)}function i(t){if(!t.parentNode){var e=document.createDocumentFragment();e.appendChild(t)}}function o(t,e){i(t);for(var o=t.parentNode.querySelectorAll(e),n=0,r=o.length;r>n;n++)if(o[n]===t)return!0;return!1}function n(t,o){return i(t),e(t,o)}var r,s=function(){if(t.matches)return"matches";if(t.matchesSelector)return"matchesSelector";for(var e=["webkit","moz","ms","o"],i=0,o=e.length;o>i;i++){var n=e[i],r=n+"MatchesSelector";if(t[r])return r}}();if(s){var a=document.createElement("div"),u=e(a,"div");r=u?e:n}else r=o;"function"==typeof define&&define.amd?define("matches-selector/matches-selector",[],function(){return r}):"object"==typeof exports?module.exports=r:window.matchesSelector=r}(Element.prototype),

What am I doing wrong??

Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

The CodePen you mention is working just fine for me in IE11.

**Comment by RobFra** [comment]
Hi David and thanks for reply.
Really I can't understand. I'll sumbit the issue in the link you've mentioned.
Thankyou very much.

**Comment by RobFra** [comment]
Hello, sample is here.

http://codepen.io/anon/pen/mJBJKP

...it seems to work. Is exactly the same reported in isotope and the same I've copied in my View.
Really I don't know where is the problem. In codepen it works also with IE.

In my project, the same View browsed with Chrome it works perfectly, browsed with IE, in gives:
Line 11, Error: 'Element' is undefined
and then
Object doesn't support property or method 'isotope'
is like page can't access to Jquery and Isotope javascript.
But scripts are all enabled  in IE, security is medium-low..... 
Sample in codepen works
Don't know.....

**Comment by desandro** [comment]
Sorry, without a reproducible test case I won't be able to debug this issue.

**Comment by RobFra** [comment]
Hello,
I've found the problem with IE11.
It was because in the server I was using for develop, localhost was in the compatibility web sites list. 
Removing it from compatibility it starts to work.

Thanks
