### ISSUE TITLE
jQuery isotope auto scrolls to top

### ISSUE THREAD

**Issue by lekhraj-knockmedia** [metafizzy/isotope#935]
function isotopInit() {
jQuery('.products-grid').each(function () {
    if (!jQuery(this).parents('#header').length) {
        if (!jQuery('body').hasClass('rtl')) {
            jQuery(this).isotope({
                itemSelector: '.item',
                resizable: true,
                layoutMode: 'fitRows',
                transformsEnabled: false
            });
        } else {
            jQuery(this).isotope({
                itemSelector: '.item',
                resizable: true,
                layoutMode: 'fitRows',
                transformsEnabled: false
            });
        }
    }
});
}

That's function is called on page load. My issue is it takes page to the top.

For eg. I am on Product list page of en E-commerce site at the bottom of the page and i click on the product and go to a product page and when i click on Browser Back button page then product list is at the bottom of the page but after few seconds it scrolls back to top.

When I comment following code 

 jQuery(this).isotope({
            itemSelector: '.item',
            resizable: true,
            layoutMode: 'fitRows',
            transformsEnabled: false
        });

Page doesn't scroll to top.

Please help, Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by lekhraj-knockmedia** [comment]
Hi,
Thanks for reverting so quickly.
1> Please go to this url

http://dev2.alishauat.com.vhost.zerolag.com/default/14k-diamond-jewelry-1.html

2> goto last product of the page "LE276Y" click on it

3> After loading product page click on browser "Back" button.

Issue - now product list page will stay on same product for couple of seconds but then it will scroll up

when I comment this code is JS file


jQuery(this).isotope({
itemSelector: '.item',
resizable: true,
layoutMode: 'fitRows',
transformsEnabled: false
});

it works fine.

**Comment by sebastianwr** [comment]
Has this bug been fixed? Unfortunately, the page still scrolls to top after I apply the `$grid.isotope({ filter: '.something'})` function. This happens in the onChange event of a `<select>` field, so there is no link that could be causing this.

**Comment by desandro** [comment]
@sebastianwr Looks like you have a separate issue because there's no space below your Isotope container. You can resolve this either by adding more space below, or disabling Isotope setting container height with `resizeContainer: false` option, and setting height with your CSS.

**Comment by sebastianwr** [comment]
@desandro Thanks for your help! By adding space you mean margin or padding or another element like an empty `<div>`?

**Comment by desandro** [comment]
@sebastianwr Yes.

**Comment by Isodie** [comment]
@lekhraj-knockmedia 
@desandro 
I am having same issue...How did you solved it.

Needs help Thanks
