### ISSUE TITLE
Isotope and acordeons

### ISSUE THREAD

**Issue by DonWasyl** [metafizzy/isotope#936]
Hi, I've a question.
I have grid where elements are accordions:

for example
```html
<div class="grid">
    <div class="element-item">
         <button class="accordion-toggle">Click to show/hide</button>
         <div class="accordion-content">Content</div>
    </div>
</div>
```

After click button content slides down/up, but it's possible by then isotope elements recalculate positions and sort again items?

**Comment by desandro** [comment]
Use [`layout` method](http://isotope.metafizzy.co/methods.html#layout) after item size changes.
