### ISSUE TITLE
I'm trying to combine a few different filtering methods

### ISSUE THREAD

**Issue by mdcrtv** [metafizzy/isotope#937]
I'm trying to combine a few filtering methods into one isotope script.

Perhaps this is more of a feature request than an issue, but it never hurts to ask the experts.

I'd like to merge these three methods:
 - Hash history: http://codepen.io/desandro/pen/vErxXj
 - Checkbox filtering: http://codepen.io/desandro/pen/btFfG
 - Filter by input: http://codepen.io/desandro/pen/wfaGu

I made an attempt here: http://codepen.io/mdcrtv/pen/jPLNLz

        function getHashFilter() {
        // get filter=filterName
        var matches = location.hash.match(/filter=([^&]+)/i);
        var hashFilter = matches && matches[1];
        return hashFilter && decodeURIComponent(hashFilter);

        $container.isotope({
            itemSelector: '.gallery-thumb',
        // use filterFns
        filter: filterFns[ hashFilter ] || hashFilter
        });
        }

        // debounce so filtering doesn't happen every millisecond
        function debounce(fn, threshold) {
            var timeout;
            return function debounced() {
                if (timeout) {
                    clearTimeout(timeout);
                }

                function delayed() {
                    fn();
                    timeout = null;
                }
                timeout = setTimeout(delayed, threshold || 100);
            }
        }

        var filters = {};

        function getComboFilter(filters) {
            var i = 0;
            var comboFilters = [];
            var message = [];
            for (var prop in filters) {
                message.push(filters[prop].join(' '));
                var filterGroup = filters[prop];
        // skip to next filter group if it doesn't have any values
        if (!filterGroup.length) {
            continue;
        }
        if (i === 0) {
        // copy to new array
        comboFilters = filterGroup.slice(0);
        } else {
            var filterSelectors = [];
        // copy to fresh array
        var groupCombo = comboFilters.slice(0); // [ A, B ]
        // merge filter Groups
        for (var k = 0, len3 = filterGroup.length; k < len3; k++) {
            for (var j = 0, len2 = groupCombo.length; j < len2; j++) {
        filterSelectors.push(groupCombo[j] + filterGroup[k]); // [ 1, 2 ]
        }
        }
        // apply filter selectors to combo filters for next group
        comboFilters = filterSelectors;
        }
        i++;
        }
        var comboFilter = comboFilters.join(', ');
        return comboFilter;
        }

        function manageCheckbox($checkbox) {
            var checkbox = $checkbox[0];
            var group = $checkbox.parents('.options').attr('data-group');
        // create array for filter group, if not there yet
        var filterGroup = filters[group];
        if (!filterGroup) {
            filterGroup = filters[group] = [];
        }
        var isAll = $checkbox.hasClass('all');
        // reset filter group if the all box was checked
        if (isAll) {
            delete filters[group];
            if (!checkbox.checked) {
                checkbox.checked = 'checked';
            }
        }
        // index of
        var index = $.inArray(checkbox.value, filterGroup);
        if (checkbox.checked) {
            var selector = isAll ? 'input' : 'input.all';
            $checkbox.siblings(selector).removeAttr('checked');
            if (!isAll && index === -1) {
        // add filter to group
        filters[group].push(checkbox.value);
        }
        } else if (!isAll) {
        // remove filter from group
        filters[group].splice(index, 1);
        // if unchecked the last box, check the all
        if (!$checkbox.siblings('[checked]').length) {
            $checkbox.siblings('input.all').attr('checked', 'checked');
        }
        }
        }

        // Set container as variable
        $container = $('#gallery-container');
        // quick search regex
        var qsRegex;
        // init Isotope
        $container.isotope({
            itemSelector: '.gallery-thumb'
        });
        // do stuff when checkbox change
        $('.options').on('change', function(jQEvent) {
            var $checkbox = $(jQEvent.target);
            manageCheckbox($checkbox);
            var comboFilter = getComboFilter(filters);
            $container.isotope({
                filter: comboFilter
            });
        });

        // use value of search field to filter
        var $quicksearch = $('.quicksearch').keyup(debounce(function() {
            qsRegex = new RegExp($quicksearch.val(), 'gi');
            if ($(".quicksearch").val()) {
                var searchResults = function() {
                    return qsRegex ? $(this).text().match(qsRegex) : true;
                }
                $container.isotope({
                    filter: searchResults
                });
            } else {
                var comboFilter = getComboFilter(filters);
                $container.isotope({
                    filter: comboFilter
                });
            }
        }, 200));

Both the quick search and checkboxes work, but the search seems to break after the first time I type a matching term.

I suspect it's due to the if else statement that switches between the search box and checkbox filter argument, but I'm not sure.

        if ($(".quicksearch").val()) {
                var searchResults = function() {
                    return qsRegex ? $(this).text().match(qsRegex) : true;
                }
                $container.isotope({
                    filter: searchResults
                });
            } else {
                var comboFilter = getComboFilter(filters);
                $container.isotope({
                    filter: comboFilter
                });
            }

If I type "test" it works fine to switch between the two filter tools, but that also happens to be the only item not set as a checkbox.

The hash filtering doesn't appear to work either, but I'm more concerned about combining the other two filter tools...

**Comment by desandro** [comment]
As a best practice, I recommend against combining so many different types of logic. It's hard for developers to maintain, and its even harder for users to understand how it works. Technically, you can achieve this, but it requires so much code that I don't believe it's worth the effort. Sorry, but I won't be able to provide a solution here.
