### ISSUE TITLE
Custom remove method?

### ISSUE THREAD

**Issue by rohan-deshpande** [metafizzy/isotope#938]
So I need a remove method that doesn't actually remove the element from the DOM, which I've achieved by simply commenting out the calls to `this.removeElem()` inside of the `Item.prototype.remove` method. But I'd rather create my own custom method, and ideally have this located outside of the `isotope.pkdg.js` file. Is there a nice clean way to do this that you could recommend? I tried simply copy pasting the code like so

    Item.prototype.archive = function() {
      this.hide();
    };

But it doesn't seem to work, I get an error `no such method 'archive' for isotope instance`.

**Comment by desandro** [comment]
You can extend Isotope's Item class like so:

``` js
Isotope.Item.prototype.methodName = function() {
 // logic...
}
```

**Comment by rohan-deshpande** [comment]
Hey thanks for the reply...hmm I'm a bit confused though, how would I call this?

I think I'm confused as to what is classified as an Isotope Item and what is an element (and are they different?), like to call the remove method, I get the isotope instance and then simply do

`$isotopeInstance.isotope('remove', $element);`

And this works. However the way I have defined `$element` is just via jQuery using a selector. 

I tried, just as a test, to define a new method like so

    Isotope.Item.prototype.customMethod = function() {
        console.log('this is my custom method');
    };

But when I try to call it in the same way as the remove method, I get the following error 

`no such method 'customMethod' for isotope instance`

Which makes sense I guess because I am setting it on the Item prototype right?

**Comment by desandro** [comment]
To call a method with jQuery:

``` js
```

**Comment by rohan-deshpande** [comment]
Hmm this is what I am trying, but I get the error `no such method 'customMethod' for isotope instance`

I'll give it another shot, thanks!

**Comment by desandro** [comment]
Sorry, I forgot to add code for adding methods to Isotope in addition to Isotope Item. i've updated the code example above.

**Comment by rohan-deshpande** [comment]
AH! Yes haha this would definitely make a difference. Thanks a lot!
