### ISSUE TITLE
Using % in layout don't work

### ISSUE THREAD

**Issue by eft0** [metafizzy/isotope#941]
And when I delete 'columnWidth', onClick first item, layout is wrong.

Any ideas ?
http://codepen.io/anon/pen/aOVKoV

**Comment by desandro** [comment]
Looks like you're missing `<div class="grid-item-size"></div>` from HTML. See http://codepen.io/desandro/pen/MwrKpg

**Comment by eft0** [comment]
Thanks david! Keep the awesome work!
