### ISSUE TITLE
Breaking layout in Firefox

### ISSUE THREAD

**Issue by thehung2224** [metafizzy/isotope#942]
Hi,

My code work very fine in Chrome, when check with Firefox the layout looks ugly. Please correct me which I'm wrong, thank you so much.

https://jsfiddle.net/dqfm3gj7/2/

**Comment by desandro** [comment]
Thanks for reporting this issue. Even without Isotope, there is a layout issue due to this CSS

``` css
figure { float: left; }
```

Removing that seems to fix things. Then, view the JS fiddle with `http` so there is no security error. See http://jsfiddle.net/dqfm3gj7/3/

**Comment by thehung2224** [comment]
I also figured out and used clearfix method but it doesn't work. Thank you so much. It's totally solved my issue :+1:
