### ISSUE TITLE
Items moving on appended methods in Safari

### ISSUE THREAD

**Issue by lolo34140** [metafizzy/isotope#945]
Hello,

I have just realize that appended method doesn't take into account animations setted in isotope options on all Mac devices & Safari browser. On your example (http://isotope.metafizzy.co/methods.html#appended), on IOS/Mac and Safari, all appended items always slide from left/top corner. This behavior doesn't happen on all other kinds of browsers and devices. 
So, if I set for example an animation (flipping in 3D with http://isotope.metafizzy.co/options.html#hiddenstyle-visiblestyle) it doesn't work correctly with appended method on Mac. Is it something normal?
All other methods like "insert" are working fine.

I success to recreate the "appended" method with add item to obtain the right result but performance is worst:

     var data = el.data('isotope');
     el.isotope('addItems',$item);
     el.isotope({transitionDuration: 0}); // remove transition while positionning (from top/left)
     el.isotope({transitionDuration: '0.7s'}); // add transition to take into account Hidden/Visible style options
     el.isotope( 'reveal', data.item );

Appended method doesn't deactivate animations when positionning items...

Lolo

**Comment by desandro** [comment]
Thank you for reporting this bug. I was able to identify and fix the bug. The fix will be in the next release of Outlayer.

[If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me yo@metafizzy so I can send some your way.

**Comment by lolo34140** [comment]
Thank a lot for the update. It's working like a charm now!

**Comment by DonWasyl** [comment]
Hi, I was this same issue and last update fix problem, but partialy.
When i try open or close my accordeons other boxes move to half distance.

http://screencast.com/t/ONQwlrFR

My accordeons has height in css and I set them height: 0 for close state and animate it by "transition".

**Comment by desandro** [comment]
@DonWasyl If you have a [**reduced test case**](http://isotope.metafizzy.co/appendix.html#reduced-test-cases) open a new issue with it.
