### ISSUE TITLE
Uncaught TypeError: Cannot set property 'position' of undefined

### ISSUE THREAD

**Issue by huzefaindxb** [metafizzy/isotope#946]
Hi,

I am trying to execute below JS but getting Uncaught TypeError.

// init Isotope
    var $categoryFilter = $('.isotope');
    if ($categoryFilter.length > 0) {
        require(['isotope.pkgd.min'],
            function (Isotope) {
                var iso = new Isotope(
                    $categoryFilter, {
                        itemSelector: '.item',
                        layoutMode: 'fitRows',
                        sortAscending: true
                    });
            });
    }

Thanks in advance for any help.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by huzefaindxb** [comment]
Thanks for replying. I got rid of Uncaught TypeError: Cannot set property 'position' of undefined, but still isotope is not initialised. Check this page for more details. http://94.200.26.140/misc/isotope/en/phase2_mobile_devices.html

**Comment by desandro** [comment]
Looks like your init code could be fixed

``` js
require( ['isotope.pkgd.min'], function( Isotope ) {
  var iso = new Isotope( $container[0], {
    itemSelector: '.item'
  });
});
```

1. Remove requiring `'jquery'`
2. To initialize Isotope with vanilla JS, you need to pass in an Element. Use `$container[0]`

**Comment by huzefaindxb** [comment]
Thanks @desandro. Isotope is initialising now but still filters not working as required. Filter button works only once and after that nothing happens when I click on any other filters. http://94.200.26.140/misc/isotope/en/phase2_mobile_devices.html

**Comment by desandro** [comment]
Sorry, I won't be able to debug your site for you. I recommend trying to put together a [reduced test case](http://isotope.metafizzy.co/appendix.html#reduced-test-cases) to see where the problem is occuring.
