### ISSUE TITLE
Wrong animation positions on percentPosition: true (packery layout)

### ISSUE THREAD

**Issue by DonWasyl** [metafizzy/isotope#948]
Hi.
When i try open or close my accordeons other boxes move to half distance and them not animate properly, but when I set percentPosition: false, everything is ok.

http://codepen.io/anon/pen/gpevrz
layout: packery,
percentPosition: true

(on my page I haven't timeouts, on codepen something is wrong, but it's not a problem)

**Comment by desandro** [comment]
Thanks for reporting this issue. This is a bug introduced in Packery v1.4.2, caused by a regression Outlayer v1.4.1. I'll be investigating.

**Comment by desandro** [comment]
Found a fix for the bug. This will go out in the next version of Isotope.

Thanks so much for reporting this :)  [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me yo@metafizzy so I can send some your way.

**Comment by desandro** [comment]
Fixed in Isotope v2.2.2. Give it a shot :whale:
