### ISSUE TITLE
Isotope filtering with search field MVC partial view

### ISSUE THREAD

**Issue by RobFra** [metafizzy/isotope#950]
Hello,
I'm using this sample http://codepen.io/desandro/pen/wfaGu to make search on tiles in my view but my real application is quite different.

I have the following div:

![image](https://cloud.githubusercontent.com/assets/9280341/8593639/ceaa9a82-2639-11e5-8ce4-483f2e959a80.png)

In fact, I have a View and inside the view there is a Partial View. The partial contains "tiles" like elements in the example.

Loading the Partial View in the following way, it works perfectly:

    <div id="JobsContainer" class="grid">
           @Html.Partial("~/Views/Jobs/_JobsContainer.cshtml", Model)
    </div>

but loading the Partial View in the following way in the Document.ready it doesn't work:

 $('#JobsContainer').load('/Jobs/_JobsContainer');

I need to load the partial view in this client.side way because there is a JS setInterval that refreshes the Partial View.

Inspecting page, it has exactly the same structure loading with @Html.Partial or $('#JobsContainer').load......

Debugging the following JS:
![image](https://cloud.githubusercontent.com/assets/9280341/8593840/8eacce62-263b-11e5-8fe8-7f43209d67a8.png)

it has in both cases the right value to serach in qsRegex and $grid object in bot cases has the right content!

Please.....help!
thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by RobFra** [comment]
Hello,

thank you for your kind and quick response.
Well, I’m trying to provide you a sample, but…
I’ve created:
http://codepen.io/anon/pen/PqeGVJ

as you can see, in the JS I’ve put:
$('#JobsContainer').load('http://codepen.io/anon/pen/LVmRqG');

Obviously it doesn’t work but is just to show you what the page has to do. It tries to simulate the Partial View. Please see also the http://codepen.io/anon/pen/LVmRqG that simulates the partial view.

And please refer to http://api.jquery.com/load/

“Due to browser security restrictions, most "Ajax" requests are subject to the same origin policy; the request can not successfully retrieve data from a different domain, subdomain, port, or protocol.”

I think that with these elements you can simulate it just making a copy-paste of the two pages in your own environment.
As I’ve said, I have to put the “elements” in a separate page because that section has to be autorefreshed.

Thank you very much for your help.

**Comment by desandro** [comment]
I'm not sure if this is a problem with Isotope. If you are able to load content into the grid element, then you should be able to initialize Isotope.

Sorry, but I don't think I'll be able to debug this problem.

**Comment by RobFra** [comment]
Ok. I'll use other javascript library.



-------- Messaggio originale --------
Da: David DeSandro <notifications@github.com>
Data:09/07/2015 20:31 (GMT+01:00)
A: metafizzy/isotope <isotope@noreply.github.com>
Cc: Roberta Franchi <Roberta.Franchi@bbinternational.com>
Oggetto: Re: [isotope] Isotope filtering with search field MVC partial view (#950)


I'm not sure if this is a problem with Isotope. If you are able to load content into the grid element, then you should be able to initialize Isotope.

Sorry, but I don't think I'll be able to debug this problem.

-
Reply to this email directly or view it on GitHub<https://github.com/metafizzy/isotope/issues/950#issuecomment-120096933>.

L'AZIENDA RIMANE CHIUSA PER FERIE DAL 10 AGOSTO AL 22 AGOSTO COMPRESI
