### ISSUE TITLE
Filtering and Sorting

### ISSUE THREAD

**Issue by aishwarya85** [metafizzy/isotope#952]
I am learning basics of js. I have knowledge of html, & css. I am trying to implement filtering and sorting on my music site.

For example, how do I fitler the following data:

Genre
     Classical
     Jazz
     Rock 
     R&B
     All

Year
     Before 1900s
     1901 - 1999
     2000-2015
     All

Artist
     Louis Armstrong
     Elvis Presley
     Rihanna
     Michael Jackson
     All

I found isotope best but i am not able to write code for JavaScript or Jquery for filtering and sorting the above data. please help me to make this filters work.

Thanks in advance.

**Comment by desandro** [comment]
The [Isotope docs](http://isotope.metafizzy.co/) have complete documentation on how to create UI for [filtering](http://isotope.metafizzy.co/filtering.html) and [sorting](http://isotope.metafizzy.co/sorting.html). They also include editable demos for each feature. I recommend you try reading the docs and playing around with the demos to help you get started.
