### ISSUE TITLE
Filter/SortBy not working with html5 data attribute added with jQuery

### ISSUE THREAD

**Issue by lolo34140** [metafizzy/isotope#956]
Hello,

It seems that Isotope do not use method `data` to retrieve informations when filtering or sorting items.
It only works when an element has an hardcoded data attribute or an attribute added thanks to `.attr()` in jquery. It's not working with last html5/jquery data attribute method `.data()`.

It seems to be something important and it could add more flexibility to create complex filtering on the fly with more security (and boolean value).

Here an example: http://fiddle.jshell.net/3a1p59h9/

Lolo

**Comment by desandro** [comment]
Yes, `[data-attr]` string will not work for sorting data set with jQuery's `.data()`, but you can use a function to make it work

``` js
getSortData: {
  dataID: function( elem ) {
    return $( elem ).data('key');
  }
}
```

See http://fiddle.jshell.net/3a1p59h9/1/

**Comment by lolo34140** [comment]
Thanks a lot! It works great like this.

Lolo
