### ISSUE TITLE
Unexpected behavior of Isotope 2 with jQuery UI Sortable (1.1.2)

### ISSUE THREAD

**Issue by LukasPatka** [metafizzy/isotope#957]
Hello,

I encountered strange behavior while trying to use Isotope 2 together with jQuery UI Sortable (1.1.2).
When dragging of an element is finished current item moves to target place from elswhere instead of just fitting into the blank space and other items sort in a strange way as well.

Here is a code on codepen: http://cdpn.io/XbBNQJ

I reused this code by just replacing Isotope 1.5 by Isotope 2: http://codepen.io/ultimatedelman/pen/kIgrC

Any idea how this could be fixed?

Thanks
Lukas

**Comment by desandro** [comment]
Thanks for reporting this issue. I"m sorry to say Isotope does not support UI Sortable. They have similar functionality but are incompatible. Sorry, I won't be able to provide a fix.
