### ISSUE TITLE
Isotope/Masonary loading slowly

### ISSUE THREAD

**Issue by dbaileybonn** [metafizzy/isotope#961]
I have a wordpress site that I am using masonary to render the stories in a pintrest style on the pages. my page loads have dropped down to 13-23 seconds a page load from 5 (yeah it was kind of bad before). http://oneshetwoshe.com it is also holding up Soliloquy rotator from loading and causing all kinds of interesting things to happen on load. Any guidance you could provide would be much appreciated.

**Comment by desandro** [comment]
Your imagesLoaded code waits until all images have been loaded before initializing Isotope. Instead, you can initialize Isotope on document ready, then relayout items have their images have been loaded. 
See docs: http://isotope.metafizzy.co/layout.html#imagesloaded and demo: http://codepen.io/desandro/pen/NqNBxy

Looks like you're using an old version of Isotope v1. I recommend upgrading to [Isotope v2](http://isotope.metafizzy.co).

**Comment by dbaileybonn** [comment]
I'll give that a try and let you know how it goes. thanks for getting back to me so quickly!
