### ISSUE TITLE
Events callback not work, realy not work at all

### ISSUE THREAD

**Issue by skiokko** [metafizzy/isotope#962]
Hi,
Sorry for contact you but i lost too time and tried everything.
Events not work. I think realy dont work , not a my fault. I tried every thing found on google.

This is a resume of what i tried:

var masonry = $('.masonrybox').isotope({
                    itemSelector: '.maso',
                    percentPosition: true,
                    isInitLayout: false,
                    masonry: {
                        columnWidth: '.maso-sizer',
                    },
                    onLayout: function () { alert('onLayout callback') },
                    layoutComplete: function () { alert('onLayout callback') }
                }, function () { alert('anon callback') });
                masonry.on('arrangeComplete', function () {
                    alert("");
                });
                // un-bind event listener
                masonry.one('arrangeComplete', function () {
                    alert("");
                });
                masonry.isotope('on', "arrangeComplete", function () {
                    alert("");
                });
                masonry.isotope('layout');

Nothing trigger, never. I need trigger after first layour complite only, becouse i must read top values of isotope items.

Thank you for support,
Federico

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by bill622** [comment]
Same for me, I need to get a "top" value of an iteam after the first page load and no events are trigger. Although, if I apply filters on my elements, "layoutComplete" and "arrangeComplete" are triggered. 

Test case is quite simple using jQuery :

var myIso = $('.my-items-list').isotope({
        layoutMode: 'fitRows',
        itemSelector : '.my-item',
        percentPosition: true,
    });

    myIso.on( 'layoutComplete', function( event, laidOutItems ){
        console.log( 'layoutComplete' );
    });

    myIso.on( 'arrangeComplete', function( event, filteredItems ) {
        console.log( 'arrangeComplete' );
    });

as explained on top, once the page is loaded and filters are applied, only then the events are trigger.

Thank you!
