### ISSUE TITLE
Center grid-item inside grid area

### ISSUE THREAD

**Issue by phongphan117** [metafizzy/isotope#964]
I want to align the grid items to center inside grid-area same as the picture, but I try to use `margin-left: auto` and `margin-right: auto` but isn't working. Can someone solve the problem?
Here is reduced test: http://jsfiddle.net/phongphan117/5vb4tdzc/
![center grid-area](https://cloud.githubusercontent.com/assets/3041677/9021488/459e3bb2-386e-11e5-85fe-92debf7e09e1.jpg)

**Comment by phongphan117** [comment]
Sorry for can't add label in the title

**Comment by desandro** [comment]
1. You're using Isotope v1. Upgrade to [Isotope v2](http://isotope.metafizzy.co/)
2. Take a look at [`isFitWidth` masonry documentation](http://isotope.metafizzy.co/layout-modes/masonry.html#isfitwidth) and the [`isFitWidth` Isotope demo](http://codepen.io/desandro/pen/BptxJ)
