### ISSUE TITLE
Isotope sorter is not a function

### ISSUE THREAD

**Issue by lolo34140** [metafizzy/isotope#966]
Hello,

Sometimes, I got thi error (1 time on 20 approximately). ANd all the layout is breaked after. I can't sort filter, ...
This error is on line 3047.
What does it mean?

EDIT: I found where comes from the issue exactly. If the grid contains getSortData and one of the sortData are note present in the DOM and if during init the grid is resized, then an error occur after append new element...

Lolo

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by lolo34140** [comment]
I've got some difficulties to reproduce it on a fiddle. My script is a little bit complicated and I can't reproduce all the side effect on a fiddle.
 It seems that if I delay reveal and append and a resize event is triggered during isotope layout then this error happen.

I try without succes with this fiddle: http://fiddle.jshell.net/3a1p59h9/32/

**Comment by lolo34140** [comment]
Ok. I found my issue. It was because of the debounce resize.
Outlayer use a 100ms second treshold and I was using a custom debounce with 150ms treshold. Because of that I was obliged to trigger isotope() in order to relayout and get the right elment sizes (I didn't know about outlayer debounce resize). And in some rare circonstance, I redeclared isotope element while resizing and the sorter functionn trigger an error.

It will be great to add an option to control the debounce resize treshold.

By the way, about my fiddle, do you think than reveal with delay with a request frame animation is the right way reveal or append with a delay (between each element in the grid ? (I try with interval or settimeout but it was not very accurate when processor is busy).

**Comment by desandro** [comment]
Very cool demo! I'd say the reveal with delay is better, as you don't need to use append.

Don't use JS for resizing logic like:

``` js
  $(window).on('resize', function() {
      $('.grid-sizer').width(100);
      $container.isotope();
  });
```

Instead, have this in CSS with a media query and use [element sizing](http://isotope.metafizzy.co/layout.html#responsive-layouts)
