### ISSUE TITLE
Sloppy filtering animation on iPhones

### ISSUE THREAD

**Issue by lspoor** [metafizzy/isotope#968]
I'm using a 3column grid on desktop with filtering and then down to a 2column grid on mobile. When filtering on iPhones isotope doesn't seem to be placing the correct positioning values on it, as you can see from the picture this is immediately after clicking a filter link. It is not animating the position correctly.

![isotopeproblem](https://cloud.githubusercontent.com/assets/1685176/9174612/cf0509ce-3f78-11e5-8ea6-545adb502a8c.jpg)

Demo link here:
http://3host.co.uk/isotope

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by lspoor** [comment]
Is it possible to send the link privately as this is a client side project 

Thanks,

Luke

**Comment by lspoor** [comment]
I'm actually experiencing another problem on desktop as well now, its very jumpy. Here is a live demo

http://m3host.co.uk/isotope

**Comment by lspoor** [comment]
So it appears 

percentPosition: true,

was causing the problem. Have removed and is working fine now.

**Comment by desandro** [comment]
You were running into issue #948. This will be resolved in the next release
