### ISSUE TITLE
Overlap grid-item when minimized window after set horizonal and vertical gutter

### ISSUE THREAD

**Issue by phongphan117** [metafizzy/isotope#969]
I use masonry layout for grid item in the parent box for make centered grid area, But not important problem. When window was maximized, Isotope that working correcly. But it's seem my gutter is for vertical space only. I'll set ```margin-bottom``` to make horizontal gutter.
![capture1](https://cloud.githubusercontent.com/assets/3041677/9243253/6926f990-41b8-11e5-8896-626a3f5d039c.PNG)
But problem is when I minimize the window. It seem grid-item was overlapped.
![capture2](https://cloud.githubusercontent.com/assets/3041677/9243272/c33d1838-41b8-11e5-9e04-4263f12219c1.PNG)
But when I resize window. It's working correctly again. I don't know how to fix my problem, Can someone help me?
Full screen result for maximize/minimize test: https://jsfiddle.net/phongphan117/bvmerhu8/embedded/result/
Source code: http://jsfiddle.net/phongphan117/bvmerhu8/
Ps. Please tell me how to add label for my github issue. Thank in advanced.

**Comment by desandro** [comment]
Looks like the bug is caused by how `.element-item` does not have any width set. Setting `.element-item { width: 300px; }` looks to fix the problem. See https://jsfiddle.net/bvmerhu8/6/
