### ISSUE TITLE
reloadItems cause animation to show and hide items

### ISSUE THREAD

**Issue by hwong668** [metafizzy/isotope#970]
I'm using isotope with an angularJS wrapper [ng-isotope] (https://github.com/diego-vieira/ng-isotope) and whenever the data changes the angularjs wrapper will call reloadItems which causes some items to appear and disappear the animation.  Is it possible to avoid the item to show and disappear when reloading items?
I've modified the demo [codepen] (http://codepen.io/anon/pen/aOxpRj?editors=101) by adding a button to change the name of one of the elements.
[This] (https://www.dropbox.com/s/wwcybqr3sgkaj61/isotope%20reloadItems%20bug.mov?dl=0) is a video I made to show the showing and hiding of the elements.

thank you

**Comment by desandro** [comment]
Thanks for reporting this bug. Try this: add a new method `reloadFilter` that reloads item and updates the filtered items to match. Add this code:

``` js
Isotope.prototype.reloadFilter = function() {
  this.reloadItems();
  // reload filtered items
  var filtered = this._filter( this.items );
  this.filteredItems = filtered.matches;
  // reset isHidden on items
  for ( var i=0, len = filtered.needHide.length; i < len; i++ ) {
    filtered.needHide[i].isHidden = true;
  }
};
```

``` js
// use reloadFilter instead of reloadItems
// jQuery
$grid.isotope('reloadFilter')
// vanilla JS
iso.reloadFilter()
```

See demo http://codepen.io/desandro/pen/vOqebZ

**Comment by hwong668** [comment]
This works flawlessly.  Thank you!
