### ISSUE TITLE
Isotope events conflict

### ISSUE THREAD

**Issue by skiokko** [metafizzy/isotope#972]
First of all: great plugin! work very good.
I have found only a bug (i think).

If in the page are present 2+ isotope scripts, so duplicated scripts. Is generated a conflict.
I receive this errors:

When i try to use these codes: 

 masonry.isotope('remove', masonry.isotope('getItemElements'));
  masonry.isotope('insert', elementsArr);
  masonry.isotope({ sortBy: jQuery("#" + eid + " .evo_srt_sel").attr("sort-value") });

I get these errors:

no such method 'getItemElements' for isotope instancex @ VM90 x-body.min.js?ver=4.0.6:1
VM90 x-body.min.js?ver=4.0.6:1 Uncaught TypeError: Cannot read property 'number' of undefined

These error show that is called same method "getItemElements" but by wrong script.
Difficoult to decsribe, but seem if 2 script isotope not use correct script.

Im a envato developer and i bought  your license for a plugin, initialy I found this bug on a theme (X theme) and i think was a theme error so i written do developers, but in these weeks im receive from clients same problem with all themes that have installed isotope...

Maybe its a my error but i can not do many thing on code, i correctly assigned var instance to my calls.
Currently you can check error here( but its a clietn site and maybe will remove script asap) http://www.limburg-nieuws.nl/kalender/

Click on bottom button "laat meer evenementen zien"

Thank you!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. I appreciate you providing a live URL, but I'm having trouble reproducing the error. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by skiokko** [comment]
Hello,
Thank you for fast response!
I sure understand you, difficoult to explan and understand, and a test case
also I not able to do, due to problem appear after a AJAX call, and write a
code for all only for a test case is very too time.
But if you agree i can put online a dev demo site, with wordpress and X
theme, that is one of themes that generate the error, with installed my
plugin. After i send you FTP and i tell you exact js rows generate
proplems, so may be is a stupid problem and can be solved fast.

Let me know,
Thanks

2015-08-28 16:16 GMT+02:00 David DeSandro <notifications@github.com>:

**Comment by skiokko** [comment]
schiocco.com

Off Grid Adventures ( https://schiocco.com )

*****************************************
Let’s start building something together !
*****************************************

Welcome to Check out all my latest Envato products and get exclusive promotions and insights. Cheers and thanks for reading!

New theme available
-------------------

Codrop is an App Landing Page and One Page multipurpose WordPress Theme based on the Bootstrap 4 Grid System, Themekit and WPTF.

( https://1.envato.market/j6Yn6 )

Lot's of premium themes
-----------------------

Static templates
----------------

Premium plugins
---------------

Secret update ...
-----------------

I'm working on the new version of Support Board! It will be a brand new plugin built from scratch with impressive new features. This update is only for the subscribers of this newsletter.

Schiocco

Mindspace, Whitechapel High St 114 , London ,

Unsubscribe (  https://u12139260.ct.sendgrid.net/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcQGyCamDBa5aXmxPR6gvk4LYT1FRxvVLWui5Ikav-2FLu3ngf3KF9UqrDl1yiM7DoYzU5G8-2Fru1fPENQ7lMOEjmwKlZhIkRt-2FGihhqlbJXZskzv0rCTDxH-2BxXs-2FB-2F8pDKd17LGv3mg8d9kpc56BLAK23yjuUOa1XIULo3IPOG0IZWTrhD6q9WBdBlN8dVRnpCdtY1HGFMM8idoQc0rKffrhLJQtf-2B10WTg24QQtNQtdRijg9rTo-2F1eWpSX-2FgDeiA3AexLhedbHW4UCMBikEFmHQLIsx1dfwO814yG-2BvVLmyXrK1zRbP-2Bclt9I0DH8PTFeFg-2FD-2Bcgm3n0YufYqY4JRIlE3Md2ngRleHvq-2F-2BfDNUMA2PZwxWP15iyLahiihh-2BG7kpk2Y-2BYv8CNqtlloeWiha0nM0d9lIiTAMC3-2B1wjXbEK27rX9evvE0D-2BhJhGR5p0pN60OQZK24XgmBXJBNmvDWUgaOlChs79igRViLQA-2BAVGCZ07feRXuUevHix-2FX8gsiOTPEHn9LFMNT5MWEH01ZJ4Rro-2FkhK6VL2A1-2Fcy17IIkSIVp8Jejg0uX8Osgq3TAE-2FvsNiNFlxYh-2FCGrxmjZ-2Bourm4tAGTpQpMoJcX-2B9NOkexKjPfzRAzit3n-2BaEZXRIDivDMV1QTv1rri19K9k7-2FOU3cgkIo8hnkOmhqArxbQfrJcyus8-2FaaBGfqVU2juVxXnwA-3D-3D  )

© 2019 Schiocco. Visit schiocco.com ( https://schiocco.com ) to view all products.
