### ISSUE TITLE
Isotope Event on load/ on initializtion

### ISSUE THREAD

**Issue by skiokko** [metafizzy/isotope#975]
Hi,
Do you planned to add this event in future relase? 
Currently i must do a trick to trigger on load event. But it's not best way, and for me this event is required most of time (ex. hide masonry, due i can only after init, or edit via js maso boxes based on position)

Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. I'm having trouble understanding how you are trying to use this event. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
