### ISSUE TITLE
Browserify & Reactify — Uncaught TypeError: Cannot read property 'EventEmitter' of undefined

### ISSUE THREAD

**Issue by variable** [metafizzy/isotope#976]
I have a reactjs component which renders sub components and I would like to use isotope to display the subcomponents.

Whenever I include isotope into my jsx file, will cause 

    Uncaught TypeError: Cannot read property 'EventEmitter' of undefined

I am not sure what is wrong here.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Isotope. Did you install Isotope as an npm package?

``` bash
npm install isotope-layout
```

**Comment by variable** [comment]
Hi Desandro,

Yes, that's what I did.

**Comment by desandro** [comment]
Thanks for the code. I'm not sure how that `.call(undefined)` got added. It's `.call(this)` in [EventEmitter](https://github.com/Olical/EventEmitter/blob/v4.2.11/EventEmitter.js#L472) and [isotope.pkgd.js](https://github.com/metafizzy/isotope/blob/v2.2.2/dist/isotope.pkgd.js#L705).

Hopefully this is just an edge case. I'll keep this issue open to see if others run into it.

**Comment by variable** [comment]
It seems babelify is causing this problem. If I don't include babelify, it didn't create `.call(undefined);` in the packaged code.

**Comment by manveru** [comment]
Same issue is happening with phoenix when you `bower install isotope -S` and try using it via the default brunch setup.

**Comment by scriptist** [comment]
I'm experiencing the same issue, also with babelify.

**Comment by LeviBotelho** [comment]
Have you tried depending explicitly on `"wolfy87-eventemitter": "4.2.0"`?

**Comment by irisSchaffer** [comment]
+1 for requiring `"wolfy87-eventemitter": "4.2.0"` explicitly. Fixed the issue for us, using babelify!

**Comment by ariroseonline** [comment]
Having these issue as well with Browserify & Babelify (with React preset)...

Changing the wolfy87-eventmitter dependency is not a great long-term solution of course...

Any other proposed solutions?

**Comment by jedierikb** [comment]
_It feels like eventemitter is the proper place to file this, but as this thread has traction..._
Tried to use browserify and babel (es2015) and got same error for latest version of eventemitter (5).  Not using react.  Dead simple setup -- just trying to browserify that library.
Reverted to 4.2.0 from bower and working fine.

**Comment by desandro** [comment]
Isotope v3 was released and switched out the `wolfy87-eventemitter` dependency for `ev-emitter`. This issue should now be resolved.

**Comment by jedierikb** [comment]
Ah, nice to see a lightweight alternative.  I will open a ticket on eventemitter for their outstanding issue.

**Comment by desandro** [comment]
Closing this issue as resolve as `wolfy87-eventemitter` has been replaced by `ev-emitter` with Isotope v3. Please open a new issue if you run into another issue with Browserify & Reactify 🌈🐻
