### ISSUE TITLE
want to set the grid item in %age but I,m unable to do so

### ISSUE THREAD

**Issue by abdullah1908** [metafizzy/isotope#977]
Hy Sir,
I am using isotope layout complete event and I am unable to use the height and width of the grid item in %age.
When I set the height and width of the grid-item in %age it does not work for me.
Images not showing and also event layout complete not worked for me.

Kindly guide me ASAP.

Regards

Abdullah

Presstiger

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by abdullah1908** [comment]
Hy Desandro,
Thanks for your response.
Now, I am using Packery and it's working fine by using grid item width in %age.
But I am facing issue in Height either I have set it in %age or use fix it in pixels.
I have three different boxes with three different sizes as square,full square and rectangular and I am facing issue in the height and width I am using is in %age.

Thanks again for your instant help.

Regards
Abdullah
Presstugers.com
