### ISSUE TITLE
Isotope pushing items onto new line?

### ISSUE THREAD

**Issue by lspoor** [metafizzy/isotope#978]
Hi guys, setup isotope filter on a grid portfolio layout no problem but on this three col layout it is pushing the 3rd item onto a new line, any ideas whats causing this? The layout is absolutely fine before intialising Isotope..the code I'm using is...

See a live version here - http://lukespoor.co.uk/simplyinfinite/portfolio-filterable.html
This is a three col layout with no filter on - http://lukespoor.co.uk/simplyinfinite/portfolio.html

```javascript
$(window).load(function(){
    var $portfolioContainer = $('#portfolio');

    $portfolioContainer.isotope({
        filter: '*',
        animationOptions: {
            duration: 750,
            easing: 'linear',
            queue: false,
        }
    });

    $('#portfolio-nav a').click(function(){
        var selector = $(this).attr('data-filter');
        $portfolioContainer.isotope({
            filter: selector,
            animationOptions: {
                duration: 750,
                easing: 'linear',
                queue: false,
            }
        });
      return false;
    });

    var $optionSets = $('#portfolio-nav ul'),
       $optionLinks = $optionSets.find('a');
     
        $optionLinks.click(function(){
        var $this = $(this);
        // don't proceed if already selected
        if ( $this.hasClass('selected') ) {
            return false;
        }
        var $optionSet = $this.parents('.portfolio-nav ul');
        $optionSet.find('.selected').removeClass('selected');
        $this.addClass('selected'); 
    });
});
```

**Comment by desandro** [comment]
Try using [`gutter` option for Masonry layout mode](http://isotope.metafizzy.co/layout-modes/masonry.html#gutter), instead of nth-child margin.

Also, you can remove `animationOptions`. This [option was removed in Isotope v2](http://isotope.metafizzy.co/appendix.html#changes)

**Comment by lspoor** [comment]
Apologies! I added ‘position:relative’ to the parent container and it fixed it!
