### ISSUE TITLE
No touchscreen support?

### ISSUE THREAD

**Issue by vinuales** [metafizzy/isotope#980]
Hi people!

I've been doing well with isotope on desktop but at the moment to move to iphone/ipad realized that hover actions doesn't work.

Didn't see any touch event management on code. 

Is it planned to be included in a close future? Maybe I am doing something wrong?

Thanks! BR

**Comment by desandro** [comment]
Hello! Thanks for getting in touch. Can you specify what the issue is? Isotope does not have any functionality related to hover states.

**Comment by vinuales** [comment]
Hi @desandro!

Thanks for your quick response.

Maybe it is something to be controlled on our side, just asking. If you check some of links from "Isotope in use" from a touch screen device, you will see.

Example: Rimmel UK (http://uk.rimmellondon.com/products/all)
Hover behaviour on desktop, not available on touch device.

As I said, maybe is something not to be considered on Isotope library, it is not dragable. Just asking because it is on other libreries (owl carousel, and probably available on flickity).

Thanks in advance!

**Comment by desandro** [comment]
The hover behavior is implemented on the individual sites in their own CSS. It's completely separate from Isotope. You can implement hover or touch events however you like on top of Isotope functionality.
