### ISSUE TITLE
Removing of a filter

### ISSUE THREAD

**Issue by Jondeus** [metafizzy/isotope#981]
Hello,

I dunno if this is ok to ask a question like this in here but..

I've had some fun with isotope and bumped into a wall here.

In a nutshell I've made 3 groups of buttons. Each group of buttons
gives a different filter for isotope.

Now if a button from a group is clicked again, I'd want that one filter to get
cleared from the filters. And no I dont mean the filterValue = '*'; or
filters = {};
$grid.isotope({ filter: '*' });

Since those just clear everything. Lets say all 3 categories have been chosen
and now from the 2nd button group a already chosen button is clicked again,
that filtergroup should be set to all or reset or something but the 1st and 3rd
filtergroup should remain as they are.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
