### ISSUE TITLE
isotope search not working when backspace is pressed

### ISSUE THREAD

**Issue by Grey007** [metafizzy/isotope#982]
Hi, 

I am busy trying to implement search functionality on my site. On keyup press, it filters the correct items. Although, on backspace press, it does not clear the 'filter' so the search result remains. 

Here is my code: 

``` js
var qsRegex;
function initIsotope() {
iso = new Isotope(grid, {
        itemSelector: '.grid__item',
        percentPosition: true,
        filter: function () {
            return qsRegex ? $(this).text().match(qsRegex) : true;
        },
        masonry: {
            // use outer width of grid-sizer for columnWidth
            columnWidth: '.grid__sizer'
        },
        transitionDuration: '0.6s'
    });
}

var $quicksearch = $('#quicksearch').keyup(debounce( function() {
    qsRegex = new RegExp($quicksearch.val(), 'gi');
    initIsotope();
}));
```
   
I followed the following tutorial: http://codepen.io/desandro/pen/wfaGu to assist me. Although, I am using design by Code Drops and using an external js file to display the items.

**Comment by desandro** [comment]
The current code initializes a new `Isotope` instance in `initIsotope`. Instead, you want to trigger [`.arrange()`](http://isotope.metafizzy.co/methods.html#arrange-isotope) on the same Isotope instance. Since you're already using jQuery, let's initialize Isotope as a jQuery plugin.

``` js
var qsRegex;
var $grid = $(grid).isotope({
    itemSelector: '.grid__item',
    percentPosition: true,
    filter: function () {
        return qsRegex ? $(this).text().match(qsRegex) : true;
    },
    masonry: {
        // use outer width of grid-sizer for columnWidth
        columnWidth: '.grid__sizer'
    },
    transitionDuration: '0.6s'
});

var $quicksearch = $('#quicksearch').keyup(debounce( function() {
    qsRegex = new RegExp($quicksearch.val(), 'gi');
    $grid.isotope();
}));
```
