### ISSUE TITLE
Manipulate image tags when items not visible

### ISSUE THREAD

**Issue by Sawascwoolf** [metafizzy/isotope#984]
Hi,

I've read that your tool is slow when a huge set of data is filtered which has large images.

Wouldn't this be faster if you would manipulate image tags inside the hidden elements to something other than imagetag?

Example:
replace <img with <isotopeimg 
and the other way around when the item gets visible again.

**Comment by desandro** [comment]
Thanks for this feature request. There may be a benefit here, but I'm concerned that changing HTML tags would have other consequences. Isotope shouldn't mess with the DOM too much. Sorry, but I'll have to pass on this one.
