### ISSUE TITLE
Support: How to always transition elements on filtering

### ISSUE THREAD

**Issue by eads** [metafizzy/isotope#986]
I'd like to provide visual feedback a filter was applied, even for elements that are already visible. I've been playing around with applying the isotope filtering twice, but that causes some problems given the architecture of the thing I'm building. Any ideas about how to do this elegantly?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
