### ISSUE TITLE
Filtering lag on iOS

### ISSUE THREAD

**Issue by Charbrec** [metafizzy/isotope#987]
Running Isotope using 4 filters on ~65 items. We're encountering a ~3s delay when using iOS devices (iPhone 6/iPad Air tested). There is zero delay across all desktop browsers (Windows/OS X), and Android browsers (Mobile/Tablet). This is only occurring on iOS devices.

When a user selects a filter, there is roughly a 3s delay before the filter state changes, and the isotope items are filtered. Since there is a delay in the button state change, this is leading to users assuming the button click was unregistered; they either click it again, or leave the page entirely. 

I'm curious if others have encountered such issues on iOS, or if this is limited to my implementation. 

[View live here](http://www.royalbrush.com/stealth/brush-finder) 
Login/PW: isotope

[Video showing error](https://youtu.be/E6jwGHKe9rM)

**Comment by desandro** [comment]
The delay may be caused by the 300ms delay for emulated `click` events on touch devices. See http://updates.html5rocks.com/2013/12/300ms-tap-delay-gone-away You may want to try [FastClick](https://github.com/ftlabs/fastclick)
