### ISSUE TITLE
Isotope synchronous growth item and repositioning items

### ISSUE THREAD

**Issue by HTML-master** [metafizzy/isotope#990]
I'm trying to adjust a plugin isotope for the needs of my project. I need to synchronously reposition the items inside the container by increasing its height. The height is increased by the plugin jQuery-Collapse (http://webcloud.se/jQuery-Collapse/) when clicking on items inside the container. Here the fiddle:

http://jsfiddle.net/adzpx1k6/12/

As seen in the example with increasing height elements located below - little jump up at recalculation position. It is necessary to avoid it.I would be grateful for any help!

**Comment by desandro** [comment]
Because the item size is determined by the size of the content, we can't use the [technique covered in the docs](http://isotope.metafizzy.co/appendix.html#animating-item-size). Sorry, but this behavior is the most suitable in this scenario.
