### ISSUE TITLE
Firefox v.24 broken layout

### ISSUE THREAD

**Issue by oleksii-s** [metafizzy/isotope#991]
Got this issue just with several old versions of firefox like v.24.  
Usually (for other browsers and latest FF versions) library calculates top and left positions of each element in container. In mentioned FF version library calculates just value for css property 'top', but property 'left' for each element is set to 0. So that's why items are displayed one above the other, such as a column, rather than displayed as a row using correct value of property 'left'

HTML:
```
<div class="view views-tiles">
   <div class="view-content">
        <div class="grid-size"></div>
        <div class="views-row views-row-1 views-row-odd views-row-first" >...</div>
        ...
        <div class="views-row views-row-1 views-row-odd views-row-first" >...</div>
   </div>
</div>
```
JS:
```javascript
var $container = $('.views-tiles > .view-content');

if ($container.length) {
        $container.imagesLoaded(function() {
          window.tiles = new Isotope('.views-tiles > .view-content', {
            itemSelector: '.views-row',
            layoutMode: 'masonry',
            masonry: {
              columnWidth: '.grid-size'
            },
            transitionDuration: 0
          });
        });
}
```
Thanks

**Comment by desandro** [comment]
Thanks for reporting this issue. Old [firefox usage is less than a tenth of 1%](http://caniuse.com/usage-table). `wontfix` for this one.
