### ISSUE TITLE
Filter Animation - CustomTransition

### ISSUE THREAD

**Issue by dukizuki** [metafizzy/isotope#992]
Hi,

I want to make better transitions on filtering like on this site: http://demo.select-themes.com/stockholm6/three-column-grid-no-space/

I looked on js code and looks like they are using some intervals to clear default isotope transition duration and add their custom, but I can't understand how to trick like that. Can you provide a code snippet to help me to disable default transition and add my custom?

Thanks in advance :)

**Comment by desandro** [comment]
Thanks for submitting this issue. The best way to achieve this effect is to use [`hiddenStyle` and `visibleStyle` options](http://isotope.metafizzy.co/options.html#hiddenstyle-visiblestyle) to only set `scale`. See demo http://codepen.io/desandro/pen/ojpZLM

``` js
  var $container = $('.isotope').isotope({
    itemSelector: '.element-item',
    layoutMode: 'fitRows',
    transitionDuration: '0.8s',
    // only scale for reveal/hide transition
    hiddenStyle: {
      transform: 'scale(0.001)'
    },
    visibleStyle: {
      transform: 'scale(1)'
    }
  });
```
