### ISSUE TITLE
Multiple Stamped Items (Packery Layout)

### ISSUE THREAD

**Issue by peterph-am** [metafizzy/isotope#993]
Hi David,

This is more of a query than issue,
I'm trying to create this layout: 

```
|-----------|-----|-----|
|           |  1  |  1  |
|     4     |-----|-----|
|           |  1  |  1  |
|-----|-----|-----|-----|
|  1  |  1  |           |
|-----|-----|     4     |
|  1  |  1  |           |
|-----|-----|-----|-----|
|           |  1  |  1  |
|     4     |-----|-----|
|           |  1  |  1  |
|-----|-----|-----|-----|
```

Where the 4 sized items are the stamped ones with the other items flowing around them.

What would be the best way to do this? I've tried just css which is fine for the left and right position but the top position I can't rely on the nth-of-type selector to grab the correct element

Cheers,
Pete

**Comment by desandro** [comment]
Thanks for reporting this issue. No need to use stamps, you can arrange the items in HTML to produce this kind of layout. See demo http://codepen.io/desandro/pen/gavZaB

``` html
<div class="grid">
  <div class="grid-item grid-item--large"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>

  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item grid-item--large"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>

  <div class="grid-item grid-item--large"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>

</div>
```

**Comment by peterph-am** [comment]
This is cool, however I can't always predict/control the order of the html cause of ordering/filter and the CMS control of the client.

If i change the markup order slightly i get this: http://codepen.io/anon/pen/QjmMmW

Is it possible to always make sure the layout is like this: 

```
|-----------|-----|-----|
|           |  1  |  1  |
|     4     |-----|-----|
|           |  1  |  1  |
|-----|-----|-----|-----|
|  1  |  1  |           |
|-----|-----|     4     |
|  1  |  1  |           |
|-----|-----|-----|-----|
|           |  1  |  1  |
|     4     |-----|-----|
|           |  1  |  1  |
|-----|-----|-----|-----|
```

**Comment by desandro** [comment]
Yes, you can use stamps. See http://codepen.io/desandro/pen/avYROq
