### ISSUE TITLE
Isotope change my colume position

### ISSUE THREAD

**Issue by BuiVietHuong** [metafizzy/isotope#996]
I am Vietnamese, so sorry about English grammar.
I have a issue when using Isotope is it change my column position.

Before: http://i.imgur.com/CupXQuH.png

After and both side not equal: http://i.imgur.com/bwzJc7t.png
I am trying viewsource and saw that each item has added position: absolute. I'm trying delete position: absolute of item but it display not beautiful, it's not impossible. Please help me.

**Comment by desandro** [comment]
Isotope uses absolute positioning to position the items. I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by BuiVietHuong** [comment]
I send you my project, please help me! :)
https://github.com/BuiVietHuong/ricons03
