### ISSUE TITLE
Stamped items repeating with infinite scroll

### ISSUE THREAD

**Issue by leanda** [metafizzy/isotope#998]
Hi

I'm using Isotope filtering with Infinite Scroll, but I have a problem where stamped items, the filter and other elements are repeated when more posts are loaded. Any ideas how I might prevent this? I feel as if I'm doing something really stupid.

Here's the example I'm working on:
http://www.cambridgerules1848.com/dev/

Thanks

**Comment by leanda** [comment]
It's always the way, you spend 2hrs trying to solve a problem, give in and ask for help and then immediately the fine the solution.

For anybody else who struggles with this issue, it's a simple matter of excluding the items in the infinite scroll itemSelector.

```
 $container.infinitescroll({
    "nextSelector":".nav-links .nav-previous a",
    "navSelector":".nav-links",
    "itemSelector":".item:not(.stamp)",
    loading: {
      finishedMsg: 'No more items to load.',
      img: 'http://i.imgur.com/qkKy8.gif'
    }
  }, function (newElements) {
    $container.isotope('insert', $(newElements));
  });
```

**Comment by desandro** [comment]
Thanks for following up!
