### ISSUE TITLE
How to add and remove a blank space under stampt element

### ISSUE THREAD

**Issue by ipetrov87** [metafizzy/isotope#999]
I am using BOOTSTRAP and ISOTOPE to make a filtering in group of elements. I have a collapse button (red cell in example) to hide and show filters. My idea is after I open a collapsed filters to get a blank white space under a red cell all the way to the bottom, and instead a 3 green cols they should become to only 2.After I collapse the filters it should become again in 3 green cols. Here is example of my code https://jsfiddle.net/tqLdre3s/2/

**Comment by desandro** [comment]
How about setting the height of the filter box https://jsfiddle.net/tqLdre3s/3/

**Comment by ipetrov87** [comment]
Thank you for response. Your solution is not exactly what i want. If you select "All" with your solution will look like this [this](http://s4.postimg.org/vjdkmwhh9/screenshot_jsfiddle_net_2015_11_08_15_31_50.png), my idea was to make look like [this](http://s8.postimg.org/7shlhiv9h/screenshot_jsfiddle_net_2015_11_08_15_31_501.png).

**Comment by desandro** [comment]
I'll leave that detail up to you!
